//[filtros|Text,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,]
-- SELECT 

DECLARE @FILTRO VARCHAR(MAX) = ISNULL(:filtros, '')
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @CONVERTCODE INT = <#SESSION.CONVERTCODE/>

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_DESCARTADAS @IDUSUARIO,@IDEMPRESA,@CONVERTCODE,@FILTRO,0