//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,filtros|Text,]
--SELECT

DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @CONVERTCODE INT
DECLARE @FILTROS VARCHAR(MAX)
SET @IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @CONVERTCODE=<#SESSION.CONVERTCODE/>
SET @FILTROS=ISNULL(:FILTROS,'')


EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ACTIVIDADES_FECHAS @IDUSUARIO,@IDEMPRESA,@CONVERTCODE,@FILTROS