//[session.idempresa|Untyped,]
DECLARE @ANIO INT
DECLARE @MES INT
DECLARE @IDEMPRESA INT

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SELECT @ANIO = YEAR (GETDATE())
SELECT @MES = MONTH (GETDATE())

DECLARE @META MONEY

SELECT  @META= ISNULL (SUM (M.META),50000) FROM EMPRESAS_METAS M WHERE M.IDEMPRESA=@IDEMPRESA AND M.ANIO = @ANIO AND M.MES = @MES

SELECT @META AS META, E.* 
FROM  EMPRESAS_ESTADISTICAS E WHERE E.IDEMPRESA=@IDEMPRESA
