//[session.idempresa|Untyped,session.idusuario|Untyped,f|Integer,paises|Text,session.db|Untyped,]
--SELECT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @FILTRO INT
DECLARE @PAISES VARCHAR(MAX)
SET @FILTRO = ISNULL(:F,0)
SET @PAISES = ISNULL(:PAISES,'') 

/*ETIQUETAS*/
IF @FILTRO = 1
BEGIN 
	 SELECT ETI.TK AS idOpcion, ETI.ETIQUETA AS opcion 
	 FROM <#SESSION.DB/>.DBO.ETIQUETAS ETI
	 WHERE ETI.IDEMPRESA = @IDEMPRESA ORDER BY opcion
END


/*FASES PROSPECTOS*/
IF @FILTRO = 2
BEGIN
	 SELECT TK AS idOpcion, FASE AS opcion 
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
	 WHERE IDEMPRESA = @IDEMPRESA  AND FASECLIENTE = 0 ORDER BY FASECLIENTE, ORDEN
END

/*FASES CLIENTES*/
IF @FILTRO = 3
BEGIN
	 SELECT TK AS idOpcion, FASE AS opcion 
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
	 WHERE IDEMPRESA = @IDEMPRESA  AND FASECLIENTE = 1 ORDER BY FASECLIENTE, ORDEN
END

/*ORIGENES*/
IF @FILTRO = 4
BEGIN
	 SELECT TK AS idOpcion, ORIGEN AS opcion
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES 
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY ORIGEN
END

/*País*/
IF @FILTRO = 5
BEGIN
	 SELECT IDPAIS AS idOpcion, PAIS AS opcion 
	 FROM <#SESSION.DB/>.DBO.PAISES 
	 ORDER BY PAIS
END

/*ESTADO*/
IF @FILTRO = 6
BEGIN
	 DECLARE @NPAIS INT
	 SELECT @NPAIS = COUNT(*) FROM SALESUP_CT.dbo.SPLIT(@PAISES, '|')
	 
	 SELECT E.IDESTADO AS idOpcion, E.ESTADO + CASE WHEN @NPAIS > 1 THEN ' - ('+P.PAIS+')' ELSE '' END AS opcion
	 FROM dbo.ESTADOS E JOIN <#SESSION.DB/>.DBO.PAISES P ON P.IDPAIS = E.IDPAIS
	 WHERE E.IDPAIS IN (SELECT SPLITVALUE FROM SALESUP_CT.dbo.SPLIT(@PAISES, '|')) 
	 ORDER BY E.IDPAIS, E.ESTADO
	 
END


/*INDUSTRIA*/
IF @FILTRO = 7
BEGIN
	 SELECT TKIND AS idOpcion, INDUSTRIA AS opcion
	 FROM <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY INDUSTRIA ASC
END

/*Corporativo*/
IF @FILTRO = 8
BEGIN
	 SELECT TKCG AS idOpcion, COMPANIAGRUPO AS opcion 
	 FROM <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY COMPANIAGRUPO ASC
END
 
 
