//[irepcon|Integer,session.idempresa|Untyped,session.db|Untyped,]
--update
DECLARE @IDREPORTECONFIGURACION INT
SET @IDREPORTECONFIGURACION = CAST(ISNULL(:irepcon,0) AS INT)

DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


DELETE FROM <#SESSION.DB/>.dbo.REPORTE_FILTROS WHERE IDREPORTEPASO IN (
	SELECT IDREPORTEPASO FROM <#SESSION.DB/>.dbo.REPORTE_PASOS  WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION
)
DELETE FROM <#SESSION.DB/>.dbo.REPORTE_PASOS WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION

DELETE FROM <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION AND IDEMPRESA = @IDEMPRESA
