//[session.idempresa|Untyped,session.idusuario|Untyped,irepcon|Text,n|Text,g|Text,u|Text,t|Text,a|Integer,p|Integer,r|Integer,session.db|Untyped,]
-- UPDATE
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @NOMBRE VARCHAR(MAX), @IDGRUPOS VARCHAR(MAX),@IDUSUARIOS VARCHAR(MAX), @TODOS VARCHAR(2)
DECLARE @AGRUPARPOR INT, @PERIODICIDAD INT, @IDREPORTE INT, @IDREPORTECONFIGURACION INT

SET @IDREPORTECONFIGURACION = CAST(:irepcon AS INT)
SET @NOMBRE = :N
SET @IDGRUPOS = ISNULL(:G,'0')
SET @IDUSUARIOS = ISNULL(:U,'0')
SET @TODOS = ISNULL(:T,'')
SET @AGRUPARPOR = ISNULL(:A,0)
SET @PERIODICIDAD = ISNULL(:P,0)
SET @IDREPORTE = ISNULL(:R,0)

SET @NOMBRE = <#SESSION.DB/>.dbo.NombreReporteCofiguracionesConversiones (@NOMBRE, @IDEMPRESA,@IDREPORTECONFIGURACION)

IF(@TODOS = '0')
BEGIN
	SET @IDGRUPOS = 0
	SET @IDUSUARIOS = 0
END

UPDATE <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES
SET 
NOMBRE = @NOMBRE, 
AGRUPARPOR = @AGRUPARPOR, 
PERIODICIDAD = @PERIODICIDAD, 
IDGRUPOS_COMPARTIDOS = @IDGRUPOS,
IDUSUARIOS_COMPARTIDOS = @IDUSUARIOS
WHERE IDEMPRESA = @IDEMPRESA AND IDREPORTECONFIG = @IDREPORTECONFIGURACION

/*SE BORRA LA CONFIGURACION ANTERIOR PARA INSERTAR LA NUEVA*/

DELETE FROM <#SESSION.DB/>.dbo.REPORTE_FILTROS WHERE IDREPORTEPASO IN (SELECT IDREPORTEPASO FROM <#SESSION.DB/>.dbo.REPORTE_PASOS  WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION)
DELETE FROM <#SESSION.DB/>.dbo.REPORTE_PASOS WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION

