//[idreporte|Integer,session.db|Untyped,session.idusuario|Untyped,]
--SELECT

/*PROTEGIDO*/

DECLARE @IDREPORTE INT
DECLARE @IDUSUARIO INT 

SET @IDREPORTE =ISNULL(:IDREPORTE, 0) 
SET @IDUSUARIO='<#SESSION.IDUSUARIO/>'
SELECT SQLTXT FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE 