//[d|Text,rc|Integer,p|Integer,universo|Integer,naturaleza|Integer,session.db|Untyped,]
-- SELECT

DECLARE @IDREPORTECONFIGURACION INT, @IDREPORTEPASO INT, @PASO INT, @UNIVERSO INT, @NATURALEZA INT
DECLARE @DESCRIPCION VARCHAR(MAX)

SET @DESCRIPCION = ISNULL(:D,'')
SET @IDREPORTECONFIGURACION = ISNULL(:RC,0)
SET @PASO = ISNULL(:P,0)
SET @UNIVERSO = ISNULL(:UNIVERSO,0)
SET @NATURALEZA = ISNULL(:NATURALEZA,0)

IF(@UNIVERSO = 0)
BEGIN
	 SET @UNIVERSO = NULL
END

IF(@NATURALEZA = 0)
BEGIN
	 SET @NATURALEZA = 1
END

 DECLARE @FROMADICIONAL VARCHAR(256)
 DECLARE @SELECTADICIONAL VARCHAR(256)
 DECLARE @OPERADORADICIONAL VARCHAR(256)
 
  SELECT TOP 1 @OPERADORADICIONAL = OPERADORADICIONAL, @FROMADICIONAL = FROMADICIONAL, 
  @SELECTADICIONAL = SELECTADICIONAL FROM SALESUP_CT.dbo.TIPOS_FILTROS WHERE NATURALEZA = @NATURALEZA AND CATE = 0
 
INSERT INTO <#SESSION.DB/>.dbo.REPORTE_PASOS
	( IDREPORTECONFIG, PASO, DESCRIPCION,UNIVERSO,NATURALEZA, FROMADICIONAL, SELECTADICIONAL,OPERADORADICIONAL)
VALUES 
	( @IDREPORTECONFIGURACION, @PASO, @DESCRIPCION,@UNIVERSO,@NATURALEZA, @FROMADICIONAL, @SELECTADICIONAL,@OPERADORADICIONAL)

SELECT TOP 1 @IDREPORTEPASO = IDREPORTEPASO 
FROM <#SESSION.DB/>.dbo.REPORTE_PASOS 
WHERE IDREPORTECONFIG = @IDREPORTECONFIGURACION AND PASO = @PASO AND DESCRIPCION = @DESCRIPCION 
ORDER BY IDREPORTEPASO DESC

SELECT @IDREPORTEPASO AS iRePa, @IDREPORTECONFIGURACION AS RC, @PASO AS P,@UNIVERSO AS UNIVERSO, @NATURALEZA AS NATURALEZA

