//[irepcon|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDREPORTECONFIG INT, @IDEMPRESA INT

SET @IDREPORTECONFIG = CAST(ISNULL(:iRepCon,0) AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT RF.IdReportePaso, RF.Descripcion, RF.Categoria, RF.Tipo, RF.Valor, RF.Operador, RP.Paso,RP.Universo
FROM <#SESSION.DB/>.dbo.REPORTE_FILTROS RF 
LEFT JOIN <#SESSION.DB/>.dbo.REPORTE_PASOS RP ON RF.IDREPORTEPASO = RP.IDREPORTEPASO 
WHERE RP.IDREPORTECONFIG = @IDREPORTECONFIG

