//[session.idempresa|Untyped,session.idusuario|Untyped,n|Text,g|Text,u|Text,t|Text,a|Integer,p|Integer,r|Integer,session.db|Untyped,]
-- SELECT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @NOMBRE VARCHAR(MAX), @IDGRUPOS VARCHAR(MAX),@IDUSUARIOS VARCHAR(MAX), @TODOS VARCHAR(2)
DECLARE @AGRUPARPOR INT, @PERIODICIDAD INT, @IDREPORTE INT, @IDREPORTECONFIGURACION INT

SET @NOMBRE = :N
SET @IDGRUPOS = ISNULL(:G,'0')
SET @IDUSUARIOS = ISNULL(:U,'0')
SET @TODOS = ISNULL(:T,'')
SET @AGRUPARPOR = CAST(:A AS INT)
SET @PERIODICIDAD = CAST(:P AS INT)
SET @IDREPORTE = CAST(:R AS INT)




IF(@TODOS = '0')
BEGIN
	SET @IDGRUPOS = 0
	SET @IDUSUARIOS = 0
END

SET @NOMBRE = <#SESSION.DB/>.dbo.NombreReporteCofiguracionesConversiones (@NOMBRE, @IDEMPRESA,0)

INSERT INTO <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES
	(IDEMPRESA, IDUSUARIO, NOMBRE, AGRUPARPOR, PERIODICIDAD, IDGRUPOS_COMPARTIDOS, IDREPORTE,IDUSUARIOS_COMPARTIDOS)
VALUES 
	(@IDEMPRESA, @IDUSUARIO, @NOMBRE, @AGRUPARPOR, @PERIODICIDAD, @IDGRUPOS, @IDREPORTE,@IDUSUARIOS)
	
SELECT TOP 1 @IDREPORTECONFIGURACION = IDREPORTECONFIG 
FROM <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES
WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND NOMBRE = @NOMBRE
ORDER BY IDREPORTECONFIG DESC

SELECT @IDREPORTECONFIGURACION AS iReCon