//[nombrereporte|Text,idreporteconfig|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--select
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @IDREPORTECONFIG INT
DECLARE @NOMBREREPORTE VARCHAR(MAX)
SET @NOMBREREPORTE=:NOMBREREPORTE
SET @IDREPORTECONFIG=CAST(ISNULL(:IDREPORTECONFIG,0) AS INT)
SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)

EXEC <#SESSION.DB/>.DBO.SP_DUPLICA_REPORTE_CONFIGURACIONES_CONVERSIONES @IDREPORTECONFIG,@NOMBREREPORTE,@IDUSUARIO,@IDEMPRESA