//[irepcon|Integer,session.idempresa|Untyped,session.nivel|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDREPORTECONFIG INT, @IDEMPRESA INT, @IDUSUARIO INT, @NIVEL INT, @IDGRUPO INT

SET @IDREPORTECONFIG = CAST(isnull(:iRepCon,0) AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @NIVEL = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)


SELECT RC.Nombre, RC.AgruparPor, RC.Periodicidad, RC.IdGrupos_Compartidos AS IdGrupos, RC.IDUSUARIOS_COMPARTIDOS AS IdUsuarios,@IDREPORTECONFIG as iRepCon,
CASE 
WHEN (@NIVEL = 1 OR @IDUSUARIO = RC.IDUSUARIO) THEN '1' 
WHEN (@NIVEL = 2 AND U.IDGRUPO = @IDGRUPO AND U.NIVEL != 1) THEN '1' 
ELSE '' 
END As PuedeEditar
FROM <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES RC
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = RC.IDUSUARIO AND U.IDEMPRESA = @IDEMPRESA 
WHERE RC.IDREPORTECONFIG = @IDREPORTECONFIG AND RC.IDEMPRESA = @IDEMPRESA
