//[session.idempresa|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.db|Untyped,]
-- select

DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @IDGRUPO INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>

SELECT IDREPORTECONFIG, NOMBRE, AGRUPARPOR, DESISTEMA
 FROM <#SESSION.DB/>.DBO.REPORTES_CONFIGURACIONES WHERE IDEMPRESA = @IDEMPRESA AND (IDUSUARIO = @IDUSUARIO OR (IDGRUPOS_COMPARTIDOS = '0' 
OR @IDGRUPO IN (SELECT SPLITVALUE FROM DBO.SPLIT(IDGRUPOS_COMPARTIDOS,','))))
AND IDREPORTE = 1
 ORDER BY DESISTEMA DESC,NOMBRE
