//[razon|Text,tipo|Integer,session.db|Untyped,session.idempresa|Untyped,tk|Text,]
--update
DECLARE @RAZONPERDIDA VARCHAR(1000)
DECLARE @TKRAZONPERDIDA VARCHAR(256)
DECLARE @TIPO INT

SET @RAZONPERDIDA = CAST(ISNULL(:RAZON,'') AS VARCHAR(1000))
SET @TKRAZONPERDIDA = ISNULL(:TK, '') 
SET @TIPO = CAST(ISNULL(:TIPO,0) AS INT)

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA SET RAZONPERDIDA = @RAZONPERDIDA, TIPO = @TIPO WHERE TK = @TKRAZONPERDIDA AND IDEMPRESA = <#SESSION.IDEMPRESA/>