//[aeliminar|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @AELIMINAR varchar(256)
SET @AELIMINAR=ISNULL(:AELIMINAR,'')
SELECT IDRAZONPERDIDA, IDEMPRESA, RAZONPERDIDA, TIPO, ULTIMAMODIFICACION, TK, TKM,
SALESUP_CT.dbo.esCanalizado(TK, TKM) AS esCanalizado 
FROM <#SESSION.DB/>.dbo.EMPRESAS_RAZONES_PERDIDA 
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND TK!=@AELIMINAR
and tipo=(select tipo from <#SESSION.DB/>.dbo.EMPRESAS_RAZONES_PERDIDA where TK=@AELIMINAR)
ORDER BY RAZONPERDIDA  
