//[session.db|Untyped,session.idempresa|Untyped,tk|Text,]
--SELECT 
/*PROTEGIDO*/
/*SEP2015*/
SELECT * FROM  <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA
WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND TK = ISNULL(:TK,'')
order by IDRAZONPERDIDA DESC