//[id2|Integer,id1|Integer,session.db|Untyped,session.idempresa|Untyped,tkeliminar|Text,tknuevo|Text,]
-- DELETE
DECLARE @RAZON INT
DECLARE @IDRAZON INT
DECLARE @TKELIMINAR VARCHAR(256) 
DECLARE @TKNUEVO VARCHAR(256) 
DECLARE @IDELIMINAR INT 
DECLARE @IDNUEVO INT 

SET @TKELIMINAR=ISNULL(:TKELIMINAR, '') 
SET @TKNUEVO=ISNULL(:TKNUEVO, '') 

SELECT @IDELIMINAR = IDRAZONPERDIDA FROM <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA WHERE TK=@TKELIMINAR
SELECT @IDNUEVO = IDRAZONPERDIDA FROM <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA WHERE TK=@TKNUEVO





INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) 
VALUES (20,@IDNUEVO,@IDELIMINAR,1,<#SESSION.IDEMPRESA/>,GETDATE())

UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES 
SET IDRAZONPERDIDA = @IDNUEVO,CAMBIOLOCAL=(CASE WHEN TKOM IS NOT NULL THEN 1 ELSE 0 END) 
WHERE IDRAZONPERDIDA = @IDELIMINAR

DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA 
WHERE IDRAZONPERDIDA = @IDELIMINAR AND IDEMPRESA = <#SESSION.IDEMPRESA/>


