//[session.idempresa|Untyped,session.idusuario|Untyped,sp_host|Untyped,session.db|Untyped,]
--SELECT

DECLARE @TOKEN VARCHAR(256)
DECLARE @IDEMPRESA INT
DECLARE @LINK VARCHAR(MAX)
DECLARE @HOST VARCHAR(MAX)
DECLARE @CLAVE VARCHAR(MAX)
DECLARE @IDUSUARIO INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @HOST= 'bidatos.salesup.com.mx'
SET @TOKEN = CAST(left(NEWID(),10) AS VARCHAR(256))
SET @CLAVE = 'PASS123'
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

exec <#session.db/>.[dbo].uspRandChars @len=10, @output=@CLAVE out

SELECT @CLAVE = SALESUP_CT.DBO.VARCHARTOBASE64(@CLAVE);

SELECT @TOKEN =  cast(@idempresa as varchar(1000))+REPLACE(@TOKEN, '-', '')



	    SELECT @LINK = LINK+'.'+DATA_BASE+'.'
		FROM CONTROL.CONTROL.DBO.SERVIDORESDB S, CONTROL.CONTROL.DBO.BASES_CONTEO B, 
		CONTROL.CONTROL.DBO.USUARIOS U, CONTROL.CONTROL.DBO.EMPRESAS E 
		WHERE U.IDUSUARIO=@IDUSUARIO AND E.IDEMPRESA=@IDEMPRESA
		AND U.IDEMPRESA=E.IDEMPRESA 
		AND E.BD_ACTUAL COLLATE DATABASE_DEFAULT = B.DATA_BASE COLLATE DATABASE_DEFAULT 
		AND S.IDSERVIDORDB= B.IDSERVIDORDB


IF NOT EXISTS(SELECT * FROM bi.REPORTES_EXTERNOS.DBO.REPORTES_EXTERNOS WHERE IDEMPRESA=@IDEMPRESA)
   BEGIN 
	
	INSERT INTO bi.REPORTES_EXTERNOS.DBO.REPORTES_EXTERNOS (IDEMPRESA, IDUSUARIO, TOKEN, ACTIVO, ULTIMA_SINCRONIZACION, SERVIDOR, LINK, PROCESADO, CLAVE)
	VALUES (@IDEMPRESA, @IDUSUARIO, @TOKEN, 1, NULL,@HOST , @LINK, 0,@CLAVE) 

   END
 
 	SELECT *,
 		CASE WHEN ULTIMA_SINCRONIZACION IS NULL THEN 'Nunca' ELSE CONVERT(VARCHAR(10), ULTIMA_SINCRONIZACION, 103) END AS ULTIMA_SINCRONIZACION_FINAL, SALESUP_CT.DBO.ObtieneHora(ULTIMA_SINCRONIZACION) as hora,
 		SALESUP_CT.DBO.BASE64TOVARCHAR(CLAVE) AS PASSWORD
	FROM bi.REPORTES_EXTERNOS.DBO.REPORTES_EXTERNOS WHERE IDEMPRESA=@IDEMPRESA
	