//[session.idusuario|Untyped,session.idempresa|Untyped,filtros|Text,]
--SELECT 	

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @FILTROSR VARCHAR(MAX) = ISNULL(:FILTROS,'')
SET @FILTROSR = REPLACE(@FILTROSR,'"ventaRC":"2"','"ventaRC":"1"')
SET @FILTROSR = REPLACE(@FILTROSR,'"ventaNR":"5"','"ventaNR":"4"')

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_VENTAS_REALIZADAS_COBRADAS @IDUSUARIO,@IDEMPRESA,@FILTROSR,1,0