//[session.idusuario|Untyped,session.idempresa|Untyped,tipo|Integer,periodo|Integer,parametros|Text,moneda|Text,actividad|Integer,mes|Integer,session.db|Untyped,]
-- Select
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @TIPO INT = ISNULL(:TIPO,0)
DECLARE @PERIODO INT = ISNULL(:PERIODO,0)
DECLARE @PARAMETROS VARCHAR(MAX) = ISNULL(:PARAMETROS,'')
DECLARE @MONEDA VARCHAR(MAX) = ISNULL(:MONEDA,'')
DECLARE @ACTIVIDAD INT = ISNULL(:ACTIVIDAD,0)
DECLARE @MES INT = ISNULL(:MES,1)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_VENTAS_DETALLE_EXPORTAR @IDUSUARIO, @IDEMPRESA, @TIPO, @PERIODO,@PARAMETROS,@MONEDA,@ACTIVIDAD,@MES