//[session.db|Untyped,session.idempresa|Untyped,]
DECLARE @LISTA_ANIOS TABLE
(
  ANIO INT
)
 
DECLARE @ANIO INT
DECLARE @PROXIMOS INT

SET @PROXIMOS = YEAR(GETDATE())+2
SELECT @ANIO = MIN(YEAR(V.FECHAHORA)) FROM <#SESSION.DB>.dbo.USUARIOS U LEFT JOIN <#SESSION.DB>.dbo.VENTAS V ON U.IDUSUARIO = V.IDUSUARIO WHERE U.IDEMPRESA = <#SESSION.IDEMPRESA/>
IF (@ANIO IS NULL)
BEGIN
	SET @ANIO = YEAR(GETDATE())
END
WHILE @ANIO<=@PROXIMOS
BEGIN
    INSERT INTO @LISTA_ANIOS VALUES (@ANIO)
    SET @ANIO=@ANIO+1       
END
SELECT * FROM @LISTA_ANIOS