//[session.idusuario|Untyped,session.idempresa|Untyped,filtros|Text,]
--SELECT 	

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @FILTROSR VARCHAR(MAX) = ISNULL(:FILTROS,'')

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_VENTAS_REALIZADAS_COBRADAS @IDUSUARIO,@IDEMPRESA,@FILTROSR,1,1