//[session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,canalizarprospecto|Text,empresadestino|Text,idejecutivo|Text,nombreempresadestino|Text,idprospecto|Text,tkp|Text,cm|Text,session.nombre|Untyped,session.apellidos|Untyped,session.iniciales|Untyped,comentariocanaliza|Text,session.compania|Untyped,session.db|Untyped,iddelacuenta|Integer,]
--INSERT
DECLARE @IDCUENTA INT
DECLARE @IDEMPRESA_ORIGEN INT, @IDUSUARIO_ORIGEN INT, @IDEJECUTIVO INT, @CANALIZAR INT, @CONVERTCODE INT
DECLARE @IDPROSPECTO_ORIGEN INT, @IDEMPRESA_DESTINO INT, @CanalizaManual INT
declare @TKP varchar(max), @NOMBRE_EMPRESA_DESTINO VARCHAR(MAX), @SUCESO varchar(max), @NOMBREUSUARIO VARCHAR(MAX)
DECLARE @ComentarioCanaliza VARCHAR(MAX), @SEGUIMIENTOCANALIZADO VARCHAR(MAX)
DECLARE @EXITO INT
SET @EXITO=1
SET @IDEMPRESA_ORIGEN = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO_ORIGEN = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @CANALIZAR = CAST(ISNULL(:CanalizarProspecto,'') AS INT)
SET @IDEMPRESA_DESTINO = CAST(ISNULL(:EmpresaDestino,'') AS INT)
SET @IDEJECUTIVO = CAST(ISNULL(:IDEJECUTIVO,'') AS INT)
SET @NOMBRE_EMPRESA_DESTINO = :NombreEmpresaDestino
SET @IDPROSPECTO_ORIGEN = CAST(ISNULL(:IDPROSPECTO,'') AS INT)
SET @IDCUENTA = ISNULL(:idDeLaCuenta,0)

SET @TKP = dbo.ValidaToken(ISNULL(:TKP,''))

SET @CanalizaManual = CAST(ISNULL(:CM,'') AS INT)
SET @NOMBREUSUARIO = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.INICIALES/>)'
IF @NOMBRE_EMPRESA_DESTINO IS NULL BEGIN SET @NOMBRE_EMPRESA_DESTINO = '' END
SET @ComentarioCanaliza = ISNULL(:ComentarioCanaliza,'')
SET @SEGUIMIENTOCANALIZADO = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.COMPANIA/>) recanalizó un contacto a ' + @NOMBRE_EMPRESA_DESTINO 
SET @SUCESO = 'Contacto recanalizado a ' + @NOMBRE_EMPRESA_DESTINO + ', por '+ @NOMBREUSUARIO

IF @CANALIZAR = 1
BEGIN
	 
	 BEGIN TRY
	   EXEC <#SESSION.DB/>.dbo.SP_RECANALIZAR_UN_PROSPECTO_IDUENTA @IDEMPRESA_ORIGEN, @IDEMPRESA_DESTINO, @IDPROSPECTO_ORIGEN, @IDUSUARIO_ORIGEN,@IDCUENTA
	 END TRY
	 BEGIN CATCH
	  SET @EXITO=0
	 END CATCH
	 IF (@EXITO=1)
	 	BEGIN
			 /*seguimiento manual */
	 		 IF @ComentarioCanaliza != '' BEGIN INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)VALUES(@IDPROSPECTO_ORIGEN, @IDUSUARIO_ORIGEN, @ComentarioCanaliza, 0) END
	 
	 		 /*Seguimiento de inicio de recanalizacion*/
	 		 INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)VALUES(@IDPROSPECTO_ORIGEN, @IDUSUARIO_ORIGEN, @SEGUIMIENTOCANALIZADO, 0)
	 
	 		 /*reasignar prospecto*/
	  		 IF @IDUSUARIO_ORIGEN != @IDEJECUTIVO BEGIN EXEC <#SESSION.DB/>.dbo.SP_REASIGNAR_PROSPECTO_AUTOMATICO @IDEMPRESA_ORIGEN, @IDUSUARIO_ORIGEN, @IDEJECUTIVO, @IDPROSPECTO_ORIGEN, @CONVERTCODE END

	  END
END
