//[session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,canalizarprospecto|Integer,empresadestino|Integer,idejecutivo|Integer,nombreempresadestino|Text,idprospecto|Integer,tkp|Text,cm|Integer,cp_manual|Integer,session.nombre|Untyped,session.apellidos|Untyped,session.iniciales|Untyped,comentariocanaliza|Text,session.compania|Untyped,session.db|Untyped,iddelacuenta|Integer,]
--INSERT
/*PROTEGIDO*/
DECLARE @IDEMPRESA_ORIGEN INT, @IDUSUARIO_ORIGEN INT, @IDEJECUTIVO INT, @CANALIZAR INT, @CONVERTCODE INT
DECLARE @IDPROSPECTO_ORIGEN INT, @IDEMPRESA_DESTINO INT, @CanalizaManual INT
declare @TKP varchar(max), @NOMBRE_EMPRESA_DESTINO VARCHAR(MAX), @SUCESO varchar(max), @NOMBREUSUARIO VARCHAR(MAX)
DECLARE @ComentarioCanaliza VARCHAR(MAX), @SEGUIMIENTOCANALIZADO VARCHAR(MAX)
DECLARE @EXITO INT, @MANUAL INT
DECLARE @IDCUENTA INT

SET @EXITO=1
SET @IDEMPRESA_ORIGEN = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO_ORIGEN = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @CANALIZAR = ISNULL(:CanalizarProspecto,0) 
SET @IDEMPRESA_DESTINO = ISNULL(:EmpresaDestino,0)
SET @IDEJECUTIVO = ISNULL(:IDEJECUTIVO,0)
SET @NOMBRE_EMPRESA_DESTINO = :NombreEmpresaDestino
SET @IDCUENTA = ISNULL(:idDeLaCuenta,0)
SET @IDPROSPECTO_ORIGEN = ISNULL(:IDPROSPECTO,0)
SET @TKP = ISNULL(:TKP,'')
SET @CanalizaManual = ISNULL(:CM,0)
SET @MANUAL = ISNULL(:cp_Manual,0)
SET @NOMBREUSUARIO = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.INICIALES/>)'
IF @NOMBRE_EMPRESA_DESTINO IS NULL BEGIN SET @NOMBRE_EMPRESA_DESTINO = '' END
SET @ComentarioCanaliza = ISNULL(:ComentarioCanaliza,'')
SET @SEGUIMIENTOCANALIZADO = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.COMPANIA/>) canalizó un contacto a ' + @NOMBRE_EMPRESA_DESTINO 
SET @SUCESO = 'Contacto canalizado a ' + @NOMBRE_EMPRESA_DESTINO + ', por '+ @NOMBREUSUARIO
IF @TKP != '' BEGIN SET @IDPROSPECTO_ORIGEN = CAST(<#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP,  @IDEMPRESA_ORIGEN) AS VARCHAR(MAX)) END

IF @CanalizaManual > 0 
BEGIN
	  UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET
	  CAMBIOLOCAL = 1, 
	  USRCANALIZO = @NOMBREUSUARIO, 
	  CANALIZADOEL = GETDATE(), 
	  ULTIMAMODIFICACION = GETDATE()
	  WHERE ( IDPROSPECTO = @IDPROSPECTO_ORIGEN OR TKP = @TKP ) AND IDEMPRESA = @IDEMPRESA_ORIGEN
END

IF @CANALIZAR = 1
BEGIN
	/*seguimiento manual */
    IF @ComentarioCanaliza != '' BEGIN INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)VALUES(@IDPROSPECTO_ORIGEN, @IDUSUARIO_ORIGEN, @ComentarioCanaliza, 0) END
	 
	/*Seguimiento de inicio de canalizacion*/
	 INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)VALUES(@IDPROSPECTO_ORIGEN, @IDUSUARIO_ORIGEN, @SEGUIMIENTOCANALIZADO, 1)
	 
	 /*reasignar prospecto*/
	 IF @IDUSUARIO_ORIGEN != @IDEJECUTIVO BEGIN EXEC <#SESSION.DB/>.dbo.SP_REASIGNAR_PROSPECTO_AUTOMATICO @IDEMPRESA_ORIGEN, @IDUSUARIO_ORIGEN, @IDEJECUTIVO, @IDPROSPECTO_ORIGEN, @CONVERTCODE END
	 
	 DELETE FROM <#SESSION.DB/>.dbo.CANALIZACIONES WHERE IDPROSPECTO = @IDPROSPECTO_ORIGEN AND IDEMPRESA = @IDEMPRESA_ORIGEN
	 INSERT INTO <#SESSION.DB/>.dbo.CANALIZACIONES(IDEMPRESA, IDUSUARIO, IDPROSPECTO, IDUSUARIO_REASIGNACION, DISTRIBUIDOR)
	 VALUES(@IDEMPRESA_ORIGEN, @IDUSUARIO_ORIGEN, @IDPROSPECTO_ORIGEN, @IDEJECUTIVO, @NOMBRE_EMPRESA_DESTINO)
	 
	 EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO_ORIGEN, 57, @IDPROSPECTO_ORIGEN, 0, @SUCESO, ''

 	 EXEC <#SESSION.DB/>.[dbo].[SP_ACTUALIZA_CANALIZACION_PROSPECTOS_CONTROL_IDCUENTA] @IDEMPRESA_ORIGEN, @IDEMPRESA_DESTINO, @IDPROSPECTO_ORIGEN, @Manual, @IDCUENTA
 	
END
