//[session.idempresa|Untyped,industria|Text,session.db|Untyped,tkindustria|Text,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDEMPRESA INT 
DECLARE @TKIND VARCHAR(256) 
DECLARE @NOMBRE_INDUSTRIA VARCHAR(MAX) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TKIND =ISNULL(:TKINDUSTRIA, '') 
SET @NOMBRE_INDUSTRIA=ISNULL(:INDUSTRIA, '') 

UPDATE  <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS SET INDUSTRIA =@NOMBRE_INDUSTRIA WHERE IDEMPRESA = IDEMPRESA and TKIND=@TKIND