//[tkeliminar|Text,tknuevo|Text,session.db|Untyped,session.idempresa|Untyped,]
-- DELETE

DECLARE @TKELIMINAR VARCHAR(256) 
DECLARE @TKNUEVO VARCHAR(256) 
DECLARE @IDELIMINAR INT 
DECLARE @IDNUEVO INT 

SET @TKELIMINAR=ISNULL(:TKELIMINAR, '') 
SET @TKNUEVO =ISNULL(:TKNUEVO, '') 

SELECT @IDELIMINAR =IDINDUSTRIA FROM <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS WHERE TKIND=@TKELIMINAR
SELECT @IDNUEVO =IDINDUSTRIA FROM <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS WHERE TKIND=@TKNUEVO

UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDINDUSTRIA = @IDNUEVO, ULTIMAMODIFICACION = GETDATE() WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDINDUSTRIA = @IDELIMINAR
UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET IDINDUSTRIA = @IDNUEVO WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDINDUSTRIA = @IDELIMINAR

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (26,@IDNUEVO,@IDELIMINAR,1,<#SESSION.IDEMPRESA/>,GETDATE())

DELETE FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> and IDINDUSTRIA=@IDELIMINAR


DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 