//[session.idempresa|Untyped,session.db|Untyped,]
-- SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>

SELECT M.IDEMPRESAMONEDA, CTM.MONEDA+'('+ M.IDMONEDA +')' AS MONEDA, CTM.MONEDA_SIMBOLO, CAST(M.TK AS VARCHAR(64)) as tk
FROM <#SESSION.DB/>.DBO.MONEDAS M
LEFT JOIN SALESUP_CT.dbo.MONEDAS CTM ON M.IDMONEDA = CTM.IDMONEDA
WHERE IDEMPRESA = @IDEMPRESA AND STATUS = 1
GROUP BY M.IDEMPRESAMONEDA, CTM.MONEDA, CTM.MONEDA_SIMBOLO, M.IDMONEDA, M.TK