//[session.idempresa|Untyped,session.db|Untyped,]
-- UPDATE
/*PROTEGIDO*/

DECLARE @TOTALMONEDAS INT = 0
DECLARE @IDPAIS VARCHAR(16)
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @IDEMPRESAMONEDA INT

SELECT @TOTALMONEDAS = COUNT(*) FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA = @IDEMPRESA

IF(@TOTALMONEDAS = 0)
BEGIN
	SELECT @IDPAIS = PAIS_DEFAULT FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA	
	INSERT INTO <#SESSION.DB/>.DBO.MONEDAS (M.IDMONEDA,TIPODECAMBIO,IDEMPRESA,PORDEFECTO,STATUS) SELECT M.IDMONEDA,'1.00',@IDEMPRESA,1,1 FROM MONEDAS M, PAISES_MONEDAS PM WHERE PM.IDPAIS = @IDPAIS AND M.IDMONEDA = PM.IDMONEDA
	
	SELECT TOP 1 @IDEMPRESAMONEDA = IDEMPRESAMONEDA FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA = @IDEMPRESA AND PORDEFECTO = 1
		
	UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES SET IDEMPRESAMONEDA = @IDEMPRESAMONEDA WHERE IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDEMPRESA = @IDEMPRESA) AND IDEMPRESAMONEDA IS NULL
	UPDATE <#SESSION.DB/>.DBO.VENTAS SET IDMONEDA = @IDEMPRESAMONEDA WHERE IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDEMPRESA = @IDEMPRESA) AND IDMONEDA IS NULL
END

UPDATE <#SESSION.DB/>.DBO.EMPRESAS SET MULTIMONEDA_ACTIVADO = 1 WHERE IDEMPRESA = @IDEMPRESA
