//[session.idempresa|Untyped,session.db|Untyped,SP_CURRENCYSTRING|Text]
--SELECT

DECLARE @MONEDASIMBOLO VARCHAR(MAX)
SET @MONEDASIMBOLO = :SP_CURRENCYSTRING

DECLARE @MONEDADEFAULT VARCHAR(128)

SELECT @MONEDADEFAULT = UNICODE(CTM.MONEDA_SIMBOLO) 
FROM SALESUP_CT.DBO.MONEDAS CTM
LEFT JOIN <#SESSION.DB/>.dbo.MONEDAS M ON M.IDMONEDA = CTM.IDMONEDA
WHERE M.IDEMPRESA = <#SESSION.IDEMPRESA/> AND M.PORDEFECTO = 1

IF @MONEDADEFAULT IS NULL SET @MONEDADEFAULT = UNICODE(@MONEDASIMBOLO)

SELECT @MONEDADEFAULT AS MONEDA_SIMBOLO
