//[session.idempresa|Untyped,session.idusuario|Untyped,tkdb|Text,session.db|Untyped,]
--select 
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @TKDB VARCHAR(MAX)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>

SET @TKDB = ISNULL(:TKDB,'')

SELECT dashBoard, compartido, 
CASE 
WHEN COMPARTIDO = 2 THEN GRUPOS_COMPARTIDOS
WHEN COMPARTIDO = 3 THEN USUARIOS_COMPARTIDOS
ELSE '' END tks
FROM <#SESSION.DB/>.dbo.DASHBOARD 
WHERE TKDB = @TKDB
