//[tk|Text,session.db|Untyped,]
--SELECT
DECLARE @TKDBCONF VARCHAR(64), @SQLARMADO VARCHAR(MAX)
SET @TKDBCONF = ISNULL(:TK,'')

SELECT @SQLARMADO = SQL_ARMADO 
FROM <#SESSION.DB/>.dbo.DASHBOARD_CONFIGURACION 
WHERE TKDBCONF = @TKDBCONF

EXEC (@SQLARMADO)

