//[session.idempresa|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.tku|Untyped,session.db|Untyped,session.nivel|Untyped,]
--SELECT 

DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @IDGRUPO INT, @NIVEL INT
DECLARE @TKU VARCHAR(MAX), @TKG VARCHAR(MAX)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @NIVEL = <#SESSION.NIVEL/>
SET @TKU = '<#SESSION.TKU/>'

SELECT @TKG = TK FROM <#SESSION.DB/>.dbo.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO = @IDGRUPO 

SELECT CASE WHEN IDUSUARIO = @IDUSUARIO OR @NIVEL = 1 THEN 1 ELSE 0 END AS pModificar, dashBoard, CAST(tkdb AS VARCHAR(MAX)) AS tkdb, orden 
FROM <#SESSION.DB/>.dbo.DASHBOARD
WHERE IDEMPRESA = @IDEMPRESA AND ( IDUSUARIO = @IDUSUARIO OR COMPARTIDO = 1 OR USUARIOS_COMPARTIDOS LIKE '%'+@TKU+'%' OR GRUPOS_COMPARTIDOS LIKE '%'+@TKG+'%' ) 
ORDER BY IDUSUARIO, ORDEN


