//[tkdb|Text,tamanio|Integer,tituloindicador|Text,jconfiguracion|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @DB VARCHAR(MAX)

DECLARE @TAMANIO INT
DECLARE @TITULO VARCHAR(MAX), @JCONFIGURACION VARCHAR(MAX), @TKDB VARCHAR(64)

SET @TKDB = ISNULL(:TKDB,'')
SET @TAMANIO = ISNULL(:TAMANIO,1)
SET @TITULO = SALESUP_CT.DBO.PreparaCadena(ISNULL(:tituloIndicador,''))
SET @JCONFIGURACION = ISNULL(:JCONFIGURACION,'')

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @DB = '<#SESSION.DB/>'

EXEC <#SESSION.DB/>.DBO.SP_DASHBOARD_NUEVO_INDICADOR @DB, @IDEMPRESA, @IDUSUARIO, @TKDB, @TITULO, @TAMANIO, @JCONFIGURACION 




