//[idprospecto|Integer,tkp|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT

DECLARE @IDPROSPECTO INT
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)

declare @tkp varchar(max)

SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, <#SESSION.IDEMPRESA/>) END


SELECT cast(FI.TKFI as varchar(64)) AS tkfi, @TKP as tkp, FI.*, VM.MES AS MESES, UP.DESCRIPCION
FROM <#SESSION.DB/>.dbo.FECHAS_IMPORTANTES FI
LEFT JOIN <#SESSION.DB/>.dbo.V_MESES VM ON VM.IDMES = FI.MES
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_PLANTILLAS UP ON UP.IDPLANTILLA = FI.IDPLANTILLA
WHERE IDPROSPECTO = @IDPROSPECTO ORDER BY FI.MES, FI.DIA