//[tk|Text,vencimiento|Integer,idaccion|Integer,tipofase|Integer,recordatorio|Text,session.db|Untyped,]
--insert

DECLARE @TK VARCHAR(MAX) 
DECLARE @VENCIMIENTO INT 
DECLARE @IDACCION INT 
DECLARE @TIPOFASE INT 
DECLARE @RECORDATORIO VARCHAR(MAX) 
DECLARE @IDFASE INT  

SET @TK= ISNULL(:TK, '') 
SET @VENCIMIENTO = ISNULL(:VENCIMIENTO, 0) 
SET @IDACCION=ISNULL(:IDACCION, 0) 
SET @TIPOFASE=ISNULL(:TIPOFASE, 0) 
SET @RECORDATORIO=ISNULL(:RECORDATORIO, 0) 
IF(@TIPOFASE=1) 
 SELECT @IDFASE =IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE TK=@TK
ELSE  IF(@TIPOFASE=2)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TK 
ELSE IF(@TIPOFASE=3)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES  WHERE TK=@TK AND FASECLIENTE=1

INSERT INTO <#SESSION.DB/>.dbo.ACCIONES_FASES (IDFASE,IDACCION,TIPOFASE,RECORDATORIO,TIPOPARA,TIPOCC,TIPOCCO,VENCIMIENTO)
 VALUES (@IDFASE,@IDACCION,@TIPOFASE,@RECORDATORIO,0,0,0,@VENCIMIENTO)