//[tk|Text,session.db|Untyped,idaccion|Integer,tipofase|Integer,plantilla|Integer,para|Text,cc|Text,cco|Text,tipopara|Integer,tipocc|Integer,tipocco|Integer,]
--insert
DECLARE @TK VARCHAR(256) 
DECLARE @IDFASE INT 
DECLARE @IDACCION INT 
DECLARE @TIPOFASE INT 
DECLARE @PLANTILLA INT 
DECLARE @PARA VARCHAR(128) 
DECLARE @CC VARCHAR(128) 
DECLARE @CCO VARCHAR(128) 
DECLARE @TIPOPARA INT 
DECLARE @TIPOCC INT 
DECLARE @TIPOCCO INT 



SET @TK=ISNULL(:TK, '')
SET @TIPOFASE=ISNULL(:TIPOFASE, 0)
IF(@TIPOFASE=1)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE TK=@TK
ELSE  IF(@TIPOFASE=2)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TK 
ELSE IF(@TIPOFASE=3)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES  WHERE TK=@TK AND FASECLIENTE=1

SET @IDACCION=ISNULL(:IDACCION, 0) 
SET @PLANTILLA=ISNULL(:PLANTILLA, 0) 
SET @PARA =ISNULL(:PARA , '') 
SET @CC =ISNULL(:CC, '') 
SET @CCO=ISNULL(:CCO, '')
SET @TIPOPARA=ISNULL(:TIPOPARA, 0) 
SET @TIPOCC=ISNULL(:TIPOCC, 0) 
SET @TIPOCCO=ISNULL(:TIPOCCO, 0) 



INSERT INTO <#SESSION.DB/>.dbo.ACCIONES_FASES (IDFASE,IDACCION,TIPOFASE,IDPLANTILLA,PARA,CC,CCO,TIPOPARA,TIPOCC,TIPOCCO)
 VALUES (@IDFASE,@IDACCION,@TIPOFASE,@PLANTILLA,@PARA,@CC,@CCO,@TIPOPARA,@TIPOCC,@TIPOCCO)