//[session.nivel|Untyped,session.db|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,]
IF <#SESSION.NIVEL/> = 1
  SELECT * FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND ACTIVO=1
  ORDER BY APELLIDOS, NOMBRE
ELSE
  SELECT * FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND (IDGRUPO=<#SESSION.IDGRUPO/> OR NIVEL <=2) AND ACTIVO=1
  ORDER BY APELLIDOS, NOMBRE

