//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,f_usuario|Text,]
-- SELECT
  DECLARE @DESCARTADO TINYINT
  DECLARE @SQL VARCHAR(MAX)
  DECLARE @F_USUARIO VARCHAR(MAX)
  
  SET @F_USUARIO = ISNULL(:F_USUARIO,'') 
  SET @DESCARTADO=CAST ('0' AS INT)

  SET @SQL='
  SELECT TOP 5
    P.TKP,<#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,
    P.NOMBRE,    P.CORREO, fase,fechacontacto, 
   ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR, A.ARCHIVADO,  
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO,
    F.FASE, F.ORDEN,CAST (COMENTARIOS AS VARCHAR(128))+''...'' AS INTRO, U.INICIALES, U.NOMBRE+'' ''+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
    <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHACONTACTO) AS FECHA_CONTACTO,
    P.ETIQUETAS_TXT AS ETIQUETAS, A.IDUSUARIO AS USUARIO, O.ORIGEN,
   (CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO,
   (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO,
   (U1.INICIALES) AS ULTIMO_CONTACTO_USUARIO,'''+@F_USUARIO+''' AS F_USUARIO
   
  FROM  
  <#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK) 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A  WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO AND A.IDUSUARIO = <#SESSION.IDUSUARIO/>
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F  WITH(NOLOCK) ON P.IDFASE = F.IDFASE
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S  WITH(NOLOCK) ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES  O  WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  JOIN <#SESSION.DB/>.DBO.USUARIOS U1  WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO     
  JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO    
  WHERE  
    (P.IDEMPRESA = <#SESSION.IDEMPRESA/>)  '+@F_USUARIO+' 
     AND P.DESCARTADO='+CAST(@DESCARTADO AS VARCHAR(1000))+' AND (P.ESOPORTUNIDAD=0 OR (TKPM IS NOT NULL AND TKPM != TKP)) AND REASIGNADO = 1 AND A.ARCHIVADO = 0 AND P.ESCLIENTE=0
  ORDER BY FECHA_ULTIMOSEGUIMIENTO DESC
  '
  EXEC (@SQL)