//[tk|Text,session.idempresa|Untyped,fasetipo|Integer,session.db|Untyped,]
--SELECT 

DECLARE @TK VARCHAR(256) 
DECLARE @IDFASE INT 
DECLARE @IDEMPRESA INT 
DECLARE @TIPOFASE INT 

SET  @TK=ISNULL(:TK, '') 
SET  @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET  @TIPOFASE=ISNULL(:FASETIPO, 0) 

IF(@TIPOFASE=1)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA   AND TK=@TK
IF(@TIPOFASE=2) 
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA=@IDEMPRESA AND TK=@TK
IF(@TIPOFASE=3) 
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA AND FASECLIENTE=1 AND TK=@TK


--SELECT @IDFASE
  SELECT af.*,UP.DESCRIPCION FROM <#SESSION.DB/>.dbo.ACCIONES_FASES aF
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_PLANTILLAS UP ON UP.IDPLANTILLA = AF.IDPLANTILLA
  WHERE AF.IDFASE=@IDFASE --AND AF.TIPOFASE=@TIPOFASE
  ORDER BY IDACCIONFASE ASC

