//[tk|Text,session.idempresa|Untyped,session.db|Untyped,fasetipo|Integer,]
--SELECT 

DECLARE @TK VARCHAR(256) 
DECLARE @IDFASE INT 
DECLARE @IDEMPRESA INT 
DECLARE @FASETIPO INT 

SET @TK=ISNULL(:TK , '') 
SELECT @IDEMPRESA=<#SESSION.IDEMPRESA/>
--SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA= @IDEMPRESA AND TK=@TK 
SET @FASETIPO=ISNULL(:FASETIPO, 0) 

IF(@FASETIPO=1)
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA  /*AND FASECLIENTE=1 */ AND TK=@TK
IF(@FASETIPO=2) 
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA=@IDEMPRESA AND TK=@TK
IF(@FASETIPO=3) 
 SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA AND FASECLIENTE=1 AND TK=@TK

SELECT COUNT(*) AS TOTACCIONES 
FROM <#SESSION.DB/>.dbo.ACCIONES_FASES 
WHERE IDFASE=@IDFASE AND TIPOFASE= @FASETIPO