//[distribucion|Integer,canalizacion|Integer,tipo|Integer,session.db|Untyped,session.idempresa|Untyped,]
-- select

DECLARE @TIPODISTRIBUCION INT
DECLARE @TIPOCANALIZACION INT
DECLARE @TIPO INT
DECLARE @IDUSUARIO INT

SET @TIPODISTRIBUCION = ISNULL(:DISTRIBUCION,0)
SET @TIPOCANALIZACION = ISNULL(:CANALIZACION,0)
SET @TIPO = ISNULL(:TIPO,0)

IF(@TIPO = 0)
BEGIN
	IF(@TIPODISTRIBUCION = 0)
	BEGIN
		SELECT (NOMBRE + ' ' + APELLIDOS + ' (' + INICIALES +')') as usuarios,* 
	 	FROM 
	 	<#SESSION.DB/>.DBO.EMPRESA_DISTRIBUCION_PROSPECTOS P, 
	 	<#SESSION.DB/>.DBO.USUARIOS U 
	 	 WHERE U.IDEMPRESA = <#SESSION.IDEMPRESA/>
	 	 AND U.IDUSUARIO = P.IDUSUARIO AND U.ACTIVO = 1 AND TIPO_DISTRIBUCION = 0
	 	 ORDER BY IDDISTRIB
	END
	ELSE
	BEGIN
	 	 SELECT @IDUSUARIO = IDUSUARIO_DISTRIBUCION FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
	 
	 	 SELECT  (NOMBRE + ' ' + APELLIDOS + ' (' + INICIALES +')') as usuarios FROM <#SESSION.DB/>.DBO.USUARIOS  WHERE IDUSUARIO = @IDUSUARIO AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND ACTIVO = 1 
	END
END
ELSE
BEGIN
	 IF(@TIPOCANALIZACION = 0)
	 BEGIN
	 	  SELECT (NOMBRE + ' ' + APELLIDOS + ' (' + INICIALES +')') as usuarios,* 
		  FROM 
	 	  <#SESSION.DB/>.DBO.EMPRESA_DISTRIBUCION_PROSPECTOS P, 
	 	  <#SESSION.DB/>.DBO.USUARIOS U 
	 	  WHERE U.IDEMPRESA = <#SESSION.IDEMPRESA/>
	 	  AND U.IDUSUARIO = P.IDUSUARIO AND U.ACTIVO = 1 AND TIPO_DISTRIBUCION = 1
	 	  ORDER BY IDDISTRIB
	END
	ELSE
	BEGIN
	 	 SELECT @IDUSUARIO = IDUSUARIO_CANALIZACION FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
	 
	 	 SELECT  (NOMBRE + ' ' + APELLIDOS + ' (' + INICIALES +')') as usuarios FROM <#SESSION.DB/>.DBO.USUARIOS  WHERE IDUSUARIO = @IDUSUARIO AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND ACTIVO = 1 
	END
END