//[id_etq|Integer,session.db|Untyped,i_etiqueta|Integer,]
--update 
DECLARE @id_etq INT
DECLARE @i_etiqueta INT
SET @id_etq = ISNULL(:id_etq,0)
SET @i_etiqueta = ISNULL(:i_etiqueta,0)

IF @id_etq != 0
BEGIN
 UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS SET IDETIQUETA = @id_etq WHERE IDETIQUETA = @i_etiqueta
 AND IDPROSPECTO NOT IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS WHERE IDETIQUETA = @id_etq)
 
 UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL SET IDETIQUETA = @id_etq WHERE IDETIQUETA = @i_etiqueta
 UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS SET IDETIQUETA = @id_etq WHERE IDETIQUETA = @i_etiqueta
 
END
  
DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS  WHERE IDETIQUETA = @i_etiqueta
DELETE FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE IDETIQUETA = @i_etiqueta
