//[session.idempresa|Untyped,etiqueta|Text,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @EXISTE INT
DECLARE @ETIQUETA VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @ETIQUETA = <#SESSION.DB/>.dbo.PreparaCadena(:ETIQUETA)
SET @EXISTE = 0

SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.ETIQUETAS WHERE IDEMPRESA = @IDEMPRESA AND ETIQUETA = @ETIQUETA
	   
IF @EXISTE = 0
BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.ETIQUETAS(IDEMPRESA, ETIQUETA) VALUES (@IDEMPRESA, @ETIQUETA)
END

SELECT TOP 1 IDETIQUETA AS Id FROM <#SESSION.DB/>.dbo.ETIQUETAS WHERE IDEMPRESA = @IDEMPRESA AND ETIQUETA = @ETIQUETA ORDER BY 1 DESC