//[session.idempresa|Untyped,session.db|Untyped,session.idusuario|Untyped]
--SELECT
DECLARE @idusuario INT = <#SESSION.IDUSUARIO/>
declare @idempresa int = <#SESSION.IDEMPRESA/>
DECLARE @ACCION INT = 2 /*0 ES DATOS, 1 ES PENETRACION*/
EXEC <#SESSION.DB/>.DBO.SP_REPORTE_VENTAS_CRUZADAS @IDEMPRESA,@IDUSUARIO,@ACCION
--EXEC ARQUIMEDES.SALESUP_VIPDB4.DBO.SP_REPORTE_VENTAS_CRUZADAS 40629,58936,@ACCION