//[session.idempresa|Untyped,session.db|Untyped,session.idusuario|Untyped,tipovariante|Integer,lavariante|Text,inicia|Integer,length|Integer,filtros|Text,fecha1|Text, fecha2|Text, tipo|Integer]
--SELECT
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @VARIANTE VARCHAR(64), @TIPO_VARIANTE INT,@ACCION INT, @TOP VARCHAR(MAX), @FILTROS VARCHAR(MAX), @FECHA1 varchar(max), @FECHA2 varchar(max), @TIPO INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = ISNULL(<#SESSION.IDUSUARIO/>,0)
DECLARE @INICIA INT
SET @INICIA = ISNULL(:inicia,0)
IF(@INICIA > 0)
BEGIN
	SET @TOP = 'TOP '+CAST(@INICIA+50-1 AS VARCHAR)+' '
END
ELSE
BEGIN
	SET @TOP = ''
END
SET @VARIANTE = ISNULL(:lavariante,'')
SET @TIPO_VARIANTE = ISNULL(:tipovariante,1)
SET @ACCION = 0
SET @FILTROS = ISNULL(:filtros,'')
SET @FECHA1 = ISNULL(:fecha1,GETDATE())
SET @FECHA2 = ISNULL(:fecha2,GETDATE())
SET @TIPO = ISNULL(:tipo,0)



EXEC <#SESSION.DB/>.DBO.SP_REPORTE_DETALLE_GANADASVSPERDIDAS @IDUSUARIO, @IDEMPRESA, @VARIANTE , @TIPO_VARIANTE, @ACCION, @TOP, @FILTROS, @FECHA1, @FECHA2, @TIPO