//[session.idempresa|Untyped,session.db|Untyped,session.idusuario|Untyped,tipovariante|Integer,lavariante|Text,inicia|Integer,length|Integer,filtros|Text ]
--SELECT
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @VARIANTE VARCHAR(64), @TIPO_VARIANTE INT,@ACCION INT, @TOP VARCHAR(MAX), @FILTROS VARCHAR(MAX)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = ISNULL(<#SESSION.IDUSUARIO/>,0)
SET @TOP = ''
SET @VARIANTE = ISNULL(:lavariante,'16B94E7D-E62F-4BF1-A44B-19F7A998A372')
SET @TIPO_VARIANTE = ISNULL(:tipovariante,1)
SET @ACCION = 1
SET @FILTROS = ISNULL(:filtros,'')



EXEC <#SESSION.DB/>.DBO.SP_REPORTE_GEOLOCALIZACION @IDUSUARIO, @IDEMPRESA, @VARIANTE , @TIPO_VARIANTE, @ACCION, @TOP, @FILTROS