//[tkrs|Text,session.idusuario|Untyped,session.db|Untyped,session.tku|Untyped,session.idgrupo|Untyped,]
--SELECT
DECLARE @TKRS VARCHAR(MAX)
DECLARE @IDREPORTE INT, @IDUSUARIO INT, @IDGRUPO INT
DECLARE @TBVARIANTES TABLE(tkRsv VARCHAR(64), idVariante INT, variante VARCHAR(MAX), criteriosVisibles VARCHAR(MAX), sistema INT, totalizar INT, editar INT ) 
DECLARE @TKG VARCHAR(64), @TKU VARCHAR(64)

SET @TKRS = ISNULL(:TKRS, '')
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @TKU = '<#SESSION.TKU/>'
SET @IDGRUPO = '<#SESSION.IDGRUPO/>'

SELECT @TKG = CAST(TK AS VARCHAR(64)) FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO = @IDGRUPO

SELECT @IDREPORTE = IDREPORTE 
FROM SALESUP_CT.DBO.REPORTES_SISTEMA 
WHERE TKRS = @TKRS

INSERT INTO @TBVARIANTES (tkRsv, idVariante, variante, criteriosVisibles, sistema )
SELECT CAST(tkRsv AS VARCHAR(MAX)) AS tkRsv, idVariante, variante, criteriosVisibles, 1 as sistema
FROM SALESUP_CT.DBO.REPORTES_SISTEMA_VARIANTES
WHERE IDREPORTE = @IDREPORTE 
ORDER BY ORDEN

INSERT INTO @TBVARIANTES (tkRsv, idVariante, variante, criteriosVisibles, sistema, totalizar, editar )
SELECT CAST(TKURV AS VARCHAR(64)), idreportevariante*-1, variante, criteriosVisibles, 0, TOTALIZAR, CASE WHEN IDUSUARIO = @IDUSUARIO THEN 1 ELSE 0 END
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE 
IDREPORTE = @IDREPORTE
AND (	
		   ( IDUSUARIO = @IDUSUARIO )
		OR ( COMPARTIDO = 1 )
		OR ( COMPARTIDO = 2 AND @TKG IN ( SELECT SPLITVALUE FROM DBO.SPLIT(COMPARTIDOCON,',') ) )
		OR ( COMPARTIDO = 3 AND @TKU IN ( SELECT SPLITVALUE FROM DBO.SPLIT(COMPARTIDOCON,',') ) )
	)

SELECT * FROM @TBVARIANTES