//[tkrsv|Text,session.db|Untyped,]
--UPDATE
DECLARE @TKURV VARCHAR(MAX)
DECLARE @IDREPORTEVARIANTE INT

SET @TKURV = ISNULL(:TKRSV, '')

SELECT @IDREPORTEVARIANTE = IDREPORTEVARIANTE 
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE TKURV = @TKURV

DELETE 
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_FILTROS_ADICIONALES 
WHERE IDREPORTEVARIANTE = @IDREPORTEVARIANTE

DELETE
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE IDREPORTEVARIANTE = @IDREPORTEVARIANTE