//[SESSION.DB|Untyped, SESSION.IDUSUARIO|Untyped,SESSION.CONVERTCODE|Untyped, filtros|Text,SESSION.IDEMPRESA|Untyped]
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @CONVERTCODE INT
DECLARE @FILTROS VARCHAR(MAX)

SET @FILTROS    = ISNULL(:FILTROS,'')
SET @IDUSUARIO  = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA  = <#SESSION.IDEMPRESA/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

EXEC <#SESSION.DB/>.dbo.SP_GUARDA_FILTROS_REPORTES @IDUSUARIO, @IDEMPRESA, @FILTROS, @CONVERTCODE