//[session.idempresa|Untyped,session.db|Untyped,tk|Text]
-- SELECT 
DECLARE @TK VARCHAR(255)
DECLARE @IDEMPRESA INT

SET @TK = ISNULL(:TK,'');
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT TOP 1 TK,LINEA_PRODUCTO,COMISION*100 as COMISION FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE IDEMPRESA = @IDEMPRESA AND TK LIKE @TK