//[session.idempresa|Untyped,session.db|Untyped,]
-- SELECT 

DECLARE @IDEMPRESA INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT TK,MARCA /*,IDMARCA*/ FROM <#SESSION.DB/>.DBO.MARCAS WHERE IDEMPRESA = @IDEMPRESA  