//[session.db|Untyped,listaids|Text,tipo|Integer,accion|Integer,cantidad|Integer,preciosactualizar|Text,]
--update
DECLARE @TKPRODUCTOS AS VARCHAR(MAX) 
DECLARE @TIPO AS INT 
DECLARE @ACCION AS INT
DECLARE @SIGNO AS VARCHAR(max)
DECLARE @PRECIOSACTUALIZAR AS VARCHAR(MAX)
DECLARE @CANTIDAD AS FLOAT 
DECLARE @TABLATEMP AS TABLE (ID INT IDENTITY,INDICEPRECIO VARCHAR(max))
DECLARE @TO AS INT, @TOTAL AS  INT
DECLARE @INDICEPRECIO AS VARCHAR(MAX)
DECLARE @SQLTXT AS VARCHAR(MAX)
DECLARE @SESSIONDB AS VARCHAR(128)
DECLARE @TEMPTKS AS TABLE(ID INT IDENTITY,IDPRODUCTO INT,  TKPRODUCTO VARCHAR(MAX) )	
DECLARE @IDPRODUCTOS VARCHAR(MAX) 
 



SET @SQLTXT=''
SET @IDPRODUCTOS='' 
SET @SESSIONDB= '<#SESSION.DB/>'
SET @TKPRODUCTOS=ISNULL(:listaids, '') 
SET @TIPO= ISNULL(:TIPO,0) 
SET @ACCION= ISNULL(:ACCION,0)
SET @CANTIDAD = ISNULL(:CANTIDAD,0)
SET @PRECIOSACTUALIZAR=ISNULL(:preciosActualizar,'')
SET @TO = 1
SET @INDICEPRECIO = @PRECIOSACTUALIZAR

SET @SIGNO= (CASE   WHEN @ACCION=1 THEN '+' ELSE '-' END) 

INSERT INTO @TABLATEMP (INDICEPRECIO)
SELECT  stringvalue
from dbo.parseJSON(@INDICEPRECIO) 
WHERE parent_id IS NOT NULL AND object_id IS NULL

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP 

	
	INSERT @TEMPTKS (TKPRODUCTO) 
	SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT (@TKPRODUCTOS, ',')
	UPDATE S SET S.IDPRODUCTO=P.IDPRODUCTO FROM <#SESSION.DB/>.DBO.PRODUCTOS P,@TEMPTKS S
	WHERE P.TK collate Modern_Spanish_CI_AI  LIKE S.TKPRODUCTO collate Modern_Spanish_CI_AI

SELECT @IDPRODUCTOS=@IDPRODUCTOS+CAST(IDPRODUCTO AS VARCHAR(1000))+',' FROM @TEMPTKS

SET @IDPRODUCTOS= @IDPRODUCTOS+'0'

WHILE @TO <= @TOTAL
BEGIN
 IF(@TIPO=1) 
	 BEGIN
		SELECT @INDICEPRECIO = INDICEPRECIO FROM @TABLATEMP WHERE ID = @TO
		SET @SQLTXT = ' UPDATE '+ @SESSIONDB+'.DBO.PRODUCTOS SET '+ @INDICEPRECIO+'='+@INDICEPRECIO  + @SIGNO + 'CAST('+CAST(@CANTIDAD AS VARCHAR(1000))+' AS MONEY)' + ' WHERE IDPRODUCTO IN ('+@IDPRODUCTOS+')'
		--SELECT @SQLTXT
		EXEC(@SQLTXT)

	 END 
 ELSE 
	BEGIN
 		SELECT @INDICEPRECIO = INDICEPRECIO FROM @TABLATEMP WHERE ID = @TO
		SET @SQLTXT = ' UPDATE '+ @SESSIONDB+'.DBO.PRODUCTOS SET '+ @INDICEPRECIO+'='+@INDICEPRECIO  + @SIGNO + '('+@INDICEPRECIO +'*CAST('+CAST(@CANTIDAD AS VARCHAR(1000))+' AS MONEY)/100)' + ' WHERE  IDPRODUCTO IN ('+@IDPRODUCTOS+')'
		--SELECT (@SQLTXT)
		EXEC(@SQLTXT)
	END 
 SET @TO = @TO + 1 	
END
