//[session.idempresa|Untyped,idmodulo|Integer,]
--SELECT

DECLARE @IDEMPRESA INT , @ACTIVO INT
DECLARE @IDMODULO VARCHAR(MAX) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @IDMODULO=:IDMODULO
SET @ACTIVO = 0

SELECT @ACTIVO = COUNT(*)
 FROM CONTROL.CONTROL.DBO.MODULOS_EMPRESAS WHERE IDMODULO=@IDMODULO AND IDEMPRESA=@IDEMPRESA
 
 
 SELECT @ACTIVO AS IDMODULO