//[listap|Text,session.idempresa|Untyped,tklinea|Text,session.db|Untyped,]
-- UPDATE

DECLARE @LISTAP VARCHAR(MAX)
DECLARE @IDEMPRESA INT, @IDLINEA INT
DECLARE @TEMPTKPROD AS TABLE(ID INT IDENTITY, IDPRODUCTO INT , TKPRODUCTO VARCHAR(MAX))
DECLARE @IDPRODUCTOS VARCHAR(MAX) 
DECLARE @TKLINEA  VARCHAR(256)
DECLARE @SQLTEXT VARCHAR(MAX) 

SET @LISTAP = ISNULL(:LISTAP,'')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
 
SET @TKLINEA = ISNULL(:TKLINEA,'') 

SELECT @IDLINEA= IDLINEA_PRODUCTO FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE IDEMPRESA= @IDEMPRESA AND TK=@TKLINEA

SET @SQLTEXT= ''

INSERT INTO @TEMPTKPROD (TKPRODUCTO)
SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT (@LISTAP, ',')

SET @IDPRODUCTOS='' 
UPDATE TKS 
SET TKS.IDPRODUCTO=P.IDPRODUCTO 
FROM  <#SESSION.DB/>.DBO.PRODUCTOS  P, @TEMPTKPROD TKS
WHERE TKS.TKPRODUCTO collate Modern_Spanish_CI_AI =P.TK collate Modern_Spanish_CI_AI

SELECT @IDPRODUCTOS=@IDPRODUCTOS+CAST(IDPRODUCTO AS VARCHAR(MAX))+','  FROM @TEMPTKPROD
SET @IDPRODUCTOS=@IDPRODUCTOS+'0'



SET @SQLTEXT= 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS SET IDLINEA_PRODUCTO = CAST(' +CAST(@IDLINEA AS VARCHAR(200)) +' AS INT) WHERE IDEMPRESA ='+ CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND IDPRODUCTO IN ('+@IDPRODUCTOS+')'
EXEC (@SQLTEXT) 
