//[codigo|Text,session.idempresa|Untyped,session.db|Untyped,]
--SELECT 


DECLARE @CODIGO VARCHAR(MAX)
DECLARE @IDEMPRESA INT 


SET @CODIGO=ISNULL(:CODIGO, '')
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'

SELECT COUNT(*)AS TOTAL FROM <#SESSION.DB/>.DBO.PRODUCTOS 
WHERE IDEMPRESA=@IDEMPRESA AND CODIGO=@CODIGO 
