//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDEMPRESA INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT LP.STATUS,LP.IDLISTA_PRECIO, LP.NOMBRE, LP.INDICE, CTM.MONEDA+'('+CTM.IDMONEDA+')' AS MONEDA ,M.IDMONEDA, LP.TK 
FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO LP,<#SESSION.DB/>.DBO.MONEDAS M, MONEDAS CTM 
WHERE LP.IDEMPRESA = @IDEMPRESA AND M.IDEMPRESA = @IDEMPRESA AND LP.IDMONEDA = M.IDMONEDA AND CTM.IDMONEDA = M.IDMONEDA