//[idmoneda|Text,]
--SELECT 
DECLARE @IDEMPRESA INT 
DECLARE @IDMONEDA VARCHAR(3) 
SET  @IDMONEDA=ISNULL(:IDMONEDA, 'MXN') 

SELECT IDMONEDA,  MONEDA_SIMBOLO, UNICODE(MONEDA_SIMBOLO) AS UNICODE FROM SALESUP_CT.DBO.MONEDAS 
WHERE IDMONEDA= @IDMONEDA 