//[actualiza|Integer,monto|Numeric,tk|Text,session.db|Untyped,indice|Integer,session.idempresa|Untyped,descripcion|Text,]
--update
DECLARE @MONTO FLOAT 
DECLARE @INDICE INT 
DECLARE @IDPRODUCTO_COMISION INT
DECLARE @DESCRIPCION VARCHAR(500) 
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @IDEMPRESA INT 
DECLARE @SQLTEXT VARCHAR(MAX)
DECLARE @ACTUALIZA INT 
DECLARE @TK VARCHAR(256) 

set @ACTUALIZA = isnull(:ACTUALIZA,0);
SET @MONTO=ISNULL(:MONTO, 0) 
SET @IDPRODUCTO_COMISION=0 
SET @TK=ISNULL(:TK, '') 
SET @IDEMPRESA=ISNULL(<#SESSION.IDEMPRESA/>, 0) 
IF(@TK!='')BEGIN  SELECT @IDPRODUCTO_COMISION=IDPRODUCTO_COMISION FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES WHERE IDEMPRESA= @IDEMPRESA AND TKCOMISION=@TK  END 

SET @INDICE=ISNULL(:INDICE, 0) 
SET @CAMPO='COMISION'+CAST(@INDICE AS VARCHAR(10))


SET @DESCRIPCION=ISNULL(:DESCRIPCION, 0)
SET @SQLTEXT=''


IF(@ACTUALIZA=1)
 BEGIN 
  SET @SQLTEXT= 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS 
  SET '+@CAMPO+'='+CAST(@MONTO AS VARCHAR(MAX))
  +' WHERE IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(MAX))
  EXEC (@SQLTEXT)
 END

 UPDATE <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES 
  SET DESCRIPCION=@DESCRIPCION,
      MONTO=@MONTO
  WHERE IDEMPRESA=@IDEMPRESA AND IDPRODUCTO_COMISION=@IDPRODUCTO_COMISION

