//[session.idempresa|Untyped,session.db|Untyped,idempresamoneda|Integer,]
-- SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @IDEMPRESAMONEDA INT = ISNULL(:IDEMPRESAMONEDA,0)
DECLARE @IDMONEDA VARCHAR(5)

SELECT @IDMONEDA = IDMONEDA FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESAMONEDA = @IDEMPRESAMONEDA


SELECT COUNT(*) AS Respuesta FROM <#SESSION.DB/>.dbo.LISTAS_PRECIO WHERE IDEMPRESA = @IDEMPRESA AND IDMONEDA = @IDMONEDA