//[session.idempresa|Untyped,session.db|Untyped,]
-- SELECT 

DECLARE @IDEMPRESA INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT TK,LINEA_PRODUCTO /*,IDLINEA_PRODUCTO*/ FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE IDEMPRESA = @IDEMPRESA  