//[ideliminar|Text,session.idempresa|Untyped,session.db|Untyped,idnuevo|Integer,]
-- SELECT 
/*PROTEGIDO*/
DECLARE @IDMONEDA VARCHAR(6)
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @TOTAL INT
DECLARE @IDEMPRESAMONEDA INT = ISNULL(:IDELIMINAR,0)
DECLARE @IDNUEVO INT = ISNULL(:IDNUEVO,0)
DECLARE @SQLTXT VARCHAR(MAX)

SELECT @IDMONEDA = IDMONEDA FROM <#SESSION.DB/>.dbo.MONEDAS WHERE IDEMPRESAMONEDA = @IDEMPRESAMONEDA AND IDEMPRESA = @IDEMPRESA

SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.dbo.LISTAS_PRECIO WHERE IDEMPRESA = @IDEMPRESA AND IDMONEDA = @IDMONEDA

IF(@TOTAL > 0)
BEGIN
	 SELECT 0 AS RESPUESTA, 'La moneda no se puede eliminar ya que está actualmente en uso.' AS MENSAJE
END
ELSE
BEGIN
	 IF(@IDNUEVO = 0)
	 BEGIN
	 	  UPDATE <#SESSION.DB/>.dbo.OPORTUNIDADES SET IDEMPRESAMONEDA = NULL WHERE IDEMPRESAMONEDA = @IDEMPRESAMONEDA
	 	  UPDATE <#SESSION.DB/>.dbo.VENTAS SET IDMONEDA = NULL WHERE IDMONEDA = @IDEMPRESAMONEDA
	 END
	 ELSE
	 BEGIN
	 	  UPDATE <#SESSION.DB/>.dbo.OPORTUNIDADES SET IDEMPRESAMONEDA = @IDNUEVO WHERE IDEMPRESAMONEDA = @IDEMPRESAMONEDA
	 	  UPDATE <#SESSION.DB/>.dbo.VENTAS SET IDMONEDA = @IDNUEVO WHERE IDMONEDA = @IDEMPRESAMONEDA
	 END
	 
	 DELETE FROM <#SESSION.DB/>.dbo.MONEDAS WHERE IDEMPRESA = @IDEMPRESA AND IDEMPRESAMONEDA = @IDEMPRESAMONEDA
	 SELECT 1 AS RESPUESTA, 'Eliminado correctamente.' AS MENSAJE
END
