//[session.idempresa|Untyped,tipos|Text,tks|Text,session.db|Untyped,]
--SELECT

DECLARE @IDEMPRESA INT
DECLARE @TKFILTRO VARCHAR(128)
DECLARE @FILTRO VARCHAR(MAX)
DECLARE @SQLTXT VARCHAR(MAX)
DECLARE @TIPO VARCHAR(128)
DECLARE @IDBUSCAR INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @FILTRO = ''
SET @TIPO =ISNULL(:TIPOS , '')  
SET @TKFILTRO =ISNULL( :TKS , '')

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,TIPO VARCHAR(128), TK VARCHAR(128))
DECLARE @TO INT, @TOTAL INT
DECLARE @TK VARCHAR(64), @TIPOFILTRO VARCHAR(2)
SET @TO = 1

INSERT INTO @TABLATEMP (TIPO,TK)
SELECT A.SplitValue,B.SplitValue FROM dbo.Split(@TIPO,'|') A, dbo.Split(@TKFILTRO,'|') B WHERE A.OccurenceId = B.OccurenceId

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @TIPOFILTRO = TIPO, @TK = salesup_ct.dbo.ValidaToken(TK) FROM @TABLATEMP WHERE ID = @TO
	
	IF(@TIPOFILTRO='1')
	BEGIN
		SELECT @IDBUSCAR = IDLINEA_PRODUCTO FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE TK = @TK
		SET @FILTRO = @FILTRO + ' AND MLP.IDLINEA_PRODUCTO = ' + CAST(@IDBUSCAR AS VARCHAR(128))
	END
	ELSE IF(@TIPOFILTRO = '2')
	BEGIN
		SELECT @IDBUSCAR = IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE TK = @TK
		SET @FILTRO = @FILTRO + ' AND M.IDMARCA = ' + CAST(@IDBUSCAR AS VARCHAR(128))
	END
	ELSE IF(@TIPOFILTRO = '3')
	BEGIN
		SET @FILTRO = @FILTRO + ' AND (P.CODIGO collate Modern_Spanish_CI_AI LIKE ''%'+@TK+'%'' OR P.NOMBRE collate Modern_Spanish_CI_AI LIKE ''%'+@TK+'%'' OR M.MARCA collate Modern_Spanish_CI_AI LIKE ''%'+@TK+'%'' OR MLP.LINEA_PRODUCTO collate Modern_Spanish_CI_AI LIKE ''%'+@TK+'%'')'	
	END
	
	SET @TO = @TO + 1
END

SET @SQLTXT ='
	   SELECT * INTO #TempTABLA_LISTAS_PRECIO FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO WHERE IDEMPRESA= ' + CAST(@IDEMPRESA AS VARCHAR)+' AND STATUS=1  
	   SELECT * INTO #TempTABLA_PRODUCTOS_COMISIONES FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES WHERE IDEMPRESA= ' + CAST(@IDEMPRESA AS VARCHAR)+'AND STATUS=1 
	   SELECT * INTO #TempTABLA_EMPRESAS_IMPUESTOS FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDEMPRESA= ' + CAST(@IDEMPRESA AS VARCHAR)+'AND STATUS=1 
		
	   SELECT P.IDPRODUCTO,P.CODIGO, P.NOMBRE, M.MARCA,MLP.LINEA_PRODUCTO,P.PRECIO_MIN,         
	   P.PRECIO1,P.PRECIO2,P.PRECIO3,P.PRECIO4,P.PRECIO5,P.PRECIO6,P.PRECIO7,P.PRECIO8,P.PRECIO9,P.PRECIO10,          
	   P.COMISION1,P.COMISION2, P.COMISION3, P.COMISION4, P.COMISION5, P.COMISION6, P.COMISION7, P.COMISION8, P.COMISION9, P.COMISION10,         
	   P.IMPUESTO1, P.IMPUESTO2, P.IMPUESTO3, P.IMPUESTO4, P.IMPUESTO5, P.IMPUESTO6, P.IMPUESTO7, P.IMPUESTO8, P.IMPUESTO9, P.IMPUESTO10,      
	   P.COSTO,P.UNIDAD,
	   CASE WHEN P.EXISTENCIA = -1 THEN ''Ilimitado'' ELSE CAST(P.EXISTENCIA AS VARCHAR(MAX)) END AS EXISTENCIA ,
	   CASE WHEN P.STATUS = 1 THEN ''Activo'' ELSE ''Inactivo '' END AS STATUS,P.TK, P.TKM,       
	   CASE WHEN LP.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO1,       
	   CASE WHEN LP.IDLISTA_PRECIO IS NOT NULL THEN LP.NOMBRE ELSE '''' END AS NOMBRE1,       
	   CASE WHEN LP2.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO2,       
	   CASE WHEN LP2.IDLISTA_PRECIO IS NOT NULL THEN LP2.NOMBRE ELSE '''' END AS NOMBRE2,       
	   CASE WHEN LP3.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO3,       
	   CASE WHEN LP3.IDLISTA_PRECIO IS NOT NULL THEN LP3.NOMBRE ELSE '''' END AS NOMBRE3,       
	   CASE WHEN LP4.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO4,       
	   CASE WHEN LP4.IDLISTA_PRECIO IS NOT NULL THEN LP4.NOMBRE ELSE '''' END AS NOMBRE4,       
	   CASE WHEN LP5.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO5,       
	   CASE WHEN LP5.IDLISTA_PRECIO IS NOT NULL THEN LP5.NOMBRE ELSE '''' END AS NOMBRE5,       
	   CASE WHEN LP6.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO6,       
	   CASE WHEN LP6.IDLISTA_PRECIO IS NOT NULL THEN LP6.NOMBRE ELSE '''' END AS NOMBRE6,       
	   CASE WHEN LP7.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO7,       
	   CASE WHEN LP7.IDLISTA_PRECIO IS NOT NULL THEN LP7.NOMBRE ELSE '''' END AS NOMBRE7,       
	   CASE WHEN LP8.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO8,      
	   CASE WHEN LP8.IDLISTA_PRECIO IS NOT NULL THEN LP8.NOMBRE ELSE '''' END AS NOMBRE8,       
	   CASE WHEN LP9.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO9,       
	   CASE WHEN LP9.IDLISTA_PRECIO IS NOT NULL THEN LP9.NOMBRE ELSE '''' END AS NOMBRE9,       
	   CASE WHEN LP10.IDLISTA_PRECIO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEPRECIO10,       
	   CASE WHEN LP10.IDLISTA_PRECIO IS NOT NULL THEN LP10.NOMBRE ELSE '''' END AS NOMBRE10, 
	             
	   CASE WHEN COM.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION1,       
	   CASE WHEN COM.IDPRODUCTO_COMISION IS NOT NULL THEN COM.DESCRIPCION ELSE '''' END AS CNOMBRE1,       
	   CASE WHEN COM2.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION2,       
	   CASE WHEN COM2.IDPRODUCTO_COMISION IS NOT NULL THEN COM2.DESCRIPCION ELSE '''' END AS CNOMBRE2,       
	   CASE WHEN COM3.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION3,       
	   CASE WHEN COM3.IDPRODUCTO_COMISION IS NOT NULL THEN COM3.DESCRIPCION ELSE '''' END AS CNOMBRE3,       
	   CASE WHEN COM4.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION4,       
	   CASE WHEN COM4.IDPRODUCTO_COMISION IS NOT NULL THEN COM4.DESCRIPCION ELSE '''' END AS CNOMBRE4,       
	   CASE WHEN COM5.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION5,       
	   CASE WHEN COM5.IDPRODUCTO_COMISION IS NOT NULL THEN COM5.DESCRIPCION ELSE '''' END AS CNOMBRE5,       
	   CASE WHEN COM6.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION6,       
	   CASE WHEN COM6.IDPRODUCTO_COMISION IS NOT NULL THEN COM6.DESCRIPCION ELSE '''' END AS CNOMBRE6,       
	   CASE WHEN COM7.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION7,       
	   CASE WHEN COM7.IDPRODUCTO_COMISION IS NOT NULL THEN COM7.DESCRIPCION ELSE '''' END AS CNOMBRE7,       
	   CASE WHEN COM8.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION8,       
	   CASE WHEN COM8.IDPRODUCTO_COMISION IS NOT NULL THEN COM8.DESCRIPCION ELSE '''' END AS CNOMBRE8,       
	   CASE WHEN COM9.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION9,       
	   CASE WHEN COM9.IDPRODUCTO_COMISION IS NOT NULL THEN COM9.DESCRIPCION ELSE '''' END AS CNOMBRE9,       
	   CASE WHEN COM10.IDPRODUCTO_COMISION IS NOT NULL THEN ''1'' ELSE '''' END AS TIENECOMISION10,       
	   CASE WHEN COM10.IDPRODUCTO_COMISION IS NOT NULL THEN COM10.DESCRIPCION ELSE '''' END AS CNOMBRE10,
	   
	   CASE WHEN IMP.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO1,       
	   CASE WHEN IMP.IDIMPUESTO IS NOT NULL THEN IMP.IMPUESTO ELSE '''' END AS IMPNOMBRE1,       
	   CASE WHEN IMP2.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO2,       
	   CASE WHEN IMP2.IDIMPUESTO IS NOT NULL THEN IMP2.IMPUESTO ELSE '''' END AS IMPNOMBRE2,       
	   CASE WHEN IMP3.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO3,       
	   CASE WHEN IMP3.IDIMPUESTO IS NOT NULL THEN IMP3.IMPUESTO ELSE '''' END AS IMPNOMBRE3,       
	   CASE WHEN IMP4.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO4,       
	   CASE WHEN IMP4.IDIMPUESTO IS NOT NULL THEN IMP4.IMPUESTO ELSE '''' END AS IMPNOMBRE4,       
	   CASE WHEN IMP5.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO5,       
	   CASE WHEN IMP5.IDIMPUESTO IS NOT NULL THEN IMP5.IMPUESTO ELSE '''' END AS IMPNOMBRE5,       
	   CASE WHEN IMP6.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO6,       
	   CASE WHEN IMP6.IDIMPUESTO IS NOT NULL THEN IMP6.IMPUESTO ELSE '''' END AS IMPNOMBRE6,       
	   CASE WHEN IMP7.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO7,       
	   CASE WHEN IMP7.IDIMPUESTO IS NOT NULL THEN IMP7.IMPUESTO ELSE '''' END AS IMPNOMBRE7,       
	   CASE WHEN IMP8.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO8,       
	   CASE WHEN IMP8.IDIMPUESTO IS NOT NULL THEN IMP8.IMPUESTO ELSE '''' END AS IMPNOMBRE8,       
	   CASE WHEN IMP9.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO9,       
	   CASE WHEN IMP9.IDIMPUESTO IS NOT NULL THEN IMP9.IMPUESTO ELSE '''' END AS IMPNOMBRE9,       
	   CASE WHEN IMP10.IDIMPUESTO IS NOT NULL THEN ''1'' ELSE '''' END AS TIENEIMPUESTO10,       
	   CASE WHEN IMP10.IDIMPUESTO IS NOT NULL THEN IMP10.IMPUESTO ELSE '''' END AS IMPNOMBRE10
	       
	   FROM <#SESSION.DB/>.DBO.MARCAS M, 
	   <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO MLP, 
	   <#SESSION.DB/>.DBO.PRODUCTOS P     
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP ON  LP.INDICE = 1
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP2 ON LP2.INDICE = 2 
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP3 ON LP3.INDICE = 3
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP4 ON LP4.INDICE = 4
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP5 ON LP5.INDICE = 5  
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP6 ON LP6.INDICE = 6
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP7 ON LP7.INDICE = 7  
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP8 ON LP8.INDICE = 8   
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP9 ON LP9.INDICE = 9  
	   LEFT JOIN #TempTABLA_LISTAS_PRECIO LP10 ON LP10.INDICE = 10     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM  ON  COM.INDICE = 1    
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM2 ON  COM2.INDICE = 2    
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM3 ON  COM3.INDICE = 3   
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM4 ON  COM4.INDICE = 4   
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM5 ON  COM5.INDICE = 5     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM6 ON  COM6.INDICE = 6     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM7 ON  COM7.INDICE = 7     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM8 ON  COM8.INDICE = 8     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM9 ON  COM9.INDICE = 9     
	   LEFT JOIN #TempTABLA_PRODUCTOS_COMISIONES COM10 ON COM10.INDICE = 10 

	   
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP   ON  IMP.INDICE = 1  
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP2  ON  IMP2.INDICE = 2 
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP3  ON  IMP3.INDICE = 3  
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP4  ON  IMP4.INDICE = 4   
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP5  ON  IMP5.INDICE = 5  
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP6  ON  IMP6.INDICE = 6   
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP7  ON  IMP7.INDICE = 7   
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP8  ON  IMP8.INDICE = 8  
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP9  ON  IMP9.INDICE = 9  
	   LEFT JOIN #TempTABLA_EMPRESAS_IMPUESTOS IMP10 ON  IMP10.INDICE = 10  

 WHERE P.STATUS!=3 AND P.IDMARCA = M.IDMARCA AND P.IDLINEA_PRODUCTO = MLP.IDLINEA_PRODUCTO AND P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR) + @FILTRO
 +'ORDER BY P.NOMBRE ASC '


DECLARE @TABLASELECT TABLE (ID INT IDENTITY, IDPRODUCTO INT,CODIGO VARCHAR(512), NOMBRE VARCHAR(512),MARCA VARCHAR(512),LINEA_PRODUCTO VARCHAR(512),PRECIO_MIN MONEY,
PRECIO1 MONEY,PRECIO2 MONEY,PRECIO3 MONEY,PRECIO4 MONEY,PRECIO5 MONEY,PRECIO6 MONEY,PRECIO7 MONEY,PRECIO8 MONEY, PRECIO9 MONEY,PRECIO10 MONEY,
COMISION1 FLOAT, COMISION2 FLOAT, COMISION3 FLOAT, COMISION4 FLOAT, COMISION5 FLOAT, COMISION6 FLOAT, COMISION7 FLOAT, COMISION8 FLOAT, COMISION9 FLOAT, COMISION10 FLOAT, 
IMPUESTO1 FLOAT, IMPUESTO2 FLOAT, IMPUESTO3 FLOAT, IMPUESTO4 FLOAT, IMPUESTO5 FLOAT, IMPUESTO6 FLOAT, IMPUESTO7 FLOAT, IMPUESTO8 FLOAT, IMPUESTO9 FLOAT, IMPUESTO10 FLOAT, 

COSTO MONEY,UNIDAD VARCHAR(256),EXISTENCIA varchar(max),STATUS VARCHAR(64),TK VARCHAR(128), TKM VARCHAR(128),
TIENEPRECIO1 VARCHAR(256),NOMBREPRECIO1 VARCHAR(256),
TIENEPRECIO2 VARCHAR(256),NOMBREPRECIO2 VARCHAR(256),
TIENEPRECIO3 VARCHAR(256),NOMBREPRECIO3 VARCHAR(256),
TIENEPRECIO4 VARCHAR(256),NOMBREPRECIO4 VARCHAR(256),
TIENEPRECIO5 VARCHAR(256),NOMBREPRECIO5 VARCHAR(256),
TIENEPRECIO6 VARCHAR(256),NOMBREPRECIO6 VARCHAR(256),
TIENEPRECIO7 VARCHAR(256),NOMBREPRECIO7 VARCHAR(256),
TIENEPRECIO8 VARCHAR(256),NOMBREPRECIO8 VARCHAR(256),
TIENEPRECIO9 VARCHAR(256),NOMBREPRECIO9 VARCHAR(256),
TIENEPRECIO10 VARCHAR(256),NOMBREPRECIO10 VARCHAR(256),
TIENECOMISION1 VARCHAR(256),CNOMBRE1 VARCHAR(256),
TIENECOMISION2 VARCHAR(256),CNOMBRE2 VARCHAR(256),
TIENECOMISION3 VARCHAR(256),CNOMBRE3 VARCHAR(256),
TIENECOMISION4 VARCHAR(256),CNOMBRE4 VARCHAR(256),
TIENECOMISION5 VARCHAR(256),CNOMBRE5 VARCHAR(256),
TIENECOMISION6 VARCHAR(256),CNOMBRE6 VARCHAR(256),
TIENECOMISION7 VARCHAR(256),CNOMBRE7 VARCHAR(256),
TIENECOMISION8 VARCHAR(256),CNOMBRE8 VARCHAR(256),
TIENECOMISION9 VARCHAR(256),CNOMBRE9 VARCHAR(256),
TIENECOMISION10 VARCHAR(256),CNOMBRE10 VARCHAR(256), 

TIENEIMPUESTO1 VARCHAR(256),IMPNOMBRE1 VARCHAR(256),
TIENEIMPUESTO2 VARCHAR(256),IMPNOMBRE2 VARCHAR(256),
TIENEIMPUESTO3 VARCHAR(256),IMPNOMBRE3 VARCHAR(256),
TIENEIMPUESTO4 VARCHAR(256),IMPNOMBRE4 VARCHAR(256),
TIENEIMPUESTO5 VARCHAR(256),IMPNOMBRE5 VARCHAR(256),
TIENEIMPUESTO6 VARCHAR(256),IMPNOMBRE6 VARCHAR(256),
TIENEIMPUESTO7 VARCHAR(256),IMPNOMBRE7 VARCHAR(256),
TIENEIMPUESTO8 VARCHAR(256),IMPNOMBRE8 VARCHAR(256),
TIENEIMPUESTO9 VARCHAR(256),IMPNOMBRE9 VARCHAR(256),
TIENEIMPUESTO10 VARCHAR(256),IMPNOMBRE10 VARCHAR(256)
)




INSERT INTO @TABLASELECT
EXEC (@SQLTXT)
SELECT COUNT(ID) AS TOTALN  FROM @TABLASELECT

