//[session.idempresa|Untyped,idproducto|Integer,session.db|Untyped,tk|Text,]
--SELECT 
/*PROTEGIDO*/

DECLARE @TK VARCHAR(256) 
DECLARE @IDPRODUCTO INT 
DECLARE @IDEMPRESA  INT 
DECLARE @TOTAL INT 
DECLARE @IMAGENES VARCHAR(MAX)

SET @TK = ISNULL(:TK, '') 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @IDPRODUCTO=ISNULL(:IDPRODUCTO, 0)
SET @TOTAL=0
SET @IMAGENES=''

IF(@IDPRODUCTO=0) 
   SELECT @IDPRODUCTO=IDPRODUCTO FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE TK=@TK

SELECT @TOTAL=COUNT(*) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_PRODUCTOS OP
WHERE  OP.IDPRODUCTO=@IDPRODUCTO 
SELECT @IMAGENES=IMAGENES FROM <#SESSION.DB/>.DBO.PRODUCTOS 
WHERE IDPRODUCTO=@IDPRODUCTO 

SELECT @TOTAL AS TOTAL, @IMAGENES AS IMAGENES

