//[idcomision|Integer,session.idempresa|Untyped,session.db|Untyped,tk|Text,]
--SELECT 
DECLARE @IDCOMISION INT 
DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(256) 

SET @TK=ISNULL(:TK, '') 


SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SELECT * FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
	WHERE IDEMPRESA=@IDEMPRESA AND TKCOMISION=@TK 