//[session.idempresa|Untyped,session.db|Untyped,valunicos|Text,]
--SELECT 
DECLARE @JSON VARCHAR(MAX)
DECLARE @IDEMPRESA INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @JSON = ISNULL(:valUnicos, '') 

DECLARE @JSONIMAGENES VARCHAR(MAX), @MONTOBASE VARCHAR(MAX), @IMG_DEFAULT VARCHAR(MAX)
DECLARE @IDMARCA INT, @IDLINEA INT
DECLARE @FECHA_IMPORTACION DATETIME

IF OBJECT_ID('tempdb..#tbValidacionUnicos') IS NOT NULL
DROP TABLE #tbValidacionUnicos
SELECT * INTO #tbValidacionUnicos FROM SALESUP_CT.DBO.parseJSON(@JSON)

SELECT J1.STRINGVALUE AS id, J2.STRINGVALUE AS codigo, COUNT(P.IDPRODUCTO) AS existe
FROM #tbValidacionUnicos J1
LEFT JOIN #tbValidacionUnicos J2 ON J1.PARENT_ID = J2.PARENT_ID AND J2.NAME = 'V'
LEFT JOIN <#SESSION.DB/>.DBO.PRODUCTOS P ON P.IDEMPRESA = @IDEMPRESA AND P.CODIGO LIKE J2.STRINGVALUE 
WHERE J1.NAME = 'id' 
GROUP BY J1.STRINGVALUE, J2.STRINGVALUE

