//[session.idempresa|Untyped,idproducto|Integer,idproductonuevo|Integer,tipo|Integer,session.db|Untyped,tkeliminar|Text,tknuevo|Text,]
--DELETE
/*PROTEGIDO*/
DECLARE @IDEMPRESA INT 
DECLARE @IDPRODUCTOELIMINAR INT 
DECLARE @IDPRODUCTONUEVO INT 
DECLARE @TIPO INT 
DECLARE @TKELIMINAR VARCHAR(256) 
DECLARE @TKNUEVO VARCHAR(256) 

SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'
SET @TIPO=ISNULL(:TIPO, 0)  
SET @TKELIMINAR = ISNULL(:TKELIMINAR, '') 
SET @TKNUEVO=ISNULL(:TKNUEVO, '') 


SELECT @IDPRODUCTOELIMINAR=IDPRODUCTO FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE TK=@TKELIMINAR
SELECT @IDPRODUCTONUEVO=IDPRODUCTO FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE TK=@TKNUEVO    
   

IF(@TIPO=1) 
 BEGIN 
 	  DELETE <#SESSION.DB/>.DBO.PRODUCTOS
	  WHERE IDEMPRESA=@IDEMPRESA AND IDPRODUCTO=@IDPRODUCTOELIMINAR
 END 
ELSE IF (@TIPO=2) 
BEGIN
UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES_PRODUCTOS 
SET IDPRODUCTO=@IDPRODUCTONUEVO
WHERE IDPRODUCTO=@IDPRODUCTOELIMINAR

DELETE  <#SESSION.DB/>.DBO.PRODUCTOS 
WHERE  IDEMPRESA=@IDEMPRESA  AND  IDPRODUCTO= @IDPRODUCTOELIMINAR 
END 
 