//[listap|Text,session.idempresa|Untyped,tkmarca|Text,session.db|Untyped,]
--UPDATE 

DECLARE @LISTAP VARCHAR(MAX)
DECLARE @IDEMPRESA INT, @IDMARCA INT
DECLARE @SQLTEXT VARCHAR(MAX) 
DECLARE @TKLISTAS VARCHAR(MAX) 
DECLARE @TKMARCA VARCHAR(MAX) 
DECLARE @TEMPTKS  AS TABLE (ID INT IDENTITY, IDPRODUCTO INT, TKPRODUCTO VARCHAR(MAX))
DECLARE @IDPRODUCTOS VARCHAR(MAX) 

SET @SQLTEXT=''

SET @TKLISTAS = ISNULL(:LISTAP,'')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TKMARCA=ISNULL(:TKMARCA, '') 
SELECT @IDMARCA = IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE IDEMPRESA=@IDEMPRESA AND TK=@TKMARCA

INSERT INTO @TEMPTKS (TKPRODUCTO)
SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT (@TKLISTAS, ',') 
SET @IDPRODUCTOS ='' 


UPDATE   TKS 
SET TKS.IDPRODUCTO=P.IDPRODUCTO 
FROM  <#SESSION.DB/>.DBO.PRODUCTOS  P, @TEMPTKS TKS
WHERE TKS.TKPRODUCTO collate Modern_Spanish_CI_AI =P.TK collate Modern_Spanish_CI_AI

SELECT @IDPRODUCTOS=@IDPRODUCTOS+CAST(IDPRODUCTO AS VARCHAR(MAX))+','  FROM @TEMPTKS
SET @IDPRODUCTOS=@IDPRODUCTOS+'0'


SET @SQLTEXT='UPDATE <#SESSION.DB/>.DBO.PRODUCTOS SET IDMARCA = '+CAST(@IDMARCA AS VARCHAR(MAX))+' WHERE IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND IDPRODUCTO IN ('+@IDPRODUCTOS+')' 
EXEC (@SQLTEXT)