//[idprodeliminar|Integer,session.idempresa|Untyped,session.db|Untyped,tk|Text,]
--select 
/*PROTEGIDO*/

DECLARE @IDPRODUCTOELIMINAR INT 
DECLARE @IDEMPRESA INT 
DECLARE @TKELIMINAR VARCHAR(256) 


SET @IDPRODUCTOELIMINAR=:idprodeliminar 
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'
SET @TKELIMINAR=ISNULL(:TK, '') 


SELECT  NOMBRE, TK 
FROM <#SESSION.DB/>.DBO.PRODUCTOS  
WHERE  IDEMPRESA=@IDEMPRESA AND STATUS=1  AND (IDPRODUCTO!=@IDPRODUCTOELIMINAR OR TK!=@TKELIMINAR) 