//[session.db|Untyped,session.idempresa|Untyped,]
--SELECT 

DECLARE @IDEMPRESA INT 
DECLARE @CONTPRECIOS INT 
DECLARE @CONTCOMISION INT 

SET @CONTPRECIOS=0
SET @CONTCOMISION= 0 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SELECT  @CONTPRECIOS=COUNT(*) FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO
WHERE IDEMPRESA=@IDEMPRESA AND STATUS=1
SELECT @CONTCOMISION=COUNT(*) FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
WHERE IDEMPRESA=@IDEMPRESA AND STATUS=1

SELECT @CONTPRECIOS AS TOTALPRECIOS, @CONTCOMISION AS TOTALCOMISION