//[session.idempresa|Untyped,status|Integer,session.db|Untyped,tk|Text,]
--SELECT
/*PROTEGIDO*/
DECLARE @TK VARCHAR(256)  
DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
SET @TK=ISNULL(:TK, 0)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @STATUS=ISNULL(:STATUS, -1)


IF(@STATUS=-1)
   SELECT STATUS FROM <#SESSION.DB/>.DBO.PRODUCTOS
   WHERE  IDEMPRESA=@IDEMPRESA  AND TK= @TK
ELSE 
 BEGIN 
  UPDATE <#SESSION.DB/>.DBO.PRODUCTOS
  SET STATUS=@STATUS
  WHERE TK=@TK AND IDEMPRESA=@IDEMPRESA
  SELECT STATUS FROM <#SESSION.DB/>.DBO.PRODUCTOS
  WHERE TK=@TK AND IDEMPRESA=@IDEMPRESA
 END 
