//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
DECLARE @json VARCHAR(max)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @json =''

DECLARE @EXISTEN_IMPUESTO INT

SELECT @EXISTEN_IMPUESTO = COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS WHERE STATUS =1 AND IDEMPRESA =@IDEMPRESA and indice is not null 

IF(@EXISTEN_IMPUESTO = 0 )
 BEGIN
  SET @json ='{"nombre":"demo","indice":0},'
 END
ELSE
 BEGIN
 SELECT @json=@json +'{"nombre":"'+IMPUESTO+'","indice":'+CAST(INDICE AS VARCHAR(128))+'},' FROM <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS WHERE STATUS =1 AND IDEMPRESA =@IDEMPRESA and indice is not null 
 END



SELECT @json as ImpEmpresa, LP.IDLISTA_PRECIO as idLtPrecios, LP.NOMBRE as Precio, LP.INDICE as Indice, M.idMoneda, M.TIPODECAMBIO, M.IDEMPRESAMONEDA ,CTM.MONEDA, UNICODE(CTM.MONEDA_SIMBOLO) AS UNICODE
FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO LP, <#SESSION.DB/>.DBO.MONEDAS M,  MONEDAS CTM
WHERE LP.IDEMPRESA = @IDEMPRESA AND M.IDEMPRESA = @IDEMPRESA AND LP.IDMONEDA = M.IDMONEDA and LP.STATUS=1 and M.IDMONEDA = CTM.IDMONEDA