//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 

DECLARE @IDEMPRESA INT 
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'

SELECT TOP 1 *
 FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS 
WHERE IDEMPRESA=@IDEMPRESA