//[listap|Text,session.idempresa|Untyped,status|Integer,session.db|Untyped,]
-- UPDATE

DECLARE @LISTAP VARCHAR(MAX)
DECLARE @IDEMPRESA INT, @STATUS INT
DECLARE @TEMPTKS AS TABLE (ID INT IDENTITY, IDPRODUCTO INT, TKPRODUCTO VARCHAR(256)) 
DECLARE @SQLTEXT VARCHAR(MAX)
DECLARE @IDPRODUCTO VARCHAR(MAX) 

SET @LISTAP = ISNULL(:LISTAP,'')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @STATUS = ISNULL(:STATUS,0)

INSERT INTO @TEMPTKS  (TKPRODUCTO) 
SELECT SplitValue FROM <#SESSION.DB/>.DBO.Split(@LISTAP,',')

UPDATE TKS
SET TKS.IDPRODUCTO=P.IDPRODUCTO
FROM  <#SESSION.DB/>.DBO.PRODUCTOS  P, @TEMPTKS TKS
WHERE TKS.TKPRODUCTO collate Modern_Spanish_CI_AI =P.TK collate Modern_Spanish_CI_AI

SET @IDPRODUCTO = ''
SELECT @IDPRODUCTO= @IDPRODUCTO+CAST(IDPRODUCTO AS VARCHAR(MAX))+',' FROM @TEMPTKS
SELECT @IDPRODUCTO=@IDPRODUCTO+'0'
 
SET @SQLTEXT=''
SET @SQLTEXT='UPDATE <#SESSION.DB/>.DBO.PRODUCTOS SET STATUS ='+CAST(@STATUS AS VARCHAR(MAX))+' WHERE IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND IDPRODUCTO IN ('+@IDPRODUCTO+')' 
EXEC (@SQLTEXT)