//[session.idempresa|Untyped,tk|Text,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT 
DECLARE @TKPRODUCTO VARCHAR(256) 


SET @IDEMPRESA =CAST(<#SESSION.IDEMPRESA/> AS INT)
SET @TKPRODUCTO=ISNULL(:TK, '') 



SELECT P.CODIGO, P.NOMBRE, P.PRECIO_MIN, P.PRECIO1, P.PRECIO2, P.PRECIO3, P.PRECIO4, P.PRECIO5, P.PRECIO6, P.PRECIO7, P.PRECIO8,
P.PRECIO9, P.PRECIO10, P.COSTO, P.UNIDAD, P.EXISTENCIA, P.STATUS, P.TK AS TKPRODUCTO, P.TKM, P.DESCRIPCION_CORTA, P.DESCRIPCION_EXTENDIDA1, 
P.DESCRIPCION_EXTENDIDA2, 
P.COMISION1*100 AS COMISION1,P.COMISION2*100 AS COMISION2, P.COMISION3*100 AS COMISION3, P.COMISION4*100 AS COMISION4, P.COMISION5*100 AS COMISION5,
P.COMISION6*100 AS COMISION6, P.COMISION7*100 AS COMISION7, P.COMISION8*100 AS COMISION8, P.COMISION9*100 AS COMISION9, P.COMISION10*100 AS COMISION10, 
P.IMPUESTO1*100 AS IMPUESTO1, P.IMPUESTO2*100 AS IMPUESTO2, P.IMPUESTO3*100 AS IMPUESTO3, P.IMPUESTO4*100 AS IMPUESTO4, P.IMPUESTO5*100 AS IMPUESTO5, 
P.IMPUESTO6*100 AS IMPUESTO6, P.IMPUESTO7*100 AS IMPUESTO7, P.IMPUESTO8*100 AS IMPUESTO8, P.IMPUESTO9*100 AS IMPUESTO9, P.IMPUESTO10*100 AS IMPUESTO10, 
P.IMAGENES, P.MONTO_BASE,
P.DESCRIPCION_COTIZACION, M.TK AS TKMARCA, LP.TK AS TKLINEAPROD, <#SESSION.DB/>.dbo.PreparaNumero(@IDEMPRESA,6) AS CARPETA
FROM <#SESSION.DB/>.DBO.PRODUCTOS P 
LEFT JOIN <#SESSION.DB/>.DBO.MARCAS M ON M.IDMARCA=P.IDMARCA
LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP ON LP.IDLINEA_PRODUCTO=P.IDLINEA_PRODUCTO 

WHERE P.IDEMPRESA=@IDEMPRESA AND  P.TK=@TKPRODUCTO

