//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SELECT * FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO 
WHERE IDEMPRESA=@IDEMPRESA AND STATUS=1

