//[tk|Text,session.db|Untyped,session.idempresa|Untyped,]
--update
DECLARE @IDLISTA INT, @INDICE INT
DECLARE @IDEMPRESA INT
DECLARE @SQLTXT VARCHAR(MAX)
DECLARE @TK VARCHAR(256) 

SET @TK=ISNULL(:TK, '') 

SELECT @IDLISTA =IDLISTA_PRECIO FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO WHERE TK=@TK
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT @INDICE = INDICE FROM <#SESSION.DB/>.dbo.LISTAS_PRECIO WHERE IDEMPRESA = @IDEMPRESA AND IDLISTA_PRECIO = @IDLISTA

SET @SQLTXT = 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS SET PRECIO'+CAST(@INDICE AS VARCHAR)+' = 0 WHERE IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR)+' '

EXEC(@SQLTXT)

DELETE FROM <#SESSION.DB/>.dbo.LISTAS_PRECIO WHERE IDEMPRESA = @IDEMPRESA AND IDLISTA_PRECIO = @IDLISTA
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS WITH(ROWLOCK) WHERE IDLISTA_PRECIO = @IDLISTA
