//[session.idempresa|Untyped,descripcion|Text,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 
DECLARE @DESCRIPCION VARCHAR(MAX) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @DESCRIPCION=ISNULL(:DESCRIPCION, '')

SELECT DESCRIPCION FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES 
WHERE IDEMPRESA=@IDEMPRESA AND DESCRIPCION=@DESCRIPCION 