//[tk|Text,session.idempresa|Untyped,session.db|Untyped,]
--SELECT

DECLARE @TK VARCHAR(128)
DECLARE @IDEMPRESA INT

SET @TK = dbo.ValidaToken(:TK)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT * FROM <#SESSION.DB/>.DBO.LISTAS_PRECIO WHERE IDEMPRESA = @IDEMPRESA AND TK = @TK