//[actualiza|Integer,tasa|Numeric,indice|Integer,session.db|Untyped,session.idempresa|Untyped,idimpuesto|Integer,nombreimpuesto|Text,tk|Text,]
--UPDATE
DECLARE @TASA FLOAT 
DECLARE @INDICE INT 
DECLARE @IDIMPUESTO VARCHAR(128)
DECLARE @IMPUESTO VARCHAR(500) 
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @IDEMPRESA INT 
DECLARE @SQLTEXT VARCHAR(MAX)
declare @actualizar int
DECLARE @TK VARCHAR(256) 

set @actualizar = isnull(:actualiza,0);

SET @TASA=ISNULL(:TASA, 0) 
SET @INDICE=ISNULL(:INDICE, 0)
SET @TK=ISNULL(:TK, '') 


IF(@INDICE=0)
 BEGIN
 	SELECT TOP 1 @INDICE=INDICE FROM SALESUP_CT.DBO.V_INDICES WHERE INDICE NOT IN (SELECT ISNULL(INDICE,0) FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDEMPRESA=@IDEMPRESA )    
 END

SET @CAMPO='IMPUESTO'+CAST(@INDICE AS VARCHAR(10))
SET @IDEMPRESA=ISNULL(<#SESSION.IDEMPRESA/>, 0) 
SELECT @IDIMPUESTO=IDIMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE TK=@TK 
SET @IMPUESTO=ISNULL(:NOMBREIMPUESTO, '')
SET @SQLTEXT=''


if @actualizar = 1
begin
SET @SQLTEXT= 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS 
SET '+@CAMPO+'='+CAST(@TASA AS VARCHAR(MAX))
+' WHERE IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(MAX))
EXEC (@SQLTEXT)
end


 UPDATE <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS
  SET IMPUESTO=@IMPUESTO,
      TASA=@TASA
  WHERE IDEMPRESA=@IDEMPRESA AND IDIMPUESTO=@IDIMPUESTO
  
