//[idmoneda|Text,session.idempresa|Untyped,session.db|Untyped,]
-- SELECT 

DECLARE @IDEMPRESA  INT 
DECLARE @IDMONEDA VARCHAR(128) 

 
SET @IDMONEDA=ISNULL(:IDMONEDA, 0) 
SET @IDEMPRESA= '<#SESSION.IDEMPRESA/>'


SELECT  PM.ID, ISNULL(M.IDMONEDA, '') AS IDMONEDA, ISNULL(BANDERA, '') AS BANDERA, ISNULL(M.MONEDA, '')  AS MONEDA, ISNULL(M.MONEDA_SIMBOLO, '') AS MONEDA_SIMBOLO, P.PAIS, P.IDPAIS
  		  FROM SALESUP_CT.DBO.PAISES_MONEDAS PM 
  		  	   LEFT JOIN SALESUP_CT.DBO.MONEDAS M  ON PM.IDMONEDA=M.IDMONEDA
  			   LEFT JOIN SALESUP_CT.DBO.PAISES P ON PM.IDPAIS=P.IDPAIS
			   WHERE P.PAIS IS NOT NULL
			   AND PM.ID NOT IN (SELECT IDPAISES_MONEDAS FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND IDPAISES_MONEDAS IS NOT NULL)
   			   OR PM.ID=(SELECT IDPAISES_MONEDAS FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND TK = @IDMONEDA)
  			   ORDER BY MONEDA ASC
