//[session.db|Untyped,session.idempresa|Untyped,f_visible|Untyped,]
SELECT COUNT(DISTINCT D.IDDOCUMENTO) AS TOTALN
FROM <#SESSION.DB/>.dbo.EMPRESAS_DOCUMENTOS D
LEFT JOIN <#SESSION.DB/>.dbo.DOCUMENTO_ICONOS ON D.NOMBRE_DOCUMENTO != '' 
AND EXTENSION = <#SESSION.DB/>.dbo.obtiene_extension(NOMBRE_DOCUMENTO) 
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>