//[elnivel|Text,session.db|Untyped,session.idempresa|Untyped,ordenamiento|Text,]
--select
DECLARE @CRIT VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
SET @CRIT = ISNULL( :ELNIVEL , '')
DECLARE @ORDENAMIENTO VARCHAR(MAX)
SET @ORDENAMIENTO = ISNULL( :ORDENAMIENTO , '')

SET @SQL = '
  SELECT COUNT (DISTINCT E.IDETIQUETA) AS TOTALN, ''' +@CRIT + ''' AS ELNIVEL, ''' +@ORDENAMIENTO + ''' AS ORDENAMIENTO 
  FROM 
  <#SESSION.DB/>.DBO.ETIQUETAS E 
  left join <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS PE 
    join <#SESSION.DB/>.DBO.PROSPECTOS PA on PE.IDPROSPECTO = PA.IDPROSPECTO AND PA.DESCARTADO = 0 
    join <#SESSION.DB/>.DBO.usuarios u on PA.IDUSUARIO = U.IDUSUARIO
  on PE.IDETIQUETA = E.IDETIQUETA AND E.IDEMPRESA = PA.IDEMPRESA ' + @CRIT + '
  WHERE E.IDEMPRESA = <#SESSION.IDEMPRESA/>  
'
EXEC (@SQL)
