//[session.idempresa|Untyped,idusuario|Integer,compartircon|Integer,texto|Text,session.idusuario|Untyped,session.idgrupo|Untyped,session.nivel|Untyped,session.db|Untyped,]
--SELECT 
/*PROTEGIDO*/


DECLARE @IDUSUARIO         INT 
DECLARE @IDEMPRESA         INT 
DECLARE @COMPARTIRCON      VARCHAR(MAX) 
DECLARE @IDGRUPO           INT
DECLARE @TEXTO             VARCHAR(100)
DECLARE @TKU VARCHAR(128)
DECLARE @IDUSUARIOSESSION INT 
DECLARE @IDGRUPOSESSION INT 
DECLARE @NIVEL INT 
DECLARE @CRITCOMPARTIRCON VARCHAR(MAX) 
DECLARE @CRITPOREJECUTIVO VARCHAR(MAX)
DECLARE @CRITTEXTO VARCHAR (MAX)
DECLARE @SQLTEXT VARCHAR(MAX)



SET @IDEMPRESA =<#SESSION.IDEMPRESA/>
SET @IDUSUARIO=ISNULL(:IDUSUARIO, 0) 
SET @COMPARTIRCON=ISNULL(REPLACE(:COMPARTIRCON, -2, ''), '')
SET @TEXTO= ISNULL(:TEXTO, '')
SET @IDUSUARIOSESSION =<#SESSION.IDUSUARIO/>
SET @IDGRUPOSESSION=<#SESSION.IDGRUPO/>
SET @NIVEL =<#SESSION.NIVEL/>

SET @CRITCOMPARTIRCON= (CASE WHEN @COMPARTIRCON != '' THEN ' AND UP.COMPARTIRCON='+@COMPARTIRCON ELSE '' END) 
SET @CRITPOREJECUTIVO=(CASE WHEN (@IDUSUARIO > 0) THEN 'AND UP.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR UP.IDUSUARIO='+CAST(@IDUSUARIOSESSION AS VARCHAR(MAX)) 
							WHEN (@IDUSUARIO='' AND @TEXTO='' AND @COMPARTIRCON='') THEN 'AND UP.IDUSUARIO='+CAST(@IDUSUARIOSESSION AS VARCHAR(MAX))
							ELSE '' END)
				 
SET @CRITTEXTO= (CASE WHEN 	@TEXTO!='' THEN 'AND UP.DESCRIPCION LIKE ''%'+@TEXTO+'%''  ' ELSE '' END)

					

SET @SQLTEXT=''					
	+'SELECT COUNT(UP.IDPLANTILLA) AS TOTAL
	 FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
 	   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO
	  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON  UP.COMPARTIRCON=UG.IDUSUARIOGRUPO
	 WHERE  UP.IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(MAX))+'
	  AND UP.IDUSUARIO IN(SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizados('+CAST(@IDUSUARIOSESSION AS VARCHAR(MAX))+'))
	  '+@CRITPOREJECUTIVO+'
	  '+@CRITCOMPARTIRCON+'
	  '+@CRITTEXTO+'
	  '
	  
EXEC(@SQLTEXT)   