//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,elanio2|Integer,filtro_grupo|Text,]
-- select
/*Protegido*/
DECLARE @ANIO INT
DECLARE @FILTRO_GRUPO VARCHAR(MAX)
DECLARE @SQLTXT VARCHAR(MAX)

SET @ANIO = :ELANIO2
SET @FILTRO_GRUPO = :FILTRO_GRUPO

SET @SQLTXT = 'SELECT COUNT (distinct L.IDLINEA_PRODUCTO) AS TOTALN ,'+CAST(@ANIO AS VARCHAR(5))+' AS ELANIO, '''+@FILTRO_GRUPO+''' AS FILTRO_GRUPO '
SET @SQLTXT = @SQLTXT + ' FROM  <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos(<#SESSION.IDUSUARIO/>,8,0) UL, '
SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO L,  <#SESSION.DB/>.DBO.USUARIOS U,  <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES O,  <#SESSION.DB/>.DBO.VENTAS V '
SET @SQLTXT = @SQLTXT + ' WHERE ' 
SET @SQLTXT = @SQLTXT + ' UL.ID=U.IDUSUARIO AND '
SET @SQLTXT = @SQLTXT + ' L.IDEMPRESA = <#SESSION.IDEMPRESA/> AND L.IDEMPRESA = U.IDEMPRESA AND L.IDLINEA_PRODUCTO = O.IDLINEA_PRODUCTO AND '
SET @SQLTXT = @SQLTXT + ' U.IDUSUARIO = P.IDUSUARIO AND P.IDPROSPECTO = O.IDPROSPECTO AND '
SET @SQLTXT = @SQLTXT + ' O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND YEAR (V.FECHAHORA) ='+CAST(@ANIO AS VARCHAR(5))+' AND O.GANADA != 0 '
SET @SQLTXT = @SQLTXT + ' and ' + @FILTRO_GRUPO

EXEC(@SQLTXT)