//[anioh|Integer,mes|Integer,periodo|Integer,agrupar|Integer,grupos|Integer,combo|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT

DECLARE @ANIO INT
DECLARE @PERIODO INT /*0 MENSUAL, 1 SEMANAL, 2 DIARIO*/
DECLARE @AGRUPAR INT /*0 EJECUTIVO, 1 GRUPOS/DEPARTAMENTOS */
DECLARE @GRUPOS INT
DECLARE @COMBO INT /*Columnas de la tabla */
DECLARE @MES INT
DECLARE @IDEMPRESA INT
SET @ANIO=ISNULL(:ANIOH, YEAR(GETDATE()))
SET @MES=ISNULL(:MES,MONTH(GETDATE()))
SET @PERIODO=ISNULL(:PERIODO,0)
SET @AGRUPAR=ISNULL(:AGRUPAR,0)
IF @AGRUPAR=1
  SET @GRUPOS=0
ELSE  
  SET @GRUPOS=ISNULL(:GRUPOS,0)
SET @COMBO=ISNULL(:COMBO,0)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
EXEC <#SESSION.DB/>.DBO.SP_LISTAR_REPORTE_ACTIVIDADES_HISTORICO_CABECERA @IDEMPRESA,@PERIODO,@AGRUPAR,@GRUPOS,@COMBO,@ANIO,@MES
