//[session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @TOTANIO INT
SELECT @TOTANIO=COUNT(*) from <#SESSION.DB/>.DBO.ACTIVIDADES_HISTORICO where IDEMPRESA=<#SESSION.IDEMPRESA/> group by ANIO
IF @TOTANIO > 0
  select anio AS ELANIO from <#SESSION.DB/>.DBO.ACTIVIDADES_HISTORICO where IDEMPRESA=<#SESSION.IDEMPRESA/> group by ANIO order by ANIO 
ELSE
  select YEAR(GETDATE()) AS ELANIO
