//[session.idempresa|Untyped,session.idusuario|Untyped,descartados|Integer,session.db|Untyped,texto_busqueda|Text,]
--select
/*PROTEGIDO*/

DECLARE @DESCARTADOS INT, @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @TEXTO VARCHAR(256)
DECLARE @TABLAPRIVILEGIOS TABLE (TIPO INT, ID INT)


SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @DESCARTADOS = ISNULL(:descartados,0)

INSERT INTO @TABLAPRIVILEGIOS (TIPO,ID)
select 1,ID from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(@IDUSUARIO,1,0)
UNION ALL
select 2,ID from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(@IDUSUARIO,2,0)
UNION ALL
select 3,ID from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(@IDUSUARIO,3,0)


IF @DESCARTADOS = 1
  SET @DESCARTADOS = 1
ELSE
  SET @DESCARTADOS = 0

    
SET @TEXTO= :texto_busqueda
SET @TEXTO= REPLACE(@TEXTO,'<','')
SET @TEXTO= REPLACE(@TEXTO,'>','')
SET @TEXTO= REPLACE(@TEXTO,'"','')
SET @TEXTO= REPLACE(@TEXTO,'''','')
SET @TEXTO= '%'+@TEXTO+'%'
 
SELECT COUNT (distinct P.IDPROSPECTO) AS TOTALN

FROM 
<#SESSION.DB/>.dbo.PROSPECTOS P WITH (NOLOCK)
LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON P.IDPAIS =PAI.IDPAIS
LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS ES ON ES.IDPAIS =P.IDPAIS AND ES.IDESTADO = P.IDESTADO
INNER JOIN <#SESSION.DB/>.dbo.USUARIOS U WITH (NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO
INNER  JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA WITH (NOLOCK) ON P.IDPROSPECTO = PA.IDPROSPECTO  


WHERE 
(
   (PA.IDUSUARIO IN (SELECT UM.ID  FROM @TABLAPRIVILEGIOS UM WHERE UM.TIPO=1)  AND P.ESCLIENTE=0) OR
   (PA.IDUSUARIO IN (SELECT UM.ID  FROM @TABLAPRIVILEGIOS UM WHERE UM.TIPO=2) AND P.ESCLIENTE=0 AND P.ESOPORTUNIDAD=1 ) OR
   (PA.IDUSUARIO IN (SELECT UM.ID  FROM @TABLAPRIVILEGIOS UM WHERE UM.TIPO=3) AND P.ESCLIENTE=1)
 
 ) AND
 P.IDPROSPECTO = PA.IDPROSPECTO AND  
 P.IDUSUARIO = U.IDUSUARIO AND P.DESCARTADO <= @DESCARTADOS AND (P.IDEMPRESA=@IDEMPRESA  
 AND 
  ( 
(LTRIM(RTRIM(P.NOMBRE)) + ' ' + LTRIM(RTRIM(P.APELLIDOS)) COLLATE Latin1_general_CI_AI like @TEXTO) OR
  ( P.NOMBRE COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.APELLIDOS  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.CORREO  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.EMPRESA  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.PUESTO  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.URL  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.TELEFONO COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.COMENTARIOS  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( P.MOVIL COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.DESCARTADORAZON COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO13  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.DIRECCION1 COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( P.DIRECCION2 COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( P.CIUDAD COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( P.CODIGOPOSTAL COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( PAI.PAIS COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( ES.ESTADO COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR 
  ( P.CAMPO14 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO15  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.CAMPO16  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.CAMPO17  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.CAMPO18  COLLATE Latin1_general_CI_AI LIKE @TEXTO) OR
  ( P.CAMPO19 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO20 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO26 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO27 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO28 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO29 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO30 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO31 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO32 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO33 COLLATE Latin1_general_CI_AI  LIKE @TEXTO) OR
  ( P.CAMPO34 COLLATE Latin1_general_CI_AI  LIKE @TEXTO)   
  )
)
