//[tkeliminar|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT 


DECLARE @TKELIMINAR VARCHAR(MAX) 
--DECLARE @TKNUEVO  VARCHAR(MAX) 

SET @TKELIMINAR=ISNULL(:TKELIMINAR, '') 

SELECT TKU, NOMBRE+', '+ APELLIDOS AS INTEGRANTE FROM <#SESSION.DB/>.DBO.USUARIOS WHERE TKU NOT IN (@TKELIMINAR) AND IDEMPRESA=<#SESSION.IDEMPRESA/>  ORDER BY NOMBRE ASC