//[session.convertcode|Untyped,session.db|Untyped,fecha_hasta|Text,fecha_desde|Text,tipo|Integer,idusuario|Integer,]
-- SELECT
DECLARE @TIPO INT
DECLARE @SQLTXT VARCHAR(MAX)
DECLARE @COMPLEMENTO VARCHAR(MAX)
--SELECT

DECLARE @CRITERIO VARCHAR(MAX)
DECLARE @CRITERIA VARCHAR(MAX)
DECLARE @IDUSUARIO INT
DECLARE @FECHA_INICIAL VARCHAR(1000)
DECLARE @FECHA_FINAL VARCHAR(1000)
DECLARE @SESSION VARCHAR(1000)
DECLARE @CONVERTCODE VARCHAR(1000)


SET @CONVERTCODE='<#SESSION.CONVERTCODE/>'
SET @SESSION='<#SESSION.DB/>'
SET @FECHA_FINAL =ISNULL(:FECHA_HASTA,'')
SET @FECHA_INICIAL=ISNULL(:FECHA_DESDE,'')
SET @TIPO=ISNULL(:TIPO,0)
SET @IDUSUARIO=ISNULL(:IDUSUARIO,0)

SET @COMPLEMENTO = ''
SELECT @CRITERIA=(CASE WHEN @TIPO=1 THEN 'AND (O.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND '+@SESSION+'.dbo.GETONLYDATE(O.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+') AND O.PERDIDA=0 AND O.GANADA=0' 
                  WHEN @TIPO=2 THEN 'AND (O.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND O.PERDIDA=1 AND O.GANADA=0 AND '+@SESSION+'.dbo.GETONLYDATE(O.PERDIDA_FECHA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')'			  
				  WHEN @TIPO=3 THEN ' AND (V.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND O.GANADA=1 AND '+@SESSION+'.dbo.GETONLYDATE(O.GANADA_FECHA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')'
				  ELSE '' END) 
	  

IF(@TIPO = 3)
BEGIN
	  SET @COMPLEMENTO = @SESSION+'.dbo.VENTAS V, '
	  SET @CRITERIO = ' V.IDOPORTUNIDAD = O.IDOPORTUNIDAD '+@CRITERIA+' AND '
END
ELSE
BEGIN
	 SET @CRITERIO = @CRITERIA
END

SET @SQLTXT = 'SELECT COUNT(*) AS TOTALN,'''+REPLACE(@CRITERIA,'''','''''')+''' AS CRITERIA, '''+@FECHA_INICIAL+''' AS FECHA_DESDE, '''+@FECHA_FINAL+''' AS FECHA_HASTA, '+CAST(@TIPO AS VARCHAR(1000))+' AS TIPO, '+CAST(@IDUSUARIO AS VARCHAR(1000))+' AS IDUSUARIO'
SET @SQLTXT = @SQLTXT + ' FROM ' 
SET @SQLTXT = @SQLTXT + @COMPLEMENTO+' '
SET @SQLTXT = @SQLTXT + @SESSION+'.dbo.OPORTUNIDADES O, '
SET @SQLTXT = @SQLTXT + @SESSION+'.dbo.PROSPECTOS P ,  '
SET @SQLTXT = @SQLTXT + @SESSION+'.dbo.USUARIOS U, '
SET @SQLTXT = @SQLTXT + @SESSION+'.dbo.OPORTUNIDADES_FASES F '

IF(@TIPO = 3)
BEGIN
	 SET @SQLTXT = @SQLTXT + ' WHERE '+@CRITERIO+' O.IDPROSPECTO = P.IDPROSPECTO AND O.IDUSUARIO=U.IDUSUARIO AND P.IDUSUARIO=O.IDUSUARIO AND O.IDFASE = F.IDFASE '
END 
ELSE
BEGIN
	 SET @SQLTXT = @SQLTXT + ' WHERE O.IDPROSPECTO = P.IDPROSPECTO AND O.IDUSUARIO=U.IDUSUARIO AND P.IDUSUARIO=O.IDUSUARIO AND O.IDFASE = F.IDFASE ' +@CRITERIO
END

 
IF (@TIPO IN (1,2,3)) 
  EXEC(@SQLTXT)
ELSE
  SELECT 0 AS TOTALN ,'''+@FECHA_INICIAL+''' AS FECHA_DESDE, '''+@FECHA_FINAL+''' AS FECHA_HASTA, '+CAST(@TIPO AS VARCHAR(1000))+' AS TIPO, '+CAST(@IDUSUARIO AS VARCHAR(1000))+' AS IDUSUARIO
