//[idetiqueta|Integer,tk|Text,idautoresponder|Integer,tkauto|Text,session.db|Untyped,session.idempresa|Untyped,condicion|Text,]
--SELECT 
/*PENDIENTE COOKIE*/
DECLARE @IDETIQUETA INT
DECLARE @TOTALN INT 
DECLARE @ACTIVAS INT
DECLARE @IDAUTORESPONDER INT
DECLARE @TKAUTO VARCHAR(128)
DECLARE @TK VARCHAR(128)
DECLARE @CONDICION VARCHAR(MAX)


SET @IDETIQUETA = ISNULL(:IDETIQUETA, 0)
SET @TK = ISNULL(:TK,'')
SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER, 0)
SET @TKAUTO = ISNULL(:TKAUTO,'')
SET @CONDICION = ISNULL(:CONDICION,'')

IF @TK != '' BEGIN SELECT @IDETIQUETA=IDETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE TK = @TK AND IDEMPRESA = <#SESSION.IDEMPRESA/> END
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END


SELECT @TOTALN = COUNT(IDAUTORESPONDER)
FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS 
WHERE IDAUTORESPONDER = @IDAUTORESPONDER

SELECT @ACTIVAS = COUNT(IDAUTORESPONDER)
FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS 
WHERE IDAUTORESPONDER = @IDAUTORESPONDER AND ESTADO = 1

SELECT @TOTALN AS TOTALN , @ACTIVAS AS ACTIVAS, @IDETIQUETA AS IDETIQUETA, @TK AS TK, @IDAUTORESPONDER AS IDAUTORESPONDER, @TKAUTO AS TKAUTO ,@CONDICION AS CONDICION