//[session.idempresa|Untyped,tk|Text,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 
DECLARE @TKTITULO VARCHAR(256) 
DECLARE @TITULO VARCHAR(MAX)

SET @IDEMPRESA= <#SESSION.IDEMPRESA/>
SET @TKTITULO=ISNULL(:TK, '') 
SELECT @TITULO=TITULO FROM <#SESSION.DB/>.DBO.EMPRESAS_TITULOS WHERE IDEMPRESA=@IDEMPRESA AND TKTI=@TKTITULO 
SELECT COUNT(*) as total FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDEMPRESA=@IDEMPRESA AND TITULO=@TITULO
 