//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 
DECLARE @SQL VARCHAR(MAX)
SET @IDEMPRESA =<#SESSION.IDEMPRESA/>

SET @SQL='SELECT GRUPO, CASE WHEN AUDITADO = 1 THEN 1 ELSE '''' END AS AUDITADO,CAST(TK AS VARCHAR(MAX)) AS TK, IDUSUARIOGRUPO
 FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA ='+CAST( @IDEMPRESA AS VARCHAR(MAX))
EXEC (@SQL)

