//[session.db|Untyped,grupo|Text,session.idempresa|Untyped,auditar|Integer,actualiza|Integer,tk|Text,]
--INSERT

DECLARE @GRUPO VARCHAR(MAX) 
DECLARE @IDEMPRESA INT 
DECLARE @AUDITAR INT 
DECLARE @ACTUALIZAR INT 
DECLARE @TK VARCHAR(256) 

SET @GRUPO = ISNULL(:GRUPO, '') 
SET @GRUPO=<#SESSION.DB/>.DBO.PREPARACADENA(@GRUPO)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @AUDITAR = ISNULL(:AUDITAR, '') 
SET @ACTUALIZAR= ISNULL(:ACTUALIZA, 0)
SET @TK=ISNULL(:TK, '')  

IF(@ACTUALIZAR=0) 
 BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_GRUPOS (GRUPO,IDEMPRESA,AUDITADO)
  VALUES (@GRUPO, @IDEMPRESA, @AUDITAR) 
  END
ELSE 
 BEGIN
   UPDATE <#SESSION.DB/>.DBO.USUARIOS_GRUPOS 
   SET GRUPO=@GRUPO, 
   AUDITADO=@AUDITAR
   WHERE IDEMPRESA=@IDEMPRESA AND  TK=@TK
 END 
