//[session.db|Untyped,session.idempresa|Untyped,tk|Text,]
--SELECT 


DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(MAX) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TK=ISNULL(:TK, '') 



SELECT GRUPO, CAST(TK AS VARCHAR(MAX)) AS TK, AUDITADO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA AND TK=@TK