//[session.idempresa|Untyped,tknuevo|Text,session.db|Untyped,tkeliminar|Text,]
--UPDATE
DECLARE @IDUSUARIOGRUPO INT
DECLARE @GRUPONUEVO INT
DECLARE @IDEMPRESA INT
DECLARE @AUDITADOOLD INT
DECLARE @AUDITADONEW INT

DECLARE @TK VARCHAR(MAX) 
DECLARE @TKNUEVO VARCHAR(MAX)



SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TK=ISNULL(:TKELIMINAR, '') 
SET @TKNUEVO=ISNULL(:TKNUEVO, '') 

SELECT @IDUSUARIOGRUPO=IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE CAST(TK AS VARCHAR(MAX)) =@TK
SELECT @GRUPONUEVO=IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE CAST(TK AS VARCHAR(MAX))=@TKNUEVO



SELECT @AUDITADOOLD=AUDITADO FROM <#SESSION.DB/>.dbo.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO=@IDUSUARIOGRUPO AND IDEMPRESA = @IDEMPRESA
SELECT @AUDITADONEW=AUDITADO FROM <#SESSION.DB/>.dbo.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO=@GRUPONUEVO AND IDEMPRESA = @IDEMPRESA

IF (@AUDITADOOLD!=@AUDITADONEW AND @AUDITADOOLD=1)
 BEGIN
  UPDATE <#SESSION.DB/>.dbo.VENTAS_COBROS SET AUDITADO=1
   WHERE IDVENTACOBRO IN 
	(SELECT VC.IDVENTACOBRO FROM <#SESSION.DB/>.dbo.USUARIOS U,<#SESSION.DB/>.dbo.VENTAS V, <#SESSION.DB/>.dbo.VENTAS_COBROS VC 
		WHERE U.IDGRUPO=@IDUSUARIOGRUPO AND 
			  U.IDEMPRESA=@IDEMPRESA AND 
			  V.IDUSUARIO=U.IDUSUARIO AND 
			  VC.IDVENTA=V.IDVENTA AND 
			  VC.AUDITADO=0 AND VC.PAGADO=1
	 ) 
 END 

-- delete
update <#SESSION.DB/>.DBO.usuarios set idgrupo = @GRUPONUEVO where IDEMPRESA = @IDEMPRESA and idgrupo = @IDUSUARIOGRUPO
update <#SESSION.DB/>.DBO.EMPRESAS_DOCUMENTOS set idgrupo = @GRUPONUEVO where IDEMPRESA = @IDEMPRESA and idgrupo = @IDUSUARIOGRUPO
DELETE FROM <#SESSION.DB/>.DBO.usuarios_metas where idempresa = @IDEMPRESA and idgrupo = @IDUSUARIOGRUPO
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA and IDUSUARIOGRUPO=@IDUSUARIOGRUPO


