//[tk|Text,session.idempresa|Untyped,session.db|Untyped,]
--DELETE 



DECLARE @TK VARCHAR(256) 
DECLARE @IDEMPRESA INT 

SET @TK=ISNULL(:TK, '') 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA= @IDEMPRESA AND TK=@TK 