//[session.db|Untyped,session.idempresa|Untyped,]


SELECT <#SESSION.DB/>.DBO.USUARIOS.IDUSUARIO,<#SESSION.DB/>.DBO.USUARIOS.NIVEL,<#SESSION.DB/>.DBO.USUARIOS.VERSISTEMA, <#SESSION.DB/>.DBO.USUARIOS.NOMBRE+' '+<#SESSION.DB/>.DBO.USUARIOS.APELLIDOS AS NOMBRE, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS.IDUSUARIOGRUPO,
<#SESSION.DB/>.DBO.USUARIOS_GRUPOS.GRUPO FROM <#SESSION.DB/>.DBO.USUARIOS INNER JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS
ON <#SESSION.DB/>.DBO.USUARIOS.IDGRUPO = <#SESSION.DB/>.DBO.USUARIOS_GRUPOS.IDUSUARIOGRUPO
WHERE <#SESSION.DB/>.DBO.USUARIOS.IDEMPRESA = <#SESSION.IDEMPRESA/> ORDER BY NOMBRE ASC

