//[tku|Text,session.db|Untyped,tipo|Integer,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/

DECLARE @TKU VARCHAR(MAX) 
DECLARE @TIPO INT 

SET @TKU =ISNULL(:TKU, '') 
SET @TIPO=ISNULL(:TIPO, 0) 

EXEC <#SESSION.DB/>.dbo.SP_ACTIVA_DESACTIVA_USUARIO @TKU,@TIPO
