//[session.idempresa|Untyped,tk|Text,session.db|Untyped,]
--SELECT 

DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(MAX) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TK=ISNULL(:TK, '') 

SELECT GRUPO, CAST(TK AS VARCHAR(MAX)) AS TK FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA= @IDEMPRESA  AND CAST(TK AS VARCHAR(256)) NOT IN (@TK) ORDER BY GRUPO ASC 