//[fase|Text,session.db|Untyped,session.idempresa|Untyped,]
--INSERT
DECLARE @MAXIMO INT
DECLARE @FASE VARCHAR(64)

SET @FASE = ISNULL(:FASE,'')

/* SELECCIONAR EL MAXIMO */
SELECT @MAXIMO = MAX(ORDEN) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/>

/* INSERTAR SIG FASE */
insert into <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES(IDEMPRESA,FASE,ORDEN) values ('<#SESSION.IDEMPRESA/>',@FASE,@MAXIMO+1)
