//[tk|Text,tknvafase|Text,session.idempresa|Untyped,session.db|Untyped,]
-- DELETE
DECLARE @TK VARCHAR(256)
DECLARE @TKnvafase  VARCHAR(256)
DECLARE @IDFASE   INT 
DECLARE @IDFASENUEVA INT 
DECLARE @IDEMPRESA INT 

SET @TK=ISNULL(:TK, '')
SET @TKnvafase = ISNULL(:TKnvafase,'')
SET @IDEMPRESA= <#SESSION.IDEMPRESA/>
SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TK
SELECT @IDFASENUEVA=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TKnvafase 



UPDATE  <#SESSION.DB/>.DBO.OPORTUNIDADES SET IDFASE = @IDFASENUEVA, CAMBIOLOCAL=(CASE WHEN TKOM IS NOT NULL THEN 1 ELSE 0 END) WHERE   IDFASE = @IDFASE
UPDATE  <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES SET ORDEN = ORDEN - 1 WHERE IDEMPRESA = @IDEMPRESA AND ORDEN > (SELECT ORDEN FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDFASE = @IDFASE)

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (11,@IDFASENUEVA,@IDFASENUEVA,1,@IDEMPRESA,GETDATE())

DELETE FROM  <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDFASE=  @IDFASE AND IDEMPRESA=@IDEMPRESA