//[tk|Text,tkfasenuevo|Text,session.idempresa|Untyped,session.db|Untyped,]
--DELETE

DECLARE @IDFASE INT 
DECLARE @IDFASENUEVO INT
DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(MAX) 
DECLARE @TKFASENUEVO VARCHAR(MAX) 


SET @TK=ISNULL(:TK, '') 
SET @TKFASENUEVO =ISNULL(:TKFASENUEVO, '') 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SELECT @IDFASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
WHERE TK=@TK AND IDEMPRESA=@IDEMPRESA

SELECT @IDFASENUEVO=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE TK=@TKFASENUEVO  AND IDEMPRESA=@IDEMPRESA

UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET IDFASE = @IDFASENUEVO, CAMBIOLOCAL=(CASE WHEN TKPM IS NOT NULL THEN  1 ELSE 0 END) WHERE IDEMPRESA=@IDEMPRESA AND IDFASE =@IDFASE  
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_FASES SET ORDEN = ORDEN - 1 WHERE IDEMPRESA = @IDEMPRESA AND ORDEN > (SELECT ORDEN from <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE =@IDFASE)  AND FASECLIENTE=0

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (9, @IDFASENUEVO,@IDFASE,1,@IDEMPRESA,GETDATE())

DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE = @IDFASE AND IDEMPRESA=@IDEMPRESA

