//[session.db|Untyped,session.idempresa|Untyped,fase|Text,]
--INSERT
DECLARE @MAXIMO INT

/* SELECCIONAR EL MAXIMO */
SELECT @MAXIMO = MAX(ORDEN) FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> and FASECLIENTE=0

/* INSERTAR SIG FASE */
insert into <#SESSION.DB/>.DBO.PROSPECTOS_FASES(IDEMPRESA,FASE,ORDEN) values (<#SESSION.IDEMPRESA/>,:FASE,@MAXIMO+1)
