//[session.db|Untyped,tk|Text,session.idempresa|Untyped,]
--select
DECLARE @TK VARCHAR(MAX) 
DECLARE @IDEMPRESA INT 

SET @TK=ISNULL(:TK, '')
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SELECT * FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TK AND IDEMPRESA=@IDEMPRESA 