//[tk|Text,session.db|Untyped,session.idempresa|Untyped,]
--UPDATE


DECLARE @ACTUAL INT
DECLARE @TK VARCHAR(256)
DECLARE @IDEMPRESA INT 
DECLARE @IDACTUAL INT
DECLARE @IDANTERIOR INT 
 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TK = ISNULL(:TK,'')
SELECT @ACTUAL=ORDEN FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK=@TK and IDEMPRESA=@IDEMPRESA
SELECT @IDANTERIOR=IDFASE  FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA=@IDEMPRESA AND ORDEN=@ACTUAL+1



IF @ACTUAL  < (SELECT MAX(ORDEN) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>)
BEGIN
  UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES SET ORDEN=@ACTUAL+1 WHERE IDEMPRESA = @IDEMPRESA AND TK=@TK 
  UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES SET ORDEN=ORDEN-1 WHERE IDEMPRESA=@IDEMPRESA AND IDFASE=@IDANTERIOR
END


