//[tk|Text,session.idempresa|Untyped,session.db|Untyped,fase|Text,]
--UPDATE
DECLARE @TK VARCHAR(256) 
DECLARE @IDEMPRESA INT 

SET @TK=ISNULL(:TK, '')
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES 
SET FASE = isnull(:FASE, '') 
WHERE TK = @TK AND IDEMPRESA=@IDEMPRESA