//[session.db|Untyped,session.idempresa|Untyped,fase|Text,]
--INSERT
DECLARE @MAXIMO INT

/* SELECCIONAR EL MAXIMO */
SELECT @MAXIMO = MAX(ORDEN) FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> and FASECLIENTE=1

IF @MAXIMO IS NULL
  SET @MAXIMO=0

/* INSERTAR SIG FASE */
insert into <#SESSION.DB/>.DBO.PROSPECTOS_FASES(IDEMPRESA,FASE,ORDEN,FASECLIENTE) values ('<#SESSION.IDEMPRESA/>',ISNULL(:FASE,''),@MAXIMO+1,1)
