//[session.idempresa|Untyped,session.db|Untyped,fase|Text,tipofase|Integer,]
--SELECT
DECLARE @IDEMPRESA INT, @ORDEN INT, @TIPOFASE INT, @EXISTE INT
DECLARE @FASE VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @FASE = <#SESSION.DB/>.dbo.PreparaCadena(:FASE)
SET @TIPOFASE = CAST(isnull(:TipoFase,0) AS INT)

SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.PROSPECTOS_FASES WHERE IDEMPRESA = @IDEMPRESA AND FASE = @FASE AND FASECLIENTE = @TIPOFASE

SELECT @ORDEN = MAX(ORDEN) FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> and FASECLIENTE = @TIPOFASE

IF @ORDEN IS NULL
  SET @ORDEN = 0

IF @EXISTE = 0
BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_FASES(IDEMPRESA, FASE, ORDEN, FASECLIENTE) 
  VALUES (@IDEMPRESA, @FASE, @ORDEN+1, @TIPOFASE)
END

SELECT TOP 1 IdFase AS Id FROM <#SESSION.DB/>.dbo.PROSPECTOS_FASES 
WHERE IDEMPRESA = @IDEMPRESA AND FASE = @FASE AND FASECLIENTE = @TIPOFASE 
ORDER BY 1 DESC
