//[]
--UPDATE
DECLARE @PROPID INT
SELECT TOP 1 @PROPID  = IDVENTAIMPORTACION FROM <#SESSION.DB/>.DBO.VENTAS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> ORDER BY IDVENTAIMPORTACION
SELECT @PROPID
IF @PROPID IS NOT NULL
  DELETE FROM <#SESSION.DB/>.DBO.VENTAS_IMPORTACION WHERE IDVENTAIMPORTACION = @PROPID
