//[session.db|Untyped,session.idempresa|Untyped,condicioncampo|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :CONDICIONCAMPO , '')

SET @SQL = '

SELECT ISNULL(LLAVE,0) AS LLAVE, ISNULL(VALIDACION,''class="adicional"'') AS VALIDACION, 
EC.LLAVE AS RES, 
CASE WHEN INDICE BETWEEN 1 AND 4 THEN ''Entero''
WHEN INDICE BETWEEN 5 AND 8 THEN ''Decimal''
WHEN INDICE BETWEEN 9 AND 12 THEN ''Fecha''
WHEN (INDICE BETWEEN 13 AND 20) OR (INDICE BETWEEN 26 AND 32) THEN ''Texto''
WHEN INDICE >= 21 AND INDICE < 26 THEN ''Lista''
WHEN INDICE = 33 THEN ''Autoincrementable''
WHEN INDICE = 34 THEN ''UUID''
END AS TIPOCAMPO,
CASE WHEN INDICE BETWEEN 1 AND 4 THEN 1
WHEN INDICE BETWEEN 5 AND 8 THEN 2
WHEN INDICE BETWEEN 9 AND 12 THEN 3
WHEN (INDICE BETWEEN 13 AND 20) OR (INDICE BETWEEN 26 AND 32) THEN 4
WHEN INDICE >= 21 AND INDICE < 26 THEN 5
WHEN INDICE = 33 THEN 6
WHEN INDICE = 34 THEN 7
END AS TIPO, 
EC.NOMBRE_CAMPO AS CAMPO,
TIPO AS VEREN,
CASE COMPARTIR WHEN 0 THEN '''' ELSE CAST(COMPARTIR AS VARCHAR(MAX)) END AS COMPARTIR,
EC.* 
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC 
WHERE EC.IDEMPRESA = <#SESSION.IDEMPRESA/> AND CAST(INDICE AS INT)>0  ' + @CRIT 


EXEC (@SQL) 