//[session.idempresa|Untyped,nombrecampo|Text,descripcion|Text,veren|Integer,tambienen|Integer,tambientab|Integer,idtabs|Integer,tipocampo|Integer,restriccion|Integer,tamanio|Integer,generaranteriores|Integer,empiezaen|Integer,tamanio_campo|Text,configuracion_campo|Text,placeholder|Integer,session.db|Untyped,]
--insert
DECLARE @NOMBRECAMPO VARCHAR(100), @DESCRIPCION VARCHAR(500), @VALIDACION VARCHAR(500), @TIPOS VARCHAR(MAX), @CONFIGURACION_CAMPO VARCHAR(MAX), @TAMANIO_CAMPO VARCHAR(4), @SQLCOMPLEMENTO VARCHAR(MAX)
DECLARE @VEREN INT, @COMPARTIR INT, @IDTAB INT, @TIPOCAMPO INT, @OBLIGATORIO INT, @TAMANIO INT, @IND INT, @ID INT, @CONTA INT, @CONTTXT INT
DECLARE @IDEMPRESA INT, @IDCAMPO INT, @EXISTE INT, @GenerarAnteriores INT, @EmpiezaEn INT, @TIPO_CAMPO INT, @PLACEHOLDER INT, @TambienTab INT


SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @VALIDACION = ''
SET @NOMBRECAMPO = :NOMBRECAMPO
SET @DESCRIPCION = :DESCRIPCION
SET @VEREN = isnull(:VerEn,0)
SET @COMPARTIR = isnull(:TambienEn,0)
SET @TambienTab = ISNULL(:TambienTab,0)

SET @IDTAB = ISNULL(:IDTABS,0)
SET @TIPOCAMPO = ISNULL(:TipoCampo,0)
SET @OBLIGATORIO = ISNULL(:Restriccion,0)
SET @TAMANIO = ISNULL(:TAMANIO,0)
SET @GenerarAnteriores = ISNULL(:GenerarAnteriores,0) 
SET @EmpiezaEn = ISNULL(:EmpiezaEn,0)
SET @TAMANIO_CAMPO = ISNULL(:Tamanio_Campo,'')
SET @CONFIGURACION_CAMPO = ISNULL(:Configuracion_Campo,'')
SET @PLACEHOLDER = ISNULL(:PlaceHolder,0)

IF @TIPOCAMPO IN (1,2,3,4,6,7) SET @TIPO_CAMPO = 1
IF @TIPOCAMPO =  5 SET @TIPO_CAMPO = 2
IF @TIPOCAMPO =  8 SET @TIPO_CAMPO = 6
IF @TIPOCAMPO =  9 SET @TIPO_CAMPO = 9
IF @TIPOCAMPO = 10 SET @TIPO_CAMPO = 8
IF @TIPOCAMPO = 11 SET @TIPO_CAMPO = 4
IF @TIPOCAMPO = 12 SET @TIPO_CAMPO = 3
IF @TIPOCAMPO = 13 SET @TIPO_CAMPO = 7
IF @TIPOCAMPO = 14 SET @TIPO_CAMPO = 5

IF @TIPOCAMPO = 1 BEGIN SET @IND =  1 END
IF @TIPOCAMPO IN (2,9) BEGIN SET @IND =  5 END
IF @TIPOCAMPO = 3 BEGIN SET @IND =  9 END
IF @TIPOCAMPO IN (4,8,10,11,12,13,14) BEGIN SET @IND = 13 END
IF @TIPOCAMPO = 6 BEGIN SET @IND = 33 SET @ID = @IND END
IF @TIPOCAMPO = 7 BEGIN SET @IND = 34 SET @ID = @IND END

SET @TIPOS = '1,3'
IF @VEREN IN (2,4) BEGIN SET @TIPOS = '2,4' END

SET @CONTA = @IND
SET @CONTTXT = @CONTA

IF @TIPOCAMPO NOT IN (4,8,10,11,12,13,14)
BEGIN
  WHILE @ID IS NULL AND @CONTA < 21
  BEGIN
	SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND INDICE = @CONTA AND TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@TIPOS,',') )
  	IF @EXISTE = 0 BEGIN SET @ID = @CONTA END
    SET @CONTA = @CONTA + 1
  END
END
ELSE
BEGIN
   WHILE @ID IS NULL AND @CONTA < 64
   BEGIN
    SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND INDICE = @CONTA AND TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@TIPOS,',') )
    IF @EXISTE = 0 BEGIN SET @ID = @CONTA END 
    IF @CONTA = 20 BEGIN SET @CONTA = 25 END
    IF @CONTA = 32 BEGIN SET @CONTA = 34 END
    SET @CONTA = @CONTA + 1
   END
END

INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS (IDEMPRESA, INDICE, NOMBRE_CAMPO, DESCRIPCION, LLAVE, VALIDACION, LARGO, TIPO, CONSECUTIVO, TAMBIENEN_IDTAB, COMPARTIR, ORDEN, IDTAB, TIPO_CAMPO, TAMANIO, CONFIGURACION_CAMPO, PLACEHOLDER) 
VALUES (@IDEMPRESA, @ID, @NOMBRECAMPO, @DESCRIPCION, @OBLIGATORIO, @VALIDACION , @TAMANIO, @VEREN, @EmpiezaEn, @TambienTab, @COMPARTIR, 999, @IDTAB, @TIPO_CAMPO, @TAMANIO_CAMPO, @CONFIGURACION_CAMPO, @PLACEHOLDER)

SELECT TOP 1 @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA ORDER BY IDCAMPO DESC

EXEC <#SESSION.DB/>.dbo.SP_GENERA_AUTO_UUID @VEREN, @COMPARTIR, @IDEMPRESA, @EmpiezaEn, @IDCAMPO, @TIPOCAMPO, @GenerarAnteriores, 1

EXEC <#SESSION.DB/>.dbo.SP_AGREGA_COLUMAS_PERSONALIZADA @IDEMPRESA , @IDCAMPO