//[idcampo|Integer,tipo|Integer,idcampocon|Integer,tamanio_campo|Text,ligar_empresa|Integer,session.db|Untyped,session.idempresa|Untyped,mostrar|Integer,]
--UPDATE
DECLARE @IDCAMPO INT
DECLARE @IDCAMPOCON INT
DECLARE @TIPO INT
DECLARE @VALIDACION VARCHAR(256)
DECLARE @TAMANIO_CAMPO VARCHAR(5)
DECLARE @LIGAR_EMPRESA INT
DECLARE @IDBUSCAHERMANO INT
DECLARE @MOSTRARCAMPO INT 


SET @IDCAMPO = ISNULL(:IDCAMPO,0)
SET @TIPO = ISNULL(:TIPO,0)
SET @IDCAMPOCON =ISNULL(:IDCAMPOCON,0)
SET @TAMANIO_CAMPO = ISNULL(:Tamanio_Campo,'')
SET @LIGAR_EMPRESA = ISNULL(:ligar_empresa, '')
SET @MOSTRARCAMPO = ISNULL(:MOSTRAR, 1);


IF @TIPO = 0 SET @VALIDACION = ''

IF @TIPO = 1 SET @VALIDACION = 'llave'

IF @TIPO = 2 SET @VALIDACION = 'obligatorio'

IF @TIPO = 3 SET @VALIDACION = 'llave obligatorio'

IF @TIPO = 4 SET @VALIDACION = 'sugerido'

SELECT @MOSTRARCAMPO = MOSTRAR FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION WHERE IDCAMPOCON=@IDCAMPO
SET @MOSTRARCAMPO=(CASE WHEN @TIPO IN (0,4) THEN @MOSTRARCAMPO WHEN @TIPO IN (1,2,3) THEN 1 END)

SELECT TOP 1 @IDBUSCAHERMANO = IDCAMPOCON FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION WHERE IDCAMPOCON != @IDCAMPOCON AND CAMPO = @IDCAMPO AND IDEMPRESA = <#SESSION.IDEMPRESA/> and idtab is not null

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION 
SET IDEMPRESA = <#SESSION.IDEMPRESA/>,
CAMPO = @IDCAMPO,
MOSTRAR=@MOSTRARCAMPO,
TIPO = @TIPO,
VALIDACION = @VALIDACION, 
TAMANIO = @TAMANIO_CAMPO,
LIGAR = @LIGAR_EMPRESA
WHERE IDCAMPOCON = @IDCAMPOCON

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION 
SET IDEMPRESA = <#SESSION.IDEMPRESA/>,
CAMPO = @IDCAMPO,
MOSTRAR=@MOSTRARCAMPO,
TIPO = @TIPO,
VALIDACION = @VALIDACION, 
TAMANIO = @TAMANIO_CAMPO,
LIGAR = @LIGAR_EMPRESA
WHERE IDCAMPOCON = @IDBUSCAHERMANO