//[session.db|Untyped,session.idempresa|Untyped,]
SELECT EC.NOMBRE_CAMPO AS NOMBRECAMPO, 
CASE 
	 WHEN EC.TIPO IN (1,3) THEN 'CP'+CAST(EC.INDICE AS VARCHAR(12))
	 WHEN EC.TIPO IN (2,4) THEN 'CPO'+CAST(EC.INDICE AS VARCHAR(12))
END AS CAMPO
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC 
WHERE EC.IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT) AND TIPO != 5