//[session.db|Untyped,session.idempresa|Untyped,indice|Integer,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @INDICE INT
SET @INDICE = isnull(:INDICE,0)
SELECT * FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDCAMPO = (SELECT IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND INDICE = @INDICE)