//[session.idempresa|Untyped,session.db|Untyped,condicioncampos|Text,]
--select 
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @CRIT = ISNULL( :CONDICIONCAMPOS , '')

SET @SQL = '
DECLARE @IDEMPRESA INT

SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)

SELECT 
CASE EC.VALIDACION 
WHEN '''' THEN ''SIN'' ELSE EC.VALIDACION END VALIDACION 
, EC.* , C.CAMPO AS NOMBRE, C.OCULTAR, C.TIP,
CASE 
WHEN (EC.CAMPO = 4) OR (EC.CAMPO = 5)  OR (EC.CAMPO = 18) OR (EC.CAMPO = 19) OR (EC.CAMPO = 20) OR 
	 (EC.CAMPO = 21) OR (EC.CAMPO = 22) OR (EC.CAMPO = 23)  OR (EC.CAMPO = 29) OR 
	 (EC.CAMPO = 30)
THEN ''1''
ELSE ''0''
END AS NOUNICOS
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION EC , SALESUP_CT.DBO.CAMPOS C
WHERE (IDEMPRESA = @IDEMPRESA) AND EC.CAMPO = C.IDCAMPO  ' +  @CRIT+ ' 
ORDER BY  C.OCULTAR DESC, 4 ASC
'
  
EXEC (@SQL)