//[idcampo|Integer,tamanio|Integer,descripcion|Text,nombrecampo|Text,session.idempresa|Untyped,restriccion|Integer,session.db|Untyped,tamanio_campo|Text,]
--update
/*PROTEGIDO*/
DECLARE @OPCIONESVALORES VARCHAR(8000), @DESCRIPCION VARCHAR(128), @CAMPO VARCHAR(128), @VALIDACION VARCHAR(1024), @Tamanio_Campo varchar(max)
DECLARE @OBLIGATORIO INT, @INDICE INT, @NCARACTERES INT, @IDEMPRESA INT, @IDCAMPO INT, @ELIMINAROPCION INT, @NUEVOIDOPCION INT, @VIEJOIDOPCION INT
DECLARE @VEREN INT, @COMPARTIR INT, @GenerarAnteriores INT, @EmpiezaEn INT, @TipoCampo int
DECLARE @SQLUPDATE VARCHAR(MAX)

SET @IDCAMPO = :IDCAMPO
SET @NCARACTERES = ISNULL(:TAMANIO,0) 
SET @DESCRIPCION = :DESCRIPCION
SET @CAMPO = :NOMBRECAMPO
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @OBLIGATORIO = ISNULL(:Restriccion,0)

set @Tamanio_Campo = isnull(:Tamanio_Campo,'')


UPDATE <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS
SET NOMBRE_CAMPO = @CAMPO,
DESCRIPCION = @DESCRIPCION,
LLAVE = @OBLIGATORIO,
LARGO = @NCARACTERES,
TAMANIO = @Tamanio_Campo
WHERE IDEMPRESA = @IDEMPRESA
AND IDCAMPO = @IDCAMPO




