//[session.idempresa|Untyped,idcampo|Integer,nombrecampo|Text,descripcion|Text,opcionesvalores|Text,tamanio|Integer,eliminaropcion|Integer,nuevoidopcion|Integer,viejoidopcion|Integer,indice|Integer,restriccion|Integer,veren|Integer,tambienen|Integer,tambientab|Integer,generaranteriores|Integer,empiezaen|Integer,idtabs|Integer,tipocampo|Integer,tamanio_campo|Text,configuracion_campo|Text,nuevaopcion|Text,viejaopcion|Text,placeholder|Integer,session.db|Untyped,]
--update
DECLARE @IDCAMPO INT
DECLARE @IDEMPRESA INT
DECLARE @INDICE INT
DECLARE @VEREN INT
DECLARE @COMPARTIR INT
DECLARE @IDTAB INT
DECLARE @LARGO INT
DECLARE @OBLIGATORIO INT
DECLARE @NCARACTERES INT
DECLARE @GenerarAnteriores INT
DECLARE @EmpiezaEn INT, @TambienTab INT


DECLARE @ELIMINAROPCION INT
DECLARE @NUEVOIDOPCION INT
DECLARE @VIEJOIDOPCION INT

DECLARE @TAMANIO_CAMPO VARCHAR(4)
DECLARE @CONFIGURACION_CAMPO VARCHAR(MAX)
DECLARE @OPCIONESVALORES VARCHAR(8000)
DECLARE @DESCRIPCION VARCHAR(128)
DECLARE @NOMBRECAMPO VARCHAR(128)
DECLARE @VALIDACION VARCHAR(1024)
DECLARE @NUEVAOPCION VARCHAR(MAX)
DECLARE @VIEJAOPCION VARCHAR(MAX)
DECLARE @TipoCampo INT
DECLARE @PLACEHOLDER INT


SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDCAMPO = :IDCAMPO
SET @NOMBRECAMPO = :NOMBRECAMPO
SET @DESCRIPCION = :DESCRIPCION
SET @OPCIONESVALORES = :OPCIONESVALORES


SET @NCARACTERES = ISNULL(:TAMANIO,0) 
SET @ELIMINAROPCION = ISNULL(:ELIMINAROPCION,0)  
SET @NUEVOIDOPCION = ISNULL(:NUEVOIDOPCION,0)  
SET @VIEJOIDOPCION = ISNULL(:VIEJOIDOPCION,0)  
SET @INDICE =  ISNULL(:INDICE,0)  
SET @OBLIGATORIO = ISNULL(:Restriccion,0)  
SET @VEREN =  ISNULL(:VerEn,0)  
SET @COMPARTIR = ISNULL(:TambienEn,0)  
SET @TambienTab = ISNULL(:TambienTab,0)   
SET @GenerarAnteriores = ISNULL(:GenerarAnteriores,0)  
SET @EmpiezaEn = ISNULL(:EmpiezaEn,0) 
SET @IDTAB = ISNULL(:IDTABS,0) 
SET @TipoCampo = ISNULL(:TipoCampo,0) 
SET @TAMANIO_CAMPO = ISNULL(:Tamanio_Campo,'')
SET @CONFIGURACION_CAMPO = ISNULL(:Configuracion_Campo,'')
SET @NUEVAOPCION = ISNULL(:nuevaopcion,'')
SET @VIEJAOPCION = ISNULL(:viejaopcion,'')
SET @PLACEHOLDER = ISNULL(:PlaceHolder,0)  

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS
SET NOMBRE_CAMPO = @NOMBRECAMPO,
DESCRIPCION = @DESCRIPCION,
LLAVE = @OBLIGATORIO,
VALIDACION = @VALIDACION,
LARGO = @NCARACTERES,
TIPO = @VEREN, 
CONSECUTIVO = @EmpiezaEn,
TAMBIENEN_IDTAB = @TambienTab,
COMPARTIR = @COMPARTIR,
IDTAB = @IDTAB,
TAMANIO = @TAMANIO_CAMPO ,
CONFIGURACION_CAMPO = @CONFIGURACION_CAMPO,
PLACEHOLDER = @PLACEHOLDER
WHERE IDEMPRESA = @IDEMPRESA
AND IDCAMPO = @IDCAMPO

IF @INDICE >= 21
BEGIN
	 IF @OPCIONESVALORES <> ''
	   INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES (IDCAMPO, OPCION)
	   SELECT @IDCAMPO, SplitValue FROM <#SESSION.DB/>.dbo.Split(@OPCIONESVALORES,'|') 				   
END
DECLARE @STRSQL VARCHAR(MAX)
IF @ELIMINAROPCION = 1
BEGIN
	 SET @STRSQL = ' UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET CAMPO'+CAST(@INDICE AS VARCHAR(MAX))+' = '+CAST(@NUEVOIDOPCION AS VARCHAR(MAX))+', ULTIMAMODIFICACION = GETDATE() WHERE CAMPO'+CAST(@INDICE AS VARCHAR(MAX))+' = '+CAST(@VIEJOIDOPCION  AS VARCHAR(MAX))
	EXEC (@STRSQL)
	
	DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
	INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE())
	 
 	DELETE FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES WHERE IDOPCION = @VIEJOIDOPCION
	INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (23,@VIEJOIDOPCION,1,<#SESSION.IDEMPRESA/>,GETDATE())
END

IF @NUEVAOPCION != ''
BEGIN
     SET @STRSQL = 'UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET CAMPO'+CAST(@INDICE AS VARCHAR(MAX))+' = '+@NUEVAOPCION+', ULTIMAMODIFICACION = GETDATE() WHERE CAMPO'+CAST(@INDICE AS VARCHAR(MAX))+' = '+@VIEJAOPCION
	 EXEC (@STRSQL)
	 
	 DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
	 INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE())
END

EXEC <#SESSION.DB/>.dbo.SP_GENERA_AUTO_UUID @VEREN, @COMPARTIR, @IDEMPRESA, @EmpiezaEn, @IDCAMPO, @TIPOCAMPO, @GenerarAnteriores, 0

