//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT EC.IDCAMPOCON AS Id, C.CAMPO AS Campo, C.IDCAMPO, EC.Validacion, 
CASE WHEN EC.TIPO = 0 THEN '1' ELSE '' END AS SinRestriccion,
CASE WHEN EC.TIPO = 1 THEN '1' ELSE '' END AS Unico,
CASE WHEN EC.TIPO = 2 THEN '1' ELSE '' END AS Obligatorio,
CASE WHEN EC.TIPO = 3 THEN '1' ELSE '' END AS UnOb,
CASE WHEN C.Ocultar = 1 THEN '1' ELSE '' END AS Ocultar,
CASE WHEN EC.Mostrar = 1 THEN '1' ELSE '' END AS Ver,
CASE WHEN EC.Mostrar = 0 THEN '1' ELSE '' END AS NoVer
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION EC , SALESUP_CT.DBO.CAMPOS C
WHERE EC.CAMPO = C.IDCAMPO AND IDEMPRESA = @IDEMPRESA
ORDER BY C.Ocultar DESC