//[session.idempresa|Untyped,idcampo|Text,session.db|Untyped,indice|Text,]
--insert
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :INDICE , '')

SET @SQL = '

DECLARE @VENTANA INT, @COMPARTIR INT, @IDEMPRESA INT, @IDCAMPO INT
SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)
SET @IDCAMPO = CAST(''' +  ISNULL(:IDCAMPO, 0) + ''' AS INT)

SELECT @VENTANA = TIPO, @COMPARTIR = COMPARTIR FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WITH(NOLOCK) WHERE IDCAMPO = @IDCAMPO

IF @VENTANA IN (1,3)
BEGIN
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET CAMPO'+@CRIT+' = NULL WHERE IDEMPRESA = @IDEMPRESA
END


IF @VENTANA IN (2,4)
BEGIN
	UPDATE O WITH(ROWLOCK) SET O.CAMP'+@CRIT+'  = NULL
	FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O
	JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO
	WHERE P.IDEMPRESA = @IDEMPRESA
END

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO
DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO
DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WITH(ROWLOCK) WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES WITH(ROWLOCK) (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE())

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK) 
(IDTABLA,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (22, @IDCAMPO, 1, @IDEMPRESA, GETDATE())

' 
SELECT @SQL