//[idcampo|Integer,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDCAMPO INT
SET @IDCAMPO = ISNULL(:IDCAMPO,0)

SELECT IdOpcion as value, Opcion AS Opcion  
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDCAMPO = @IDCAMPO ORDER BY OPCION