//[ido|Integer,idv|Integer,tko|Text,session.convertcode|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDOPORTUNIDAD INT, @IDVENTA INT, @IDEMPRESA INT, @CONVERTCODE INT
DECLARE @TKO VARCHAR(MAX)

SET @IDOPORTUNIDAD = ISNULL(:IDO,0)
SET @IDVENTA = ISNULL(:IDV,0)
SET @TKO = dbo.ValidaToken(ISNULL(:TKO,''))
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

IF @IDOPORTUNIDAD = 0 BEGIN SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD FROM <#SESSION.DB/>.dbo.VENTAS WHERE IDVENTA = @IDVENTA END

SELECT
O.Campo1, O.Campo2, O.Campo3, O.Campo4, 
O.Campo5, O.Campo6, O.Campo7, O.Campo8, 

CASE WHEN O.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO9,@CONVERTCODE) ELSE '' END AS Campo9,
CASE WHEN O.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO10,@CONVERTCODE) ELSE '' END AS Campo10,
CASE WHEN O.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO11,@CONVERTCODE) ELSE '' END AS Campo11,
CASE WHEN O.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO12,@CONVERTCODE) ELSE '' END AS Campo12,
O.Campo13, O.Campo14, O.Campo15, O.Campo16,
O.Campo17, O.Campo18, O.Campo19, O.Campo20,

O.Campo21, O.Campo22, O.Campo23, O.Campo24, O.Campo25,
O.Campo26, O.Campo27, O.Campo28, O.Campo29, O.Campo30, O.Campo31, O.Campo32, 
O.Campo33, O.Campo34, @IDOPORTUNIDAD  AS IDO,@IDVENTA AS IDV,@TKO AS TKO
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O 
JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = O.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA

WHERE O.IDOPORTUNIDAD = @IDOPORTUNIDAD OR O.TKO = @TKO


