//[col|Text,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @COL VARCHAR(1000)
SET @COL= ISNULL(:COL,'')

SET @SQL='SELECT COUNT ('+@COL+') AS COLUMNA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND '+@COL+' = '''''
EXEC (@SQL)