//[session.db|Untyped,session.idempresa|Untyped,vizualizaren|Text,]
--SELECT
DECLARE @VizualizarEn VARCHAR(1000)
SET @VizualizarEn=ISNULL(:VizualizarEn,'')
SELECT NOMBRE_CAMPO, 
CASE 
WHEN TIPO IN (1,3) THEN CAST(INDICE AS VARCHAR(MAX)) + 'P'
WHEN TIPO IN (2,4) THEN CAST(INDICE AS VARCHAR(MAX)) + 'O'
END AS INDICE, 
TIPO, COMPARTIR, @VizualizarEn AS VizualizarEn
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> 
AND INDICE IN (21,22,23,24,25) 
AND (TIPO IN (SELECT SPLITVALUE FROM DBO.SPLIT(@VizualizarEn,',')) OR COMPARTIR IN (SELECT SPLITVALUE FROM DBO.SPLIT(@VizualizarEn,',')))
ORDER BY IDCAMPO