//[session.idempresa|Untyped,nombrecampo|Text,descripcion|Text,idtabs|Integer,tambientab|Integer,tipocampo|Integer,restriccion|Integer,tamanio|Integer,tamanio_campo|Text,configuracion_campo|Text,placeholder|Integer,session.db|Untyped,]
--insert 
DECLARE @CAMPO VARCHAR(100), @DESCRIPCION VARCHAR(500), @TIPOS VARCHAR(MAX), @CONFIGURACION_CAMPO VARCHAR(MAX), @TAMANIO VARCHAR(4)
DECLARE @IDTAB INT, @TIPO INT, @TIPOCAMPO INT, @RESTRICCION INT, @INDICE INT, @CONTA INT, @ORDEN INT, @LARGO INT
DECLARE @IDEMPRESA INT, @IDCAMPO INT, @EXISTE INT, @TIPO_CAMPO INT, @PLACEHOLDER INT, @TambienTab INT, @COMPARTIR INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @CAMPO = ISNULL(:NOMBRECAMPO,'')
SET @DESCRIPCION = ISNULL(:DESCRIPCION,'')

SET @IDTAB = ISNULL(:IDTABS,0)
SET @COMPARTIR = 3
SET @TambienTab = ISNULL(:TambienTab,0)

SET @TIPO = ISNULL(:TipoCampo,0)
SET @RESTRICCION = ISNULL(:Restriccion,0)
SET @LARGO = ISNULL(:TAMANIO,0)
SET @TAMANIO = ISNULL(:Tamanio_Campo,'')
SET @CONFIGURACION_CAMPO = ISNULL(:Configuracion_Campo,'')
SET @PLACEHOLDER = ISNULL(:PlaceHolder,0)

SET @ORDEN = 0
SET @CONTA = 1

IF @TIPO IN (1,2,3,4,6,7) SET @TIPOCAMPO = 1
IF @TIPO =  5 SET @TIPOCAMPO = 2
IF @TIPO =  8 SET @TIPOCAMPO = 6
IF @TIPO =  9 SET @TIPOCAMPO = 9
IF @TIPO = 10 SET @TIPOCAMPO = 8
IF @TIPO = 11 SET @TIPOCAMPO = 4
IF @TIPO = 12 SET @TIPOCAMPO = 3
IF @TIPO = 13 SET @TIPOCAMPO = 7
IF @TIPO = 14 SET @TIPOCAMPO = 5
   
WHILE @INDICE IS NULL AND @CONTA <= 10
BEGIN
	 SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND INDICE = @CONTA AND TIPO = 5
	 IF @EXISTE = 0 BEGIN SET @INDICE = @CONTA END
	 SET @CONTA = @CONTA + 1
END

/*SELECT TOP 1 @ORDEN = ORDEN FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND TIPO = 5 ORDER BY ORDEN*/
SET @ORDEN = 99

SELECT @IDTAB = IDTAB FROM <#SESSION.DB/>.DBO.EMPRESAS_TABS WHERE IDEMPRESA = @IDEMPRESA AND TAB_DEFAULT = 4 AND IDVENTANA = 1
SELECT @TambienTab = IDTAB FROM <#SESSION.DB/>.DBO.EMPRESAS_TABS WHERE IDEMPRESA = @IDEMPRESA AND TAB_DEFAULT = 4 AND IDVENTANA = 3

INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS
	(IDEMPRESA, INDICE, NOMBRE_CAMPO, DESCRIPCION, LLAVE,  LARGO, TIPO, ORDEN, IDTAB, TIPO_CAMPO, TAMANIO, CONFIGURACION_CAMPO, COMPARTIR, TAMBIENEN_IDTAB, PLACEHOLDER, TAMBIENEN_ORDEN)
VALUES 
	(@IDEMPRESA, @INDICE, @CAMPO, @DESCRIPCION, @RESTRICCION, @LARGO, 5, @ORDEN, @IDTAB, @TIPOCAMPO, @TAMANIO, @CONFIGURACION_CAMPO, @COMPARTIR, @TambienTab, @PLACEHOLDER, @ORDEN)

SELECT TOP 1 @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA ORDER BY IDCAMPO DESC

EXEC <#SESSION.DB/>.dbo.SP_AGREGA_COLUMAS_PERSONALIZADA @IDEMPRESA , @IDCAMPO

