//[base|Text,bd|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @BASE VARCHAR(1000)
DECLARE @BD VARCHAR(1000)
SET @BASE = ISNULL(:BASE,'')
SET @BD = ISNULL(:BD,'')
IF(@BASE <> '' OR @BD <> '')
BEGIN
	 SELECT * FROM SALESUP_CT.dbo.BASES_CONTEO WHERE (DATA_BASE =@BD OR DATA_BASE = @BASE)
END
ELSE
BEGIN
	 SELECT 1 AS SINBASE
END