//[session.db|Untyped,session.idempresa|Untyped,]
SELECT * 
FROM SALESUP_CT.dbo.CAMPOS 
WHERE IDCAMPO NOT IN (SELECT CAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>)