//[ven|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @VerEn VARCHAR(12)
DECLARE @IDEMPRESA INT, @VENTANA INT

SET @VENTANA = ISNULL(:VEN,0)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


IF @VENTANA = 1 BEGIN SET @VEREN = '1,3' END
IF @VENTANA = 2 BEGIN SET @VEREN = '2,4' END
IF @VENTANA = 3 BEGIN SET @VEREN = '1,3' END
IF @VENTANA = 4 BEGIN SET @VEREN = '1,2,3,4' END


SELECT IdCampo as IdCampoPer ,Indice as IdC, NOMBRE_CAMPO AS Campo, Descripcion as Tip, Largo AS Max,
'Campo'+CAST(Indice AS VARCHAR(MAX)) AS Nombre,
'Campo'+CAST(Indice AS VARCHAR(MAX)) AS Id,
CASE
WHEN LLAVE = 0 AND(TIPO IN (1,3) OR COMPARTIR IN (1,3)) THEN 'TbProspectos'
WHEN LLAVE = 0 AND(TIPO IN (2,4) OR COMPARTIR IN (2,4)) THEN 'TbOportunidades'
WHEN LLAVE = 1 AND(TIPO IN (1,3) OR COMPARTIR IN (1,3)) THEN 'InfoUnico InfoObligatorio TbProspectos '+(CASE WHEN SALESUP_CT.dbo.esCanalizado(TK, TKM) = 2 THEN 'cpCanalizado' ELSE '' END)
WHEN LLAVE = 1 AND(TIPO IN (2,4) OR COMPARTIR IN (2,4)) THEN 'InfoUnico InfoObligatorio TbOportunidades '+(CASE WHEN SALESUP_CT.dbo.esCanalizado(TK, TKM) = 2 THEN 'cpCanalizado' ELSE '' END)
WHEN LLAVE = 2 AND(TIPO IN (1,3) OR COMPARTIR IN (1,3)) THEN 'InfoObligatorio TbProspectos '+(CASE WHEN SALESUP_CT.dbo.esCanalizado(TK, TKM) = 2 THEN 'cpCanalizado' ELSE '' END)
WHEN LLAVE = 2 AND(TIPO IN (2,4) OR COMPARTIR IN (2,4)) THEN 'InfoObligatorio TbOportunidades '+(CASE WHEN SALESUP_CT.dbo.esCanalizado(TK, TKM) = 2 THEN 'cpCanalizado' ELSE '' END)
WHEN LLAVE = 3 AND(TIPO IN (1,3) OR COMPARTIR IN (1,3)) THEN 'InfoUnico TbProspectos'
WHEN LLAVE = 3 AND(TIPO IN (2,4) OR COMPARTIR IN (2,4)) THEN 'InfoUnico TbOportunidades'
WHEN LLAVE = 4 AND(TIPO IN (1,3) OR COMPARTIR IN (1,3)) THEN 'InfoSugerido TbProspectos'
WHEN LLAVE = 4 AND(TIPO IN (2,4) OR COMPARTIR IN (2,4)) THEN 'InfoSugerido TbOportunidades'
END AS ClasesAdicionales, 
'OcultarEste'+CASE
WHEN @VENTANA = 1 AND (TIPO = 1 OR COMPARTIR = 1) THEN ' NoOcultar'
WHEN @VENTANA = 2 AND (TIPO = 2 OR COMPARTIR = 2) THEN ' NoOcultar'
WHEN @VENTANA = 3 AND (TIPO = 3 OR COMPARTIR = 3) THEN ' NoOcultar'
WHEN @VENTANA = 4 AND (TIPO = 4 OR COMPARTIR = 4) THEN ' NoOcultar'
ELSE ''
END AS Ventana, 
CASE
	WHEN INDICE BETWEEN 1 AND 4 THEN 'numero'
	WHEN INDICE BETWEEN 5 AND 8 THEN 'decimal'
	WHEN INDICE BETWEEN 9 AND 12 THEN 'Fecha'
	WHEN ( (INDICE BETWEEN 13 AND 20)  OR (INDICE BETWEEN 26 AND 33)  )  THEN 'Texto'
	WHEN INDICE BETWEEN 21 AND 25 THEN 'Lista'
	END AS TipoCampo,
CASE WHEN INDICE BETWEEN 21 AND 25 THEN '1' END AS EsSelect,
CASE WHEN NOT(INDICE BETWEEN 21 AND 25) THEN '1' END AS EsInput
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS 
WHERE IDEMPRESA = @IDEMPRESA AND INDICE NOT IN (33,34) 
AND (
	TIPO IN (SELECT SPLITVALUE FROM  SALESUP_CT.dbo.SPLIT(@VEREN,','))  OR COMPARTIR IN (SELECT SPLITVALUE FROM  SALESUP_CT.dbo.SPLIT(@VEREN,','))
	)
ORDER BY LLAVE DESC, NOMBRE_CAMPO