//[session.db|Untyped,nombre|Text,session.idempresa|Untyped,campo|Text,borrar|Text,session.idusuario|Untyped,contador|Text,]
-- update

DECLARE @CONTEO INT
DECLARE @IDPROSPECTOIMPORTA INT
DECLARE @IDCAMPO INT
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @NOMBRE VARCHAR(MAX)
DECLARE @BORRAR VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONTADOR VARCHAR(MAX)
SET @CAMPO = ISNULL(:CAMPO,'')
SET @NOMBRE = ISNULL(:NOMBRE,'')
SET @BORRAR = ISNULL(:BORRAR,'')
SET @CONTADOR = ISNULL(:CONTADOR,'1'

SELECT @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE NOMBRE_CAMPO = @NOMBRE AND IDEMPRESA = <#SESSION.IDEMPRESA>

IF ((@CAMPO='CAMPO21')OR(@CAMPO='CAMPO22')OR(@CAMPO='CAMPO23')OR(@CAMPO='CAMPO24')OR(@CAMPO='CAMPO25'))
BEGIN
	 IF (@BORRAR=1)
	 BEGIN
	 	  SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
          SET @SQL='
		  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION SET COL'+@CONTADOR+' = CAST(IDOPCION AS VARCHAR(125)) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC
		  JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO ON EC.IDCAMPO = ECO.IDCAMPO
		  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PIM ON ECO.OPCION = PIM.COL'+@CONTADOR+'
		  WHERE EC.IDEMPRESA = <#SESSION.IDEMPRESA> AND PIM.IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTOIMPORTA!='+CAST(@IDPROSPECTOIMPORTA AS VARCHAR(1000))+' AND ECO.IDCAMPO = '+CAST(@IDCAMPO AS VARCHAR(1000))+'
		  '
	END
	ELSE
	BEGIN
		 SET @SQL='
		  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION SET COL'+@CONTADOR+' = CAST(IDOPCION AS VARCHAR(125)) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC
		  JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO ON EC.IDCAMPO = ECO.IDCAMPO
		  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PIM ON ECO.OPCION = PIM.COL'+@CONTADOR+'
		  WHERE EC.IDEMPRESA = <#SESSION.IDEMPRESA> AND PIM.IDUSUARIO = <#SESSION.IDUSUARIO/> AND ECO.IDCAMPO = '+CAST(@IDCAMPO AS VARCHAR(1000))+'
		 '
	END
END
