//[session.idempresa|Untyped,nombrecampo|Text,descripcion|Text,tipocampo|Integer,restriccion|Integer,tamanio|Integer,veren|Integer,tambienen|Integer,generaranteriores|Integer,empiezaen|Integer,session.db|Untyped,]
--insert
/*PROTEGIDO*/
DECLARE @IND INT, @ID INT, @CONTA INT, @TIPOCAMPO INT, @CONTTXT INT
DECLARE @IDEMPRESA INT, @IDCAMPO INT, @OBLIGATORIO INT, @TAMANIO INT, @EXISTE INT
DECLARE @VEREN INT, @COMPARTIR INT, @GenerarAnteriores INT, @EmpiezaEn INT
DECLARE @VALIDACION VARCHAR(500), @NOMBRECAMPO VARCHAR(100), @DESCRIPCION VARCHAR(100), @TIPOS VARCHAR(MAX)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @VALIDACION = ''
SET @NOMBRECAMPO = :NOMBRECAMPO
SET @DESCRIPCION = :DESCRIPCION
SET @TIPOCAMPO = ISNULL(:TipoCampo,0)
SET @OBLIGATORIO = ISNULL(:Restriccion,0)
SET @TAMANIO = ISNULL(:TAMANIO,0)
SET @VEREN = ISNULL(:VerEn,0)
SET @COMPARTIR = ISNULL(:TambienEn,0)
SET @GenerarAnteriores = ISNULL(:GenerarAnteriores,0)
SET @EmpiezaEn = ISNULL(:EmpiezaEn,0)
 
IF @TIPOCAMPO = 1 BEGIN SET @IND =  1 END
IF @TIPOCAMPO = 2 BEGIN SET @IND =  5 END
IF @TIPOCAMPO = 3 BEGIN SET @IND =  9 END
IF @TIPOCAMPO = 4 BEGIN SET @IND = 13 END
IF @TIPOCAMPO = 6 BEGIN SET @IND = 33 SET @ID = @IND END
IF @TIPOCAMPO = 7 BEGIN SET @IND = 34 SET @ID = @IND END

SET @TIPOS = '1,3'
IF @VEREN IN (2,4) BEGIN SET @TIPOS = '2,4' END

SET @CONTA = @IND
SET @CONTTXT = @CONTA

IF @TIPOCAMPO != 4
BEGIN
  WHILE @ID IS NULL AND @CONTA < 21
  BEGIN
	SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND INDICE = @CONTA AND TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@TIPOS,',') )
  	IF @EXISTE = 0 BEGIN SET @ID = @CONTA END
    SET @CONTA = @CONTA + 1
  END
END
ELSE
BEGIN
  WHILE @ID IS NULL AND @CONTA < 28
  BEGIN
	SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA AND INDICE = @CONTTXT AND TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@TIPOS,',') )
  	IF @EXISTE = 0 BEGIN SET @ID = @CONTTXT END 
	IF @CONTTXT = 20 BEGIN SET @CONTTXT = 25 END
	SET @CONTA = @CONTA + 1
	SET @CONTTXT = @CONTTXT + 1
  END
END

INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS (IDEMPRESA, INDICE, NOMBRE_CAMPO, DESCRIPCION, LLAVE, VALIDACION, LARGO, TIPO, CONSECUTIVO, COMPARTIR) 
VALUES (@IDEMPRESA, @ID, @NOMBRECAMPO, @DESCRIPCION, @OBLIGATORIO, @VALIDACION , @TAMANIO, @VEREN, @EmpiezaEn, @COMPARTIR)

SELECT TOP 1 @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA ORDER BY IDCAMPO DESC



/*AUTOINCREMENTABLE*/
IF @TIPOCAMPO = 6 AND @GenerarAnteriores = 1
BEGIN
	 
	 DECLARE @QRY VARCHAR(MAX)
	 SET @QRY = ''

	 SET @QRY = @QRY + ' DECLARE @MAX INT'
	 SET @QRY = @QRY + ' DECLARE @TABLA TABLE( ID INT, NUMERO INT IDENTITY(' + CAST(@EmpiezaEn AS VARCHAR(MAX)) + ',1))'
	 SET @QRY = @QRY + ' INSERT INTO @TABLA (ID)'
	 IF @VEREN IN (1,3)
	 BEGIN
	 	  SET @QRY = @QRY + ' SELECT P.IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS P WHERE P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(MAX)) + ' AND P.CAMPO33 IS NULL ORDER BY P.FECHACONTACTO'

		  SET @QRY = @QRY + ' UPDATE P SET CAMPO33 = TB.NUMERO '
		  SET @QRY = @QRY + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P '
		  SET @QRY = @QRY + ' JOIN @TABLA TB ON TB.ID = P.IDPROSPECTO  '
		  SET @QRY = @QRY + ' WHERE P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(MAX))
	 END
	 IF @VEREN IN (2,4)
	 BEGIN
	 	  SET @QRY = @QRY + ' SELECT O.IDOPORTUNIDAD FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = O.IDPROSPECTO WHERE P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(MAX)) + ' AND O.CAMPO33 IS NULL ORDER BY O.IDOPORTUNIDAD'

		  SET @QRY = @QRY + ' UPDATE O SET O.CAMPO33 = TB.NUMERO   '
		  SET @QRY = @QRY + ' FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O '
		  SET @QRY = @QRY + ' JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = O.IDPROSPECTO '
		  SET @QRY = @QRY + ' JOIN @TABLA TB ON TB.ID = O.IDOPORTUNIDAD'
		  SET @QRY = @QRY + ' WHERE P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(MAX))
	 END
	 SET @QRY = @QRY + ' SELECT @MAX = MAX(NUMERO)+1 FROM @TABLA'
	 SET @QRY = @QRY + ' UPDATE <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS SET CONSECUTIVO = @MAX WHERE IDCAMPO = ' + CAST(@IDCAMPO AS VARCHAR(MAX)) 
	 SET @QRY = @QRY + ''
	 EXEC(@QRY)
END

/*UUID*/
IF @TIPOCAMPO = 7 AND @GenerarAnteriores = 1
BEGIN
	 IF @VEREN IN (1,3)
	 BEGIN
	 	  UPDATE P SET CAMPO34 = CAST(NEWID() AS VARCHAR(64)) 
		  FROM <#SESSION.DB/>.DBO.PROSPECTOS P WHERE P.IDEMPRESA = @IDEMPRESA AND CAMPO34 IS NULL
	 END
	 
	 IF @VEREN IN (2,4)
	 BEGIN
	 	  UPDATE O SET CAMPO34 = CAST(NEWID() AS VARCHAR(64)) 
		  FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O 
	 	  JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = O.IDPROSPECTO AND P.CAMPO34 IS NULL
	 	  WHERE P.IDEMPRESA = @IDEMPRESA
	 END
END



EXEC <#SESSION.DB/>.dbo.SP_AGREGA_COLUMAS_PERSONALIZADA @IDEMPRESA , @IDCAMPO
