//[veren|Text,tambienen|Text,empiezaen|Text,restriccion|Text,idtabs|Text,tipocampo|Text,tamanio|Text,tamanio_campo|Text,tambientab|Text,session.db|Untyped,session.idempresa|Untyped,nombrecampo|Text,descripcion|Text,opciones|Text,]
--insert
DECLARE @IND INT, @ID INT, @CONTA INT, @TIPOCAMPO INT, @IDCAMPO INT
DECLARE @VALIDACION VARCHAR(MAX), @OBLIGATORIO VARCHAR(MAX), @TIPOS VARCHAR(MAX), @TAMANIO_CAMPO VARCHAR(4)
DECLARE @VEREN INT, @COMPARTIR INT, @EmpiezaEn INT, @IDTAB INT, @TAMANIO INT, @TIPO_CAMPO INT, @TambienTab INT

SET @VEREN = CAST(ISNULL(:VerEn,'') AS INT)
SET @COMPARTIR = CAST(ISNULL(:TambienEn,'') AS INT)
SET @EmpiezaEn = CAST(ISNULL(:EmpiezaEn,'') AS INT)
SET @OBLIGATORIO = CAST(ISNULL(:Restriccion,'') AS INT)
SET @IDTAB = CAST(ISNULL(:IDTABS,'') AS INT)
SET @TIPOCAMPO = CAST(ISNULL(:TipoCampo,'') AS INT)
SET @TAMANIO = CAST(ISNULL(:TAMANIO,'') AS INT)
SET @TAMANIO_CAMPO = ISNULL(:Tamanio_Campo,'')
SET @TambienTab = CAST(ISNULL(:TambienTab,'') AS INT)

IF @TIPOCAMPO = 5 BEGIN SET @TIPO_CAMPO = 2 END
IF @TIPOCAMPO = 5 BEGIN SET @IND = 21 END

SET @TIPOS = '1,3'
IF @VEREN IN (2,4) BEGIN SET @TIPOS = '2,4' END

SET @CONTA = @IND
WHILE @ID IS NULL AND @CONTA < 26
BEGIN
  IF (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND INDICE = @CONTA AND TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@TIPOS,',') ) )=0
    SELECT @ID = @CONTA
  	SET @CONTA = @CONTA +1
END

INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS (IDEMPRESA, INDICE, NOMBRE_CAMPO, DESCRIPCION, LLAVE, VALIDACION, TIPO, COMPARTIR, ORDEN, IDTAB, TAMBIENEN_IDTAB, TIPO_CAMPO, TAMANIO) 
VALUES (<#SESSION.IDEMPRESA/>, @ID, ISNULL(:NOMBRECAMPO,''), ISNULL(:DESCRIPCION,''), @OBLIGATORIO, @VALIDACION, @VEREN, @COMPARTIR, 999, @IDTAB, @TambienTab, @TIPO_CAMPO, @TAMANIO_CAMPO)
	
SELECT TOP 1 @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS where idempresa = <#SESSION.IDEMPRESA/> order by idcampo desc
 
INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES (IDCAMPO, OPCION)
SELECT @IDCAMPO, SplitValue FROM <#SESSION.DB/>.dbo.Split(ISNULL(:opciones,''), '|')

DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
EXEC <#SESSION.DB/>.dbo.SP_AGREGA_COLUMAS_PERSONALIZADA @IDEMPRESA , @IDCAMPO 

