//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @TEXTO INT, @TOTAL INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT @TEXTO = 10 - COUNT(*) 
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS 
WHERE
	IDEMPRESA = @IDEMPRESA 
AND TIPO = 5 
AND INDICE BETWEEN 1 AND 10 

SET @TOTAL = @TEXTO

SELECT @TEXTO AS texto, @TOTAL AS total