//[session.db|Untyped,session.idempresa|Untyped,]
DECLARE @TEXTO INT
DECLARE @NUMERICOS INT
DECLARE @DECIMALES INT
DECLARE @FECHA INT
DECLARE @LISTA INT
DECLARE @TOTAL INT


SELECT @NUMERICOS = 4-COUNT(*)  FROM <#SESSION.DB/>.DBO.empresas_campos where idempresa = <#SESSION.IDEMPRESA/> AND INDICE BETWEEN 1 AND 4
SELECT @DECIMALES = 4-COUNT(*)  FROM  <#SESSION.DB/>.DBO.empresas_campos where idempresa = <#SESSION.IDEMPRESA/> AND INDICE BETWEEN 5 AND 8 
SELECT @FECHA = 4-COUNT(*)  FROM  <#SESSION.DB/>.DBO.empresas_campos where idempresa = <#SESSION.IDEMPRESA/> AND INDICE BETWEEN 9 AND 12
SELECT @TEXTO = 8-COUNT(*)  FROM  <#SESSION.DB/>.DBO.empresas_campos where idempresa = <#SESSION.IDEMPRESA/> AND INDICE BETWEEN 13 AND 20
SELECT @LISTA = 5-COUNT(*)  FROM  <#SESSION.DB/>.DBO.empresas_campos where idempresa = <#SESSION.IDEMPRESA/> AND INDICE >= 21
SET @TOTAL = @NUMERICOS+@DECIMALES+@FECHA+@TEXTO+@LISTA
SELECT @NUMERICOS AS NUMERICOS , @DECIMALES AS DECIMALES , @FECHA AS FECHA , @TEXTO AS TEXTO , @LISTA AS LISTA , @TOTAL AS TOTAL 