//[idcampo|Integer,tipo|Integer,session.db|Untyped,session.idempresa|Untyped,]
--INSERT
DECLARE @IDCAMPO INT
DECLARE @TIPO INT
DECLARE @VALIDACION VARCHAR(256)

SET @IDCAMPO = ISNULL(:IDCAMPO,0)
SET @TIPO = ISNULL(:TIPO,0)

IF @TIPO = 1 SET @VALIDACION = 'llave'

IF @TIPO = 2 SET @VALIDACION = 'obligatorio'

IF @TIPO = 3 SET @VALIDACION = 'llave obligatorio'


INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION (IDEMPRESA,CAMPO,TIPO,VALIDACION)
VALUES (<#SESSION.IDEMPRESA/>,@IDCAMPO,@TIPO,@VALIDACION)
 