//[valor|Text,session.db|Untyped,idcampo|Integer,session.convertcode|Untyped,idprospecto|Integer,session.idempresa|Untyped,]
DECLARE @USR INT
DECLARE @IDPROSPECTO INT
DECLARE @IDPROSPECTO1 INT
DECLARE @INDICE INT
declare @VALOR VARCHAR(200) 
DECLARE @IDCAMPO INT 

SET @VALOR=:VALOR
SET @IDPROSPECTO1=ISNULL(:IDPROSPECTO,0)
SET @IDCAMPO = ISNULL(:IDCAMPO,0)

SELECT @INDICE = INDICE FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS WHERE IDCAMPO = @IDCAMPO


IF (@INDICE IN (9,10,11,12))
  SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCampoLlave(@IDCAMPO,CONVERT (DATETIME,@VALOR,<#SESSION.CONVERTCODE/>), @IDPROSPECTO1, <#SESSION.IDEMPRESA/>)
ELSE
  SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCampoLlave(@IDCAMPO,@VALOR, @IDPROSPECTO1, <#SESSION.IDEMPRESA/>)


SELECT @USR = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
SELECT  NOMBRE + ' '+APELLIDOS + '('+INICIALES+')' AS NOMBRE  FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @USR 



