//[texto|Text,error|Text,resultado|Text,db|Text,msgid|Text,idemail|Text,]
--UPDATE
DECLARE @SQL VARCHAR(max)
DECLARE @TEXTO VARCHAR(max)
SET @TEXTO = REPLACE(:TEXTO, '''', '')
DECLARE @ERROR VARCHAR(max)
SET @ERROR = REPLACE(:ERROR, '''', '')

IF (:RESULTADO = 1)
BEGIN
	 SET @SQL = ' SET DEADLOCK_PRIORITY HIGH  UPDATE '+ :DB + '.dbo.USUARIOS_EMAILS WITH(ROWLOCK) SET ESTADO = 1, FECHAHORA_ENVIO = GETDATE(), HEADERS= ''' + @TEXTO + ''', MSGID = ''' + :MSGID + ''' WHERE IDEMAIL = '+ :IDEMAIL
END
ELSE
BEGIN
	 SET @SQL = 'SET DEADLOCK_PRIORITY HIGH  UPDATE '+ :DB + '.dbo.USUARIOS_EMAILS WITH(ROWLOCK) SET HEADERS= ''' + @TEXTO + ''', ERRORES = 3, ULTIMOERRORMSG = LEFT('''+ @ERROR + ''', 255) WHERE IDEMAIL = '+ :IDEMAIL
END
  IF @SQL IS NOT NULL
  BEGIN 
     BEGIN TRY
	   BEGIN TRANSACTION
       SET DEADLOCK_PRIORITY HIGH
       EXEC (@SQL) 
	   COMMIT TRANSACTION
     END TRY
     BEGIN CATCH
	   ROLLBACK TRANSACTION
	   WAITFOR DELAY '00:00:02';
	   BEGIN TRY
	   BEGIN TRANSACTION
       SET DEADLOCK_PRIORITY low
       EXEC (@SQL) 
	   COMMIT TRANSACTION
       END TRY   
	   BEGIN CATCH
	     ROLLBACK TRANSACTION
		 WAITFOR DELAY '00:00:02';
	     BEGIN TRANSACTION
	     SET DEADLOCK_PRIORITY low
         EXEC (@SQL)
		 COMMIT TRANSACTION 
	    END CATCH  
     END CATCH
  END