//[session.convertcode|Untyped,tk|Text,tipo|Integer,agrupar|Integer,periodo|Integer,fecha_desde|Text,fecha_hasta|Text,session.db|Untyped,]
--SELECT
DECLARE @TK VARCHAR(MAX)
DECLARE @TIPO INT
DECLARE @FECHA_DESDE VARCHAR(MAX)
DECLARE @FECHA_HASTA VARCHAR(MAX)
DECLARE @AGRUPAR INT
DECLARE @PERIODO INT
DECLARE @CONVERTCODE VARCHAR(1000)

SET @CONVERTCODE='<#SESSION.CONVERTCODE/>'
SET @TK = ISNULL(:tk,'')
SET @TIPO = ISNULL(:tipo,0)
SET @AGRUPAR = ISNULL(:agrupar,1)
SET @PERIODO = ISNULL(:periodo,5)
SET @FECHA_DESDE = ISNULL(:fecha_desde,'')
SET @FECHA_HASTA = ISNULL(:fecha_hasta,'')

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ACTIVIDADES_DETALLE @TK,@TIPO,@FECHA_DESDE,@FECHA_HASTA,@AGRUPAR,@PERIODO,@CONVERTCODE,0