//[session.db|Untyped,idusuario|Integer,fecha_desde|Text,session.convertcode|Untyped,fecha_hasta|Text,session.idempresa|Untyped,]
--SELECT
DECLARE @IDUSUARIO INT
DECLARE @FECHA_DESDE VARCHAR(1000)
DECLARE @FECHA_HASTA VARCHAR(1000)
SET @IDUSUARIO=ISNULL(:IDUSUARIO,0)
SET @FECHA_DESDE=ISNULL(:FECHA_DESDE,'')
SET @FECHA_HASTA=ISNULL(:FECHA_HASTA,'')

SELECT  COUNT(P.IDPROSPECTO)  AS TOTALN, @IDUSUARIO AS IDUSUARIO, @FECHA_DESDE AS FECHA_DESDE, @FECHA_HASTA AS FECHA_HASTA
FROM  
 <#SESSION.DB/>.dbo.PROSPECTOS P 
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS ON P.IDPROSPECTO = PS.IDPROSPECTO  
LEFT JOIN <#SESSION.DB/>.dbo.SEGUIMIENTO_CATEGORIAS SC ON SC.IDSEGUIMIENTOCATEGORIA = PS.IDSEGUIMIENTOCATEGORIA
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = PS.IDUSUARIO 
WHERE  (<#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA)BETWEEN CONVERT(DATETIME,@FECHA_DESDE,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FECHA_HASTA,<#SESSION.CONVERTCODE/>)) 
AND PS.IDSEGUIMIENTOCATEGORIA IS NOT NULL
AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>  AND PS.IDUSUARIO=@IDUSUARIO AND P.DESCARTADO = 0 AND P.ESCLIENTE = 1