//[session.convertcode|Untyped,session.db|Untyped,fecha_hasta|Text,fecha_desde|Text,tipo|Integer,idusuario|Integer,]
--select
DECLARE @CONVERTCODE VARCHAR(1000)
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRITERIA VARCHAR(MAX)
DECLARE @TIPO INT
DECLARE @IDUSUARIO INT
DECLARE @FECHA_INICIAL VARCHAR(1000)
DECLARE @FECHA_FINAL VARCHAR(1000)
DECLARE @SESSION VARCHAR(1000)

SET @CONVERTCODE='<#SESSION.CONVERTCODE/>'
SET @SESSION='<#SESSION.DB/>'
SET @FECHA_FINAL =ISNULL(:FECHA_HASTA,'')
SET @FECHA_INICIAL=ISNULL(:FECHA_DESDE,'')
SET @TIPO=ISNULL(:TIPO,0)
SET @IDUSUARIO=ISNULL(:IDUSUARIO,0)



SELECT @CRITERIA=(CASE WHEN @TIPO=1 THEN 'AND (P.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND ESCLIENTE=0 AND P.REASIGNADO=0 AND P.DESCARTADO=0 AND '+@SESSION+'.dbo.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')' 
                  WHEN @TIPO=2 THEN 'AND (P.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND ESCLIENTE=0 AND P.REASIGNADO=1 AND P.DESCARTADO=0 AND '+@SESSION+'.dbo.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')'			  
				  WHEN @TIPO=3 THEN 'AND (P.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(1000))+') AND ESCLIENTE=0 AND P.DESCARTADO=1 AND '+@SESSION+'.dbo.GETONLYDATE(P.DESCARTADOFECHA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')'
				  ELSE '' END) 

SET @SQL = ''
SET @SQL='
SELECT '+@SESSION+'.DBO.ValidaEmail(P.CORREO) as ESCORREO , 
	   p.*, CAST (COMENTARIOS AS VARCHAR(128))+''...'' AS INTRO, U.INICIALES,ISNULL(U.NOMBRE,'''')+'' ''+ISNULL(U.APELLIDOS,'''') AS NOMBRE_USUARIO,
    '+@SESSION+'.dbo.FECHA_STR(P.FECHACONTACTO) AS FECHA_CONTACTO,
   (SELECT ORIGEN FROM '+@SESSION+'.dbo.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, 
    '+@SESSION+'.dbo.FECHA_STR(P.DESCARTADOFECHA) AS FECHA_DESCARTADO,
   (SELECT TOP 1 CAST(COMENTARIO AS VARCHAR(128)) FROM '+@SESSION+'.dbo.PROSPECTOS_SEGUIMIENTO WHERE IDPROSPECTO = P.IDPROSPECTO  ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO,
   FECHA_ULTIMOSEGUIMIENTO AS ULTIMO_CONTACTO_TIEMPO,
   (SELECT TOP 1 U.INICIALES FROM '+@SESSION+'.dbo.PROSPECTOS_SEGUIMIENTO S, USUARIOS U WHERE S.IDPROSPECTO = P.IDPROSPECTO   AND S.IDUSUARIO = U.IDUSUARIO ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_USUARIO
   

FROM 
'+@SESSION+'.dbo.PROSPECTOS P, 
'+@SESSION+'.dbo.USUARIOS U 
WHERE 
   P.IDUSUARIO = U.IDUSUARIO '+@CRITERIA+'
   
AND
  ( 
    ('+@SESSION+'.dbo.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')) OR
    ('+@SESSION+'.dbo.GETONLYDATE(P.DESCARTADOFECHA) BETWEEN CONVERT(DATETIME, '''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')) OR
    ('+@SESSION+'.dbo.GETONLYDATE(P.FECHA_ULTIMOSEGUIMIENTO) BETWEEN CONVERT(DATETIME, '''+@FECHA_INICIAL+''','+@CONVERTCODE+') AND CONVERT(DATETIME,'''+@FECHA_FINAL+''','+@CONVERTCODE+')) 
  )    
  
 '
 EXEC(@SQL)

 


