//[session.convertcode|Untyped,fecha_hasta|Text,fecha_desde|Text,session.db|Untyped,idusuario|Integer,]
DECLARE @FECHA_INICIAL VARCHAR(128)
DECLARE @FECHA_FINAL VARCHAR(128)
DECLARE @IDUSUARIO INT
DECLARE @CONVERTCODE INT
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @FECHA_FINAL = ISNULL(:FECHA_HASTA,'')
SET @FECHA_INICIAL= ISNULL(:FECHA_DESDE,'')
SET @IDUSUARIO = ISNULL(:IDUSUARIO, 0)

SELECT 
  <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO , ISNULL(ganada, 0) AS ganada, isnull(perdida, 0) AS PERDIDA,
  P.*,F.FASE,U.INICIALES,ISNULL(U.NOMBRE,'')+' '+ISNULL(U.APELLIDOS,'') AS NOMBRE_USUARIO,
  <#SESSION.DB/>.dbo.FECHA_STR(P.FECHACONTACTO) AS FECHA_CONTACTO,
  <#SESSION.DB/>.dbo.url_host (sitio_captura) as ORIGEN, 
 (SELECT TOP 1 CAST(COMENTARIO AS VARCHAR(MAX)) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE IDPROSPECTO = P.IDPROSPECTO AND SISTEMA=0 ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO,
 (CASE WHEN P.FECHA_ULTIMOSEGUIMIENTO > ISNULL(O.FECHA_ULTIMOSEGUIMIENTO, 0) OR  P.ESOPORTUNIDAD=0 THEN <#SESSION.DB/>.dbo.TIEMPO_TXT (P.FECHA_ULTIMOSEGUIMIENTO,GETDATE()) ELSE <#SESSION.DB/>.dbo.TIEMPO_TXT (O.FECHA_ULTIMOSEGUIMIENTO,GETDATE()) END ) AS ULTIMO_CONTACTO_TIEMPO,
 (SELECT TOP 1 U.INICIALES FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S, <#SESSION.DB/>.dbo.USUARIOS U WHERE S.IDPROSPECTO = P.IDPROSPECTO AND S.IDUSUARIO = U.IDUSUARIO ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_USUARIO,
 ISNULL (O.MONTO,0) AS OPORTUNIDAD_MONTO,
 ISNULL(O.CERTEZA,0) AS CERTEZA

FROM 
<#SESSION.DB/>.dbo.PROSPECTOS P
  JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSEG ON P.IDULTIMOSEGUIMIENTO = PSEG.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON P.IDPROSPECTO = PA.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_FASES F ON  P.IDFASE=F.IDFASE 
  LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDPROSPECTO = P.IDPROSPECTO,
<#SESSION.DB/>.dbo.USUARIOS U
WHERE 
PA.IDUSUARIO= @IDUSUARIO AND P.IDUSUARIO = U.IDUSUARIO AND PA.IDUSUARIO=U.IDUSUARIO

AND 
 SISTEMA = 0 AND 
 ( 
   (PA.IDUSUARIO = O.IDUSUARIO AND <#SESSION.DB/>.dbo.GETONLYDATE(P.FECHA_ULTIMOSEGUIMIENTO) = <#SESSION.DB/>.dbo.GETONLYDATE(O.FECHA_ULTIMOSEGUIMIENTO) AND <#SESSION.DB/>.dbo.GETONLYDATE(P.FECHA_ULTIMOSEGUIMIENTO) BETWEEN CONVERT(DATETIME,@FECHA_INICIAL,@CONVERTCODE) AND CONVERT(DATETIME,@FECHA_FINAL,@CONVERTCODE))  OR
   (O.GANADA IS NULL AND ESCLIENTE = 0 AND ESOPORTUNIDAD = 0 AND <#SESSION.DB/>.dbo.GETONLYDATE(P.FECHA_ULTIMOSEGUIMIENTO) BETWEEN CONVERT(DATETIME,@FECHA_INICIAL,@CONVERTCODE) AND CONVERT(DATETIME,@FECHA_FINAL,@CONVERTCODE))  OR
   (PA.IDUSUARIO = O.IDUSUARIO AND  GANADA = 0 AND PERDIDA = 0 AND <#SESSION.DB/>.dbo.GETONLYDATE(O.FECHA_ULTIMOSEGUIMIENTO) BETWEEN CONVERT(DATETIME,@FECHA_INICIAL,@CONVERTCODE) AND CONVERT(DATETIME,@FECHA_FINAL,@CONVERTCODE))   
 )

    

