//[tipo|Integer,criteria|Text,session.db|Untyped,]
--SELECT 
DECLARE @TIPO INT = ISNULL(:TIPO,0)
DECLARE @SQLTXT VARCHAR(MAX)
DECLARE @COMPLEMENTO VARCHAR(MAX) = ''
DECLARE @CRITERIO VARCHAR(MAX)
DECLARE @SELECTEXTRA VARCHAR(MAX)

IF(@TIPO = 3)
BEGIN
	  SET @CRITERIO = ' V.IDOPORTUNIDAD = O.IDOPORTUNIDAD ' + :CRITERIA + ' AND	'
	  SET @COMPLEMENTO = ' <#SESSION.DB/>.dbo.VENTAS V, '
	  SET @SELECTEXTRA = ' V.MONTO, V.COMISION AS COMISION_MONTO, O.CERTEZA,O.FECHA_CIERRE,V.IDVENTA,V.TKV,O.IDOPORTUNIDAD,O.TKO,'
END
ELSE
BEGIN
	 SET @CRITERIO = :CRITERIA
	 SET @SELECTEXTRA = ' O.*, '
END 


SET @SQLTXT = 'SELECT <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,  '
SET @SQLTXT = @SQLTXT + ' P.*, '
SET @SQLTXT = @SQLTXT + @SELECTEXTRA
SET @SQLTXT = @SQLTXT + ' F.*, '
SET @SQLTXT = @SQLTXT + ' U.INICIALES,ISNULL(U.NOMBRE,'''')+'' ''+ISNULL(U.APELLIDOS,'''') AS NOMBRE_USUARIO,(SELECT TOP 1 CAST(COMENTARIO AS VARCHAR(max)) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE IDPROSPECTO = P.IDPROSPECTO AND SISTEMA=0 ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO, '
SET @SQLTXT = @SQLTXT + '  (SELECT TOP 1 <#SESSION.DB/>.dbo.TIEMPO_TXT (FECHAHORA,GETDATE()) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE IDPROSPECTO = P.IDPROSPECTO AND SISTEMA=0 ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_TIEMPO '
SET @SQLTXT = @SQLTXT + ' FROM '
SET @SQLTXT = @SQLTXT + @COMPLEMENTO
SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.dbo.OPORTUNIDADES O, ' 
SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.dbo.PROSPECTOS P , '
SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.dbo.USUARIOS U, '
SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F '

IF(@TIPO = 3)
BEGIN
	 SET @SQLTXT = @SQLTXT + ' WHERE '+@CRITERIO+' O.IDPROSPECTO = P.IDPROSPECTO AND O.IDUSUARIO=U.IDUSUARIO AND P.IDUSUARIO=O.IDUSUARIO AND O.IDFASE = F.IDFASE '
END 
ELSE
BEGIN
	 SET @SQLTXT = @SQLTXT + ' WHERE O.IDPROSPECTO = P.IDPROSPECTO AND O.IDUSUARIO=U.IDUSUARIO AND P.IDUSUARIO=O.IDUSUARIO AND O.IDFASE = F.IDFASE ' +@CRITERIO
END


EXEC(@SQLTXT)
