//[idventa|Integer,session.db|Untyped,session.convertcode|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @GRUPOAUDITADO INT
DECLARE @IDVENTA INT
SET @IDVENTA=ISNULL(:IDVENTA,0)
 
SELECT @GRUPOAUDITADO=UG.AUDITADO FROM <#SESSION.DB/>.DBO.VENTAS V,<#SESSION.DB/>.DBO.USUARIOS U , <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG WHERE V.IDVENTA=@IDVENTA AND V.IDUSUARIO=U.IDUSUARIO AND U.IDGRUPO=UG.IDUSUARIOGRUPO


DECLARE @CONVERTCODE INT
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
IF  @CONVERTCODE = 0 SET  @CONVERTCODE = 103

DECLARE @TOTALCOBROS INT
SET @TOTALCOBROS = 0
DECLARE @MUESTRAPAGOS INT
SELECT @TOTALCOBROS=COUNT(*) FROM  <#SESSION.DB/>.DBO.VENTAS_COBROS VC WHERE IDVENTA=@IDVENTA
IF @TOTALCOBROS>1
  SET @MUESTRAPAGOS=1  
ELSE
  SELECT @MUESTRAPAGOS=(CASE WHEN PAGADO=1 THEN 0 ELSE 1 END) FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTA=@IDVENTA AND NOPARCIALIDAD=1  



SELECT @IDVENTA AS IDVENTA,
SALESUP_CT.dbo.esCanalizado(O.TKO, O.TKOM) AS esCanalizado, 
  (SELECT CASE WHEN COUNT(PA1.IDPROSPECTO) > 0 THEN '1' ELSE '' END FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA1 WHERE PA1.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != PA1.IDUSUARIO) AS COMPARTIDO,
  @GRUPOAUDITADO AS GRUPOAUDITADO,INDUSTRIA, COMPANIAGRUPO,
  LEN(ISNULL(MOVIL,0)) AS TIENEMOVIL, COM.TELEFONOCORPORATIVO,
  COM.URL AS URLEMPRESA,COM.DIRECCION1 AS DIRECCIONEMPRESA1, COM.DIRECCION2 AS DIRECCIONEMPRESA2, COM.CIUDAD AS CIUDADEMPRESA,COM.CODIGOPOSTAL AS CPEMPRESA,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = COM.IDESTADO AND IDPAIS=COM.IDPAIS) AS ESTADOEMPRESA, COM.NEMPLEADOS AS NEMPRESA,
   (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = COM.IDPAIS) AS PAISEMPRESA,
 
  O.CAMPO1 AS CAMPO1O, O.CAMPO2 AS CAMPO2O, O.CAMPO3 AS CAMPO3O, O.CAMPO4 AS CAMPO4O,
  O.CAMPO5 AS CAMPO5O, O.CAMPO6 AS CAMPO6O, O.CAMPO7 AS CAMPO7O, O.CAMPO8 AS CAMPO8O,
  CASE WHEN O.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO9,103) ELSE '' END AS CAMPO9O,
  CASE WHEN O.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO10,103) ELSE '' END AS CAMPO10O,
  CASE WHEN O.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO11,103) ELSE '' END AS CAMPO11O,
  CASE WHEN O.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO12,103) ELSE '' END AS CAMPO12O,
  O.CAMPO13+' ' AS CAMPO13O, O.CAMPO14+' ' AS CAMPO14O, O.CAMPO15+' ' AS CAMPO15O, O.CAMPO16+' ' AS CAMPO16O,
  O.CAMPO17+' ' AS CAMPO17O, O.CAMPO18+' ' AS CAMPO18O, O.CAMPO19+' ' AS CAMPO19O, O.CAMPO20+' ' AS CAMPO20O,
  O.CAMPO21 AS CAMPO21O, O.CAMPO22 AS CAMPO22O, O.CAMPO23 AS CAMPO23O, O.CAMPO24 AS CAMPO24O, O.CAMPO25 AS CAMPO25O, 
  O.CAMPO26+' ' AS CAMPO26O, O.CAMPO27+' ' AS CAMPO27O, O.CAMPO28+' ' AS CAMPO28O,
  O.CAMPO29+' ' AS CAMPO29O, O.CAMPO30+' ' AS CAMPO30O, O.CAMPO31+' ' AS CAMPO31O, O.CAMPO32+' ' AS CAMPO32O,
  O.CAMPO33+' ' AS CAMPO33O, O.CAMPO34+' ' AS CAMPO34O,
  
  P.CAMPO1 AS CAMPO1P, P.CAMPO2 AS CAMPO2P, P.CAMPO3 AS CAMPO3P, P.CAMPO4 AS CAMPO4P,
  P.CAMPO5 AS CAMPO5P, P.CAMPO6 AS CAMPO6P, P.CAMPO7 AS CAMPO7P, P.CAMPO8 AS CAMPO8P,
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '' END AS CAMPO9P,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '' END AS CAMPO10P,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '' END AS CAMPO11P,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '' END AS CAMPO12P,
  P.CAMPO13+' ' AS CAMPO13P, P.CAMPO14+' ' AS CAMPO14P, P.CAMPO15+' ' AS CAMPO15P, P.CAMPO16+' ' AS CAMPO16P,
  P.CAMPO17+' ' AS CAMPO17P, P.CAMPO18+' ' AS CAMPO18P, P.CAMPO19+' ' AS CAMPO19P, P.CAMPO20+' ' AS CAMPO20P,
  P.CAMPO21 AS CAMPO21P, P.CAMPO22 AS CAMPO22P, P.CAMPO23 AS CAMPO23P, P.CAMPO24 AS CAMPO24P,
  P.CAMPO25 AS CAMPO25P, P.CAMPO26+' ' AS CAMPO26P, P.CAMPO27+' ' AS CAMPO27P, P.CAMPO28+' ' AS CAMPO28P,
  P.CAMPO29+' ' AS CAMPO29P, P.CAMPO30+' ' AS CAMPO30P, P.CAMPO31+' ' AS CAMPO31P, P.CAMPO32+' ' AS CAMPO32P,
  P.CAMPO33+' ' AS CAMPO33P, P.CAMPO34+' ' AS CAMPO34P,

  CONVERT(VARCHAR(12), V.FECHAHORA,  @CONVERTCODE ) AS FECHAHORA,
  V.*,
  YEAR (V.FECHAHORA) AS A_CIERRE,
  MONTH (V.FECHAHORA) AS M_CIERRE,
  MONTH (V.FECHAHORA)-1 AS M_CIERRE_ANT,
  DAY (V.FECHAHORA) AS D_CIERRE,
  P.ETIQUETAS_TXT AS ETIQUETAS,  
  GANADA_FECHA, LP.LINEA_PRODUCTO,
  ISNULL(ARCHIVO, '') AS ARCHIVO,
  CASE WHEN ISNULL(P.IDCOMPANIA, 0) > 0 THEN '<a href="EmpresasVisualizar.dbsp?tkcom='+com.tkcom+'"><i class="fa fa-building-o"></i> '+P.EMPRESA+'</a>' ELSE p.EMPRESA END AS EMPRESA,
  P.EMPRESA as EmpresaTxt,COM.TKCOM,COM.CCAMPO1,COM.CCAMPO2,COM.CCAMPO3,COM.CCAMPO4,COM.CCAMPO5,COM.CCAMPO6,COM.CCAMPO7,COM.CCAMPO8,COM.CCAMPO9,COM.CCAMPO10,
  O.IdCatalogoOpcion1, O.IdCatalogoOpcion2, O.IdCatalogoOpcion3,
  O.*, P.*, F.FASE, P.IDUSUARIO AS D_PROS,
  isnull((SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WHERE PA.IDUSUARIO = <#SESSION.IDUSUARIO/> AND PA.IDPROSPECTO = P.IDPROSPECTO),0) AS asignado,
  <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,
   DATENAME (DD, O.FECHA_CIERRE)+'/'+CAST (DATEPART (MM,O.FECHA_CIERRE) AS VARCHAR)+'/'+DATENAME  (YYYY,O.FECHA_CIERRE) AS FECHA_CIERRE_EST,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = P.IDESTADO AND IDPAIS = P.IDPAIS) AS ESTADO,
  (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = P.IDPAIS) AS PAIS,  
  (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,
  (U.NOMBRE + ' ' + U.APELLIDOS) AS AGENTE, U.EMAIL,U.CALENDARIOPAGOS,@MUESTRAPAGOS AS MUESTRAPAGOS,
    ISNULL(ICONO_ARCHIVO, 'icon_default.jpg') AS ICONO_ARCHIVO,
  (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTA=@IDVENTA) AS NOPARCIALIDADES
FROM <#SESSION.DB/>.DBO.VENTAS V,  <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, <#SESSION.DB/>.DBO.OPORTUNIDADES O

  LEFT JOIN <#SESSION.DB/>.DBO.DOCUMENTO_ICONOS ON O.ARCHIVO != '' AND EXTENSION = <#SESSION.DB/>.dbo.obtiene_extension(ARCHIVO)
, <#SESSION.DB/>.DBO.PROSPECTOS P
	LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA AND COM.IDEMPRESA = <#SESSION.IDEMPRESA/>
    LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO 
    LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA,
 <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, <#SESSION.DB/>.DBO.USUARIOS U
WHERE
  V.IDVENTA = @IDVENTA AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND
  O.IDPROSPECTO = P.IDPROSPECTO  AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND 
  O.IDFASE = F.IDFASE AND 
  P.IDUSUARIO = U.IDUSUARIO