//[idventa|Text,tkv|Text,session.db|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,]
-- insert
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDVENTA INT
DECLARE @IDUSUARIO INT
DECLARE @FECHAMETA DATETIME

DECLARE @LISTA VARCHAR(MAX)
SET @LISTA = ISNULL(:IDVENTA,'')

DECLARE @TKV VARCHAR(MAX)
SET @TKV = ISNULL(:TKV,'')
IF @TKV != '' BEGIN SET @LISTA = <#SESSION.DB/>.dbo.obtieneListaIdVenta(@TKV) END

IF (@LISTA!='')
BEGIN
	DECLARE @TABLATEMP TABLE (ID INT IDENTITY, IDVENTA INT, IDUSUARIO INT, FECHAMETA DATETIME)
	DECLARE @TO INT, @TOTAL INT
	SET @TO = 1

	INSERT INTO @TABLATEMP (IDVENTA, IDUSUARIO, FECHAMETA)
	SELECT IDVENTA, IDUSUARIO, FECHAHORA FROM <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK) WHERE V.IDVENTA IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,','))
	
	SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

	WHILE @TO <= @TOTAL
	BEGIN
		SELECT @IDVENTA = IDVENTA, @IDUSUARIO = IDUSUARIO, @FECHAMETA = FECHAMETA FROM @TABLATEMP WHERE ID = @TO
		EXEC <#SESSION.DB/>.DBO.SP_ELIMINAR_VENTA @IDVENTA,<#SESSION.IDUSUARIO/>,<#SESSION.CONVERTCODE/>,1
		EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO 3, @IDUSUARIO, @FECHAMETA
		SET @TO = @TO + 1
	END
END

DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = <#SESSION.IDEMPRESA/>
DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 15 AND IDUSUARIO =<#SESSION.IDUSUARIO/> 

INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES(4,<#SESSION.IDEMPRESA/>) 
INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDUSUARIO) VALUES(15,<#SESSION.IDUSUARIO/>)



