//[idventa|Integer,session.convertcode|Untyped,session.db|Untyped,]
DECLARE @IDVENTA AS INT 


SET @IDVENTA= CAST(ISNULL(:IDVENTA,0) AS INT)

SELECT IDVENTACOBRO, IDVENTA, NOPARCIALIDAD, CONVERT(VARCHAR(10), FECHAHORA,<#SESSION.CONVERTCODE/> ) as FECHAHORA, MONTO, COMISION, ULTIMAMODIFICACION, REFERENCIA, AUDITADO, PAGADO,CONFIGURACION,ENVIOS
FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTA=@IDVENTA ORDER BY NOPARCIALIDAD ASC