//[tkcom|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.db|Untyped,f_usuario|Text,crit|Text,]
--select
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT,@IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @TkCom = dbo.ValidaToken(ISNULL(:TKCOM,''))
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)
SET @F_USUARIO = ISNULL(:F_USUARIO,'')
SET @CRIT = ISNULL(:CRIT, '')

SET @IDCOMPANIA = 0
IF @TkCom != ''
BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END

/*  OR @NIVELUSUARIO <= 2 OR @NIVELUSUARIO = 1 AND (@NIVELUSUARIO = 2 AND @IDGRUPO = U.IDGRUPO) */
SET @SQL ='
SELECT count(*) AS TotalResgistros 
FROM 
<#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, 
<#SESSION.DB/>.DBO.PROSPECTOS P 
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 ON CP21.IDOPCION = P.CAMPO21
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 ON CP22.IDOPCION = P.CAMPO22
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 ON CP23.IDOPCION = P.CAMPO23
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 ON CP24.IDOPCION = P.CAMPO24
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 ON CP25.IDOPCION = P.CAMPO25
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA ON PA.IDUSUARIO ='+CAST(@IDUSUARIO AS VARCHAR(1000))+' AND P.IDPROSPECTO = PA.IDPROSPECTO, 
<#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F,
<#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, 
<#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO

WHERE
  V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND
  O.IDPROSPECTO = P.IDPROSPECTO AND
  P.DESCARTADO = 0 AND v.IDUSUARIO = U.IDUSUARIO AND   
  O.IDFASE = F.IDFASE AND
  O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+'
  AND P.IDORIGEN = PO.IDORIGEN AND P.IDCOMPANIA = '+CAST(@IDCOMPANIA AS VARCHAR(1000))+'
  '+@F_USUARIO+'
  '+@CRIT+'

'
EXEC (@SQL)


