//[idventa|Text,comisionactual|Text,tipocomision|Text,idventacobro|Text,monto|Text,cobrooriginal|Text,totporpago|Text,accion|Text,fechacobro|Text,session.convertcode|Untyped,referencia|Text,auditado|Text,cobrar|Text,session.nivel|Untyped,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--update	
DECLARE @IDVENTACOBRO INT
DECLARE @IDVENTA INT
DECLARE @COMISIONACTUAL FLOAT
DECLARE @COMISIONFALTANTE FLOAT
DECLARE @TIPOCOMISION INT
DECLARE @TOTCOBROSPENDIENTES INT
DECLARE @COBROACTUAL FLOAT
DECLARE @COBROORIGINAL FLOAT
DECLARE @DIFERENCIA FLOAT
DECLARE @FECHA DATETIME
DECLARE @PARCIALIDADES INT
DECLARE @COMISION FLOAT
DECLARE @IDOPORTUNIDAD INT
DECLARE @TOTPORPAGAR FLOAT
DECLARE @ACCION INT
DECLARE @REFERENCIA VARCHAR(MAX)
DECLARE @COMISIONCOBRADA FLOAT,@COMISIONVENTA FLOAT
DECLARE @ULTIMACOMISION FLOAT
DECLARE @IDCOBROEXCLUIR INT
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME

SET @IDCOBROEXCLUIR=0
SET @IDVENTA = CAST(ISNULL(:IDVENTA,'') AS INT)
SET @COMISIONACTUAL=CAST(ISNULL(:comisionactual,'') AS FLOAT)
SET @TIPOCOMISION=CAST(ISNULL(:tipocomision,'') AS FLOAT)
SET @IDVENTACOBRO = CAST(ISNULL(:IDVENTACOBRO,'') AS INT)
SET @COBROACTUAL = CAST(ISNULL(:monto,'') AS FLOAT)
SET @COBROORIGINAL = CAST(ISNULL(:cobrooriginal,'') AS FLOAT)
SET @TOTPORPAGAR = CAST(ISNULL(:TOTPORPAGO,'') AS FLOAT)
SET @ACCION = CAST(ISNULL(:ACCION,'') AS INT)
SET @DIFERENCIA = @COBROORIGINAL-@COBROACTUAL
SET @FECHA=CONVERT(DATETIME,ISNULL(:fechacobro,''),<#SESSION.CONVERTCODE/>)
SET @REFERENCIA=:REFERENCIA
SET @ULTIMACOMISION=0

/*VARIABLES PARA REALIZAR COBRO*/
DECLARE @AUDITADO INT
DECLARE @NIVEL INT
DECLARE @COBRAR INT
DECLARE @ESAUDITADO INT 
 DECLARE @IDPROSPECTO INT
 DECLARE @AUDITOR VARCHAR(1000)
 DECLARE @SEGUIMIENTO VARCHAR(MAX)
 
 
 
 SET @AUDITADO = CAST(ISNULL(:AUDITADO,'') AS INT)
 SET @COBRAR = CAST(ISNULL(:COBRAR,'') AS INT)
 SET @NIVEL = <#SESSION.NIVEL/>
 SELECT @AUDITOR=NOMBRE +' ' + APELLIDOS FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>
 SELECT @IDOPORTUNIDAD=IDOPORTUNIDAD FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA=@IDVENTA
 SELECT @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
 SELECT @SEGUIMIENTO='Cobro '+(CAST(NOPARCIALIDAD AS VARCHAR(100))+' de '+CAST(V.NOPARCIALIDADES AS VARCHAR(100)))+' confirmado/auditado por '+@AUDITOR FROM <#SESSION.DB/>.DBO.VENTAS V , <#SESSION.DB/>.DBO.VENTAS_COBROS VC WHERE V.IDVENTA=VC.IDVENTA AND VC.IDVENTACOBRO=@IDVENTACOBRO

SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
SET @FECHAHOY = GETDATE()

UPDATE V SET V.CAMBIOLOCAL = 1 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P 
WHERE V.IDVENTA = @IDVENTA AND V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO AND V.TKVM IS NOT NULL AND O.TKOM IS NOT NULL AND P.TKPM IS NOT NULL	

 SELECT @ESAUDITADO=UG.AUDITADO FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG 
 		WHERE IDVENTA=@IDVENTA AND U.IDUSUARIO=V.IDUSUARIO AND U.IDGRUPO=UG.IDUSUARIOGRUPO AND U.IDEMPRESA=<#SESSION.IDEMPRESA/>
/*TERMINAN VARIABLES REALIZAR COBRO*/

SELECT @PARCIALIDADES = NOPARCIALIDADES+1, @COMISION=(case when monto>0 then comision/monto else 0 end),@COMISIONVENTA = COMISION FROM <#SESSION.DB/>.dbo.VENTAS WHERE IDVENTA= @IDVENTA
SELECT @COMISIONCOBRADA = SUM(COMISION) FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA AND PAGADO = 1
SELECT @COMISIONFALTANTE=@COMISIONVENTA-@COMISIONCOBRADA

IF (@TIPOCOMISION = 1)
   SELECT TOP 1 @IDCOBROEXCLUIR=IDVENTACOBRO FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA ORDER BY IDVENTACOBRO ASC
IF (@TIPOCOMISION = 2)
   SELECT TOP 1 @IDCOBROEXCLUIR=IDVENTACOBRO FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA ORDER BY IDVENTACOBRO DESC
   
IF (@IDVENTACOBRO > 0 )
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.VENTAS_COBROS SET FECHAHORA=@FECHA, MONTO=@COBROACTUAL, COMISION=(CASE WHEN @TIPOCOMISION=0 THEN (@COBROACTUAL*@COMISION) ELSE COMISION END),ULTIMAMODIFICACION=GETDATE(), REFERENCIA=@REFERENCIA  WHERE IDVENTACOBRO = @IDVENTACOBRO AND IDVENTA = @IDVENTA

	 SELECT @TOTCOBROSPENDIENTES=COUNT(*) FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA AND PAGADO = 0 AND IDVENTACOBRO NOT IN  (@IDVENTACOBRO,@IDCOBROEXCLUIR)
	 SELECT @ULTIMACOMISION=COMISION FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA AND IDVENTACOBRO = @IDVENTACOBRO
	 IF (@TIPOCOMISION!=3)
	 	BEGIN
	     SELECT @COMISIONCOBRADA = SUM(COMISION) FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA AND PAGADO = 1
	     SELECT @COMISIONFALTANTE=@COMISIONVENTA-@COMISIONCOBRADA-@ULTIMACOMISION
		END
     ELSE
	    BEGIN
	     SELECT @COMISIONCOBRADA = SUM(COMISION) FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA
	     SELECT @COMISIONFALTANTE=@COMISIONVENTA-@COMISIONCOBRADA
		END
		
		
  IF(@COBROORIGINAL <> @COBROACTUAL)
  BEGIN
  IF (@ACCION=0)
   BEGIN
    IF(@TOTPORPAGAR=0)
      DELETE FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTACOBRO != @IDVENTACOBRO AND PAGADO=0 AND IDVENTA = @IDVENTA
    ELSE
	 BEGIN
		 IF(@COMISIONCOBRADA < @COMISIONVENTA)
	 	   UPDATE <#SESSION.DB/>.dbo.VENTAS_COBROS SET MONTO=@TOTPORPAGAR, COMISION= (CASE WHEN @TIPOCOMISION!=3 AND IDVENTACOBRO != @IDCOBROEXCLUIR THEN @COMISIONFALTANTE/@TOTCOBROSPENDIENTES  ELSE COMISION END), ULTIMAMODIFICACION=GETDATE() 
		     WHERE IDVENTACOBRO NOT IN  (@IDVENTACOBRO) AND PAGADO=0 AND IDVENTA = @IDVENTA
	 	 ELSE
	 	   UPDATE <#SESSION.DB/>.dbo.VENTAS_COBROS SET MONTO=@TOTPORPAGAR, COMISION=(CASE WHEN @TIPOCOMISION=0 THEN (@TOTPORPAGAR*@COMISION) ELSE COMISION END), ULTIMAMODIFICACION=GETDATE() WHERE IDVENTACOBRO  NOT IN  (@IDVENTACOBRO) AND PAGADO=0 AND IDVENTA = @IDVENTA
	 END
   END
  ELSE
   BEGIN
    IF (@ACCION=1)
     BEGIN
      IF (@DIFERENCIA>0)
         INSERT INTO <#SESSION.DB/>.dbo.VENTAS_COBROS (IDVENTA,NOPARCIALIDAD,FECHAHORA,MONTO,COMISION,PAGADO,ULTIMAMODIFICACION,AUDITADO)
 	     SELECT IDVENTA,@PARCIALIDADES,FECHAHORA,@DIFERENCIA,(CASE WHEN @COMISIONFALTANTE>0  THEN @COMISIONFALTANTE ELSE 0 END),0,GETDATE(),@AUDITADO FROM  <#SESSION.DB/>.dbo.VENTAS_COBROS 
			   WHERE IDVENTACOBRO = @IDVENTACOBRO AND IDVENTA = @IDVENTA
     END	
   END	
   END 
  SELECT @PARCIALIDADES=COUNT(*) FROM <#SESSION.DB/>.dbo.VENTAS_COBROS WHERE IDVENTA = @IDVENTA
  UPDATE  <#SESSION.DB/>.dbo.VENTAS SET NOPARCIALIDADES=@PARCIALIDADES WHERE IDVENTA= @IDVENTA
  
  /*Se realiza el cobro*/
  IF(@COBRAR = 1)
  BEGIN
  	   IF (@ESAUDITADO=1) AND (@NIVEL!=1)
            UPDATE <#SESSION.DB/>.DBO.VENTAS_COBROS SET PAGADO=1, AUDITADO=0 WHERE  IDVENTACOBRO=@IDVENTACOBRO
       ELSE
            UPDATE <#SESSION.DB/>.DBO.VENTAS_COBROS SET PAGADO=1, AUDITADO=1 WHERE IDVENTACOBRO=@IDVENTACOBRO
		
		EXEC <#SESSION.DB/>.DBO.SP_INSERTA_EMAIL_COBRO_PROGRAMADO @IDVENTACOBRO, -1
		EXEC <#SESSION.DB/>.DBO.SP_CALCULA_FECHA_PROXIMO_ENVIO @IDVENTACOBRO

       IF (@ESAUDITADO=1) AND (@NIVEL=1)
         BEGIN
          IF (@IDPROSPECTO>0 AND @IDOPORTUNIDAD>0)
             INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
             VALUES (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, @SEGUIMIENTO)
         END
        EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO 3, <#SESSION.IDUSUARIO/>, @FECHA
  END
  /*FINALIZA COBRO*/
END
 EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1	