//[session.db|Untyped,idoportunidad|Integer,session.idusuario|Untyped,seguimiento|Text,session.convertcode|Untyped,]
--insert
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
SET @IDOPORTUNIDAD=ISNULL(:IDOPORTUNIDAD,0)

  SELECT @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD


  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO
  (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
  VALUES 
  (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, ISNULL(:seguimiento,''))
  

DECLARE @ID INT
  
  SELECT TOP 1 @ID = IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO
  WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD AND IDUSUARIO = <#SESSION.IDUSUARIO/>
  ORDER BY IDSEGUIMIENTO DESC
  
EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES <#SESSION.IDUSUARIO/>, 10, @IDPROSPECTO, @IDOPORTUNIDAD, <#SESSION.CONVERTCODE/>, '', @ID