//[session.nivel|Untyped,session.db|Untyped,idventacobro|Integer,session.idusuario|Untyped,session.idempresa|Untyped,]
--UPDATE
 DECLARE @FECHA DATETIME
 DECLARE @IDVENTA INT
 DECLARE @NIVEL INT
 DECLARE @AUDITADO INT
 DECLARE @ESAUDITADO INT
 
 DECLARE @IDOPORTUNIDAD INT
 DECLARE @IDPROSPECTO INT
 DECLARE @AUDITOR VARCHAR(1000)
 DECLARE @SEGUIMIENTO VARCHAR(MAX)
 SET @IDPROSPECTO=0
 SET @IDOPORTUNIDAD=0
 SET @AUDITOR = ''
 SET @SEGUIMIENTO= ''
 
 
 SET @NIVEL=<#SESSION.NIVEL/>
 SELECT @IDVENTA = IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTACOBRO = :idventacobro
 SELECT @FECHA = ISNULL(FECHAHORA,GETDATE()) FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA = @IDVENTA
 
 SELECT @AUDITOR=NOMBRE +' ' + APELLIDOS FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>
 SELECT @IDOPORTUNIDAD=IDOPORTUNIDAD FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA=@IDVENTA
 SELECT @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
 SELECT @SEGUIMIENTO='Cobro '+(CAST(NOPARCIALIDAD AS VARCHAR(100))+' de '+CAST(V.NOPARCIALIDADES AS VARCHAR(100)))+' no confirmado/no auditado por '+@AUDITOR FROM <#SESSION.DB/>.DBO.VENTAS V , <#SESSION.DB/>.DBO.VENTAS_COBROS VC WHERE V.IDVENTA=VC.IDVENTA AND VC.IDVENTACOBRO=:idventacobro

UPDATE V SET V.CAMBIOLOCAL = 1 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P 
WHERE V.IDVENTA = @IDVENTA AND V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO AND V.TKVM IS NOT NULL AND O.TKOM IS NOT NULL AND P.TKPM IS NOT NULL	
 
 SELECT @ESAUDITADO=UG.AUDITADO FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG 
 		WHERE IDVENTA=@IDVENTA AND U.IDUSUARIO=V.IDUSUARIO AND U.IDGRUPO=UG.IDUSUARIOGRUPO AND U.IDEMPRESA=<#SESSION.IDEMPRESA/>
 
  
 IF (@ESAUDITADO=1)
  BEGIN
  		UPDATE <#SESSION.DB/>.DBO.VENTAS_COBROS
			   SET PAGADO=0, AUDITADO=0
	    WHERE 
		      IDVENTACOBRO=:idventacobro 
  END
 ELSE
  BEGIN 
  		UPDATE <#SESSION.DB/>.DBO.VENTAS_COBROS
			   SET PAGADO=0, AUDITADO=0
	    WHERE 
		      IDVENTACOBRO=:idventacobro
  END
  
  IF (@ESAUDITADO=1) AND (@NIVEL=1)
  BEGIN
    IF (@IDPROSPECTO>0 AND @IDOPORTUNIDAD>0)
      BEGIN
       INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO
       (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
       VALUES 
       (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, @SEGUIMIENTO)
     END
  END
 
  EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO 3, <#SESSION.IDUSUARIO/>, @FECHA