//[session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.db|Untyped,f_usuario|Text,crit|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :CRIT , '')
DECLARE @F_USUARIO VARCHAR(MAX) SET @F_USUARIO = ISNULL( :F_USUARIO , '')

SET @SQL = '
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT
SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)
SET @IDUSUARIO = CAST(''<#SESSION.IDUSUARIO/>'' AS INT)
SET @NIVELUSUARIO = CAST(''<#SESSION.NIVEL/>'' AS INT)
SET @IDGRUPO = CAST(''<#SESSION.IDGRUPO/>'' AS INT)

SELECT COUNT(*) AS TotalResgistros
FROM 
<#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, 
<#SESSION.DB/>.DBO.PROSPECTOS P LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA ON PA.IDUSUARIO = @IDUSUARIO AND P.IDPROSPECTO = PA.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA, 
<#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F,
<#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, 
<#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO

WHERE
  V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND
  O.IDPROSPECTO = P.IDPROSPECTO AND
  P.DESCARTADO = 0 AND v.IDUSUARIO = U.IDUSUARIO AND   
  O.IDFASE = F.IDFASE AND
  O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND P.IDEMPRESA = @IDEMPRESA
  AND P.IDORIGEN = PO.IDORIGEN 
  
 ' +  @F_USUARIO + '
 ' +  @CRIT + ''



EXEC (@SQL) 

