//[idplantilla|Integer,idventacobro|Integer,session.db|Untyped,]
-- SELECT 
/*PROTEGIDO*/

DECLARE @IDPLANTILLA INT,@IDPROSPECTO INT, @IDUSUARIO INT, @IDEMPRESA INT, @IDOPORTUNIDAD INT,@IDVENTA INT,@IDVENTACOBRO INT
DECLARE @CORREOUSUARIO VARCHAR(512), @CORREOCONTACTO VARCHAR(512),@NOMBREUSUARIO VARCHAR(512), @NOMBRECONTACTO VARCHAR(512)

SET @IDPLANTILLA = ISNULL(:IDPLANTILLA,0)
SET @IDVENTACOBRO = ISNULL(:IDVENTACOBRO,0)

SELECT @IDVENTA = IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTACOBRO = @IDVENTACOBRO
SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD, @IDUSUARIO = IDUSUARIO FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA = @IDVENTA
SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
SELECT @CORREOCONTACTO = CORREO, @NOMBRECONTACTO = ISNULL(NOMBRE,'') + ' ' + ISNULL(APELLIDOS,'') FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
SELECT @IDEMPRESA = IDEMPRESA, @CORREOUSUARIO = EMAIL, @NOMBREUSUARIO = ISNULL(NOMBRE,'') + ' ' + ISNULL(APELLIDOS,'') FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO

SELECT
<#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponderCobros(ASUNTO,@IDPROSPECTO,@IDUSUARIO,@IDEMPRESA,@IDOPORTUNIDAD,@IDVENTACOBRO) AS ASUNTO,
<#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponderCobros(CUERPO,@IDPROSPECTO,@IDUSUARIO,@IDEMPRESA,@IDOPORTUNIDAD,@IDVENTACOBRO) AS CUERPO,
@CORREOUSUARIO AS CORREOUSUARIO, @CORREOCONTACTO AS CORREOCONTACTO, ANEXOS, NOMBRE_ARCHIVO_REAL, @NOMBREUSUARIO AS NOMBRE_USUARIO,@NOMBRECONTACTO AS NOMBRE_CONTACTO, @IDEMPRESA AS IDEMPRESA
FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA