//[session.nivel|Untyped,idprospecto|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.db|Untyped,]
--SELECT 
/*PROTEGIDO*/

DECLARE @NIVEL INT 
DECLARE @IDPROSPECTO INT 
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @IDGRUPO INT

SET @NIVEL= <#SESSION.NIVEL/>
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO, 0) 
SET @IDEMPRESA= <#SESSION.IDEMPRESA/>
SET @IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @IDGRUPO=<#SESSION.IDGRUPO/>

IF @NIVEL=1
BEGIN
	SELECT 
	COUNT(*) as totaln
  	FROM 
    <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
    P.IDEMPRESA =@IDEMPRESA AND P.IDPROSPECTO = @IDPROSPECTO AND P.IDPROSPECTO = O.IDPROSPECTO 
	AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND V.IDUSUARIO = U.IDUSUARIO
END
IF @NIVEL=2
BEGIN
	SELECT 
	count(*) as totaln
  	FROM 
    <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P,  <#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
    P.IDEMPRESA = @IDEMPRESA AND P.IDPROSPECTO =  @IDPROSPECTO AND P.IDPROSPECTO = O.IDPROSPECTO AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
	AND V.IDUSUARIO = U.IDUSUARIO 
	AND (U.IDGRUPO = @IDGRUPO  OR P.IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PAM WHERE IDUSUARIO = @IDUSUARIO))

END
IF @NIVEL=3
BEGIN
	SELECT 
	count(*) as totaln
 	FROM 
    <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O,  <#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
  	O.IDPROSPECTO = @IDPROSPECTO AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND V.IDUSUARIO = U.IDUSUARIO 
	AND (O.IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PAM WHERE IDUSUARIO = @IDUSUARIO))

END
IF @NIVEL not in (1,2,3)
	SELECT   0 as TOTALN 