//[idventacobro|Integer,session.db|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,]
--UpDATE
DECLARE @IDVENTA INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDPROSPECTO INT
DECLARE @AUDITOR VARCHAR(1000)
DECLARE @SEGUIMIENTO VARCHAR(MAX)
DECLARE @idventacobro INT
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME
SET @idventacobro=ISNULL(:idventacobro,0)
SET @IDPROSPECTO=0
SET @IDOPORTUNIDAD=0
SET @AUDITOR = ''
SET @SEGUIMIENTO= ''
SELECT @IDVENTA = IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTACOBRO = @idventacobro
SELECT @AUDITOR=NOMBRE +' ' + APELLIDOS FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>
SELECT @IDOPORTUNIDAD=IDOPORTUNIDAD FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA=@IDVENTA
SELECT @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
SELECT @SEGUIMIENTO='Cobro '+(CAST(NOPARCIALIDAD AS VARCHAR(100))+' de '+CAST(V.NOPARCIALIDADES AS VARCHAR(100)))+' confirmado/auditado por '+@AUDITOR FROM <#SESSION.DB/>.DBO.VENTAS V , <#SESSION.DB/>.DBO.VENTAS_COBROS VC WHERE V.IDVENTA=VC.IDVENTA AND VC.IDVENTACOBRO=@idventacobro

SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
SET @FECHAHOY = GETDATE()

UPDATE V SET V.CAMBIOLOCAL = 1 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P 
WHERE V.IDVENTA = @IDVENTA AND V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO AND V.TKVM IS NOT NULL AND O.TKOM IS NOT NULL AND P.TKPM IS NOT NULL		

UPDATE <#SESSION.DB/>.DBO.VENTAS_COBROS SET AUDITADO=1, ULTIMAMODIFICACION=GETDATE() WHERE IDVENTACOBRO=@idventacobro
EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1
			  
IF (@IDPROSPECTO>0 AND @IDOPORTUNIDAD>0)
BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO
  (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
  VALUES 
  (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, @SEGUIMIENTO)
END  
   