//[session.db|Untyped,idsproductos|Text,listacantidad|Text,]

-- SELECT 
DECLARE @TABLAERRORES TABLE (ID INT IDENTITY, PRODUCTO VARCHAR(MAX), EXISTENCIA INT, CANTIDAD FLOAT)
DECLARE @TABLA TABLE (ID INT IDENTITY, IDPRODUCTO INT, CANTIDAD FLOAT)
DECLARE @TABLA2 TABLE (ID INT IDENTITY, IDPRODUCTO INT, CANTIDAD FLOAT)
DECLARE @TO INT = 1
DECLARE @TOTAL INT,@CANTIDAD INT,@EXISTENCIA INT, @IDPRODUCTO INT
declare @idProductos varchar(1024)
declare @ltCantidad varchar(1024)

set @idProductos = isnull(:IDSPRODUCTOS, '')
set @ltCantidad = ISNULL(:LISTACANTIDAD, '')

INSERT INTO @TABLA (IDPRODUCTO, CANTIDAD)
SELECT	RTRIM(LTRIM(LTP.SPLITVALUE)),
        RTRIM(LTRIM(LTC.SPLITVALUE))
        FROM SALESUP_CT.DBO.SPLIT(@idProductos,',') LTP, SALESUP_CT.DBO.SPLIT(@ltCantidad,',') LTC where  LTP.OCCURENCEID = LTC.OCCURENCEID

INSERT INTO @TABLA2 (IDPRODUCTO, CANTIDAD)
SELECT IDPRODUCTO, SUM(CANTIDAD) FROM @TABLA GROUP BY IDPRODUCTO

SELECT @TOTAL = COUNT(*) FROM @TABLA2

WHILE(@TO <= @TOTAL)
BEGIN
	SELECT @IDPRODUCTO = IDPRODUCTO, @CANTIDAD = CANTIDAD FROM @TABLA2 WHERE ID = @TO
	SELECT @EXISTENCIA = EXISTENCIA FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDPRODUCTO = @IDPRODUCTO
	
	IF(@EXISTENCIA = 0 OR (@EXISTENCIA >= 1 AND @EXISTENCIA < @CANTIDAD))
	BEGIN
		INSERT INTO @TABLAERRORES (PRODUCTO,EXISTENCIA,CANTIDAD) SELECT NOMBRE,EXISTENCIA, @CANTIDAD FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDPRODUCTO = @IDPRODUCTO
	END
	SET @TO = @TO + 1
END

SELECT * FROM @TABLAERRORES