//[tkv|Text,session.db|Untyped,]
-- SELECT 
/*PROTEGIDO*/

DECLARE @TKV VARCHAR(128)
DECLARE @IDVENTA INT

SET @TKV = ISNULL(:TKV,'')

SELECT @IDVENTA = IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS WHERE TKV = @TKV

SELECT IDVENTACOBRO,CONVERT(VARCHAR(10),FECHAHORA, 103) AS FECHAHORA, MONTO, REFERENCIA,CONFIGURACION,FECHAPROXIMOENVIO,ENVIOS FROM <#SESSION.DB/>.DBO.VENTAS_COBROS WHERE IDVENTA = @IDVENTA AND PAGADO = 0