//[session.nivel|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,ventaid|Text,par|Text,fecha|Text,session.convertcode|Untyped,comision|Text,pago|Text,pagado|Text,referenciaventa|Text,concepto|Text,configuracion|Text,envios|Text,session.db|Untyped,]
--INSERT
DECLARE @IDVENTA INT
DECLARE @PAR INT
DECLARE @FECHA DATETIME
DECLARE @COMISION MONEY
DECLARE @PAGO MONEY
DECLARE @PAGADO INT
DECLARE @REFERENCIAVENTA VARCHAR(MAX)
DECLARE @IDGRUPO INT
DECLARE @AUDITADO INT
DECLARE @IDEMPRESA INT
DECLARE @NIVEL INT
DECLARE @CONCEPTO VARCHAR(128)
DECLARE @IDOPORTUNIDAD INT

DECLARE @CONFIGURACION VARCHAR(MAX)
DECLARE @ENVIOS VARCHAR(10)

DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME

SET @NIVEL=<#SESSION.NIVEL/>
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @AUDITADO=1
SET @IDGRUPO=<#SESSION.IDGRUPO/>
SET @IDVENTA=CAST(ISNULL(:VENTAID,'') AS INT)
SET @PAR=CAST(ISNULL(:PAR,'') AS INT)
SET @FECHA=CONVERT(DATETIME,ISNULL(:FECHA,''),<#SESSION.CONVERTCODE/>)
SET @COMISION=CAST(CAST(ISNULL(:COMISION,'') AS FLOAT) AS MONEY)
SET @PAGO=CAST(CAST(ISNULL(:PAGO,'') AS FLOAT) AS MONEY)
SET @PAGADO=CAST(ISNULL(:PAGADO,'') AS INT)
SET @REFERENCIAVENTA=CAST(:REFERENCIAVENTA AS VARCHAR(MAX))
SET @CONCEPTO = :CONCEPTO
SET @CONFIGURACION = :CONFIGURACION
SET @ENVIOS = :ENVIOS
SET @FECHAHOY = GETDATE()
IF(@CONFIGURACION = 'UNDEF' OR @CONFIGURACION = 'null' OR @CONFIGURACION = 'undefined')
BEGIN
	SET @CONFIGURACION = NULL
	SET @ENVIOS = NULL
END

SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD FROM <#SESSION.DB/>.DBO.VENTAS WHERE IDVENTA = @IDVENTA

SELECT @P = CAST(IDPROSPECTO AS VARCHAR(MAX)) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE @IDOPORTUNIDAD = IDOPORTUNIDAD 

UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET CONCEPTO = @CONCEPTO WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD

SELECT @AUDITADO=(CASE WHEN AUDITADO=0 THEN 1 ELSE 0 END) FROM  <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO=@IDGRUPO AND IDEMPRESA=@IDEMPRESA
SELECT @AUDITADO=(CASE WHEN AUDITADO=0 THEN 1 WHEN (@NIVEL=1 AND @PAGADO=1) THEN 1 ELSE 0 END) FROM  <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDUSUARIOGRUPO=@IDGRUPO AND IDEMPRESA=@IDEMPRESA

  INSERT INTO <#SESSION.DB/>.DBO.VENTAS_COBROS WITH(ROWLOCK) (IDVENTA,NOPARCIALIDAD,FECHAHORA,MONTO,COMISION,PAGADO,REFERENCIA,AUDITADO,CONFIGURACION,ENVIOS)
  VALUES (@IDVENTA,@PAR,@FECHA,@PAGO,@COMISION, @PAGADO,@REFERENCIAVENTA,@AUDITADO,@CONFIGURACION,@ENVIOS)
  
  EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1
