//[session.db|Untyped,session.idempresa|Untyped,idventa|Integer,]
--SELECT

DECLARE @GRUPOAUDITADO INT, @IDVENTA INT, @TIPODECAMBIO INT, @IDEMPRESAMONEDADEFAULT INT, @IDEMPRESA INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDVENTA =  ISNULL(:IDVENTA,0) 

SELECT 
	@GRUPOAUDITADO = UG.AUDITADO , 
	@IDEMPRESAMONEDADEFAULT = V.IDEMPRESAMONEDADEFAULT, 
	@TIPODECAMBIO = V.TIPODECAMBIO
FROM 
	<#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.USUARIOS U , 
	<#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG 
WHERE 
	V.IDVENTA =  @IDVENTA
	AND V.IDUSUARIO = U.IDUSUARIO 
	AND U.IDGRUPO = UG.IDUSUARIOGRUPO

SELECT 
	VC.MONTO AS MONTO, 
	VC.COMISION AS COMISION, 
	MONCT.MONEDA_SIMBOLO, UNICODE(MONCT.MONEDA_SIMBOLO) AS UNICODEMONEDA, 
	VC.IDVENTACOBRO, VC.IDVENTA, VC.NOPARCIALIDAD, VC.FECHAHORA, VC.PAGADO, 
	VC.ULTIMAMODIFICACION, VC.REFERENCIA, VC.AUDITADO, VC.CONFIGURACION, VC.FECHAPROXIMOENVIO, VC.ENVIOS, 
	@GRUPOAUDITADO AS GRUPOAUDITADO 
FROM 
	<#SESSION.DB/>.DBO.VENTAS_COBROS VC 
	JOIN <#SESSION.DB/>.DBO.VENTAS V ON V.IDVENTA = VC.IDVENTA
	LEFT JOIN <#SESSION.DB/>.DBO.MONEDAS MON ON MON.IDEMPRESAMONEDA = V.IDMONEDA
	LEFT JOIN SALESUP_CT.DBO.MONEDAS MONCT ON MONCT.IDMONEDA = MON.IDMONEDA
WHERE 
	VC.IDVENTA =  @IDVENTA AND VC.PAGADO = 1






