//[bd|Text,idusuario|Integer,idrecordatorio|Integer,]
--select
DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDRECORDATORIO VARCHAR(1000)
DECLARE @IDUSUARIO VARCHAR(1000)
SET @IDRECORDATORIO=CAST(ISNULL(:IDRECORDATORIO,0) AS VARCHAR(1000))
SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO, 0) AS VARCHAR(1000))
SET @EXECSQL = 'SELECT REPLACE(RECORDATORIO,''"'','''') AS RECORDATORIO, CONVERT(VARCHAR,R.FECHAHORA,20) AS FECHAHORA,R.* FROM '+@BD+'.dbo.RECORDATORIOS R WITH (NOLOCK) '
SET @EXECSQL = @EXECSQL + 'WHERE R.IDUSUARIO = '+@IDUSUARIO+' AND R.IDRECORDATORIO = '+@IDRECORDATORIO
EXEC(@EXECSQL)