//[tk|Text,]
-- select

DECLARE @TK VARCHAR(64)

SET @TK = dbo.ValidaToken(:TK)

SELECT top 120 
CO.OPCION as Proyecto, CO.ULTIMAMODIFICACION AS FechaInicio, UP.INICIALES AS Vendedor, REPLACE(REPLACE(CAST(CO.DESCRIPCION AS VARCHAR(128)), '<p>', ''), '</p>', '') AS Descripcion, CASE WHEN (CO.ACTIVO = 1) THEN 'Activo' ELSE 'Inactivo' END AS Estatus, 
P.Nombre +' '+ P.Apellidos AS Prospecto, Fase AS Fase,P.Empresa,   UP.INICIALES AS Vendedor, 
CONVERT(datetime,FechaCreacion,103) AS Creacion,
ROUND(
LTRIM(ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SALESUP_DB8.dbo.RemueveLetras(CO.CAMPO13), ',', ''), '$', ''), '  ', ' '), ' ', ''), 'USD', ''), '0')), 
0) as Monto,
--P.CAMPO1 AS MontoEstimado, 
ECO.OPCION As UnidadNegocio, P.CAMPO21 AS MontoEstimado,
L.LINEA_Producto as Linea,O.MONTO AS MontoReal,  CONVERT(datetime,O.FECHAHORA,103) AS FechaCreacion, 
CONVERT(datetime,Fecha_cierre,103) as FechaEstimadaCierre, O.CAMPO13 AS Obra,
 V.MONTO as MontoFinal, CONVERT(datetime, V.FechaHora,103) As FechaCierre
FROM 
SALESUP_DB8.dbo.EMPRESAS_REPORTES ER, 
SALESUP_DB8.dbo.CATALOGOS C,
SALESUP_DB8.dbo.PROSPECTOS_FASES PF,
SALESUP_DB8.dbo.CATALOGOS_OPCIONES CO,
SALESUP_DB8.dbo.PROSPECTOS P 
LEFT JOIN SALESUP_DB8.dbo.OPORTUNIDADES O ON O.IDPROSPECTO = P.IDPROSPECTO AND PERDIDA = 0
LEFT JOIN SALESUP_DB8.dbo.VENTAS V ON V.IDOPORTUNIDAD = O.IDOPORTUNIDAD
LEFT JOIN SALESUP_DB8.dbo.USUARIOS UP ON UP.IDUSUARIO = P.IDUSUARIO 
LEFT JOIN SALESUP_DB8.dbo.USUARIOS_GRUPOS UG ON UG.IDUSUARIOGRUPO = UP.IDGRUPO 
LEFT JOIN SALESUP_DB8.dbo.EMPRESAS_LINEAS_PRODUCTO L ON O.IDLINEA_PRODUCTO = L.IDLINEA_PRODUCTO 
LEFT JOIN SALESUP_DB8.dbo.EMPRESAS_CAMPOS_OPCIONES ECO ON ECO.IDOPCION = P.CAMPO23  
WHERE 
  ER.TK = @TK  AND P.IDEMPRESA = ER.IDEMPRESA AND
  C.IDCATALOGO = ER.IDCATALOGO AND P.IDCATALOGOOPCION1 = CO.IDCATALOGOOPCION
  /* AND  CO.ACTIVO = 1*/ AND P.DESCARTADO = 0
   AND P.IDFASE = PF.IDFASE
  
  ORDER BY LTRIM(RTRIM(CO.OPCION))