//[datos|Text,sessionid|Text,base|Text,]
-- SELECT 

--SELECT 
DECLARE @SQL VARCHAR(MAX)
SET @SQL = '


DECLARE @DATOSJSON VARCHAR(MAX)
DECLARE @SESSIONID INT

SET @DATOSJSON =  ''' + :DATOS + '''
SET @SESSIONID = CAST(''' + :SESSIONID + ''' AS INT) 

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDUSUARIO INT, IDEMPRESA INT, IDPROSPECTO_LOCAL INT,ARCHIVADO INT, IDPROSPECTO INT)
DECLARE @TO INT, @TOTAL INT, @CONTEO INT
DECLARE @IDUSUARIO VARCHAR(10)
DECLARE @ARCHIVADO INT
DECLARE @IDPROSPECTO VARCHAR(10)
DECLARE @IDEMPRESA INT

INSERT INTO @TABLATEMP (IDUSUARIO, IDEMPRESA, IDPROSPECTO_LOCAL,ARCHIVADO, IDPROSPECTO)
Select 
       max(case when NAME=''IDUSUARIO'' then STRINGVALUE else '''' end) as IDUSUARIO,
	   max(case when NAME=''IDEMPRESA'' then STRINGVALUE else '''' end) as IDEMPRESA,
       max(case when NAME=''IDPROSPECTO_LOCAL'' then STRINGVALUE else '''' end) as IDPROSPECTO_LOCAL,
       max(case when NAME=''ARCHIVADO'' then STRINGVALUE else '''' end) as ARCHIVADO,
       max(case when NAME=''IDPROSPECTO'' then STRINGVALUE else '''' end) as IDPROSPECTO
from SALESUP_CT.dbo.parseJSON(@DATOSJSON)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDUSUARIO = CAST(IDUSUARIO AS VARCHAR(10)),@IDEMPRESA = IDEMPRESA, @ARCHIVADO = ARCHIVADO, @IDPROSPECTO = CAST(IDPROSPECTO AS VARCHAR(10)) FROM @TABLATEMP WHERE ID = @TO
	EXEC ' + :BASE + '.DBO.SP_COMPARTIR_PROSPECTOS @SESSIONID, @IDEMPRESA, @IDPROSPECTO, @IDUSUARIO, 120
	SET @TO = @TO+1
END

SELECT 1 AS RESPUESTA

' 
EXEC (@SQL)