//[bd|Text,fecha|Text,idusuario|Text,]
--SELECT

DECLARE @DB VARCHAR(512)

DECLARE @FECHA DATETIME


SET @DB = :BD
SET @FECHA = CONVERT(DATETIME,  ISNULL(:FECHA,''), 20)


DECLARE @SQL VARCHAR(MAX)
SET @SQL = '' 
SET @SQL =  @SQL + ' DECLARE @YASINCRONIZADO INT '
SET @SQL =  @SQL + ' IF(CONVERT(DATETIME,'''+ CONVERT(VARCHAR(32), @FECHA, 20) +''',20) = 0)' 
SET @SQL =  @SQL + ' BEGIN'
SET @SQL =  @SQL + ' 	SET @YASINCRONIZADO = 0'
SET @SQL =  @SQL + ' END '
SET @SQL =  @SQL + ' ELSE' 
SET @SQL =  @SQL + ' BEGIN' 
SET @SQL =  @SQL + ' 	SET @YASINCRONIZADO = 1'
SET @SQL =  @SQL + ' END ' 
SET @SQL =  @SQL + ' SELECT  SALESUP_CT.dbo.PreparaCadenaJson(REPLACE(CONCEPTO,'''''''','''')) AS CONCEPTO , CONVERT(VARCHAR,FECHA_CIERRE,20) AS FECHA_CIERRE, CONVERT(VARCHAR,GANADA_FECHA,20) AS GANADA_FECHA,' 
SET @SQL =  @SQL + '  CONVERT(VARCHAR,PERDIDA_FECHA,20) AS PERDIDA_FECHA, SALESUP_CT.dbo.PreparaCadenaJson(PERDIDA_RAZON) AS PERDIDA_RAZON,CONVERT(VARCHAR,FECHAHORA,20) AS FECHAHORA, '
SET @SQL =  @SQL + '  CONVERT(VARCHAR,FECHA_ULTIMOSEGUIMIENTO,20) AS FECHA_ULTIMOSEGUIMIENTO, IDOPORTUNIDAD,IDPROSPECTO,MONTO,CERTEZA,IDFASE,IDLINEA_PRODUCTO,COMISION,COMISION_MONTO,ARCHIVO,GANADA,MONTO_PAGADO,PERDIDA,'
SET @SQL =  @SQL + '  IDULTIMOSEGUIMIENTO,FECHA_PROXIMORECORDATORIO,IDUSUARIO,ID_ANT,ULTIMAMODIFICACION,AMAZON,IDRAZONPERDIDA,NARCHIVOS,TKO,IDPETICION,'
SET @SQL =  @SQL + '  CAMPO1,CAMPO2,CAMPO3,CAMPO4,CAMPO5,CAMPO6,CAMPO7,CAMPO8,CONVERT(VARCHAR,CAMPO9,20) as CAMPO9,CONVERT(VARCHAR,CAMPO10,20) as CAMPO10,CONVERT(VARCHAR,CAMPO11,20) as CAMPO11,CONVERT(VARCHAR,CAMPO12,20) as CAMPO12,' 
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO13) as CAMPO13,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO14) as CAMPO14,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO15) as CAMPO15,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO16) as CAMPO16,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO17) as CAMPO17,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO18) as CAMPO18,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO19) as CAMPO19,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO20) as CAMPO20,' 
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO21) as CAMPO21,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO22) as CAMPO22,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO23) as CAMPO23,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO24) as CAMPO24,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO25) as CAMPO25, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO26) as CAMPO26,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO27) as CAMPO27,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO28) as CAMPO28,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO29) as CAMPO29,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO30) as CAMPO30,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO31) as CAMPO31,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO32) as CAMPO32,'
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO33) as CAMPO33,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO34) as CAMPO34,SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO35) as CAMPO35, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO36) as CAMPO36, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO37) as CAMPO37, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO38) as CAMPO38, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO39) as CAMPO39, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO40) as CAMPO40, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO41) as CAMPO41, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO42) as CAMPO42, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO43) as CAMPO43, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO44) as CAMPO44, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO45) as CAMPO45, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO46) as CAMPO46, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO47) as CAMPO47, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO48) as CAMPO48, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO49) as CAMPO49, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO50) as CAMPO50, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO51) as CAMPO51, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO52) as CAMPO52, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO53) as CAMPO53, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO54) as CAMPO54, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO55) as CAMPO55, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO56) as CAMPO56, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO57) as CAMPO57, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO58) as CAMPO58, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO59) as CAMPO59, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO60) as CAMPO60, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO61) as CAMPO61, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO62) as CAMPO62, '
SET @SQL =  @SQL + ' SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO63) as CAMPO63, SALESUP_CT.DBO.PreparaCadenaApp2(CAMPO64) as CAMPO64,'
SET @SQL =  @SQL + ' IDCATALOGOOPCION1, IDCATALOGOOPCION2,IDCATALOGOOPCION3, TKO, TKOM'
SET @SQL =  @SQL + ' FROM '+@DB+'.dbo.OPORTUNIDADES WITH (NOLOCK) '
SET @SQL =  @SQL + ' WHERE (PERDIDA = 0 OR (PERDIDA_FECHA >= CONVERT(DATETIME, '''+CONVERT(VARCHAR(32), @FECHA, 20)+''',20) AND @YASINCRONIZADO > 0)) AND IDPROSPECTO IN (SELECT IDPROSPECTO FROM '+@DB+'.dbo.PROSPECTOS_ASIGNADOS' 
SET @SQL =  @SQL + ' WHERE IDUSUARIO = '+ :IDUSUARIO + '  ) '
SET @SQL =  @SQL + ' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+ CONVERT(VARCHAR(32), @FECHA, 20) +''',20)  '
--SET @SQL =   ' SELECT  CONVERT(DATETIME,'''+ CONVERT(VARCHAR(32), @FECHA, 20) +''',20)'

--SELECT REVERSE(LEFT(REVERSE(@SQL), 250))
EXEC (@SQL)
--select (@SQL)