//[bd|Text,idprospecto|Integer,idetiqueta|Integer,fechaetiquetado|Text,]
--select

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDPROSPECTO INT
DECLARE @IDETIQUETA INT
DECLARE @FECHAETIQUETADO VARCHAR(1000)


SET @BD = ISNULL(:BD,'')
SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,0) AS INT)
SET @IDETIQUETA = ISNULL(:IDETIQUETA,0)
SET @FECHAETIQUETADO=ISNULL(:FECHAETIQUETADO,'')


IF(@IDPROSPECTO > 0)
BEGIN
	 SET @EXECSQL = 'insert INTO '+@BD+'.dbo.PROSPECTOS_ETIQUETAS WITH (ROWLOCK) (idprospecto, idetiqueta, fechaetiquetado) values ('+CAST(@IDPROSPECTO AS VARCHAR(1000))+', '+CAST(@IDETIQUETA AS VARCHAR(1000))+',CONVERT(DATETIME,'''+@FECHAETIQUETADO+''', 20)) '
	 SET @EXECSQL = @EXECSQL +'	 UPDATE '+@BD+'.dbo.PROSPECTOS_ETIQUETAS SET FECHAETIQUETADO = GETDATE() WHERE  IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(1000))+' AND FECHAETIQUETADO > GETDATE() ' 
	 SET @EXECSQL = @EXECSQL +'  DECLARE @IDEMPRESA INT  SELECT @IDEMPRESA = IDEMPRESA FROM '+@BD+'.dbo.PROSPECTOS WHERE IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(1000))
	 SET @EXECSQL = @EXECSQL +'  EXEC  '+@BD+'.DBO.SP_ENVIA_AUTORESPONDER_ESPECIFICO @IDEMPRESA, '+CAST(@IDPROSPECTO AS VARCHAR(1000))+',   '+CAST(@IDETIQUETA AS VARCHAR(1000))+' '
	 SET @EXECSQL = @EXECSQL + ' DELETE FROM '+@BD+'.dbo.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA   AND IDTABLA = 6 '
	 SET @EXECSQL = @EXECSQL + ' INSERT INTO '+@BD+'.dbo.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA ,6,GETDATE()) '
	 SET @EXECSQL = @EXECSQL + ' SELECT 1 AS RESPUESTA, ''INSERTADO CON EXITO'' AS MENSAJE ,'''+@BD+''' AS BD,  '+CAST(@IDPROSPECTO AS VARCHAR(1000))+' AS IDPROSPECTO,  '+CAST(@IDETIQUETA AS VARCHAR(1000))+' AS IDETIQUETA, '''+@FECHAETIQUETADO+''' AS FECHAETIQUETADO'
END
ELSE
BEGIN
	 SET @EXECSQL = @EXECSQL + ' SELECT 1 AS RESPUESTA, ''INSERTADO CON EXITO'' AS MENSAJE ,'''+@BD+''' AS BD,  '+CAST(@IDPROSPECTO AS VARCHAR(1000))+' AS IDPROSPECTO,  '+CAST(@IDETIQUETA AS VARCHAR(1000))+' AS IDETIQUETA, '''+@FECHAETIQUETADO+''' AS FECHAETIQUETADO'
END

EXEC(@EXECSQL)