//[base|Text,datos|Text,sessionid|Integer,]
-- SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @BASE VARCHAR(MAX)
DECLARE @SESSIONID INT
SET @SESSIONID = ISNULL(:SESSIONID,0)
SET @BASE=ISNULL(:BASE,'')
SET @SQL='
DECLARE @DATOSJSON VARCHAR(MAX)
DECLARE @SESSIONID INT
DECLARE @ESTADOANTERIOR VARCHAR(MAX), @ESTADO VARCHAR(MAX)

SET @DATOSJSON = '''+ISNULL(:DATOS,'')+'''
SET @SESSIONID = CAST('+CAST(@SESSIONID AS VARCHAR(1000))+' AS INT)

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDTAREA INT,IDTAREA_LOCAL INT, IDINICIADOR INT, IDREALIZADOR VARCHAR(10), IDESTADO INT,FECHA_VENCIMIENTO VARCHAR(MAX), FECHA_CREACION VARCHAR(MAX), TITULO VARCHAR(2000),IDPROSPECTO_LOCAL INT, IDOPORTUNIDAD_LOCAL INT,IDPROSPECTO INT, IDOPORTUNIDAD INT,IDPETICION VARCHAR(50),MASTIEMPO INT,FECHA_PROPUESTA VARCHAR(64))
DECLARE @TO INT, @TOTAL INT, @CONTEO INT
DECLARE @IDESTADOANTERIOR INT

DECLARE @IDTAREA INT
DECLARE @IDTAREA_LOCAL INT
DECLARE @IDINICIADOR INT
DECLARE @MASTIEMPO INT
DECLARE @IDREALIZADOR VARCHAR(10)
DECLARE @IDESTADO INT
DECLARE @FECHA_VENCIMIENTO VARCHAR(MAX)
DECLARE @FECHA_CREACION VARCHAR(MAX)
DECLARE @FECHA_PROPUESTA VARCHAR(MAX)
DECLARE @TITULO VARCHAR(2000)
DECLARE @IDPROSPECTO_LOCAL INT
DECLARE @IDOPORTUNIDAD_LOCAL INT
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDEMPRESA INT
DECLARE @TKP VARCHAR(2000)
DECLARE @TKOPORTUNIDAD VARCHAR(2000)
DECLARE @IDPETICION VARCHAR(50)
DECLARE @IDREALIZADORANTERIOR INT
DECLARE @TIPOSUCESO INT
DECLARE @REALIZADORANTERIOR VARCHAR(100)
DECLARE @NUEVOREALIZADOR VARCHAR(100)
DECLARE @COMENTARIOSISTEMA VARCHAR(100)

SELECT @IDEMPRESA = IDEMPRESA FROM '+@BASE+'.DBO.USUARIOS WITH (NOLOCK) WHERE IDUSUARIO = @SESSIONID

INSERT INTO @TABLATEMP (IDTAREA,IDTAREA_LOCAL, IDINICIADOR, IDREALIZADOR, IDESTADO,FECHA_VENCIMIENTO, FECHA_CREACION, TITULO,IDPROSPECTO_LOCAL, IDOPORTUNIDAD_LOCAL,IDPROSPECTO, IDOPORTUNIDAD,IDPETICION,MASTIEMPO,FECHA_PROPUESTA)
Select 
       max(case when NAME=''IDTAREA'' then STRINGVALUE else '''' end) as IDTAREA,
	   max(case when NAME=''IDTAREA_LOCAL'' then STRINGVALUE else '''' end) as IDTAREA_LOCAL,
	   max(case when NAME=''IDINICIADOR'' then STRINGVALUE else '''' end) as IDINICIADOR,
       max(case when NAME=''IDREALIZADOR'' then STRINGVALUE else '''' end) as IDREALIZADOR,
       max(case when NAME=''IDESTADO'' then STRINGVALUE else '''' end) as IDESTADO,
       max(case when NAME=''FECHA_VENCIMIENTO'' then STRINGVALUE else '''' end) as FECHA_VENCIMIENTO,
	   max(case when NAME=''FECHA_CREACION'' then STRINGVALUE else '''' end) as FECHA_CREACION,
	   max(case when NAME=''TITULO'' then STRINGVALUE else '''' end) as TITULO,
	   max(case when NAME=''IDPROSPECTO_LOCAL'' then STRINGVALUE else '''' end) as IDPROSPECTO_LOCAL,
	   max(case when NAME=''IDOPORTUNIDAD_LOCAL'' then STRINGVALUE else '''' end) as IDOPORTUNIDAD_LOCAL,
	   max(case when NAME=''IDPROSPECTO'' then STRINGVALUE else '''' end) as IDPROSPECTO,
	   max(case when NAME=''IDOPORTUNIDAD'' then STRINGVALUE else '''' end) as IDOPORTUNIDAD,
	   max(case when NAME=''IDPETICION'' then STRINGVALUE else '''' end) as IDPETICION,
	   max(case when NAME=''MASTIEMPO'' then STRINGVALUE else '''' end) as MASTIEMPO,
	   max(case when NAME=''FECHA_PROPUESTA'' then STRINGVALUE else '''' end) as FECHA_PROPUESTA
from SALESUP_CT.dbo.parseJSON(@DATOSJSON)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDTAREA = IDTAREA,@IDTAREA_LOCAL = IDTAREA_LOCAL,@IDINICIADOR = IDINICIADOR,@IDREALIZADOR = IDREALIZADOR,@IDESTADO = IDESTADO,@FECHA_VENCIMIENTO = FECHA_VENCIMIENTO,@FECHA_CREACION = FECHA_CREACION,@TITULO = TITULO,@IDPROSPECTO_LOCAL = IDPROSPECTO_LOCAL,@IDOPORTUNIDAD_LOCAL = IDOPORTUNIDAD_LOCAL,@IDPROSPECTO = IDPROSPECTO,@IDPETICION = IDPETICION,@IDOPORTUNIDAD = IDOPORTUNIDAD,@MASTIEMPO = MASTIEMPO,@FECHA_PROPUESTA = FECHA_PROPUESTA FROM @TABLATEMP WHERE ID = @TO
	
	IF(@FECHA_PROPUESTA = '''' OR @FECHA_PROPUESTA = ''null'')
		 	SET @FECHA_PROPUESTA = NULL
	
	SELECT @TKP = TKP FROM '+@BASE+'.DBO.PROSPECTOS WITH (NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
	SELECT @TKOPORTUNIDAD = TKO FROM '+@BASE+'.DBO.OPORTUNIDADES WITH (NOLOCK) WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
	
	IF(@IDTAREA = 0)
	BEGIN
		 EXEC '+@BASE+'.dbo.SP_NUEVA_TAREA @SESSIONID, @IDEMPRESA, 120, @IDREALIZADOR, '''', @TITULO, '''', @FECHA_VENCIMIENTO, @TKP, '''', '''', '''', '''', '''', '''', '''', @IDPETICION, @TKOPORTUNIDAD,1, @FECHA_CREACION,NULL
	
		 SELECT @IDTAREA = IDTAREA FROM '+@BASE+'.DBO.TAREAS WITH (NOLOCK) WHERE IDINICIADOR = @SESSIONID AND TITULO = @TITULO AND FECHA_CREACION = @FECHA_CREACION AND IDPETICION = @IDPETICION
		 UPDATE @TABLATEMP SET IDTAREA = @IDTAREA WHERE ID = @TO AND IDTAREA_LOCAL = @IDTAREA_LOCAL
	END
	ELSE
	BEGIN
		
		 SELECT @IDREALIZADORANTERIOR = IDREALIZADOR, @IDESTADOANTERIOR = IDESTADO FROM '+@BASE+'.DBO.TAREAS WITH (NOLOCK) WHERE IDTAREA = @IDTAREA
		 
		 IF(@IDREALIZADORANTERIOR <> CAST(@IDREALIZADOR AS INT))
		 BEGIN
		 	  SELECT @REALIZADORANTERIOR = NOMBRE + '' '' + ISNULL(APELLIDOS,'''') FROM '+@BASE+'.dbo.USUARIOS WITH (NOLOCK) WHERE IDUSUARIO = @IDREALIZADORANTERIOR
		 	  SELECT @NUEVOREALIZADOR = NOMBRE + '' '' + ISNULL(APELLIDOS,'''') FROM '+@BASE+'.dbo.USUARIOS WITH (NOLOCK) WHERE IDUSUARIO = CAST(@IDREALIZADOR AS INT)
	
		 	  SET @COMENTARIOSISTEMA = ''La tarea ha sido reasignada a ''+@NUEVOREALIZADOR+'', responsable anterior (''+@REALIZADORANTERIOR+'')''
			  
			  SET @TIPOSUCESO = 32
			  EXEC '+@BASE+'.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @SESSIONID, @TIPOSUCESO, @IDPROSPECTO, 120, @COMENTARIOSISTEMA, @IDTAREA
		 END 
		 
		 IF(@IDESTADOANTERIOR <> CAST(@IDESTADO AS INT))
		 BEGIN
		 	  SELECT @ESTADO = ESTADO, @TIPOSUCESO = IDSUCESO FROM SALESUP_CT.dbo.V_TAREAS_ESTADOS WHERE IDESTADO = @IDESTADO 
			  SELECT @ESTADOANTERIOR = ESTADO FROM SALESUP_CT.dbo.V_TAREAS_ESTADOS WHERE IDESTADO = @IDESTADOANTERIOR 
	
		 	  SET @COMENTARIOSISTEMA = ''Se ha cambiado el estado de ''+@ESTADOANTERIOR+'' a ''+@ESTADO

			  EXEC '+@BASE+'.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @SESSIONID, @TIPOSUCESO, @IDPROSPECTO, 120, @COMENTARIOSISTEMA, @IDTAREA
		 END 
		 
		 UPDATE '+@BASE+'.dbo.TAREAS  WITH (ROWLOCK)
		 SET MASTIEMPO = @MASTIEMPO, FECHA_VENCIMIENTO = @FECHA_VENCIMIENTO, TITULO = @TITULO, IDREALIZADOR = CAST(@IDREALIZADOR AS INT), IDESTADO = @IDESTADO ,FECHA_PROPUESTA = CONVERT(DATETIME,@FECHA_PROPUESTA,120)
		 WHERE IDTAREA = @IDTAREA
	END
	
	SET @TO = @TO+1
END

SELECT * FROM @TABLATEMP
'
EXEC (@SQL)