//[datos|Text,base|Text,]
-- SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @BASE VARCHAR(MAX)
SET @BASE=ISNULL(:BASE,'')
SET @SQL ='

DECLARE @DATOSJSON VARCHAR(MAX)
DECLARE @SESSIONID INT

SET @DATOSJSON = '''+isnull(:DATOS,'')+'''

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDCITAINVITADO_LOCAL INT,IDCITAINVITADO INT,IDCITA_LOCAL INT, IDCITA INT, IDPERSONA INT, PERSONA VARCHAR(MAX), TIPOPERSONA INT)

DECLARE @TO INT, @TOTAL INT, @CONTEO INT

DECLARE @IDCITAINVITADO_LOCAL INT
DECLARE @IDCITAINVITADO INT
DECLARE @IDCITA_LOCAL INT
DECLARE @IDCITA INT
DECLARE @IDPERSONA INT
DECLARE @PERSONA VARCHAR(MAX)
DECLARE @TIPOPERSONA INT

DECLARE @IDCITA_ANTERIOR INT
SET @IDCITA_ANTERIOR = 0


INSERT INTO @TABLATEMP (IDCITAINVITADO_LOCAL,IDCITAINVITADO,IDCITA_LOCAL, IDCITA, IDPERSONA, PERSONA, TIPOPERSONA)
Select 
       max(case when NAME=''IDCITAINVITADO_LOCAL'' then STRINGVALUE else '''' end) as IDCITAINVITADO_LOCAL,
	   max(case when NAME=''IDCITAINVITADO'' then STRINGVALUE else '''' end) as IDCITAINVITADO,
	   max(case when NAME=''IDCITA_LOCAL'' then STRINGVALUE else '''' end) as IDCITA_LOCAL,
       max(case when NAME=''IDCITA'' then STRINGVALUE else '''' end) as IDCITA,
       max(case when NAME=''IDPERSONA'' then STRINGVALUE else '''' end) as IDPERSONA,
       max(case when NAME=''PERSONA'' then STRINGVALUE else '''' end) as PERSONA,
	   max(case when NAME=''TIPOPERSONA'' then STRINGVALUE else '''' end) as TIPOPERSONA
from SALESUP_CT.dbo.parseJSON(@DATOSJSON)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	 SELECT @IDCITAINVITADO_LOCAL = IDCITAINVITADO_LOCAL,@IDCITAINVITADO = IDCITAINVITADO,@IDCITA_LOCAL = IDCITA_LOCAL, @IDCITA = IDCITA, @IDPERSONA = IDPERSONA, @PERSONA = PERSONA, @TIPOPERSONA = TIPOPERSONA FROM @TABLATEMP WHERE ID = @TO
	 
	 IF(@IDCITA_ANTERIOR <> @IDCITA)
	 BEGIN
	 	DELETE FROM '+@BASE+'.DBO.CITAS_INVITADOS WHERE IDCITA=@IDCITA
	 	SET @IDCITA_ANTERIOR = @IDCITA
	 END
	 
	INSERT INTO '+@BASE+'.DBO.CITAS_INVITADOS (IDCITA,IDPERSONA,PERSONA,TIPOPERSONA) VALUES(@IDCITA,@IDPERSONA,@PERSONA,@TIPOPERSONA)
	
	SELECT @IDCITAINVITADO = IDCITAINVITADO FROM '+@BASE+'.DBO.CITAS_INVITADOS WHERE IDCITA = @IDCITA AND IDPERSONA = @IDPERSONA AND PERSONA = @PERSONA AND TIPOPERSONA = @TIPOPERSONA
	
	UPDATE @TABLATEMP SET IDCITAINVITADO = @IDCITAINVITADO WHERE IDCITAINVITADO_LOCAL = @IDCITAINVITADO_LOCAL
	
	SET @TO = @TO+1
END

SELECT * FROM @TABLATEMP
'
EXEC (@SQL)