//[idusuario|Integer,idempresa|Integer,bd|Text,fecha|Text,]
-- SELECT 
DECLARE @BD VARCHAR(1000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @SQL VARCHAR(MAX)
DECLARE @FECHA VARCHAR(1000)
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))
SET @IDEMPRESA = CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @BD= ISNULL(:BD,'')
SET @FECHA = ISNULL(:FECHA,'')

SET @SQL = '
SELECT *,'+@IDUSUARIO+' AS IDUSUARIO, '+@IDEMPRESA+' AS IDEMPRESA  FROM '+@BD+'.dbo.CITAS_INVITADOS WITH (NOLOCK) WHERE IDCITA IN  (
SELECT C.IDCITA FROM '+@BD+'.dbo.CITAS C WITH (NOLOCK),
 '+@BD+'.dbo.CITAS_INVITADOS CI WITH (NOLOCK)
  WHERE C.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA +''',20) AND C.IDCITA = CI.IDCITA AND C.IDEMPRESA = '+@IDEMPRESA+' AND 
   (C.IDUSUARIO_CREACION = '+@IDUSUARIO+' OR CI.idpersona = '+@IDUSUARIO+')
 GROUP BY C.IDCITA)
'
EXEC (@SQL)