//[bd|Text,idempresa|Integer,]
-- select
/*protegido*/
DECLARE @BD VARCHAR(512)
DECLARE @IDEMPRESA VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

SET @BD = isnull(:BD,'')
SET @IDEMPRESA=ISNULL(:IDEMPRESA,0)

SET @EXECSQL = 'SELECT * FROM '+@BD+'.dbo.SEGUIMIENTO_CATEGORIAS WITH (NOLOCK) WHERE IDEMPRESA = CAST('''+CAST(@IDEMPRESA AS VARCHAR(1000))+''' AS INT)'
EXEC(@EXECSQL)