//[bd|Text,idoportunidad|Text,monto|Text,comision|Text,fechahora|Text,referencia|Text,anticipos_monto|Text,anticipos_comision|Text,saldo_monto|Text,saldo_comision|Text,noparcialidades|Text,idusuario|Text,periodicidad|Text,idventa|Text,]
--select

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

DECLARE @IDOPORTUNIDAD INT
DECLARE @MONTO MONEY
DECLARE @COMISION MONEY
DECLARE @FECHAHORA VARCHAR(512)
DECLARE @REFERENCIA VARCHAR(64)
DECLARE @ANTICIPOS_MONTO MONEY
DECLARE @ANTICIPOS_COMISION MONEY
DECLARE @SALDO_MONTO MONEY
DECLARE @SALDO_COMISION MONEY
DECLARE @NOPARCIALIDADES INT
DECLARE @IDUSUARIO INT
DECLARE @PERIODICIDAD INT
DECLARE @IDVENTA INT

SET @BD = :BD

IF(:IDOPORTUNIDAD ='null')
	SET @IDOPORTUNIDAD = 0
ELSE
	SET @IDOPORTUNIDAD = CAST(:IDOPORTUNIDAD AS INT)

SET @MONTO = CAST(:MONTO AS MONEY)
SET @COMISION = CAST(:COMISION AS MONEY)

IF ((:FECHAHORA != '')AND(:FECHAHORA IS NOT NULL))
   SET @FECHAHORA = CONVERT(DATETIME,:FECHAHORA,20)
ELSE
	SET @FECHAHORA = ''

SET @REFERENCIA = ISNULL(REPLACE(:REFERENCIA,'''',''''''),'')
SET @ANTICIPOS_MONTO =CAST(:ANTICIPOS_MONTO AS MONEY)
SET @ANTICIPOS_COMISION =CAST(:ANTICIPOS_COMISION AS MONEY)
SET @SALDO_MONTO =CAST(:SALDO_MONTO AS MONEY)
SET @SALDO_COMISION =CAST(:SALDO_COMISION AS MONEY)
SET @NOPARCIALIDADES =CAST(:NOPARCIALIDADES AS INT)
SET @IDUSUARIO =CAST(:IDUSUARIO AS INT)
SET @PERIODICIDAD =CAST(:PERIODICIDAD AS INT)
SET @IDVENTA =CAST( ISNULL( :IDVENTA,0 ) AS INT)

SET @EXECSQL = 'EXEC '+@BD+'.DBO.SP_INSERTA_VENTA_MV '
SET @EXECSQL = @EXECSQL + CAST(@IDOPORTUNIDAD AS VARCHAR(12))+','+CAST(@MONTO AS VARCHAR(12))+','+CAST(@COMISION AS VARCHAR(12))+','''+@FECHAHORA+''','''+@REFERENCIA+''','+CAST(@ANTICIPOS_MONTO AS VARCHAR(12))+','+CAST(@ANTICIPOS_COMISION AS VARCHAR(12))+', '
SET @EXECSQL = @EXECSQL + CAST(@SALDO_MONTO AS VARCHAR(12))+','+CAST(@SALDO_COMISION AS VARCHAR(12))+','+CAST(@NOPARCIALIDADES AS VARCHAR(12))+','+CAST(@IDUSUARIO AS VARCHAR(12))+','+CAST(@PERIODICIDAD AS VARCHAR(12))+','+CAST(@IDVENTA AS VARCHAR(12))

EXEC(@EXECSQL)