//[bd|Text,idusuario|Integer,fecha|Text,]
--SELECT

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDUSUARIO VARCHAR(8000)
DECLARE @FECHA VARCHAR(1000)
SET @BD = isnulL(:BD,'')
SET @IDUSUARIO=ISNULL(:IDUSUARIO,0)
SET @FECHA =  ISNULL(:FECHA,'')

SET @EXECSQL = 'select CONVERT(VARCHAR,V.FECHAHORA,20) AS FECHAHORA, NOPARCIALIDADES = CASE WHEN V.NOPARCIALIDADES > 12 THEN 12 ELSE V.NOPARCIALIDADES END, V.* from '+@BD+'.dbo.ventas V WITH (NOLOCK), '+@BD+'.dbo.OPORTUNIDADES O, '+@BD+'.dbo.PROSPECTOS_ASIGNADOS PA '
SET @EXECSQL = @EXECSQL + 'where V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND PA.IDPROSPECTO = O.IDPROSPECTO AND PA.idusuario = '+CAST(@IDUSUARIO AS VARCHAR(1000))+' AND V.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)'
EXEC(@EXECSQL) 
