//[datos|Text,sessionid|Integer,base|Text,]
-- SELECT 

DECLARE @SQL VARCHAR(MAX)
DECLARE @BASE VARCHAR(MAX)
SET @BASE=ISNULL(:BASE,'')

SET @SQL='
DECLARE @DATOSJSON VARCHAR(MAX)
DECLARE @SESSIONID INT

SET @DATOSJSON = '''+ISNULL(:DATOS,'')+'''
SET @SESSIONID = '+CAST(ISNULL(:SESSIONID, 0) AS VARCHAR(1000))+'

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDTAREASEGUIMIENTO_LOCAL INT,IDUSUARIO INT, FECHAHORA DATETIME, COMENTARIO VARCHAR(MAX),IDTAREA_LOCAL INT, IDTAREA INT,IDTAREASEGUIMIENTO INT,LATITUDE VARCHAR(MAX),LONGITUDE VARCHAR(MAX))
DECLARE @TO INT, @TOTAL INT, @CONTEO INT

DECLARE @IDTAREASEGUIMIENTO_LOCAL INT
DECLARE @IDUSUARIO INT
DECLARE @FECHAHORA DATETIME
DECLARE @COMENTARIO VARCHAR(MAX)
DECLARE @IDTAREA_LOCAL INT
DECLARE @IDTAREA INT
DECLARE @IDTAREASEGUIMIENTO INT
DECLARE @LATITUDE VARCHAR(MAX)
DECLARE @LONGITUDE VARCHAR(MAX)

INSERT INTO @TABLATEMP (IDTAREASEGUIMIENTO_LOCAL,IDUSUARIO, FECHAHORA, COMENTARIO,IDTAREA_LOCAL, IDTAREA,IDTAREASEGUIMIENTO,LATITUDE,LONGITUDE)
Select 
       max(case when NAME=''IDTAREASEGUIMIENTO_LOCAL'' then STRINGVALUE else '''' end) as IDTAREASEGUIMIENTO_LOCAL,
	   max(case when NAME=''IDUSUARIO'' then STRINGVALUE else '''' end) as IDUSUARIO,
	   max(case when NAME=''FECHAHORA'' then STRINGVALUE else '''' end) as FECHAHORA,
       max(case when NAME=''COMENTARIO'' then STRINGVALUE else '''' end) as COMENTARIO,
       max(case when NAME=''IDTAREA_LOCAL'' then STRINGVALUE else '''' end) as IDTAREA_LOCAL,
       max(case when NAME=''IDTAREA'' then (CASE WHEN STRINGVALUE= ''NULL'' THEN '''' ELSE stringvalue END) else '''' end) as IDTAREA,
	   max(case when NAME=''IDTAREASEGUIMIENTO'' then STRINGVALUE else '''' end) as IDTAREASEGUIMIENTO,
	   max(case when NAME=''LATITUDE'' then STRINGVALUE else '''' end) as LATITUDE,
	   max(case when NAME=''LONGITUDE'' then STRINGVALUE else '''' end) as LONGITUDE
from SALESUP_CT.dbo.parseJSON(@DATOSJSON)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDTAREASEGUIMIENTO_LOCAL = IDTAREASEGUIMIENTO_LOCAL,@IDUSUARIO = IDUSUARIO, @FECHAHORA = FECHAHORA, @COMENTARIO = COMENTARIO,
	@IDTAREA_LOCAL = IDTAREA_LOCAL, @IDTAREA = IDTAREA, @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO,@LATITUDE = LATITUDE,@LONGITUDE = LONGITUDE FROM @TABLATEMP WHERE ID = @TO
	
	INSERT INTO '+@BASE+'.dbo.TAREAS_SEGUIMIENTO WITH (ROWLOCK) (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA, LATITUDE,LONGITUDE)
	VALUES (@SESSIONID, @FECHAHORA, @COMENTARIO, @IDTAREA,@LATITUDE,@LONGITUDE)
	
	SELECT TOP 1 @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO 
	FROM '+@BASE+'.dbo.TAREAS_SEGUIMIENTO WITH (NOLOCK)
	WHERE IDTAREA = @IDTAREA ORDER BY 1 DESC
	
	UPDATE '+@BASE+'.dbo.TAREAS WITH (ROWLOCK) SET IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO WHERE IDTAREA = @IDTAREA
	
	UPDATE @TABLATEMP SET IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO WHERE ID = @TO AND IDTAREASEGUIMIENTO_LOCAL = @IDTAREASEGUIMIENTO_LOCAL
	
	SET @TO = @TO+1
END

SELECT *,'''+ISNULL(:DATOS,'')+''' AS DATOS, @SESSIONID AS SESSIONID FROM @TABLATEMP
'
EXEC (@SQL)