//[bd|Text,idventa|Integer,noparcialidad|Integer,fechahora|Text,monto|Numeric,comision|Numeric,pagado|Integer,]
--SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(512)
DECLARE @IDVENTA VARCHAR(1000) 
DECLARE @NOPARCIALIDAD VARCHAR(1000)
DECLARE @FECHAHORA VARCHAR(1000)
DECLARE @MONTO VARCHAR(1000)
DECLARE @COMISION VARCHAR(1000)
DECLARE @PAGADO VARCHAR(1000)

SET @BD = ISNULL(:BD,'')
SET @IDVENTA = CAST(ISNULL(:IDVENTA,0) AS VARCHAR(1000))
SET @NOPARCIALIDAD=CAST(ISNULL(:NOPARCIALIDAD,0) AS VARCHAR(1000))
SET @FECHAHORA=ISNULL(:FECHAHORA,'')
SET @MONTO=CAST(ISNULL(:MONTO,0) AS VARCHAR(1000))
SET @COMISION=CAST(ISNULL(:COMISION,0) AS VARCHAR(1000))
SET @PAGADO=CAST(ISNULL(:PAGADO,0) AS VARCHAR(1000))

SET @SQL='

DECLARE @IDVENTACOBRO INT 

INSERT INTO '+@BD+'.dbo.VENTAS_COBROS WITH (ROWLOCK) 
(IDVENTA, NOPARCIALIDAD, FECHAHORA, MONTO, COMISION, PAGADO) 
VALUES 
(CAST('+@IDVENTA+' AS INT),CAST('+@NOPARCIALIDAD+' AS INT) , '+@BD+'.dbo.GETONLYDATE(CONVERT(DATETIME,'''+@FECHAHORA+''',20)), CAST('+@MONTO+' AS MONEY), CAST('+@COMISION+' AS MONEY), CAST('+@PAGADO+' AS MONEY)) 
	
SELECT TOP 1 @IDVENTACOBRO=IDVENTACOBRO FROM '+@BD+'.dbo.VENTAS_COBROS WITH (NOLOCK) WHERE IDVENTA = CAST('+@IDVENTA+' AS INT)  
ORDER BY IDVENTACOBRO DESC  

SELECT @IDVENTACOBRO AS IDVENTACOBRO, 1 AS RESPUESTA 
'
EXEC (@SQL)