//[bd|Text,idempresa|Text,fecha|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA=ISNULL(:FECHA,'')

SET @SQL='
SELECT ECO.IDOPCION,ECO.IDCAMPO,SALESUP_CT.DBO.PreparaCadenaApp2(ECO.OPCION) AS OPCION , '''+@FECHA+''' AS FECHA, '+@IDEMPRESA+' AS IDEMPRESA
FROM '+@BD+'.dbo.EMPRESAS_CAMPOS_OPCIONES ECO WITH (NOLOCK), '+@BD+'.dbo.EMPRESAS_CAMPOS EC WITH (NOLOCK) 
where EC.idempresa = '+@IDEMPRESA+' AND ECO.IDCAMPO = EC.IDCAMPO AND ECO.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)
'
EXEC (@SQL)