//[bd|Text,idtabla|Text,idelemento_eliminado|Text,idusuario|Text,idempresa|Text,idprospecto|Text,fecha|Text,]
--DELETE

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @FECHA VARCHAR(512)
DECLARE @IDTABLA INT, @IDELEMENTO_ELIMINADO INT, @IDUSUARIO INT, @IDEMPRESA INT, @IDPROSPECTO INT

SET @BD = ISNULL(:BD,'')
SET @IDTABLA = CAST(ISNULL(:IDTABLA,'') AS INT)
SET @IDELEMENTO_ELIMINADO = CAST(ISNULL(:IDELEMENTO_ELIMINADO,'') AS INT)
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,'') AS INT)
SET @IDEMPRESA = CAST(ISNULL(:IDEMPRESA,'') AS INT)
SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,'') AS INT)
SET @FECHA = CONVERT(VARCHAR(512),ISNULL(:FECHA,''),20)

IF(@IDTABLA=4)
BEGIN
	 SET @EXECSQL = 'EXEC '+@BD+'.dbo.SP_REASIGNAR_PROSPECTO_MV '+CAST(@IDELEMENTO_ELIMINADO AS VARCHAR(100))+', '+CAST(@IDUSUARIO AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'DELETE FROM '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'INSERT INTO '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES(4,'+CAST(@IDEMPRESA AS VARCHAR(100))+') '
	 EXEC(@EXECSQL)
END
ELSE IF(@IDTABLA=6 AND @IDPROSPECTO > 0)
BEGIN
	 SET @EXECSQL = 'DELETE FROM '+@BD+'.dbo.PROSPECTOS_ETIQUETAS WHERE IDETIQUETA = '+CAST(@IDELEMENTO_ELIMINADO AS VARCHAR(100))+' AND IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'INSERT INTO '+@BD+'.dbo.ELIMINACIONES (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES(6,'+CAST(@IDPROSPECTO AS VARCHAR(100))+','+CAST(@IDELEMENTO_ELIMINADO AS VARCHAR(100))+',1,'+CAST(@IDEMPRESA AS VARCHAR(100))+',GETDATE()) '
	 EXEC(@EXECSQL)
END
ELSE IF(@IDTABLA=16)
BEGIN
	 SET @EXECSQL = 'DECLARE @FECHAMETA DATETIME SELECT @FECHAMETA = FECHAHORA FROM '+@BD+'.DBO.VENTAS V WHERE V.IDVENTA='+CAST(@IDELEMENTO_ELIMINADO AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'EXEC '+@BD+'.dbo.SP_ELIMINAR_VENTA '+CAST(@IDELEMENTO_ELIMINADO AS VARCHAR(100))+', '+CAST(@IDUSUARIO AS VARCHAR(100))+', 103,1 '
	 SET @EXECSQL = @EXECSQL + 'EXEC '+@BD+'.DBO.SP_ACTUALIZA_METAS_PROCESO 3, '+CAST(@IDUSUARIO AS VARCHAR(100))+', @FECHAMETA '
	 SET @EXECSQL = @EXECSQL + 'DELETE FROM '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'DELETE FROM '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 15 AND IDUSUARIO ='+CAST(@IDUSUARIO AS VARCHAR(100))+' '
	 SET @EXECSQL = @EXECSQL + 'INSERT INTO '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES(4,'+CAST(@IDEMPRESA AS VARCHAR(100))+') '
	 SET @EXECSQL = @EXECSQL + 'INSERT INTO '+@BD+'.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDUSUARIO) VALUES(15,'+CAST(@IDUSUARIO AS VARCHAR(100))+') '
	 EXEC(@EXECSQL)
END