//[bd|Text,idusuario|Text,token|Text,]
-- SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @TOKEN VARCHAR(512)
	
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))	
SET @BD = CAST(ISNULL(:BD,'') AS VARCHAR(512))
SET @TOKEN = ISNULL(:TOKEN,'')

SET @SQL='
DECLARE @IDUSUARIO INT 
DECLARE @TOKEN VARCHAR(512) 
SET @IDUSUARIO = 0 
IF('''+@BD+'''<>'''') 
BEGIN 
	
	IF('''+@IDUSUARIO+''' <> ''null'') 
	BEGIN 
		 SET @IDUSUARIO = '+@IDUSUARIO+' 
	END 
	
	SET @TOKEN = '''+@TOKEN+''' 
	
	UPDATE '+@BD+'.dbo.USUARIOS_TOKENS WITH(ROWLOCK) SET NUM_NOTIFICACIONES = 0 WHERE IDUSUARIO = @IDUSUARIO  AND TOKEN_DEVICE LIKE ''%''+'''+@TOKEN+'''+''%'' 
	
	SELECT 1 AS RESPUESTA 
END 
ELSE 
BEGIN 
	 SELECT 1 AS RESPUESTA 
END 
' 
EXEC (@SQL)