//[fecha|Text,bd|Text,idempresa|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @FECHA VARCHAR(100)
DECLARE @BD VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
SET @FECHA = ISNULL(:FECHA,'')
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))

SET @SQL='
SELECT IDRAZONPERDIDA AS IDRAZONPERDIDA,IDEMPRESA AS IDEMPRESA,RAZONPERDIDA AS RAZONPERDIDA,TIPO AS TIPO, ULTIMAMODIFICACION AS ULTIMAMODIFICACION, TK, TKM, '''+@FECHA+''' AS FECHA
FROM '+@BD+'.DBO.EMPRESAS_RAZONES_PERDIDA WITH (NOLOCK) WHERE IDEMPRESA ='+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)
'
EXEC(@SQL)