//[bd|Text,idempresa|Text,]
-- select
DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDEMPRESA VARCHAR(1000)
SET @BD = ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))

SET @EXECSQL = 'SELECT IDFASE,IDEMPRESA, FASE, ISNULL(ORDEN,1) AS ORDEN,TK,TKM FROM '+@BD+'.dbo.OPORTUNIDADES_FASES WITH (NOLOCK) WHERE IDEMPRESA = '+@IDEMPRESA
EXEC(@EXECSQL)