//[bd|Text,idempresa|Integer,fecha|Text,]
--select

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @FECHA VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)

SET @BD = ISNULL(:BD,'')
SET @FECHA = ISNULL(:FECHA,'')
SET @IDEMPRESA = CAST( ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))

SET @EXECSQL = 'SELECT COUNT(*) AS TOTAL, '+@IDEMPRESA+' AS IDEMPRESA, '''+@FECHA+''' AS FECHA FROM '+@BD+'.dbo.USUARIOS_SUCESOS WITH (NOLOCK) WHERE IDUSUARIO IN (SELECT IDUSUARIO FROM '+@BD+'.dbo.USUARIOS WHERE IDEMPRESA = '+@IDEMPRESA+') AND ((FECHAHORA between DATEADD(day, -1, getdate()) AND GETDATE())'
SET @EXECSQL = @EXECSQL+ 'AND (ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)))'
EXEC(@EXECSQL)
