//[bd|Text,campo|Text,valor|Text,tipovalidacion|Text,idempresa|Integer,]
-- select
/*PROTEGIDO */

DECLARE @BD VARCHAR(512)
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @VALOR VARCHAR(MAX)
DECLARE @TIPOVALIDACION VARCHAR(252)
DECLARE @IDEMPRESA INT 

SET @BD =:BD 
SELECT @BD=CASE WHEN @BD='undefined' THEN '' when @BD='UNDEF' THEN '' WHEN @BD='null' THEN '' ELSE ISNULL(@BD, '') END
 

SET @CAMPO = :CAMPO
SET @VALOR = :VALOR 

IF(@CAMPO ='NOEMPLEADOS') 
BEGIN
	 SET @VALOR =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL(@VALOR, 0),0)  
	 SELECT @VALOR= CASE WHEN @VALOR ='undefined' THEN '' WHEN @VALOR='UNDEF' THEN '' WHEN @VALOR='null' THEN '' WHEN @VALOR='.' THEN '' ELSE ISNULL(CAST(@VALOR AS VARCHAR(4)), 0) END
END 
ELSE 
BEGIN 
SELECT @VALOR= CASE WHEN @VALOR ='UNDEFINED' THEN '' WHEN @VALOR='UNDEF' THEN '' WHEN @VALOR='NULL' THEN ''WHEN @VALOR='.' THEN '' ELSE ISNULL(@VALOR , '') END
END 

SET @TIPOVALIDACION = ISNULL(:TIPOVALIDACION, '')  
SET @IDEMPRESA= ISNULL(:IDEMPRESA, 0) 
IF(@BD!='') 
 BEGIN 
  IF(@TIPOVALIDACION != '')
BEGIN
  IF(@TIPOVALIDACION = 'prospecto')
  BEGIN	
	 SET @EXECSQL = 'SELECT COUNT(*) AS TOTAL FROM '+@BD+'.dbo.PROSPECTOS WHERE IDEMPRESA ='+CAST(@IDEMPRESA AS VARCHAR(100))+' AND cast('+@CAMPO+' as varchar(max))='''+@valor+''''
  END
 ELSE
  BEGIN
  	 
  	  SET @EXECSQL = 'SELECT COUNT(*) AS TOTAL FROM '+@BD+'.dbo.OPORTUNIDADES O, '+@BD+'.dbo.PROSPECTOS P WHERE O.IDPROSPECTO = P.IDPROSPECTO AND P.IDEMPRESA ='
	  	  		   + CAST(@IDEMPRESA AS VARCHAR(100))+' AND cast(O.' + @CAMPO + ' as varchar(max)) like'''+@valor+''''
  END
END
ELSE
 SET @EXECSQL = 'SELECT 0 AS TOTAL '
 END 
ELSE 
BEGIN 
	  SET @EXECSQL = 'SELECT 0 AS TOTAL '   
 END
 
 
  EXEC (@EXECSQL)






