//[bd|Text,recordatorio|Text,fechahora|Text,idrecordatorio|Text,idprospecto|Text,idoportunidad|Text,idusuario|Text,completado|Text,enviado|Text,min_previos|Text,avisado|Text,]
--SELECT

DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)


DECLARE @DB VARCHAR(512)
SET @DB =  :BD

SET @SQL = '
DECLARE @IDRECORDATORIO INT
DECLARE @IDPROSPECTO INT 
DECLARE @IDOPORTUNIDAD INT 
DECLARE @FECHAHORA DATETIME
DECLARE @FECHAHORARECORDATORIO DATETIME
DECLARE @RECORDATORIO VARCHAR(2000)
SET @RECORDATORIO = CAST(' + @DB +'.dbo.PreparaCadena(''' + ISNULL(:RECORDATORIO, '') + ''') AS VARCHAR(2000))

IF(isDate(''' + ISNULL(:FECHAHORA, '') + ''') = 1)
BEGIN
	 SET @FECHAHORARECORDATORIO = CONVERT(DATETIME,''' + ISNULL(:FECHAHORA, '') +''',120)
END
ELSE
BEGIN
	 SET @FECHAHORARECORDATORIO = GETDATE()
END

 SET @IDRECORDATORIO = CAST(''' + ISNULL(:IDRECORDATORIO, 0) + ''' AS INT) 

 IF(''' +  ISNULL(:IDPROSPECTO, '') + '''!='''') 
	 SET @IDPROSPECTO = CAST(''' +  ISNULL(:IDPROSPECTO, 0) +''' AS INT) 

 IF(''' +  ISNULL(:IDOPORTUNIDAD,'') + ''' != '''') 
	 SET @IDOPORTUNIDAD = CAST(''' +  ISNULL(:IDOPORTUNIDAD, 0) + ''' AS INT) 

 IF @IDRECORDATORIO = 0 
 BEGIN 
 INSERT INTO ' + @DB +'.dbo.RECORDATORIOS WITH (ROWLOCK)
	 (IDUSUARIO, IDPROSPECTO, IDOPORTUNIDAD, FECHAHORA, RECORDATORIO, COMPLETADO, ENVIADO, MIN_PREVIOS, AVISADO)
 VALUES 
	 (CAST(''' +  ISNULL(:IDUSUARIO, 0) + ''' AS INT), @IDPROSPECTO,@IDOPORTUNIDAD,@FECHAHORARECORDATORIO,@RECORDATORIO,CAST(''' + ISNULL(:COMPLETADO, 0) +''' AS INT),CAST(''' + ISNULL(:ENVIADO, 0) +''' AS INT),CAST(''' + ISNULL(:MIN_PREVIOS, 0) +''' AS INT),CAST(''' + ISNULL(:AVISADO, 0) +''' AS INT)) 
	
 SELECT TOP 1 @IDRECORDATORIO=IDRECORDATORIO, @FECHAHORA = FECHAHORA FROM ' + @DB +'.dbo.RECORDATORIOS WITH (NOLOCK) WHERE RECORDATORIO = @RECORDATORIO  AND IDUSUARIO = CAST(''' + ISNULL(:IDUSUARIO,0) +''' AS INT) ORDER BY 1 DESC 

 SELECT @IDRECORDATORIO AS IDRECORDATORIO, @FECHAHORA AS FECHA 
 END 
 ELSE 
 BEGIN 
 UPDATE ' + @DB +'.dbo.RECORDATORIOS WITH(ROWLOCK) SET FECHAHORA = @FECHAHORARECORDATORIO, RECORDATORIO = @RECORDATORIO,COMPLETADO = CAST(''' + ISNULL(:COMPLETADO, 0) +''' AS INT) WHERE IDRECORDATORIO = @IDRECORDATORIO  AND IDPROSPECTO = @IDPROSPECTO 
 SELECT @FECHAHORA AS FECHA FROM ' + @DB +'.dbo.RECORDATORIOS WITH (NOLOCK) WHERE IDRECORDATORIO = @IDRECORDATORIO  AND IDPROSPECTO = @IDPROSPECTO 
 DELETE FROM ' + @DB +'.dbo.MODIFICACIONES WITH(ROWLOCK) WHERE IDUSUARIO = CAST(''' + ISNULL(:IDUSUARIO, 0) +''' AS INT) AND IDTABLA = 18 
 INSERT INTO ' + @DB +'.dbo.MODIFICACIONES WITH(ROWLOCK) (IDUSUARIO, IDTABLA,FECHAHORA) VALUES(CAST(''' + ISNULL(:IDUSUARIO, 0) +''' AS INT),18,GETDATE()) 

 SELECT @IDRECORDATORIO AS IDRECORDATORIO, @FECHAHORA AS FECHA
 END 
'
 
EXEC (@SQL)