//[bd|Text,idcompania|Text,idempresa|Text,idindustria|Text,idcompaniagrupo|Text,empresa|Text,url|Text,telefonocorporativo|Text,direccion1|Text,direccion2|Text,ciudad|Text,codigopostal|Text,idestado|Text,idpais|Text,nempleados|Text,idcatalogoopcion1|Text,idcatalogoopcion2|Text,idcatalogoopcion3|Text,]
--SELECT
DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(MAX)

SET @BD = :BD 
DECLARE @SQL VARCHAR(MAX)

SET @SQL = '


DECLARE @IDCOMPANIA INT
DECLARE @IDEMPRESA INT
DECLARE @IDINDUSTRIA INT
DECLARE @NEMPLEADOS VARCHAR(128)
DECLARE @IDCOMPANIAGRUPO INT
DECLARE @EMPRESA VARCHAR(512)
DECLARE @URL VARCHAR(512)
DECLARE @TELEFONOCORPORATIVO VARCHAR(512)
DECLARE @DIRECCION1 VARCHAR(512)
DECLARE @DIRECCION2 VARCHAR(512)
DECLARE @CIUDAD VARCHAR(512)
DECLARE @CODIGOPOSTAL VARCHAR(512)
DECLARE @IDESTADO VARCHAR(512)
DECLARE @IDPAIS VARCHAR(512)
DECLARE @IDCATALOGOOPCION1 INT
DECLARE @IDCATALOGOOPCION2 INT
DECLARE @IDCATALOGOOPCION3 INT
DECLARE @NUMEMPLEADO INT 


SET @IDCOMPANIA  = CAST(' + ISNULL(:IDCOMPANIA  , 0)+' AS INT)
SET @IDEMPRESA   = CAST(' + ISNULL(:IDEMPRESA   , 0)+' AS INT)
SET @IDINDUSTRIA = CAST(' + ISNULL(:IDINDUSTRIA , 0)+' AS INT)

SET @IDCOMPANIAGRUPO = ISNULL(CAST(' + ISNULL(:IDCOMPANIAGRUPO, 0)+' AS INT), 0)

SET @EMPRESA             = ISNULL(''' + ISNULL(REPLACE(:EMPRESA             ,'''',''''''), '')+ ''','''')
SET @URL                 = ISNULL(''' + ISNULL(REPLACE(:URL                 ,'''',''''''), '')+ ''','''')
SET @TELEFONOCORPORATIVO = ISNULL(''' + ISNULL(REPLACE(:TELEFONOCORPORATIVO ,'''',''''''), '')+ ''','''')
SET @DIRECCION1          = ISNULL(''' + ISNULL(REPLACE(:DIRECCION1          ,'''',''''''), '')+ ''','''')
SET @DIRECCION2          = ISNULL(''' + ISNULL(REPLACE(:DIRECCION2          ,'''',''''''), '')+ ''','''')
SET @CIUDAD              = ISNULL(''' + ISNULL(REPLACE(:CIUDAD              ,'''',''''''), '')+ ''','''')
SET @CODIGOPOSTAL        = ISNULL(''' + ISNULL(REPLACE(:CODIGOPOSTAL        ,'''',''''''), '')+ ''','''')
SET @IDESTADO            = ISNULL(''' + ISNULL(REPLACE(:IDESTADO            ,'''',''''''), '')+ ''','''')
SET @IDPAIS              = ISNULL(''' + ISNULL(REPLACE(:IDPAIS              ,'''',''''''), '')+ ''','''')
SET @NEMPLEADOS          = ISNULL(' + ISNULL(:NEMPLEADOS, 0)+', 0) 
SET @NUMEMPLEADO=0

IF (''' + ISNULL(:IDCATALOGOOPCION1, '') +''' = ''undefined'' OR ''' + ISNULL(:IDCATALOGOOPCION1, '') +''' = ''null'')
   SET @IDCATALOGOOPCION1 = ''''
ELSE
   SET @IDCATALOGOOPCION1 = CAST(' + ISNULL(:IDCATALOGOOPCION1, 0) +' AS INT)
   
IF (''' + ISNULL(:IDCATALOGOOPCION2, '') +''' = ''undefined'' OR ''' + ISNULL(:IDCATALOGOOPCION2, 0)+ ''' = ''null'')
   SET @IDCATALOGOOPCION2 = ''''
ELSE
   SET @IDCATALOGOOPCION2 = CAST(' + ISNULL(:IDCATALOGOOPCION2, 0)+ ' AS INT) 
   
IF (''' + ISNULL(:IDCATALOGOOPCION3, '') +''' = ''undefined'' OR ''' + ISNULL(:IDCATALOGOOPCION3, 0)+ ''' = ''null'')
   SET @IDCATALOGOOPCION3 = ''''
ELSE
   SET @IDCATALOGOOPCION3 = CAST(' + ISNULL(:IDCATALOGOOPCION3, 0)+ ' AS INT) 

IF(@IDESTADO = ''undefined'' OR @IDESTADO = ''null'')
	SET @IDESTADO = ''AGS''

IF(@IDPAIS = ''undefined'' OR @IDPAIS = ''null'')
	SET @IDPAIS = ''MX''
IF( ISNUMERIC(@NEMPLEADOS)=0)
	SET @NUMEMPLEADO = 0
ELSE	
	SET @NUMEMPLEADO=CAST(@NEMPLEADOS AS INT)	
	

EXEC ' + @BD + '.DBO.SP_INSERTA_COMPANIA_MV @IDCOMPANIA,@IDEMPRESA,@IDINDUSTRIA,@NUMEMPLEADO,@IDCOMPANIAGRUPO,@EMPRESA,@URL,@TELEFONOCORPORATIVO,@DIRECCION1,@DIRECCION2,@CIUDAD,@CODIGOPOSTAL,@IDESTADO,@IDPAIS,@IDCATALOGOOPCION1,@IDCATALOGOOPCION2,@IDCATALOGOOPCION3
'
EXEC(@SQL)