//[bd|Text,fecha|Text,idusuario|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
SET @SQL = '

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

SET @BD = ''' + ISNULL(:BD,'') +'''

DECLARE @FECHAUX DATETIME 
IF (CONVERT(DATETIME,''' + ISNULL(:FECHA,'') + ''',20) = 0) 
BEGIN 
	SET @FECHAUX = GETDATE() 
END 
ELSE 
BEGIN 
	SET @FECHAUX = CONVERT(DATETIME,''' + ISNULL(:FECHA,'') +''',20) 
END 
SELECT 
IDUSUARIO AS IDU, 
IDSEGUIMIENTO AS IDS, 
IDPROSPECTO AS IDP, 
IDOPORTUNIDAD AS IDO, 
IDSEGUIMIENTOCATEGORIA AS IDSC, 
TIPO_SEGUIMIENTO AS TS, 
SISTEMA AS SIS, 
COMENTARIO CM,
IDRELACIONADO AS IDR,
CONVERT(VARCHAR,FECHAHORA,20) AS FH 
FROM (SELECT 
         ROW_NUMBER() OVER ( PARTITION BY PS.IDPROSPECTO, PS.IDOPORTUNIDAD ORDER BY 
PS.FECHAHORA DESC ) AS ''RowNumber'', 
         PS.IDSEGUIMIENTO, 
         PS.IDPROSPECTO, 
         SALESUP_CT.DBO.PreparaCadenaApp2(PS.COMENTARIO) AS COMENTARIO, 
		 PS.IDOPORTUNIDAD, 
		 PS.TIPO_SEGUIMIENTO, 
		 PS.IDSEGUIMIENTOCATEGORIA, 
		 PS.SISTEMA, 
    	 PS.IDUSUARIO, 
    	 PS.ULTIMAMODIFICACION, 
		 PS.FECHAHORA,
		 PS.IDRELACIONADO
      FROM '+ :BD + '.dbo.prospectos_seguimiento PS WITH (NOLOCK), ' + :BD + '.dbo.PROSPECTOS P WITH (NOLOCK) 
	  LEFT JOIN '+ :BD + '.dbo.PROSPECTOS_ASIGNADOS A WITH (NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO 
	  WHERE A.IDUSUARIO = CAST(''' + ISNULL(:IDUSUARIO,'') + ''' AS INT) AND P.IDPROSPECTO = A.IDPROSPECTO 
	  AND A.IDPROSPECTO = PS.IDPROSPECTO AND P.IDULTIMOSEGUIMIENTO IS NOT NULL 
	  AND (P.DESCARTADO = 0 OR P.DESCARTADOFECHA >= @FECHAUX)  
      AND PS.ULTIMAMODIFICACION >= CONVERT(DATETIME,''' + ISNULL(:FECHA,'') +  ''',20) 
      ) dt 
WHERE RowNumber <= 10 
ORDER BY IDPROSPECTO, IDSEGUIMIENTO 
'
EXEC (@SQL)