//[idusuario|Integer,idempresa|Integer,bd|Text,fecha|Text,]
-- SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(100)
DECLARE @FECHA VARCHAR(100)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
SET @IDUSUARIO =CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))
SET @IDEMPRESA = CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @BD=ISNULL(:BD,'')
SET @FECHA=ISNULL(:FECHA,'')

SET @SQL='
SELECT SALESUP_CT.DBO.PreparaCadenaApp2(CI_AUX.ASUNTO) AS ASUNTO, SALESUP_CT.DBO.PreparaCadenaApp2(CI_AUX.DESCRIPCION) AS DESCRIPCION, SALESUP_CT.DBO.PreparaCadenaApp2(LUGAR) AS LUGAR,CI_AUX.* , '+@IDEMPRESA+' AS IDIEMPRESA, '+@IDUSUARIO+' AS IDUSUARIO
FROM '+@BD+'.dbo.CITAS CI_AUX WITH (NOLOCK) WHERE CI_AUX.IDCITA IN ( 
SELECT C.IDCITA FROM '+@BD+'.dbo.CITAS C WITH (NOLOCK), 
'+@BD+'.dbo.CITAS_INVITADOS CI WITH (NOLOCK) 
WHERE C.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20) AND C.IDCITA = CI.IDCITA AND C.IDEMPRESA = '+@IDEMPRESA+' AND  
(C.IDUSUARIO_CREACION = '+@IDUSUARIO+' OR CI.idpersona = '+@IDUSUARIO+') 
GROUP BY C.IDCITA) 
'
EXEC (@SQL)