//[bd|Untyped,idusuario|Untyped,fecha|Untyped,version|Untyped,dispositivo|Untyped,token|Untyped,configuracion|Untyped,tokendevice|Untyped,sp_ipaddress|Untyped,sp_browser|Untyped,idempresa|Untyped,]
-- select  
  DECLARE @BD VARCHAR(512)  
  DECLARE @EXECSQL VARCHAR(8000)   
   SET @BD = '<#BD/>'
   
  DECLARE @IDUSUARIO INT
  SET @IDUSUARIO = CAST('<#IDUSUARIO/>' AS INT)
  
  DECLARE @SESSIONID VARCHAR(32)
  SELECT @SESSIONID = CAST(YEAR(GETDATE()) AS VARCHAR(4)) + CAST(MONTH(GETDATE()) AS VARCHAR(2)) + CAST(DAY(GETDATE()) AS VARCHAR(2)) + CAST(@IDUSUARIO AS VARCHAR(12)) + 'APP'
   
   DECLARE @FECHA DATETIME 
   SET @FECHA = CONVERT(DATETIME,'<#FECHA/>',20)   
   
   DECLARE @VERSION FLOAT 
   SET @VERSION = CAST('<#VERSION/>' AS FLOAT)  
   
   DECLARE @VERSIONMINIMA FLOAT   
   DECLARE @RESPUESTA INT SET @RESPUESTA = 1   
   DECLARE @FULTIMASINC DATETIME
   DECLARE @FECHAACTUAL DATETIME
   DECLARE @FECHASINCRONIZACION DATETIME
   
   SET @FECHAACTUAL = SALESUP_CT.DBO.GETONLYDATE(GETDATE())
   SET @FULTIMASINC = GETDATE()  
   
   DECLARE @BORRAR_BASELOCAL INT  
   DECLARE @TOTAL INT  
   DECLARE @CONFIGPUSH VARCHAR(255)  
   DECLARE @IDCSS INT
   DECLARE @REALIZARCONSULTAS INT
       
   SELECT @IDCSS = IDCSS FROM <#BD/>.dbo.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
  
   SET @TOTAL = 0    IF('<#DISPOSITIVO>' = 'iphone')   
   BEGIN    
        SELECT @VERSIONMINIMA = VERSION_MINIMA_IPHONE FROM SALESUP_CT.dbo.V_VERSIONES   
   END   
   ELSE   
   BEGIN   
         SELECT @VERSIONMINIMA = VERSION_MINIMA_ANDROID FROM SALESUP_CT.dbo.V_VERSIONES   
   END   
   
   IF(@VERSION > @VERSIONMINIMA)   
   BEGIN
       UPDATE <#BD/>.dbo.USUARIOS_TOKENS SET VERSION = @VERSION WHERE IDUSUARIO = @IDUSUARIO AND TOKEN = '<#TOKEN/>'
   END
   ELSE IF(@VERSION < @VERSIONMINIMA)   
   BEGIN
       SET @RESPUESTA = 3   
   END   
   IF('<#CONFIGURACION/>' <> '')   
   BEGIN
       UPDATE <#BD/>.dbo.USUARIOS_TOKENS SET CONFIGURACION = '<#CONFIGURACION/>' WHERE IDUSUARIO = @IDUSUARIO AND TOKEN = '<#TOKEN/>' OR TOKEN_DEVICE = '<#TOKENDEVICE/>'  
   END
   
   SELECT @REALIZARCONSULTAS = 0, @CONFIGPUSH = CONFIGURACION, @BORRAR_BASELOCAL = BORRAR_BASELOCAL, @FECHASINCRONIZACION = SALESUP_CT.DBO.GETONLYDATE(ULTIMA_SINCRONIZACION) FROM <#BD/>.dbo.USUARIOS_TOKENS WHERE IDUSUARIO = @IDUSUARIO AND TOKEN = '<#TOKEN/>' OR TOKEN_DEVICE = '<#TOKENDEVICE/>'
   
   IF(@FECHAACTUAL > @FECHASINCRONIZACION)
   BEGIN
   		UPDATE SALESUP_CT.dbo.USUARIOS SET ULTIMO_ACCESO = @FULTIMASINC, ACTUALIZAR = 1 WHERE IDUSUARIO = @IDUSUARIO
		
		DELETE FROM <#BD/>.DBO.USUARIOS_ACCESOS WHERE  SESSIONID like @SESSIONID
		UPDATE <#BD/>.DBO.USUARIOS_ACCESOS SET ACTIVO=0 WHERE IDUSUARIO=@IDUSUARIO AND ACTIVO=1 
	    INSERT INTO <#BD/>.DBO.USUARIOS_ACCESOS (SESSIONID, IDUSUARIO, DIRECCIONIP, BROWSER,ACTIVO) VALUES (@SESSIONID,@IDUSUARIO,'<#SP_IPADDRESS/>', '<#SP_BROWSER/>',1)
   END
   
   UPDATE <#BD/>.dbo.USUARIOS_TOKENS SET ULTIMA_SINCRONIZACION = @FULTIMASINC WHERE IDUSUARIO = @IDUSUARIO AND TOKEN = '<#TOKEN/>' OR TOKEN_DEVICE = '<#TOKENDEVICE/>'        
   
   SELECT COUNT(distinct(m.idtabla)) AS TOTAL, @RESPUESTA AS RESPUESTA,CONVERT(VARCHAR,@FULTIMASINC,20) AS FULTIMASINC , 
   @BORRAR_BASELOCAL AS BORRAR_BASELOCAL, @IDCSS AS IDCSS,  @REALIZARCONSULTAS as  REALIZARCONSULTAS,
   ''+@BD+'' AS BD, @IDUSUARIO AS IDUSUARIO,'<#IDEMPRESA/>' AS IDEMPRESA, '<#FECHA/>' AS FECHA , '<#TOKEN/>' AS TOKEN
   FROM <#BD/>.dbo.MODIFICACIONES M WITH (NOLOCK), SALESUP_CT.dbo.V_TABLAS VT WITH (NOLOCK)   
   WHERE M.IDTABLA = VT.IDTABLA   AND (IDEMPRESA = CAST('<#IDEMPRESA/>' AS INT) OR IDUSUARIO = @IDUSUARIO)   AND  FECHAHORA >= @FECHA