//[idusuario|Text,token|Text,bd|Text,]
-- SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @TOKEN VARCHAR(MAX)
DECLARE @BD VARCHAR(MAX)
SET @BD=ISNULL(:BD,'')
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))
SET @TOKEN = CAST(ISNULL(:TOKEN,'') AS VARCHAR(MAX))

SET @SQL='
SELECT PUEDESINCRONIZAR, MENSAJE FROM '+@BD+'.DBO.USUARIOS_TOKENS WHERE IDUSUARIO = '+@IDUSUARIO+' AND TOKEN = '''+@TOKEN+'''
'

EXEC (@SQL)