//[bd|Text,idusuario|Integer,]
-- select

DECLARE @BD VARCHAR(512)
DECLARE @IDUSUARIO VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO = ISNULL(:IDUSUARIO,0)

SET @EXECSQL = 'SELECT * FROM '+@BD+'.dbo.USUARIOS_LINEAS_COMISION WITH (NOLOCK) WHERE IDUSUARIO ='+CAST(@IDUSUARIO AS VARCHAR(1000))
EXEC(@EXECSQL)