//[idusuario|Text,fecha|Text,bd|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(MAX)
SET @BD=ISNULL(:BD,'')

SET @SQL='
DECLARE @IDGRUPO INT
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @FECHA DATETIME

SET @IDUSUARIO = CAST('''+ISNULL(:IDUSUARIO,'')+''' AS INT)
SET @FECHA = CONVERT(DATETIME,'''+ISNULL(:FECHA,'')+''',20)

SELECT @IDEMPRESA = IDEMPRESA, @IDGRUPO = IDGRUPO FROM '+@BD+'.DBO.USUARIOS WITH (NOLOCK) WHERE IDUSUARIO = @IDUSUARIO

DECLARE @CONT INT

SELECT @CONT=COUNT(UP.IDPLANTILLA) FROM '+@BD+'.DBO.USUARIOS_PLANTILLAS UP WITH (NOLOCK)
LEFT JOIN '+@BD+'.DBO.USUARIOS U WITH (NOLOCK) ON U.IDUSUARIO=UP.IDUSUARIO 
 WHERE (UP.COMPARTIRCON=@IDGRUPO OR UP.COMPARTIRCON=-1) AND UP.IDUSUARIO != @IDUSUARIO and U.IDEMPRESA=@IDEMPRESA 

IF @CONT>0 
 BEGIN
 	  SELECT UP.TIPOCORREO,UP.IDPLANTILLA,UP.IDUSUARIO AS IDUSUARIOP, @IDUSUARIO AS IDUSUARIO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.DESCRIPCION) AS DESCRIPCION, SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.CUERPO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS CUERPO,
	  SALESUP_CT.DBO.PreparaCadenaApp2(UP.ANEXOS) AS ANEXOS, SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO) AS NOMBRE_ARCHIVO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO_REAL) AS NOMBRE_ARCHIVO_REAL,
	  SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.ASUNTO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS ASUNTO, UP.COMPARTIRCON
	  FROM '+@BD+'.DBO.USUARIOS_PLANTILLAS UP WITH (NOLOCK)
	  LEFT JOIN '+@BD+'.DBO.USUARIOS U WITH (NOLOCK) ON U.IDUSUARIO=UP.IDUSUARIO AND U.IDEMPRESA=@IDEMPRESA
	  WHERE UP.IDUSUARIO = @IDUSUARIO
	  UNION ALL
	  SELECT UP.TIPOCORREO,UP.IDPLANTILLA,UP.IDUSUARIO AS IDUSUARIOP, @IDUSUARIO AS IDUSUARIO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.DESCRIPCION) AS DESCRIPCION, SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.CUERPO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS CUERPO,
	  SALESUP_CT.DBO.PreparaCadenaApp2(UP.ANEXOS) AS ANEXOS, SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO) AS NOMBRE_ARCHIVO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO_REAL) AS NOMBRE_ARCHIVO_REAL,
	  SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.ASUNTO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS ASUNTO, UP.COMPARTIRCON 
	  FROM '+@BD+'.DBO.USUARIOS_PLANTILLAS UP WITH (NOLOCK)
	  LEFT JOIN '+@BD+'.DBO.USUARIOS U WITH (NOLOCK) ON U.IDUSUARIO=UP.IDUSUARIO 
	  WHERE (UP.COMPARTIRCON=@IDGRUPO OR UP.COMPARTIRCON=-1) AND UP.IDUSUARIO != @IDUSUARIO and U.IDEMPRESA=@IDEMPRESA AND UP.ULTIMAMODIFICACION >= @FECHA
	  ORDER BY DESCRIPCION
 END
ELSE
BEGIN
  	   SELECT UP.TIPOCORREO,UP.IDPLANTILLA,UP.IDUSUARIO AS IDUSUARIOP, @IDUSUARIO AS IDUSUARIO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.DESCRIPCION) AS DESCRIPCION, SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.CUERPO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS CUERPO,
	  SALESUP_CT.DBO.PreparaCadenaApp2(UP.ANEXOS) AS ANEXOS, SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO) AS NOMBRE_ARCHIVO,SALESUP_CT.DBO.PreparaCadenaApp2(UP.NOMBRE_ARCHIVO_REAL) AS NOMBRE_ARCHIVO_REAL,
	  SALESUP_CT.DBO.PreparaCadenaApp2(REPLACE(REPLACE(CAST(UP.ASUNTO AS VARCHAR(MAX)),''['',''{{''),'']'',''}}'')) AS ASUNTO, UP.COMPARTIRCON
	  FROM '+@BD+'.DBO.USUARIOS_PLANTILLAS UP WITH (NOLOCK)
	  LEFT JOIN '+@BD+'.DBO.USUARIOS U WITH (NOLOCK) ON U.IDUSUARIO=UP.IDUSUARIO
	  WHERE UP.IDUSUARIO = @IDUSUARIO and U.IDEMPRESA=@IDEMPRESA AND UP.ULTIMAMODIFICACION >= @FECHA
	  
	  ORDER BY DESCRIPCION
END
'
EXEC (@SQL)