//[base|Text,datos|Text,sessionid|Integer,]
-- SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @BASE VARCHAR(MAX)
DECLARE @SESSIONID INT
SET @SESSIONID = ISNULL(:SESSIONID,0)
SET @BASE=ISNULL(:BASE,'')
SET @SQL='

DECLARE @DATOSJSON VARCHAR(MAX)
DECLARE @SESSIONID INT

SET @DATOSJSON = '''+ISNULL(:DATOS,'')+'''
SET @SESSIONID = CAST('+CAST(@SESSIONID AS VARCHAR(1000))+' AS INT)

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDCITA_LOCAL INT,IDCITA INT, IDUSUARIO_CREACION INT, IDEMPRESA INT, ASUNTO VARCHAR(MAX),LUGAR VARCHAR(MAX), FECHA_INICIO DATETIME, 
FECHA_FIN DATETIME,FECHACREACION DATETIME,RECORDATORIO_CORREO_ACTIVO INT, RECORDATORIO_IDPLANTILLA INT, RECORDATORIO_MOMENTO INT, RECORDATORIO_SMS_ACTIVO INT, RECORDATORIO_SMS_IDPLANTILLA INT,
RECORDATORIO_SMS_MOMENTO INT, NOTIFICA_CORREO_ACTIVO INT, NOTIFICA_IDPLANTILLA INT, NOTIFICA_SMS_ACTIVO INT, NOTIFICA_SMS_IDPLANTILLA INT, DESCRIPCION VARCHAR(MAX),PROXFECHARECORDAR DATETIME,
NOTIFICADO INT, ACTIVO INT,TKC VARCHAR(MAX))

DECLARE @TO INT, @TOTAL INT, @CONTEO INT

DECLARE @IDCITA_LOCAL INT
DECLARE @IDCITA INT 
DECLARE @IDUSUARIO_CREACION INT 
DECLARE @IDEMPRESA INT 
DECLARE @ASUNTO VARCHAR(MAX)
DECLARE @LUGAR VARCHAR(MAX) 
DECLARE @FECHA_INICIO DATETIME 
DECLARE @FECHA_FIN DATETIME
DECLARE @FECHACREACION DATETIME
DECLARE @RECORDATORIO_CORREO_ACTIVO INT 
DECLARE @RECORDATORIO_IDPLANTILLA INT
DECLARE @RECORDATORIO_MOMENTO INT 
DECLARE @RECORDATORIO_SMS_ACTIVO INT 
DECLARE @RECORDATORIO_SMS_IDPLANTILLA INT
DECLARE @RECORDATORIO_SMS_MOMENTO INT
DECLARE @NOTIFICA_CORREO_ACTIVO INT 
DECLARE @NOTIFICA_IDPLANTILLA INT 
DECLARE @NOTIFICA_SMS_ACTIVO INT 
DECLARE @NOTIFICA_SMS_IDPLANTILLA INT 
DECLARE @DESCRIPCION VARCHAR(MAX)
DECLARE @PROXFECHARECORDAR DATETIME
DECLARE @NOTIFICADO INT 
DECLARE @ACTIVO INT
DECLARE @TKC VARCHAR(MAX)

SELECT @IDEMPRESA = IDEMPRESA FROM '+@BASE+'.DBO.USUARIOS WHERE IDUSUARIO = @SESSIONID

INSERT INTO @TABLATEMP (IDCITA_LOCAL,IDCITA, IDUSUARIO_CREACION, IDEMPRESA, ASUNTO,LUGAR, FECHA_INICIO, FECHA_FIN,FECHACREACION,RECORDATORIO_CORREO_ACTIVO, RECORDATORIO_IDPLANTILLA,RECORDATORIO_MOMENTO, RECORDATORIO_SMS_ACTIVO, RECORDATORIO_SMS_IDPLANTILLA,RECORDATORIO_SMS_MOMENTO,NOTIFICA_CORREO_ACTIVO, NOTIFICA_IDPLANTILLA, NOTIFICA_SMS_ACTIVO, NOTIFICA_SMS_IDPLANTILLA, DESCRIPCION,PROXFECHARECORDAR,NOTIFICADO,ACTIVO,TKC)
Select 
       max(case when NAME=''IDCITA_LOCAL'' then STRINGVALUE else '''' end) as IDCITA_LOCAL,
	   max(case when NAME=''IDCITA'' then STRINGVALUE else '''' end) as IDCITA,
	   max(case when NAME=''IDUSUARIO_CREACION'' then STRINGVALUE else '''' end) as IDUSUARIO_CREACION,
       max(case when NAME=''IDEMPRESA'' then STRINGVALUE else '''' end) as IDEMPRESA,
       max(case when NAME=''ASUNTO'' then STRINGVALUE else '''' end) as ASUNTO,
       max(case when NAME=''LUGAR'' then STRINGVALUE else '''' end) as LUGAR,
	   max(case when NAME=''FECHA_INICIO'' then STRINGVALUE else '''' end) as FECHA_INICIO,
	   max(case when NAME=''FECHA_FIN'' then STRINGVALUE else '''' end) as FECHA_FIN,
	   max(case when NAME=''FECHACREACION'' then STRINGVALUE else '''' end) as FECHACREACION,
	   max(case when NAME=''RECORDATORIO_CORREO_ACTIVO'' then STRINGVALUE else '''' end) as RECORDATORIO_CORREO_ACTIVO,
	   max(case when NAME=''RECORDATORIO_IDPLANTILLA'' then STRINGVALUE else '''' end) as RECORDATORIO_IDPLANTILLA,
	   max(case when NAME=''RECORDATORIO_MOMENTO'' then STRINGVALUE else '''' end) as RECORDATORIO_MOMENTO,
	   max(case when NAME=''RECORDATORIO_SMS_ACTIVO'' then STRINGVALUE else '''' end) as RECORDATORIO_SMS_ACTIVO,
	   max(case when NAME=''RECORDATORIO_SMS_IDPLANTILLA'' then STRINGVALUE else '''' end) as RECORDATORIO_SMS_IDPLANTILLA,
	   max(case when NAME=''RECORDATORIO_SMS_MOMENTO'' then STRINGVALUE else '''' end) as RECORDATORIO_SMS_MOMENTO,
	   max(case when NAME=''NOTIFICA_CORREO_ACTIVO'' then STRINGVALUE else '''' end) as NOTIFICA_CORREO_ACTIVO,
	   max(case when NAME=''NOTIFICA_IDPLANTILLA'' then STRINGVALUE else '''' end) as NOTIFICA_IDPLANTILLA,
	   max(case when NAME=''NOTIFICA_SMS_ACTIVO'' then STRINGVALUE else '''' end) as NOTIFICA_SMS_ACTIVO,
	   max(case when NAME=''NOTIFICA_SMS_IDPLANTILLA'' then STRINGVALUE else '''' end) as NOTIFICA_SMS_IDPLANTILLA,
	   max(case when NAME=''DESCRIPCION'' then STRINGVALUE else '''' end) as DESCRIPCION,
	   max(case when NAME=''PROXFECHARECORDAR'' then STRINGVALUE else '''' end) as PROXFECHARECORDAR,
	   max(case when NAME=''NOTIFICADO'' then STRINGVALUE else '''' end) as NOTIFICADO,
	   max(case when NAME=''ACTIVO'' then STRINGVALUE else '''' end) as ACTIVO,
	   max(case when NAME=''TKC'' then STRINGVALUE else '''' end) as TKC
from SALESUP_CT.dbo.parseJSON(@DATOSJSON)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	 SELECT @IDCITA_LOCAL = IDCITA_LOCAL,@IDCITA= IDCITA, @IDUSUARIO_CREACION= IDUSUARIO_CREACION, @IDEMPRESA= IDEMPRESA, @ASUNTO= ASUNTO,@LUGAR= LUGAR, @FECHA_INICIO= FECHA_INICIO, @FECHA_FIN= FECHA_FIN,@FECHACREACION= FECHACREACION,@RECORDATORIO_CORREO_ACTIVO= RECORDATORIO_CORREO_ACTIVO, @RECORDATORIO_IDPLANTILLA= RECORDATORIO_IDPLANTILLA,@RECORDATORIO_MOMENTO= RECORDATORIO_MOMENTO, @RECORDATORIO_SMS_ACTIVO= RECORDATORIO_SMS_ACTIVO, @RECORDATORIO_SMS_IDPLANTILLA= RECORDATORIO_SMS_IDPLANTILLA,@RECORDATORIO_SMS_MOMENTO= RECORDATORIO_SMS_MOMENTO,@NOTIFICA_CORREO_ACTIVO= NOTIFICA_CORREO_ACTIVO, @NOTIFICA_IDPLANTILLA= NOTIFICA_IDPLANTILLA, @NOTIFICA_SMS_ACTIVO= NOTIFICA_SMS_ACTIVO, @NOTIFICA_SMS_IDPLANTILLA= NOTIFICA_SMS_IDPLANTILLA, @DESCRIPCION= DESCRIPCION,@PROXFECHARECORDAR= PROXFECHARECORDAR,@NOTIFICADO= NOTIFICADO,@ACTIVO = ACTIVO, @TKC = TKC FROM @TABLATEMP WHERE ID = @TO
	 
	 IF(@RECORDATORIO_SMS_IDPLANTILLA = 0)
	 BEGIN
	 	  SET @RECORDATORIO_SMS_ACTIVO = 0
	 END
	 ELSE
	 BEGIN
	 	  SET @RECORDATORIO_SMS_ACTIVO = 1
	 END
	 
	 IF(@IDCITA = 0)
	 BEGIN
		INSERT INTO '+@BASE+'.DBO.CITAS (IDUSUARIO_CREACION, IDEMPRESA, ASUNTO,LUGAR, FECHA_INICIO, FECHA_FIN,FECHACREACION,RECORDATORIO_CORREO_ACTIVO, 
			   RECORDATORIO_IDPLANTILLA,RECORDATORIO_MOMENTO, RECORDATORIO_SMS_ACTIVO, RECORDATORIO_SMS_IDPLANTILLA,RECORDATORIO_SMS_MOMENTO,NOTIFICA_CORREO_ACTIVO, 
			   NOTIFICA_IDPLANTILLA, NOTIFICA_SMS_ACTIVO, NOTIFICA_SMS_IDPLANTILLA, DESCRIPCION,TKC,RECURRENCIA,TIPOFIN,FRECUENCIA,PROXFECHARECORDAR,NOTIFICADO,ACTIVO)
		VALUES(@IDUSUARIO_CREACION, @IDEMPRESA, @ASUNTO,@LUGAR, @FECHA_INICIO, @FECHA_FIN,@FECHACREACION,@RECORDATORIO_CORREO_ACTIVO, 
			   @RECORDATORIO_IDPLANTILLA,@RECORDATORIO_MOMENTO, @RECORDATORIO_SMS_ACTIVO, @RECORDATORIO_SMS_IDPLANTILLA,@RECORDATORIO_SMS_MOMENTO,@NOTIFICA_CORREO_ACTIVO, 
			   @NOTIFICA_IDPLANTILLA, @NOTIFICA_SMS_ACTIVO, @NOTIFICA_SMS_IDPLANTILLA, @DESCRIPCION,@TKC,0,0,1,@PROXFECHARECORDAR,@NOTIFICADO,@ACTIVO)
		
		SELECT @IDCITA = IDCITA FROM '+@BASE+'.DBO.CITAS WHERE IDUSUARIO_CREACION = @IDUSUARIO_CREACION AND IDEMPRESA = @IDEMPRESA AND TKC = @TKC ORDER BY IDCITA DESC
		
		UPDATE @TABLATEMP SET IDCITA = @IDCITA WHERE IDCITA_LOCAL = @IDCITA_LOCAL
	END
	ELSE
	BEGIN
		 UPDATE '+@BASE+'.dbo.CITAS 
		 SET ASUNTO= @ASUNTO,
     	 LUGAR= @LUGAR,
     	 FECHA_INICIO= @FECHA_INICIO,
     	 FECHA_FIN= @FECHA_FIN,
     	 RECORDATORIO_CORREO_ACTIVO= @RECORDATORIO_CORREO_ACTIVO,
     	 RECORDATORIO_IDPLANTILLA= @RECORDATORIO_IDPLANTILLA,
     	 RECORDATORIO_MOMENTO= @RECORDATORIO_MOMENTO,
     	 RECORDATORIO_SMS_ACTIVO= @RECORDATORIO_SMS_ACTIVO,
     	 RECORDATORIO_SMS_IDPLANTILLA= @RECORDATORIO_SMS_IDPLANTILLA,
     	 RECORDATORIO_SMS_MOMENTO= @RECORDATORIO_SMS_MOMENTO,
     	 DESCRIPCION= @DESCRIPCION,
     	 NOTIFICA_CORREO_ACTIVO=@NOTIFICA_CORREO_ACTIVO,
     	 NOTIFICA_IDPLANTILLA=@NOTIFICA_IDPLANTILLA,
     	 NOTIFICA_SMS_ACTIVO=@NOTIFICA_SMS_ACTIVO,
     	 NOTIFICA_SMS_IDPLANTILLA=@NOTIFICA_SMS_IDPLANTILLA,
		 NOTIFICADO = @NOTIFICADO,
		 ACTIVO = @ACTIVO,
     	 PROXFECHAREPETIR=@PROXFECHARECORDAR
 		 WHERE IDCITA=@IDCITA AND TKC = @TKC
	END
	
	SET @TO = @TO+1
END

SELECT * FROM @TABLATEMP
'
EXEC (@SQL)