//[error|Text,idusuario|Integer,bd|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @ERROR VARCHAR(MAX)
DECLARE @IDUSUARIO INT
DECLARE @BD VARCHAR(1000)
SET @ERROR =  ISNULL(:ERROR,'')
SET @IDUSUARIO =  ISNULL(:IDUSUARIO,0)
SET @BD = ISNULL(:BD,'')
INSERT INTO SALESUP_CT.dbo.ERRORES_MOVIL (ERROR,IDUSUARIO,BD) VALUES(@ERROR,@IDUSUARIO,@BD)

SELECT 1 AS RESPUESTA