//[bd|Text,token|Text,idusuario|Text,]
--DELETE

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @TOKEN VARCHAR(1000)

SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))
SET @TOKEN=ISNULL(:TOKEN,'')

SET @EXECSQL = 'UPDATE '+@BD+'.dbo.usuarios_tokens WITH (ROWLOCK) SET CONECTADO = 0 WHERE idusuario = '+@IDUSUARIO+' AND TOKEN = '''+@TOKEN+''''
EXEC(@EXECSQL)