//[bd|Text,idusuario|Integer,]
-- SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @BD VARCHAR(1000)
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDUSUARIO VARCHAR(1000)
SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO =  CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))

SET @SQL='SELECT TOP 300 * FROM '+@BD+'.dbo.USUARIOS_NOTIFICACIONES WITH (NOLOCK) WHERE IDUSUARIO = '+@IDUSUARIO 
EXEC (@SQL)  