//[correo|Text,]
-- SELECT
DECLARE @RESPUESTA INT
DECLARE @MENSAJE VARCHAR(512)
DECLARE @CORREO VARCHAR(1000)
SET @CORREO=CAST(ISNULL(:CORREO,'') AS VARCHAR(512))

SELECT @RESPUESTA = COUNT(IDUSUARIO) FROM SALESUP_CT.dbo.USUARIOS WHERE EMAIL = @CORREO

IF(@RESPUESTA != 0)
BEGIN
	 SET @MENSAJE = 'El correo que ingreso ya está registrado en el sistema'
END
ELSE
BEGIN
	 SET @MENSAJE = '1' 
END

SELECT @RESPUESTA AS RESPUESTA, @MENSAJE AS MENSAJE, @CORREO AS CORREO