//[bd|Text,idseguimiento|Integer,idusuario|Integer,]
-- select

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @IDSEGUIMIENTO VARCHAR(1000)

SET @BD = ISNULL(:BD,'')
SET @IDSEGUIMIENTO=CAST(ISNULL(:IDSEGUIMIENTO,0) AS VARCHAR(1000))
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))

SET @EXECSQL = 'SELECT '
         SET @EXECSQL = @EXECSQL + 'PS.IDSEGUIMIENTO AS IDS, '
         SET @EXECSQL = @EXECSQL + 'PS.IDPROSPECTO AS IDP, '
         SET @EXECSQL = @EXECSQL + 'PS.COMENTARIO AS CM, '
		 SET @EXECSQL = @EXECSQL + 'PS.IDOPORTUNIDAD AS IDO, '
		 SET @EXECSQL = @EXECSQL + 'PS.TIPO_SEGUIMIENTO AS TS, '
		 SET @EXECSQL = @EXECSQL + 'PS.IDSEGUIMIENTOCATEGORIA AS IDSC, '
		 SET @EXECSQL = @EXECSQL + 'PS.SISTEMA AS SIS, '
    	 SET @EXECSQL = @EXECSQL + 'PS.ULTIMAMODIFICACION, '
		 SET @EXECSQL = @EXECSQL + 'PS.FECHAHORA AS FH,'+@IDUSUARIO+' AS IDUSUARIO, '+@IDSEGUIMIENTO+' AS IDSEGUMIENTO '
      SET @EXECSQL = @EXECSQL + 'FROM '+@BD+'.dbo.prospectos_seguimiento PS WITH (NOLOCK) '
	  SET @EXECSQL = @EXECSQL + 'WHERE PS.IDUSUARIO = '+@IDUSUARIO+' AND PS.IDSEGUIMIENTO = '+@IDSEGUIMIENTO
EXEC(@EXECSQL)
