//[id|Text,bd|Text,tipo|Text,idusuario|Text,idplantilla|Text,]
--INSERT 
DECLARE @SQL VARCHAR(MAX)
SET @SQL = '
DECLARE @BD VARCHAR(512)
DECLARE @TIPO INT
DECLARE @ID INT
DECLARE @IDUSUARIO INT
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDVENTA INT
DECLARE @IDPLANTILLA INT
DECLARE @DESTINATARIO VARCHAR(512) 

DECLARE @EXECSQL VARCHAR(MAX)



IF(''' + ISNULL( CAST(:ID AS VARCHAR(MAX)) , '''') + ''' = ''null'')
BEGIN
	 SET @ID = NULL
END
ELSE
BEGIN
	 SET @ID = CAST(' + :ID + ' AS INT)
END

SET @BD = ''' + :BD + '''
SET @TIPO = CAST(''' + ISNULL( :TIPO, '')  +''' AS INT)
SET @IDUSUARIO = CAST(''' + ISNULL( :IDUSUARIO, '')  +''' AS INT)
SET @IDPLANTILLA = CAST(''' + ISNULL(:IDPLANTILLA, '')  +''' AS INT)

SET @IDPROSPECTO = 0
SET @IDOPORTUNIDAD = 0
SET @IDVENTA = 0

IF(@ID IS NOT NULL)
BEGIN
IF(@TIPO = 1)
BEGIN 
	SELECT @DESTINATARIO = CORREO, @IDPROSPECTO = IDPROSPECTO FROM '+ :BD +'.DBO.PROSPECTOS WHERE IDPROSPECTO = @ID
	SET @IDPROSPECTO = @ID
END
ELSE IF(@TIPO = 2)
BEGIN 
	SELECT @DESTINATARIO = P.CORREO, @IDPROSPECTO = P.IDPROSPECTO FROM '+ :BD +'.DBO.OPORTUNIDADES O, '+ :BD +'.DBO.PROSPECTOS P WHERE O.IDPROSPECTO = P.IDPROSPECTO AND O.IDOPORTUNIDAD = @ID
	SET @IDOPORTUNIDAD = @ID
END
ELSE IF(@TIPO = 3)
BEGIN
	SELECT @DESTINATARIO = ISNULL(P.CORREO,''), @IDPROSPECTO = ISNULL(P.IDPROSPECTO,'') FROM '+ :BD +'.DBO.OPORTUNIDADES O, '+ :BD +'.DBO.PROSPECTOS P, '+ :BD +'.DBO.VENTAS V WHERE V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO AND V.IDVENTA = @ID
	SET @IDVENTA = @ID
END
 
EXEC '+ :BD +'.DBO.SP_ENVIA_PLANTILLA @IDUSUARIO, @IDPROSPECTO, @IDOPORTUNIDAD, @IDVENTA,@IDPLANTILLA, @DESTINATARIO, '''', '''',1
END

'
EXEC (@SQL)