//[bd|Text,idusuario|Text,idventa|Text,]
--SELECT

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @IDVENTA VARCHAR(1000)
SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))
SET @IDVENTA=CAST(ISNULL(:IDVENTA,0) AS VARCHAR(1000))

SET @EXECSQL = 'select CONVERT(VARCHAR,V.FECHAHORA,20) AS FECHAHORA, V.* from '+@BD+'.dbo.ventas V WITH (NOLOCK) '
SET @EXECSQL = @EXECSQL + 'where V.idusuario = '+@IDUSUARIO+' AND V.IDVENTA = '+@IDVENTA
EXEC(@EXECSQL)