//[idsuceso|Text,bd|Text,]
-- SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(1000)
DECLARE @IDSUCESOC VARCHAR(1000)
SET @IDSUCESOC = CAST(ISNULL(:IDSUCESO,'') AS VARCHAR(1000))
SET @BD=ISNULL(:BD,'')

SET @SQL='
DECLARE @IDSUCESO INT
IF(ISNUMERIC('+@IDSUCESOC+') = 1)
BEGIN
	 SET @IDSUCESO = '+@IDSUCESOC+'
END
ELSE
BEGIN
	 SELECT TOP 1 @IDSUCESO = IDSUCESO FROM '+@BD+'.DBO.USUARIOS_SUCESOS WHERE TEXTO LIKE '+@IDSUCESOC+' ORDER BY 1 DESC
END

 EXEC '+@BD+'.DBO.SP_OBTIENE_DATOS_NOTIFICACION @IDSUCESO
'
EXEC(@SQL)