//[bd|Untyped,idprospecto|Untyped,idoportunidad|Untyped,idrelacionado|Untyped,idusuario|Untyped,idseguimientocategoria|Untyped,tipo_seguimiento|Untyped,fechahora|Text,comentario|Text,sistema|Untyped,latitude|Text,longitude|Text,direccion|Text,idpeticion|Untyped,]

-- Query 1067

--SELECT

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDUSUARIO INT
DECLARE @IDSEGUIMIENTOCATEGORIA INT
DECLARE @TIPO_SEGUIMIENTO INT
DECLARE @FECHAHORA VARCHAR(512)
DECLARE @COMENTARIO VARCHAR(MAX)
DECLARE @SISTEMA INT
DECLARE @LATITUD VARCHAR(512)
DECLARE @LONGITUD VARCHAR(512)
DECLARE @DIRECCION VARCHAR(512)
DECLARE @IDPETICION VARCHAR(512)
DECLARE @IDRELACIONADO INT

SET @BD = '<#BD/>'

IF('<#IDPROSPECTO/>' = 'null')
BEGIN
	SET @IDPROSPECTO = 0
END
ELSE
BEGIN
	 SET @IDPROSPECTO = CAST('<#IDPROSPECTO/>' AS INT)
END

IF('<#IDOPORTUNIDAD/>' = 'null')
BEGIN
	SET @IDOPORTUNIDAD = 0
END
ELSE
BEGIN
	 SET @IDOPORTUNIDAD = CAST('<#IDOPORTUNIDAD/>' AS INT)
END

IF('<#IDRELACIONADO/>' = 'null')
BEGIN
	SET @IDRELACIONADO = 0
END
ELSE
BEGIN
	SET @IDRELACIONADO = CAST('<#IDRELACIONADO/>' AS INT)
END

SET @IDUSUARIO = CAST('<#IDUSUARIO/>' AS INT)
SET @IDSEGUIMIENTOCATEGORIA = CAST('<#IDSEGUIMIENTOCATEGORIA/>' AS INT)
SET @TIPO_SEGUIMIENTO = CAST('<#TIPO_SEGUIMIENTO/>' AS INT)

IF ((:FECHAHORA != '')AND(:FECHAHORA IS NOT NULL))
   SET @FECHAHORA = CONVERT(DATETIME,:FECHAHORA,20)
ELSE
	SET @FECHAHORA = ''
	
SET @COMENTARIO = ISNULL(REPLACE(:COMENTARIO,'''',''''''),'')
SET @SISTEMA = CAST('<#SISTEMA/>' AS INT)

SET @LATITUD = ISNULL(REPLACE(:LATITUDE,'''',''''''),'')
IF(@LATITUD = 'undefined')
	SET @LATITUD = ''

SET @LONGITUD = ISNULL(REPLACE(:LONGITUDE,'''',''''''),'')
IF(@LONGITUD = 'undefined')
	SET @LONGITUD = ''
	
SET @DIRECCION = ISNULL(REPLACE(:DIRECCION,'''',''''''),'')
IF(@DIRECCION = 'undefined')
	SET @DIRECCION = ''
	
SET @IDPETICION = ISNULL(REPLACE('<#IDPETICION/>','''',''''''),'')
IF(@IDPETICION = 'undefined')
	SET @IDPETICION = ''
	
     BEGIN TRY
	   BEGIN TRANSACTION
       SET DEADLOCK_PRIORITY HIGH
       EXEC <#BD/>.DBO.SP_INSERTA_PROSPECTO_SEGUIMIENTO_MV @IDPROSPECTO,@IDOPORTUNIDAD,@IDUSUARIO,@IDSEGUIMIENTOCATEGORIA,@TIPO_SEGUIMIENTO,@FECHAHORA,@COMENTARIO,@SISTEMA,@LATITUD,@LONGITUD,@DIRECCION,@IDRELACIONADO,@IDPETICION
	   COMMIT TRANSACTION
     END TRY
     BEGIN CATCH
	   ROLLBACK TRANSACTION
	   WAITFOR DELAY '00:00:02';
	   BEGIN TRY
	   BEGIN TRANSACTION
       SET DEADLOCK_PRIORITY low
       EXEC <#BD/>.DBO.SP_INSERTA_PROSPECTO_SEGUIMIENTO_MV @IDPROSPECTO,@IDOPORTUNIDAD,@IDUSUARIO,@IDSEGUIMIENTOCATEGORIA,@TIPO_SEGUIMIENTO,@FECHAHORA,@COMENTARIO,@SISTEMA,@LATITUD,@LONGITUD,@DIRECCION,@IDRELACIONADO,@IDPETICION 
	   COMMIT TRANSACTION
       END TRY   
	   BEGIN CATCH
	     ROLLBACK TRANSACTION
		 WAITFOR DELAY '00:00:02';
	     BEGIN TRANSACTION
	     SET DEADLOCK_PRIORITY low
         EXEC <#BD/>.DBO.SP_INSERTA_PROSPECTO_SEGUIMIENTO_MV @IDPROSPECTO,@IDOPORTUNIDAD,@IDUSUARIO,@IDSEGUIMIENTOCATEGORIA,@TIPO_SEGUIMIENTO,@FECHAHORA,@COMENTARIO,@SISTEMA,@LATITUD,@LONGITUD,@DIRECCION,@IDRELACIONADO,@IDPETICION
		 COMMIT TRANSACTION 
	    END CATCH  
     END CATCH