//[bd|Text,idempresa|Integer,fecha|Text,]
-- select
/*protegido*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(MAX)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @FECHA VARCHAR(100)

SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA = CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA = ISNULL(:FECHA,'')

SET @SQL='
SELECT IDINDUSTRIA,IDEMPRESA, SALESUP_CT.DBO.PreparaCadenaApp2(INDUSTRIA) AS INDUSTRIA, TKIND,TKM
FROM '+@BD+'.dbo.EMPRESAS_INDUSTRIAS WITH (NOLOCK) WHERE IDEMPRESA = '+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)
'

EXEC (@SQL)