//[bd|Text,idusuario|Text,idoportunidad|Text,]
--SELECT

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @CONCEPTO VARCHAR(MAX)
DECLARE @IDUSUARIO VARCHAR(512)
DECLARE @IDOPORTUNIDAD VARCHAR(512)

SET @BD = :BD
SET @IDUSUARIO = :IDUSUARIO
SET @IDOPORTUNIDAD = :IDOPORTUNIDAD



SET @EXECSQL = 'SELECT SALESUP_CT.dbo.PreparaCadenaJson(REPLACE(CONCEPTO,'''''''','''')) AS CONCEPTO,CONVERT(VARCHAR,FECHA_CIERRE,20) AS FECHA_CIERRE, CONVERT(VARCHAR,GANADA_FECHA,20) AS GANADA_FECHA, '
SET @EXECSQL = @EXECSQL + 'CONVERT(VARCHAR,PERDIDA_FECHA,20) AS PERDIDA_FECHA, SALESUP_CT.dbo.PreparaCadenaJson(PERDIDA_RAZON) AS PERDIDA_RAZON,CONVERT(VARCHAR,FECHAHORA,20) AS FECHAHORA, '
SET @EXECSQL = @EXECSQL + 'CONVERT(VARCHAR,FECHA_ULTIMOSEGUIMIENTO,20) AS FECHA_ULTIMOSEGUIMIENTO, * FROM '+@BD+'.dbo.OPORTUNIDADES WITH (NOLOCK) WHERE IDUSUARIO = CAST(''' +@IDUSUARIO +''' AS INT) AND IDOPORTUNIDAD = CAST(''' + :IDOPORTUNIDAD +''' AS INT) '
EXEC(@EXECSQL)
