//[bd|Text,fecha|Text,idusuario|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)

SET @SQL = '

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @FECHA DATETIME
DECLARE @YASINCRONIZADO INT

SET @BD = ''' + ISNULL(:BD,'') + '''
SET @FECHA = CONVERT(DATETIME,''' + ISNULL(:FECHA,'') +''',20)

IF(@FECHA = 0) 
BEGIN
	SET @YASINCRONIZADO = 0
END 
ELSE 
BEGIN 
	SET @YASINCRONIZADO = 1
END 

SELECT SALESUP_CT.DBO.PreparaCadenaApp2(RECORDATORIO) AS RECORDATORIO, CONVERT(VARCHAR,R.FECHAHORA,20) AS FECHAHORA,R.* 
FROM ' + ISNULL(:BD,'') + '.dbo.RECORDATORIOS R WITH (NOLOCK)
LEFT JOIN ' + ISNULL(:BD,'') + '.dbo.PROSPECTOS P WITH (NOLOCK) ON P.IDPROSPECTO = R.IDPROSPECTO AND P.DESCARTADO = 0 
LEFT JOIN ' + ISNULL(:BD,'') + '.dbo.OPORTUNIDADES O WITH (NOLOCK) ON O.IDUSUARIO = R.IDUSUARIO AND P.IDPROSPECTO = O.IDPROSPECTO AND O.PERDIDA = 0 AND O.IDOPORTUNIDAD = R.IDOPORTUNIDAD
LEFT JOIN ' + ISNULL(:BD,'') + '.dbo.PROSPECTOS_ASIGNADOS A WITH (NOLOCK) ON A.IDUSUARIO = R.IDUSUARIO AND A.ARCHIVADO = 0 AND A.IDPROSPECTO = R.IDPROSPECTO
WHERE R.IDUSUARIO = CAST(' + ISNULL(:IDUSUARIO,'') + ' AS INT) AND ((R.ULTIMAMODIFICACION >= @FECHA AND @YASINCRONIZADO > 0) OR (@YASINCRONIZADO = 0 AND R.COMPLETADO = 0))
' 
EXEC (@SQL)