//[idempresa|Integer,bd|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(1000) 
DECLARE @IDEMPRESA INT
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA = ISNULL(:IDEMPRESA,0)
SET @SQL='SELECT IDLINEA_PRODUCTO,IDEMPRESA,SALESUP_CT.DBO.PreparaCadenaApp2(LINEA_PRODUCTO) AS LINEA_PRODUCTO,COMISION, TK,TKM FROM '+@BD+'.dbo.EMPRESAS_LINEAS_PRODUCTO WITH (NOLOCK) WHERE IDEMPRESA ='+CAST(@IDEMPRESA AS VARCHAR(1000))
EXEC (@SQL)