//[fecha|Text,idusuario|Integer,bd|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
DECLARE @BD VARCHAR(100)
SET @BD=ISNULL(:BD,'')
SET @FECHA =  ISNULL(:FECHA,'')
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))

SET @SQL='
SELECT 
TS.IDTAREASEGUIMIENTO,TS.IDUSUARIO,TS.FECHAHORA,SALESUP_CT.DBO.PreparaCadenaApp2(TS.COMENTARIO) AS COMENTARIO,TS.IDTAREA
FROM '+@BD+'.dbo.TAREAS_SEGUIMIENTO TS WITH(NOLOCK) 
JOIN '+@BD+'.dbo.TAREAS T WITH(NOLOCK) ON T.idtarea = ts.idtarea 
JOIN '+@BD+'.dbo.USUARIOS U WITH(NOLOCK) ON U.IDUSUARIO = TS.IDUSUARIO 
WHERE TS.IDTAREA = T.IDTAREA and TS.ULTIMAMODIFICACION >= CONVERT(DATETIME, '''+@FECHA+''',20) AND 
((t.idrealizador = '+@IDUSUARIO+' and t.idiniciador != '+@IDUSUARIO+') or (t.idiniciador = '+@IDUSUARIO+' and t.idrealizador != '+@IDUSUARIO+')) 
'
EXEC (@SQL)