//[bd|Text,idempresa|Text,fecha|Text,]
-- select

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)

SET @BD = ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA=ISNULL(:FECHA,'')

SET @EXECSQL = 'SELECT COUNT(*) AS TOTAL, '+@IDEMPRESA+' AS IDEMPRESA,'''+@FECHA+''' AS FECHA, '''+@BD+''' AS BD FROM '+@BD+'.dbo.usuarios WITH(NOLOCK) where idempresa = '+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)'
EXEC(@EXECSQL)