//[bd|Text,idempresa|Text,fecha|Text,]
-- SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA=ISNULL(:FECHA, '')
SET @SQL='
SELECT IDEMPRESA,SALESUP_CT.DBO.PreparaCadenaApp2(COMPANIA) AS COMPANIA,ACTIVA,PAIS_DEFAULT,ESTADO_DEF,FECHA_ALTA,TIPO_LICENCIA,EXPIRACION,TELEFONO,OCULTAR_CERTEZAS_SINDESC 
FROM '+@BD+'.dbo.EMPRESAS WITH(NOLOCK) where idempresa = '+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)
'
EXEC (@SQL)