//[bd|Text,idempresa|Text,fecha|Text,]
--select

DECLARE @BD VARCHAR(512)
DECLARE @IDEMPRESA VARCHAR(512)
DECLARE @FECHA VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)

SET @BD        = :BD
SET @FECHA     = :FECHA
SET @IDEMPRESA = :IDEMPRESA

SET @EXECSQL = 'SELECT CONVERT(VARCHAR,US.FECHAHORA,20) AS FECHAHORA, US.*, PR.NOMBRE,PR.APELLIDOS,PR.ESOPORTUNIDAD,PR.ESCLIENTE, REPLACE(OP.CONCEPTO,'','','''') as CONCEPTO, OP.MONTO, OP.CERTEZA, OP.FECHA_CIERRE, OP.COMISION_MONTO, VT.MONTO AS MONTOVENTA, ' 
SET @EXECSQL = @EXECSQL + 'VT.COMISION, VT.REFERENCIA, VT.ANTICIPOS_MONTO, VT.ANTICIPOS_COMISION, VT.SALDO_COMISION, VT.SALDO_MONTO,OP.GANADA '
SET @EXECSQL = @EXECSQL + 'FROM '+@BD+'.dbo.PROSPECTOS PR WITH (NOLOCK), '+@BD+'.dbo.USUARIOS_SUCESOS US WITH (NOLOCK) '
SET @EXECSQL = @EXECSQL + 'LEFT JOIN '+@BD+'.dbo.OPORTUNIDADES OP WITH (NOLOCK) ON US.IDOPORTUNIDAD = OP.IDOPORTUNIDAD '
SET @EXECSQL = @EXECSQL + 'LEFT JOIN '+@BD+'.dbo.VENTAS VT WITH (NOLOCK) ON VT.IDOPORTUNIDAD = OP.IDOPORTUNIDAD '
SET @EXECSQL = @EXECSQL + 'WHERE PR.IDPROSPECTO = US.IDPROSPECTO '
SET @EXECSQL = @EXECSQL + 'AND US.IDUSUARIO IN (SELECT IDUSUARIO FROM '+@BD+'.dbo.USUARIOS WHERE IDEMPRESA = CAST(''' + @IDEMPRESA + ''' AS INT)) AND ((US.FECHAHORA between DATEADD(day, -1, getdate()) AND GETDATE()) '
SET @EXECSQL = @EXECSQL + 'AND (US.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''   + @FECHA +''',20)))'
EXEC(@EXECSQL)