//[fecha|Text,bd|Text,idusuario|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @FECHA VARCHAR(1000)
DECLARE @BD VARCHAR(1000)
DECLARE @IDUSUARIO VARCHAR(1000)
SET @FECHA = ISNULL(:FECHA,'')
SET @BD=ISNULL(:BD,'')
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))

SET @SQL='
select *,'''+@FECHA+''' AS FECHA,'''+@BD+''' AS BD from '+@BD+'.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) 
where ULTIMAMODIFICACION > =  CONVERT(DATETIME,'''+@FECHA+''',20) AND (IDUSUARIO = '+@IDUSUARIO+' or IDPROSPECTO in 
(select IDPROSPECTO from '+@BD+'.DBO.PROSPECTOS WITH(NOLOCK) where IDUSUARIO = '+@IDUSUARIO+'))
'
EXEC (@SQL)