//[bd|Text,idusuario|Integer,fecha|Text,]
--SELECT

DECLARE @BD VARCHAR(512)
DECLARE @EXECSQL VARCHAR(8000)
DECLARE @FECHA VARCHAR(1000)
DECLARE @IDUSUARIO VARCHAR(1000)
SET @FECHA=ISNULL(:FECHA,'')
SET @BD = ISNULL(:BD,'')
SET @IDUSUARIO=CAST(ISNULL(:IDUSUARIO, 0) AS VARCHAR(1000))

SET @EXECSQL = 'SELECT COUNT(*) AS TOTAL, '''+@FECHA+''' AS FECHA,'+@IDUSUARIO+' AS IDUSUARIO from '+@BD+'.dbo.ventas V WITH (NOLOCK),  '+@BD+'.dbo.ventas_COBROS VC WITH (NOLOCK)'
SET @EXECSQL = @EXECSQL + 'where idusuario = '+@IDUSUARIO+' AND VC.IDVENTA = V.IDVENTA AND VC.ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)'
EXEC(@EXECSQL)