//[bd|Text,idempresa|Text,fecha|Text,]
-- select
/*PROTEGIDO*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
DECLARE @IDEMPRESA VARCHAR(1000)
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA=ISNULL(:FECHA,'')
SET @SQL='
SELECT IDCOMPANIAGRUPO,IDEMPRESA,SALESUP_CT.DBO.PreparaCadenaApp2(COMPANIAGRUPO) AS COMPANIAGRUPO, TKCG, TKM 
FROM '+@BD+'.dbo.COMPANIAS_GRUPOS WITH (NOLOCK) WHERE IDEMPRESA = '+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20)
'

EXEC (@SQL)
