//[idempresa|Integer,fecha|Text,bd|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(512)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
SET @BD=ISNULL(:BD,'')
SET @IDEMPRESA=CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @FECHA = ISNULL(:FECHA,'')

SET @SQL='
SELECT ULTIMAMODIFICACION,IDCOMPANIA,IDEMPRESA, IDINDUSTRIA,SALESUP_CT.DBO.PreparaCadenaApp2(EMPRESA) AS EMPRESA,URL,TELEFONOCORPORATIVO, SALESUP_CT.DBO.PreparaCadenaApp2(DIRECCION1) AS DIRECCION1,
SALESUP_CT.DBO.PreparaCadenaApp2(DIRECCION2) AS DIRECCION2, SALESUP_CT.DBO.PreparaCadenaApp2(CIUDAD)  
AS CIUDAD, SALESUP_CT.DBO.PreparaCadenaApp2(CODIGOPOSTAL) AS CODIGOPOSTAL, IDESTADO, IDPAIS, NEMPLEADOS, IDCOMPANIAGRUPO , TKCOM,TKM 
FROM '+@BD+'.dbo.COMPANIAS WITH (NOLOCK) WHERE IDEMPRESA ='+@IDEMPRESA+' AND ULTIMAMODIFICACION >= CONVERT(DATETIME,'''+@FECHA+''',20) 
'
EXEC (@SQL)