//[id|Text,tipo|Text,idusuario|Text,idplantilla|Text,idempresa|Text,bd|Text,]
--SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @BD VARCHAR(MAX)
SET @BD=ISNULL(:BD,'')
SET @SQL ='
DECLARE @CORREOPROSPECTO VARCHAR(255)
DECLARE @CORREOENVIA VARCHAR(255)
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @ID INT
DECLARE @TIPO INT
DECLARE @IDPLANTILLA INT
DECLARE @IDVENTA INT

IF('''+ISNULL(:ID,'')+''' = ''null'')
BEGIN
	 SET @ID = NULL
END
ELSE
BEGIN
	 SET @ID = CAST('''+ISNULL(:ID,'')+''' AS INT)
END

SET @TIPO = CAST('''+ISNULL(:TIPO,'')+''' AS INT)
SET @IDUSUARIO = CAST('''+ISNULL(:IDUSUARIO,'')+''' AS INT)
SET @IDPLANTILLA = CAST('''+ISNULL(:IDPLANTILLA,'')+''' AS INT)
SET @IDEMPRESA = CAST('''+ISNULL(:IDEMPRESA,'')+''' AS INT)

IF(@ID IS NOT NULL)
BEGIN
IF(@TIPO = 1)
BEGIN
	SET @IDPROSPECTO = @ID 
	SET @IDOPORTUNIDAD = NULL
END
ELSE IF(@TIPO = 2)
BEGIN
	SET @IDOPORTUNIDAD = @ID
	SELECT @IDPROSPECTO = IDPROSPECTO FROM '+@BD+'.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
END
ELSE IF(@TIPO = 3)
BEGIN
	SET @IDVENTA = @ID
	SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD FROM '+@BD+'.DBO.VENTAS WHERE IDVENTA = @IDVENTA
	SELECT @IDPROSPECTO = IDPROSPECTO FROM '+@BD+'.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
END

SELECT @CORREOPROSPECTO = CORREO FROM '+@BD+'.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
SELECT @CORREOENVIA = EMAIL FROM '+@BD+'.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO


SELECT '+@BD+'.dbo.ObtieneCuerpoAutoresponder(CUERPO,@IDPROSPECTO,@IDUSUARIO,@IDEMPRESA,@IDOPORTUNIDAD) AS CUERPO, '+@BD+'.dbo.ObtieneCuerpoAutoresponder(ASUNTO,@IDPROSPECTO,@IDUSUARIO,@IDEMPRESA,@IDOPORTUNIDAD) AS ASUNTO, @CORREOPROSPECTO AS CORREO, @CORREOENVIA AS DE, @IDPROSPECTO AS IDPROSPECTO,@IDUSUARIO AS IDUSUARIO,@IDEMPRESA AS IDEMPRESA,@IDOPORTUNIDAD AS IDOPORTUNIDAD, @IDPLANTILLA AS IDPLANTILLA, @TIPO AS TIPO, '''+@BD+''' AS BD
FROM '+@BD+'.DBO.USUARIOS_PLANTILLAS
WHERE IDPLANTILLA = @IDPLANTILLA
END
ELSE
BEGIN
	 SELECT '''' AS CUERPO, '''' AS ASUNTO, '''' AS CORREO, @CORREOENVIA AS DE, @IDPROSPECTO AS IDPROSPECTO,@IDUSUARIO AS IDUSUARIO,@IDEMPRESA AS IDEMPRESA,@IDOPORTUNIDAD AS IDOPORTUNIDAD, @IDPLANTILLA AS IDPLANTILLA, @TIPO AS TIPO, '''+@BD+''' AS BD
END
'
EXEC (@SQL)