//[SESSION.DB|Untyped,TKREC|Text,]

--DELETE
DECLARE @TKREC VARCHAR(MAX)

SET @TKREC = CAST(ISNULL(:TKREC,'')AS VARCHAR(MAX))
IF (@TKREC != '') DELETE FROM <#SESSION.DB/>.DBO.RECORDATORIOS WHERE TKREC = @TKREC