//[session.idempresa|Untyped,idprospecto|Text,idoportunidad|Numeric,tko|Text,tkp|Text,session.db|Untyped,]
--select
DECLARE @ESCLIENTE INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDEMPRESA INT
DECLARE @IDPROSPECTO INT
DECLARE @TKP VARCHAR(256) 
DECLARE @TKO VARCHAR(256) 
DECLARE @IDFASEACTUAL INT 
DECLARE @ESOPORTUNIDAD INT 


SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO, 0) 
SET @IDOPORTUNIDAD=ISNULL(:IDOPORTUNIDAD, 0) 



SET @TKO=ISNULL(:TKO, '') 
SET @TKP = ISNULL(:TKP,'') 

IF @TKO != '' BEGIN	 SET @IDOPORTUNIDAD = <#SESSION.DB/>.DBO.obtieneIdOportunidad(@TKO) END
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END

SELECT @ESCLIENTE = ESCLIENTE,@ESOPORTUNIDAD=ESOPORTUNIDAD, @IDFASEACTUAL=ISNULL(IDFASE,0) FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDEMPRESA=@IDEMPRESA AND IDPROSPECTO = @IDPROSPECTO

IF (@ESOPORTUNIDAD=1 AND  @ESCLIENTE=0)
BEGIN 
	SELECT @IDFASEACTUAL=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDPROSPECTO=@IDPROSPECTO
  SELECT *, @IDOPORTUNIDAD AS IDOPORTUNIDAD, SALESUP_CT.DBO.ESCANALIZADO(TK, TKM) AS ESCANALIZADO, (CASE WHEN @IDFASEACTUAL=IDFASE THEN 1 ELSE 0 END) AS SELECCIONADO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDEMPRESA=@IDEMPRESA   ORDER BY ORDEN
END
ELSE 
BEGIN 

  IF @ESCLIENTE=1
	BEGIN
	  SELECT *, @IDOPORTUNIDAD AS IDOPORTUNIDAD, SALESUP_CT.DBO.ESCANALIZADO(TK, TKM) AS ESCANALIZADO,(CASE WHEN @IDFASEACTUAL=IDFASE THEN 1 ELSE 0 END) AS SELECCIONADO FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA AND  FASECLIENTE=1  ORDER BY ORDEN
	END 
	ELSE
	begin
  	  SELECT *, @IDOPORTUNIDAD AS IDOPORTUNIDAD, SALESUP_CT.DBO.ESCANALIZADO(TK, TKM) AS ESCANALIZADO, (CASE WHEN @IDFASEACTUAL=IDFASE THEN 1 ELSE 0 END) AS SELECCIONADO FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=@IDEMPRESA AND  FASECLIENTE=0  ORDER BY ORDEN
	end
END	
	

