//[session.gmt|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--select
declare @gmt int
declare @idusuario int
DECLARE @HORAREAL DATETIME
DECLARE @MILISEGUNDOS INT, @AVISAR INT, @MILISEGUNDOS_CITAS INT
DECLARE  @offset INT

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT )

SELECT @GMT = DIFERENCIA FROM V_GMT WHERE GMT= @GMT

SELECT @offset = SALESUP_CT.DBO.OFFSET(GETDATE())
SET @HORAREAL = DATEADD(hh, -1*@offset+(@gmt), GETDATE())
 

SELECT @MILISEGUNDOS = DATEDIFF(ms, @HORAREAL, FECHAHORA)  
FROM <#SESSION.DB/>.DBO.RECORDATORIOS R WITH(NOLOCK)
JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON U.IDUSUARIO = R.IDUSUARIO
JOIN <#SESSION.DB/>.DBO.V_GMT G  WITH(NOLOCK) ON G.GMT = U.GMT
WHERE 
  COMPLETADO = 0 AND 
  U.IDUSUARIO = <#SESSION.IDUSUARIO/> AND  
   R.FECHAHORA  <= DATEADD(ms, 1800000 , @HORAREAL) AND 
   R.FECHAHORA  >= DATEADD(ms, -60000 ,  @HORAREAL)   



SELECT @MILISEGUNDOS_CITAS = DATEDIFF(ms, @HORAREAL, C.FECHA_INICIO)
FROM <#SESSION.DB/>.DBO.CITAS C WITH(NOLOCK)
JOIN <#SESSION.DB/>.DBO.CITAS_INVITADOS CI WITH(NOLOCK) ON CI.idcita = C.IDCITA
JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON U.IDUSUARIO = CI.IDPERSONA
JOIN <#SESSION.DB/>.DBO.V_GMT G  WITH(NOLOCK) ON G.GMT = U.GMT
WHERE
	 C.ACTIVO = 1 AND
	 CI.idpersona = <#SESSION.IDUSUARIO/> AND
	 CI.tipopersona = 2 AND
	 C.FECHA_INICIO <= DATEADD(ms, 1800000 , @HORAREAL) AND 
     C.FECHA_INICIO >= DATEADD(ms, -60000 ,  @HORAREAL) 

SET @MILISEGUNDOS = CASE WHEN @MILISEGUNDOS IS NOT NULL AND @MILISEGUNDOS_CITAS IS NULL THEN @MILISEGUNDOS
				   		 WHEN @MILISEGUNDOS IS NULL 	AND @MILISEGUNDOS_CITAS IS NOT NULL THEN @MILISEGUNDOS_CITAS
						 WHEN @MILISEGUNDOS IS NOT NULL AND @MILISEGUNDOS_CITAS IS NOT NULL THEN (CASE WHEN @MILISEGUNDOS > @MILISEGUNDOS_CITAS THEN @MILISEGUNDOS ELSE @MILISEGUNDOS_CITAS END )
						 WHEN @MILISEGUNDOS IS NULL 	AND @MILISEGUNDOS_CITAS IS NULL THEN 300001 
					END
						 
 
SELECT @AVISAR = COUNT(*) 
FROM <#SESSION.DB/>.DBO.USUARIOS WITH(NOLOCK) 
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> 
AND DATEADD(ms, 60000,ISNULL(ULTIMOAVISO, GETDATE()-1)) < GETDATE()

SELECT @MILISEGUNDOS AS Diferencia, @AVISAR AS Avisar, @HORAREAL AS HORAREAL, @OFFSET AS OFFSET, @GMT AS GMT, @MILISEGUNDOS_CITAS AS MA