//[session.db|Untyped,session.idusuario|Untyped,]
SELECT COUNT(*) AS Avisar
FROM <#SESSION.DB/>.DBO.USUARIOS WITH(NOLOCK) 
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> 
AND DATEADD(ms, 60000,ISNULL(ULTIMOAVISO, GETDATE()-1)) < GETDATE()