//[idr|Integer,posponer|Integer,com|Text,session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--update
/*PROTEGIDO*/
DECLARE @IDRECORDATORIO INT, @POSPONER INT, @IDUSUARIO INT, @IDSEGUIMIENTO INT, @IDEMPRESA INT, @IDOPORTUNIDAD INT, @IDPROSPECTO INT
DECLARE @FECHAACTUAL DATETIME , @FECHANUEVA DATETIME
DECLARE @COMENTARIO VARCHAR(MAX)

SET @IDRECORDATORIO = ISNULL(:IDR,0) 
SET @POSPONER = ISNULL(:POSPONER,0) 
SET @COMENTARIO = :COM

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT @FECHAACTUAL = R.FECHAHORA, @IDPROSPECTO = R.IDPROSPECTO, @IDOPORTUNIDAD = R.IDOPORTUNIDAD 
FROM <#SESSION.DB/>.DBO.RECORDATORIOS R WHERE R.IDRECORDATORIO = @IDRECORDATORIO


IF @POSPONER = 1 BEGIN SET @FECHANUEVA = DATEADD(mi, 15, @FECHAACTUAL) END
IF @POSPONER = 2 BEGIN SET @FECHANUEVA = DATEADD(mi, 30, @FECHAACTUAL) END
IF @POSPONER = 3 BEGIN SET @FECHANUEVA = DATEADD(mi, 45, @FECHAACTUAL) END
IF @POSPONER = 4 BEGIN SET @FECHANUEVA = DATEADD(hh, 1 , @FECHAACTUAL) END
IF @POSPONER = 5 BEGIN SET @FECHANUEVA = DATEADD(hh, 2 , @FECHAACTUAL) END
IF @POSPONER = 6 BEGIN SET @FECHANUEVA = DATEADD(hh, 4 , @FECHAACTUAL) END
IF @POSPONER = 7 BEGIN SET @FECHANUEVA = DATEADD(hh, 6 , @FECHAACTUAL) END
IF @POSPONER = 8 BEGIN SET @FECHANUEVA = DATEADD(hh, 12, @FECHAACTUAL) END
IF @POSPONER = 9 BEGIN SET @FECHANUEVA = DATEADD(dd, 1 , @FECHAACTUAL) END

UPDATE <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK) SET FECHAHORA = @FECHANUEVA WHERE IDRECORDATORIO = @IDRECORDATORIO


IF LEN(@COMENTARIO) > 1
	 BEGIN
		  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, COMENTARIO)
		  VALUES (@IDPROSPECTO, @IDOPORTUNIDAD, @IDUSUARIO, @COMENTARIO)
		  
		  SELECT TOP 1 @IDSEGUIMIENTO = IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(NOLOCK)
		  WHERE IDPROSPECTO = @IDPROSPECTO AND IDOPORTUNIDAD = @IDOPORTUNIDAD AND IDUSUARIO = @IDUSUARIO ORDER BY IDSEGUIMIENTO DESC
		  
		  IF @IDOPORTUNIDAD IS NOT NULL
		  BEGIN
		  	   UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET FECHA_ULTIMOSEGUIMIENTO = GETDATE(), IDULTIMOSEGUIMIENTO = @IDSEGUIMIENTO WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
			   EXEC <#SESSION.DB/>.DBO.SP_PROXIMORECORDATORIO_OPORTUNIDAD @IDOPORTUNIDAD
		  END
		  ELSE
		  BEGIN
		  	   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET FECHA_ULTIMOSEGUIMIENTO = GETDATE(), IDULTIMOSEGUIMIENTO = @IDSEGUIMIENTO WHERE IDPROSPECTO = @IDPROSPECTO
		  END
		  
		  DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
		  INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES WITH(ROWLOCK) (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE() )

	 END
