//[session.idusuario|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDUSUARIO INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT )

SELECT 
   (CASE 
   		 WHEN P.ESCLIENTE = 0 THEN 'prospecto'
		 WHEN P.ESCLIENTE = 1 THEN 'cliente'
   END) AS FASE,
   P.TKP, U.TKU,U.NOMBRE + ' ' + ISNULL(U.APELLIDOS,'') + ' (' + ISNULL(REPLACE(U.INICIALES, ' ',''),'') + ')' AS USUARIO,
   P.NOMBRE + ' ' + ISNULL(P.APELLIDOS,'')  AS PROSPECTO,C.EMPRESA,C.TKCOM
FROM 
   <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.COMPANIAS C
WHERE 
    P.APROBACIONESTADO = 1 
    AND U.IDUSUARIO = P.IDUSUARIO 
    AND C.IDCOMPANIA = P.IDCOMPANIA 
    AND C.IDUSUARIO = @IDUSUARIO