//[idrecordatorio|Integer,idprospecto|Integer,comentario|Text,session.idempresa|Untyped,session.convertcode|Untyped,session.idusuario|Untyped,session.nivel|Untyped,idfase|Integer,cierraRecordatorio|Integer,recordatorio|Text,idpeticion|Text,fecharecordatorio|Text,horarecordatorio|Text,duracionllamada|Integer,tkp|Text,session.db|Untyped,tkrec|Text,]
-- INSERT

DECLARE @IDVENTA INT
DECLARE @TOTAL INT, @DUENIO INT, @IDFASE INT
DECLARE @idoportunidad INT, @idprospecto INT, @IDSEGUIMIENTO INT, @IDUSUARIOSESSION INT
DECLARE @IDRECORDATORIO INT, @IDEMPRESA INT, @CONVERTCODE INT, @NIVEL INT
DECLARE @COMENTARIO VARCHAR(MAX), @RECORDATORIO VARCHAR(MAX), @IDPETICION VARCHAR(MAX), @TKP VARCHAR(MAX)
DECLARE @TKREC VARCHAR(64)
DECLARE @FECHARECORDATORIO VARCHAR(1000)
DECLARE @HORARECORDATORIO VARCHAR(1000)
DECLARE @FECHA VARCHAR(1000)
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME
DECLARE @DURACIONLLAMADA INT
DECLARE @TIPO_SEGUIMIENTO INT
DECLARE @CIERRA_REC INT


SET @FECHAHOY = GETDATE()

SET @IDRECORDATORIO = ISNULL(:IDRECORDATORIO,0)
SET @idprospecto = ISNULL(:IDPROSPECTO,0) 
SET @idoportunidad=0
SET @COMENTARIO = LTRIM(:COMENTARIO)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @IDUSUARIOSESSION = <#SESSION.IDUSUARIO/>
SET @NIVEL = <#SESSION.NIVEL/>
SET @IDFASE = ISNULL(:IDFASE,0)
SET @RECORDATORIO = :RECORDATORIO
SET @IDPETICION = ISNULL(:IDPETICION,'')
SET @CIERRA_REC = CAST(ISNULL(:cierraRecordatorio,1)AS INT)
SET @FECHARECORDATORIO = ISNULL(:FECHARECORDATORIO,'')
SET @HORARECORDATORIO = ISNULL(:HORARECORDATORIO,'')
SET @FECHA = @FECHARECORDATORIO+' '+@HORARECORDATORIO
SET @DURACIONLLAMADA =ISNULL(:DURACIONLLAMADA, 0 )
SET @TIPO_SEGUIMIENTO=0

IF @DURACIONLLAMADA != 0
BEGIN
SET @TIPO_SEGUIMIENTO=8
END

SET @TKP = ISNULL(:TKP,'')
IF @TKP != ''
BEGIN
	 SELECT @idprospecto = P.IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) WHERE P.TKP = @TKP
END

SET @TKREC = ISNULL(:TKREC,'')
IF @TKREC != '' BEGIN SELECT @IDRECORDATORIO = IDRECORDATORIO FROM <#SESSION.DB/>.DBO.RECORDATORIOS WHERE TKREC = @TKREC END


IF( (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE FECHAHORA > GETDATE()-1 AND LEN(@IDPETICION)=25
 AND     IDPETICION !='' AND IDPETICION = @IDPETICION) = 0)
BEGIN
 

IF (@IDRECORDATORIO>0)
  select @idoportunidad=idoportunidad from <#SESSION.DB/>.DBO.recordatorios WITH(NOLOCK) where idrecordatorio = @IDRECORDATORIO

IF (@idprospecto>0)
BEGIN
IF LEN(@COMENTARIO) > 0
begin
  IF (@idoportunidad > 0)
  BEGIN
    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, COMENTARIO, IDOPORTUNIDAD, IDPETICION, DURACION, TIPO_SEGUIMIENTO )
    VALUES 
    (@idprospecto, @IDUSUARIOSESSION, @COMENTARIO, @idoportunidad, @IDPETICION, @DURACIONLLAMADA, @TIPO_SEGUIMIENTO )
 	
	SELECT TOP 1 @IDSEGUIMIENTO = IDSEGUIMIENTO from <#SESSION.DB/>.DBO.prospectos_seguimiento WITH(NOLOCK) where idprospecto = @IDPROSPECTO AND @IDOPORTUNIDAD = @idoportunidad ORDER BY IDSEGUIMIENTO DESC
  
  SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) WHERE IDPROSPECTO = @idprospecto
  
  SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @idprospecto
  
  IF (@NIVEL = 1 AND @TOTAL <= 1 AND @IDUSUARIOSESSION <> @DUENIO)
  BEGIN
     EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_SEGUIMIENTO @idprospecto, @IDUSUARIOSESSION, @IDEMPRESA, @COMENTARIO
  END
  
   EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES @IDUSUARIOSESSION, 10, @idprospecto, @idoportunidad, @CONVERTCODE, '', @IDSEGUIMIENTO
  END
  ELSE
  BEGIN 
    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, COMENTARIO, IDPETICION, DURACION, TIPO_SEGUIMIENTO)
    VALUES (@idprospecto, @IDUSUARIOSESSION, @COMENTARIO, @IDPETICION, @DURACIONLLAMADA, @TIPO_SEGUIMIENTO)
	
	SELECT TOP 1 @IDSEGUIMIENTO = IDSEGUIMIENTO from <#SESSION.DB/>.DBO.prospectos_seguimiento WITH(NOLOCK) where idprospecto = @IDPROSPECTO ORDER BY IDSEGUIMIENTO DESC
  
    SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) WHERE IDPROSPECTO = @idprospecto
  
    SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @idprospecto
  
  IF (@NIVEL = 1 AND @TOTAL <= 1 AND @IDUSUARIOSESSION <> @DUENIO)
  BEGIN
     EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_SEGUIMIENTO @idprospecto, @IDUSUARIOSESSION, @IDEMPRESA, @COMENTARIO
  END
  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIOSESSION,7, @idprospecto,@CONVERTCODE, '',@IDSEGUIMIENTO
  END

end

--SET @FECHAREC = CONVERT(DATETIME,@FECHA,@CONVERTCODE)

IF LEN(@RECORDATORIO) > 0 
BEGIN 
  UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMOAVISO = CONVERT(DATETIME,GetDate()-1,@CONVERTCODE) WHERE IDUSUARIO = @IDUSUARIOSESSION
  IF (@idoportunidad > 0)
  BEGIN
    INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO, IDOPORTUNIDAD)
    VALUES 
    (@idprospecto, @IDUSUARIOSESSION,CONVERT(DATETIME,@FECHA,@CONVERTCODE), @RECORDATORIO,@idoportunidad )
  
    EXEC <#SESSION.DB/>.DBO.SP_PROXIMORECORDATORIO_OPORTUNIDAD @idoportunidad 
  
  END
  ELSE
  BEGIN 
    INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO)
      VALUES 
  (@idprospecto, @IDUSUARIOSESSION,CONVERT(DATETIME,@FECHA,@CONVERTCODE), @RECORDATORIO)
  END
END

 DECLARE @IDUSUARIO INT

 
 DECLARE  @REASIGNADO INT
 DECLARE @OLD_FASE INT
 SELECT @REASIGNADO = REASIGNADO, @IDUSUARIO = IDUSUARIO, @OLD_FASE=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @idprospecto

   
 DECLARE @ESCLIENTE INT
 DECLARE @FASETXT VARCHAR(1000)
 SET @FASETXT=''
 IF  (@IDUSUARIOSESSION = @IDUSUARIO)   SET @REASIGNADO = 0

  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET
     REASIGNADO = @REASIGNADO  
   WHERE
     IDPROSPECTO = @idprospecto

-- se activan las acciones de las fases
IF (@idoportunidad = 0) BEGIN
  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET IDFASE = @IDFASE, REASIGNADO = @REASIGNADO, @ESCLIENTE=ESCLIENTE    WHERE  IDPROSPECTO = @idprospecto
END
ELSE BEGIN
  DECLARE @HAYFASE INT
  Select @HAYFASE=count(*) from <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WITH(NOLOCK) where IDFASE=@IDFASE AND IDEMPRESA=@IDEMPRESA
  IF @HAYFASE>0 BEGIN
    SELECT @OLD_FASE=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK) WHERE IDOPORTUNIDAD = @idoportunidad
    UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES SET IDFASE = @IDFASE  WHERE  IDOPORTUNIDAD = @idoportunidad
  END
  ELSE BEGIN
    UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET IDFASE = @IDFASE, REASIGNADO = @REASIGNADO  WHERE  IDPROSPECTO = @idprospecto 
  END
  IF @OLD_FASE<>@IDFASE BEGIN
    EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @IDFASE,@idprospecto,@idoportunidad 
    IF (@idoportunidad IS NOT NULL) BEGIN
      SELECT @FASETXT=' - '+ISNULL(FASE,'') FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDFASE=@IDFASE AND IDEMPRESA=@IDEMPRESA
      EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES @IDUSUARIOSESSION,21,@idprospecto,@idoportunidad,@CONVERTCODE, @FASETXT,''
    END
    ELSE BEGIN 
      SELECT @FASETXT=' - '+ISNULL(FASE,'') FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE=@IDFASE AND IDEMPRESA=@IDEMPRESA
      SELECT @ESCLIENTE = ESCLIENTE FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @idprospecto
      IF @ESCLIENTE=0 BEGIN
        EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIOSESSION,23,@idprospecto,@CONVERTCODE, @FASETXT,''
      END
      ELSE BEGIN
        EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIOSESSION,22,@idprospecto,@CONVERTCODE, @FASETXT, ''
      END
    END
  END
END
     
     
     
--inserta el ultimo seguimiento

IF LEN(@COMENTARIO) > 0
begin
  SELECT TOP 1 @IDSEGUIMIENTO= IDSEGUIMIENTO from <#SESSION.DB/>.DBO.prospectos_seguimiento WITH(NOLOCK) where idprospecto = @idprospecto  ORDER BY IDSEGUIMIENTO DESC
  IF (@idoportunidad > 0)
       UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET 
       FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,GetDate(),@CONVERTCODE),
       IDULTIMOSEGUIMIENTO=@IDSEGUIMIENTO
       WHERE
       IDOPORTUNIDAD = @idoportunidad
   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET 
   FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,GetDate(),@CONVERTCODE),
   IDULTIMOSEGUIMIENTO=@IDSEGUIMIENTO
   WHERE
   IDPROSPECTO = @idprospecto
    
end
     
   
  
-- Marca un recordatorio previo como realizado
IF @IDRECORDATORIO > 0 AND (@RECORDATORIO IS NOT NULL  OR @RECORDATORIO!='')
BEGIN
  UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMOAVISO = CONVERT(DATETIME,GetDate()-1,@CONVERTCODE) WHERE IDUSUARIO = @IDUSUARIOSESSION
  IF(@CIERRA_REC = 1) BEGIN
    UPDATE <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK) SET COMPLETADO = 1 WHERE IDRECORDATORIO = @IDRECORDATORIO
  END
END  
  

END -- del validador de IDPETICION
  ELSE 
  BEGIN
    INSERT INTO SALESUP_CT.dbo.LOG(IDU, IDP, IDO, TEXTO) VALUES ('<#SESSION.IDUSUARIO/>', @idprospecto, '', 'Seguimiento varios')
    SELECT TOP 1 @IDVENTA=IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK) WHERE 
     IDPROSPECTO = @idprospecto AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD ORDER BY IDVENTA DESC
    SELECT @IDVENTA AS AIDVENTA  
  END
END

SET @P = CAST(@idprospecto AS VARCHAR(MAX))
EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1
