//[session.gmt|Untyped,session.db|Untyped,session.idusuario|Untyped,]
--SELECT 
/*PROTEGIDO*/

DECLARE @GMT INT
DECLARE  @offset INT
DECLARE @HORAREAL DATETIME

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SELECT @GMT = DIFERENCIA FROM V_GMT WHERE GMT= @GMT

SELECT @offset = SALESUP_CT.DBO.OFFSET(GETDATE())
SET @HORAREAL = DATEADD(hh, -1*@offset+(@gmt), GETDATE())

SELECT GETDATE(),*,<#SESSION.DB/>.DBO.GETONLYTIME(R.FECHAHORA) as REC_HR 
FROM 
  <#SESSION.DB/>.DBO.RECORDATORIOS R WITH(NOLOCK) LEFT JOIN 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) ON R.IDPROSPECTO = P.IDPROSPECTO
  WHERE
   R.COMPLETADO=0 AND R.IDUSUARIO=<#SESSION.IDUSUARIO/> AND
   R.FECHAHORA  <= DATEADD(ms, 1800000 , @HORAREAL) AND 
   R.FECHAHORA  >= DATEADD(ms, -60000 ,  @HORAREAL)
   
  --DATEADD(hh, (6+@GMT)*-1, R.FECHAHORA)<= DATEADD(ms, 1800000 ,GETDATE()) 
--  AND  DATEADD(hh, (6+@GMT)*-1, R.FECHAHORA) >= DATEADD(ms, -60000 ,GETDATE())   



