//[session.db|Untyped,session.idusuario|Untyped,idrec|Integer,]
--UPDATE
/*PROTEGIDO*/

UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMOAVISO = GETDATE() WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>

UPDATE <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK) SET AVISADO = 1 WHERE IDRECORDATORIO = isnull(:IDREC,0)AND DATEDIFF(ms, GETDATE(),FECHAHORA )<=90000