//[session.db|Untyped,session.idempresa|Untyped,]

SELECT 
CASE WHEN(IDPAIS = 'MX') THEN 16 ELSE 0 END AS IMPUESTO_REAL,
16 AS IMPUESTO,
* 
  FROM <#SESSION.DB/>.dbo.EMPRESAS E 
  LEFT JOIN CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION F ON E.IDEMPRESA = F.IDEMPRESA and f.idproducto=1 
--  LEFT JOIN ESTADOS_IMPUESTOS I ON F.IDESTADO = I.IDESTADO AND F.IDPAIS = I.IDPAIS
  WHERE E.IDEMPRESA = <#SESSION.IDEMPRESA/>
