//[session.db|Untyped,session.idempresa|Untyped,e|Integer,s|Currency,i|Currency,m|Currency,f|Numeric,u|Integer,t_bu|Currency,t_f|Integer,t_nom|Text,t_num|Text,t_mes|Text,t_a|Text,t_c|Text,t_t|Integer,]
--update
/*PROTEGIDO*/
DECLARE @IDEMPRESA INT = ISNULL(:E,0)
DECLARE @S MONEY = ISNULL(:S,0)
DECLARE @I MONEY = ISNULL(:I,0)
DECLARE @M MONEY = ISNULL(:M,0)
DECLARE @F FLOAT = ISNULL(:F,0)
DECLARE @U INT = ISNULL(:U,0)
DECLARE @T_BU MONEY = ISNULL(:T_BU,0)
DECLARE @T_F INT = ISNULL(:T_F,0)
DECLARE @T_NOM VARCHAR(256) = ISNULL(:T_NOM,'')
DECLARE @T_NUM VARCHAR(256) = ISNULL(:T_NUM,'')
DECLARE @T_MES VARCHAR(256) = ISNULL(:T_MES,'')
DECLARE @T_A VARCHAR(256) = ISNULL(:T_A,'')
DECLARE @T_T INT = ISNULL(:T_T,0)
DECLARE @T_C VARCHAR(256) = ISNULL(:T_C,0)

DECLARE @IDDISTRIBUIDOR INT
SELECT @IDDISTRIBUIDOR  = IDDISTRIBUIDOR FROM <#SESSION.DB/>.dbo.EMPRESAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
DELETE FROM CARRITO  WHERE IDEMPRESA = @IDEMPRESA
INSERT INTO CARRITO (IDEMPRESA,FECHA, SUBTOTAL, IMPUESTOS, MONTO, FRECUENCIA, USUARIOS, TIPO, IDDISTRIBUIDOR,BONIFICACION)
VALUES (@IDEMPRESA, GETDATE(), @S, @I, @M,@F, @U, 'S', @IDDISTRIBUIDOR,@T_BU)

 
  UPDATE  EMPRESA_DATOS_FACTURACION SET
    FORMA_PAGO = @T_F, 
    TARJETA_NOMBRE = @T_NOM/>, 
    TARJETA_NUMERO = @T_NUM, 
    TARJETA_MES = @T_MES/>, 
    TARJETA_ANNIO = @T_A, 
    TARJETA_TIPO = @T_T, 
    TARJETA_CODIGO = @T_C
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> 
   