//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 
DECLARE @FECHAHOY VARCHAR(10) 
DECLARE @EXPIRACION VARCHAR(10) 
DECLARE @DIASAPAGAR INT 


SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'

SELECT @EXPIRACION=CONVERT(VARCHAR, <#SESSION.DB/>.DBO.GETONLYDATE(EXPIRACION) , 103) FROM  <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA=@IDEMPRESA
SET @FECHAHOY=CONVERT(VARCHAR,<#SESSION.DB/>.DBO.GETONLYDATE(GETDATE()),103)
SELECT @DIASAPAGAR=SALESUP_CT.DBO.DIASENTREFECHAS(@FECHAHOY,@EXPIRACION)

SELECT E.IDVERSION, FREC, MAX_USUARIOS, PAIS_DEFAULT, TIPO_LICENCIA, EXPIRACION, MAX_USUARIOS, FREC, MONTO, 
ULTIMAMODIFICACION,E.IDVERSION,  L.IDVERSION , L.VERSION ,
 CASE WHEN PAIS_DEFAULT='MX' THEN 
    dbo.OBTEN_MONTO_LICENCIA(1,E.IDVERSION,1,FREC,0)/FREC 
  ELSE 
    dbo.OBTEN_MONTO_LICENCIA(1,E.IDVERSION,1,FREC,1) /FREC
 END AS PRECIODEF,
 ISNULL(@DIASAPAGAR,0) AS DIASAPAGAR,
CASE WHEN PAIS_DEFAULT='MX' THEN 'MXN' ELSE 'USD' END AS PREFMONEDA 
 FROM <#SESSION.DB/>.DBO.EMPRESAS E 
LEFT JOIN CONTROL.DISTRIBUIDORES.DBO.VERSIONES L ON L.IDVERSION=E.IDVERSION 
WHERE IDEMPRESA=@IDEMPRESA   
