//[session.db|Untyped,session.idempresa|Untyped,]
SELECT 11 AS IMPUESTO,* 
  FROM <#SESSION.DB/>.dbo.EMPRESAS E 
  LEFT JOIN CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION F ON E.IDEMPRESA = F.IDEMPRESA 
--  LEFT JOIN ESTADOS_IMPUESTOS I ON F.IDESTADO = I.IDESTADO AND F.IDPAIS = I.IDPAIS
  WHERE E.IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDPRODUCTO=1