//[session.db|Untyped,session.idempresa|Untyped,]
DECLARE @IDPAIS VARCHAR(2)
DECLARE @IDPRODUCTO INT
DECLARE @IDMONEDA INT

SET  @IDPRODUCTO = CAST('1' AS MONEY)

SELECT   @IDPAIS = PAIS_DEFAULT FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>


DECLARE @CODIGOMONEDA VARCHAR(3)
DECLARE @MONEDA VARCHAR(32)
DECLARE @PAIS VARCHAR(64)
DECLARE @DESCRIPCION VARCHAR(8000)


DECLARE @TC MONEY
DECLARE @PRECIO MONEY
SET @PRECIO = 1000
SET @IDMONEDA = 1
SET @TC = 1
SET @CODIGOMONEDA  = 'MXN'
SET @MONEDA  = 'Pesos Mexicanos'
SET @PAIS  = 'México'


SELECT @PRECIO = PRECIO FROM CONTROL.DISTRIBUIDORES.DBO.SKUS WHERE IDPRODUCTO = 1 AND IDSKU = 2
SELECT @IDMONEDA  = IDMONEDA , @CODIGOMONEDA = CODIGO, @MONEDA = MONEDA,@TC = TC, @PAIS = PAIS, @DESCRIPCION = DESCRIPCION FROM CONTROL.VENTAS.DBO.MONEDAS M , CONTROL.VENTAS.DBO.PAISES P 
WHERE P.IDPAIS = M.IDPAIS AND P.IDPAIS = @IDPAIS

SELECT @TC AS TC,@TC*@PRECIO AS PRECIO, @CODIGOMONEDA AS CODIGO, @MONEDA as MONEDA, @PAIS AS PAIS, REPLACE(@DESCRIPCION,'.','.<BR />') AS DESCRIPCION,@PRECIO as PRECIO_BASE_MXN , @IDMONEDA  AS aIDMONEDA

