//[f|Integer,u|Integer,idlicencia|Integer,sku|Integer,t|Text,tc|Numeric,precio_base|Numeric,idmoneda|Integer,subt|Numeric,imp|Numeric,m|Numeric,session.idempresa|Untyped,t_bu|Numeric,t_f|Integer,t_nom|Text,t_num|Text,t_mes|Text,t_a|Text,t_t|Text,t_c|Text,session.db|Untyped,openpay_oculto|Text,openpay_tarjeta|Text,]
--update 
/*PROTEGIDO*/
DECLARE @IDDISTRIBUIDOR INT
DECLARE @IDMONEDA INT
DECLARE @SKU INT
DECLARE @USU INT
DECLARE @FREC INT
DECLARE @TC MONEY
DECLARE @PRECIO_BASE MONEY
DECLARE @S MONEY
DECLARE @I MONEY
DECLARE @M MONEY
DECLARE @TIPO VARCHAR(1)
DECLARE @MONTO_ORIGINAL MONEY
DECLARE @IDLICENCIA   INT
DECLARE @IDEMPRESA INT 
DECLARE @TBU  MONEY
SET @FREC  =ISNULL(:F, 0) 
SET @USU  = ISNULL(:U , 0) 
SET @IDLICENCIA =ISNULL(:IDLICENCIA, 1)
SET @SKU  = ISNULL(:SKU, 0) 
IF @SKU = 2 
  SET @TIPO = 'M' 
ELSE
  SET @TIPO =ISNULL(:T, '') 
 
SET @TC  = ISNULL(:TC, 0) 
SET @PRECIO_BASE = ISNULL(:PRECIO_BASE, 0) 
SET  @IDMONEDA = ISNULL(:IDMONEDA, 0) 
IF @IDMONEDA = 0 SET @IDMONEDA = 1 


SET  @S = ISNULL(:SUBT, 0) 
SET  @I = ISNULL(:IMP, 0)
SET  @M = ISNULL(:M, 0) 
SET  @MONTO_ORIGINAL = 0

IF @TC != 1
BEGIN
  SET  @MONTO_ORIGINAL = @M
  SET  @S = CAST(@S/@TC AS MONEY)
  SET  @I = CAST(@I/@TC AS MONEY)
  SET  @M = CAST(@M/@TC AS MONEY)
END

SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'
SET @TBU= ISNULL(:T_BU, 0) 
DECLARE @T_F INT 
DECLARE @T_NOM VARCHAR(128)
DECLARE @T_NUM VARBINARY(256)
DECLARE @T_MES VARBINARY(256)
DECLARE @T_A VARBINARY(256)
DECLARE @T_T INT
DECLARE @T_C VARBINARY(256)

SET @T_F=ISNULL(:T_F, 0) 
SET @T_NOM=ISNULL( :T_NOM , '')
SET @T_NUM=CONVERT(VARBINARY(256),:T_NUM)
SET @T_MES=CONVERT(VARBINARY(256),:T_MES)
SET @T_A=CONVERT(VARBINARY(256),:T_A) 
SET @T_T=ISNULL(:T_T, 0) 
SET @T_C=CONVERT(VARBINARY(256),:T_C) 


SELECT @IDDISTRIBUIDOR  = IDDISTRIBUIDOR FROM <#SESSION.DB/>.dbo.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA
DELETE FROM CONTROL.VENTAS.DBO.CARRITO  WHERE IDEMPRESA = @IDEMPRESA and idproducto=1
INSERT INTO CONTROL.VENTAS.DBO.CARRITO (IDEMPRESA,IDPRODUCTO,FECHA, SUBTOTAL, IMPUESTOS, MONTO, FRECUENCIA, USUARIOS, TIPO, IDDISTRIBUIDOR,BONIFICACION, MONTOORIGINAL, TC, IDMONEDA, IDSKU, IDVERSION, CAMPOOCULTO, TKTARJETA)
VALUES (@IDEMPRESA,1, GETDATE(), @S, @I, @M,@FREC , @USU, @TIPO, @IDDISTRIBUIDOR,@TBU, @MONTO_ORIGINAL, @TC,@IDMONEDA,@SKU, @IDLICENCIA, :openpay_oculto, :openpay_tarjeta)

IF @T_F = 2
BEGIN
  IF (SELECT COUNT(*) FROM CONTROL.vENTAS.DBO.EMPRESA_TARJETAS WHERE TARJETA = RIGHT(@T_NUM, 4)) = 1
  BEGIN
    UPDATE CONTROL.vENTAS.DBO.EMPRESA_TARJETAS SET TARJETADEFAULT = 0  WHERE IDEMPRESA = @IDEMPRESA AND IDPRODUCTO = 1
    INSERT INTO CONTROL.vENTAS.DBO.EMPRESA_TARJETAS (IDEMPRESA, IDPRODUCTO, TKOPENPAY, NOMBRE, TARJETA, TARJETADEFAULT)
    VALUES (@IDEMPRESA,1,:openpay_tarjeta, @T_NOM, RIGHT(@T_NUM, 4), 1)
  END
END

use master
/*OPEN MASTER KEY DECRYPTION BY PASSWORD = 'BFX.Cancun2013'*/
OPEN SYMMETRIC KEY KeyGrupoBFX DECRYPTION BY CERTIFICATE CertBFX;
 
  UPDATE  CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION SET
    FORMA_PAGO = @T_F, 
    TARJETA_NOMBRE = @T_NOM, 
    TARJETA_TIPO = @T_T 
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>  and idproducto=1

  UPDATE  CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION SET
    FORMA_PAGO = @T_F, 
    TARJETA_NOMBRE = @T_NOM, 
    TARJETA_NUMERO = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),@T_NUM), 
    TARJETA_MES = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),@T_MES), 
    TARJETA_ANNIO = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),@T_A), 
    TARJETA_TIPO = @T_T, 
    TARJETA_CODIGO =ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),@T_C) 
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>  and idproducto=1
	

CLOSE SYMMETRIC KEY KeyGrupoBFX
use SALESUP_CT	
DECLARE @TK VARCHAR(62)

IF @T_F = 2
BEGIN
  SELECT TOP 1 @TK = TK FROM CONTROL.VENTAS.DBO.CARRITO where IDEMPRESA = @IDEMPRESA ORDER BY IDEMPRESACOMPRA DESC
--  EXEC CONTROL.VENTAS.dbo.[SP_PROCESA_CARGO_CARRITO]  @TK
END   

