//[t_f|Integer,t_nom|Text,t_num|Text,t_mes|Text,t_a|Text,t_t|Integer,t_c|Text,session.idempresa|Untyped,]
-- update

use master
/*OPEN MASTER KEY DECRYPTION BY PASSWORD = 'BFX.Cancun2013'*/
OPEN SYMMETRIC KEY KeyGrupoBFX DECRYPTION BY CERTIFICATE CertBFX;
 
  UPDATE  CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION SET
    FORMA_PAGO = ISNULL(:T_F,0), 
    TARJETA_NOMBRE = ISNULL(:T_NOM,''), 
    TARJETA_NUMERO = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),ISNULL(:T_NUM,'')), 
    TARJETA_MES = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),ISNULL(:T_MES,'')), 
    TARJETA_ANNIO = ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),ISNULL(:T_A,'')), 
    TARJETA_TIPO = ISNULL(:T_T,0),
    TARJETA_CODIGO =ENCRYPTBYKEY(KEY_GUID('KeyGrupoBFX'),ISNULL(:T_C,'')) 
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>  and idproducto=1
	

CLOSE SYMMETRIC KEY KeyGrupoBFX
use SALESUP_CT	