//[session.db|Untyped,session.idusuario|Untyped,session.email|Untyped,idcorreo|Text,]
DECLARE @IDUSUARIOC INT

SELECT top 1 @IDUSUARIOC  = IDUSUARIOCORREO FROM <#SESSION.DB/>.dbo.USUARIOS_CUENTAS_CORREOS 
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND EMAIL = '<#SESSION.EMAIL/>' ORDER BY 1 DESC

SELECT ESTADO FROM   <#SESSION.DB/>.dbo.USUARIOS_EMAILS  WHERE IDEMAIL = :IDCORREO   

