//[session.db|Untyped,session.idusuario|Untyped,session.email|Untyped,]
DECLARE @IDUSUARIOC INT

SELECT top 1 @IDUSUARIOC  = IDUSUARIOCORREO FROM <#SESSION.DB/>.dbo.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND
EMAIL = '<#SESSION.EMAIL/>' ORDER BY 1 DESC

UPDATE  <#SESSION.DB/>.dbo.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 0 WHERE IDUSUARIOCORREO =   @IDUSUARIOC  

SELECT @IDUSUARIOC AS  IDUSUARIOCORREO