//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--SELECT

SELECT IDCONFIGURACION, NOMBRE_CONFIGURACION 
FROM <#SESSION.DB/>.DBO.CONFIGURACION_USUARIOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDEMPRESA = <#SESSION.IDEMPRESA/>