//[campo|Text,tamanio|Text,session.db|Untyped,session.idusuario|Untyped,]
--UPDATE
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @TAMANIO VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
SET @SQL=''
SET @CAMPO=ISNULL(:CAMPO,'')
SET @TAMANIO=ISNULL(:TAMANIO,'')
SET @SQL='
UPDATE PRO SET PRO.'+@CAMPO+' = LEFT(PRI.'+@CAMPO+',CAST('+@TAMANIO+' AS INT)) 
FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PRO  
INNER JOIN <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PRI ON PRO.IDPROSPECTOIMPORTA = PRI.IDPROSPECTOIMPORTA 
WHERE PRO.IDUSUARIO = <#SESSION.IDUSUARIO/>
'
EXEC (@SQL)