//[session.db|Untyped,contador|Text,idfase|Text,session.idempresa|Untyped,session.idusuario|Untyped,]
-- SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDFASE VARCHAR(1000)
DECLARE @CONTADOR VARCHAR(1000)
SET @IDFASE = CAST(ISNULL(:IDFASE,0) AS VARCHAR(1000))
SET @CONTADOR = CAST(ISNULL(:CONTADOR,0) AS VARCHAR(1000))

SET @SQL = '
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION
SET COL'+@CONTADOR+' = ISNULL(CAST(PF.IDFASE AS VARCHAR(10)),'+@IDFASE+') 
FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES PF ON PS.COL'+@CONTADOR+' = PF.FASE AND PF.IDEMPRESA = <#SESSION.IDEMPRESA/>
 WHERE PS.IDUSUARIO = <#SESSION.IDUSUARIO/>

SELECT 0 AS CONTEOS, 0 AS TIPO
'
EXEC (@SQL)