//[idpais|Text,idestado|Text,colpais|Text,colestado|Text,colmunicipio|Text,colnombre|Text,session.db|Untyped,session.idusuario|Untyped,]
-- UPDATE
/*PROTEGIDO*/

DECLARE @IDPAIS VARCHAR(128) = ISNULL(:IDPAIS,'')
DECLARE @IDESTADO VARCHAR(128) = ISNULL(:IDESTADO,'')
DECLARE @COLPAIS VARCHAR(128) = ISNULL(:COLPAIS,'')
DECLARE @COLESTADO VARCHAR(128) = ISNULL(:COLESTADO,'')
DECLARE @COLMUNICIPIO VARCHAR(128) = ISNULL(:COLMUNICIPIO,'')
DECLARE @COLNOMBRE VARCHAR(128) = ISNULL(:COLNOMBRE,'')
DECLARE @SQLTXT VARCHAR(MAX)

UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION  SET   
  IDPAIS = @IDPAIS, IDESTADO = @IDESTADO   
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>  

SET @SQLTXT = 'UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION  SET '   
SET @SQLTXT = @SQLTXT + ' IDPAISDEF = isnull((select TOP 1 IDPAIS from <#SESSION.DB/>.DBO.Paises where (idpais = '+@COLPAIS+' OR salesup_ct.dbo.NomalizaCadena(PAIS) LIKE salesup_ct.dbo.NomalizaCadena('+@COLPAIS+'))), '''+@IDPAIS+''') '   
SET @SQLTXT = @SQLTXT + ' WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> '  
EXEC(@SQLTXT)

SET @SQLTXT = ' UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION  SET '   
SET @SQLTXT = @SQLTXT + ' IDESTADODEF = isnull((select TOP 1 IDESTADO from <#SESSION.DB/>.DBO.ESTADOS where IDPAIS = IDPAISDEF AND (IDESTADO = salesup_ct.dbo.NomalizaCadena('+@COLESTADO+') OR salesup_ct.dbo.NomalizaCadena(ESTADO) LIKE salesup_ct.dbo.NomalizaCadena('+@COLESTADO+')) ), '''+@IDESTADO+''') '   
SET @SQLTXT = @SQLTXT + ' WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> '  
EXEC(@SQLTXT)

SET @SQLTXT = ' UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION  SET '   
SET @SQLTXT = @SQLTXT + ' IDMUNICIPIODEF = (select TOP 1 IDMUNICIPIO from salesup_ct.DBO.MUNICIPIOS where IDPAIS = IDPAISDEF AND IDESTADO = IDESTADODEF AND (MUNICIPIO = salesup_ct.dbo.NomalizaCadena('+@COLMUNICIPIO+') OR salesup_ct.dbo.NomalizaCadena(MUNICIPIO) LIKE salesup_ct.dbo.NomalizaCadena('+@COLMUNICIPIO+')) ) '   
SET @SQLTXT = @SQLTXT + ' WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> '
EXEC(@SQLTXT)  

UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION  SET   
  @ColNombre = '(Desconocido)'   
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>  AND @ColNombre = ''