//[archivo|Text,session.idusuario|Untyped,session.db|Untyped,]
--update
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @RESULT VARCHAR(3000)
DECLARE @ARCHIVO VARCHAR(1000)
SET @ARCHIVO =  ISNULL(:ARCHIVO,'') 
EXEC SALESUP_CT.DBO.SP_CARGA_PROSPECTOS_CSV @ARCHIVO, <#SESSION.IDUSUARIO/>,'<#SESSION.DB/>' ,@RESULT out 