//[guardarconfig|Integer,nombreconfiguracion|Text,configimportacion|Text,configimportaciondefaults|Text,configimportacionprospectos|Text,etiquetas|Text,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,qry|Text,qryupdate|Text,]
DECLARE @GUARDACONFIG INT
DECLARE @NOMBRE_CONFIGURACION VARCHAR(100)
DECLARE @CONFIGURACION_TABLA VARCHAR(1000)
DECLARE @CONFIGDEFAULTS VARCHAR(1000)
DECLARE @CONFIGPROSPECTOS VARCHAR(1000)
DECLARE @ETIQUETAS VARCHAR(1000)
DECLARE @QRY VARCHAR(1000)
DECLARE @QRYUPDATE VARCHAR(1000)

SET @GUARDACONFIG = CAST(ISNULL(:guardarConfig,0) AS INT)
SET @NOMBRE_CONFIGURACION = CAST(ISNULL(:nombreConfiguracion,'') AS VARCHAR(100))
SET @CONFIGURACION_TABLA = ISNULL(:configImportacion,'')
SET @CONFIGDEFAULTS = ISNULL(:configImportacionDefaults,'')
SET @CONFIGPROSPECTOS = ISNULL(:configImportacionProspectos,'')
SET @ETIQUETAS = CAST(ISNULL(:etiquetas,'') AS VARCHAR(1000))
SET @QRY=ISNULL(:QRY,'')
SET @QRYUPDATE=ISNULL(:QRYUPDATE,'')

IF(@GUARDACONFIG = 1)
BEGIN
	INSERT INTO <#SESSION.DB/>.DBO.CONFIGURACION_USUARIOS_IMPORTACION (IDUSUARIO, IDEMPRESA, NOMBRE_CONFIGURACION,CONFIGURACION_TABLA,CONFIGURACION_DEFAULTS,CONFIGURACION_PROSPECTOS,CONFIGURACION_ETIQUETAS) 
	VALUES(<#SESSION.IDUSUARIO/>,<#SESSION.IDEMPRESA/>,@NOMBRE_CONFIGURACION,@CONFIGURACION_TABLA,@CONFIGDEFAULTS,@CONFIGPROSPECTOS,@ETIQUETAS)
END

DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION_PARAMETROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION_PARAMETROS  (IDUSUARIO, QUERY1, QUERY2) VALUES(<#SESSION.IDUSUARIO/>, @QRY, @QRYUPDATE)