//[contador|Integer,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONTADOR VARCHAR(MAX)
SET @CONTADOR=CAST(ISNULL(:CONTADOR,0) AS VARCHAR(MAX))
SET @SQL='SELECT * FROM (SELECT COL'+@CONTADOR+' AS CORREOREPETIDO FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND COL'+@CONTADOR+' != '''' GROUP BY COL'+@CONTADOR+' HAVING COUNT(*)>1 ) AS T'
EXEC (@SQL)
