//[session.db|Untyped,session.idusuario|Untyped,]
SELECT 
  (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND RESULTADOTIPO = 1) AS INSERTADOS,
  (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND RESULTADOTIPO = 2) AS ACTUALIZADOS,
  (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND RESULTADOTIPO = 0) AS ERRORES     