//[validacionjson|Text,session.db|Untyped,session.idusuario|Untyped,tipoBorrar|integer]
-- SELECT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @JSON VARCHAR(MAX)

SET @JSON = :validacionjson

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDPROSPECTOIMPORTA INT, COLUMNA VARCHAR(10))
DECLARE @TO INT, @TOTAL INT, @CONTEO INT
DECLARE @IDPROSPECTOIMPORTA INT
DECLARE @COLUMNA VARCHAR(10)
DECLARE @TIPOBORRAR INT = :TIPOborrar
DECLARE @EXECSQL VARCHAR(MAX)

SET @TO = 1


INSERT INTO @TABLATEMP (IDPROSPECTOIMPORTA,COLUMNA)
Select 
       max(case when NAME='idprospectoimporta' then STRINGVALUE else '' end) as IDPROSPECTOIMPORTA,
       max(case when NAME='columna' then STRINGVALUE else '' end) as COLUMNA
from SALESUP_CT.dbo.parseJSON(@JSON)
WHERE parent_id IS NOT NULL
group by PARENT_ID

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA,@COLUMNA = COLUMNA FROM @TABLATEMP WHERE ID = @TO
	IF(@COLUMNA <> '')
	BEGIN
	  IF (ISNULL(@TIPOBORRAR, 0)=0)
		SET @EXECSQL = ' UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION SET ' + @COLUMNA + ' = '''' WHERE IDPROSPECTOIMPORTA = ' + CAST(@IDPROSPECTOIMPORTA AS VARCHAR(50)) + ' AND IDUSUARIO = <#SESSION.IDUSUARIO/> '
	 ELSE
		SET @EXECSQL = ' DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDPROSPECTOIMPORTA = ' + CAST(@IDPROSPECTOIMPORTA AS VARCHAR(50)) + ' AND IDUSUARIO = <#SESSION.IDUSUARIO/> '
  	  EXEC(@EXECSQL)
	END
	
	SET @TO = @TO + 1
END

SELECT 'DATOS BORRADOS' AS RESPUESTA