//[campo|Text,borrar|Text,session.db|Untyped,session.idusuario|Untyped,contador|Text,]
-- SELECT
DECLARE @CAMPO VARCHAR(1000)
DECLARE @SQL VARCHAR(MAX)
DECLARE @BORRAR VARCHAR(1000)
DECLARE @CONTADOR VARCHAR(1000)
SET @CAMPO=ISNULL(:CAMPO,'')
SET @BORRAR=ISNULL(:BORRAR,'0')
SET @CONTADOR=ISNULL(:CONTADOR,'')

SET @SQL='
DECLARE @CONTEO INT
DECLARE @IDPROSPECTOIMPORTA INT

IF (('''+@CAMPO+'''=''CAMPO1'')OR('''+@CAMPO+'''=''CAMPO2'')OR('''+@CAMPO+'''=''CAMPO3'')OR('''+@CAMPO+'''=''CAMPO4'')OR('''+@CAMPO+'''=''CAMPO5'')OR('''+@CAMPO+'''=''CAMPO6'')OR('''+@CAMPO+'''=''CAMPO7'')OR('''+@CAMPO+'''=''CAMPO8'')OR('''+@CAMPO+'''=''Noempleados''))
BEGIN
	 IF ('+@borrar+'=1)
	 BEGIN
	 	  SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		  SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND (COL'+@CONTADOR+' != '''' AND ISNUMERIC(COL'+@CONTADOR+')=0) AND IDPROSPECTOIMPORTA != @IDPROSPECTOIMPORTA
		  SELECT @CONTEO AS CONTEOS, 1 AS TIPO
	END
	ELSE
	BEGIN
		 SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND (COL'+@CONTADOR+' != '''' AND ISNUMERIC(COL'+@CONTADOR+')=0)
		 SELECT @CONTEO AS CONTEOS, 1 AS TIPO
	END
END
ELSE
IF (('''+@CAMPO+'''=''CAMPO9'')OR('''+@CAMPO+'''=''CAMPO10'')OR('''+@CAMPO+'''=''CAMPO11'')OR('''+@CAMPO+'''=''CAMPO12''))
BEGIN
	 IF ('+@borrar+'=1)
	 BEGIN
	 	  SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		  SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION 
		  WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND (ISDATE(<#SESSION.DB/>.DBO.FormatoFechaImportacion(COL'+@CONTADOR+'))=0 AND COL'+@CONTADOR+' != '''') AND IDPROSPECTOIMPORTA != @IDPROSPECTOIMPORTA AND COL'+@CONTADOR+'!=''''
		  
		  SELECT @CONTEO AS CONTEOS, 2 AS TIPO
	END
	ELSE
	BEGIN
		SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION 
		WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND (ISDATE(<#SESSION.DB/>.DBO.FormatoFechaImportacion(COL'+@CONTADOR+'))=0 AND COL'+@CONTADOR+'!='''')
		
		SELECT @CONTEO AS CONTEOS, 2 AS TIPO, @CAMPO AS CAMPO, @BORRAR AS BORRAR, @CONTADOR AS CONTADOR
	END
END
ELSE
BEGIN
	 SELECT 0 AS CONTEOS, 0 AS TIPO, @CAMPO AS CAMPO, @BORRAR AS BORRAR, @CONTADOR AS CONTADOR
END
'
EXEC (@SQL)