//[tit|Text,session.db|Untyped,session.idempresa|Untyped,criteriofiltro|Text,]
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @CRIT = ISNULL( :CRITERIOFILTRO , '')

SET @SQL = '
  DECLARE @TIPO INT,@TITULO INT, @COMPARTIR INT
  SET @TITULO = CAST(  ' + :TIT + ' AS INT)

  IF(@TITULO = 0)
  BEGIN
	 SET @TIPO = 1
	 SET @COMPARTIR = 1
  END
  ELSE
  BEGIN
	 SET @TIPO = 3
	 SET @COMPARTIR = 3
  END

  SELECT
  ISNULL(EC.LLAVE,0) AS LLAVE,
  CASE EC.LLAVE
  WHEN 2 THEN EC.NOMBRE_CAMPO+'' *'' ELSE EC.NOMBRE_CAMPO END AS NOMBRE_CAMPO ,
  ISNULL(EC.VALIDACION,''class="adicional"'') AS VALIDACION,
  EC.*, 
  SUBSTRING(NOMBRE_CAMPO,1,13) AS NOMBRECORTO 
  FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC
  WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND indice >= 21 and indice < 26 AND 
  (TIPO = @TIPO OR COMPARTIR = @COMPARTIR) AND TIPO_CAMPO NOT IN (3,4,6,7,8,9) 
   '  +   @CRIT +  '
   ORDER BY EC.NOMBRE_CAMPO
   
   '
   EXEC (@SQL)