//[session.db|Untyped,nombre|Text,session.idempresa|Untyped,campo|Text,borrar|Text,session.idusuario|Untyped,contador|Text,]
-- SELECT

DECLARE @IDPROSPECTOIMPORTA VARCHAR(1000)
DECLARE @IDCAMPO VARCHAR(1000)
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @NOMBRE VARCHAR(MAX)
DECLARE @CONTADOR VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
DECLARE @BORRAR VARCHAR(MAX)
SET @CAMPO=ISNULL(:CAMPO,'')
SET @NOMBRE =  ISNULL(:NOMBRE,'')
SET @CONTADOR =  ISNULL(:CONTADOR, '1')
SET @BORRAR =  ISNULL(:BORRAR,'')


SELECT @IDCAMPO = IDCAMPO FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE NOMBRE_CAMPO = @NOMBRE AND IDEMPRESA = <#SESSION.IDEMPRESA>

IF ((@CAMPO='CAMPO21')OR(@CAMPO='CAMPO22')OR(@CAMPO='CAMPO23')OR(@CAMPO='CAMPO24')OR(@CAMPO='CAMPO25'))
BEGIN
	 IF (@BORRAR=1)
	 BEGIN
	 	  SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		  SET @SQL='
		  DECLARE @CONTEO INT
		  SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND COL'+@CONTADOR+' NOT IN(SELECT OPCION FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDCAMPO = '+@IDCAMPO+') AND IDPROSPECTOIMPORTA != '+@IDPROSPECTOIMPORTA+'
		  SELECT @CONTEO AS CONTEOS, 1 AS TIPO, '''+@CAMPO+''' AS CAMPO, '''+@NOMBRE+''' AS NOMBRE, '''+@CONTADOR+''' AS CONTADOR ,'''+@BORRAR+''' as BORRAR
		  '
	      EXEC (@SQL)
	END
	ELSE
	BEGIN
		 SET @SQL='
     	 DECLARE @CONTEO INT
		 SELECT @CONTEO=COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND COL'+@CONTADOR+' NOT IN(SELECT OPCION FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDCAMPO = '+@IDCAMPO+')
		 SELECT @CONTEO AS CONTEOS, 1 AS TIPO, '''+@CAMPO+''' AS CAMPO, '''+@NOMBRE+''' AS NOMBRE, '''+@CONTADOR+''' AS CONTADOR ,'''+@BORRAR+''' as BORRAR
		 '
		 EXEC (@SQL)	 
	END
END
ELSE
BEGIN
	 SELECT 0 AS CONTEOS, 0 AS TIPO, @CAMPO AS CAMPO, @NOMBRE AS NOMBRE, @CONTADOR AS CONTADOR ,@BORRAR as BORRAR
END