//[session.idusuario|Untyped,]
--UPDATE
DECLARE @PROPID INT
SELECT TOP 1 @PROPID  = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> ORDER BY IDPROSPECTOIMPORTA
SELECT @PROPID
IF @PROPID IS NOT NULL
  DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDPROSPECTOIMPORTA = @PROPID
