//[session.db|Untyped,col|Text,session.idusuario|Untyped,idprospectoimporta|Integer,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDPROSPECTO VARCHAR(1000)
DECLARE @COL VARCHAR(1000)
SET @IDPROSPECTO=CAST( ISNULL(:idprospectoimporta,0) AS VARCHAR(1000))
SET @COL =  ISNULL(:COL,'')
SET @SQL='UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION SET '+@COL+' = NULL WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTOIMPORTA = '+@IDPROSPECTO
EXEC (@SQL)