//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,idconfiguracion|Integer,]
-- SELECT

SELECT CONFIGURACION_TABLA, CONFIGURACION_DEFAULTS, CONFIGURACION_PROSPECTOS, CONFIGURACION_ETIQUETAS 
FROM <#SESSION.DB/>.DBO.CONFIGURACION_USUARIOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDCONFIGURACION = CAST(ISNULL(:idconfiguracion,0) AS INT)