//[tipo|Text,titulo|Text,borrar|Text,jsoncampos|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,]
-- SELECT 

DECLARE @TABLATEMP TABLE (ID INT IDENTITY, CAMPONOMBRE VARCHAR(500),COLUMNA VARCHAR(500))
DECLARE @TO INT, @TOTAL INT
DECLARE @CAMPONOMBRE VARCHAR(100)
DECLARE @CAMPOCORREO VARCHAR(100)
DECLARE @COLUMNA VARCHAR(50)
DECLARE @ESCORREO INT
DECLARE @ESPROSPECTO INT
DECLARE @CAMPOPROSPECTO VARCHAR(100) = ''
DECLARE @INDICE VARCHAR(10)
DECLARE @NOMBREREAL VARCHAR(512)
DECLARE @TEXTOTIPO VARCHAR(512)
DECLARE @TEXTOSINTIPO VARCHAR(512)
DECLARE @TIPO INT,@TIPOCAMPO INT
DECLARE @TITULO INT
DECLARE @EXECSQL VARCHAR(MAX)
SET @EXECSQL = 'SELECT '

DECLARE @IDPROSPECTOIMPORTA INT
DECLARE @BORRAR INT

SET @TIPO = CAST(ISNULL(:TIPO,'') AS INT)

SET @TITULO = CAST(ISNULL(:TITULO,'') AS INT)

IF(@TITULO = 1)
BEGIN
	 SET @TIPOCAMPO = 3
	 SET @TEXTOSINTIPO = 'Cliente nuevo'
END
ELSE
BEGIN
	 SET @TIPOCAMPO = 1
	 SET @TEXTOSINTIPO = 'Prospecto nuevo'
END

IF(@TITULO = 1)
BEGIN
	 SET @TEXTOTIPO = 'Cliente por actualizar'
END
ELSE
BEGIN
	 SET @TEXTOTIPO = 'Prospecto por actualizar'
END

IF(@TIPO = 1)
BEGIN
	 IF(@TITULO = 1)
	 BEGIN
	 	 SET @TEXTOTIPO = 'Cliente por ignorar'
	END
	ELSE
	BEGIN
		 SET @TEXTOTIPO = 'Prospecto por ignorar'
	END 
END

SET @TO = 1
SET @BORRAR = CAST(ISNULL(:BORRAR,'') AS INT)
SET @ESCORREO = 0

INSERT INTO @TABLATEMP (CAMPONOMBRE,COLUMNA)
Select name, stringvalue
from SALESUP_CT.dbo.parseJSON(:JSONCAMPOS)
WHERE parent_id IS NOT NULL

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @CAMPONOMBRE = CAMPONOMBRE,@COLUMNA = COLUMNA FROM @TABLATEMP WHERE ID = @TO
	SET @INDICE = REPLACE(@CAMPONOMBRE,'CAMPO','')
	SET @NOMBREREAL = ''
	
	IF(ISNUMERIC(@INDICE) = 1)
	BEGIN
		 SELECT @NOMBREREAL = isnull('<b>' + NOMBRE_CAMPO + '</b>:','') FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WHERE INDICE = @INDICE AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND TIPO = @TIPOCAMPO
	END
	
	IF(@TO = 1)
	BEGIN
		IF(ISNUMERIC(@INDICE) = 1 AND (@INDICE >=21 AND @INDICE <= 25))
		 BEGIN
			SET @EXECSQL = @EXECSQL+ ''''+@NOMBREREAL+'''' +'+ISNULL((SELECT OPCION FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDOPCION = PS.'+@COLUMNA+'),'''') AS ' + @CAMPONOMBRE + ' '
		 END
		 ELSE
		 BEGIN
			SET @EXECSQL = @EXECSQL+ ''''+@NOMBREREAL+'''' +'+PS.' + @COLUMNA + ' AS ' + @CAMPONOMBRE + ' '
		 END
	END
	ELSE
	BEGIN
		IF(ISNUMERIC(@INDICE) = 1 AND (@INDICE >=21 AND @INDICE <= 25))
		 BEGIN
			SET @EXECSQL = @EXECSQL + ',' + ''''+@NOMBREREAL+'''' +'+ISNULL((SELECT OPCION FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WHERE IDOPCION = PS.'+@COLUMNA+'),'''') AS ' + @CAMPONOMBRE + ' '
		 END
		 ELSE
		 BEGIN
			SET @EXECSQL = @EXECSQL + ',' + ''''+@NOMBREREAL+'''' +'+PS.' + @COLUMNA + ' AS ' + @CAMPONOMBRE + ' '
		 END
	END
	
	IF(@CAMPONOMBRE = 'correo')
	BEGIN
		 SET @ESCORREO = 1
		 SET @CAMPOCORREO = @COLUMNA
	END
	
	IF(@CAMPONOMBRE = 'Idprospecto')
	BEGIN
		 SET @ESPROSPECTO = 1
		 SET @CAMPOPROSPECTO = @COLUMNA
	END

	SET @TO = @TO + 1
END

IF(@ESPROSPECTO = 1)
BEGIN
	IF(@BORRAR=1)
	BEGIN
		 SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo,CASE WHEN '+@CAMPOPROSPECTO+' = '''' THEN '''+@TEXTOSINTIPO+''' ELSE '''+@TEXTOTIPO+''' END AS existe,idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON PS.'+@CAMPOPROSPECTO+' = P.IDPROSPECTO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND ltrim(rtrim(isnull(PS.'+@CAMPOPROSPECTO+',''''))) <> '''' WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTOIMPORTA != ' + CAST(@IDPROSPECTOIMPORTA AS VARCHAR(100)) + ' '
	END
	ELSE
	BEGIN
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo,CASE WHEN '+@CAMPOPROSPECTO+' = '''' THEN '''+@TEXTOSINTIPO+''' ELSE '''+@TEXTOTIPO+''' END AS existe, idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON PS.'+@CAMPOPROSPECTO+' = P.IDPROSPECTO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND ltrim(rtrim(isnull(PS.'+@CAMPOPROSPECTO+',''''))) <> '''' WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> '
	END
END
ELSE IF(@ESCORREO = 1)
BEGIN
	IF(@BORRAR=1)
	BEGIN
		 SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo,CASE WHEN p.correo is null THEN '''+@TEXTOSINTIPO+''' ELSE '''+@TEXTOTIPO+''' END AS existe,idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON PS.'+@CAMPOCORREO+' = P.CORREO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND ltrim(rtrim(isnull(PS.'+@CAMPOCORREO+',''''))) <> '''' WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTOIMPORTA != ' + CAST(@IDPROSPECTOIMPORTA AS VARCHAR(100)) + ' '
	END
	ELSE
	BEGIN
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo,CASE WHEN p.correo is null THEN '''+@TEXTOSINTIPO+''' ELSE '''+@TEXTOTIPO+''' END AS existe, idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON PS.'+@CAMPOCORREO+' = P.CORREO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND ltrim(rtrim(isnull(PS.'+@CAMPOCORREO+',''''))) <> '''' WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> '
	END
END
ELSE
BEGIN
	IF(@BORRAR=1)
	BEGIN
		 SELECT TOP 1 @IDPROSPECTOIMPORTA = IDPROSPECTOIMPORTA FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo, idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS, <#SESSION.DB/>.DBO.USUARIOS U WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTOIMPORTA != ' + CAST(@IDPROSPECTOIMPORTA AS VARCHAR(100)) + ' '
	END
	ELSE
	BEGIN
		 SET @EXECSQL = @EXECSQL + ', CONVERT(VARCHAR,GETDATE(),103) AS fecha, U.INICIALES AS iniciales, u.nombre+'' ''+isnull(u.apellidos,'''') as ejecutivo, idprospectoimporta as idprospectoimporta FROM <#SESSION.DB/>.DBO.PROSPECTOS_IMPORTACION PS, <#SESSION.DB/>.DBO.USUARIOS U WHERE PS.IDUSUARIO = U.IDUSUARIO AND PS.IDUSUARIO = <#SESSION.IDUSUARIO/> '
	END
END

EXEC(@EXECSQL)