//[session.idempresa|Untyped,session.idusuario|Untyped,idventana|Integer,session.db|Untyped,]
---SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT, @IDPANTALLA INT, @IDEMPRESA INT, @VERPROSPECTOS INT, @VERVENTAS INT, @VEREMPRESA INT
DECLARE @HTML VARCHAR(MAX), @THEAD VARCHAR(MAX), @VizualizarEn VARCHAR(MAX)
DECLARE @LtCampos TABLE( IDUSUCOL INT, IDCOLUMNA INT, COLUMNA VARCHAR(MAX), TIPO INT,MODULO INT)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)   
SET @IDPANTALLA = ISNULL(:IDVENTANA,0) 
SET @HTML = ''
SET @THEAD = ''
SET @VizualizarEn = ''
SET @VEREMPRESA = 1
SET @VERPROSPECTOS = 0
SET @VERVENTAS = 0

/* EN ESTE CASO PROSPECTOS Y CLIENTES SON 1,4  - EN ESTE CASO OPORTUNIDADES Y VENTAS SON 2,3 */

IF @IDPANTALLA = 1 BEGIN SET @VizualizarEn = '1' END
IF @IDPANTALLA = 4 BEGIN SET @VizualizarEn = '1,3' END
IF @IDPANTALLA = 1 OR @IDPANTALLA = 4 BEGIN SET @VERPROSPECTOS = 1 END

IF @IDPANTALLA = 2 BEGIN SET @VizualizarEn = '1,2' END
IF @IDPANTALLA = 3 BEGIN SET @VizualizarEn = '1,4' END
IF @IDPANTALLA = 2 OR @IDPANTALLA = 3 BEGIN SET @VERVENTAS = 1 SET @VERPROSPECTOS = 1 END

INSERT INTO @LtCampos (IDUSUCOL, IDCOLUMNA, COLUMNA, TIPO, MODULO)
SELECT 
UC.IDUSUARIOCOLUMNA,
CASE 
WHEN C.IDCOLUMNA IS NOT NULL THEN C.IDCOLUMNA
WHEN EC.IDCAMPO IS NOT NULL THEN EC.IDCAMPO
WHEN LP.IDLISTA_PRECIO IS NOT NULL THEN LP.IDLISTA_PRECIO
WHEN IM.IDIMPUESTO IS NOT NULL THEN IM.IDIMPUESTO
WHEN COM.IDPRODUCTO_COMISION IS NOT NULL THEN COM.IDPRODUCTO_COMISION
WHEN CAT.IDCATALOGO IS NOT NULL THEN CAT.IDCATALOGO END ,
CASE 
WHEN C.IDCOLUMNA IS NOT NULL THEN C.COLUMNA
WHEN EC.IDCAMPO IS NOT NULL THEN EC.NOMBRE_CAMPO
WHEN LP.IDLISTA_PRECIO IS NOT NULL THEN LP.NOMBRE
WHEN IM.IDIMPUESTO IS NOT NULL THEN IM.IMPUESTO
WHEN COM.IDPRODUCTO_COMISION IS NOT NULL THEN COM.DESCRIPCION
WHEN CAT.IDCATALOGO IS NOT NULL THEN (SELECT SplitValue FROM SALESUP_CT.DBO.SPLIT(CAT.CATALOGO,'/') WHERE OccurenceId = 1) END ,
CASE 
WHEN C.IDCOLUMNA IS NOT NULL THEN 1
WHEN EC.IDCAMPO IS NOT NULL THEN 2
WHEN LP.IDLISTA_PRECIO IS NOT NULL THEN 4
WHEN IM.IDIMPUESTO IS NOT NULL THEN 5
WHEN COM.IDPRODUCTO_COMISION IS NOT NULL THEN 6
WHEN CAT.IDCATALOGO IS NOT NULL THEN 3 END ,C.MODULO

FROM <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS UC 
LEFT JOIN SALESUP_CT.dbo.COLUMNAS C ON C.IDCOLUMNA = UC.IDCOLUMNA AND C.IDPANTALLA = @IDPANTALLA AND C.HTML IS NOT NULL
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC ON UC.IDCAMPO = EC.IDCAMPO AND EC.IDEMPRESA = @IDEMPRESA AND (EC.TIPO IN (SELECT SPLITVALUE FROM dbo.Split(@VizualizarEn,',')) OR EC.COMPARTIR IN (SELECT SPLITVALUE FROM dbo.Split(@VizualizarEn,',')))
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CAT ON CAT.IDEMPRESA = @IDEMPRESA AND CAT.IDCATALOGO = UC.IDCATALOGO AND (CAT.VERPROSPECTOS = @VERPROSPECTOS OR CAT.VEREMPRESA = 1) AND (CAT.VERVENTAS = @VERVENTAS OR CAT.VEREMPRESA = 1 OR CAT.VERPROSPECTOS = @VERPROSPECTOS) AND CAT.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.LISTAS_PRECIO LP ON UC.IDLISTA_PRECIO = LP.IDLISTA_PRECIO AND LP.IDEMPRESA = @IDEMPRESA AND LP.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS IM ON UC.IDIMPUESTO = IM.IDIMPUESTO AND IM.IDEMPRESA = @IDEMPRESA AND IM.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.PRODUCTOS_COMISIONES COM ON UC.IDCOMISION = COM.IDPRODUCTO_COMISION AND COM.IDEMPRESA = @IDEMPRESA AND COM.STATUS = 1
WHERE UC.IDUSUARIO = @IDUSUARIO AND UC.VISIBLE = 1 AND UC.IDPANTALLA = @IDPANTALLA 
ORDER BY UC.ORDEN

SELECT 1 AS R, IdUsuCol, IdColumna, Columna, Tipo, Modulo FROM @LtCampos WHERE IDCOLUMNA > 0