//[session.idempresa|Untyped,session.idusuario|Untyped,idventana|Integer,session.db|Untyped,]
---SELECT
DECLARE @IDUSUARIO INT, @IDVENTANA INT, @IDEMPRESA INT, @VERPROSPECTOS INT, @VERVENTAS INT, @VEREMPRESA INT
DECLARE @HTML VARCHAR(MAX), @THEAD VARCHAR(MAX), @SIMBOLO VARCHAR(MAX), @UNICODE VARCHAR(MAX),@simboloMoneda varchar(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)   
SET @IDVENTANA = ISNULL(:IDVENTANA,0)  
SET @HTML = ''
SET @THEAD = ''
SET @SIMBOLO = ''
SET @UNICODE = ''
SET @VERPROSPECTOS = 0
SET @VERVENTAS = 0
set @simboloMoneda = ''


IF @IDVENTANA = 1 OR @IDVENTANA = 4 BEGIN SET @VERPROSPECTOS = 1 END
IF @IDVENTANA = 2 OR @IDVENTANA = 3 BEGIN SET @VERVENTAS = 1 SET @VERPROSPECTOS = 1 END

SELECT 
@HTML = @HTML + CASE 
WHEN C.IDCOLUMNA IS NOT NULL THEN C.HTML
WHEN EC.IDCAMPO IS NOT NULL THEN SALESUP_CT.dbo.HtmlCaposPersonalizables(EC.NOMBRE_CAMPO, EC.INDICE, 2, EC.TIPO, EC.COMPARTIR, EC.TIPO_CAMPO)
WHEN CAT.IDCATALOGO IS NOT NULL THEN SALESUP_CT.dbo.HtmlCatalogos ( CAT.Catalogo, CAT.TIPO, CAT.INDICE, CAT.VERPROSPECTOS, CAT.VERVENTAS, CAT.VEREMPRESA, 0 )
WHEN UC.IDLISTA_PRECIO IS NOT NULL THEN ISNULL('<td class="FormatoAdd" data-simbolo="'+MON.MONEDA_SIMBOLO+'" data-unicode="'+ CAST(UNICODE(MON.MONEDA_SIMBOLO) AS VARCHAR(MAX))+'">{{PRECIO'+CAST(LP.INDICE AS VARCHAR(100))+'}}</td>','')

WHEN UC.IDIMPUESTO IS NOT NULL THEN ISNULL('<td class="tCen FormatPercent">{{IMPUESTO'+CAST(IM.INDICE AS VARCHAR(100))+'}}</td>','') 
WHEN UC.IDCOMISION IS NOT NULL THEN ISNULL('<td class="tCen FormatPercent">{{COMISION'+CAST(COM.INDICE AS VARCHAR(100))+'}}</td>','')  else '' END,
 
@THEAD = @THEAD + CASE 
WHEN C.IDCOLUMNA IS NOT NULL THEN C.THEAD
WHEN EC.IDCAMPO IS NOT NULL THEN SALESUP_CT.dbo.HtmlCaposPersonalizables(EC.NOMBRE_CAMPO, EC.INDICE, 1, 0 , 0, EC.TIPO_CAMPO)
WHEN CAT.IDCATALOGO IS NOT NULL THEN SALESUP_CT.dbo.HtmlCatalogos ( CAT.Catalogo, CAT.TIPO, CAT.INDICE, CAT.VERPROSPECTOS, CAT.VERVENTAS, CAT.VEREMPRESA, 1 )
WHEN UC.IDLISTA_PRECIO IS NOT NULL THEN ISNULL('<td class="">'+LP.NOMBRE+'</td>','')
WHEN UC.IDIMPUESTO IS NOT NULL THEN ISNULL('<td>'+IM.IMPUESTO+'</td>','')
WHEN UC.IDCOMISION IS NOT NULL THEN ISNULL('<td>'+COM.DESCRIPCION+'</td>','') else '' END

FROM <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS UC 
LEFT JOIN SALESUP_CT.dbo.COLUMNAS C ON C.IDCOLUMNA = UC.IDCOLUMNA AND C.IDPANTALLA = @IDVENTANA AND C.HTML IS NOT NULL
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC ON UC.IDCAMPO = EC.IDCAMPO AND EC.IDEMPRESA = @IDEMPRESA
LEFT JOIN <#SESSION.DB/>.dbo.LISTAS_PRECIO LP ON UC.IDLISTA_PRECIO = LP.IDLISTA_PRECIO AND LP.IDEMPRESA = @IDEMPRESA AND LP.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS IM ON UC.IDIMPUESTO = IM.IDIMPUESTO AND IM.IDEMPRESA = @IDEMPRESA   AND IM.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.PRODUCTOS_COMISIONES COM ON UC.IDCOMISION = COM.IDPRODUCTO_COMISION AND COM.IDEMPRESA = @IDEMPRESA  AND COM.STATUS = 1
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CAT ON CAT.IDEMPRESA = @IDEMPRESA AND CAT.IDCATALOGO = UC.IDCATALOGO 
LEFT JOIN SALESUP_CT.DBO.MONEDAS MON ON MON.IDMONEDA=LP.IDMONEDA
WHERE UC.IDUSUARIO = @IDUSUARIO AND UC.VISIBLE = 1 AND UC.IDPANTALLA = @IDVENTANA 
ORDER BY UC.ORDEN

SELECT @THEAD AS THEAD , @HTML AS HTML,@IDVENTANA AS IDVENTANA