//[iduc|Integer,v|Integer,session.idusuario|Untyped,idventana|Integer,session.db|Untyped,vistaActual|Integer,]
--UPDATE 
DECLARE @IDUSUARIOCOLUMNA INT, @V INT, @ORDEN INT, @IDUSUARIO INT, @IDVENTANA INT, @ORDENACTUAL INT, @vistaActual INT

SET @IDUSUARIOCOLUMNA = ISNULL(:IDUC,0)
SET @V = ISNULL(:V,0)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDVENTANA = ISNULL(:IDVENTANA,0)
SET @vistaActual = CAST(:vistaActual AS INT)

IF @V = 1
BEGIN
	 SELECT TOP 1 @ORDEN = ORDEN FROM <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS 
	 WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDVENTANA ORDER BY ORDEN DESC
	 
	 SET @ORDEN = @ORDEN + 1
	 
	 IF @ORDEN IS NULL 
	 	SET @ORDEN = 1
END

IF @V = 0
BEGIN
	 SELECT @ORDENACTUAL = ORDEN FROM <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS WHERE IDUSUARIOCOLUMNA = @IDUSUARIOCOLUMNA
	 UPDATE <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS SET ORDEN = ORDEN-1 
	 WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDVENTANA AND ORDEN > @ORDENACTUAL
END

UPDATE <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS SET VISIBLE = @V , ORDEN = @ORDEN
WHERE IDUSUARIOCOLUMNA = @IDUSUARIOCOLUMNA

IF @IDVENTANA = 2 BEGIN EXEC <#SESSION.DB/>.dbo.SP_COMPILA_CONSULTA @IDUSUARIO, @IDVENTANA, @vistaActual, '' END