//[session.idempresa|Untyped,session.idusuario|Untyped,periodo|Integer,anio|Integer,session.db|Untyped,tku|Text,]
--SELECT

DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @TIPOREPORTE INT
DECLARE @ANIO INT

SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TIPOREPORTE=CAST(ISNULL(:PERIODO,0) AS INT)
SET @ANIO=CAST(ISNULL(:ANIO,YEAR(GETDATE())) AS INT)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_CLIENTES_CONTINUIDAD_CABECERA @IDEMPRESA, @IDUSUARIO, @TIPOREPORTE, @ANIO