//[session.idusuario|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,session.nivel|Untyped,session.convertcode|Untyped,session.db|Untyped,]
--SELECT


DECLARE @FECHA1 DATETIME
DECLARE @FECHA2 DATETIME
DECLARE @IDUSUARIO INT 
DECLARE @IDEMPRESA INT 
DECLARE @IDGRUPO INT
DECLARE @NIVEL INT 
DECLARE @CONVERTCODE INT 

SET @FECHA1=DATEADD(mm, DATEDIFF(m,0,getdate() )-0, 0)    
SET @FECHA2=GETDATE()
SET @IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @IDEMPRESA =<#SESSION.IDEMPRESA/>
SET @IDGRUPO=<#SESSION.IDGRUPO/>
SET @NIVEL=<#SESSION.NIVEL/>
SET @CONVERTCODE= <#SESSION.CONVERTCODE/>




EXEC <#SESSION.DB/>.DBO.SP_REPORTE_COBROS_Y_COMISIONES @IDUSUARIO,@IDEMPRESA,@IDGRUPO,@NIVEL,@CONVERTCODE