//[name|Text,pk|Text,session.db|Untyped,value|Text,session.idempresa|Untyped,]
--UPDATE 
/*PROTEGIDO*/
DECLARE @ACTUALIZA VARCHAR(MAX), @TKCOM VARCHAR(MAX), @VALOR VARCHAR(MAX)
DECLARE @IDCOMPANIA INT, @IDEMPRESA INT
SET @ACTUALIZA = ISNULL(:NAME,'')
SET @TKCOM = ISNULL(:PK,'')
SET @VALOR = <#SESSION.DB/>.dbo.PreparaCadena(:VALUE)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TKCOM AND IDEMPRESA = @IDEMPRESA

IF @ACTUALIZA = 'Empresa'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET EMPRESA = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET EMPRESA = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Corporativo'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET IDCOMPANIAGRUPO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDCOMPANIAGRUPO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Industria'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET IDINDUSTRIA = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDINDUSTRIA = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Telefono'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET TELEFONOCORPORATIVO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET TELEFONOCORPORATIVO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Url'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET URL = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET URL = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'nEmpleados'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET NEMPLEADOS = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET NOEMPLEADOS = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Pais'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET IDPAIS = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDPAIS = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Estado'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET IDESTADO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDESTADO = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Ciudad'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET CIUDAD = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET CIUDAD = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Cp'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET CODIGOPOSTAL = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET CODIGOPOSTAL = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Calle'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET DIRECCION1 = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET DIRECCION1 = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

IF @ACTUALIZA = 'Colonia'
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.COMPANIAS SET DIRECCION2 = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET DIRECCION2 = @VALOR WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA
END

