//[session.idempresa|Untyped,tconsulta|Integer,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @TIPOCOSULTA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TIPOCOSULTA = CAST(ISNULL(:tConsulta,0) AS INT)


IF @TIPOCOSULTA = 1
BEGIN
	SELECT IDCOMPANIAGRUPO as value, COMPANIAGRUPO as Opcion 
	FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS 
	WHERE IDEMPRESA = @IDEMPRESA
	ORDER BY COMPANIAGRUPO
END
ELSE
BEGIN
	SELECT IDCOMPANIAGRUPO as Id, COMPANIAGRUPO as GrupoEmpresarial 
	FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS 
	WHERE IDEMPRESA = @IDEMPRESA
	ORDER BY COMPANIAGRUPO
END


