//[tkcom|Text,c|Integer,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
DECLARE @IDCOMPANIA INT
DECLARE @TKCOM VARCHAR(64)
DECLARE @C INT 

DECLARE @IDUSUARIO INT
SET @IDUSUARIO = <#SESSION.IDUSUARIO/> 

SET @TKCOM = ISNULL(:TKCOM, '')
SET @C=ISNULL(:C, 0)
IF ISNUMERIC(@C)=1 BEGIN SET @IDCOMPANIA = CAST(@C AS INT) END ELSE BEGIN SET @IDCOMPANIA = 0 END

IF @TKCOM != '' BEGIN SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TKCOM  END

SELECT 
<#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa(@IDUSUARIO,C.IdCompania) AS puedeUtilizarEmpresa, 
U.tku, C.tkCom, LTRIM(RTRIM(u.NOMBRE)) + ' ' + ISNULL(LTRIM(RTRIM(U.APELLIDOS)),'') + ' ('+LTRIM(RTRIM(U.INICIALES))+')'  AS duenioEmpresa,
C.IdCompania, C.Empresa, C.IdIndustria, C.IdCompaniaGrupo, C.Url, C.TelefonoCorporativo, C.Direccion1, C.Direccion2, 
C.Ciudad, C.CodigoPostal, C.IdEstado, C.IdPais, C.nEmpleados,
EI.Industria, CG.CompaniaGrupo as Grupo, PA.Pais, E.Estado,
C.IDCATALOGOOPCION1 AS Com_OpcionCatalogo1, C.IDCATALOGOOPCION2 AS Com_OpcionCatalogo2, C.IDCATALOGOOPCION3 AS Com_OpcionCatalogo3,
C.NUMERO_INTERIOR as NumInterior, C.NUMERO_EXTERIOR as NumExterior, 
C.CCAMPO1 as Campo1C, C.CCAMPO2 as Campo2C, C.CCAMPO3 as Campo3C, C.CCAMPO4 as Campo4C, C.CCAMPO5 as Campo5C,
C.CCAMPO6 as Campo6C, C.CCAMPO7 as Campo7C, C.CCAMPO8 as Campo8C, C.CCAMPO9 as Campo9C, C.CCAMPO10 as Campo10C,
M.idMunicipio
FROM 
<#SESSION.DB/>.dbo.COMPANIAS C
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = C.IDINDUSTRIA 
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = C.IDCOMPANIAGRUPO 
LEFT JOIN <#SESSION.DB/>.dbo.PAISES PA ON PA.IDPAIS = C.IDPAIS
LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON E.IDESTADO = C.IDESTADO  
LEFT JOIN SALESUP_CT.dbo.MUNICIPIOS M ON M.IDESTADO = C.IDESTADO AND M.IDPAIS = C.IDPAIS AND M.IDMUNICIPIO = C.IDMUNICIPIO 
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON C.IDUSUARIO = U.IDUSUARIO 
WHERE IDCOMPANIA = @IDCOMPANIA
