//[session.idempresa|Untyped,industria|Text,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @EXISTE INT
DECLARE @INDUSTRIA VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @INDUSTRIA = <#SESSION.DB/>.dbo.PreparaCadena(:INDUSTRIA)

SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS WHERE IDEMPRESA = @IDEMPRESA AND INDUSTRIA = @INDUSTRIA
	   
IF @EXISTE = 0
BEGIN
  INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS (IDEMPRESA, INDUSTRIA) VALUES(@IDEMPRESA, @INDUSTRIA)
END

SELECT TOP 1 IDINDUSTRIA AS Id FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS WHERE IDEMPRESA = @IDEMPRESA AND INDUSTRIA = @INDUSTRIA ORDER BY 1 DESC