//[tkcom|Text,session.idusuario|Untyped,session.crearempresas|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDCOMPANIA INT, @CREAREMPRESAS INT
DECLARE @TKCOM VARCHAR(64)
SET @IDCOMPANIA = 0
SET @TKCOM = dbo.ValidaToken(ISNULL(:TKCOM,'')) 

DECLARE @IDUSUARIO INT
SET @IDUSUARIO = <#SESSION.IDUSUARIO/> 
SET @CREAREMPRESAS = <#SESSION.CREAREMPRESAS/>
SELECT 
CASE WHEN <#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa(@IDUSUARIO,C.IdCompania) = 1 AND @CREAREMPRESAS = 1 THEN 1 ELSE 0 END AS puedeEditarEmpresa, 
C.IdCompania, C.Empresa, C.IdIndustria, EI.Industria, C.TelefonoCorporativo as telefonoEmpresa, US.nombre+' '+US.apellidos+' ('+US.iniciales+')' as Ejecutivo, US.IDUSUARIO,  CG.IDCOMPANIAGRUPO AS IdCompaniaGrupo,CG.CompaniaGrupo as Grupo, 
C.Direccion1 AS Calle, C.Direccion2 as Colonia, C.Ciudad, C.CodigoPostal as Cp, C.URL AS Web, C.IdEstado, EST.Estado, PAI.Pais , C.IdPais, C.nEmpleados
, CG.tkcg as Tkcg, EI.Tkind as Tkind, 
C.IDCATALOGOOPCION1 AS IdCat1, CO1.OPCION AS Cat1,
(SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(C1.Catalogo,'/') WHERE OCCURENCEID= 1) as Catalogo1, C1.TKCA AS Tkca1,
C1.IDCATALOGO AS IdCatalogo1,
C.IDCATALOGOOPCION2 AS IdCat2, CO2.OPCION AS Cat2,
(SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(C2.Catalogo,'/') WHERE OCCURENCEID= 1) as Catalogo2, C2.TKCA AS Tkca2,
C2.IDCATALOGO AS IdCatalogo2,
C.IDCATALOGOOPCION3 AS IdCat3, CO3.OPCION AS Cat3, 
(SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(C3.Catalogo,'/') WHERE OCCURENCEID= 1) as Catalogo3, C3.TKCA AS Tkca3,
C3.IDCATALOGO AS IdCatalogo3, M.Municipio, M.idMunicipio,
C.NUMERO_INTERIOR as NumInterior, C.NUMERO_EXTERIOR as NumExterior, 
C.CCAMPO1 as Campo1C, C.CCAMPO2 as Campo2C, C.CCAMPO3 as Campo3C, C.CCAMPO4 as Campo4C, C.CCAMPO5 as Campo5C,
C.CCAMPO6 as Campo6C, C.CCAMPO7 as Campo7C, C.CCAMPO8 as Campo8C, C.CCAMPO9 as Campo9C, C.CCAMPO10 as Campo10C,@TKCOM AS TKCOM
FROM <#SESSION.DB/>.dbo.COMPANIAS C
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS US ON US.IDUSUARIO = C.IDUSUARIO
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = C.IDCOMPANIAGRUPO
LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = C.IDINDUSTRIA
LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS = C.IDPAIS
LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS EST ON EST.IDESTADO = C.IDESTADO AND EST.IDPAIS = C.IDPAIS
LEFT JOIN SALESUP_CT.dbo.MUNICIPIOS M ON M.IDESTADO = C.IDESTADO AND M.IDPAIS = C.IDPAIS AND M.IDMUNICIPIO = C.IDMUNICIPIO 
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES CO1 ON CO1.IDCATALOGOOPCION = C.IDCATALOGOOPCION1 LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS C1 ON CO1.IDCATALOGO = C1.IDCATALOGO 
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES CO2 ON CO2.IDCATALOGOOPCION = C.IDCATALOGOOPCION2 LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS C2 ON CO2.IDCATALOGO = C2.IDCATALOGO
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES CO3 ON CO3.IDCATALOGOOPCION = C.IDCATALOGOOPCION3 LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS C3 ON CO3.IDCATALOGO = C3.IDCATALOGO
WHERE TKCOM = @TKCOM