//[session.idempresa|Untyped,session.db|Untyped,empresa|Text,estado|Text,pais|Text,]
--SELECT
DECLARE @IDEMPRESA INT, @IDINDUSTRIA INT, @EXISTE INT, @IDCOMPANIAGRUPO INT
DECLARE @EMPRESA VARCHAR(MAX), @IDESTADO VARCHAR(MAX), @IDPAIS VARCHAR(MAX)
DECLARE @IDUSUARIO INT
SET @IDUSUARIO = <#SESSION.IDUSUARIO/> 
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @EMPRESA =  <#SESSION.DB/>.dbo.PreparaCadena(:EMPRESA)
SET @IDESTADO = ISNULL(:ESTADO,'')
SET @IDPAIS = ISNULL(:PAIS,'')

SELECT TOP 1 @IDINDUSTRIA = IDINDUSTRIA FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS WHERE IDEMPRESA = @IDEMPRESA ORDER BY 1
SELECT TOP 1 @IDCOMPANIAGRUPO = IDCOMPANIAGRUPO FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA ORDER BY 1

SET @EXISTE = 0 

SELECT @EXISTE = (CASE WHEN EXISTS (SELECT IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE IDEMPRESA = @IDEMPRESA AND EMPRESA = @EMPRESA) THEN 1 ELSE 0 END)
	   
IF @EXISTE = 0
BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.COMPANIAS(IDEMPRESA, IDINDUSTRIA, IDCOMPANIAGRUPO, EMPRESA, IDESTADO, IDPAIS, IDUSUARIO) VALUES ( @IDEMPRESA, @IDINDUSTRIA, @IDCOMPANIAGRUPO, @EMPRESA, @IDESTADO, @IDPAIS, @IDUSUARIO)
END

SELECT TOP 1 IdCompania AS Id, IdIndustria, @EXISTE AS Existe, @IDESTADO AS ESTADO, @IDPAIS AS PAIS 
FROM <#SESSION.DB/>.dbo.COMPANIAS 
WHERE IDEMPRESA = @IDEMPRESA AND EMPRESA = @EMPRESA AND IDINDUSTRIA = @IDINDUSTRIA 
ORDER BY 1 DESC