//[tkcom|Text,session.idempresa|Untyped,session.db|Untyped,]
--UPDATE
DECLARE @IDEMPRESA INT, @IDCOMPANIA INT
DECLARE @TKCOM VARCHAR(64)
SET @TKCOM=dbo.ValidaToken(ISNULL(:TKCOM,''))
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SELECT TOP 1 @IDCOMPANIA = IDCOMPANIA FROM  <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TKCOM
IF @IDCOMPANIA IS NOT NULL
BEGIN
  UPDATE <#SESSION.DB/>.dbo.PROSPECTOS  SET IDCOMPANIA = NULL WHERE IDEMPRESA = @IDEMPRESA AND IDCOMPANIA = @IDCOMPANIA
  DELETE FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE IDEMPRESA = @IDEMPRESA AND IDCOMPANIA = @IDCOMPANIA
  INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) 
  VALUES (25,@IDCOMPANIA,1,@IDEMPRESA,GETDATE())
END