//[session.idempresa|Untyped,tconsulta|Integer,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @TIPOCOSULTA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TIPOCOSULTA = CAST(ISNULL(:tConsulta,0) AS INT)


IF @TIPOCOSULTA = 1
BEGIN
	SELECT IdIndustria as value, Industria as Opcion
	FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS 
	WHERE IDEMPRESA = @IDEMPRESA
	ORDER BY INDUSTRIA
END
ELSE
BEGIN
	SELECT IdIndustria, Industria 
	FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS 
	WHERE IDEMPRESA = @IDEMPRESA
	ORDER BY INDUSTRIA
END

