//[tktr|Text,session.idusuario|Untyped,session.convertcode|Untyped,idtr|Integer,session.db|Untyped,]
--select

DECLARE @TKTR VARCHAR(64)
DECLARE @IDUSUARIO INT, @CONVERTCODE INT, @IDTAREA INT
SET @TKTR = dbo.ValidaToken(ISNULL(:tktr,''))
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @IDTAREA =ISNULL(:IDTR,0)
SELECT 
T.TITULO as Asunto, 
CASE WHEN ISNULL(T.IDPROSPECTO,0) > 0 THEN P.NOMBRE + ' ' + ISNULL(P.APELLIDOS,'') ELSE '' END AS Contacto,
VT.Estado, T.IDESTADO AS EdoActual, T.IDREALIZADOR AS IdRealizador,
U1.NOMBRE + ' ' + ISNULL(U1.APELLIDOS,'') AS De, U2.NOMBRE + ' ' + ISNULL(U2.APELLIDOS,'') AS Para,
CONVERT(VARCHAR(10),T.FECHA_CREACION,103) AS CreadoEl,
SALESUP_CT.dbo.ObtieneHora(T.FECHA_CREACION) as CreadoHora,
CONVERT(VARCHAR(10),T.FECHA_VENCIMIENTO,103) AS VenceEl, 
CONVERT(VARCHAR(10),T.FECHA_VENCIMIENTO,@CONVERTCODE) AS Vencimiento,
SALESUP_CT.dbo.ObtieneHora(T.FECHA_VENCIMIENTO) as VenceHora,
CONVERT(VARCHAR(10),T.FECHA_PROPUESTA,@CONVERTCODE) AS Propuesta,
SALESUP_CT.dbo.ObtieneHora(T.FECHA_PROPUESTA) as PropuestaHora,
(CASE WHEN T.IDPADRE IS NOT NULL AND T.RECURRENCIA>0 THEN '1' ELSE '' END) AS tPadre,
CASE WHEN T.FECHA_VENCIMIENTO < GETDATE() THEN '1' ELSE '' END AS Vencido,
CASE WHEN (T.IDESTADO = 1 OR T.IDESTADO = 4 OR T.IDESTADO = 6) AND T.IDREALIZADOR = @IDUSUARIO THEN '1' ELSE '' END EnProceso,
CASE WHEN T.IDESTADO = 2 AND T.IDINICIADOR = @IDUSUARIO THEN '1' ELSE '' END Completado,
CASE WHEN T.IDESTADO != 5 AND T.IDINICIADOR = @IDUSUARIO THEN '1' ELSE '' END Cancelado,
CASE WHEN T.IDINICIADOR = @IDUSUARIO THEN '1' ELSE '' END Editar, @TKTR AS TKTR, @IDTAREA AS IDTR
FROM 
<#SESSION.DB/>.dbo.TAREAS T
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = T.IDPROSPECTO
JOIN SALESUP_CT.dbo.V_TAREAS_ESTADOS VT ON VT.IDESTADO = T.IDESTADO 
JOIN <#SESSION.DB/>.dbo.USUARIOS U1 ON U1.IDUSUARIO = T.IDINICIADOR
JOIN <#SESSION.DB/>.dbo.USUARIOS U2 ON U2.IDUSUARIO = T.IDREALIZADOR
WHERE (T.TKTR = @TKTR OR T.IDTAREA = @IDTAREA)

