//[tktr|Text,session.db|Untyped,]
--select

DECLARE @TKTR VARCHAR(64)

SET @TKTR = dbo.ValidaToken(ISNULL(:tktr,''))

SELECT 
TS.IDTAREASEGUIMIENTO AS Id,
CONVERT(VARCHAR(10),TS.FECHAHORA,103) as Fecha, 
SALESUP_CT.dbo.ObtieneHora(TS.FECHAHORA) as Hora,
TS.Comentario, U.Iniciales,
CASE WHEN (TS.LATITUDE IS NULL OR TS.LATITUDE = '') AND (TS.LONGITUDE IS NULL OR TS.LONGITUDE = '') THEN '' ELSE '1' END AS Coordenadas,
T.IDTAREA AS Idtarea
FROM <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO TS 
JOIN <#SESSION.DB/>.dbo.TAREAS T ON T.TKTR = @TKTR
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = TS.IDUSUARIO
WHERE TS.IDTAREA = T.IDTAREA ORDER BY 1 DESC

