//[session.idusuario|Untyped,session.convertcode|Untyped,tktr|Text,vencimiento|Integer,responsable|Integer,hora|Text,vence|Text,paraquien|Text,asunto|Text,session.db|Untyped,]
--UPDATE 
/*PROTEGIDO*/

DECLARE @TKTR VARCHAR(64), @ASUNTO VARCHAR(MAX), @ASUNTOACTUAL VARCHAR(MAX), @HORA VARCHAR(MAX), @COMENTARIOSISTEMA VARCHAR(MAX)
DECLARE @REALIZADORANTERIOR VARCHAR(MAX), @NUEVOREALIZADOR VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @VENCIMIENTO INT, @RESPONSABLE INT, @IDREALIZADOR INT, @IDTAREA INT
DECLARE @CONVERTCODE INT, @PARAQUIEN INT, @TIPOSUCESO INT, @IDPROSPECTO INT, @MASTIEMPO INT, @IDTAREASEGUIMIENTO INT
DECLARE @FECHAVENCIMIENTO DATETIME, @VENCE DATETIME, @FECHAHOY DATETIME
DECLARE @STRVENCE VARCHAR(64), @P VARCHAR(MAX)

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

SET @P = ''
SET @TKTR = ISNULL(:tktr,'')
SET @VENCIMIENTO = ISNULL(:Vencimiento,0)
SET @RESPONSABLE = ISNULL(:Responsable,0)
SET @HORA = ISNULL(:HORA,'')
SET @STRVENCE = ISNULL(:VENCE,'')+' '
SET @VENCE = CONVERT(DATETIME,@STRVENCE+@HORA, @CONVERTCODE)
SET @PARAQUIEN = ISNULL(:ParaQuien,'')
SET @ASUNTO = ISNULL(:ASUNTO,'')
SET @FECHAHOY = GETDATE()

SET @COMENTARIOSISTEMA = ''
SELECT @IDTAREA = IDTAREA, @ASUNTOACTUAL = TITULO, @FECHAVENCIMIENTO = FECHA_VENCIMIENTO, @IDREALIZADOR = IDREALIZADOR , @MASTIEMPO = ISNULL(MASTIEMPO,0)
FROM <#SESSION.DB/>.dbo.TAREAS WHERE TKTR = @TKTR



IF @VENCIMIENTO = 1 
BEGIN

	SET @COMENTARIOSISTEMA = 'La fecha de vencimiento se ha modificado, fecha anterior '+SALESUP_CT.dbo.FechaFormato(@FECHAVENCIMIENTO,2) 
	INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
	VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)
	
	SET @MASTIEMPO = @MASTIEMPO + 1
	
	/*Suceso tarea*/
	SET @TIPOSUCESO = 45
	EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @CONVERTCODE, @COMENTARIOSISTEMA, @IDTAREA
END

IF @RESPONSABLE = 1
BEGIN
    SELECT @REALIZADORANTERIOR = NOMBRE + ' ' + ISNULL(APELLIDOS,'') FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDUSUARIO = @IDREALIZADOR
	SELECT @NUEVOREALIZADOR = NOMBRE + ' ' + ISNULL(APELLIDOS,'') FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDUSUARIO = @PARAQUIEN
	
	SET @COMENTARIOSISTEMA = 'La tarea ha sido reasignada a '+@NUEVOREALIZADOR+', responsable anterior ('+@REALIZADORANTERIOR+')' 
	INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
	VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)
	
	/*Suceso tarea*/
	SET @TIPOSUCESO = 32
	EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @CONVERTCODE, @COMENTARIOSISTEMA, @IDTAREA
END


IF @ASUNTOACTUAL <> @ASUNTO
BEGIN
	SET @COMENTARIOSISTEMA = 'El asunto ha sido modificado, asunto anterior ('+@ASUNTOACTUAL+')' 
	INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
	VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)
END 
SELECT @P = CAST(TP.IDPROSPECTO AS VARCHAR) FROM (SELECT IDPROSPECTO FROM <#SESSION.DB/>.dbo.TAREAS WHERE IDTAREA = @IDTAREA) AS TP
SELECT TOP 1 @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO 
FROM <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO 
WHERE IDTAREA = @IDTAREA ORDER BY 1 DESC
	
UPDATE <#SESSION.DB/>.dbo.TAREAS 
SET IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO,
MASTIEMPO = @MASTIEMPO, FECHA_VENCIMIENTO = @VENCE, TITULO = @ASUNTO, IDREALIZADOR = @PARAQUIEN
WHERE IDTAREA = @IDTAREA
EXEC <#SESSION.DB/>.dbo.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1