//[tkp|Text,idu|Text,idg|Text,session.idempresa|Untyped,session.db|Untyped,]
--SELECT

DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @NU INT, @LoTiene INT, @N INT, @IDUSUARIO INT, @L INT
DECLARE @TKP VARCHAR(64), @LTIDUSUARIOS VARCHAR(MAX), @USUARIOSNOCOMPARTIDOS VARCHAR(MAX), @IdsNoCompartidos VARCHAR(MAX)
DECLARE @LTGRUPOS VARCHAR(MAX), @USUARIOSGRUPOS VARCHAR(MAX)
DECLARE @TBTEMP TABLE (Ids INT, Usuario VARCHAR(MAX), LoTiene INT)

SET @TKP = dbo.ValidaToken(ISNULL(:TKP,'')) 
SET @LTIDUSUARIOS = ISNULL(:IDU,'')
SET @LTGRUPOS = ISNULL(:IDG,'')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @NU = 0
SET @LoTiene = 0
SET @N = 1
SET @IdsNoCompartidos = ''
SET @USUARIOSGRUPOS = ''


SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE TKP = @TKP AND IDEMPRESA = @IDEMPRESA

SELECT @USUARIOSGRUPOS = @USUARIOSGRUPOS + CAST(IDUSUARIO AS VARCHAR(MAX)) +',' 
FROM <#SESSION.DB/>.dbo.USUARIOS WHERE ACTIVO = 1 AND IDGRUPO IN (SELECT SplitValue FROM SALESUP_CT.dbo.Split(@LTGRUPOS, ','))

SET @LTIDUSUARIOS = @LTIDUSUARIOS + @USUARIOSGRUPOS
SELECT @NU = COUNT(*) FROM SALESUP_CT.dbo.Split(@LTIDUSUARIOS, ',')
WHILE @N <= @NU
BEGIN
	 SELECT @IDUSUARIO = SPLITVALUE FROM SALESUP_CT.dbo.Split(@LTIDUSUARIOS, ',') WHERE OccurenceId = @N
	
	 INSERT @TBTEMP (Ids, USUARIO, LOTIENE)
	 SELECT U.IDUSUARIO, U.Nombre + ' ' +ISNULL(U.APELLIDOS, ''), COUNT(PA.IDPROSPECTO) FROM <#SESSION.DB/>.dbo.USUARIOS U 
	 LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = @IDPROSPECTO AND U.IDUSUARIO = PA.IDUSUARIO 
	 WHERE U.IDUSUARIO = @IDUSUARIO
	 GROUP BY U.IDUSUARIO, U.NOMBRE, U.APELLIDOS
	 
	 SET @N = @N + 1
END

SET @USUARIOSNOCOMPARTIDOS = ''
SELECT @USUARIOSNOCOMPARTIDOS = @USUARIOSNOCOMPARTIDOS + USUARIO + ', ', @IdsNoCompartidos = @IdsNoCompartidos + CAST(Ids AS VARCHAR(MAX)) + ', '  FROM @TBTEMP WHERE LOTIENE = 0 GROUP BY USUARIO, IDS

SET @L = LEN(@USUARIOSNOCOMPARTIDOS)
IF @L > 1 BEGIN SET @USUARIOSNOCOMPARTIDOS = SUBSTRING( @USUARIOSNOCOMPARTIDOS , 1, @L-1) END
	
SELECT @USUARIOSNOCOMPARTIDOS AS NoCompartidos, @IdsNoCompartidos as IdsNoCompartidos
