//[session.idusuario|Untyped,session.convertcode|Untyped,tktr|Text,edoant|Integer,edo|Integer,c|Text,session.db|Untyped,]
--UPDATE

DECLARE @TKTR VARCHAR(64), @ESTADOANTERIOR VARCHAR(MAX), @ESTADO VARCHAR(MAX), @P VARCHAR(MAX)
DECLARE @COMENTARIO VARCHAR(MAX), @COMENTARIOSISTEMA VARCHAR(MAX), @ASUNTO VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @IDTAREA INT, @IDESTADOANTERIOR INT, @IDESTADO INT
DECLARE @IDTAREASEGUIMIENTO INT, @TIPOSUCESO INT, @IDPROSPECTO INT, @CONVERTCODE INT
DECLARE @FECHAHOY DATETIME

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @TKTR = dbo.ValidaToken(ISNULL(:TKTR,''))
SET @IDESTADOANTERIOR = ISNULL(:EdoAnt,0)
SET @IDESTADO = ISNULL(:Edo,0)
SET @COMENTARIO = ISNULL(:C,'')
SET @P = ''
SET @FECHAHOY = GETDATE()

SELECT @IDTAREA = IDTAREA, @IDPROSPECTO = IDPROSPECTO, @ASUNTO = TITULO FROM <#SESSION.DB/>.dbo.TAREAS WHERE TKTR = @TKTR
SELECT @ESTADO = ESTADO, @TIPOSUCESO = IDSUCESO FROM SALESUP_CT.dbo.V_TAREAS_ESTADOS WHERE IDESTADO = @IDESTADO 
SELECT @ESTADOANTERIOR = ESTADO FROM SALESUP_CT.dbo.V_TAREAS_ESTADOS WHERE IDESTADO = @IDESTADOANTERIOR 

SET @COMENTARIOSISTEMA = 'Se ha cambiado el estado de '+@ESTADOANTERIOR+' a '+@ESTADO
SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))

/*SEGUIMIENTO TAREA*/
INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)

/*SEGUIMIENTO TAREA SI SE AGREGO COMENTARIO*/
IF @COMENTARIO <> '' BEGIN 
   INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
   VALUES (@IDUSUARIO, GETDATE(), @COMENTARIO, @IDTAREA) 
END

SELECT TOP 1 @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO 
FROM <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO 
WHERE IDTAREA = @IDTAREA ORDER BY 1 DESC

/*Suceso tarea*/
EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @CONVERTCODE, @COMENTARIOSISTEMA, @IDTAREA

IF @IDPROSPECTO IS NOT NULL BEGIN
   INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, TIPO_SEGUIMIENTO, FECHAHORA, COMENTARIO, SISTEMA, IDRELACIONADO )
   VALUES (@IDPROSPECTO, @IDUSUARIO, 7, GETDATE(), @ASUNTO + ' - ' +@COMENTARIOSISTEMA  , 1, @IDTAREA)
END
/*CAMBIAR ESTADO TAREA*/
UPDATE <#SESSION.DB/>.dbo.TAREAS SET IDESTADO = @IDESTADO, IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO WHERE IDTAREA = @IDTAREA
EXEC <#SESSION.DB/>.dbo.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1
