//[session.db|Untyped,idseguimiento|Integer,idtarea|Integer,]
-- SELECT
SELECT TS.LATITUDE,TS.LONGITUDE,TS.COMENTARIO, <#SESSION.DB/>.DBO.TIEMPO_TXT (TS.FECHAHORA,GETDATE()) AS ULTIMO_CONTACTO_TIEMPO, T.TITULO, ISNULL(:IDSEGUIMIENTO,0)  AS IDSEGUIMIENTO, ISNULL(:IDTAREA,0) AS IDTAREA FROM <#SESSION.DB/>.DBO.TAREAS_SEGUIMIENTO TS, <#SESSION.DB/>.DBO.TAREAS T 
WHERE TS.IDTAREA = T.IDTAREA AND TS.IDTAREASEGUIMIENTO = ISNULL(:IDSEGUIMIENTO,0) AND TS.IDTAREA = ISNULL(:IDTAREA,0)