//[idpl|Text,idpieza|Text,session.db|Untyped,]
--select
DECLARE @TB TABLE(Idn INT IDENTITY, Nombre VARCHAR(MAX), Archivo VARCHAR(MAX))
DECLARE @ANEXOS VARCHAR(MAX)
DECLARE @IDPLANTILLA INT , @IDPIEZA INT
SET @IDPLANTILLA = CAST( :idpl AS INT)
SET @IDPIEZA = CAST(:IDPIEZA AS INT)

IF @IDPLANTILLA > 0
BEGIN
	 SELECT @ANEXOS = REPLACE(CONVERT(VARCHAR(MAX), ANEXOS), CHAR(10)+CHAR(13) , '|') 
	 FROM <#session.db/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA
END

IF @IDPIEZA > 0
BEGIN
	 SELECT @ANEXOS = REPLACE(CONVERT(VARCHAR(MAX), ANEXOS), CHAR(10)+CHAR(13) , '|') 
	 FROM <#session.db/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZA
END

INSERT INTO @TB (Nombre, Archivo)
SELECT REPLACE(SUBSTRING(SplitValue,25,LEN(SplitValue)),'_',' ') , REPLACE(SplitValue, '/','') 
FROM SALESUP_CT.DBO.Split(@ANEXOS,'|') WHERE SplitValue != ''

SELECT 
REPLACE( REPLACE(Nombre, CHAR(10)+CHAR(13) , '') , CHAR(13)+CHAR(10),'') as Nombre, 
REPLACE( REPLACE(Archivo, CHAR(10)+CHAR(13) , ''), CHAR(13)+CHAR(10), '') as Archivo 
FROM @TB