//[session.db|Untyped,session.idusuario|Untyped,idp|Integer,ud|Text,ed|Text,]
--INSERT
DECLARE @IDP INT
DECLARE @UD VARCHAR(MAX)
DECLARE @ED VARCHAR(MAX)
SET @IDP=ISNULL(:IDP,0)
SET @UD=ISNULL(:UD,'')
SET @ED=ISNULL(:ED,'')

INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO (IDUSUARIO, IDPROSPECTO, COMENTARIO)
VALUES (<#SESSION.IDUSUARIO/>, @IDP, 'Se ha referido el prospecto a '+@UD+' de la empresa '+@ED)

DECLARE @IDSEGUIM INT

SELECT TOP 1 @IDSEGUIM = IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPROSPECTO = @IDP ORDER BY IDSEGUIMIENTO DESC
EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>, 49, @IDP, 103, '', @IDSEGUIM