//[session.convertcode|Untyped,session.idempresa|Untyped,session.db|Untyped,session.idusuario|Untyped,filtros|Text,]
--SELECT
/*PROTEGIDO*/

DECLARE @CONVERTCODE INT = <#SESSION.CONVERTCODE/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @FILTROS VARCHAR(MAX) = ISNULL(:FILTROS,'')


EXEC <#SESSION.DB/>.DBO.SP_REPORTE_SMS @IDEMPRESA,@IDUSUARIO,@CONVERTCODE,@FILTROS,0