//[session.db|Untyped,idcompania|Integer,]
--select
DECLARE @IDCOMPANIA INT
SET @IDCOMPANIA=ISNULL(:IDCOMPANIA,0)
SELECT ISNULL(DIRECCION1,'') + ' ' + ISNULL(DIRECCION2,'') + ' ' + ISNULL(CIUDAD,'') AS DIRECCION, ISNULL(EMPRESA,'') AS NOMBRE,ISNULL(TELEFONOCORPORATIVO,'') AS TELEFONO,ISNULL(URL,'') AS URL 
from <#SESSION.DB/>.DBO.companias WHERE IDCOMPANIA = @IDCOMPANIA