//[filtroagrupardetalle|Integer,idelimina|Integer,session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @FILTROAGRUPARDETALLE INT 
DECLARE @CONDICIONETIQUETA VARCHAR(MAX)
DECLARE @IDELIMINAR INT
DECLARE @SQL VARCHAR(MAX)
SET @FILTROAGRUPARDETALLE = ISNULL(:FILTROAGRUPARDETALLE, 0)
SET @IDELIMINAR = ISNULL(:IdElimina,0)

SET @CONDICIONETIQUETA = ISNULL((CASE WHEN @FILTROAGRUPARDETALLE > 0 THEN ' AND IDETIQUETA <> '+CAST(@IDELIMINAR AS VARCHAR(1000)) ELSE '' END),'')

SET @SQL='
SELECT REPLACE(E.ETIQUETA, ''"'', '''') AS ETIQUETA,'+cast(@FILTROAGRUPARDETALLE AS VARCHAR(8000))+' AS FILTROAGRUPARDETALLE,'+CAST(@IDELIMINAR AS VARCHAR(8000))+' AS IDELIMINAR, * 
FROM <#SESSION.DB/>.DBO.ETIQUETAS E 
WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> '+@CONDICIONETIQUETA+' ORDER BY 1
'
EXEC(@SQL)

