//[session.idempresa|Untyped,etiquetasiniciales|Text,lista|Text,idprospecto|Integer,tkp|Text,session.db|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,]
--update
DECLARE @LISTA_ANTERIOR VARCHAR(8000)
DECLARE @LISTA_NUEVA VARCHAR(8000)
DECLARE @IDETIQUETA INT
DECLARE @IDETIQUETABORRAR INT
DECLARE @IDPROSPECTO INT
DECLARE @FECHA DATETIME
DECLARE @LISTA VARCHAR(8000)

DECLARE @IDEMPRESA INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SET @LISTA_ANTERIOR = ISNULL(:etiquetasiniciales,'')
SET @LISTA = ISNULL(:Lista,'')
SET @LISTA_NUEVA = (case when @LISTA='UNDEF' then @LISTA_ANTERIOR  else @LISTA end)
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @FECHA = GETDATE()

DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END

IF @IDPROSPECTO > 0
BEGIN
   DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WITH(ROWLOCK) 
   WHERE  IDPROSPECTO = @IDPROSPECTO AND IDETIQUETA IN ( SELECT A.splitvalue FROM  <#SESSION.DB/>.dbo.Split(@LISTA_ANTERIOR, ',') A LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTA_NUEVA, ',') N ON A.splitvalue = N.splitvalue WHERE N.splitvalue IS NULL GROUP BY  A.splitvalue) 
   
   INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) 
   SELECT 6,@IDPROSPECTO,A.splitvalue,1,<#SESSION.IDEMPRESA/>,GETDATE() 
   FROM <#SESSION.DB/>.dbo.Split(@LISTA_ANTERIOR, ',') A 
   LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTA_NUEVA, ',') N ON A.splitvalue = N.splitvalue  
   WHERE N.splitvalue IS NULL GROUP BY  A.splitvalue
 
   INSERT INTO  <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WITH(ROWLOCK)  (IDPROSPECTO, IDETIQUETA) 
   SELECT @IDPROSPECTO , N.splitvalue 
   FROM <#SESSION.DB/>.dbo.Split(@LISTA_NUEVA, ',') N 
   LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTA_ANTERIOR, ',') A ON A.splitvalue = N.splitvalue  
   WHERE A.splitvalue IS NULL AND N.splitvalue NOT IN (SELECT IDETIQUETA FROM <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WHERE IDPROSPECTO = @IDPROSPECTO) GROUP BY  N.splitvalue

  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = <#SESSION.IDEMPRESA/>
  DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
  INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE())
  
  EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO <#SESSION.IDUSUARIO/>,@FECHA

   EXEC  <#SESSION.DB/>.DBO.SP_ENVIA_AUTORESPONDER_ESPECIFICO <#SESSION.IDEMPRESA/>, @IDPROSPECTO, @LISTA_NUEVA

   EXEC  <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,4,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, '',''
END