//[idusuario|Integer,]
--select
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @DB VARCHAR(16)

IF (ISNUMERIC(ISNULL(:IDUSUARIO,0))=1)
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,0) AS INT)

IF (@IDUSUARIO IS NOT NULL)
  SELECT @DB = BD_ACTUAL , @IDEMPRESA=U.IDEMPRESA FROM USUARIOS U, EMPRESAS E WHERE E.IDEMPRESA = U.IDEMPRESA AND IDUSUARIO = @IDUSUARIO
DECLARE @SQL VARCHAR(8000)

SET @SQL =  ''
SET @SQL =  @SQL + ' SELECT TOP 25 '+CAST(@IDUSUARIO AS VARCHAR(1000))+' AS IDUSUARIO,01 AS '''+ @DB+''',' 
SET @SQL =  @SQL + '   P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS, TITULO, CORREO, EMPRESA, fase, origen,REPLACE(CAST(comentarios AS VARCHAR(MAX)), ''<br>'', '''') AS COMENTARIOS '
SET @SQL =  @SQL + '   FROM'
SET @SQL =  @SQL + '     '+@DB+'.dbo.PROSPECTOS P, '+@DB+'.dbo.PROSPECTOS_ASIGNADOS PA ,  '+@DB+'.dbo.PROSPECTOS_FASES F, '+@DB+'.dbo.PROSPECTOS_ORIGENES O '
SET @SQL =  @SQL + '   WHERE '
SET @SQL =  @SQL + '     P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(8)) +' AND  P.IDPROSPECTO = PA.IDPROSPECTO AND PA.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(8)) +' '
SET @SQL =  @SQL + '    AND P.IDFASE = F.IDFASE AND P.IDORIGEN = O.IDORIGEN AND P.DESCARTADO=0 AND P.ESOPORTUNIDAD=0  '
SET @SQL =  @SQL + '     ORDER BY FECHA_ULTIMOSEGUIMIENTO DESC' 
  

IF @DB IS NOT NULL
  EXEC ( @SQL)
ELSE
BEGIN
	 SET @SQL =  'SELECT TOP 1 * FROM '+@DB+'.dbo.PROSPECTOS WHERE IDUSUARIO = 0 '
	 EXEC ( @SQL)
END

 