//[idoportunidad|Integer,session.db|Untyped,tkop|Text,]
-- delete
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDOPORTUNIDAD INT 
DECLARE @TKOPORTUNIDAD VARCHAR(256) 

SET @TKOPORTUNIDAD =ISNULL(:TKOP, '') 

SET @IDOPORTUNIDAD= ISNULL(:IDOPORTUNIDAD,0)

DELETE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_TEMPLATES
WHERE TK=@TKOPORTUNIDAD