//[idimpuesto|Integer,session.idempresa|Untyped,session.db|Untyped,tk|Text,]
--DELETE 


DECLARE @IDIMPUESTO INT 
DECLARE @IDEMPRESA INT 
DECLARE @INDICE INT 
DECLARE @SQLTEXT VARCHAR(MAX) 
DECLARE @CAMPO VARCHAR(100) 
DECLARE @TK  VARCHAR(256) 

SET @TK = ISNULL(:TK, '') 
SELECT @IDIMPUESTO=IDIMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE TK = @TK  
SET @IDEMPRESA= '<#SESSION.IDEMPRESA/>'

SET @SQLTEXT=''
SELECT @INDICE=INDICE FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE 
IDEMPRESA=@IDEMPRESA AND IDIMPUESTO=@IDIMPUESTO

SET @CAMPO='IMPUESTO'+CAST(@INDICE AS VARCHAR(10))
SET @SQLTEXT= 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS 
SET '+@CAMPO+'=0'
+' WHERE IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(MAX))
EXEC (@SQLTEXT)


DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDEMPRESA=@IDEMPRESA AND IDIMPUESTO=@IDIMPUESTO
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS WITH(ROWLOCK) WHERE IDIMPUESTO = @IDIMPUESTO

