//[identificador|Integer,session.db|Untyped,session.idempresa|Untyped,]
--SELECT 
/*PROTEGIDO*/
DECLARE @IDENTIFICADOR INT 
SET @IDENTIFICADOR= ISNULL(:IDENTIFICADOR, 0)  

IF(@IDENTIFICADOR=1) 
 SELECT  IDLINEA_PRODUCTO AS IDLINEA, LINEA_PRODUCTO, TK AS TKLINEA_PRODUCTO
 FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO 
 WHERE IDEMPRESA= <#SESSION.IDEMPRESA/>
 ORDER BY LINEA_PRODUCTO ASC
ELSE 
 SELECT IDFASE, FASE, TK AS TKFASE
 FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES
  WHERE IDEMPRESA= <#SESSION.IDEMPRESA/>
  ORDER BY FASE ASC

 