//[producto|Numeric,pais|Text,]
DECLARE @IDPAIS VARCHAR(2)
DECLARE @IDPRODUCTO INT

SET  @IDPRODUCTO = CAST(ISNULL(:PRODUCTO,0) AS MONEY)
SET  @IDPAIS = ISNULL(:PAIS,'')

DECLARE @CODIGOMONEDA VARCHAR(3)
DECLARE @MONEDA VARCHAR(32)
DECLARE @PAIS VARCHAR(64)
DECLARE @DESCRIPCION VARCHAR(8000)


DECLARE @TC MONEY
DECLARE @PRECIO MONEY
SET @PRECIO = 129
SET @TC = 1
SET @CODIGOMONEDA  = 'MXN'
SET @MONEDA  = 'Pesos Mexicanos'
SET @PAIS  = 'México'

IF @IDPAIS != 'MX' SET @IDPAIS = 'US'

SELECT @PRECIO = 149 
SELECT @CODIGOMONEDA = CODIGO, @MONEDA = MONEDA,@TC = TC, @PAIS = PAIS, @DESCRIPCION = DESCRIPCION FROM CONTROL.VENTAS.DBO.MONEDAS M , CONTROL.VENTAS.DBO.PAISES P 
WHERE P.IDPAIS = M.IDPAIS AND P.IDPAIS = @IDPAIS

SELECT @TC AS TC,ROUND(@TC*@PRECIO,1) AS PRECIO, @CODIGOMONEDA AS CODIGO, @MONEDA as MONEDA, @PAIS AS PAIS, REPLACE(@DESCRIPCION,'.','.<BR />') AS DESCRIPCION, @IDPRODUCTO AS PRODUCTO

