//[session.idempresa|Untyped,session.db|Untyped,]
DECLARE @IDEMPRESA INT 


SET @IDEMPRESA=CAST(<#SESSION.IDEMPRESA/> AS INT)


SELECT IDMARCA, MARCA, STATUS, TK
FROM <#SESSION.DB/>.DBO.MARCAS

WHERE IDEMPRESA=@IDEMPRESA  
