//[session.idempresa|Untyped,session.db|Untyped,]
DECLARE @IDEMPRESA INT 
SET @IDEMPRESA=CAST(<#SESSION.IDEMPRESA/> AS INT)


SELECT /*IDLINEA_PRODUCTO,*/ LINEA_PRODUCTO, STATUS, TK
FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO
WHERE IDEMPRESA=@IDEMPRESA 