//[session.idempresa|Untyped,status|Integer,session.db|Untyped,idmoneda|Integer,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDMONEDA INT 
DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
SET @IDMONEDA=ISNULL(:IDMONEDA, 0)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @STATUS=ISNULL(:STATUS, -1)


IF(@STATUS=-1)
   SELECT STATUS FROM <#SESSION.DB/>.DBO.MONEDAS
   WHERE IDEMPRESAMONEDA=@IDMONEDA AND IDEMPRESA=@IDEMPRESA
ELSE 
 BEGIN 
  UPDATE <#SESSION.DB/>.DBO.MONEDAS
  SET STATUS=@STATUS
  WHERE IDEMPRESAMONEDA=@IDMONEDA AND IDEMPRESA=@IDEMPRESA
  SELECT STATUS FROM <#SESSION.DB/>.DBO.MONEDAS
  WHERE IDEMPRESAMONEDA=@IDMONEDA AND IDEMPRESA=@IDEMPRESA
 END 
