//[idprospecto|Integer,db|Text,]
--select
DECLARE @IDPROSPECTO INT
DECLARE @DB VARCHAR(16)

IF (ISNUMERIC(ISNULL(:IDPROSPECTO,0))=1)
SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,0) AS INT)

IF (@IDPROSPECTO IS NOT NULL) AND (ISNUMERIC(ISNULL(:DB,''))=1) 
  IF CAST(ISNULL(:DB,'') AS INT) BETWEEN 1 AND 5 
  SELECT @DB = 'SALESUP_DB'+ISNULL(:DB,'')
  
DECLARE @SQL VARCHAR(8000)

SET @SQL =  ''
SET @SQL =  @SQL + ' SELECT TOP 50 '''+@DB+''' AS DB,*'
SET @SQL =  @SQL + '   FROM '
SET @SQL =  @SQL + ' '  +@DB+'.dbo.PROSPECTOS_SEGUIMIENTO S, '+@DB+'.dbo.USUARIOS U '
SET @SQL =  @SQL + '   WHERE S.IDUSUARIO = U.IDUSUARIO AND ' 
SET @SQL =  @SQL + '     S.IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(8)) + ' ORDER BY FECHAHORA DESC' 
  

IF @DB IS NOT NULL
EXEC ( @SQL)
ELSE
BEGIN
	 SET @SQL =  'SELECT TOP 1 * FROM '+@DB+'.dbo.PROSPECTOS WHERE IDUSUARIO = 0 '
	 EXEC ( @SQL)
END
