//[actualiza|Integer,bandera|Integer,nombreimpuesto|Text,tasa|Numeric,session.idempresa|Untyped,idimpuesto|Integer,idimpuestonuevo|Integer,session.db|Untyped,tk|Text,]
--SELECT
DECLARE @NOMBREIMPUESTO VARCHAR(200) 
DECLARE @TASA FLOAT
DECLARE @IDEMPRESA INT 
DECLARE @BANDERA INT 
DECLARE @IDIMPUESTO INT 
DECLARE @IDIMPUESTONUEVO INT 
DECLARE @INDICE INT 
DECLARE @ACTUALIZA INT

DECLARE @INDIC INT 
DECLARE @IDIMP INT 
DECLARE @SQLTEXT VARCHAR(MAX) 
DECLARE @CAMPO VARCHAR(32)
DECLARE @T FLOAT
DECLARE @TK VARCHAR(256) 



SET @ACTUALIZA=ISNULL(:ACTUALIZA, 0)   
SET @BANDERA= CAST(ISNULL(:BANDERA, 0) AS INT)
SET @NOMBREIMPUESTO=ISNULL(:NOMBREIMPUESTO, '')
SET @TASA=CAST(ISNULL(:TASA, 0) AS FLOAT)
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'



SET @IDIMPUESTONUEVO=CAST(ISNULL(:IDIMPUESTONUEVO, 0) AS INT)
SET @INDICE = 1
SET @TK = ISNULL(:TK, '') 
IF(@TK!='') BEGIN SELECT @IDIMPUESTO=IDIMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE TK = @TK END  



IF(@BANDERA=0)
  BEGIN
     IF (EXISTS(SELECT IMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS  WHERE IMPUESTO=@NOMBREIMPUESTO AND IDEMPRESA=@IDEMPRESA))
	   BEGIN
	 	SELECT 'EXISTE' AS RESULTADO
		END
	 ELSE
	 BEGIN
	 SELECT TOP 1 @INDICE=INDICE FROM SALESUP_CT.DBO.V_INDICES WHERE INDICE NOT IN (SELECT ISNULL(INDICE,0) FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDEMPRESA=@IDEMPRESA ) 
	 
	 INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS  (IDEMPRESA, IMPUESTO, TASA, INDICE) VALUES (@IDEMPRESA, @NOMBREIMPUESTO, @TASA, @INDICE)
	 
	 SELECT TOP 1 @IDIMP=IDIMPUESTO, @INDIC=INDICE, @T=TASA FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS ORDER BY 1 DESC
	 
	 IF(@ACTUALIZA=1)
	   BEGIN 
		 SET @CAMPO='IMPUESTO'+CAST(@INDICE AS VARCHAR(10))
		 SET @SQLTEXT= 'UPDATE <#SESSION.DB/>.DBO.PRODUCTOS 
		 SET '+@CAMPO+'='+CAST(@T AS VARCHAR(MAX))
		 +' WHERE IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(MAX))
		 EXEC (@SQLTEXT)
	   END 
	   
	   EXEC <#SESSION.DB/>.DBO.SP_AGREGA_COLUMAS_PRODUCTOS @IDEMPRESA,@IDIMP,2
	   
	   SELECT 'INSERTADO' AS RESULTADO
	 END
  END
ELSE IF(@BANDERA=1) 
BEGIN
UPDATE  <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS 
SET    IMPUESTO=@NOMBREIMPUESTO,
   	   TASA=@TASA
WHERE IDIMPUESTO=@IDIMPUESTO
SELECT 'ACTUALIZADO' AS RESULTADO

END
ELSE IF(@BANDERA=2) 
BEGIN 
   DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDIMPUESTO=@IDIMPUESTO
   DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS WITH(ROWLOCK) WHERE IDIMPUESTO = @IDIMPUESTO
   
   SELECT 'ELIMINADO' AS RESULTADO
END
  