//[session.db|Untyped,session.idempresa|Untyped,]
--SELECT

SELECT Ot.tk, OT.tkm, OT.IDOPORTUNIDADTEMPLATE AS IDOPORTUNIDAD, EMP.COMPANIA AS EMPRESA, ELP.LINEA_PRODUCTO AS LINEA, OT.CONCEPTO, OT.MONTO, OT.COMISION, OT.CERTEZA, OPF.FASE, OT.DIASCIERREESTIMADO AS CIERRE
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES_TEMPLATES OT  
JOIN  <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO ELP ON OT.IDLINEA=ELP.IDLINEA_PRODUCTO  AND OT.IDEMPRESA=ELP.IDEMPRESA
JOIN  <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES OPF ON OT.IDFASE=OPF.IDFASE AND OT.IDEMPRESA=OPF.IDEMPRESA
JOIN <#SESSION.DB/>.dbo.EMPRESAS EMP ON OT.IDEMPRESA=EMP.IDEMPRESA AND EMP.IDEMPRESA = <#SESSION.IDEMPRESA/>