//[idprospecto|Integer,db|Text,]
--select
DECLARE @IDPROSPECTO INT
DECLARE @DB VARCHAR(16)

IF (ISNUMERIC(ISNULL(:IDPROSPECTO,0))=1)
SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,0) AS INT)
SELECT @DB = ISNULL(:DB,'')
 
DECLARE @SQL VARCHAR(8000)
SET @SQL =  ''
SET @SQL =  @SQL + ' SELECT TOP 5 '''+@DB+''' AS DB,REPLACE(CAST(comentarios AS VARCHAR(MAX)), ''<br>'', '''')  AS COMENTARIOS,*'
SET @SQL =  @SQL + '   FROM'
SET @SQL =  @SQL + '     '+@DB+'.dbo.PROSPECTOS P ,  '+@DB+'.dbo.PROSPECTOS_FASES F, '+@DB+'.dbo.PROSPECTOS_ORIGENES O '
SET @SQL =  @SQL + '   WHERE P.IDFASE = F.IDFASE AND P.IDORIGEN = O.IDORIGEN AND ' 
SET @SQL =  @SQL + '     P.IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(8))
  

IF @DB IS NOT NULL
EXEC ( @SQL)
ELSE
BEGIN
	 SET @SQL =  'SELECT TOP 1 * FROM '+@DB+'.dbo.PROSPECTOS WHERE IDUSUARIO = 0 '
	 EXEC ( @SQL)
END
