//[session.idempresa|Untyped,status|Integer,session.db|Untyped,tk|Text,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDIMPUESTO INT 
DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
DECLARE @TK VARCHAR(256) 

SET @TK=ISNULL(:TK, '') 
SELECT @IDIMPUESTO=IDIMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE TK = @TK 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @STATUS=ISNULL(:STATUS, -1)


IF(@STATUS=-1)
   SELECT STATUS FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS
   WHERE IDIMPUESTO=@IDIMPUESTO AND IDEMPRESA=@IDEMPRESA
ELSE 
 BEGIN 
  UPDATE <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS
  SET STATUS=@STATUS
  WHERE IDIMPUESTO=@IDIMPUESTO AND IDEMPRESA=@IDEMPRESA
  SELECT STATUS FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS
  WHERE IDIMPUESTO=@IDIMPUESTO AND IDEMPRESA=@IDEMPRESA
 END 
