//[session.idusuario|Untyped,session.idempresa|Untyped,idtabinbox|Integer,ltidinbox|Text,ltidtabinbox|Text,ltprospectos|Text,session.db|Untyped,mover|Integer,]
--update
/*protegido*/
DECLARE @ltIdInbox VARCHAR(MAX), @ltIdTabInbox VARCHAR(MAX), @ltProspectos VARCHAR(MAX)
DECLARE @idTabInbox INT, @IDUSUARIO INT, @IDEMPRESA INT, @MOVER INT
DECLARE @TBPROSPECTOS TABLE(IDPROSPECTO INT)
DECLARE @TBUSUARIOS TABLE(IDCOLABORADOR INT)
DECLARE @TBBANDEJA TABLE(FROMADDRESS VARCHAR(256))

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SET @idTabInbox = ISNULL(:idTabInbox,0)
SET @ltIdInbox = ISNULL(:ltIdInbox,'')
SET @ltIdTabInbox = ISNULL(:ltIdTabInbox,'')
SET @ltProspectos = ISNULL(:ltProspectos,'')
SET @MOVER = ISNULL(:mover,1)


IF @MOVER = 1
BEGIN
	UPDATE UI SET UI.IDTABINBOX = @idTabInbox 
	FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
	LEFT JOIN SALESUP_CT.dbo.Split(@ltIdTabInbox, '|') S2 ON S1.OCCURENCEID = S2.OCCURENCEID
	LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDTABINBOX = S2.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO

	UPDATE PA SET PA.IDTABINBOX = @idTabInbox
	FROM SALESUP_CT.dbo.Split(@ltProspectos, '|') S1
	LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = S1.SPLITVALUE AND PA.IDUSUARIO = @IDUSUARIO 	
	
END

IF @MOVER = 2
BEGIN
	INSERT INTO @TBPROSPECTOS (IDPROSPECTO)
	SELECT UI.IDPROSPECTO
	FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
	LEFT JOIN SALESUP_CT.dbo.Split(@ltIdTabInbox, '|') S2 ON S1.OCCURENCEID = S2.OCCURENCEID
	LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDTABINBOX = S2.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO AND ISNULL(UI.IDPROSPECTO,0) > 0
	GROUP BY UI.IDPROSPECTO
	
	INSERT INTO @TBUSUARIOS (IDCOLABORADOR)
	SELECT UI.IDCOLABORADOR
	FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
	LEFT JOIN SALESUP_CT.dbo.Split(@ltIdTabInbox, '|') S2 ON S1.OCCURENCEID = S2.OCCURENCEID
	LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDTABINBOX = S2.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO AND ISNULL(UI.IDCOLABORADOR,0) > 0
	GROUP BY UI.IDCOLABORADOR
	
	INSERT INTO @TBBANDEJA (FROMADDRESS)
	SELECT UI.FROMADDRESS
	FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
	LEFT JOIN SALESUP_CT.dbo.Split(@ltIdTabInbox, '|') S2 ON S1.OCCURENCEID = S2.OCCURENCEID
	LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDTABINBOX = S2.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO AND ISNULL(UI.IDCOLABORADOR,0) = 0 AND ISNULL(UI.IDPROSPECTO,0) = 0
	GROUP BY UI.FROMADDRESS
	
	UPDATE UI SET UI.IDTABINBOX = @idTabInbox 
	FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX UI 
	JOIN @TBUSUARIOS TBU ON TBU.IDCOLABORADOR = UI.IDCOLABORADOR
	WHERE UI.IDUSUARIO = @IDUSUARIO 
	
	UPDATE UI SET UI.IDTABINBOX = @idTabInbox 
	FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX UI 
	JOIN @TBBANDEJA TBB ON TBB.FROMADDRESS = UI.FROMADDRESS
	WHERE UI.IDUSUARIO = @IDUSUARIO 
	
	UPDATE UI SET UI.IDTABINBOX = @idTabInbox  
	FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX UI 
	JOIN @TBPROSPECTOS TBP ON TBP.IDPROSPECTO = UI.IDPROSPECTO
	WHERE UI.IDUSUARIO = @IDUSUARIO 
	
	UPDATE PA SET PA.IDTABINBOX = @idTabInbox
	FROM @TBPROSPECTOS TBP
	JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = TBP.IDPROSPECTO AND PA.IDUSUARIO = @IDUSUARIO 	
	
END

