//[tku|Text,]
--select

DECLARE @TKU VARCHAR(64)
SELECT @TKU = :TKU
DECLARE @BASE VARCHAR(128)
DECLARE @IDUSUARIO INT
SELECT @IDUSUARIO = IDUSUARIO,@BASE = BD_ACTUAL FROM EMPRESAS E, USUARIOS U WHERE U.IDEMPRESA = E.IDEMPRESa AND U.TKU = @TKU

DECLARE @SQL VARCHAR(5000)
SELECT @SQL =' declare @llave varchar(128) set @llave = salesup_ct.dbo.getsalesupkey() '
SELECT @SQL =@SQL+' SELECT ''<#SP_HOST/>'','''+@@SERVERNAME+''', POP3_HOST SERVIDOR, POP3_PORT PUERTO, POP3_USERNAME USUARIO, convert(varchar(max),DecryptByPassPhrase(@llave, POP3_PASSWORD))  CLAVE, INBOX_TIPO TIPO,  INBOX_USA_SSL AS SSL FROM '+@BASE+'.dbo.USUARIOS_MAILCONFIG U WHERE IDUSUARIO = '+ CAST(@IDUSUARIO AS VARCHAR(128))   
EXEC (@SQL)  