//[session.idusuario|Untyped,session.db|Untyped,]
--select
/*PROTEGIDO*/

DECLARE @NOLEIDOS INT
DECLARE @IDUSUARIO INT



SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SELECT @NOLEIDOS = SUM(ISNULL(NOLEIDOS, 0)) 
FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX_TABS UI
WHERE UI.IDUSUARIO = @IDUSUARIO 


SELECT @NOLEIDOS AS noLeidos


