//[session.idusuario|Untyped,tab|Text,icono|Text,idtabinbox|Integer,session.db|Untyped,]
--SELECT
/*protegido*/
DECLARE @IDUSUARIO INT, @IDTABINBOX INT
DECLARE @TAB VARCHAR(MAX), @ICONO VARCHAR(MAX)

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TAB = ISNULL(:TAB,'')
SET @ICONO = ISNULL(:ICONO,'')
SET @IDTABINBOX = ISNULL(:IDTABINBOX,0)

UPDATE <#SESSION.DB/>.dbo.USUARIOS_INBOX_TABS
SET TAB = @TAB, ICONO = @ICONO
WHERE IDTABINBOX = @IDTABINBOX

SELECT top 1 idTabInbox, Tab, Icono, noLeidos, Orden, ISNULL(tab_default,0) AS tabDefault, 1 as editar 
FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX_TABS 
WHERE IDUSUARIO = @IDUSUARIO AND IDTABINBOX = @IDTABINBOX

