//[session.idusuario|Untyped,session.db|Untyped,]
--select
/*PROTEGIDO*/

--select
/*PROTEGIDO*/

DECLARE @NOLEIDOS INT, @IDUSUARIO INT, @IDTABINBOX INT, @ORDEN INT, @RECORDATORIO INT,
@METASALCANZADAS INT, @METASNOALCANZADAS INT, @CONTEONOTIF INT, @NOTIF_PUSH INT, @AUTPENDIENTES INT, @FUERZACONTRASENA INT

DECLARE @TICKETS INT
DECLARE @TICKETS_ALERTA INT


UPDATE SALESUP_Ct.dbo.USUARIOS WITH(ROWLOCK ) SET HEARTBEAT = GETDATE()  WHERE IDUSUARIO =  <#SESSION.IDUSUARIO/>

DECLARE @REINICIARSESION TINYINT
SELECT @REINICIARSESION = REINICIARSESION, @FUERZACONTRASENA  = FUERZA_CONTRASENA  FROM <#SESSION.DB/>.dbo.USUARIOS  WITH(NOLOCK)  WHERE IDUSUARIO =  <#SESSION.IDUSUARIO/>

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDTABINBOX = 0
SET @ORDEN = 0
SELECT @NOLEIDOS = COUNT(*) 
FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX UI  WITH(NOLOCK) 
WHERE UI.IDUSUARIO = @IDUSUARIO 
AND UI.[READ] = 0 
AND UI.ACTIVO = 1
AND (UI.idinboxmaster is null or UI.IDINBOX  IN 
(SELECT MAX(IDinbox) AS IDINBOX from <#SESSION.DB/>.DBO.USUARIOS_INBOX WITH(NOLOCK) 
where IDUSUARIO = @IDUSUARIO and ACTIVO = 1 group by IDINBOXMASTER) )


IF @NOLEIDOS > 0
BEGIN
	SELECT TOP 1 @IDTABINBOX = IDTABINBOX, @ORDEN = ORDEN 
	FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX_TABS   WITH(NOLOCK)
	WHERE IDUSUARIO = @IDUSUARIO AND NOLEIDOS > 0 
	
	ORDER BY ORDEN 
END

select @METASALCANZADAS = COUNT(*)
from <#SESSION.DB/>.DBO.USUARIOS_ALERTAS UA  WITH(NOLOCK)
JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS US   WITH(NOLOCK) ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=<#SESSION.IDUSUARIO/> and UA.LEIDO=0 AND UA.NOTIFICADO=0 and US.TIPO=19

select @METASNOALCANZADAS = COUNT(*)
from <#SESSION.DB/>.DBO.USUARIOS_ALERTAS UA  WITH(NOLOCK)
JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS US   WITH(NOLOCK) ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=<#SESSION.IDUSUARIO/> and UA.LEIDO=0 AND UA.NOTIFICADO=0 and US.TIPO=69


SELECT @CONTEONOTIF = COUNT (*)   
FROM
 <#SESSION.DB/>.DBO.USUARIOS_ALERTAS A WITH(NOLOCK)
 JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS S WITH(NOLOCK) ON S.IDSUCESO =  A.IDSUCESO
 JOIN SALESUP_CT.dbo.TIPOS_SUCESOS T WITH(NOLOCK) ON T.IDSUCESO = S.TIPO
 LEFT JOIN <#SESSION.DB/>.DBO.TAREAS TR WITH(NOLOCK) ON TR.IDTAREA = S.IDTAREA
 LEFT JOIN <#SESSION.DB/>.DBO.CITAS C WITH(NOLOCK) ON C.IDCITA = S.IDCITA
WHERE A.IDUSUARIO=<#SESSION.IDUSUARIO> AND A.LEIDO = 0 AND ISNULL(ALERTA, '') !='' AND S.IDMETA IS NULL


SELECT
 @NOTIF_PUSH = COUNT(*)
 FROM
 <#SESSION.DB/>.DBO.USUARIOS_ALERTAS A WITH(NOLOCK)
 JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS S WITH(NOLOCK) ON S.IDSUCESO =  A.IDSUCESO
 JOIN SALESUP_CT.dbo.TIPOS_SUCESOS T WITH(NOLOCK) ON T.IDSUCESO = S.TIPO
 LEFT JOIN <#SESSION.DB/>.DBO.TAREAS TR WITH(NOLOCK) ON TR.IDTAREA = S.IDTAREA
 LEFT JOIN <#SESSION.DB/>.DBO.CITAS C WITH(NOLOCK) ON C.IDCITA = S.IDCITA
WHERE A.IDUSUARIO=<#SESSION.IDUSUARIO> AND A.NOTIFICADO = 0 AND S.IDMETA IS NULL
AND ISNULL(ALERTA, '') !=''

SELECT @RECORDATORIO = <#SESSION.DB/>.DBO.AVISOEVENTO(@IDUSUARIO)

SELECT 
	   @AUTPENDIENTES = COUNT(*)
FROM 
   <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK), <#SESSION.DB/>.DBO.COMPANIAS C WITH(NOLOCK)
WHERE 
    P.APROBACIONESTADO = 1 
    AND U.IDUSUARIO = P.IDUSUARIO 
    AND C.IDCOMPANIA = P.IDCOMPANIA 
    AND C.IDUSUARIO = @IDUSUARIO

SELECT @TICKETS = COUNT(*)
FROM 
  CONTROL.TICKETS.DBO.TICKETS WITH(NOLOCK)  
WHERE  VISTO_CLIENTE = 0 AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDUSUARIO = <#SESSION.IDUSUARIO/>

SELECT @TICKETS_ALERTA = COUNT(*) FROM CONTROL.TICKETS.DBO.TICKETS T
OUTER APPLY(
	SELECT TOP 1 TCC.IDCALIFICACION FROM CONTROL.TICKETS.DBO.TICKET_COMENTARIOS TCC WHERE TCC.IDTICKET = T.IDTICKET AND TCC.TIPOUSUARIO = 2 ORDER BY TCC.IDTICKETCOMENTARIO DESC
) TC
WHERE T.IDESTADO = 1  AND TC.IDCALIFICACION =1 AND T.IDEMPRESA = <#SESSION.IDEMPRESA/> AND T.IDUSUARIO = <#SESSION.IDUSUARIO/> AND T.IDPRODUCTO = 1 AND (T.CERRAR = 1 OR T.VISTO_CLIENTE = 0)

SELECT @NOLEIDOS AS noLeidos, @IDTABINBOX as idTabInbox, @ORDEN AS orden, @FUERZACONTRASENA AS fuerzaPsw, @TICKETS AS Tickets, @TICKETS_ALERTA AS Tickets_Alertas, 1 AS Leido_Tickets_Alertas, @METASALCANZADAS AS metasAlcanzadas, @METASALCANZADAS AS metasNoAlcanzadas,@CONTEONOTIF AS notificaciones, @NOTIF_PUSH AS notificacionesPush, @REINICIARSESION  AS reiniciarSesion, @RECORDATORIO AS recordatorio,@AUTPENDIENTES AS autPendientes
