//[idemail|Integer,session.idusuario|Untyped,session.gmt|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--select
/*protegido*/
DECLARE @IDEMAIL INT, @IDUSUARIO INT, @GMT INT, @IDEMPRESA INT
SET @IDEMAIL = ISNULL(:IDEMAIL,0)
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @GMT = <#SESSION.GMT/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT 
UE.CUERPO as bodyEmail,  
0 AS tieneAdjuntos, '' as Adjunto,
CAST(UE.FECHAHORA AS FLOAT) AS dtf
FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UE.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDEMPRESA = @IDEMPRESA AND U.IDUSUARIO = P.IDUSUARIO
WHERE UE.IDUSUARIO = @IDUSUARIO AND UE.IDEMAIL = @IDEMAIL