//[]
--select
DECLARE @FECHA DATETIME
SET @FECHA = dbo.GETONLYDATE(GETDATE())-30

--DELETE FROM USUARIOS_INBOX WHERE DATE < @FECHA AND ISNULL(ATTACHMENTS, '') LIKE '' AND ACTIVO !=1
select TOP 1 IDINBOX, ATTACHMENTS, MONTH(FECHADESCARGA), YEAR(FECHADESCARGA) FROM FENIXNEW.SALESUP_DB1.dbo.USUARIOS_INBOX WHERE DATE < @FECHA AND ISNULL(ATTACHMENTS, '') NOT LIKE '' AND ACTIVO !=1

