//[session.idusuario|Untyped,auto|Integer,idinbox|Integer,session.db|Untyped,]
--update
/*protegido*/

DECLARE @AUTO INT, @IDINBOX INT, @IDUSUARIO INT

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @AUTO = ISNULL(:auto,0)
SET @IDINBOX = ISNULL(:idInbox,0)
 

UPDATE PA SET PA.GUARDAINBOX = @AUTO
FROM 
<#SESSION.DB/>.DBO.USUARIOS_INBOX UI, 
<#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA
WHERE 
    UI.IDUSUARIO = @IDUSUARIO 
AND UI.IDINBOX = @IDINBOX 
AND PA.IDPROSPECTO = UI.IDPROSPECTO 
AND PA.IDUSUARIO = UI.IDUSUARIO 



	