//[idinbox|Integer,session.db|Untyped,]
-- SELECT
/*protegido*/
DECLARE @IDINBOX INT

SET @IDINBOX = ISNULL(:IDINBOX,0)

SELECT
 UI.*, U.EMAIL, U.NOMBRE AS NOMUSUARIO, U.APELLIDOS AS APEUSUARIO, P.NOMBRE, P.APELLIDOS 
FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX UI
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UI.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON UI.IDUSUARIO = U.IDUSUARIO
WHERE UI.IDINBOX = @IDINBOX
