//[session.idusuario|Untyped,idtabinbox|Integer,idnuevotab|Integer,session.db|Untyped,]
--delete 
DECLARE @IDTABINBOX INT, @IDNUEVOTAB INT, @IDUSUARIO INT

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDTABINBOX = ISNULL(:IDTABINBOX, 0)
SET @IDNUEVOTAB = ISNULL(:IDNUEVOTAB, 0)

DECLARE @PUEDEELIMINAR INT
SET @PUEDEELIMINAR = 0

SELECT @PUEDEELIMINAR = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX_TABS WHERE  IDTABINBOX = @IDTABINBOX AND IDUSUARIO = @IDUSUARIO AND TAB_DEFAULT IS NULL

IF @PUEDEELIMINAR > 0
BEGIN
	 IF @IDNUEVOTAB > 0
	 BEGIN
	 UPDATE <#SESSION.DB/>.dbo.USUARIOS_INBOX SET IDTABINBOX = @IDNUEVOTAB
	 WHERE IDUSUARIO = @IDUSUARIO AND IDTABINBOX = @IDTABINBOX

	 UPDATE <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS SET IDTABINBOX = @IDNUEVOTAB
	 WHERE IDTABINBOX = @IDTABINBOX

	 END

	 DELETE FROM <#SESSION.DB/>.dbo.USUARIOS_INBOX_TABS WHERE IDTABINBOX = @IDTABINBOX AND IDUSUARIO = @IDUSUARIO AND TAB_DEFAULT IS NULL

END


