//[idinbox|Integer,session.idusuario|Untyped,session.gmt|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--select
/*protegido*/
DECLARE @IDINBOX INT, @IDUSUARIO INT, @GMT INT, @IDEMPRESA INT
SET @IDINBOX = ISNULL(:IDINBOX,0)
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @GMT = <#SESSION.GMT/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT U.NOMBRE+' '+ISNULL(U.APELLIDOS,'')+ ' ('+LTRIM(RTRIM(ISNULL(U.INICIALES,'')))+')'  AS duenio, CASE WHEN @IDUSUARIO != ISNULL(PA.IDUSUARIO,0) THEN '1' ELSE '' END AS noEsTuyo, UI.IdInbox, ISNULL(UI.idInboxMaster,0) AS idInboxMaster, UI.idTabInbox, ISNULL(UI.idSeguimiento,0) AS idSeguimiento, UI.EMAILID as emailId, [READ] AS noLeido,UI.FROMNAME as De, 
CASE WHEN ISNULL(UI.REPLYTO,'') = '' THEN UI.FROMADDRESS ELSE UI.REPLYTO END as correoDe, UI.cc,
UI.TOADDRESS as Para, SUBJECT as Asunto,
UI.BODY as bodyEmail, CONVERT(VARCHAR(10),SALESUP_CT.dbo.fechaOffSet(@GMT,UI.DATE),103) as Fecha, SALESUP_CT.DBO.OBTIENEHORA(SALESUP_CT.dbo.fechaOffSet(@GMT,UI.DATE)) AS Hora, 
CASE WHEN LEN(UI.ATTACHMENTS)>0 THEN 1 ELSE 0 END AS tieneAdjuntos, UI.ATTACHMENTS as Adjuntos,
RTRIM(P.NOMBRE)+' '+ISNULL(LTRIM(P.APELLIDOS),'') AS Contacto, P.Empresa, P.tkp, P.Idprospecto, P.esCliente, P.ETIQUETAS_TXT as etiquetas,
CAST(UI.DATE AS FLOAT) AS dtf
FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX UI
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = UI.IDPROSPECTO AND PA.IDUSUARIO = @IDUSUARIO AND PA.IDTABINBOX = UI.IDTABINBOX
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UI.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDEMPRESA = @IDEMPRESA AND U.IDUSUARIO = P.IDUSUARIO
WHERE UI.IDUSUARIO = @IDUSUARIO AND UI.IDINBOX = @IDINBOX AND UI.ACTIVO = 1





