//[session.gmt|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,idinboxmaster|Integer,session.replyto|Untyped,session.nombre|Untyped,session.apellidos|Untyped,session.db|Untyped,]
--SELECT
/*protegido*/

DECLARE @IDINBOXMASTER INT, @IDUSUARIO INT, @TIPOMAIL INT, @IDTEMP INT
DECLARE @IDCORREO INT, @GMT INT, @idTabInbox INT, @IDEMPRESA INT, @IDEMAIL INT, @IDINBOX INT
DECLARE @TB TABLE(
	idTemp INT IDENTITY, tipoCorreo INT, tkui VARCHAR(MAX),  IdInbox INT, idEmail INT, Asunto VARCHAR(MAX), tieneAdjuntos INT,
	Fecha VARCHAR(10), Hora VARCHAR(10), dtf FLOAT, De VARCHAR(MAX), correoDe VARCHAR(MAX), para VARCHAR(MAX), 
	paraCorreo VARCHAR(MAX), bodyEmail VARCHAR(MAX), Adjuntos VARCHAR(MAX), idProspecto INT, reciente INT, dtfecha datetime, cc varchar(max)
)

DECLARE @BODYEMAIL VARCHAR(MAX), @ADJUNTOS VARCHAR(MAX), @REPLYTO VARCHAR(MAX), @NOMUSUARIO VARCHAR(MAX)
DECLARE @IDPROSPECTO INT

SET @GMT = CAST('<#SESSION.GMT/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDINBOXMASTER = ISNULL(:idInboxMaster,0)

SET @REPLYTO = '<#SESSION.REPLYTO/>'
SET @NOMUSUARIO = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/>'

INSERT INTO @TB (tipoCorreo, idInbox, idEmail, asunto, fecha, hora, dtf, paraCorreo, correoDe, de, dtfecha)
SELECT 1, @IDINBOXMASTER, IDEMAIL, ASUNTO, CONVERT(VARCHAR(10),FECHAHORA,103), SALESUP_CT.DBO.OBTIENEHORA(FECHAHORA), 
CAST(FECHAHORA AS FLOAT), DESTINATARIO , @REPLYTO, @NOMUSUARIO, FECHAHORA
FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS 
WHERE IDUSUARIO = @IDUSUARIO AND IDINBOX = @IDINBOXMASTER 
order by FECHAHORA ASC

INSERT INTO @TB (tipoCorreo, tkui, idInbox, asunto, fecha, hora, dtf, de, correoDe, dtfecha, cc)
SELECT 2, ui.tkui, UI.idinbox, UI.SUBJECT, CONVERT(VARCHAR(10),SALESUP_CT.dbo.fechaOffSet(@GMT,UI.DATE),103), SALESUP_CT.DBO.OBTIENEHORA(SALESUP_CT.dbo.fechaOffSet(@GMT,UI.DATE)) , 
CAST(DATE AS FLOAT), 
 
CASE
WHEN ISNULL(UI.IDCOLABORADOR,0) > 0 THEN RTRIM(US.NOMBRE)+' '+ISNULL(LTRIM(US.APELLIDOS),'') + ' ('+LTRIM(RTRIM(US.INICIALES))+')' 
WHEN ISNULL(UI.IDPROSPECTO,0) > 0 THEN RTRIM(P.NOMBRE)+' '+ISNULL(LTRIM(P.APELLIDOS),'')
WHEN ISNULL(UI.IDPROSPECTO,0) = 0 AND ISNULL(UI.IDCOLABORADOR,0) = 0 AND ISNULL(UI.FROMNAME,'') != '' 
THEN (CASE WHEN ISNULL(UI.REPLYTO,'') = '' THEN UI.FROMADDRESS ELSE UI.REPLYTO END)
END, 

CASE WHEN ISNULL(UI.REPLYTO,'') = '' THEN UI.FROMADDRESS ELSE UI.REPLYTO END as correoDe,

 SALESUP_CT.dbo.fechaOffSet(@GMT,UI.DATE), UI.cc
FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX UI
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = UI.IDPROSPECTO AND PA.IDUSUARIO = @IDUSUARIO AND PA.IDTABINBOX = UI.IDTABINBOX
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UI.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDEMPRESA = @IDEMPRESA AND U.IDUSUARIO = P.IDUSUARIO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDEMPRESA = @IDEMPRESA AND US.IDUSUARIO = UI.IDCOLABORADOR
WHERE UI.IDUSUARIO = @IDUSUARIO AND UI.IDINBOXMASTER = @IDINBOXMASTER AND UI.ACTIVO = 1
ORDER BY DATE

SELECT TOP 1 @IDTEMP = IDTEMP, @TIPOMAIL = tipoCorreo, @IDINBOX = IDINBOX, @IDEMAIL = IDEMAIL FROM @TB ORDER BY dtfecha DESC

IF @TIPOMAIL = 1
BEGIN
	SELECT @BODYEMAIL = CUERPO, @ADJUNTOS = '', @IDPROSPECTO = IDPROSPECTO 
	FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS 
	WHERE IDEMAIL = @IDEMAIL AND IDUSUARIO = @IDUSUARIO
END

IF @TIPOMAIL = 2
BEGIN
	SELECT @BODYEMAIL = BODY, @ADJUNTOS = ATTACHMENTS, @IDPROSPECTO = IDPROSPECTO 
	FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX 
	WHERE IDINBOX = @IDINBOX AND IDUSUARIO = @IDUSUARIO
END

UPDATE @TB 
SET 
reciente = 1, bodyEmail = @BODYEMAIL, 
ADJUNTOS = @ADJUNTOS, IDPROSPECTO = @IDPROSPECTO,
tieneAdjuntos = CASE WHEN LEN(@ADJUNTOS)>0 THEN 1 ELSE 0 END
WHERE IDTEMP = @IDTEMP

SELECT * FROM @TB ORDER BY dtfecha DESC
