//[session.idusuario|Untyped,session.idempresa|Untyped,ltidinbox|Text,session.db|Untyped,]
--update
/*protegido*/
DECLARE @ltIdInbox VARCHAR(MAX), @ltIdTabInbox VARCHAR(MAX), @ltProspectos VARCHAR(MAX)
DECLARE @idTabInbox INT, @IDUSUARIO INT, @IDEMPRESA INT
 
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @ltIdInbox = ISNULL(:ltIdInbox,'')

UPDATE UI SET [READ] = 1
FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO

UPDATE UIM SET [READ] = 1 
FROM SALESUP_CT.dbo.Split(@ltIdInbox, '|') S1
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UI ON UI.IDINBOX = S1.SPLITVALUE AND UI.IDUSUARIO = @IDUSUARIO 
JOIN <#SESSION.DB/>.dbo.USUARIOS_INBOX UIM ON UIM.IDINBOXMASTER = UI.IDINBOXMASTER AND UIM.ACTIVO = 1



