//[session.tku|Untyped,anteriores|Integer,session.db|Untyped,async|Text,]
--update
/*protegido*/

DECLARE @TKU VARCHAR(MAX)
SET @TKU = '<#SESSION.TKU/>'

DECLARE @ANTERIORES INT
DECLARE @FECHA_BASE DATETIME = 0

IF (ISNULL(:ANTERIORES, 0) != 0)
BEGIN
 SELECT @FECHA_BASE  = MIN(DATE) FROM  <#SESSION.DB/>.DBO.USUARIOS_INBOX I,
 <#SESSION.DB/>.DBO.USUARIOS U WHERE U.TKU = @TKU AND I.IDUSUARIO = U.IDUSUARIO  AND IDSEGUIMIENTO IS NULL
END
 
IF :ASYNC IS NOT NULL
BEGIN
  DECLARE @PARAMS VARCHAR(MAX)
  SET  @PARAMS  =  'EXEC <#SESSION.DB/>.dbo.SP_INBOX_REVISA_CORREOS_USUARIO '''+ @TKU +''',0,0'
  EXEC SALESUP_CT.dbo.SP_ASYNC_EXECUTE @PARAMS 
END
ELSE
  EXEC <#SESSION.DB/>.DBO.SP_INBOX_REVISA_CORREOS_USUARIO @TKU, @FECHA_BASE,0
