//[vizualizaren|Text,session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
/*protegido*/
DECLARE @IDEMPRESA INT, @TOTAL INT, @ID INT, @HAY INT, @IDTAB INT
DECLARE @TB TABLE(idCampo INT, Filtro VARCHAR(MAX), Campo VARCHAR(MAX), tCamper VARCHAR(MAX), esDe INT, tipoCampo INT, Config VARCHAR(MAX) )
DECLARE @TABS TABLE(ID INT IDENTITY, IDTAB INT, TAB VARCHAR(MAX))
DECLARE @VizualizarEn VARCHAR(MAX)
SET @VizualizarEn = ISNULL(:VizualizarEn,'')

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

INSERT INTO @TABS (IDTAB, TAB)
SELECT IDTAB, NOMBRE FROM <#SESSION.DB/>.dbo.EMPRESAS_TABS 
WHERE IDEMPRESA = @IDEMPRESA AND IDVENTANA IN (SELECT SPLITVALUE FROM SALESUP_CT.DBO.SPLIT(@VizualizarEn,','))


SELECT @TOTAL = COUNT(*) FROM @TABS

SET @ID = 1
SET @HAY = 0

WHILE @ID <= @TOTAL
BEGIN
	SELECT @IDTAB = IDTAB FROM @TABS WHERE ID = @ID

	SELECT @HAY = COUNT(*) 
	FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC 
	WHERE EC.IDEMPRESA = @IDEMPRESA AND EC.IDTAB = @IDTAB	
	
	IF @HAY > 0 
	BEGIN
		INSERT INTO @TB(idCampo, Filtro, Campo, tCamper, esDe, tipoCampo, Config)
		SELECT '', '(... '+TAB+' ...)', '', '', '', '', '' FROM @TABS WHERE ID = @ID 
		
		INSERT INTO @TB(idCampo, Filtro, Campo, tCamper, esDe, tipoCampo, Config)
		SELECT EC.idCampo, EC.NOMBRE_CAMPO AS Filtro,
		'-'+CAST(EC.INDICE AS VARCHAR(12)) AS Campo,
		CASE WHEN EC.INDICE >= 1 AND EC.INDICE <= 4 THEN '1'
		WHEN EC.INDICE >= 5 AND EC.INDICE <= 8 THEN '2' 
		WHEN EC.INDICE >= 9 AND EC.INDICE <= 12 THEN '3' 
		WHEN (EC.INDICE >= 13 AND EC.INDICE <= 20) OR (EC.INDICE >= 26 AND EC.INDICE <= 32) OR (INDICE BETWEEN 35 AND 64) THEN '4' 
		WHEN EC.INDICE >= 21 AND  EC.INDICE < 26 THEN '5'
		WHEN EC.INDICE = 33 THEN '4'
		WHEN EC.INDICE = 34 THEN '4'
		END tCamper, 
		EC.TIPO AS esDe, 
		tipo_campo AS tipoCampo, CONFIGURACION_CAMPO AS Config
		FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC 
		WHERE EC.IDEMPRESA = @IDEMPRESA AND ( EC.IDTAB = @IDTAB OR EC.TAMBIENEN_IDTAB = @IDTAB )
		AND IDCAMPO NOT IN (SELECT IDCAMPO FROM @TB)
		ORDER BY EC.NOMBRE_CAMPO
	END
	
	
	SET @ID = @ID + 1
END

select * from @TB





