//[session.idusuario|Untyped,idpantalla|Integer,session.db|Untyped,]
-- delete

DECLARE @IDUSUARIO INT
DECLARE @IDPANTALLA INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS INT)

DELETE FROM <#SESSION.DB/>.DBO.usuarios_filtros WHERE IDPANTALLA = @IDPANTALLA AND IDUSUARIO = @IDUSUARIO