//[idpantalla|Text|,session.db|Untyped|,session.idusuario|Untyped|]
--select
DECLARE @IDPANTALLA VARCHAR(1000)
SET @IDPANTALLA=CAST(ISNULL(:IDPANTALLA,0) AS VARCHAR(1000))
IF PATINDEX('%.%', '<#SESSION.DB/>') = 0
BEGIN
  EXEC ('SELECT <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (<#SESSION.IDUSUARIO/>, CAST(rtrim(ltrim('+@IDPANTALLA+')) AS INT)) AS SQLTXT')
  EXEC ('SELECT <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (<#SESSION.IDUSUARIO/>, CAST(rtrim(ltrim(''15'')) AS INT)) AS SQLTXT')
END
ELSE
  SELECT '' AS SQLTXT

