//[session.db|Untyped,session.idusuario|Untyped,idpantalla|Integer,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDPANTALLA INT
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SELECT *,  <#SESSION.DB/>.DBO.UDF_NOMBRE_FILTRO(TIPO) AS TIPOTXT  
FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS 
WHERE IDUSUARIO=<#SESSION.IDUSUARIO> AND IDPANTALLA=@IDPANTALLA and tipo in (1,2,3,4,5,6,7)
ORDER BY TIPO