//[borrar|Integer,session.db|Untyped,session.idusuario|Untyped,idpantalla|Integer,]
--insert
DECLARE @BORRAR INT
DECLARE @IDPANTALLA INT
SET @BORRAR=CAST(ISNULL(:BORRAR,0) AS INT)
SET @IDPANTALLA=ISNULL(:IDPANTALLA,0)

IF @BORRAR=1
 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=@IDPANTALLA AND TIPO = 1
IF @BORRAR=2 
 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=@IDPANTALLA AND TIPO = 2
IF @BORRAR=3
 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=@IDPANTALLA AND TIPO = 3 