//[idpantalla|Integer,session.db|Untyped,session.idusuario|Untyped,]
DECLARE @IDPANTALLA INT
SET @IDPANTALLA=CAST(ISNULL(:IDPANTALLA,0) AS INT)
SELECT *,  <#SESSION.DB/>.DBO.UDF_NOMBRE_FILTRO(TIPO) AS TIPOTXT  
FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS 
WHERE IDUSUARIO=<#SESSION.IDUSUARIO> AND IDPANTALLA=@IDPANTALLA and tipo=15
ORDER BY TIPO