//[session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,v|Text,f|Text,r1|Text,r2|Text,session.db|Untyped,ini|Integer,inicializacion|Integer,]
--select

DECLARE @FILTRO INT, @VENTANA INT, @IDUSUARIO INT, @IDEMPRESA INT, @VENTANA_RECORDATORIOS INT, @VENTANA_TAREAS INT, @VENTANA_CITAS INT, @CONVERTCODE INT
DECLARE @VENTANA_COBROS_AUDITAR INT, @VENTANA_COBROS_PENDIENTES INT, @INICIALIZACION INT
DECLARE @VALOR VARCHAR(MAX), @TEXTO VARCHAR(MAX), @SQL VARCHAR(MAX), @SQLTAREAS VARCHAR(MAX), @SQLCITAS VARCHAR(MAX), @SQLRECORDATORIOS VARCHAR(MAX), @NEWID VARCHAR(10)
DECLARE @SQLCOBROSPENDIENTES VARCHAR(MAX), @SQLCOBROSAUDITAR VARCHAR(MAX)
DECLARE @FECHAINICIO VARCHAR(MAX), @FECHAFIN VARCHAR(MAX), @R1 VARCHAR(MAX), @R2 VARCHAR(MAX), @SQLBASE VARCHAR(MAX), @COMODINTAREAS VARCHAR(MAX)
DECLARE @FINICIO DATETIME, @FFIN DATETIME, @RANGO1 DATETIME, @RANGO2 DATETIME
DECLARE @VIENEDEINICIALIZACION INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT) 
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @CONVERTCODE = '<#SESSION.CONVERTCODE/>'
SET @VALOR = ISNULL(:V,'')
SET @FILTRO = ISNULL(:F,'')
SET @R1 = ISNULL(:R1,'')
SET @R2 = ISNULL(:R2,'')
SET @VENTANA = ''
SET @SQLRECORDATORIOS = ''
SET @SQLTAREAS = ''
SET @SQLCITAS = ''
SET @SQLCOBROSPENDIENTES = ''
SET @SQLCOBROSAUDITAR = ''
SET @VENTANA_RECORDATORIOS = 410
SET @VENTANA_TAREAS = 411
SET @VENTANA_CITAS = 412
SET @VENTANA_COBROS_PENDIENTES = 414
SET @VENTANA_COBROS_AUDITAR = 415
SET @COMODINTAREAS = ''

IF @R1 != '' BEGIN SET @RANGO1 = CONVERT(DATETIME, @R1, @CONVERTCODE) END
IF @R2 != '' BEGIN SET @RANGO2 = CONVERT(DATETIME, @R2, @CONVERTCODE) END

SET @NEWID = LEFT(CONVERT(VARCHAR(MAX), NEWID()),8)
SET @TEXTO = ''
/*DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND TIPO = @FILTRO AND IDPANTALLA IN (410,411,412)*/

SET @INICIALIZACION = ISNULL(:INI,0)
IF @INICIALIZACION = 1 BEGIN SET @COMODINTAREAS = ' AND VT.IDESTADO NOT IN(3,5) '  END 

SET @VIENEDEINICIALIZACION= ISNULL(:INICIALIZACION,0)

IF @FILTRO = 1
BEGIN
	SELECT @TEXTO = 'De: '+ U.NOMBRE+' '+U.APELLIDOS + ' ('+ U.INICIALES+')' FROM <#SESSION.DB/>.DBO.USUARIOS U WHERE U.IDUSUARIO = @VALOR
	SET @SQLRECORDATORIOS = 'R.IDUSUARIO = ' + @VALOR
	SET @SQLTAREAS = 'T.IDINICIADOR = ' + @VALOR
	SET @SQLCITAS = 'C.IDUSUARIO_CREACION = ' + @VALOR
	SET @SQLCOBROSPENDIENTES = 'V.IDUSUARIO = '+ @VALOR
	SET @SQLCOBROSAUDITAR = 'V.IDUSUARIO = '+ @VALOR
END

IF @FILTRO = 2
BEGIN
	SELECT @TEXTO = 'Para: '+U.NOMBRE+' '+U.APELLIDOS + ' ('+ U.INICIALES+')' FROM <#SESSION.DB/>.DBO.USUARIOS U WHERE U.IDUSUARIO = @VALOR
	SET @SQLRECORDATORIOS = 'R.IDUSUARIO = ' + @VALOR
	SET @SQLTAREAS = 'T.IDREALIZADOR = ' + @VALOR
	SET @SQLCITAS = 'CI.IDPERSONA = '+@VALOR
	SET @SQLCOBROSPENDIENTES = 'V.IDUSUARIO = '+ @VALOR
	SET @SQLCOBROSAUDITAR = 'V.IDUSUARIO = '+ @VALOR
END

IF @FILTRO = 3
BEGIN
	SELECT @TEXTO = GRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIOGRUPO = @VALOR
	SET @SQLRECORDATORIOS = 'U.IDGRUPO = ' + @VALOR
	SET @SQLTAREAS = 'U.IDGRUPO = ' + @VALOR
	SET @SQLCITAS = 'U.IDGRUPO = '+@VALOR
	SET @SQLCOBROSPENDIENTES = 'U.IDGRUPO = '+@VALOR
	SET @SQLCOBROSAUDITAR = 'U.IDGRUPO = '+@VALOR
END

IF @FILTRO = 4
BEGIN
	
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, @VALOR, NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, @VALOR, NULL)
	
	IF @VALOR = '0' BEGIN SET @TEXTO = 'Todos' END
	IF @VALOR = '1' BEGIN SET @TEXTO = 'Hoy' END
	IF @VALOR = '2' BEGIN SET @TEXTO = 'Ayer' END
	IF @VALOR = '3' BEGIN SET @TEXTO = 'Esta semana' END
	IF @VALOR = '4' BEGIN SET @TEXTO = 'Semana anterior' END
	IF @VALOR = '5' BEGIN SET @TEXTO = 'Este mes' END
	IF @VALOR = '6' BEGIN SET @TEXTO = 'Mes anterior' END
	IF @VALOR = '7' BEGIN SET @TEXTO = 'Hace 2 meses' END
	IF @VALOR = '8' BEGIN SET @TEXTO = 'Este Año' END
	IF @VALOR = '9' BEGIN SET @TEXTO = 'Futuros' END
	IF @VALOR = '10' BEGIN SET @TEXTO = @R1+' - '+@R2 END
	
	IF @RANGO1 IS NOT NULL BEGIN SET @FINICIO = @RANGO1 END
	IF @RANGO2 IS NOT NULL BEGIN SET @FFIN = @RANGO2 END
	
	SET @FECHAINICIO = CONVERT(VARCHAR(MAX), @FINICIO, 103)
	SET @FECHAFIN = CONVERT(VARCHAR(MAX), @FFIN, 103)
	
	SET @SQLRECORDATORIOS = 'SALESUP_CT.DBO.GETONLYDATE(R.FECHAHORA) >= CONVERT(DATETIME, '''+@FECHAINICIO+''' ,103) AND SALESUP_CT.DBO.GETONLYDATE(R.FECHAHORA) <= CONVERT(DATETIME, '''+@FECHAFIN+''' ,103) '
	SET @SQLTAREAS = 'SALESUP_CT.DBO.GETONLYDATE(T.FECHA_VENCIMIENTO) >= CONVERT(DATETIME, '''+@FECHAINICIO+''' ,103) AND SALESUP_CT.DBO.GETONLYDATE(T.FECHA_VENCIMIENTO) <= CONVERT(DATETIME, '''+@FECHAFIN+''' ,103) ' + @COMODINTAREAS
	SET @SQLCITAS = 'SALESUP_CT.DBO.GETONLYDATE(C.FECHA_INICIO) >= CONVERT(DATETIME, '''+@FECHAINICIO+''' ,103) AND SALESUP_CT.DBO.GETONLYDATE(C.FECHA_INICIO) <= CONVERT(DATETIME, '''+@FECHAFIN+''' ,103) '
	SET @SQLCOBROSPENDIENTES = 'SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) >= CONVERT(DATETIME, '''+@FECHAINICIO+''' ,103) AND SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) <= CONVERT(DATETIME, '''+@FECHAFIN+''' ,103) '
	SET @SQLCOBROSAUDITAR = 'SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) >= CONVERT(DATETIME, '''+@FECHAINICIO+''' ,103) AND SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) <= CONVERT(DATETIME, '''+@FECHAFIN+''' ,103) '
END

IF @FILTRO = 5
BEGIN
 	IF @VALOR = '1'
 	BEGIN
 		SET @TEXTO = 'Activos'
 		SET @SQLRECORDATORIOS = ' SALESUP_CT.DBO.GETONLYDATE(R.FECHAHORA) >= GETDATE() '
		SET @SQLTAREAS = ' SALESUP_CT.DBO.GETONLYDATE(T.FECHA_VENCIMIENTO) >= GETDATE() ' 
		SET @SQLCITAS = ' SALESUP_CT.DBO.GETONLYDATE(C.FECHA_INICIO) >= GETDATE() '
		SET @SQLCOBROSPENDIENTES = ' SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) >= GETDATE() '
		SET @SQLCOBROSAUDITAR = ' SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) >= GETDATE() '
 	END
 	
 	IF @VALOR = '2'
 	BEGIN
 		SET @TEXTO = 'Vencidos'
		SET @SQLRECORDATORIOS = ' SALESUP_CT.DBO.GETONLYDATE(R.FECHAHORA) <= GETDATE() '
		SET @SQLTAREAS = ' SALESUP_CT.DBO.GETONLYDATE(T.FECHA_VENCIMIENTO) <= GETDATE() ' 
		SET @SQLCITAS = ' SALESUP_CT.DBO.GETONLYDATE(C.FECHA_INICIO) <= GETDATE() '
		SET @SQLCOBROSPENDIENTES = ' SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) <= GETDATE() '
		SET @SQLCOBROSAUDITAR = ' SALESUP_CT.DBO.GETONLYDATE(VC.FECHAHORA) <= GETDATE() '
 	END
END

IF @FILTRO = 6
BEGIN
	IF @VALOR = '1'
 	BEGIN
 		SET @TEXTO = 'Recordatorios'
 		SET @SQLRECORDATORIOS = '1=1'
		SET @SQLTAREAS = '0=0' 
		SET @SQLCITAS = '0=0'
		SET @SQLCOBROSPENDIENTES = '0=0'
		SET @SQLCOBROSAUDITAR = '0=0'
 	END
	IF @VALOR = '2'
 	BEGIN
 		SET @TEXTO = 'Tareas'
 		SET @SQLRECORDATORIOS = '0=0'
		SET @SQLTAREAS = '1=1' 
		SET @SQLCITAS = '0=0'
		SET @SQLCOBROSPENDIENTES = '0=0'
		SET @SQLCOBROSAUDITAR = '0=0'
 	END
	IF @VALOR = '3'
 	BEGIN
 		SET @TEXTO = 'Citas'
 		SET @SQLRECORDATORIOS = '0=0'
		SET @SQLTAREAS = '0=0' 
		SET @SQLCITAS = '1=1'
		SET @SQLCOBROSPENDIENTES = '0=0'
		SET @SQLCOBROSAUDITAR = '0=0'
 	END
END


IF @FILTRO = 7
BEGIN
	SET @SQLBASE = ''
	SET @SQLBASE = '( ( ISNULL(P.NOMBRE,'''') +'' ''+ ISNULL(P.APELLIDOS,'''') COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'' ) OR ( P.NOMBRE COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'' ) OR (P.APELLIDOS COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'' ) OR ( P.CORREO LIKE ''%' + @VALOR + '%'' ) '
	SET @TEXTO = @VALOR
	SET @SQLRECORDATORIOS = @SQLBASE + ' OR (R.RECORDATORIO COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'') )'
	SET @SQLTAREAS = @SQLBASE + ' OR (T.TITULO COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'') )'
	SET @SQLCITAS = @SQLBASE + ' OR (C.ASUNTO COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'') )'
	SET @SQLCOBROSPENDIENTES = @SQLBASE + ' OR (O.CONCEPTO COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'') )'
	SET @SQLCOBROSAUDITAR = @SQLBASE + ' OR (O.CONCEPTO COLLATE Latin1_general_CI_AI LIKE ''%' + @VALOR + '%'') )'
	
END

--SELECT COUNT(*) FROM USUARIOS_FILTROS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND IDPANTALLA IN (410,411,412,414,415) 


IF @VIENEDEINICIALIZACION=0
BEGIN
IF LEN(@TEXTO)>0
BEGIN
	SET @TEXTO = <#SESSION.DB/>.DBO.PreparaCadena(@TEXTO)
	SET @SQLRECORDATORIOS = <#SESSION.DB/>.DBO.PreparaCadena(@SQLRECORDATORIOS)
	SET @SQLTAREAS = <#SESSION.DB/>.DBO.PreparaCadena(@SQLTAREAS)
	SET @SQLCITAS = <#SESSION.DB/>.DBO.PreparaCadena(@SQLCITAS)

	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
	VALUES (@IDUSUARIO, @VENTANA_RECORDATORIOS ,@FILTRO , @TEXTO, @SQLRECORDATORIOS, @NEWID)
	
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
	VALUES (@IDUSUARIO, @VENTANA_TAREAS ,@FILTRO , @TEXTO, @SQLTAREAS, @NEWID)
	
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
	VALUES (@IDUSUARIO, @VENTANA_CITAS ,@FILTRO , @TEXTO, @SQLCITAS, @NEWID)
	
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
	VALUES (@IDUSUARIO, @VENTANA_COBROS_PENDIENTES ,@FILTRO , @TEXTO, @SQLCOBROSPENDIENTES, @NEWID)
	
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
	VALUES (@IDUSUARIO, @VENTANA_COBROS_AUDITAR ,@FILTRO , @TEXTO, @SQLCOBROSAUDITAR, @NEWID)
END
END
SELECT Tipo, Texto, SQLTXT_EXP AS Aux FROM <#SESSION.DB/>.dbo.USUARIOS_FILTROS 
WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA IN (@VENTANA_RECORDATORIOS, @VENTANA_TAREAS, @VENTANA_CITAS) 
GROUP BY TIPO, TEXTO, SQLTXT_EXP


