//[filtrotiporeporte|Text,session.db|Untyped,session.idusuario|Untyped,idpantalla|Integer,]
--insert
DECLARE @TIPO INT
DECLARE @GRUPO VARCHAR(255)
DECLARE @TIPOREPORTE VARCHAR(255)
DECLARE @CONDICIONTIPOREPORTE VARCHAR(1000)
DECLARE @IDPANTALLA INT

SET @TIPO='20'
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SET @TIPOREPORTE=ISNULL(:FILTROTIPOREPORTE,'')
SET @CONDICIONTIPOREPORTE=''

SELECT @CONDICIONTIPOREPORTE =(CASE WHEN @TIPOREPORTE=1 THEN 'V.NUEVA=1' WHEN @TIPOREPORTE=2 THEN 'V.NUEVA=0' ELSE '1=1' END)

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT,SQLTXT_EXP)
VALUES (<#SESSION.IDUSUARIO/>, @IDPANTALLA,@TIPO, @TIPOREPORTE,@CONDICIONTIPOREPORTE,'')