//[session.idusuario|Untyped,session.idempresa|Untyped,idpantalla|Integer,tipo|Text,valor|Text,texto|Text,session.db|Untyped,]
--INSERT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @IDPANTALLA INT
DECLARE @TIPO VARCHAR(MAX), @VALOR VARCHAR(MAX), @TEXTO VARCHAR(MAX)

SET @IDPANTALLA = CAST(ISNULL(:idpantalla,0) AS INT)
SET @TIPO = ISNULL(:TIPO,'')
SET @VALOR = ISNULL(:VALOR,'')
SET @TEXTO = ISNULL(:TEXTO,'')

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDPANTALLA

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP)
  VALUES (@IDUSUARIO, @IDPANTALLA,0,@TIPO,@VALOR,@TEXTO)