//[session.db|Untyped,session.idusuario|Untyped,idpantalla|Integer,]
SELECT *,ISNULL(SQLTXT_exp,'0') AS FILTROGRUPO
FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS
WHERE IDUSUARIO=<#SESSION.IDUSUARIO> AND IDPANTALLA=:IDPANTALLA