//[session.db|Untyped,idcampo|Integer,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDCAMPO INT
SET @IDCAMPO = ISNULL(:IDCAMPO,0)
SELECT IdOpcion, Opcion, IdCampo 
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES 
WHERE IDCAMPO = @IDCAMPO ORDER BY OPCION