//[session.idusuario|Untyped,session.idempresa|Untyped,idpantalla|Integer,filtrotipo|Integer,indice|Integer,verprospectos|Integer,verventas|Integer,verempresa|Integer,tkca|Text,v|Text,filtro|Text,opciontexto|Text,session.db|Untyped,]
--INSERT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @IDPANTALLA INT, @FILTRO INT, @INDICE INT, @VERPROSPECTOS INT, @VERVENTAS INT, @VEREMPRESA INT
DECLARE @VALOR VARCHAR(MAX), @TKCA VARCHAR(64), @QRY VARCHAR(MAX), @CALIF VARCHAR(MAX), @OPCION VARCHAR(MAX)

SET @IDPANTALLA = CAST(ISNULL(:idpantalla,0) AS INT)
SET @FILTRO = CAST(ISNULL(:FiltroTipo,0) AS INT)
SET @INDICE = CAST(ISNULL(:indice,0) AS INT)
SET @VERPROSPECTOS = CAST(ISNULL(:verProspectos,0) AS INT)
SET @VERVENTAS = CAST(ISNULL(:verVentas,0) AS INT)
SET @VEREMPRESA = CAST(ISNULL(:verEmpresa,0) AS INT)
SET @TKCA = dbo.ValidaToken(ISNULL(:tkca,''))
SET @VALOR = ISNULL(:v,'')
SET @QRY = ''
SET @OPCION = ISNULL(:filtro,'')+':'+ISNULL(:OpcionTexto,'')

IF @VERPROSPECTOS = 1 BEGIN SET @CALIF = 'P.' END
IF @VERVENTAS = 1 BEGIN SET @CALIF = 'O.' END
IF @VEREMPRESA = 1 BEGIN SET @CALIF = 'COM.' END 

SET @QRY = @CALIF+'IDCATALOGOOPCION' + CAST(@INDICE AS VARCHAR(MAX)) + ' = '+@VALOR

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
  VALUES (@IDUSUARIO, @IDPANTALLA,@FILTRO, @OPCION, @QRY)