//[session.idempresa|Untyped|,session.idusuario|Untyped|,idpantalla|Integer|,session.db|Untyped|]
--SELECT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @IDPANTALLA INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS INT)

SELECT * ,@IDPANTALLA AS IDPANTALLA,OPERADOR AS OPER,
CASE 
	 WHEN TIPO < 0 THEN <#SESSION.DB/>.dbo.NombreFiltroPersonalizado (TIPO, @IDEMPRESA)
	 ELSE <#SESSION.DB/>.DBO.UDF_NOMBRE_FILTRO(TIPO)
	 END AS TIPOTXT 
FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS 
WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDPANTALLA
ORDER BY TIPO