//[tipo|Text,grupo|Text,usuario|Text,filtrofecha|Text,fechad|Text,session.convertcode|Untyped,fechah|Text,usuariotku|Text,session.db|Untyped,session.nivel|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,idpantalla|Integer,]
--INSERT
DECLARE @TEXTO VARCHAR(MAX)
DECLARE @TEXTOSQL VARCHAR(MAX)
DECLARE @SQLTXT_EXP VARCHAR(MAX)
DECLARE @FECHADESDE VARCHAR(MAX)
DECLARE @FECHAHASTA VARCHAR(MAX)

DECLARE @TIPO INT
DECLARE @GRUPO INT
DECLARE @IDUSUARIO INT
DECLARE @FILTROFECHA INT
DECLARE @IDS VARCHAR(MAX)
SET @TIPO=CAST(ISNULL(:TIPO,'') AS INT)
SET @GRUPO=CAST(ISNULL(:GRUPO,'') AS INT)
SET @IDUSUARIO = ISNULL(CAST(ISNULL(:usuario,'') AS INT), 0 )
SET @FILTROFECHA = CAST(ISNULL(:FILTROFECHA,'') AS INT)
SET @SQLTXT_EXP=' AND 1=1'
SET @FECHADESDE =  CONVERT(VARCHAR(10),ISNULL(:FECHAD,''),<#SESSION.CONVERTCODE/>)
SET @FECHAHASTA =  CONVERT(VARCHAR(10),ISNULL(:FECHAH,''),<#SESSION.CONVERTCODE/>)
SET @TEXTO = ''
SET @IDS=''

DECLARE @TKU VARCHAR(128)

SET @TKU = ISNULL(:USUARIOTKU, '')

IF(@TKU != '')BEGIN SELECT @IDUSUARIO = IDUSUARIO  FROM  <#SESSION.DB/>.DBO.USUARIOS U WHERE CAST(U.TKU AS VARCHAR(128)) = @TKU END


-- Prospectos
IF (<#SESSION.NIVEL/>=3)
BEGIN
  IF (exists(SELECT * FROM <#SESSION.DB/>.DBO.V_MODULOS_PERMISOS WHERE IDMODULO=8))
		  BEGIN
		    SELECT @IDS=CAST(ID AS VARCHAR(MAX))+','+@IDS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0)
		  	SET @IDS=@IDS+'0'
			SET @SQLTXT_EXP= 'AND PS.IDUSUARIO IN  ('+@IDS+') AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		  END
   ELSE
		   SET @SQLTXT_EXP = ' AND PS.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(MAX))+' AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
    SELECT  @TEXTO = 'Usuarios'
    SET @TEXTOSQL = '{TIPO:'+CAST(@TIPO AS VARCHAR(256))+',ID:'+CAST(@IDUSUARIO AS VARCHAR(256))+',DESDE:'''+@FECHADESDE+''',HASTA:'''+@FECHAHASTA+''',FILTROFECHA:'''+CAST(@FILTROFECHA AS VARCHAR(256))+'''}'
END
ELSE
BEGIN
IF @TIPO=1
  BEGIN
    SET @IDS=''
  	IF (@IDUSUARIO = 0)
	BEGIN
	    IF (exists(SELECT * FROM <#SESSION.DB/>.DBO.V_MODULOS_PERMISOS WHERE IDMODULO=8))
		  BEGIN
		    SELECT @IDS=CAST(ID AS VARCHAR(MAX))+','+@IDS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0)
		  	SET @IDS=@IDS+'0'
			SET @SQLTXT_EXP= 'AND PS.IDUSUARIO IN  ('+@IDS+') AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		  END
		ELSE
		BEGIN
		 IF (<#SESSION.NIVEL/>=1)
		    SET @SQLTXT_EXP = ' AND 1=1 AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		 ELSE
            SET @SQLTXT_EXP = ' AND U.IDGRUPO='+CAST(<#SESSION.IDGRUPO/> AS VARCHAR(10))+' AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
	     END
	END
	ELSE 
	BEGIN
		SELECT @SQLTXT_EXP = ' AND PS.IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(256))+' AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
	END
    SELECT  @TEXTO = 'Usuarios'
    SET @TEXTOSQL = '{TIPO:'+CAST(@TIPO AS VARCHAR(256))+',ID:'+CAST(@IDUSUARIO AS VARCHAR(256))+',DESDE:'''+@FECHADESDE+''',HASTA:'''+@FECHAHASTA+''',FILTROFECHA:'''+CAST(@FILTROFECHA AS VARCHAR(5))+'''}'
  END

IF @TIPO=2

  BEGIN
    IF (@GRUPO = 0)
	BEGIN
	    IF (exists(SELECT * FROM <#SESSION.DB/>.DBO.V_MODULOS_PERMISOS WHERE IDMODULO=8))
		  BEGIN
		    SELECT @IDS=CAST(ID AS VARCHAR(MAX))+','+@IDS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0)
		  	SET @IDS=@IDS+'0'
			SET @SQLTXT_EXP= 'AND PS.IDUSUARIO IN  ('+@IDS+') AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		  END
		ELSE
		 BEGIN
		 IF (<#SESSION.NIVEL/>=1)
		    SET @SQLTXT_EXP = ' AND 1=1 AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		 ELSE
            SET @SQLTXT_EXP = ' AND U.IDGRUPO='+CAST(<#SESSION.IDGRUPO/> AS VARCHAR(256))+' AND 1=1 AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'		   	
	     END
	END
	ELSE
	BEGIN
	    IF (exists(SELECT * FROM <#SESSION.DB/>.DBO.V_MODULOS_PERMISOS WHERE IDMODULO=8))
		  BEGIN
		    SELECT @IDS=CAST(ID AS VARCHAR(MAX))+','+@IDS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0)
		  	SET @IDS=@IDS+'0'
			SET @SQLTXT_EXP= 'AND PS.IDUSUARIO IN  ('+@IDS+') AND U.IDGRUPO='+CAST(@GRUPO AS VARCHAR(256))+' AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
		  END
		ELSE
		   SET @SQLTXT_EXP = ' AND U.IDGRUPO='+CAST(@GRUPO AS VARCHAR(256))+' AND <#SESSION.DB/>.dbo.GETONLYDATE(PS.FECHAHORA) BETWEEN CONVERT(DATETIME,''' + @FECHADESDE + ''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,''' + @FECHAHASTA + ''',<#SESSION.CONVERTCODE/>)'
	END
    SELECT  @TEXTO = 'Grupos'
    SET @TEXTOSQL = '{TIPO:'+CAST(@TIPO AS VARCHAR(256))+',ID:'+CAST(@GRUPO AS VARCHAR(256))+',DESDE:'''+@FECHADESDE+''',HASTA:'''+@FECHAHASTA+''',FILTROFECHA:'''+CAST(@FILTROFECHA AS VARCHAR(256))+'''}'
  END
END  

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT,SQLTXT_EXP)
VALUES (<#SESSION.IDUSUARIO/>, ISNULL(:IDPANTALLA,0),@TIPO, @TEXTO,@SQLTXT_EXP,@TEXTOSQL)