//[session.idusuario|Untyped,session.idempresa|Untyped,tiporeporte|Numeric,vista|Integer,grupo|Integer,tipo|Integer,session.db|Untyped,moneda|Integer,]
-- Select
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @TIPOREPORTE INT = ISNULL(:TIPOREPORTE,0)
DECLARE @REPORTEVISTA INT = ISNULL(:VISTA,1)
DECLARE @GRUPO INT = ISNULL(:GRUPO,0)
DECLARE @TIPO INT = ISNULL(:TIPO,0)
DECLARE @MONEDA INT = ISNULL(:MONEDA,0)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ESTIMACION_VENTAS @IDUSUARIO,@IDEMPRESA,@TIPOREPORTE,@REPORTEVISTA,@GRUPO,@MONEDA,@TIPO