//[accion|Text,filtrotipo|Text,filtrotipoagrupar|Text,filtrodetalle|Text,fecha_desde|Text,fecha_hasta|Text,session.db|Untyped,session.idusuario|Untyped,idpantalla|Integer,]
--INSERT

DECLARE @TEXTO VARCHAR(MAX), @TEXTOSQL VARCHAR(MAX), @VALORFILTRO VARCHAR(MAX)

DECLARE @TIPO INT, @TIPODETALLE INT, @ACCION INT

SET @ACCION=CAST(ISNULL(:ACCION,'') AS INT)


IF (@ACCION=1)
BEGIN
  SET @TIPO = CAST(ISNULL(:FILTROTIPO,'') AS INT)
  SELECT  @TEXTO = @TIPO
  SET @TEXTOSQL = (CASE WHEN @TIPO=-1 THEN ' 1=1' WHEN @TIPO=1 THEN ' VC.AUDITADO=1' ELSE ' VC.AUDITADO=0' END)
END

IF (@ACCION=2)
BEGIN
  SET @TIPO = CAST(ISNULL(:FILTROTIPOAGRUPAR,'') AS INT)
  SELECT  @TEXTO = @TIPO
  SET @TEXTOSQL = CAST(ISNULL(:FiltroDetalle,'') AS INT)
END

IF (@ACCION=3)
BEGIN
  SET @TIPO =  CAST(ISNULL(:FILTROTIPOAGRUPAR,'') AS INT)
  SELECT  @TEXTO = CAST(ISNULL(:FECHA_DESDE,'') AS VARCHAR(10))
  SET @TEXTOSQL = CAST(ISNULL(:FECHA_HASTA,'') AS VARCHAR(10))
END


IF @TEXTO!=''
BEGIN 
  SET @TEXTO = <#SESSION.DB/>.DBO.PreparaCadena(@TEXTO)
  SET @TEXTOSQL = <#SESSION.DB/>.DBO.PreparaCadena(@TEXTOSQL)

  INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
  VALUES (<#SESSION.IDUSUARIO/>, ISNULL(:IDPANTALLA,0),@ACCION, @TEXTO, @TEXTOSQL)
END