//[idusuariofiltro|Integer|,session.db|Untyped|,session.idusuario|Untyped|]
--DELETE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDUSUARIOFILTRO INT
SET @IDUSUARIOFILTRO=ISNULL(:IDUSUARIOFILTRO,0) 
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDUSUARIOFILTRO=@IDUSUARIOFILTRO