//[session.idusuario|Untyped,session.idempresa|Untyped,vista|Integer,grupo|Integer,tipo|Integer,moneda|Integer,session.db|Untyped,]
-- Select
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @REPORTEVISTA INT = ISNULL(:VISTA,1)
DECLARE @GRUPO INT = ISNULL(:GRUPO,0)
DECLARE @TIPO INT = ISNULL(:TIPO,0)
DECLARE @MONEDA INT = ISNULL(:MONEDA,0)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_OPORTUNIDAD_SIN_SEGUIMIENTO @IDUSUARIO,@IDEMPRESA,@REPORTEVISTA,@GRUPO,@MONEDA,@TIPO