//[idpantalla|Integer|,filtroagrupardetalle|Integer|,session.db|Untyped|,session.idusuario|Untyped|]
--SELECT  

DECLARE @IDPANTALLA  INT 
DECLARE @FILTROAGRUPARDETALLE INT 

SET @IDPANTALLA=ISNULL(:IDPANTALLA, 0)
SET @FILTROAGRUPARDETALLE= ISNULL(:FILTROAGRUPARDETALLE, 0) 


SELECT COUNT (*) AS HAYFILTROS, @IDPANTALLA AS IDPANTALLA, @FILTROAGRUPARDETALLE AS FILTROAGRUPARDETALLE
FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS
WHERE IDUSUARIO=<#SESSION.IDUSUARIO> AND IDPANTALLA=@IDPANTALLA