//[session.db|Untyped,session.idempresa|Untyped,tkcgeliminar|Text,tkcgnuevo|Text,]
--DELETE


DECLARE @IDEMPRESA INT 
DECLARE @TKCGELIMINAR VARCHAR(256) 
DECLARE @TKCGNUEVO VARCHAR(256) 
DECLARE @IDGRUPO_ELIMINAR INT 
DECLARE @IDGRUPO_NUEVO INT 


SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TKCGELIMINAR = ISNULL(:TKCGELIMINAR, '') 
SET @TKCGNUEVO = ISNULL(:TKCGNUEVO, '') 
SELECT @IDGRUPO_ELIMINAR= IDCOMPANIAGRUPO FROM <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS WHERE TKCG=@TKCGELIMINAR
SELECT @IDGRUPO_NUEVO= IDCOMPANIAGRUPO FROM <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS WHERE TKCG=@TKCGNUEVO


UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDCOMPANIAGRUPO = ISNULL(@IDGRUPO_NUEVO,0) WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDCOMPANIAGRUPO = ISNULL(@IDGRUPO_ELIMINAR,0)
INSERT INTO <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK) (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (27,ISNULL(@IDGRUPO_NUEVO,0),ISNULL(@IDGRUPO_ELIMINAR,0),1,<#SESSION.IDEMPRESA/>,GETDATE())
DELETE FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> and IDCOMPANIAGRUPO=ISNULL(@IDGRUPO_ELIMINAR,0)





