//[session.db|Untyped,session.idempresa|Untyped,tkcg|Text,]
--SELECT 


DECLARE @IDEMPRESA  INT 
DECLARE @TKCG VARCHAR(256)
SET @IDEMPRESA= <#SESSION.IDEMPRESA/> 
SET @TKCG=ISNULL(:TKCG, '') 


SELECT * FROM <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS WHERE IDEMPRESA =@IDEMPRESA AND TKCG=@TKCG  