//[]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @ID INT
DECLARE @EMAIL VARCHAR(1000)
SET @ID = ISNULL(:ID,0)
SET @EMAIL = ISNULL(:EMAIL,'')
UPDATE USUARIOS SET RECIBIRCORREOS=0 WHERE IDUSUARIO = @ID AND EMAIL=@EMAIL