//[f_usuario|Text,critarchivar|Text,descartado|Text,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,session.sessionid|Untyped,]
DECLARE @SQL VARCHAR(8000)
DECLARE @DESCARTADO VARCHAR(1)
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_CAMPOS VARCHAR(MAX)

SET @F_USUARIO = REPLACE(ISNULL(:F_USUARIO,''),'''','''''')
SET @CRITARCHIVAR = REPLACE(ISNULL(:CRITARCHIVAR,''),'''','''''')
SET @DESCARTADO=CAST (ISNULL(:DESCARTADO,0) AS VARCHAR(1))

declare @FILTRO varchar(max)
DECLARE @SERVIDORIP VARCHAR(16)
SET @SERVIDORIP =  REPLACE(@@SERVERNAME,'-','.')

SET @FILTRO = ''
select @FILTRO = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (<#SESSION.IDUSUARIO/>, 1)
SET @CAMPOS_PERSONALIZADOS_NOMBRES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 1, '<#SESSION.DB/>',1)
SET @CAMPOS_PERSONALIZADOS_VALORES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 2, '<#SESSION.DB/>',1)
SET @CAMPOS_PERSONALIZADOS_CAMPOS   = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 3, '<#SESSION.DB/>',1)

IF @FILTRO='' 
 SET @FILTRO = ISNULL(@FILTRO,'')+' '+ REPLACE(' AND A.IDUSUARIO in (select idusuario from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizados (<#SESSION.IDUSUARIO/>))' ,'''','''''') 

SELECT @SQL = ' bcp " SELECT  ''ID'', ''NOMBRE'', ''APELLIDOS'','' TITULO'',''CORREO'', ''EMPRESA'', ''NOEMPLEADOS'', '
SELECT @SQL = @SQL + ' ''PUESTO'', ''URL'', ''TELEFONO'', ''TELEFONO 2'', ''MOVIL'', ''CREADO EL'', ''COMENTARIOS'', ''FECHA ÚLTIMO SEGUIMIENTO'', ''ÚLTIMO CONTACTO'', ' 
SELECT @SQL = @SQL + ' ''PAIS'', ''ESTADO'',''MUNICIPIO'',''DIRECCION1'', ''DIRECCION 2'', ''CIUDAD'', ''CODIGOPOSTAL'', ''ORIGEN'', ''FASE'', ' 
SELECT @SQL = @SQL + ' ''EJECUTIVO_NOMBRE'' '+@CAMPOS_PERSONALIZADOS_NOMBRES + ', ''ETIQUETAS'' '
SELECT @SQL = @SQL + ' " queryout C:\FileRepository\exporta\archivos\prospectos-<#SESSION.SESSIONID/>-1.csv   -c -C"Latin1" -t, -T -S'+ @@servername
exec master..xp_cmdshell @sql

SELECT @SQL = ''
SELECT @SQL = ' bcp  " SELECT DISTINCT P.IDPROSPECTO, NOMBRE_COM  COLLATE DATABASE_DEFAULT, APELLIDOS_COM COLLATE DATABASE_DEFAULT, TITULO_COM , CORREO_COM, EMPRESA_COM, CAST(NOEMPLEADOS AS VARCHAR(10))  COLLATE DATABASE_DEFAULT, PUESTO_COM  COLLATE DATABASE_DEFAULT, URL_COM, TELEFONO_COM, TELEFONO2_COM, MOVIL, ''''+SALESUP_CT.DBO.FechaFormato(FECHACONTACTO,2) COLLATE DATABASE_DEFAULT+'''' ,  COMMENTARIOS_MINI, F_ULTIMOSEGUIMIENTO ,SALESUP_CT.DBO.PREPARACADENAAPP2(REPLACE(ULTIMOSEGUIMIENTO,'','','''')) COLLATE DATABASE_DEFAULT AS ULTIMOSEGUIMIENTO, PAIS, ESTADO,MUNICIPIO,DIRECCION1_COM, DIRECCION2_COM COLLATE DATABASE_DEFAULT, CIUDAD_COM COLLATE DATABASE_DEFAULT, CODIGOPOSTAL COLLATE DATABASE_DEFAULT, ORIGEN  COLLATE DATABASE_DEFAULT, FASE  COLLATE DATABASE_DEFAULT, U.NOMBRE + '' ''  COLLATE DATABASE_DEFAULT + U.APELLIDOS  COLLATE DATABASE_DEFAULT AS EJECUTIVO_NOMBRE '+ @CAMPOS_PERSONALIZADOS_VALORES+', <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO)  COLLATE DATABASE_DEFAULT  FROM <#SESSION.DB/>.DBO.V_PROSPECTOS P WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK), <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) WHERE P.IDEMPRESA = <#SESSIOn.IDEMPRESA/> '+@F_USUARIO +' AND U.IDUSUARIO = P.IDUSUARIO AND P.ESCLIENTE = 0 AND ESOPORTUNIDAD = 0 AND P.DESCARTADO='+@DESCARTADO+' AND A.IDPROSPECTO = P.IDPROSPECTO  '+@FILTRO+' '+@CRITARCHIVAR+'  " queryout C:\FileRepository\exporta\archivos\prospectos-<#SESSION.SESSIONID/>-2.csv   -c -C"Latin1" -t, -T -S'+ @@servername

SET @SQL = REPLACE(@SQL, 'DBO.getonlydate', 'SALESUP_CT.DBO.getonlydate')

exec master..xp_cmdshell @SQL
set @sql = 'copy C:\FileRepository\exporta\archivos\prospectos-<#SESSION.SESSIONID/>-1.csv +  C:\FileRepository\exporta\archivos\prospectos-<#SESSION.SESSIONID/>-2.csv C:\FileRepository\exporta\archivos\prospectos-<#SESSION.SESSIONID/>.csv'

exec master..xp_cmdshell  @sql


