//[session.idusuario|Untyped,session.idempresa|Untyped,session.sessionid|Untyped,session.db|Untyped,nivel|Text,f_usuario|Text,]
--SELECT
/*PROTEGIDO*/
DECLARE @SQL VARCHAR(8000)
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_CAMPOS VARCHAR(MAX)
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
declare @FILTRO varchar(MAX)
DECLARE @SESSIONID VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @NIVEL VARCHAR(MAX)

SET @FILTRO = ''
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS  INT)
SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS  INT)
SET @SESSIONID ='<#SESSION.SESSIONID/>'
select @FILTRO = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, 4)

SET @CAMPOS_PERSONALIZADOS_NOMBRES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(@IDEMPRESA, 1, '<#SESSION.DB/>',3)
SET @CAMPOS_PERSONALIZADOS_VALORES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(@IDEMPRESA, 2, '<#SESSION.DB/>',3)
SET @CAMPOS_PERSONALIZADOS_CAMPOS   = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(@IDEMPRESA, 3, '<#SESSION.DB/>',3)

SET @NIVEL = ISNULL(:NIVEL,'')
SET @F_USUARIO = ISNULL(:F_USUARIO,'')

DECLARE @SERVIDORIP VARCHAR(16)
SET @SERVIDORIP =  REPLACE(@@SERVERNAME,'-','.')

SELECT @SQL = ' bcp " SELECT ''ID'',''NOMBRE''  COLLATE DATABASE_DEFAULT , ''APELLIDOS'' COLLATE DATABASE_DEFAULT ,''CORREO'' COLLATE DATABASE_DEFAULT , ''EMPRESA'' COLLATE DATABASE_DEFAULT ,''PAIS'' COLLATE DATABASE_DEFAULT,''ESTADO'' COLLATE DATABASE_DEFAULT,''MUNICIPIO'' COLLATE DATABASE_DEFAULT, ''DIRECCION'' COLLATE DATABASE_DEFAULT, ''PUESTO'' COLLATE DATABASE_DEFAULT , '
SELECT @SQL = @SQL + ' ''ORIGEN'' COLLATE DATABASE_DEFAULT , ''URL'' COLLATE DATABASE_DEFAULT , ''TELEFONO'' COLLATE DATABASE_DEFAULT , ''TELEFONO2'' COLLATE DATABASE_DEFAULT , ''MOVIL'' COLLATE DATABASE_DEFAULT , ''FECHACONTACTO'' COLLATE DATABASE_DEFAULT , ''COMENTARIOS'' COLLATE DATABASE_DEFAULT , '
SELECT @SQL = @SQL + ' ''EJECUTIVO'' COLLATE DATABASE_DEFAULT , ''TRANSACCIONES'' COLLATE DATABASE_DEFAULT ,''MONTO_COMPRADO'' COLLATE DATABASE_DEFAULT , ''ANTICIPOS'' COLLATE DATABASE_DEFAULT , ''SALDOS''  COLLATE DATABASE_DEFAULT '+@CAMPOS_PERSONALIZADOS_NOMBRES + ', ''ETIQUETAS'' COLLATE DATABASE_DEFAULT '
SELECT @SQL = @SQL + ' " queryout C:\FileRepository\exporta\archivos\clientes-'+@SESSIONID+'-1.csv -c -C"Latin1" -t, -T -S'+ @@servername
exec master..xp_cmdshell @sql
SELECT @SQL = ''
SELECT @SQL = ' bcp " SELECT P.IDPROSPECTO,NOMBRE_COM, APELLIDOS_COM, CORREO_COM, EMPRESA_COM,PAIS,ESTADO,MUNICIPIO,ISNULL(DIRECCION1_COM,'''') + '' '' + ISNULL(DIRECCION2_COM,''''),'
SELECT @SQL = @SQL + ' PUESTO_COM, P.ORIGEN, URL_COM, TELEFONO_COM, TELEFONO2_COM, MOVIL, CAST(FECHACONTACTO AS VARCHAR(12)),'
SELECT @SQL = @SQL + ' COMMENTARIOS_MINI, U.INICIALES , COUNT (DISTINCT V.IDVENTA) , SUM (V.MONTO) , SUM (V.ANTICIPOS_MONTO), SUM (V.SALDO_MONTO) '+ @CAMPOS_PERSONALIZADOS_VALORES+'  ,  <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) '
SELECT @SQL = @SQL + ' FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO WITH(NOLOCK) ' 
SELECT @SQL = @SQL + ' JOIN <#SESSION.DB/>.DBO.V_PROSPECTOS P WITH(NOLOCK) ON P.IDORIGEN = PO.IDORIGEN '
SELECT @SQL = @SQL + ' LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO'
SELECT @SQL = @SQL + ' LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK) ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD'
SELECT @SQL = @SQL + ' JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO '
SELECT @SQL = @SQL + ' LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A ON P.IDPROSPECTO = A.IDPROSPECTO '
SELECT @SQL = @SQL + ' WHERE '
SELECT @SQL = @SQL + ' P.IDEMPRESA =  '+ CAST(@IDEMPRESA AS VARCHAR(100)) + ' AND P.ESCLIENTE =1 '
SELECT @SQL = @SQL + ' '+@F_USUARIO+' '+@NIVEL+' '+ @FILTRO
SELECT @SQL = @SQL + ' GROUP BY P.IDPROSPECTO,P.MOVIL, P.FECHACONTACTO, COMMENTARIOS_MINI,PAIS,ESTADO,MUNICIPIO, P.DIRECCION1_COM,P.DIRECCION2_COM ,P.PUESTO_COM, P.CORREO_COM, P.URL_COM, P.TELEFONO_COM, P.TELEFONO2_COM,P.NOMBRE_COM, P.APELLIDOS_COM, P.EMPRESA_COM, P.ORIGEN, U.INICIALES, P.PUESTO, P.CORREO , P.IDPROSPECTO  '+@CAMPOS_PERSONALIZADOS_CAMPOS
SELECT @SQL = @SQL + ' " queryout C:\FileRepository\exporta\archivos\clientes-'+@SESSIONID+'-2.csv -c -C"Latin1" -t, -T -S'+ @@servername
exec master..xp_cmdshell @sql
SET @SQL =  'copy C:\FileRepository\exporta\archivos\clientes-'+@SESSIONID+'-1.csv + C:\FileRepository\exporta\archivos\clientes-'+@SESSIONID+'-2.csv C:\FileRepository\exporta\archivos\clientes-'+@SESSIONID+'.csv' 
exec master..xp_cmdshell @SQL