//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,f_usuario|Text,session.sessionid|Untyped,]
--SELECT
	--UPDATE
declare @FILTRO varchar(MAX)
DECLARE @SQL VARCHAR(8000)
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_CAMPOS VARCHAR(MAX)

DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES_P VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES_P VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_CAMPOS_P VARCHAR(MAX)

SET @FILTRO = ''
select @FILTRO = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (<#SESSION.IDUSUARIO/>, 2)

SET @CAMPOS_PERSONALIZADOS_NOMBRES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 1, '<#SESSION.DB/>',2)
SET @CAMPOS_PERSONALIZADOS_VALORES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 2, '<#SESSION.DB/>',2)
SET @CAMPOS_PERSONALIZADOS_CAMPOS   = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 3, '<#SESSION.DB/>',2)

SET @CAMPOS_PERSONALIZADOS_NOMBRES_P  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 1, '<#SESSION.DB/>',1)
SET @CAMPOS_PERSONALIZADOS_VALORES_P  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 2, '<#SESSION.DB/>',1)
SET @CAMPOS_PERSONALIZADOS_CAMPOS_P   = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 3, '<#SESSION.DB/>',1)


DECLARE @SERVIDORIP VARCHAR(16)
SET @SERVIDORIP =  REPLACE(@@SERVERNAME,'-','.')

DECLARE @F_USUARIO VARCHAR(MAX)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')

SELECT @SQL = ' bcp "   '
SELECT @SQL = @SQL + ' SELECT ''Id prospecto'','' Fecha Cierre'' COLLATE DATABASE_DEFAULT , ''Prospecto'' COLLATE DATABASE_DEFAULT, ''Empresa'' COLLATE DATABASE_DEFAULT, ''Concepto'' COLLATE DATABASE_DEFAULT, ''Fecha de creación'' COLLATE DATABASE_DEFAULT, ''Línea'' COLLATE DATABASE_DEFAULT, ''Fase''  COLLATE DATABASE_DEFAULT, ''Monto''  COLLATE DATABASE_DEFAULT,'
SELECT @SQL = @SQL + ' ''Certeza''  COLLATE DATABASE_DEFAULT, ''Comisión'' COLLATE DATABASE_DEFAULT, ''Comisión porcentaje'' COLLATE DATABASE_DEFAULT, '
SELECT @SQL = @SQL + ' ''Correo'' COLLATE DATABASE_DEFAULT, ''Teléfono'' COLLATE DATABASE_DEFAULT, ''Teléfono 2'' COLLATE DATABASE_DEFAULT, ''Móvil'' COLLATE DATABASE_DEFAULT, ''Calle'' COLLATE DATABASE_DEFAULT, ''Colonia'' COLLATE DATABASE_DEFAULT, ''Página Web'' COLLATE DATABASE_DEFAULT, ''Ejecutivo'' COLLATE DATABASE_DEFAULT'+@CAMPOS_PERSONALIZADOS_NOMBRES_P+@CAMPOS_PERSONALIZADOS_NOMBRES + ', ''Etiquetas'' COLLATE DATABASE_DEFAULT, ''Código SalesUp!'' COLLATE DATABASE_DEFAULT, ''País'' COLLATE DATABASE_DEFAULT, ''Región'' COLLATE DATABASE_DEFAULT, ''Municipio'' COLLATE DATABASE_DEFAULT, ''Último seguimiento'' COLLATE DATABASE_DEFAULT'
SELECT @SQL = @SQL + ' " queryout C:\FileRepository\exporta\archivos\oportunidades-<#SESSION.SESSIONID/>-1.csv -c -C"Latin1" -t, -T -S'+ @@servername
exec master..xp_cmdshell @sql
SELECT @SQL = ''
SELECT @SQL =  'bcp " SELECT O.IDPROSPECTO,CAST(FECHA_CIERRE AS VARCHAR(12)), O.PROSPECTO, O.EMPRESA , SALESUP_CT.DBO.PreparaCadenaExportacion(REPLACE(CONCEPTO,'','','''')) AS CONCEPTO, CAST(O.FECHAHORA AS VARCHAR(12))  , O.LINEA_PRODUCTO, '
SELECT @SQL = @SQL + ' O.FASE,  CONVERT(VARCHAR(32),ISNULL(MONTO, 0)),  '
SELECT @SQL = @SQL + ' CONVERT(VARCHAR(32), ISNULL(CERTEZA, 0)), CONVERT(VARCHAR(32), ISNULL(COMISION_MONTO, 0 ) ), '
SELECT @SQL = @SQL + ' CAST(O.COMISION AS VARCHAR(12)), O.CORREO, O.TELEFONO, O.TELEFONO2, O.MOVIL, O.CALLE , O.COLONIA , O.URLWEB , EJECUTIVO '+ @CAMPOS_PERSONALIZADOS_VALORES_P+ @CAMPOS_PERSONALIZADOS_VALORES+' , <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO), CAST(O.IDOPORTUNIDAD AS VARCHAR(12)), P.PAIS, P.ESTADO,P.MUNICIPIO,o.ULTIMO_CONTACTO '
SELECT @SQL = @SQL + ' FROM <#SESSION.DB/>.DBO.V_OPORTUNIDADES O WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK), '
SELECT @SQL = @SQL + ' <#SESSION.DB/>.DBO.V_PROSPECTOS P WITH(NOLOCK)  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA2 WITH(NOLOCK) ON PA2.IDPROSPECTO = P.IDPROSPECTO AND PA2.IDUSUARIO = <#SESSION.IDUSUARIO/>, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F WITH(NOLOCK), <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK)' 
SELECT @SQL = @SQL + ' WHERE  O.IDPROSPECTO = P.IDPROSPECTO '+@F_USUARIO+' AND O.IDUSUARIO = U.IDUSUARIO ' 
SELECT @SQL = @SQL + ' AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>'
SELECT @SQL = @SQL + @FILTRO
SELECT @SQL = @SQL + ' ORDER BY 1 " '
SELECT @SQL = @SQL + ' queryout C:\FileRepository\exporta\archivos\oportunidades-<#SESSION.SESSIONID/>-2.csv   -c -C"Latin1"  -t, -T -S'+ @@servername
exec master..xp_cmdshell @sql

SET @SQL =  'copy C:\FileRepository\exporta\archivos\oportunidades-<#SESSION.SESSIONID/>-1.csv + C:\FileRepository\exporta\archivos\oportunidades-<#SESSION.SESSIONID/>-2.csv C:\FileRepository\exporta\archivos\oportunidades-<#SESSION.IDUSUARIO/>.csv'
exec master..xp_cmdshell @sql
 
