//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,f_usuario|Text,session.sessionid|Untyped,]
--select update
declare @FILTRO varchar(8000)
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_CAMPOS VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
SET @FILTRO = ''
select @FILTRO = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (<#SESSION.IDUSUARIO/>, 3)

SET @CAMPOS_PERSONALIZADOS_NOMBRES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 1, '<#SESSION.DB/>',4)
SET @CAMPOS_PERSONALIZADOS_VALORES  = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 2, '<#SESSION.DB/>',4)
SET @CAMPOS_PERSONALIZADOS_CAMPOS   = <#SESSION.DB/>.DBO.ObtieneCamposLlaveNuevo(<#SESSIOn.IDEMPRESA/>, 3, '<#SESSION.DB/>',4)

DECLARE @SERVIDORIP VARCHAR(16)
SET @SERVIDORIP =  REPLACE(@@SERVERNAME,'-','.')
SET @F_USUARIO=ISNULL(:F_USUARIO,'')


DECLARE @aSQL VARCHAR(8000)
DECLARE @SQL VARCHAR(MAX)
SELECT @SQL = ' bcp " '
SELECT @SQL = @SQL + ' SELECT  ''Prospecto''  COLLATE DATABASE_DEFAULT , ''Origen''  COLLATE DATABASE_DEFAULT , ''Empresa'' COLLATE DATABASE_DEFAULT , ''Concepto'' COLLATE DATABASE_DEFAULT , ''Línea'' COLLATE DATABASE_DEFAULT , ''Último pago'' COLLATE DATABASE_DEFAULT , ''Anticipos'' COLLATE DATABASE_DEFAULT ,'
SELECT @SQL = @SQL + ' ''Comisiones'' COLLATE DATABASE_DEFAULT , ''Saldo'' COLLATE DATABASE_DEFAULT , ''Total'' COLLATE DATABASE_DEFAULT , '
SELECT @SQL = @SQL + '  '' Fecha de cierre'' COLLATE DATABASE_DEFAULT  AS GANADA_FECHA, ''Ejecutivo''  COLLATE DATABASE_DEFAULT '+@CAMPOS_PERSONALIZADOS_NOMBRES + ', ''Etiquetas'' COLLATE DATABASE_DEFAULT , ''Venta'' COLLATE DATABASE_DEFAULT '
SELECT @SQL = @SQL + ' " queryout C:\FileRepository\exporta\archivos\ventas-<#SESSION.SESSIONID/>-1.csv   -c -C"Latin1"  -t, -T -S'+ @@servername

SET @aSQL = LEFT(@SQL, 8000)
EXec master..xp_cmdshell @asql
SELECT @SQL = ''
SELECT @SQL = @SQL + ' bcp "  SELECT  PROSPECTO   COLLATE DATABASE_DEFAULT, PO.ORIGEN   COLLATE DATABASE_DEFAULT,  V.EMPRESA   COLLATE DATABASE_DEFAULT, V.CONCEPTO   COLLATE DATABASE_DEFAULT, V.LINEA_PRODUCTO  COLLATE DATABASE_DEFAULT, '
SELECT @SQL = @SQL + ' CONVERT(VARCHAR(12),PAGADA_FECHA,103)  COLLATE DATABASE_DEFAULT, CAST(ANTICIPOS_MONTO AS VARCHAR(32)), CAST(ANTICIPOS_COMISION AS VARCHAR(32)), '
SELECT @SQL = @SQL + ' CAST(SALDO_MONTO AS VARCHAR(32)), CAST(V.MONTO AS VARCHAR(32)),CONVERT(VARCHAR(12),V.GANADA_FECHA, 103), EJECUTIVO_NOMBRE  COLLATE DATABASE_DEFAULT '+ @CAMPOS_PERSONALIZADOS_VALORES+' ,  <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO), CAST(V.IDVENTA AS VARCHAR(32)) '
SELECT @SQL = @SQL + ' FROM <#SESSION.DB/>.DBO.V_VENTAS_EXPORTA V WITH(NOLOCK), <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK), <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) '
SELECT @SQL = @SQL + ' LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO WITH(NOLOCK) ON PO.IDORIGEN=P.IDORIGEN,'
SELECT @SQL = @SQL + ' <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK), '
SELECT @SQL = @SQL + ' <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP WHERE  V.IDOPORTUNIDAD = O.IDOPORTUNIDAD AND  O.IDPROSPECTO = P.IDPROSPECTO AND '  
SELECT @SQL = @SQL + '   P.DESCARTADO=0 AND V.IDUSUARIO = U.IDUSUARIO AND '   
SELECT @SQL = @SQL + '   O.IDFASE = F.IDFASE AND '
SELECT @SQL = @SQL + '   O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/>'
SELECT @SQL = @SQL + ''+@F_USUARIO+' '+@FILTRO
SELECT @SQL = @SQL + ' ORDER BY V.GANADA_FECHA " '
SELECT @SQL = @SQL + ' queryout C:\FileRepository\exporta\archivos\ventas-<#SESSION.SESSIONID/>-2.csv   -c -C"Latin1"  -t, -T -S'+ @@servername
--select @sql
--EXec master..xp_cmdshell @sql
SET @aSQL = LEFT(@SQL, 8000)
EXec master..xp_cmdshell @asql


SET @SQL =  'copy C:\FileRepository\exporta\archivos\ventas-<#SESSION.SESSIONID/>-1.csv + C:\FileRepository\exporta\archivos\ventas-<#SESSION.SESSIONID/>-2.csv C:\FileRepository\exporta\archivos\ventas-<#SESSION.SESSIONID/>.csv'
SET @aSQL = LEFT(@SQL, 8000)
EXec master..xp_cmdshell @asql

