//[session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/
declare @llave varchar(128)
declare @contrasenia varchar(1024)
  
set @llave = salesup_ct.dbo.getsalesupkey()

IF (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO =<#SESSION.IDUSUARIO/> ) != 0
SELECT 
  IDMAILCONFIG, EMAIL, IDUSUARIO, POP3_HOST, POP3_PORT, SMTP_HOST, SMTP_PORT, POP3_USERNAME,
  INBOX_HABILITADO, INBOX_TIPO,INBOX_USA_SSL,INBOX_DEJARCOPIA, 
   convert(varchar(max),DecryptByPassPhrase(@llave, POP3_PASSWORD)) AS POP3_PASSWORD, SMTP_USERNAME, 
   convert(varchar(max),DecryptByPassPhrase(@llave, SMTP_PASSWORD)) AS SMTP_PASSWORD,CCO ,isnull(TIPO,-1) as TIPO, USE_SSL, FIRMA 
FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO =<#SESSION.IDUSUARIO/> 
ELSE
SELECT 
  0 IDMAILCONFIG, 0 EMAIL, <#SESSION.IDUSUARIO/>  IDUSUARIO, '' POP3_HOST, '' POP3_PORT, 
  '' SMTP_HOST, '' SMTP_PORT, '' POP3_USERNAME,
  '0' INBOX_HABILITADO,1 INBOX_TIPO, '' INBOX_USA_SSL,'' INBOX_DEJARCOPIA, 
  '' AS POP3_PASSWORD, '' SMTP_USERNAME, 
  '' AS SMTP_PASSWORD, '' CCO  ,-1 TIPO, '' USE_SSL,  '' FIRMA  
