//[session.idusuario|Untyped,email|Text,cco|Text,firma|Text,predeterminado|Integer,idusuariocorreo|Integer,session.db|Untyped,]
-- INSERT

/*PROTEGIDO*/
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @EMAIL VARCHAR(256) = ISNULL(:EMAIL,'')
DECLARE @CCO VARCHAR(256) = ISNULL(:CCO,'')
DECLARE @FIRMA VARCHAR(MAX) = ISNULL(:FIRMA,'')
DECLARE @PREDETERMINADO INT = ISNULL(:PREDETERMINADO,1)
DECLARE @IDUSUARIOCORREO INT = ISNULL(:IDUSUARIOCORREO,0)

DECLARE @POP3_HOST VARCHAR(256)
DECLARE @POP3_PORT VARCHAR(256)
DECLARE @SMTP_HOST VARCHAR(256)
DECLARE @SMTP_PORT VARCHAR(256)
DECLARE @TIPO INT
DECLARE @USE_SSL INT
DECLARE @ESTADO INT 
DECLARE @INBOX_USA_SSL INT
DECLARE @INBOX_ESTADO INT
DECLARE @TIPO_CUENTA INT
DECLARE @POP3_USERNAME VARCHAR(256)
DECLARE @SMTP_USERNAME VARCHAR(256)
DECLARE @POP3_PASSWORD VARCHAR(256)
DECLARE @SMTP_PASSWORD VARCHAR(256)
DECLARE @TIENECONFIGURACION INT
DECLARE @INBOX_HABILITADO INT

SELECT @TIENECONFIGURACION = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO = @IDUSUARIO

UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET EMAIL = @EMAIL, CCO = @CCO, FIRMA = @FIRMA, PREDETERMINADO = @PREDETERMINADO WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO

SELECT @POP3_HOST = POP3_HOST,@POP3_PORT = POP3_PORT,@SMTP_HOST = SMTP_HOST, @SMTP_PORT = SMTP_PORT, @POP3_USERNAME = POP3_USERNAME,@POP3_PASSWORD = POP3_PASSWORD, @SMTP_USERNAME = SMTP_USERNAME, @SMTP_PASSWORD = SMTP_PASSWORD, @TIPO = PROVEEDOR, @USE_SSL = USE_SSL,@ESTADO = ESTADO,
@INBOX_USA_SSL = INBOX_USA_SSL, @INBOX_ESTADO = INBOX_ESTADO, @TIPO_CUENTA = TIPO_CUENTA 
FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS 
WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO

IF(@PREDETERMINADO = 1)
BEGIN
	 IF(@TIENECONFIGURACION > 0)
	 BEGIN
	 	  IF(@TIPO_CUENTA = 1)
		  BEGIN
	 	  	   UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET
     	  	   EMAIL=@EMAIL,
     	  	   SMTP_HOST=@SMTP_HOST,
     	  	   SMTP_PORT=@SMTP_PORT,
     	  	   SMTP_USERNAME=@SMTP_USERNAME,
     	  	   SMTP_PASSWORD=@SMTP_PASSWORD,
     	  	   USE_SSL=@USE_SSL,
     	  	   TIPO=@TIPO,
			   CCO = @CCO,
			   FIRMA = @FIRMA,
 	 	  	   ESTADO=@ESTADO
		  	   WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
	 	  END
		  ELSE IF(@TIPO_CUENTA = 3)
	 	  BEGIN
	 	  	   UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET
			   EMAIL=@EMAIL,
     	  	   SMTP_HOST=@SMTP_HOST,
     	  	   SMTP_PORT=@SMTP_PORT,
     	  	   SMTP_USERNAME=@SMTP_USERNAME,
     	  	   SMTP_PASSWORD=@SMTP_PASSWORD,
     	  	   USE_SSL=@USE_SSL,
     	  	   POP3_HOST=@POP3_HOST,
     	  	   POP3_PORT=@POP3_PORT,
     	  	   POP3_USERNAME=@POP3_USERNAME,
     	  	   POP3_PASSWORD=@POP3_PASSWORD,
     	  	   INBOX_USA_SSL=@INBOX_USA_SSL,
     	  	   TIPO=@TIPO,
			   CCO = @CCO,
			   FIRMA = @FIRMA,
 	 	  	   INBOX_ESTADO=@INBOX_ESTADO,
		  	   INBOX_HABILITADO = 2
		  	   WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
	 	  END
	END
	ELSE
	BEGIN
		 IF(@TIPO_CUENTA = 2 OR @TIPO_CUENTA = 3)
		 BEGIN
		 	 SET @INBOX_HABILITADO = 2
		 END
		 
		 INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG 
	 	 (IDUSUARIO,EMAIL,POP3_HOST,POP3_PORT,SMTP_HOST,SMTP_PORT,POP3_USERNAME,POP3_PASSWORD,SMTP_USERNAME,SMTP_PASSWORD,TIPO,USE_SSL,ESTADO,INBOX_USA_SSL,INBOX_ESTADO,INBOX_HABILITADO)
	 	 VALUES(@IDUSUARIO,@EMAIL,@POP3_HOST,@POP3_PORT,@SMTP_HOST,@SMTP_PORT,@POP3_USERNAME,@POP3_PASSWORD,@SMTP_USERNAME,@SMTP_PASSWORD,@TIPO,@USE_SSL,@ESTADO,@INBOX_USA_SSL,@INBOX_ESTADO,@INBOX_HABILITADO)
	END
	
	IF(@TIPO <> 1 AND @TIPO_CUENTA = 2)
	BEGIN
		 UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET GMAILTOKEN = NULL WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
	END

	UPDATE <#SESSION.DB/>.DBO.USUARIOS SET MAILCONFIG = 1 WHERE  IDUSUARIO = @IDUSUARIO
END