//[session.idusuario|Untyped,session.email|Untyped,session.db|Untyped,]
--select 
DECLARE @IDUSUARIO INT
DECLARE @INBOXACTIVO INT, @COMPOSEACTIVO INT, @INBOXSTATUS INT, @COMPOSESTATUS INT, @MAILTOACTIVO INT 
DECLARE @ReplyTo VARCHAR(MAX) 
SET @IDUSUARIO = <#SESSION.idusuario/>
SET @INBOXACTIVO = 0 SET @COMPOSEACTIVO = 0 SET @COMPOSESTATUS = 0 SET @INBOXSTATUS = 0 SET @MAILTOACTIVO = 0 
set @ReplyTo = '<#SESSION.EMAIL/>'
IF OBJECT_ID('tempdb..#TempTABLA_LOGIN') IS NOT NULL DROP TABLE #TempTABLA_LOGIN
SELECT * INTO #TempTABLA_LOGIN FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIO = @IDUSUARIO

SELECT @INBOXACTIVO = COUNT(*) FROM #TempTABLA_LOGIN WHERE TIPO_CUENTA IN (2,3) AND ESTADO != 2 
SELECT @INBOXSTATUS = COUNT(*) FROM #TempTABLA_LOGIN WHERE ESTADO = 0 AND TIPO_CUENTA IN (2,3) 
SELECT @COMPOSEACTIVO = COUNT(*) FROM #TempTABLA_LOGIN WHERE TIPO_CUENTA IN (1,3) AND ESTADO != 2 
SELECT @COMPOSESTATUS = COUNT(*) FROM #TempTABLA_LOGIN WHERE ESTADO = 0 AND TIPO_CUENTA IN (1,3) 
SELECT @MAILTOACTIVO = COUNT(*) FROM #TempTABLA_LOGIN WHERE ESTADO = 2
SELECT TOP 1 @ReplyTo = EMAIL FROM DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO AND ISNULL(EMAIL,'')!=''
SELECT TOP 1 @ReplyTo = EMAIL FROM #TempTABLA_LOGIN WHERE ESTADO = 0 AND TIPO_CUENTA IN (1,3) AND PREDETERMINADO = 1  AND ISNULL(EMAIL,'')!=''

if len(@ReplyTo)=0 set @ReplyTo = '<#SESSION.EMAIL/>' 
SELECT @INBOXACTIVO AS INBOXACTIVO, @COMPOSEACTIVO AS COMPOSEACTIVO, @INBOXSTATUS AS INBOXSTATUS, @COMPOSESTATUS AS COMPOSESTATUS, @MAILTOACTIVO AS MAILTOACTIVO, @ReplyTo as ReplyTo

