//[session.idusuario|Untyped,session.convertcode|Untyped,tktr|Text,hora|Text,vence|Text,session.db|Untyped,]
--UPDATE 

DECLARE @TKTR VARCHAR(64), @HORA VARCHAR(MAX), @COMENTARIOSISTEMA VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @IDTAREA INT
DECLARE @CONVERTCODE INT, @PARAQUIEN INT, @TIPOSUCESO INT, @IDPROSPECTO INT, @IDTAREASEGUIMIENTO INT, @IDESTADO INT
DECLARE @FECHAVENCIMIENTO DATETIME, @VENCE DATETIME


SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

SET @TKTR = dbo.ValidaToken( ISNULL( :tktr, ''))
SET @HORA =  ISNULL(:HORA, '')
SET @VENCE = CONVERT(DATETIME, ISNULL(:VENCE, '')+' ' +@HORA, @CONVERTCODE)
SET @IDESTADO = 6


SELECT @IDTAREA = IDTAREA, @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.TAREAS WHERE TKTR = @TKTR

SET @COMENTARIOSISTEMA = 'Se ha solicitado una modificación de fecha de vencimiento, fecha propuesta - '+SALESUP_CT.dbo.FechaFormato(@VENCE,2) 
INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)
	
SELECT TOP 1 @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO 
FROM <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO 
WHERE IDTAREA = @IDTAREA ORDER BY 1 DESC
	
UPDATE <#SESSION.DB/>.dbo.TAREAS SET IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO, 
FECHA_PROPUESTA = @VENCE, IDESTADO = @IDESTADO
WHERE IDTAREA = @IDTAREA

EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, 33, @IDPROSPECTO, @CONVERTCODE, @COMENTARIOSISTEMA, @IDTAREA
