//[session.idusuario|Untyped,session.convertcode|Untyped,tktr|Text,session.db|Untyped,fecha|Text,hora|Text,]
--UPDATE 

DECLARE @TKTR VARCHAR(64), @HORA VARCHAR(MAX), @COMENTARIOSISTEMA VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @VENCIMIENTO INT, @RESPONSABLE INT, @IDREALIZADOR INT, @IDTAREA INT
DECLARE @CONVERTCODE INT, @TIPOSUCESO INT, @IDPROSPECTO INT, @MASTIEMPO INT, @IDTAREASEGUIMIENTO INT
DECLARE @FECHAVENCIMIENTO DATETIME, @VENCE DATETIME
DECLARE @FECHAHORA VARCHAR(20) 


SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @HORA = ISNULL(:HORA, '') 
SET @FECHAHORA = ISNULL(:fecha, '') +' '+@HORA
SET @TKTR = ISNULL(:tktr, '')

SET @VENCE = CONVERT(DATETIME, @FECHAHORA, @CONVERTCODE)

SET @COMENTARIOSISTEMA = ''

SELECT @IDTAREA = IDTAREA, @FECHAVENCIMIENTO = FECHA_VENCIMIENTO, @MASTIEMPO = ISNULL(MASTIEMPO,0)
FROM <#SESSION.DB/>.dbo.TAREAS WHERE TKTR = @TKTR

SET @COMENTARIOSISTEMA = 'La fecha de vencimiento se ha modificado, fecha anterior '+SALESUP_CT.dbo.FechaFormato(@FECHAVENCIMIENTO,2) 
INSERT INTO <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO (IDUSUARIO, FECHAHORA, COMENTARIO, IDTAREA)
VALUES (@IDUSUARIO, GETDATE(), @COMENTARIOSISTEMA, @IDTAREA)
/*Suceso tarea*/
SET @TIPOSUCESO = 45
EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @CONVERTCODE, @COMENTARIOSISTEMA, @IDTAREA

SET @MASTIEMPO = @MASTIEMPO + 1

SELECT TOP 1 @IDTAREASEGUIMIENTO = IDTAREASEGUIMIENTO 
FROM <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO 
WHERE IDTAREA = @IDTAREA ORDER BY 1 DESC

UPDATE <#SESSION.DB/>.dbo.TAREAS 
SET IDTAREASEGUIMIENTO = @IDTAREASEGUIMIENTO,
MASTIEMPO = @MASTIEMPO, FECHA_VENCIMIENTO = @VENCE, IDESTADO = 1
WHERE IDTAREA = @IDTAREA