//[idusuariocorreo|Integer,usuario|Text,contrasenia|Text,servidorsmtp|Text,puertosmtp|Integer,seguridadsmtp|Integer,session.db|Untyped,servidorpop|Text,puertopop|Integer,seguridadpop|Text,]
--UPDATE
/*PROTEGIDO*/

DECLARE @IDUSUARIOCORREO INT = :IDUSUARIOCORREO
DECLARE @USUARIO VARCHAR(MAX) = :USUARIO
DECLARE @CONTRASENIA VARCHAR(MAX) = :CONTRASENIA
DECLARE @servidorSMTP VARCHAR(MAX) = :servidorSMTP
DECLARE @puertoSMTP VARCHAR(MAX) = :puertoSMTP
DECLARE @seguridadSMTP VARCHAR(MAX) = :seguridadSMTP
DECLARE @llave VARCHAR(128) = salesup_ct.dbo.getsalesupkey()
DECLARE @SMTP_PASSWORD VARCHAR(MAX)

DECLARE @servidorPOP3 VARCHAR(MAX) = :servidorPOP
DECLARE @puertoPOP3 VARCHAR(MAX) = :puertoPOP
DECLARE @seguridadPOP3 VARCHAR(MAX) = :seguridadPOP
DECLARE @POP3_PASSWORD VARCHAR(MAX)

DECLARE @CONFUSUARIO VARCHAR(MAX)
DECLARE @GMAILTOKEN  VARCHAR(MAX)
DECLARE @PROVEEDOR INT
DECLARE @IDUSUARIO INT


DECLARE @TIPO_CUENTA INT

SELECT @IDUSUARIO = IDUSUARIO,@TIPO_CUENTA = TIPO_CUENTA,@PROVEEDOR = PROVEEDOR FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO

IF (@PROVEEDOR = 1) OR (@PROVEEDOR = 32)
BEGIN
	SELECT @CONFUSUARIO = TMPTOKEN FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
	IF @CONFUSUARIO  IS NOT NULL
	BEGIN
	  SELECT @USUARIO = SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@CONFUSUARIO,'|') WHERE OCCURENCEID = 1
	  SELECT @GMAILTOKEN = SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@CONFUSUARIO,'|') WHERE OCCURENCEID = 2
	END
	UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET EMAIL = @USUARIO,  GMAILTOKEN = @GMAILTOKEN WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO 
END


IF(@TIPO_CUENTA = 1)
BEGIN
	 SET @SMTP_PASSWORD = EncryptByPassPhrase(@llave,@CONTRASENIA)
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET SMTP_USERNAME = @USUARIO, SMTP_HOST = @SERVIDORSMTP, SMTP_PORT = @PUERTOSMTP,SMTP_PASSWORD = @SMTP_PASSWORD, USE_SSL = @SEGURIDADSMTP WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO
END
ELSE IF(@TIPO_CUENTA = 2)
BEGIN
	 SET @POP3_PASSWORD = EncryptByPassPhrase(@llave,@CONTRASENIA)
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET POP3_USERNAME = @USUARIO, POP3_HOST = @SERVIDORPOP3, POP3_PORT = @PUERTOPOP3,POP3_PASSWORD = @POP3_PASSWORD, INBOX_USA_SSL = @SEGURIDADPOP3 WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO
END
ELSE IF(@TIPO_CUENTA = 3)
BEGIN
	 SET @SMTP_PASSWORD = EncryptByPassPhrase(@llave,@CONTRASENIA)
	 SET @POP3_PASSWORD = EncryptByPassPhrase(@llave,@CONTRASENIA)
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET SMTP_USERNAME = @USUARIO, SMTP_HOST = @SERVIDORSMTP, SMTP_PORT = @PUERTOSMTP,SMTP_PASSWORD = @SMTP_PASSWORD, USE_SSL = @SEGURIDADSMTP, POP3_USERNAME = @USUARIO, POP3_HOST = @SERVIDORPOP3, POP3_PORT = @PUERTOPOP3,POP3_PASSWORD = @POP3_PASSWORD, INBOX_USA_SSL = @SEGURIDADPOP3 WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO
END