//[session.idusuario|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>

SELECT ISNULL(TMPTOKEN,'') AS TOKEN FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
AND TMPTOKEN LIKE '%refresh_token%'