//[idoportunidad|Integer,tko|Text,session.db|Untyped,]
-- SELECT 
DECLARE @TABLAERRORES TABLE (ID INT IDENTITY, PRODUCTO VARCHAR(MAX), EXISTENCIA INT, CANTIDAD INT)
DECLARE @TABLA TABLE (ID INT IDENTITY, IDPRODUCTO INT, CANTIDAD INT)
DECLARE @TO INT = 1
DECLARE @TOTAL INT,@CANTIDAD INT,@EXISTENCIA INT, @IDPRODUCTO INT
DECLARE @IDOPORTUNIDAD INT = :IDOPORTUNIDAD
DECLARE @TKO VARCHAR(256) = ISNULL(:TKO,'')

IF(@TKO <> '')
BEGIN
	 SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE TKO = @TKO
END

INSERT INTO @TABLA (IDPRODUCTO, CANTIDAD)
SELECT IDPRODUCTO, SUM(CANTIDAD) AS CANTIDAD FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_PRODUCTOS WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD GROUP BY IDPRODUCTO

SELECT @TOTAL = COUNT(*) FROM @TABLA

WHILE(@TO <= @TOTAL)
BEGIN
	SELECT @IDPRODUCTO = IDPRODUCTO, @CANTIDAD = CANTIDAD FROM @TABLA WHERE ID = @TO
	SELECT @EXISTENCIA = EXISTENCIA FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDPRODUCTO = @IDPRODUCTO
	
	IF(@EXISTENCIA = 0 OR (@EXISTENCIA >= 1 AND @EXISTENCIA < @CANTIDAD))
	BEGIN
		INSERT INTO @TABLAERRORES (PRODUCTO,EXISTENCIA,CANTIDAD) SELECT NOMBRE,EXISTENCIA, @CANTIDAD FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDPRODUCTO = @IDPRODUCTO
	END
	SET @TO = @TO + 1
END

SELECT * FROM @TABLAERRORES