//[session.idusuario|Untyped,usuario|Text,servidorpop|Text,puertopop|Integer,servidorsmtp|Text,puertosmtp|Integer,proveedor|Integer,seguridadsmtp|Integer,seguridadpop|Integer,tipocuenta|Integer,session.db|Untyped,contrasenia|Text,session.email|Untyped,]
-- INSERT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @USUARIO VARCHAR(256) = ISNULL(:USUARIO,'')
DECLARE @POP3_HOST VARCHAR(256) = :SERVIDORPOP
DECLARE @POP3_PORT VARCHAR(256) = :PUERTOPOP
DECLARE @SMTP_HOST VARCHAR(256) = :SERVIDORSMTP
DECLARE @SMTP_PORT VARCHAR(256) = :PUERTOSMTP
DECLARE @PROVEEDOR INT = :PROVEEDOR
DECLARE @USE_SSL INT = :SEGURIDADSMTP
DECLARE @ESTADO INT = 0 
DECLARE @INBOX_USA_SSL INT = ISNULL(:SEGURIDADPOP,0)
DECLARE @INBOX_ESTADO INT = 0
DECLARE @TIPO_CUENTA INT = :TIPOCUENTA
DECLARE @POP3_USERNAME VARCHAR(256) = NULL
DECLARE @SMTP_USERNAME VARCHAR(256) = NULL
DECLARE @POP3_PASSWORD VARCHAR(256) = NULL
DECLARE @SMTP_PASSWORD VARCHAR(256) = NULL
DECLARE @TIENECONFIGURACION INT
DECLARE @PREDETERMINADO INT = 1
DECLARE @INBOX_HABILITADO INT = 0
DECLARE @GMAILTOKEN VARCHAR(MAX) = NULL
DECLARE @CONFUSUARIO VARCHAR(MAX) = NULL
DECLARE @IDUSUARIOCORREO INT
DECLARE @TIPOCUENTA_AUX INT
DECLARE @IDAUX INT

SELECT @TIENECONFIGURACION = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO = @IDUSUARIO

DECLARE @llave VARCHAR(128) = salesup_ct.dbo.getsalesupkey()

IF(@TIPO_CUENTA = 1 AND @PROVEEDOR = 0)
BEGIN
	SET @SMTP_USERNAME = @USUARIO
	SET @SMTP_PASSWORD = EncryptByPassPhrase(@llave,:CONTRASENIA)
END
ELSE IF(@TIPO_CUENTA = 2 AND @PROVEEDOR = 0)
BEGIN
	SET @POP3_USERNAME = @USUARIO
	SET @POP3_PASSWORD = EncryptByPassPhrase(@llave,:CONTRASENIA)
END
ELSE
BEGIN
	SET @SMTP_USERNAME = @USUARIO
	SET @SMTP_PASSWORD = EncryptByPassPhrase(@llave,:CONTRASENIA)
	SET @POP3_USERNAME = @USUARIO
	SET @POP3_PASSWORD = EncryptByPassPhrase(@llave,:CONTRASENIA)
END

IF (@PROVEEDOR = 1) OR (@PROVEEDOR = 33)
BEGIN
	SELECT @CONFUSUARIO = TMPTOKEN FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
	SELECT @USUARIO = SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@CONFUSUARIO,'|') WHERE OCCURENCEID = 1
	SELECT @GMAILTOKEN = SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@CONFUSUARIO,'|') WHERE OCCURENCEID = 2
	SELECT @SMTP_USERNAME = @USUARIO
	SELECT @POP3_USERNAME = @USUARIO
END

IF(@TIPO_CUENTA = 3)
BEGIN
	UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 0 WHERE IDUSUARIO = @IDUSUARIO
END
ELSE
BEGIN
	
	IF(@TIPO_CUENTA = 2)
	BEGIN
		 SET @PREDETERMINADO = 0 
		 SET @TIPOCUENTA_AUX = 1
	END
	ELSE
	BEGIN
		 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 0 WHERE IDUSUARIO = @IDUSUARIO AND (TIPO_CUENTA = 1 OR TIPO_CUENTA = 3)
		 SET @TIPOCUENTA_AUX = 2
	END
		
	SELECT TOP 1 @IDAUX = IDUSUARIOCORREO FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE TIPO_CUENTA <> 3 AND TIPO_CUENTA = @TIPOCUENTA_AUX
	
	--UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 1 WHERE IDUSUARIO = @IDUSUARIO AND IDUSUARIOCORREO = @IDAUX
END 

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS 
(IDUSUARIO,EMAIL,POP3_HOST,POP3_PORT,SMTP_HOST,SMTP_PORT,POP3_USERNAME,POP3_PASSWORD,SMTP_USERNAME,SMTP_PASSWORD,PROVEEDOR,USE_SSL,ESTADO,INBOX_USA_SSL,INBOX_ESTADO,GMAILTOKEN,TIPO_CUENTA,PREDETERMINADO)
VALUES(@IDUSUARIO,@USUARIO,@POP3_HOST,@POP3_PORT,@SMTP_HOST,@SMTP_PORT,@POP3_USERNAME,@POP3_PASSWORD,@SMTP_USERNAME,@SMTP_PASSWORD,@PROVEEDOR,@USE_SSL,@ESTADO,@INBOX_USA_SSL,@INBOX_ESTADO,@GMAILTOKEN,@TIPO_CUENTA,@PREDETERMINADO)

SELECT TOP 1 @IDUSUARIOCORREO = IDUSUARIOCORREO FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIO = @IDUSUARIO AND TIPO_CUENTA = @TIPO_CUENTA AND PROVEEDOR = @PROVEEDOR ORDER BY 1 DESC 

	IF(@TIENECONFIGURACION > 0)
	 BEGIN
	 	  IF(@TIPO_CUENTA = 1)
		  BEGIN
	 	  	   UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET
     	  	   EMAIL=@USUARIO,
     	  	   SMTP_HOST=@SMTP_HOST,
     	  	   SMTP_PORT=@SMTP_PORT,
     	  	   SMTP_USERNAME=@SMTP_USERNAME,
     	  	   SMTP_PASSWORD=@SMTP_PASSWORD,
     	  	   USE_SSL=@USE_SSL,
     	  	   TIPO=@PROVEEDOR,
 	 	  	   ESTADO=1
		  	   WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
	 	  END
	 	  ELSE IF(@TIPO_CUENTA = 2)
	 	  BEGIN
	 	  	   UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET
     	  	   POP3_HOST=@POP3_HOST,
     	  	   POP3_PORT=@POP3_PORT,
     	  	   POP3_USERNAME=@POP3_USERNAME,
     	  	   POP3_PASSWORD=@POP3_PASSWORD,
     	  	   INBOX_USA_SSL=@INBOX_USA_SSL,
     	  	   TIPO=@PROVEEDOR,
 	 	  	   INBOX_ESTADO=@INBOX_ESTADO,
		  	   INBOX_HABILITADO = 2
		  	   WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
			   
			   EXEC <#SESSION.DB/>.DBO.SP_AGREAR_INBOXTABS_USUARIOS @IDUSUARIO
	 	  END
		  ELSE IF(@TIPO_CUENTA = 3)
	 	  BEGIN
	 	  	   UPDATE <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG SET
			   EMAIL=@USUARIO,
     	  	   SMTP_HOST=@SMTP_HOST,
     	  	   SMTP_PORT=@SMTP_PORT,
     	  	   SMTP_USERNAME=@SMTP_USERNAME,
     	  	   SMTP_PASSWORD=@SMTP_PASSWORD,
     	  	   USE_SSL=@USE_SSL,
     	  	   POP3_HOST=@POP3_HOST,
     	  	   POP3_PORT=@POP3_PORT,
     	  	   POP3_USERNAME=@POP3_USERNAME,
     	  	   POP3_PASSWORD=@POP3_PASSWORD,
     	  	   INBOX_USA_SSL=@INBOX_USA_SSL,
     	  	   TIPO=@PROVEEDOR,
 	 	  	   INBOX_ESTADO=@INBOX_ESTADO,
		  	   INBOX_HABILITADO = 2,
			   ESTADO = 1
		  	   WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
			   
			   EXEC <#SESSION.DB/>.DBO.SP_AGREAR_INBOXTABS_USUARIOS @IDUSUARIO
	 	  END
	END
	ELSE
	BEGIN
		 IF(@TIPO_CUENTA = 2 OR @TIPO_CUENTA = 3)
		 BEGIN
		 	 SET @INBOX_HABILITADO = 2
			 
			 EXEC <#SESSION.DB/>.DBO.SP_AGREAR_INBOXTABS_USUARIOS @IDUSUARIO
		 END
		 
		 INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG 
	 	 (IDUSUARIO,EMAIL,POP3_HOST,POP3_PORT,SMTP_HOST,SMTP_PORT,POP3_USERNAME,POP3_PASSWORD,SMTP_USERNAME,SMTP_PASSWORD,TIPO,USE_SSL,ESTADO,INBOX_USA_SSL,INBOX_ESTADO,INBOX_HABILITADO)
	 	 VALUES(@IDUSUARIO,@USUARIO,@POP3_HOST,@POP3_PORT,@SMTP_HOST,@SMTP_PORT,@POP3_USERNAME,@POP3_PASSWORD,@SMTP_USERNAME,@SMTP_PASSWORD,@PROVEEDOR,@USE_SSL,@ESTADO,@INBOX_USA_SSL,@INBOX_ESTADO,@INBOX_HABILITADO)
	END
	

	UPDATE <#SESSION.DB/>.DBO.USUARIOS SET TMPTOKEN = NULL WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
	UPDATE <#SESSION.DB/>.DBO.USUARIOS SET MAILCONFIG = 1 WHERE  IDUSUARIO = @IDUSUARIO


IF((@TIPO_CUENTA = 1 OR @TIPO_CUENTA = 3))
BEGIN
	 IF(@PROVEEDOR <> 0)
	 BEGIN
	 	  EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_EMAIL_CONFIGURADO @IDUSUARIO,'<#SESSION.EMAIL/>', @IDUSUARIOCORREO
	 END	
	 ELSE
	 BEGIN
	 	  EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_EMAIL_CONFIGURADO @IDUSUARIO,@USUARIO, @IDUSUARIOCORREO
	 END
END