//[tipo|Integer,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/

DECLARE @TIPO INT = ISNULL(:TIPO,'0')

UPDATE <#SESSION.DB/>.DBO.USUARIOS SET TMPTOKEN = NULL WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>

SELECT IDPROVEEDOR, PROVEEDOR FROM PROVEEDORES WHERE @TIPO IN (SELECT SPLITVALUE FROM DBO.SPLIT(TIPO,',')) ORDER BY PROVEEDOR