//[session.db|Untyped,session.idusuario|Untyped,]
 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO =<#SESSION.IDUSUARIO/> 

 UPDATE <#SESSION.DB/>.DBO.USUARIOS SET
    MAILCONFIG = 2  
  WHERE
    IDUSUARIO = <#SESSION.IDUSUARIO/>