//[session.idusuario|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT
SET @IDUSUARIO=<#SESSION.IDUSUARIO/>

SELECT EMAIL,CONTRASENA FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=@IDUSUARIO