//[idusuariocorreo|Integer,session.idusuario|Untyped,session.db|Untyped,]
-- update
/*PROTEGIDO*/

DECLARE @IDUSUARIOCORREO INT = ISNULL(:IDUSUARIOCORREO,0)
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @TIPO_CUENTA INT

SELECT @TIPO_CUENTA = TIPO_CUENTA FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO

IF(@TIPO_CUENTA = 3)
BEGIN
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 0 WHERE IDUSUARIO = @IDUSUARIO
END
ELSE
BEGIN
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 0 WHERE IDUSUARIO = @IDUSUARIO AND (TIPO_CUENTA = @TIPO_CUENTA OR TIPO_CUENTA = 3)
END

UPDATE <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS SET PREDETERMINADO = 1 WHERE IDUSUARIOCORREO = @IDUSUARIOCORREO
