//[sp_browser|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDMONEDA VARCHAR(10), @MOBILE VARCHAR(MAX)


SELECT @IDMONEDA = IDMONEDA from <#SESSION.DB/>.DBO.MONEDAS where idempresa = <#SESSION.IDEMPRESA/> AND PORDEFECTO = 1

SET @MOBILE = SALESUP_CT.DBO.EsMobile('<#SP_BROWSER/>') 

SELECT @IDMONEDA AS MONEDA, @MOBILE AS MOBILE
