//[session.db|Untyped,session.idusuario|Untyped,]
--insert
 delete from <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG where idusuario=<#SESSION.IDUSUARIO/>
 update <#SESSION.DB/>.DBO.USUARIOS SET MAILCONFIG=0 WHERE idusuario=<#SESSION.IDUSUARIO/>
 

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDELIMINADO,TIPO,IDUSUARIO,FECHAHORA) VALUES (29,'',1,<#SESSION.IDUSUARIO/>,GETDATE())