//[session.idusuario|Untyped,session.db|Untyped,]
-- SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>

SELECT 
IDUSUARIOCORREO,
EMAIL AS CUENTA,
P.PROVEEDOR,TIPO_CUENTA,PREDETERMINADO,P.IDPROVEEDOR
FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS UC, PROVEEDORES P
WHERE IDUSUARIO = @IDUSUARIO AND UC.PROVEEDOR = P.IDPROVEEDOR
ORDER BY CUENTA