//[session.db|Untyped,tipo_meta|Text,]
--SELECT 
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @TIPO_META VARCHAR(1000)
SET @TIPO_META = ISNULL(:TIPO_META,'')
SELECT META_NOMBRE, TIPO AS TIPOMETA FROM <#SESSION.DB/>.DBO.V_TIPOS_METAS WHERE META_NOMBRE LIKE '%'+@TIPO_META+'%'