//[fecha_desde|Text,session.convertcode|Untyped,fecha_hasta|Text,periodo_seleccionado|Text,activas|Text,crituser|Text,crituser2|Text,crituser3|Text,session.nivel|Untyped,session.db|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @PERIODO_SELECCIONADO VARCHAR(MAX)
DECLARE @ACTIVAS INT
DECLARE @EJECUTIVOS VARCHAR(2024)
DECLARE @NIVEL INT
DECLARE @ACTIVE VARCHAR(MAX)

DECLARE @FECHADESDE VARCHAR(MAX)
DECLARE @FECHAHASTA VARCHAR(MAX) 

DECLARE @FECHA_DESDE DATETIME
DECLARE @FECHA_HASTA DATETIME

DECLARE @CONDICION VARCHAR(MAX)
DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @CRITUSER VARCHAR(MAX)
DECLARE @CRITUSER2 VARCHAR(MAX)
DECLARE @CRITUSER3 VARCHAR(MAX)

SET @CONDICION = ''
SELECT @FECHADESDE = :FECHA_DESDE
SELECT @FECHAHASTA = :FECHA_HASTA
SET @PERIODO_SELECCIONADO= :PERIODO_SELECCIONADO
SET @ACTIVE = ISNULL(:ACTIVAS,'')
SET @CRITUSER = ISNULL(:CRITUSER,'')
SET @CRITUSER2 = ISNULL(:CRITUSER2,'')
SET @CRITUSER3 = ISNULL(:CRITUSER3,'')





/**VALIDACION DE FECHAS UNDEFINED*/
IF( @FECHADESDE= 'UNDEFINED') BEGIN SET @FECHA_HASTA= ''  END ELSE BEGIN SET @FECHA_HASTA=CONVERT(DATETIME, @FECHAHASTA, <#SESSION.CONVERTCODE/>) END
IF( @FECHADESDE= 'UNDEFINED') BEGIN SET @FECHA_DESDE='' END ELSE BEGIN SET @FECHA_DESDE=CONVERT(DATETIME, @FECHADESDE, <#SESSION.CONVERTCODE/>) END 



/***/
--Nuevos filtros

IF(@PERIODO_SELECCIONADO = '6')

BEGIN
SET @CONDICION = ' AND DBO.GETONLYDATE(FIN) BETWEEN CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_DESDE, <#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_HASTA,<#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) '
END
ELSE IF(@PERIODO_SELECCIONADO = '-1')
BEGIN
	 SET @CONDICION = ' '
END
ELSE 
BEGIN
   SET @CONDICION = (SELECT SALESUP_CT.dbo.CALCULOFECHA(@PERIODO_SELECCIONADO))
END


--Fin nuevos filtros
 
IF (@ACTIVE='')
   SET @ACTIVAS=1
ELSE
  SET @ACTIVAS=CAST(@ACTIVE AS INT)

IF (<#SESSION.NIVEL/>=3)
BEGIN
   SET @EXECSQL = 'SELECT DISTINCT TP.IDCOMPONENTE, TP.NOMBRE_COMPONENTE, TP.CATEGORIASVISIBLES, TP.FORMATO ' 
   SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.V_TIPOS_METAS AS VTP ON VTP.TIPO = UM.TIPO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN dbo.TIPOS_METAS AS TP ON TP.IDCOMPONENTE = UM.IDCOMPONENTE '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE (UM.IDUSUARIO=<#SESSION.IDUSUARIO/> OR UM.IDGRUPO=<#SESSION.IDGRUPO/> OR UM.IDEMPRESA=<#SESSION.IDEMPRESA/>) '
   SET @EXECSQL = @EXECSQL + ISNULL(@CONDICION, '')+' AND ((<#SESSION.IDUSUARIO/> = UM.IDUSUARIO) OR (<#SESSION.IDGRUPO>=UM.IDGRUPO AND <#SESSION.IDUSUARIO>= US.IDUSUARIO) OR ((UM.IDGRUPO IS NULL) AND (UM.IDUSUARIO IS NULL))) ' + ' AND TP.IDCOMPONENTE IS NOT NULL '
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5)) + ' '+@CRITUSER+' '+@CRITUSER2+' '+@CRITUSER3+' '
   EXEC(@EXECSQL)
END
ELSE IF (<#SESSION.NIVEL/>=2)
BEGIN   
   SET @EXECSQL = 'SELECT DISTINCT TP.IDCOMPONENTE, TP.NOMBRE_COMPONENTE, TP.CATEGORIASVISIBLES, TP.FORMATO ' 
   SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.V_TIPOS_METAS AS VTP ON VTP.TIPO = UM.TIPO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN dbo.TIPOS_METAS AS TP ON TP.IDCOMPONENTE = UM.IDCOMPONENTE '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE UM.IDEMPRESA=<#SESSION.IDEMPRESA/> AND TP.IDCOMPONENTE IS NOT NULL '
   SET @EXECSQL = @EXECSQL + ISNULL(@CONDICION, '')
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5))  + ' '+@CRITUSER+' '+@CRITUSER2+' '+@CRITUSER3+' '
   EXEC(@EXECSQL)

END 
ELSE IF (<#SESSION.NIVEL/>=1)
BEGIN
   SET @EXECSQL = 'SELECT DISTINCT TP.IDCOMPONENTE, TP.NOMBRE_COMPONENTE, TP.CATEGORIASVISIBLES, TP.FORMATO ' 
   SET @EXECSQL = @EXECSQL + ' FROM  <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.V_TIPOS_METAS AS VTP ON VTP.TIPO = UM.TIPO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN dbo.TIPOS_METAS AS TP ON TP.IDCOMPONENTE = UM.IDCOMPONENTE '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE UM.IDUSUARIO_ASIGNO=US.IDUSUARIO AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> AND TP.IDCOMPONENTE IS NOT NULL '
   SET @EXECSQL = @EXECSQL + ISNULL(@CONDICION, '') 
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5))  + ' '+@CRITUSER+' '+@CRITUSER2+' '+@CRITUSER3+' '
   EXEC(@EXECSQL)
END 
