//[session.idempresa|Untyped,idmeta|Integer,session.db|Untyped,]
-- SELECT
DECLARE @IDMETA INT
DECLARE @IDEMPRESA INT
DECLARE @CONT INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDMETA = ISNULL(:IDMETA,0)

SELECT @CONT = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_METAS WHERE IDMETA = @IDMETA AND IDEMPRESA = @IDEMPRESA

IF(@CONT > 0)
	EXEC <#SESSION.DB/>.DBO.SP_METAS_DETALLES_CONTEO @IDMETA
ELSE
	SELECT 0 AS TOTAL, 'Información no encontrada.' as META
	
	