//[session.db|Untyped,metas|Integer,session.idempresa|Untyped,session.convertcode|Untyped,]
--select

DECLARE @TIPO INT
DECLARE @IDGRUPO INT
DECLARE @IDUSUARIO INT
DECLARE @IDPROSPECTO INT
DECLARE @IDLINEA INT
DECLARE @INICIO VARCHAR(233)
DECLARE @FIN VARCHAR(233)

SELECT @TIPO=TIPO, @IDGRUPO=IDGRUPO, @IDUSUARIO=IDUSUARIO, @IDPROSPECTO = IDPROSPECTO, @IDLINEA = IDLINEA, @INICIO=INICIO, @FIN=FIN FROM <#SESSION.DB/>.DBO.USUARIOS_METAS WHERE IDMETA=ISNULL(:METAS,0)

IF @TIPO=100
BEGIN
  SELECT
    P.NOMBRE,    P.CORREO,
   ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR,
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO,
    F.FASE, F.ORDEN,CAST (COMENTARIOS AS VARCHAR(128))+'...' AS INTRO, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
    <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHACONTACTO) AS FECHA_CONTACTO,
    P.ETIQUETAS_TXT AS ETIQUETAS,
    
   (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, 
    
	(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO,
   (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO
   
  FROM <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F ON F.IDFASE=P.IDFASE
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON P.IDUSUARIO=U.IDUSUARIO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> AND P.DESCARTADO=0 AND P.ESOPORTUNIDAD=0 AND (P.IMPORTADODESDE = 0 OR P.IMPORTADODESDE = 1) 
  AND <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END

IF @TIPO=101
BEGIN
  SELECT
    P.NOMBRE,    P.CORREO,
   ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR,
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO,
    F.FASE, F.ORDEN,CAST (COMENTARIOS AS VARCHAR(128))+'...' AS INTRO, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
    <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHACONTACTO) AS FECHA_CONTACTO,
    P.ETIQUETAS_TXT AS ETIQUETAS,
    
   (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, 
    
	(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO,
   (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO
   
  FROM <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F ON F.IDFASE=P.IDFASE
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON P.IDUSUARIO=U.IDUSUARIO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> AND U.IDGRUPO = @IDGRUPO AND P.DESCARTADO=0 AND (P.IMPORTADODESDE = 0 OR P.IMPORTADODESDE = 1) 
  AND <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END

IF @TIPO=102
BEGIN
  SELECT
    P.NOMBRE,    P.CORREO,
   ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR,
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO,
    F.FASE, F.ORDEN,CAST (COMENTARIOS AS VARCHAR(128))+'...' AS INTRO, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
    <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHACONTACTO) AS FECHA_CONTACTO,
    P.ETIQUETAS_TXT AS ETIQUETAS,
    
   (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, 
    
	(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO,
   (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO
   
  FROM <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F ON F.IDFASE=P.IDFASE
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON P.IDUSUARIO=U.IDUSUARIO
  WHERE P.IDUSUARIO=@IDUSUARIO AND P.DESCARTADO=0 AND (P.IMPORTADODESDE = 0 OR P.IMPORTADODESDE = 1) --AND P.ESOPORTUNIDAD=0
  AND <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END

IF (@TIPO=200)OR(@TIPO=203)OR(@TIPO=206)
BEGIN
	SELECT O.IDOPORTUNIDAD, F.FASE,(P.NOMBRE+' '+P.APELLIDOS) AS NOMBRE_PROSPECTO, P.EMPRESA, P.CORREO, P.TELEFONO, P.TELEFONO2, P.MOVIL, O.CONCEPTO, U.INICIALES, 
	(SELECT ORIGEN FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,
	LP.LINEA_PRODUCTO, O.MONTO, O.COMISION, O.CERTEZA, O.FECHA_CIERRE,(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO
	FROM <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.PROSPECTOS P,<#SESSION.DB/>.DBO.OPORTUNIDADES O
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP ON O.IDLINEA_PRODUCTO=LP.IDLINEA_PRODUCTO
	LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON O.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
	LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F ON O.IDFASE=F.IDFASE
	WHERE O.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND P.IDPROSPECTO=O.IDPROSPECTO
	AND <#SESSION.DB/>.DBO.GETONLYDATE(O.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END

IF (@TIPO=201)OR(@TIPO=204)OR(@TIPO=207)
BEGIN
	SELECT O.IDOPORTUNIDAD, F.FASE,(P.NOMBRE+' '+P.APELLIDOS) AS NOMBRE_PROSPECTO, P.EMPRESA, P.CORREO, P.TELEFONO, P.TELEFONO2, P.MOVIL, O.CONCEPTO, U.INICIALES, 
	(SELECT ORIGEN FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,
	LP.LINEA_PRODUCTO, O.MONTO, O.COMISION, O.CERTEZA, O.FECHA_CIERRE,(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO
	FROM <#SESSION.DB/>.DBO.PROSPECTOS P,<#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.OPORTUNIDADES O
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP ON O.IDLINEA_PRODUCTO=LP.IDLINEA_PRODUCTO
	LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON O.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
	LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F ON O.IDFASE=F.IDFASE 
	WHERE O.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND U.IDGRUPO=@IDGRUPO AND P.IDPROSPECTO=O.IDPROSPECTO
	AND <#SESSION.DB/>.DBO.GETONLYDATE(O.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=202)OR(@TIPO=205)OR(@TIPO=208)
BEGIN
	SELECT O.IDOPORTUNIDAD, F.FASE,(P.NOMBRE+' '+P.APELLIDOS) AS NOMBRE_PROSPECTO, P.EMPRESA, P.CORREO, P.TELEFONO, P.TELEFONO2, P.MOVIL, O.CONCEPTO, U.INICIALES, 
	(SELECT ORIGEN FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,
	LP.LINEA_PRODUCTO, O.MONTO, O.COMISION, O.CERTEZA, O.FECHA_CIERRE,(CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO
	FROM <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.PROSPECTOS P,<#SESSION.DB/>.DBO.OPORTUNIDADES O
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP ON O.IDLINEA_PRODUCTO=LP.IDLINEA_PRODUCTO
	LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S ON O.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
	LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F ON O.IDFASE=F.IDFASE
	WHERE O.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND U.IDUSUARIO=@IDUSUARIO AND P.IDPROSPECTO=O.IDPROSPECTO
	AND <#SESSION.DB/>.DBO.GETONLYDATE(O.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=300)OR(@TIPO=303)OR(@TIPO=306)OR(@TIPO=403)OR(@TIPO=512)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*,  V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=301)OR(@TIPO=304)OR(@TIPO=307)OR(@TIPO=404)OR(@TIPO=511)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=302)OR(@TIPO=305)OR(@TIPO=308)OR(@TIPO=405)OR(@TIPO=510)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=513)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION, VC.COMISION AS COMISION_COBRADA,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, <#SESSION.DB/>.DBO.VENTAS_COBROS VC 
	 WHERE V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1 AND V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=514)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION, VC.COMISION AS COMISION_COBRADA,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, <#SESSION.DB/>.DBO.VENTAS_COBROS VC 
	 WHERE V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1 AND V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=515)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION, VC.COMISION AS COMISION_COBRADA,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, <#SESSION.DB/>.DBO.VENTAS_COBROS VC 
	 WHERE V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1 AND V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=400)
BEGIN
	 SELECT P.NOMBRE, P.APELLIDOS, PO.ORIGEN, COUNT (DISTINCT V.IDVENTA) AS TRANSACCIONES, SUM (V.MONTO) AS MONTO_COMPRADO, 
     SUM (V.ANTICIPOS_MONTO) AS ANTICIPOS, SUM (V.SALDO_MONTO) AS SALDO,
	 (SELECT ISNULL (SUM (VC.MONTO),0) FROM <#SESSION.DB/>.DBO.VENTAS_COBROS VC, <#SESSION.DB/>.DBO.VENTAS V1, <#SESSION.DB/>.DBO.OPORTUNIDADES O1 WHERE VC.PAGADO=0 AND VC.FECHAHORA<GETDATE() AND VC.IDVENTA = V1.IDVENTA  AND V1.IDOPORTUNIDAD = O1.IDOPORTUNIDAD AND O1.IDPROSPECTO = P.IDPROSPECTO)AS SALDO_VENCIDO,
     U.INICIALES, P.IDPROSPECTO,  P.APELLIDOS,P.EMPRESA, V.IDUSUARIO, P.ESCLIENTE, P.ETIQUETAS_TXT AS ETIQUETAS
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  ON P.IDORIGEN = PO.IDORIGEN 
     LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O
     LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V ON  O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
     JOIN  <#SESSION.DB/>.DBO.USUARIOS U ON V.IDUSUARIO = U.IDUSUARIO ON P.IDPROSPECTO = O.IDPROSPECTO, <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA 
	 WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> AND P.DESCARTADO=0 AND P.ESCLIENTE=1 AND P.IDPROSPECTO = PA.IDPROSPECTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)
	 GROUP BY 
     P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.EMPRESA, V.IDUSUARIO, PO.ORIGEN, U.INICIALES, P.ETIQUETAS_TXT, P.ESCLIENTE

END
IF (@TIPO=401)
BEGIN
	 SELECT P.NOMBRE, P.APELLIDOS, PO.ORIGEN, COUNT (DISTINCT V.IDVENTA) AS TRANSACCIONES, SUM (V.MONTO) AS MONTO_COMPRADO, 
     SUM (V.ANTICIPOS_MONTO) AS ANTICIPOS, SUM (V.SALDO_MONTO) AS SALDO,
	 (SELECT ISNULL (SUM (VC.MONTO),0) FROM <#SESSION.DB/>.DBO.VENTAS_COBROS VC, <#SESSION.DB/>.DBO.VENTAS V1, <#SESSION.DB/>.DBO.OPORTUNIDADES O1 WHERE VC.PAGADO=0 AND VC.FECHAHORA<GETDATE() AND VC.IDVENTA = V1.IDVENTA  AND V1.IDOPORTUNIDAD = O1.IDOPORTUNIDAD AND O1.IDPROSPECTO = P.IDPROSPECTO)AS SALDO_VENCIDO,
     U.INICIALES, P.IDPROSPECTO,  P.APELLIDOS,P.EMPRESA, V.IDUSUARIO, P.ESCLIENTE, P.ETIQUETAS_TXT AS ETIQUETAS
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  ON P.IDORIGEN = PO.IDORIGEN 
     LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O
     LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V ON  O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
     JOIN  <#SESSION.DB/>.DBO.USUARIOS U ON V.IDUSUARIO = U.IDUSUARIO ON P.IDPROSPECTO = O.IDPROSPECTO
	 JOIN (SELECT MIN(V.FECHAHORA) AS FECHA_CLIENTE, P.IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK), <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK), <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK)
	 WHERE U.IDEMPRESA=<#SESSION.IDEMPRESA/> AND V.IDUSUARIO = U.IDUSUARIO AND U.IDGRUPO = @IDGRUPO AND P.DESCARTADO=0 AND P.ESCLIENTE=1 AND O.GANADA = 1 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD GROUP BY P.IDPROSPECTO) AS T 
	 ON V.FECHAHORA = T.FECHA_CLIENTE AND P.IDPROSPECTO = T.IDPROSPECTO
	 WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> AND V.IDUSUARIO = U.IDUSUARIO AND U.IDGRUPO = @IDGRUPO AND P.DESCARTADO=0 AND P.ESCLIENTE=1
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)
	 GROUP BY 
     P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.EMPRESA, V.IDUSUARIO, PO.ORIGEN, U.INICIALES, P.ETIQUETAS_TXT, P.ESCLIENTE

END
IF (@TIPO=402)
BEGIN
	 SELECT P.NOMBRE, P.APELLIDOS, PO.ORIGEN, COUNT (DISTINCT V.IDVENTA) AS TRANSACCIONES, SUM (V.MONTO) AS MONTO_COMPRADO, 
     SUM (V.ANTICIPOS_MONTO) AS ANTICIPOS, SUM (V.SALDO_MONTO) AS SALDO,
	 (SELECT ISNULL (SUM (VC.MONTO),0) FROM <#SESSION.DB/>.DBO.VENTAS_COBROS VC, <#SESSION.DB/>.DBO.VENTAS V1, <#SESSION.DB/>.DBO.OPORTUNIDADES O1 WHERE VC.PAGADO=0 AND VC.FECHAHORA<GETDATE() AND VC.IDVENTA = V1.IDVENTA  AND V1.IDOPORTUNIDAD = O1.IDOPORTUNIDAD AND O1.IDPROSPECTO = P.IDPROSPECTO)AS SALDO_VENCIDO,
     U.INICIALES, P.IDPROSPECTO,  P.APELLIDOS,P.EMPRESA, V.IDUSUARIO, P.ESCLIENTE, P.ETIQUETAS_TXT AS ETIQUETAS
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  ON P.IDORIGEN = PO.IDORIGEN 
     LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O
     LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V ON  O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
     JOIN  <#SESSION.DB/>.DBO.USUARIOS U ON V.IDUSUARIO = U.IDUSUARIO ON P.IDPROSPECTO = O.IDPROSPECTO
	 JOIN (SELECT MIN(V.FECHAHORA) AS FECHA_CLIENTE, P.IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK), <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK), <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK), <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK)
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDUSUARIO=@IDUSUARIO AND P.DESCARTADO=0 AND P.ESCLIENTE=1 AND O.GANADA = 1 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD GROUP BY P.IDPROSPECTO) AS T
	 ON V.FECHAHORA = T.FECHA_CLIENTE AND P.IDPROSPECTO = T.IDPROSPECTO
	 WHERE V.IDUSUARIO=@IDUSUARIO AND P.DESCARTADO=0 AND P.ESCLIENTE=1 
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)
	 GROUP BY 
     P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.EMPRESA, V.IDUSUARIO, PO.ORIGEN, U.INICIALES, P.ETIQUETAS_TXT, P.ESCLIENTE

END
IF (@TIPO=500)OR(@TIPO=503)OR(@TIPO=506)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, VC.MONTO AS ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,VC.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*,  V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP,<#SESSION.DB/>.DBO.VENTAS_COBROS VC
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD AND V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=501)OR(@TIPO=504)OR(@TIPO=507)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, VC.MONTO AS ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,VC.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP,<#SESSION.DB/>.DBO.VENTAS_COBROS VC
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD  AND V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=502)OR(@TIPO=505)OR(@TIPO=508)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, VC.MONTO AS ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,VC.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP,<#SESSION.DB/>.DBO.VENTAS_COBROS VC
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD AND V.IDVENTA = VC.IDVENTA AND VC.PAGADO = 1
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(VC.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=309)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO AND P.IDPROSPECTO = @IDPROSPECTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=310)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO AND P.IDPROSPECTO = @IDPROSPECTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=311)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND P.IDPROSPECTO = @IDPROSPECTO
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=312)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO = @IDUSUARIO AND O.IDLINEA_PRODUCTO = @IDLINEA
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=313)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO = @IDGRUPO AND O.IDLINEA_PRODUCTO = @IDLINEA
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=314)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND O.IDLINEA_PRODUCTO = @IDLINEA
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=315)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*,  V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND V.NUEVA = 1
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=316)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO AND V.NUEVA = 1
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=317)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO AND V.NUEVA = 1
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END


IF (@TIPO=318)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*,  V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND V.NUEVA = 0
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=319)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA,  U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDGRUPO=@IDGRUPO AND V.NUEVA = 0
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END
IF (@TIPO=320)
BEGIN
	 SELECT  P.NOMBRE, CONCEPTO, V.FECHAHORA, V.ANTICIPOS_MONTO, V.ANTICIPOS_COMISION,O.CONCEPTO,V.FECHAHORA AS PAGADA_FECHA,
	 CASE WHEN ISNULL(ANTICIPOS_MONTO, 0) != 0 THEN ANTICIPOS_COMISION/ANTICIPOS_MONTO ELSE 0 END, SALDO_MONTO,V.MONTO, 
	 GANADA_FECHA, INICIALES, V.*, V.FECHAHORA AS PAGADA_FECHA_FECHAHORA,O.GANADA_FECHA AS GANADA_FECHA_FECHAHORA,
	 P.ETIQUETAS_TXT AS ETIQUETAS, P.IDPROSPECTO,P.NOMBRE, P.APELLIDOS,P.EMPRESA, U.INICIALES, U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 F.FASE, F.ORDEN, ISNULL(ABS (CAST (O.GANADA_FECHA-O.FECHAHORA AS INT)),0) as TIEMPO_TRANSCURRIDO, 
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, LP.LINEA_PRODUCTO 
	 FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F, 
	 <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
	 WHERE V.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/> AND V.IDOPORTUNIDAD=O.IDOPORTUNIDAD 
	 AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDFASE = F.IDFASE AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND U.IDUSUARIO=@IDUSUARIO AND V.NUEVA = 0
	 AND <#SESSION.DB/>.DBO.GETONLYDATE(V.FECHAHORA) BETWEEN CONVERT(DATETIME,@INICIO,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FIN,<#SESSION.CONVERTCODE/>)

END