//[idmetas|Text,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDMETAS VARCHAR(MAX)

SET @IDMETAS =ISNULL(:IDMETAS,'')

SELECT  TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.*, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, 
<#SESSION.DB/>.DBO.FECHA_STR(UM.FIN) AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS, DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS,(CASE WHEN DBO.GETONLYDATE(UM.FIN)= DBO.GETONLYDATE(GETDATE()) THEN 1 ELSE 0 END) AS ES_HOY
FROM SALESUP_CT.DBO.TIPOS_METAS AS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM
JOIN SALESUP_CT.DBO.SPLIT(@IDMETAS,',') ME ON UM.IDMETA=ME.SPLITVALUE
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO 
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO 
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO 
WHERE UM.IDUSUARIO_ASIGNO=US.IDUSUARIO AND TM.IDCOMPONENTE=UM.IDCOMPONENTE 
   
