//[term|Text,session.db|Untyped,session.idempresa|Untyped,condicion|Text,]
--SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @CRIT = ISNULL( :CONDICION , '')

SET @SQL = '

  DECLARE @CLIENTES VARCHAR(MAX)
  DECLARE @TERM VARCHAR(MAX)

  SET @CLIENTES = ''''
  SET @TERM =  ''' +  :TERM + '''

  SELECT @CLIENTES = @CLIENTES + '',''+''{"value":"''+ISNULL(P.NOMBRE,'''')+'' ''+ISNULL(P.APELLIDOS,'''')+''","id":"''+CAST(P.IDPROSPECTO AS VARCHAR)+''"}'' 
  FROM  <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = P.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A ON A.IDPROSPECTO = P.IDPROSPECTO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> AND DESCARTADO = 0 AND ESCLIENTE = 1 
  AND (ISNULL(P.NOMBRE,'''') + '' '' + ISNULL(P.APELLIDOS,'''') LIKE ''%''+@TERM+''%'')
   ' + @CRIT + '
  SELECT SUBSTRING(@CLIENTES, 2,LEN(@CLIENTES)) AS CLIENTES
 '
  
EXEC (@SQL)  