//[listap|Text,session.db|Untyped,]
--UPDATE

DECLARE @IDMETA INT
DECLARE @LISTAP VARCHAR(MAX)  
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDMETA INT)
DECLARE @TO INT, @TOTAL INT
SET @LISTAP=ISNULL(:LISTAP,'')
SET @TO = 1

INSERT INTO @TABLATEMP (IDMETA)
SELECT IDMETA FROM <#SESSION.DB/>.dbo.USUARIOS_METAS WITH(NOLOCK) WHERE TKMTA IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@LISTAP,',')) AND (IDMETA >0)

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDMETA = IDMETA FROM @TABLATEMP WHERE ID = @TO
	UPDATE <#SESSION.DB/>.dbo.USUARIOS_METAS WITH(ROWLOCK) SET STATUS=0 WHERE IDMETA=@IDMETA  
	SET @TO = @TO + 1
END