//[fecha_desde|Text,session.convertcode|Untyped,fecha_hasta|Text,session.idempresa|Untyped,status_meta|Text,periodo_seleccionado|Text,session.db|Untyped,]

DECLARE @IDEMPRESA INT
DECLARE @STATUS_META INT
DECLARE @CONDICION VARCHAR(MAX)
DECLARE @PERIODO_SELECCIONADO VARCHAR(MAX)
DECLARE @EXECSQL VARCHAR (MAX)
DECLARE @FECHA_DESDE DATETIME
DECLARE @FECHA_HASTA DATETIME

SELECT @FECHA_DESDE = CONVERT(DATETIME,ISNULL(:FECHA_DESDE,''),<#SESSION.CONVERTCODE/>)
SELECT @FECHA_HASTA = CONVERT(DATETIME,ISNULL(:FECHA_HASTA,''),<#SESSION.CONVERTCODE/>)

SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'
SET @STATUS_META= ISNULL( :STATUS_META , '')
SET @CONDICION = ''
SET @PERIODO_SELECCIONADO = ISNULL(:PERIODO_SELECCIONADO , '')

IF(@PERIODO_SELECCIONADO = '6')
BEGIN
SET @CONDICION = ' AND DBO.GETONLYDATE(FIN) BETWEEN CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_DESDE, <#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_HASTA,<#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) '
END
ELSE 
BEGIN
   SET @CONDICION = (SELECT SALESUP_CT.dbo.CALCULOFECHA(@PERIODO_SELECCIONADO))+' '
END


 SET @EXECSQL = 'SELECT  UG.GRUPO,  UG.IDUSUARIOGRUPO ' 
 SET @EXECSQL = @EXECSQL + 'FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG, <#SESSION.DB/>.DBO.USUARIOS_METAS US '
 SET @EXECSQL = @EXECSQL + 'WHERE UG.IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(5))+' AND US.IDGRUPO=UG.IDUSUARIOGRUPO AND US.STATUS='+CAST(@STATUS_META AS VARCHAR(5))+' '+@CONDICION
 SET @EXECSQL = @EXECSQL + 'group by  UG.GRUPO,  UG.IDUSUARIOGRUPO' 

EXEC(@EXECSQL)
