//[crituser|Text,crituser2|Text,crituser3|Text,periodo_seleccionado|Integer,session.db|Untyped,session.convertcode|Untyped,fecha_desde|Text,fecha_hasta|Text,porcomponente|Text,activas|Integer,session.nivel|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,]
--SELECT
/*protegido*/

DECLARE @ACTIVAS INT
DECLARE @PERIODO_SELECCIONADO INT
DECLARE @EJECUTIVOS VARCHAR(2024)
DECLARE @FECHA_DESDE DATETIME
DECLARE @FECHA_HASTA DATETIME
DECLARE @CONDICION VARCHAR(MAX)
DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @PORCOMPONENTE VARCHAR(MAX)
DECLARE @CONDICIONPORCOMPONENTE VARCHAR(MAX)
DECLARE @CONVERTCODE INT
DECLARE @SESSION_NIVEL INT
DECLARE @SESSION_DB VARCHAR(1024)
DECLARE @CRITUSER VARCHAR(1024)
DECLARE @CRITUSER2 VARCHAR(1024)
DECLARE @CRITUSER3 VARCHAR(1024)
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @IDGRUPO INT

SET @CRITUSER = ISNULL(:CRITUSER, '')
SET @CRITUSER2 = ISNULL(:CRITUSER2, '')
SET @CRITUSER3 = ISNULL(:CRITUSER3, '')
SET @PERIODO_SELECCIONADO = ISNULL(:PERIODO_SELECCIONADO, 0)
SET @SESSION_DB = '<#SESSION.DB/>' 
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SELECT @FECHA_DESDE = CONVERT(DATETIME,ISNULL(:FECHA_DESDE,''),@CONVERTCODE)
SELECT @FECHA_HASTA = CONVERT(DATETIME,ISNULL(:FECHA_HASTA,''),@CONVERTCODE)
SET @PORCOMPONENTE= ISNULL (:PORCOMPONENTE,'')
SET @ACTIVAS = ISNULL(:ACTIVAS, 0)
SET @SESSION_NIVEL = <#SESSION.NIVEL/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDGRUPO =ISNULL( '<#SESSION.IDGRUPO/>', 0 )

exec  <#SESSION.DB/>.[dbo].[SP_METAS] 0,'1', @ACTIVAS, @PERIODO_SELECCIONADO,  @FECHA_DESDE,  @FECHA_HASTA, @PORCOMPONENTE , @CONVERTCODE, @SESSION_NIVEL, @SESSION_DB, @CRITUSER, @CRITUSER2, @CRITUSER3, @IDEMPRESA, @IDUSUARIO, @IDGRUPO, '' 
