//[session.idempresa|Untyped,]
SELECT DISTINCT(ANIO) FROM EMPRESAS_METAS WHERE IDEMPRESA=<#SESSION.IDEMPRESA/>
UNION
SELECT YEAR (GETDATE())-1
UNION
SELECT YEAR (GETDATE())
UNION
SELECT YEAR (GETDATE())+1
