//[tipoconsulta|Text,session.idusuario|Untyped,session.idgrupo|Untyped,periodo_seleccionado|Text,session.db|Untyped,activas|Text,session.nivel|Untyped,session.idempresa|Untyped,]
--SELECT

DECLARE @ACTIVAS INT
DECLARE @EJECUTIVOS VARCHAR(2024)
DECLARE @NIVEL INT
DECLARE @CONDICION VARCHAR(MAX)
DECLARE @CONDICIONTIPO VARCHAR(MAX)
DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @TIPOCONSULTA INT
DECLARE @PERIODO_SELECCIONADO VARCHAR(1000)

SET @CONDICION = ''
SET @TIPOCONSULTA= CAST(ISNULL(:TIPOCONSULTA,'') AS INT)
SET @PERIODO_SELECCIONADO=ISNULL(:PERIODO_SELECCIONADO,'')
--tipo consulta SOLO USUARIO DE LA SESSION 1-individual, 2-grupal, 3-empresarial


IF(@TIPOCONSULTA = 1)
BEGIN
	 SET @CONDICIONTIPO = ' AND <#SESSION.IDUSUARIO>= UM.IDUSUARIO '
END
ELSE IF(@TIPOCONSULTA = 2)
BEGIN
	 SET @CONDICIONTIPO = ' AND <#SESSION.IDGRUPO>=UM.IDGRUPO AND <#SESSION.IDUSUARIO>= US.IDUSUARIO '
END
ELSE IF(@TIPOCONSULTA = 3)
BEGIN
	 SET @CONDICIONTIPO = ' AND (UM.IDGRUPO IS NULL) AND (UM.IDUSUARIO IS NULL) '
END


IF(@PERIODO_SELECCIONADO = '0')
BEGIN
	 SET @CONDICION = ' AND (MONTH(FIN) = MONTH(GETDATE()) AND YEAR(FIN) = YEAR(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '1')
BEGIN
	 SET @CONDICION = ' AND (DATEPART(q,FIN) = DATEPART(q,GETDATE()) AND YEAR(FIN) = YEAR(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '2')
BEGIN
	 SET @CONDICION = ' AND ((CASE WHEN (floor (((DATEPART(mm,FIN)) - 1) / 6) + 1) = 1 THEN 1 ELSE 2 END) = (CASE WHEN (floor (((DATEPART(mm,GETDATE())) - 1) / 6) + 1) = 1 THEN 1 ELSE 2 END) AND YEAR(FIN) = YEAR(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '3')
BEGIN
	 SET @CONDICION = ' AND (YEAR(FIN) = YEAR(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '4')
BEGIN
	 SET @CONDICION = ' AND (YEAR(FIN) < YEAR(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '5')
BEGIN
	 SET @CONDICION = ' AND (<#SESSION.DB/>.DBO.GETONLYDATE(FIN) > <#SESSION.DB/>.DBO.GETONLYDATE(GETDATE())) '
END
ELSE IF(@PERIODO_SELECCIONADO = '6')
BEGIN
	 SET @CONDICION = '  AND (DBO.GETONLYDATE(FIN) = DBO.GETONLYDATE(GETDATE()))   '
END
ELSE IF(@PERIODO_SELECCIONADO = '7')
BEGIN
	 SET @CONDICION = '  AND DBO.GETONLYDATE(FIN) BETWEEN (select SALESUP_CT.dbo.RangoFecha(0,3,NULL)) AND (select SALESUP_CT.dbo.RangoFecha(1,3,NULL))   '
END




--Fin nuevos filtros
 
IF (ISNULL(:ACTIVAS,'')='')
   SET @ACTIVAS=1
ELSE
  SET @ACTIVAS=CAST(ISNULL(:ACTIVAS,'') AS INT)

IF (<#SESSION.NIVEL/>=3)
BEGIN
   SET @EXECSQL = 'SELECT  TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.IDMETA,UM.IDUSUARIO_ASIGNO,UM.IDUSUARIO,UM.IDGRUPO,UM.IDEMPRESA,UM.INICIO,UM.FIN,UM.TIPO,REPLACE(UM.DESCRIPCION,''"'','''') AS DESCRIPCION,UM.META,UM.AVANCE,UM.PCT,UM.ORDEN,UM.FORMATO,UM.STATUS,UM.NOTIFICA,UM.IDPROSPECTO,UM.IDLINEA,UM.TKMTA,UM.TKMTAM,UM.CAMBIOLOCAL,UM.IDEMPRESADIST,UM.CANALIZADOEL,UM.ULTIMAMODIFICACION,UM.IDCOMPONENTE,UM.USRCANALIZO, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, '    
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN)AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS, DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS, (CASE WHEN DBO.GETONLYDATE(UM.FIN)= DBO.GETONLYDATE(GETDATE()) THEN 1 ELSE 0 END) AS ES_HOY' 
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE TM.IDCOMPONENTE=UM.IDCOMPONENTE AND (UM.IDUSUARIO=<#SESSION.IDUSUARIO/> OR UM.IDGRUPO=<#SESSION.IDGRUPO/> OR UM.IDEMPRESA=<#SESSION.IDEMPRESA/>)'
   SET @EXECSQL = @EXECSQL + @CONDICION+ ' AND ((<#SESSION.IDUSUARIO/> = UM.IDUSUARIO) OR (<#SESSION.IDGRUPO>=UM.IDGRUPO OR <#SESSION.IDUSUARIO>= US.IDUSUARIO) OR ((UM.IDGRUPO IS NULL) AND (UM.IDUSUARIO IS NULL))) '
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5))
   EXEC(@EXECSQL)
END
ELSE IF (<#SESSION.NIVEL/>=2)
BEGIN   
   SET @EXECSQL = 'SELECT TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.IDMETA,UM.IDUSUARIO_ASIGNO,UM.IDUSUARIO,UM.IDGRUPO,UM.IDEMPRESA,UM.INICIO,UM.FIN,UM.TIPO,REPLACE(UM.DESCRIPCION,''"'','''') AS DESCRIPCION,UM.META,UM.AVANCE,UM.PCT,UM.ORDEN,UM.FORMATO,UM.STATUS,UM.NOTIFICA,UM.IDPROSPECTO,UM.IDLINEA,UM.TKMTA,UM.TKMTAM,UM.CAMBIOLOCAL,UM.IDEMPRESADIST,UM.CANALIZADOEL,UM.ULTIMAMODIFICACION,UM.IDCOMPONENTE,UM.USRCANALIZO, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, '
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN)AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS,DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS , (CASE WHEN DBO.GETONLYDATE(UM.FIN)= DBO.GETONLYDATE(GETDATE()) THEN 1 ELSE 0 END) AS ES_HOY'
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE TM.IDCOMPONENTE=UM.IDCOMPONENTE AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> '
   SET @EXECSQL = @EXECSQL + @CONDICION+ ' AND ((<#SESSION.IDUSUARIO/> = UM.IDUSUARIO) OR (<#SESSION.IDGRUPO>=UM.IDGRUPO OR <#SESSION.IDUSUARIO>= US.IDUSUARIO) OR ((UM.IDGRUPO IS NULL) AND (UM.IDUSUARIO IS NULL))) '
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5))
   EXEC(@EXECSQL)
END 
ELSE IF (<#SESSION.NIVEL/>=1)
BEGIN
   SET @EXECSQL = 'SELECT  TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.IDMETA,UM.IDUSUARIO_ASIGNO,UM.IDUSUARIO,UM.IDGRUPO,UM.IDEMPRESA,UM.INICIO,UM.FIN,UM.TIPO,REPLACE(UM.DESCRIPCION,''"'','''') AS DESCRIPCION,UM.META,UM.AVANCE,UM.PCT,UM.ORDEN,UM.FORMATO,UM.STATUS,UM.NOTIFICA,UM.IDPROSPECTO,UM.IDLINEA,UM.TKMTA,UM.TKMTAM,UM.CAMBIOLOCAL,UM.IDEMPRESADIST,UM.CANALIZADOEL,UM.ULTIMAMODIFICACION,UM.IDCOMPONENTE,UM.USRCANALIZO, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, ' 
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN) AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS, DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS, (CASE WHEN DBO.GETONLYDATE(UM.FIN)= DBO.GETONLYDATE(GETDATE()) THEN 1 ELSE 0 END) AS ES_HOY' 
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE UM.IDUSUARIO_ASIGNO=US.IDUSUARIO AND TM.IDCOMPONENTE=UM.IDCOMPONENTE AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> '
   SET @EXECSQL = @EXECSQL + @CONDICION+ ' AND ((<#SESSION.IDUSUARIO/> = UM.IDUSUARIO) OR (<#SESSION.IDGRUPO>=UM.IDGRUPO OR <#SESSION.IDUSUARIO>= US.IDUSUARIO) OR ((UM.IDGRUPO IS NULL) AND (UM.IDUSUARIO IS NULL))) '
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5))
   EXEC(@EXECSQL)
END 
