//[session.db|Untyped,listap|Text,]
--UPDATE

DECLARE @IDRECORDATORIO INT
DECLARE @LISTAP VARCHAR(MAX)
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDRECORDATORIO INT)
DECLARE @TO INT, @TOTAL INT

SET @LISTAP=ISNULL(:LISTAP,'')
SET @TO = 1

INSERT INTO @TABLATEMP (IDRECORDATORIO)
SELECT IDRECORDATORIO FROM <#SESSION.DB/>.DBO.RECORDATORIOS WHERE IDRECORDATORIO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@LISTAP,','))

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDRECORDATORIO = IDRECORDATORIO FROM @TABLATEMP WHERE ID = @TO
	UPDATE <#SESSION.DB/>.dbo.RECORDATORIOS SET COMPLETADO = 1 WHERE IDRECORDATORIO=@IDRECORDATORIO  
	SET @TO = @TO + 1
END
