//[fecha_desde|Text,session.convertcode|Untyped,fecha_hasta|Text,porcomponente|Text,periodo_seleccionado|Text,activas|Integer,session.nivel|Untyped,session.db|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.idempresa|Untyped,crituser|Text,crituser2|Text,crituser3|Text,ordenamiento|Text,]
--SELECT
DECLARE @CRITUSER VARCHAR(MAX)
DECLARE @CRITUSER2 VARCHAR(MAX)
DECLARE @CRITUSER3 VARCHAR(MAX)
DECLARE @EJECUTIVOS VARCHAR(2024)
DECLARE @NIVEL INT, @ACTIVAS INT
DECLARE @PORCOMPONENTE VARCHAR(MAX)
DECLARE @CONDICION VARCHAR(MAX)
DECLARE @CONDICIONPORMETA VARCHAR(MAX)
DECLARE @PERIODO_SELECCIONADO VARCHAR(12)
DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @FECHA_DESDE DATETIME
DECLARE @FECHA_HASTA DATETIME
DECLARE @ORDENAMIENTO VARCHAR(1000)

SELECT @FECHA_DESDE = CONVERT(DATETIME,ISNULL(:FECHA_DESDE,''),<#SESSION.CONVERTCODE/>)
SELECT @FECHA_HASTA = CONVERT(DATETIME,ISNULL(:FECHA_HASTA,''),<#SESSION.CONVERTCODE/>)

SET @PORCOMPONENTE = ISNULL(:PORCOMPONENTE,'')
SET @CONDICION = ''
SET @CONDICIONPORMETA = ''
SET @PERIODO_SELECCIONADO = ISNULL(:PERIODO_SELECCIONADO,'')
SET @ORDENAMIENTO  = ISNULL(:ORDENAMIENTO,'')
SET @CRITUSER = ISNULL(:CRITUSER,'')
SET @CRITUSER2 = ISNULL(:CRITUSER2,'')
SET @CRITUSER3 = ISNULL(:CRITUSER3,'')
--Nuevos filtros

IF (@PORCOMPONENTE='')
   SET @CONDICIONPORMETA=''
ELSE
   SET @CONDICIONPORMETA=' AND UM.IDCOMPONENTE='+@PORCOMPONENTE

IF(@PERIODO_SELECCIONADO = '6')
BEGIN
SET @CONDICION = ' AND DBO.GETONLYDATE(FIN) BETWEEN CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_DESDE, <#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+CONVERT(VARCHAR(64),@FECHA_HASTA,<#SESSION.CONVERTCODE/>)+''',<#SESSION.CONVERTCODE/>) '
END
ELSE 
BEGIN
   SET @CONDICION = (SELECT SALESUP_CT.dbo.CALCULOFECHA(@PERIODO_SELECCIONADO))+' '
END

--Fin nuevos filtros
SET @ACTIVAS = ISNULL(:ACTIVAS, 1)

IF (<#SESSION.NIVEL/>=3)
BEGIN
   SET @EXECSQL = 'SELECT TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.*, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, '    
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN)AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS TOTAL_DIAS, DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS' 
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE TM.IDCOMPONENTE=UM.IDCOMPONENTE AND (UM.IDUSUARIO=<#SESSION.IDUSUARIO/> OR UM.IDGRUPO=<#SESSION.IDGRUPO/>) AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> '
   SET @EXECSQL = @EXECSQL + @CONDICION+@CONDICIONPORMETA
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5)) + ' '+@CRITUSER +' '+@CRITUSER2 +' '+@CRITUSER3 
   SET @EXECSQL = @EXECSQL + ' ORDER BY '+@ORDENAMIENTO 
   EXEC(@EXECSQL)
END
ELSE IF (<#SESSION.NIVEL/>=2)
BEGIN   
   SET @EXECSQL = 'SELECT TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.*, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, '
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN)AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS,DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS '
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE TM.IDCOMPONENTE=UM.IDCOMPONENTE AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> '
   SET @EXECSQL = @EXECSQL + @CONDICION+@CONDICIONPORMETA
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5)) + ' '+@CRITUSER +' '+@CRITUSER2 +' '+@CRITUSER3 
   SET @EXECSQL = @EXECSQL + ' ORDER BY '+@ORDENAMIENTO 
   EXEC(@EXECSQL)
END 
ELSE IF (<#SESSION.NIVEL/>=1)
BEGIN
   SET @EXECSQL = 'SELECT TM.NOMBRE_COMPONENTE AS META_NOMBRE, UM.*, US.INICIALES AS ASIGNO, U.INICIALES AS RESPONSABLE, U.NOMBRE, U.APELLIDOS, U.IDGRUPO AS GRUPOS, UG.GRUPO AS GRUPO, ' 
   SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.FECHA_STR(UM.FIN) AS FECHA_FIN, <#SESSION.DB/>.DBO.FECHA_STR(UM.INICIO) AS FECHA_INIC,CONVERT(VARCHAR,UM.INICIO)AS FECHA_INICIO, DATEDIFF(DD,UM.INICIO, UM.FIN) AS NUMDIAS, DATEDIFF(DD,UM.INICIO, GETDATE()) AS DIAS_TRANS'
   SET @EXECSQL = @EXECSQL + ' FROM SALESUP_CT.DBO.TIPOS_METAS TM, <#SESSION.DB/>.DBO.USUARIOS_METAS UM '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US ON US.IDUSUARIO=UM.IDUSUARIO_ASIGNO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UM.IDUSUARIO '
   SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON UM.IDGRUPO=UG.IDUSUARIOGRUPO '
   SET @EXECSQL = @EXECSQL + ' WHERE UM.IDUSUARIO_ASIGNO=US.IDUSUARIO AND TM.IDCOMPONENTE=UM.IDCOMPONENTE AND UM.IDEMPRESA=<#SESSION.IDEMPRESA/> '
   SET @EXECSQL = @EXECSQL + @CONDICION+@CONDICIONPORMETA
   SET @EXECSQL = @EXECSQL + ' AND STATUS=' + CAST(@ACTIVAS AS VARCHAR(5)) + ' '+@CRITUSER +' '+@CRITUSER2 +' '+@CRITUSER3 
   SET @EXECSQL = @EXECSQL + ' ORDER BY '+@ORDENAMIENTO 
   EXEC(@EXECSQL)
END 

