//[session.idempresa|Untyped,idmeta|Integer,session.gmt|Untyped,session.db|Untyped,]
-- SELECT

DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @IDMETA INT,@GMT INT
DECLARE @SQLTXT VARCHAR(MAX)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDMETA = CAST(isnull(:IDMETA,0) AS INT)
SET @GMT = CAST('<#SESSION.GMT/>' AS INT )

EXEC <#SESSION.DB/>.DBO.SP_DETALLES_METAS @IDEMPRESA, @IDMETA,@GMT,1