//[crit|Text,elnivel|Text,ordenamiento|Text,session.db|Untyped,session.idempresa|Untyped,]
/*
PROTEGIDO
*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @ELNIVEL VARCHAR(MAX)
DECLARE @ORDENAMIENTO VARCHAR(MAX)
SET @CRIT=ISNULL(:CRIT,'')
SET @ELNIVEL=ISNULL(:ELNIVEL,'')
SET @ORDENAMIENTO=ISNULL(:ORDENAMIENTO,' 1 ASC')

SET @SQL='
SELECT COUNT (P.IDPROSPECTO) AS TOTALN , '''+REPLACE(@CRIT,'''','''''')+''' AS CRIT, '''+REPLACE(@ELNIVEL,'''','''''')+''' AS ELNIVEL, '''+REPLACE(@ORDENAMIENTO,'''','''''')+''' AS ORDENAMIENTO
FROM 
  <#SESSION.DB/>.DBO.USUARIOS U, 
  <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.PAISES PS   ON P.IDPAIS = PS.IDPAIS
  LEFT JOIN <#SESSION.DB/>.DBO.ESTADOS ES  ON ES.IDPAIS = P.IDPAIS AND ES.IDESTADO = P.IDESTADO
WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/>
  AND P.DESCARTADO=0 AND P.IDUSUARIO = U.IDUSUARIO '+@ELNIVEL+' 
'+@CRIT+'
  '
  
  EXEC(@SQL)
  
