//[session.db|Untyped,elnivel|Text,session.idempresa|Untyped,ordenamiento|Text,]
--select
DECLARE @SQL VARCHAR(MAX)
DECLARE @ELNIVEL VARCHAR(MAX)
SET @ELNIVEL = ISNULL( :ELNIVEL , '')
DECLARE @ORDENAMIENTO VARCHAR(MAX)
SET @ORDENAMIENTO = ISNULL( :ORDENAMIENTO , '')

SET @SQL = '
 SELECT E.TK, E.TKM,
 E.IDETIQUETA, E.ETIQUETA, COUNT (PA.IDPROSPECTO) AS TOTAL,
 SUM ( CASE WHEN PA.ESCLIENTE=0 AND PA.ESOPORTUNIDAD=0 THEN 1 ELSE 0 END ) AS PROSPECTOS,
 SUM ( CASE WHEN PA.ESCLIENTE=0 AND PA.ESOPORTUNIDAD=1 THEN 1 ELSE 0 END ) AS OPORTUNIDADES,
 SUM ( CASE WHEN PA.ESCLIENTE=1 THEN 1 ELSE 0 END ) AS CLIENTES,
 (select count(*) from <#SESSION.DB/>.DBO.AUTORESPONDERS a where a.idetiqueta=E.IDETIQUETA) as totalauto
 FROM 
 <#SESSION.DB/>.DBO.ETIQUETAS E 
 left join <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS PE 
  join <#SESSION.DB/>.DBO.PROSPECTOS PA on PE.IDPROSPECTO = PA.IDPROSPECTO AND PA.DESCARTADO = 0 
  join <#SESSION.DB/>.DBO.usuarios u on Pa.IDUSUARIO = U.IDUSUARIO
 on PE.IDETIQUETA = E.IDETIQUETA AND E.IDEMPRESA = PA.IDEMPRESA '  + @ELNIVEL + '
 WHERE E.IDEMPRESA = <#SESSION.IDEMPRESA/>  
 GROUP BY E.IDETIQUETA, E.ETIQUETA, E.TK, E.TKM
 ORDER BY ' + @ORDENAMIENTO+ ' 
' 
EXEC (@SQL)