//[session.db|Untyped,session.idempresa|Untyped,elnivel|Text,crit|Text,ordenamiento|Text,]
--SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @ELNIVEL VARCHAR(MAX)
DECLARE @ORDENAMIENTO VARCHAR(MAX)
SET @ORDENAMIENTO=ISNULL(:ORDENAMIENTO,' 1 ASC')
SET @CRIT=ISNULL(:CRIT,'')
SET @ELNIVEL=ISNULL(:ELNIVEL,'')


SET @SQL='

SELECT p.tkp, P.NOMBRE, P.CORREO, P.DIRECCION1, P.DESCARTADO, (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN, <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,
  P.ULTIMA_ACTUALIZACION, P.IDPROSPECTO,P.APELLIDOS, P.EMPRESA, P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO,
  P.DIRECCION1, P.DIRECCION2, P.CIUDAD, P.CODIGOPOSTAL, P.ESCLIENTE, P.ESOPORTUNIDAD, ULTIMA_ACTUALIZACION,
    <#SESSION.DB/>.DBO.FECHA_STR(P.ULTIMA_ACTUALIZACION) AS ULTIMAACTUALIZACION, U.INICIALES,  U.NOMBRE+'' ''+U.APELLIDOS AS EJECUTIVO_NOMBRE,
    ''.''+LTRIM(ISNULL(TELEFONO, '''')) AS TELEFONO_E, ''.''+LTRIM(ISNULL(TELEFONO2, '''')) AS TELEFONO2_E, ''.''+LTRIM(ISNULL(MOVIL, '''')) AS MOVIL_E, ''.''+LTRIM(ISNULL(CORREO, '''')) AS CORREO_E,
    PS.PAIS, ES.ESTADO,
    P.ETIQUETAS_TXT AS ETIQUETAS, (CASE WHEN (P.ESOPORTUNIDAD=0 AND P.ESCLIENTE=0) THEN 1 ELSE (CASE WHEN (P.ESOPORTUNIDAD=1 AND P.ESCLIENTE=0) THEN 2 ELSE 3 END) END) AS TIPO
FROM 
--<#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK),
<#SESSION.DB/>.DBO.USUARIOS U, 
<#SESSION.DB/>.DBO.PROSPECTOS P
LEFT JOIN <#SESSION.DB/>.DBO.PAISES PS 
  ON P.IDPAIS = PS.IDPAIS
  LEFT JOIN <#SESSION.DB/>.DBO.ESTADOS ES
  ON ES.IDPAIS = P.IDPAIS AND ES.IDESTADO = P.IDESTADO
   
WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> 
--AND A.IDPROSPECTO = P.IDPROSPECTO 
AND P.DESCARTADO=0 AND P.IDUSUARIO = U.IDUSUARIO '+@ELNIVEL+'
  '+@CRIT+'
  
ORDER BY '+@ORDENAMIENTO+'
'
EXEC (@SQL)