//[idetiqueta|Integer,tk|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,otrocritseg|Text,tiposegmento|Text,]
--INSERT
DECLARE @TK VARCHAR(128)
DECLARE @IDETIQUETA INT
DECLARE @TEXTO VARCHAR (1024)
DECLARE @tiposegmento VARCHAR(1000)
DECLARE @OTROCRITSEG VARCHAR(1000)

SET @OTROCRITSEG = ISNULL(:OTROCRITSEG,'')
SET @tiposegmento = ISNULL(:tiposegmento,'')
SET @IDETIQUETA = ISNULL(:IDETIQUETA, 0)

SET @TK = ISNULL(:TK,'')
IF @TK != '' BEGIN SELECT @IDETIQUETA=IDETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE TK = @TK AND IDEMPRESA = <#SESSION.IDEMPRESA/> END


DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO> AND IDPANTALLA=5

SELECT @TEXTO=ETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE IDETIQUETA = @IDETIQUETA

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
VALUES (<#SESSION.IDUSUARIO/>,5,20,@TEXTO,'P.IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS WHERE IDETIQUETA='+CAST(@IDETIQUETA AS VARCHAR(128))+') '+@OTROCRITSEG)

IF @tiposegmento='1' 
  BEGIN
  	   INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
	   VALUES (<#SESSION.IDUSUARIO/>,5,100,'Prospectos','P.ESOPORTUNIDAD=0 AND P.ESCLIENTE=0')
  END

IF @tiposegmento='2' 
  BEGIN
  	   INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
	   VALUES (<#SESSION.IDUSUARIO/>,5,100,'Oportunidades','P.ESOPORTUNIDAD=1 AND P.ESCLIENTE=0')
  END

IF @tiposegmento='3' 
  BEGIN
  	   INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT)
	   VALUES (<#SESSION.IDUSUARIO/>,5,100,'Clientes','P.ESCLIENTE=1')  
  END

