//[session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,idemail|Text,asunto|Text,contenido|Text,totalprospectos|Text,limite|Text,copiaoculta|Text,concopia|Text,idplantilla|Text,idprospecto|Text,plantillas|Text,ruta_doc|Text,idoportunidad|Text,programarcorreo|Text,pcfecha|Text,pchora|Text,session.db|Untyped,ltarchivosagregados|Text,ltarchivosagregadosprospecto|Text,enviarestearchivo|Text,estado|Text,]
--INSERT
DECLARE @IDULTIMO INT , @CORREOSENVIADOS INT, @IDPLANTILLA INT , @LIMITE INT , @TOTALPROSPECTOS INT
DECLARE @COMENTARIO VARCHAR(MAX), @RUTA_DOC VARCHAR(MAX),@ADJUNTOS VARCHAR(MAX), @ADJANEXOS VARCHAR(MAX), @FechaProgramada varchar(32)
DECLARE @IDOPORTUNIDAD VARCHAR(MAX), @CC VARCHAR(MAX), @CCO VARCHAR(MAX), @ASUNTO  VARCHAR(MAX), @CONTENIDO VARCHAR(MAX) , @PROSPECTOS VARCHAR(MAX) 
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @ProgramarCorreo INT, @CONVERTCODE INT, @IDEMAIL INT
DECLARE @dt_FechaProgramada datetime
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME

SET @IDEMPRESA = '<#SESSION.IDEMPRESA/>'
SET @IDUSUARIO = '<#SESSION.IDUSUARIO/>'
SET @CONVERTCODE = '<#SESSION.CONVERTCODE/>'

SET @IDEMAIL = CAST(ISNULL(:IDEMAIL,'') AS INT)
SET @ASUNTO = :ASUNTO
SET @CONTENIDO =  :CONTENIDO
SET @TOTALPROSPECTOS = CAST(ISNULL(:TOTALPROSPECTOS,'') AS INT)
SET @LIMITE = CAST(ISNULL(:LIMITE,'') AS INT)
SET @CCO = ISNULL(:COPIAOCULTA,'')
SET @CC = ISNULL(:CONCOPIA,'')
SET @IDPLANTILLA = CAST(ISNULL(:idplantilla,'') AS INT)
SET @PROSPECTOS = ISNULL(:IDPROSPECTO,'')
SET @IDPLANTILLA = CAST(ISNULL(:PLANTILLAS,'') AS INT)
SET @ADJUNTOS = ISNULL(:RUTA_DOC,'') 
SET @RUTA_DOC = ''
SET @IDOPORTUNIDAD = LTRIM(RTRIM(ISNULL(:IDOPORTUNIDAD,'')))
SET @ProgramarCorreo = CAST(ISNULL(:ProgramarCorreo,'') AS INT)
SET @FechaProgramada = ISNULL(:pcfecha,'')+' '+ISNULL(:pchora,'')

SET @FECHAHOY = GETDATE()
SET @P = ''
SET @P = CAST(@PROSPECTOS AS VARCHAR(MAX))

SELECT @ADJANEXOS = CAST(ANEXOS AS VARCHAR(8000)) FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA

IF @ProgramarCorreo = 1 BEGIN SET @dt_FechaProgramada = CONVERT(DATETIME, @FechaProgramada, @CONVERTCODE) END

IF (@ADJUNTOS='') BEGIN SET @RUTA_DOC='' END ELSE BEGIN SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/') END
 
IF (RTRIM(LTRIM(@ADJANEXOS))!='') BEGIN SET @RUTA_DOC = @RUTA_DOC + CHAR(10)+CHAR(13)+@ADJANEXOS END

IF(@IDOPORTUNIDAD = '0' OR @IDOPORTUNIDAD='') BEGIN SET @IDOPORTUNIDAD = NULL END

/*ARCHIVOS AGREGADOS DESDE MI NUBE*/
DECLARE @LtArchivosAgregados VARCHAR(MAX), @LtArchivosAgregadosDelProspecto VARCHAR(MAX)
DECLARE @ArchivosAgregados VARCHAR(MAX), @EnviarEsteArchivo VARCHAR(MAX), @ArchivosAgregadosDelProspecto VARCHAR(MAX)

SET @LtArchivosAgregados = ISNULL(:LtArchivosAgregados,'')
SET @LtArchivosAgregadosDelProspecto = ISNULL(:LtArchivosAgregadosProspecto,'')
SET @EnviarEsteArchivo = ISNULL(:EnviarEsteArchivo,'')
SET @ArchivosAgregados = ''
SET @ArchivosAgregadosDelProspecto = ''

/*ARCHIVOS DE LA NUBE*/
SELECT @ArchivosAgregados = @ArchivosAgregados + '/'+SPLITVALUE + CHAR(10) + CHAR(13) FROM <#SESSION.DB/>.dbo.Split(@LtArchivosAgregados,'|')
IF @ArchivosAgregados != '' BEGIN SET @RUTA_DOC = @ArchivosAgregados + @RUTA_DOC + CHAR(10)+CHAR(13) END

/*ARCHIVOS DEL PROSPECTO */
SELECT @ArchivosAgregadosDelProspecto = @ArchivosAgregadosDelProspecto + '/'+SPLITVALUE + CHAR(10) + CHAR(13) FROM <#SESSION.DB/>.dbo.Split(@LtArchivosAgregadosDelProspecto,'|')
IF @ArchivosAgregadosDelProspecto != '' BEGIN SET @RUTA_DOC = @ArchivosAgregadosDelProspecto + @RUTA_DOC + CHAR(10)+CHAR(13) END

/*UN SOLO ARCHIVO DEL PROSPECTO*/
IF @EnviarEsteArchivo != '' BEGIN SET @RUTA_DOC = '/'+@EnviarEsteArchivo + CHAR(10)+CHAR(13) + @RUTA_DOC  END
   
DECLARE @TABLA AS TABLE (ID INT IDENTITY, IDPROSPECTO INT, CORREO VARCHAR(1000), IDOPORTUNIDAD INT)
DECLARE @TOTAL INT, @CONT INT, @IDP INT, @IDOPOR INT, @ESTADO INT 
DECLARE @CORREOP VARCHAR(1000)
 
SET @TOTAL = 0
SET @CONT = 1
SET @IDP = 0
SET @IDOPOR = 0
SET @CORREOP = ''
SET @ESTADO = CAST(ISNULL(:ESTADO,'') AS INT)

IF (@IDOPORTUNIDAD IS NULL)
BEGIN
  INSERT INTO @TABLA (IDPROSPECTO, CORREO) SELECT IDPROSPECTO,CORREO 
  from <#SESSION.DB/>.DBO.PROSPECTOS 
  where IDPROSPECTO in (select splitvalue from <#SESSION.DB/>.DBO.Split(@PROSPECTOS,',')) and  correo is not null
END
ELSE
BEGIN
  INSERT INTO @TABLA (IDPROSPECTO, CORREO, IDOPORTUNIDAD)
  SELECT P.IDPROSPECTO, P.CORREO, O.IDOPORTUNIDAD from <#SESSION.DB/>.DBO.PROSPECTOS P ,<#SESSION.DB/>.DBO.OPORTUNIDADES O 
  WHERE P.IDPROSPECTO in (select splitvalue from <#SESSION.DB/>.DBO.Split(@PROSPECTOS,',')) AND O.IDPROSPECTO=P.IDPROSPECTO
  AND O.IDOPORTUNIDAD IN  (select splitvalue from <#SESSION.DB/>.DBO.Split(@IDOPORTUNIDAD,',')) 
END

SELECT @TOTAL=COUNT(*) FROM @TABLA
/*FECHALEIDO*/
WHILE @CONT<=@TOTAL
BEGIN
	SELECT @CORREOSENVIADOS = CORREOSENVIADOS 
	FROM <#SESSION.DB/>.DBO.USUARIOS WITH(NOLOCK) 
	WHERE IDUSUARIO = @IDUSUARIO
	
	SELECT @IDP = IDPROSPECTO, @CORREOP = CORREO, @IDOPOR = CAST(IDOPORTUNIDAD AS INT) 
	FROM @TABLA WHERE ID = @CONT
	
	IF @IDPLANTILLA != 0 AND @TOTALPROSPECTOS > 1
    BEGIN
   	  SELECT 
      @CONTENIDO = <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(CUERPO, @IDP, @IDUSUARIO, @IDEMPRESA, @IDOPOR),
      @ASUNTO = <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(ASUNTO, @IDP, @IDUSUARIO, @IDEMPRESA, @IDOPOR)
	  FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
	  WHERE IDPLANTILLA = @IDPLANTILLA
    END 
    
	SET @RUTA_DOC = REPLACE (@RUTA_DOC,'\r \n',CHAR(13)+CHAR(10))
	
	UPDATE <#SESSION.DB/>.DBO.USUARIOS_EMAILS WITH(ROWLOCK)
	SET 
	ASUNTO = @ASUNTO, CUERPO = @CONTENIDO,
	CC = @CC, BCC = @CCO,
	ANEXOS = CAST(ANEXOS AS VARCHAR(MAX)) + @RUTA_DOC, FECHAPROGRAMADA = @dt_FechaProgramada
	WHERE IDEMAIL = @IDEMAIL
    
	SET @CONT = @CONT + 1
END
EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1 



