//[session.idusuario|Untyped,f|Integer,aux|Text,session.db|Untyped,]
--delete
DECLARE @IDUSUARIO INT, @FILTRO INT
DECLARE @AUX VARCHAR(10)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @FILTRO = CAST(ISNULL(:F,0) AS INT)
SET @AUX = ISNULL(:AUX,'')
DELETE FROM <#SESSION.DB/>.dbo.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND TIPO = @FILTRO AND SQLTXT_EXP = @AUX AND IDPANTALLA IN (410,411,412,414,415) 