//[session.db|Untyped,idemail|Integer,]
SELECT REPLACE( REPLACE(CAST(UE.CUERPO AS VARCHAR(8000)),'autoresponder-leido.asp', 'estilos/vacio.png'),'correo-leido.asp', 'estilos/vacio.png' ) AS CUERPOSIN,
 UE.*, U.EMAIL, U.NOMBRE AS NOMUSUARIO, U.APELLIDOS AS APEUSUARIO, P.NOMBRE, P.APELLIDOS 
FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UE.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON UE.IDUSUARIO = U.IDUSUARIO
WHERE UE.IDEMAIL = ISNULL(:IDEMAIL,0)
