//[estado|Text,idautoresponder|Integer,session.db|Untyped,tkauto|Text,session.idempresa|Untyped,]
--update
/*PROTEGIDO*/
/*SEP2015*/

DECLARE @TKAUTO VARCHAR(128)
DECLARE @IDAUTORESPONDER INT
DECLARE @ESTADO VARCHAR(1000)

SET @ESTADO =  :ESTADO
SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER, 0 )


SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END


IF (@ESTADO IS NOT NULL)
   UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS SET ESTADO = @ESTADO WHERE IDAUTORESPONDER = @IDAUTORESPONDER