//[idplantilla|Integer,archivo|Text,session.db|Untyped,archivoreal|Text,session.idempresa|Untyped,]
--INSERT
DECLARE @ANEXOS VARCHAR(8000)
DECLARE @ANEXOSNUEVO VARCHAR(8000)
DECLARE @ARCHIVONUEVO VARCHAR(8000)
DECLARE @NOMBRE_REALNUEVO VARCHAR(8000)
DECLARE @ARCHIVO VARCHAR(8000)
DECLARE @NOMBRE_REAL VARCHAR(8000)
DECLARE @IDPLANTILLA INT
DECLARE @RUTA VARCHAR(8000)
DECLARE @ARCHIVOBUSCAR VARCHAR(8000)
DECLARE @ARCHIVOREAL VARCHAR(5000)
DECLARE @HAYARCHIVO INT
SET @IDPLANTILLA = ISNULL(:IDPLANTILLA,0)
SET @ARCHIVOBUSCAR = ISNULL(:ARCHIVO,'')
SET @RUTA = '/'+@ARCHIVOBUSCAR
SET @ARCHIVOREAL=ISNULL(:ARCHIVOREAL,'')

SELECT @ANEXOS=ANEXOS , @ARCHIVO=NOMBRE_ARCHIVO , @NOMBRE_REAL = NOMBRE_ARCHIVO_REAL FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA 
SET @ANEXOSNUEVO = ''
SET @ARCHIVONUEVO = ''
SET @NOMBRE_REALNUEVO = ''
SET @ANEXOS = REPLACE (@ANEXOS, @RUTA ,@ANEXOSNUEVO)
SET @ARCHIVO = REPLACE (@ARCHIVO, ltrim(rtrim(@ARCHIVOBUSCAR+',')),@ARCHIVONUEVO)
SET @NOMBRE_REAL = REPLACE (@NOMBRE_REAL, ltrim(rtrim(@ARCHIVOREAL+',')),@NOMBRE_REALNUEVO)

SELECT @HAYARCHIVO=COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND ARCHIVO LIKE @ARCHIVOBUSCAR
  IF (@HAYARCHIVO>0)
   BEGIN
     DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE ARCHIVO LIKE @ARCHIVOBUSCAR AND IDEMPRESA=<#SESSION.IDEMPRESA/> AND TIPO='PA'
   END  

UPDATE 
<#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
SET 
ANEXOS = @ANEXOS, 
NOMBRE_ARCHIVO = @ARCHIVO, 
NOMBRE_ARCHIVO_REAL = @NOMBRE_REAL 
WHERE  
IDPLANTILLA = @IDPLANTILLA