//[idvideo|Integer,puntaje|Numeric,]
--SELECT
DECLARE @PUNTAJE1 FLOAT
DECLARE @PUNTAJE FLOAT
DECLARE @VOTOS INT
DECLARE @IDVIDEO INT
SET @IDVIDEO=ISNULL(:IDVIDEO,0)
SET @PUNTAJE1=ISNULL(:PUNTAJE,0.0)
SET @PUNTAJE=0
SET @VOTOS=0
SELECT @PUNTAJE = PUNTAJE, @VOTOS = VOTOS FROM SALESUP_CT.DBO.RATING_VIDEOS WHERE IDVIDEO = @IDVIDEO

SET @PUNTAJE = @PUNTAJE + @PUNTAJE1
SET @VOTOS = @VOTOS + 1

UPDATE SALESUP_CT.DBO.RATING_VIDEOS
SET 
PUNTAJE = @PUNTAJE,
VOTOS = @VOTOS
WHERE IDVIDEO = @IDVIDEO

SELECT @VOTOS AS VOTOS