//[session.idempresa|Untyped,session.idusuario|Untyped,q|Text,session.db|Untyped,]

--SELECT 
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @Q VARCHAR(MAX), @QRYCONSULTA VARCHAR(MAX), @CONSULTASQL VARCHAR(MAX)
DECLARE @Q1 VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @Q1=ISNULL(:Q,'')	
SET @Q = '%'+@Q1+'%'

SET @CONSULTASQL = ''
SET @CONSULTASQL = SALESUP_CT.DBO.ArmaQryConsulta(@Q)

SET @QRYCONSULTA = ''
SET @QRYCONSULTA = @QRYCONSULTA + ' SELECT P.Tkp, P.IDPROSPECTO AS IdProspecto, '''+@Q1+''' AS Q,'
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(P.TITULO+'' '','''') AS Titulo , LTRIM(RTRIM(P.NOMBRE)) AS Nombre , '
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS Apellido , '
SET @QRYCONSULTA = @QRYCONSULTA + ' <#SESSION.DB/>.dbo.NomalizaCadena(LTRIM(RTRIM(P.NOMBRE))) AS NomNorma, '
SET @QRYCONSULTA = @QRYCONSULTA + ' <#SESSION.DB/>.dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''')) AS ApeNorma, '
SET @QRYCONSULTA = @QRYCONSULTA + ' P.EMPRESA AS Empresa, P.CORREO AS Correo, P.SEXO AS Sexo, '
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(P.TELEFONO,'''') + ISNULL('', ''+P.TELEFONO2,'''') AS Telefono, ISNULL(P.MOVIL,'''') AS Movil, '
SET @QRYCONSULTA = @QRYCONSULTA + ' P.ESCLIENTE AS EsCliente , CASE PA.ARCHIVADO WHEN 1 THEN ''Archivado'' ELSE '''' END AS Archivado '
SET @QRYCONSULTA = @QRYCONSULTA + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P '
SET @QRYCONSULTA = @QRYCONSULTA + ' JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = P.IDPROSPECTO '
SET @QRYCONSULTA = @QRYCONSULTA + ' WHERE Pa.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' AND P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.DESCARTADO = 0 '
SET @QRYCONSULTA = @QRYCONSULTA + @CONSULTASQL
SET @QRYCONSULTA = @QRYCONSULTA + ' ORDER BY P.NOMBRE, P.APELLIDOS '

EXEC (@QRYCONSULTA)
