//[idautoresponder|Integer,session.db|Untyped,]
DECLARE @TOTAL INT
DECLARE @CONT INT
DECLARE @IDPIEZA INT
DECLARE @IDPIEZAFINAL INT
DECLARE @EXISTE INT
DECLARE @NOMBREARCHIVO VARCHAR(8000)
DECLARE @NOMBRE VARCHAR(8000)
DECLARE @IDAUTORESPONDER INT
SET @IDAUTORESPONDER =ISNULL(:IDAUTORESPONDER,0)
SET @NOMBREARCHIVO = ''
SELECT TOP 1 @IDPIEZA = IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER 
SELECT TOP 1 @IDPIEZAFINAL = IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER  ORDER BY IDPIEZA DESC
SELECT @TOTAL = COUNT (*) FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER 

SET @CONT = 0
WHILE @IDPIEZA <= @IDPIEZAFINAL 
BEGIN
SELECT @EXISTE = COUNT (*) FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZA
	IF @EXISTE <> 0
	BEGIN
	SELECT @NOMBRE = NOMBRE_ARCHIVO FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER  AND IDPIEZA = @IDPIEZA
	SET @NOMBREARCHIVO = @NOMBREARCHIVO + @NOMBRE 
	END

	
SET @IDPIEZA = @IDPIEZA + 1
END
SELECT @NOMBREARCHIVO AS ARCHIVOS,@IDAUTORESPONDER  AS IDAUTORESPONDER 