//[ruta_doc|Text,pesokb|Text,idautoresponder|Text,tkauto|Text,session.db|Untyped,session.idempresa|Untyped,tipocorreo|Integer,titulo|Text,contenido|Text,dias|Text,session.idusuario|Untyped,]
--insert

DECLARE @IDULTIMO INT
DECLARE @TOTAL INT
DECLARE @ORDEN INT
DECLARE @ORD INT
DECLARE @MAXIDPIEZA INT
DECLARE @RUTA_DOC VARCHAR(8000)
DECLARE @ADJUNTOS VARCHAR(8000)
DECLARE @PESOS VARCHAR(8000)
DECLARE @TKAUTO VARCHAR(128)
DECLARE  @IDAUTORESPONDER INT

SET @ADJUNTOS = :RUTA_DOC
SET @PESOS=:PESOKB

SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER, 0)
SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END



DECLARE @TIPOCORREO INT
SET @TIPOCORREO = CAST(ISNULL(:TIPOCORREO,0) AS INT)
IF @TIPOCORREO = 0 SET @TIPOCORREO = 1

SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/')
INSERT INTO <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS (IDAUTORESPONDER, ASUNTO, CUERPO, ANEXOS, NOMBRE_ARCHIVO, NOMBRE_ARCHIVO_REAL, ENVIAR_TIEMPO,ENVIAR_TIPO, ESTADO, TIPOCORREO) 
VALUES (@IDAUTORESPONDER,:TITULO, :CONTENIDO , @RUTA_DOC, '','',ISNULL(:dias,''),1,1, @TIPOCORREO)

SELECT @IDULTIMO = @@IDENTITY

SELECT @ORDEN = MAX(ORDEN) FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER
SELECT @MAXIDPIEZA = MAX(IDPIEZA) FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER AND ORDEN = @ORDEN

IF @ORDEN IS NULL
   SET @ORDEN = 1
ELSE 
  SET @ORDEN = @ORDEN + 1

 UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS 
  SET 
  NOMBRE_ARCHIVO = <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_PLANTILLAS (ANEXOS),
  NOMBRE_ARCHIVO_REAL = <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PLANTILLAS (ANEXOS), 
  ORDEN = @ORDEN 
  WHERE IDPIEZA = @IDULTIMO
  
  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_ARCHIVOS_CONTROL_EMPRESAS_ARCHIVOS_AMAZON <#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,@ADJUNTOS,@PESOS,'AU'
  
/* UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS 
  SET ANEXOS = REPLACE (CAST (ANEXOS AS VARCHAR(8000)),'\r \n',CHAR(13)+CHAR(10)),
  NOMBRE_ARCHIVO = REPLACE (CAST (NOMBRE_ARCHIVO AS VARCHAR(8000)), ' ,',''),
  NOMBRE_ARCHIVO_REAL = REPLACE (CAST (NOMBRE_ARCHIVO_REAL AS VARCHAR(8000)), ' ,',''),
  ORDEN = @ORDEN 
  WHERE IDPIEZA = @IDULTIMO*/  
  
  UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL SET IDPIEZA_SIGUIENTE = @IDULTIMO WHERE IDPIEZA = @MAXIDPIEZA AND IDPIEZA_SIGUIENTE = -1