//[tipodoc|Text,carpeta|Text,nombrearchivo|Text,]
--insert
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @TIPODOC VARCHAR(1000)
DECLARE @CARPETA VARCHAR(1000)
DECLARE @NOMBREARCHIVO VARCHAR(1000)
SET @TIPODOC=ISNULL(:TIPODOC,'')
SET @CARPETA=CAST(:CARPETA,'')
SET @NOMBREARCHIVO=CAST(:NOMBREARCHIVO,'')
EXEC SALESUP_CT.DBO.SP_MUEVE_DOC @TIPODOC, @CARPETA, @NOMBREARCHIVO
