//[session.idempresa|Untyped,session.idusuario|Untyped,idoportunidad|Integer,session.db|Untyped,cuerpo|Text,]
--SELECT 
/*PROTEGIDO*/

DECLARE @CADENA VARCHAR(MAX)
DECLARE @INICIO INT
DECLARE @INICIO2 INT
DECLARE @FIN INT
DECLARE @CONTADOR INT
DECLARE @INTENTOS INT
DECLARE @VALOR VARCHAR(MAX)
DECLARE @IDPROSPECTO INT 
DECLARE @CORREOPROSPECTO VARCHAR (8000)
DECLARE @NOMBREPROSPECTO VARCHAR (8000)
DECLARE @APELLIDOPROSPECTO VARCHAR (8000)
DECLARE @CORREOUSUARIO VARCHAR (8000)
DECLARE @NOMBREUSUARIO VARCHAR (8000)
DECLARE @APELLIDOUSUARIO VARCHAR (8000)
DECLARE @IDoportunidad INT, @IDUSUARIO INT, @IDEMPRESA INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDoportunidad = ISNULL(:IDoportunidad,0)

SELECT @IDPROSPECTO = 0, @NOMBREPROSPECTO = 'Vanessa', @APELLIDOPROSPECTO = 'Arce', @CORREOPROSPECTO = 'soporte@salesup.com.mx' 

SELECT @NOMBREUSUARIO = NOMBRE, @APELLIDOUSUARIO = APELLIDOS, @CORREOUSUARIO = EMAIL 
FROM <#SESSION.DB/>.DBO.USUARIOS 
WHERE IDUSUARIO = @IDUSUARIO

SET @CADENA = ISNULL(:CUERPO,'')
SET @VALOR = ''
SET @CONTADOR = 0
SET @INTENTOS = 30
SET @INICIO = CHARINDEX ('[', @CADENA,1)
SET @FIN = CHARINDEX (']', @CADENA,1)
SET @INICIO2 = CHARINDEX('[', @CADENA,1+CHARINDEX(']', @CADENA,1)) 

IF @INICIO2 = '0'
SET @INICIO2 = @FIN+1


WHILE @INICIO <> 0 AND @FIN <> 0 AND @CONTADOR < @INTENTOS
BEGIN

IF ( (@INICIO > @FIN) OR (@INICIO=@INICIO2) )
BEGIN
   SET @VALOR = SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), 0, @INICIO2-1)
   SET @VALOR = REPLACE (@VALOR,']','<b style=''color: ff0000''>} << ERROR: ETIQUETA NO VALIDA  </b>')
   SET @CADENA = REPLACE (@CADENA,SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), 0, @INICIO2-1),@VALOR)

END
ELSE
BEGIN

IF (@FIN > @INICIO2)
  BEGIN
  SET @FIN = @FIN-@INICIO
   SET @VALOR = SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), @INICIO+1, @FIN-1)
   SET @VALOR = REPLACE (@VALOR,'[','{')
   SET @VALOR = '<b style=''color:ff0000''>{'+@VALOR+'}</b><b style=''color:ff0000''> << ERROR: ETIQUETA NO VALIDA </b>'
   SET @CADENA = REPLACE (@CADENA,'['+SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), @INICIO+1, @FIN-1)+']',@VALOR)
  END
  ELSE
  BEGIN
  SET @FIN = @FIN-@INICIO
  SET @VALOR = <#SESSION.DB/>.DBO.ObtieneEtiquetasPlantillas(@IDPROSPECTO,@IDUSUARIO,@IDEMPRESA,SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), @INICIO+1, @FIN-1),@IDoportunidad)
  SET @CADENA = REPLACE (@CADENA,'['+SUBSTRING(CAST(@CADENA AS VARCHAR(MAX)), @INICIO+1, @FIN-1)+']',@VALOR)
  END
  
END
SET @INICIO = CHARINDEX ('[', @CADENA,1)
SET @INICIO2 = CHARINDEX('[', @CADENA,1+CHARINDEX(']', @CADENA,1))   
SET @FIN = CHARINDEX (']', @CADENA,1)
SET @CONTADOR = @CONTADOR+1

IF @INICIO2 = '0'
SET @INICIO2 = @FIN+1

END
SELECT @CADENA AS TEXTO , @NOMBREPROSPECTO +' '+ @APELLIDOPROSPECTO AS NOMBREPROSPECTO , 
@CORREOPROSPECTO  AS CORREOPROSPECTO , @NOMBREUSUARIO +' '+ @APELLIDOUSUARIO AS NOMBREUSUARIO,
@CORREOUSUARIO AS CORREOUSUARIO 




 