//[session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--SELECT

DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @TIENEN INT
DECLARE @FONDO VARCHAR(MAX)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT @FONDO = FONDO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO

UPDATE <#SESSION.DB/>.DBO.USUARIOS SET FONDO = NULL WHERE IDUSUARIO = @IDUSUARIO

UPDATE <#SESSION.DB/>.DBO.USUARIOS SET FONDO = NULL, CAMBIARFONDO = 1 
WHERE IDEMPRESA = @IDEMPRESA AND FONDO = @FONDO

SELECT @TIENEN = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDEMPRESA = @IDEMPRESA AND FONDO = @FONDO

SELECT @TIENEN AS Tienen, @FONDO AS Fondo