//[session.idempresa|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,idusuario|Text,session.db|Untyped,]
--select 
DECLARE @IDEMPRESA INT, @IDNIVEL INT, @IDGRUPO INT
DECLARE @IDUSUARIO INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDNIVEL = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)
SET @IDUSUARIO=CAST(:IDUSUARIO AS INT)

IF @IDNIVEL = 1
  SELECT U.IDUSUARIO, U.NOMBRE +' '+U.APELLIDOS+' ('+LTRIM(RTRIM(U.INICIALES))+')' AS NOMBRE, U.IDGRUPO , UG.GRUPO, u.tku, u.idusuario
  FROM <#SESSION.DB/>.dbo.USUARIOS U
  LEFT JOIN  <#SESSION.DB/>.dbo.USUARIOS_GRUPOS UG ON UG.IDUSUARIOGRUPO = U.IDGRUPO AND UG.IDEMPRESA = U.IDEMPRESA
  WHERE U.IDEMPRESA = @IDEMPRESA AND U.ACTIVO=1
  ORDER BY U.NOMBRE, U.APELLIDOS
ELSE
  SELECT U.IDUSUARIO, U.NOMBRE +' '+U.APELLIDOS+' ('+LTRIM(RTRIM(U.INICIALES))+')' AS NOMBRE, U.IDGRUPO , UG.GRUPO, u.tku, u.idusuario
  FROM <#SESSION.DB/>.dbo.USUARIOS U
  LEFT JOIN  <#SESSION.DB/>.dbo.USUARIOS_GRUPOS UG ON UG.IDUSUARIOGRUPO = U.IDGRUPO AND UG.IDEMPRESA = U.IDEMPRESA
  WHERE U.IDEMPRESA = @IDEMPRESA AND (U.IDGRUPO=@IDGRUPO OR U.NIVEL <=2) AND U.ACTIVO=1
  ORDER BY U.NOMBRE, U.APELLIDOS