//[session.db|Untyped,idautoresponderactual|Text,idautoresponder|Integer,]
--INSERT
INSERT INTO <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS (IDAUTORESPONDER, ASUNTO, CUERPO, ANEXOS, NOMBRE_ARCHIVO, NOMBRE_ARCHIVO_REAL,ENVIAR_TIEMPO, ENVIAR_TIPO, ORDEN, ESTADO, ID_ANT)
SELECT ISNULL(:IdAutoResponderActual,''), ASUNTO, CUERPO, ANEXOS, NOMBRE_ARCHIVO, NOMBRE_ARCHIVO_REAL,ENVIAR_TIEMPO, ENVIAR_TIPO, ORDEN, 0, ID_ANT 
FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = cast(ISNULL(:IdAutoresponder,0) as int)