//[session.db|Untyped,contenido|Text,idplantilla|Integer,ruta_doc|Text,pesokb|Text,asunto|Text,descripcion|Text,compartircon|Integer,session.idempresa|Untyped,session.idusuario|Untyped,tkpl|Text,]
--INSERT
DECLARE @ANEXOS VARCHAR(8000)
DECLARE @RUTADOC VARCHAR(8000)
DECLARE @ANEXOSNUEVO VARCHAR(8000)
DECLARE @CONTENIDO VARCHAR(MAX)
DECLARE @TKPL VARCHAR(128)

SET @CONTENIDO = <#SESSION.DB/>.dbo.PreparaCadena(:CONTENIDO)


DECLARE @ARCHIVONUEVO VARCHAR(8000)
DECLARE @NOMBRE_REALNUEVO VARCHAR(8000)
DECLARE @ARCHIVO VARCHAR(8000)
DECLARE @NOMBRE_REAL VARCHAR(8000), @ASUNTO VARCHAR(1024), @DESCRIPCION VARCHAR(1024)
DECLARE @RUTA_DOC VARCHAR(8000)
DECLARE @ADJUNTOS VARCHAR(8000)
DECLARE @PESOS VARCHAR(8000)
DECLARE @IDPLANTILLA INT
SET @IDPLANTILLA=ISNULL(:IDPLANTILLA,0)
SET @ADJUNTOS = :RUTA_DOC
SET @PESOS=:PESOKB
SET @RUTA_DOC=''


SET @TKPL = ISNULL(:TKPL,'')
IF @TKPL != '' BEGIN SELECT @IDPLANTILLA=IDPLANTILLA FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE CAST(TK AS VARCHAR(128))  = @TKPL END



IF (@ADJUNTOS IS NOT NULL AND @ADJUNTOS!='')
BEGIN
SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/')
end

SELECT @ANEXOS=ANEXOS, @ARCHIVO=NOMBRE_ARCHIVO , @NOMBRE_REAL = NOMBRE_ARCHIVO_REAL FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA

IF (RTRIM(LTRIM(REPLACE(REPLACE(@ANEXOS,CHAR(10),''),CHAR(13),'')))='')
   SET @ANEXOSNUEVO = @RUTA_DOC
ELSE
   SET @ANEXOSNUEVO = CASE WHEN @ANEXOS IS NULL THEN @RUTA_DOC ELSE @ANEXOS+CHAR(10)+CHAR(13)+ @RUTA_DOC END
       
SET @ARCHIVONUEVO = @ARCHIVO + <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_PLANTILLAS (@RUTA_DOC)
SET @NOMBRE_REALNUEVO = @NOMBRE_REAL + <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PLANTILLAS (@RUTA_DOC)
SET @ARCHIVO = @ARCHIVONUEVO
SET @NOMBRE_REAL = @NOMBRE_REALNUEVO
SET @ASUNTO = :ASUNTO
SET @DESCRIPCION = :DESCRIPCION

SET @ASUNTO = REPLACE(@ASUNTO, '"', '&quot;')
SET @DESCRIPCION = REPLACE(@DESCRIPCION, '"', '&quot;')

IF @CONTENIDO IS NULL SET @CONTENIDO = ''

UPDATE <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
SET
DESCRIPCION = @DESCRIPCION,
CUERPO = @CONTENIDO,
ASUNTO = @ASUNTO,
ANEXOS = @ANEXOSNUEVO, 
NOMBRE_ARCHIVO =@ARCHIVO,
NOMBRE_ARCHIVO_REAL = @NOMBRE_REAL,  
COMPARTIRCON=:COMPARTIRCON
WHERE IDPLANTILLA = @IDPLANTILLA



EXEC <#SESSION.DB/>.DBO.SP_INGRESA_ARCHIVOS_CONTROL_EMPRESAS_ARCHIVOS_AMAZON <#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,@ADJUNTOS,@PESOS,'PA'
