//[idplantilla|Integer,session.db|Untyped,session.idusuario|Untyped,tkpl|Text,]

DECLARE @IDPLANTILLA INT
DECLARE @TKPL VARCHAR(128)


SET @IDPLANTILLA = ISNULL(:IDPLANTILLA, 0)

SET @TKPL = ISNULL(:TKPL,'')
IF @TKPL != '' BEGIN SELECT @IDPLANTILLA=IDPLANTILLA FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE CAST(TK AS VARCHAR(128))  = @TKPL END



IF @IDPLANTILLA = 0
SELECT 0 AS IDPLANTILLA, 0 AS COMPARTIRCON
ELSE 
SELECT
CASE WHEN TIPOCORREO = 1 THEN 'Correo' ELSE 'SMS' END AS ELTIPO,
TIPOCORREO,
replace(up.asunto,'"','&quot;') as asunto, 
(CASE WHEN RTRIM(LTRIM(REPLACE(REPLACE(CAST(up.anexos AS VARCHAR(8000)),CHAR(10),''),CHAR(13),'')))='' THEN '' ELSE REPLACE(REPLACE(REPLACE(CAST(up.anexos AS VARCHAR(8000)),CHAR(10)+CHAR(10),CHAR(10)),CHAR(10),','),CHAR(13),'')END) as anexos,
<#SESSION.DB/>.DBO.fnCountChar(up.NOMBRE_ARCHIVO_REAL,',') AS TOTALFILES,up.* 
FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP WHERE 
 up.idusuario=<#session.idusuario/> AND UP.IDPLANTILLA = @IDPLANTILLA
ORDER BY DESCRIPCION
 