//[amazon|Integer,archivo|Text,idpieza|Integer,idautoresponder|Integer,session.db|Untyped,session.idempresa|Untyped,]
--delete
DECLARE @IDPIEZAACTUALIZAR INT
DECLARE @IDPIEZAELIMINAR INT
DECLARE @IDPIEZASIGUIENTE INT
DECLARE @IDAUTORESPONDER INT
DECLARE @ORDEN INT
DECLARE @AMAZON INT
DECLARE @HAYARCHIVO INT
DECLARE @ARCHIVOBUSCAR VARCHAR(8000)
SET @AMAZON=ISNULL(:AMAZON,0)
SET @ARCHIVOBUSCAR = ISNULL(:ARCHIVO,'')

SET @IDPIEZAELIMINAR = ISNULL(:IDPIEZA,0)
SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER,0)

SELECT TOP 1 @IDPIEZASIGUIENTE = IDPIEZA_SIGUIENTE FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_CONTROL WHERE IDPIEZA = @IDPIEZAELIMINAR
SELECT TOP 1 @IDPIEZAACTUALIZAR = IDPIEZA FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_CONTROL WHERE IDPIEZA_SIGUIENTE = @IDPIEZAELIMINAR

UPDATE <#SESSION.DB/>.dbo.AUTORESPONDERS_CONTROL SET IDPIEZA_SIGUIENTE = @IDPIEZASIGUIENTE WHERE IDPIEZA = @IDPIEZAACTUALIZAR
DELETE FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_CONTROL WHERE IDPIEZA = @IDPIEZAELIMINAR
UPDATE <#SESSION.DB/>.dbo.USUARIOS_EMAILS SET IDAUTORESPONDER = NULL , IDPIEZA = NULL WHERE IDAUTORESPONDER  = @IDAUTORESPONDER AND IDPIEZA = @IDPIEZAELIMINAR

SELECT @ORDEN = ORDEN FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZAELIMINAR
UPDATE <#SESSION.DB/>.dbo.AUTORESPONDERS_PIEZAS SET ORDEN = ORDEN - 1 WHERE ORDEN > @ORDEN AND IDAUTORESPONDER  = @IDAUTORESPONDER
DELETE FROM <#SESSION.DB/>.dbo.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZAELIMINAR


IF @AMAZON!=0 
 BEGIN
  SELECT @HAYARCHIVO=COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND ARCHIVO LIKE @ARCHIVOBUSCAR
  IF (@HAYARCHIVO>0)
   BEGIN
     DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE ARCHIVO LIKE @ARCHIVOBUSCAR AND IDEMPRESA=<#SESSION.IDEMPRESA/> AND TIPO='AU'
   END  
 END 
