//[idemail|Integer,session.db|Untyped,]
--select
DECLARE @TB TABLE(Id INT IDENTITY, Nombre VARCHAR(MAX), Archivo VARCHAR(MAX))
DECLARE @ANEXOS VARCHAR(MAX)
DECLARE @IDEMAIL INT 
SET @IDEMAIL = CAST(ISNULL(:idemail,0) AS INT)

SELECT @ANEXOS = REPLACE(CONVERT(VARCHAR(MAX), ANEXOS), CHAR(10)+CHAR(13) , '|') FROM <#session.db/>.DBO.USUARIOS_EMAILS WHERE IDEMAIL = @IDEMAIL

INSERT INTO @TB (Nombre, Archivo)
SELECT REPLACE(SUBSTRING(SplitValue,25,LEN(SplitValue)),'_',' ') , REPLACE(SplitValue, '/','') FROM SALESUP_CT.DBO.Split(@ANEXOS,'|') WHERE SplitValue != ''

SELECT * FROM @TB