//[estado|Integer,idpieza|Integer,session.db|Untyped,]
--UPDATE
DECLARE @ESTADO INT, @IDPIEZA INT, @ORDEN INT, @IDAUTORESPONDER INT, @TOTAL INT
SET @ESTADO = ISNULL(:ESTADO,0)
SET @IDPIEZA = ISNULL(:IDPIEZA,0)

IF @ESTADO = 0
BEGIN
	SELECT @ORDEN = ORDEN , @IDAUTORESPONDER = IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZA
	UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS SET ESTADO = @ESTADO , ORDEN = NULL WHERE IDPIEZA = @IDPIEZA
	UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS SET ORDEN = ORDEN - 1 WHERE ORDEN > @ORDEN AND IDAUTORESPONDER = @IDAUTORESPONDER
END

IF @ESTADO = 1
BEGIN
   SELECT @IDAUTORESPONDER = IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDPIEZA = @IDPIEZA
   SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER
   IF @TOTAL = 1
   	  SET @ORDEN = 0
   ELSE
   	  SELECT TOP 1 @ORDEN = ORDEN FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDAUTORESPONDER = @IDAUTORESPONDER ORDER BY ORDEN DESC
   
   IF @ORDEN IS NULL SET @ORDEN = 0
   
   UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS SET ORDEN = @ORDEN + 1, ESTADO = @ESTADO WHERE IDPIEZA = @IDPIEZA
END