//[condicioncitas|Text,session.idusuario|Untyped,idu|Text,fechaactual|Text,session.gmt|Untyped,r|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONDICIONCITAS VARCHAR(MAX)
SET @CONDICIONCITAS = ISNULL(:CONDICIONCITAS,'')

SET @SQL ='
DECLARE @GMT INT, @SESSIONIDUSUARIO INT, @TO INT, @N INT, @IDCITA INT, @CONPROSPECTOS INT, @IDEMPRESA INT
DECLARE @MESACTUAL VARCHAR(MAX), @IDUSUARIO VARCHAR(MAX), @INVITADOS VARCHAR(MAX), @CONTACTOS VARCHAR(MAX), @IdsProspectos VARCHAR(MAX), @TksProspectos VARCHAR(MAX)
DECLARE @FECHA DATETIME, @FINICIO DATETIME, @FFIN DATETIME
DECLARE @TB TABLE(N INT IDENTITY, IDCITA INT, Tipo VARCHAR(MAX), Color VARCHAR(MAX), id VARCHAR(MAX), title VARCHAR(MAX), className VARCHAR(MAX),
start VARCHAR(32), [end] VARCHAR(32), StrFecha VARCHAR(MAX), Lugar VARCHAR(MAX), DescripcionCita VARCHAR(MAX), hInicio VARCHAR(MAX), hFin VARCHAR(MAX), 
ConQuien VARCHAR(MAX), IdCompania VARCHAR(MAX), Empresa VARCHAR(MAX), Invitados VARCHAR(MAX), Idu VARCHAR(MAX),  MismoDia VARCHAR(1), FechaInicio VARCHAR(MAX), HoraInicio VARCHAR(10), FechaFin VARCHAR(MAX), 
HoraFin VARCHAR(10), DTF FLOAT, ConProspecto INT, Contactos VARCHAR(MAX), IdsProspectos VARCHAR(MAX), TksProspectos VARCHAR(MAX),tPadre varchar(max))
DECLARE @RANGO INT

SET @SESSIONIDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDUSUARIO = '''+ISNULL(:IDU,'')+'''
SET @MESACTUAL = '''+ISNULL(:FechaActual,'')+'''
SET @GMT = <#SESSION.GMT/>
SET @RANGO = '+CAST(ISNULL(:R,0) AS VARCHAR(1000))+'
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

IF @MESACTUAL != ''''
BEGIN
	SET @FECHA = CONVERT(DATETIME, @MESACTUAL, 103 )
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, 5, @FECHA)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, 5, @FECHA)
	SET @FINICIO = DATEADD(dd, -6, @FINICIO)
	SET @FFIN = DATEADD(dd, 6, @FFIN)
END
ELSE
BEGIN
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, @RANGO, NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, @RANGO, NULL)
END

SET @TO = 0
SET @N = 1

INSERT INTO @TB (IDCITA, Tipo, Color, id, title, className, start, [end], StrFecha, Lugar, DescripcionCita, hInicio, hFin, ConQuien, IdCompania, Empresa, Idu, MismoDia, FechaInicio, HoraInicio, FechaFin, HoraFin, DTF,tPadre)
SELECT C.IDCITA, 2 AS Tipo, ''#624492'' as color, ''C''+CAST(C.IDCITA AS VARCHAR(MAX)) AS id, ''<i class="fa fa-calendar"></i> '' + C.ASUNTO AS title,
''Pointer EventoCita C''+CONVERT(VARCHAR(MAX),U.IDUSUARIO)+'' IDC''+CAST(C.IDCITA AS VARCHAR(MAX)) AS className,

SALESUP_CT.DBO.Fecha(C.FECHA_INICIO) AS start,
CASE WHEN C.FECHA_FIN = C.FECHA_INICIO THEN SALESUP_CT.DBO.Fecha(DATEADD(mi,30, C.FECHA_FIN)) ELSE SALESUP_CT.DBO.Fecha(C.FECHA_FIN) END AS [end],

SALESUP_CT.dbo.FechaFormato(C.FECHA_INICIO,5) AS Fecha, C.Lugar, 
CAST(C.DESCRIPCION AS VARCHAR(MAX)) ,
LTRIM(RTRIM(RIGHT(CONVERT(VARCHAR, DATEADD(hh, (0),C.FECHA_INICIO) ,100),8))) as hInicio,
LTRIM(RTRIM(RIGHT(CONVERT(VARCHAR, DATEADD(hh, (0),C.FECHA_FIN) ,100),8))) as hFin,
'''', P.IdCompania, CASE WHEN ISNULL(P.IDCOMPANIA,0)=0 THEN P.EMPRESA ELSE COM.EMPRESA END AS Empresa, U.IDUSUARIO, 
CASE WHEN SALESUP_CT.dbo.GetOnlyDate(C.FECHA_FIN) = SALESUP_CT.dbo.GetOnlyDate(C.FECHA_INICIO) THEN ''1'' ELSE '''' END as MismoDia,
CONVERT(VARCHAR(10), C.FECHA_INICIO,103) as FechaInicio, 
SALESUP_CT.dbo.ObtieneHora(C.FECHA_INICIO) as HoraInicio, 
CONVERT(VARCHAR(10), C.FECHA_FIN,103) as FechaFin,
SALESUP_CT.dbo.ObtieneHora(C.FECHA_FIN) as HoraFin,
CONVERT(FLOAT, C.FECHA_FIN) AS DTF
,(CASE WHEN C.IDPADRE IS NOT NULL OR C.RECURRENCIA>0 THEN ''1'' ELSE '''' END) AS tPadre
FROM <#SESSION.DB/>.dbo.CITAS C
JOIN <#SESSION.DB/>.dbo.CITAS_INVITADOS CI ON CI.IDPERSONA IN (SELECT SPLITVALUE FROM SALESUP_CT.DBO.SPLIT(@IDUSUARIO, '','') ) AND C.IDCITA = CI.IDCITA
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = CI.IDPERSONA
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = CI.IDPERSONA
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA 
JOIN <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SESSIONIDUSUARIO,5,0) UP ON U.IDUSUARIO = UP.ID
WHERE 
U.IDEMPRESA = @IDEMPRESA  AND C.ACTIVO = 1  '+@CONDICIONCITAS+'
GROUP BY C.IDCITA, C.ASUNTO, C.FECHA_INICIO, C.FECHA_FIN, C.LUGAR, CI.PERSONA, U.APELLIDOS, U.NOMBRE, CI.TIPOPERSONA, P.NOMBRE, P.APELLIDOS, P.IDCOMPANIA, P.EMPRESA, COM.EMPRESA, U.IDUSUARIO,C.IDPADRE,C.RECURRENCIA, CAST(C.DESCRIPCION AS VARCHAR(MAX)) 

DECLARE @L INT
SELECT @TO = COUNT(*) FROM @TB
WHILE @N <= @TO
BEGIN
	SELECT @IDCITA = IDCITA FROM @TB WHERE N = @N
	SET @INVITADOS = ''''
	
	SELECT @INVITADOS = @INVITADOS + U.NOMBRE +'' ''+ISNULL(U.APELLIDOS, '''')+ '', '' 
	FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS CI 
	JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = CI.IDPERSONA AND CI.TIPOPERSONA = 2 /*AND U.IDUSUARIO != @SESSIONIDUSUARIO */
	WHERE CI.IDCITA = @IDCITA 
	
	SET @CONPROSPECTOS = 0
	SELECT @CONPROSPECTOS = COUNT(*) FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS CI WHERE CI.IDCITA = @IDCITA AND CI.TIPOPERSONA = 1
	
	IF @CONPROSPECTOS = 0 BEGIN SET @CONPROSPECTOS = NULL END
	
	SET @CONTACTOS = ''''
	SET @IdsProspectos = ''''
	SET @TksProspectos = ''''
	SELECT @CONTACTOS = @CONTACTOS + P.NOMBRE + '' '' +ISNULL(P.APELLIDOS, '''')+'', '', 
	@IdsProspectos = @IdsProspectos + CONVERT(VARCHAR(MAX), P.IDPROSPECTO) + '','',
	@TksProspectos = @TksProspectos + P.TKP + '',''
	FROM <#SESSION.DB/>.dbo.PROSPECTOS P 
	JOIN <#SESSION.DB/>.dbo.CITAS_INVITADOS CI ON CI.IDCITA = @IDCITA AND CI.IDPERSONA = P.IDPROSPECTO AND CI.TIPOPERSONA = 1
	
	SELECT @CONTACTOS = @CONTACTOS + CI.PERSONA +'', ''
	FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS CI 
	WHERE CI.IDCITA = @IDCITA AND CI.TIPOPERSONA = 0
	
	SET @L = LEN(@INVITADOS)
	IF @L > 1 BEGIN  SET @INVITADOS = SUBSTRING( @INVITADOS , 1, @L-1) END
	
	SET @L = 0
	SET @L = LEN(@CONTACTOS)
	IF @L > 1 BEGIN  SET @CONTACTOS = SUBSTRING( @CONTACTOS , 1, @L-1) END
	
	SET @L = 0
	SET @L = LEN(@IdsProspectos)
	IF @L > 1 BEGIN  SET @IdsProspectos = SUBSTRING( @IdsProspectos , 1, @L-1) END
	
	SET @L = 0
	SET @L = LEN(@TksProspectos)
	IF @L > 1 BEGIN  SET @TksProspectos = SUBSTRING( @TksProspectos , 1, @L-1) END
	
	UPDATE @TB SET INVITADOS = @INVITADOS, ConProspecto = @CONPROSPECTOS, 
	Contactos = @CONTACTOS, IdsProspectos = @IdsProspectos ,
	TksProspectos = @TksProspectos
	WHERE IDCITA = @IDCITA
	
SET @N = @N + 1
END

SELECT ''1'' as Cita,Tipo, color, id, title, className, start, [end], StrFecha, Lugar, DescripcionCita,
hInicio, hFin, ConQuien, IdCompania, Empresa, Invitados, Idu,''1'' AS Acciones, MismoDia, FechaInicio, HoraInicio, FechaFin, HoraFin, ConProspecto, Contactos, IdsProspectos, TksProspectos, DTF, tPadre
FROM @TB 
GROUP BY idcita, Tipo, color, id, title, className, start, [end], StrFecha, Lugar, DescripcionCita,
hInicio, hFin, ConQuien, IdCompania, Empresa, Invitados, Idu, MismoDia, FechaInicio, HoraInicio, ConProspecto, FechaFin, HoraFin, Contactos, DTF, IdsProspectos, TksProspectos, tPadre
ORDER BY DTF
'
EXEC (@SQL)