//[session.idempresa|Untyped,session.idusuario|Untyped,periodo|Integer,anioreporte|Integer,elagrupar|Integer,filtusuario|Integer,filtgrupo|Integer,session.db|Untyped,session.sessionid|Untyped,idmoneda|Integer,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @TIPOREPORTE INT
DECLARE @TIPOAGRUPAMIENTO INT
DECLARE @IDUSUARIOLISTA INT
DECLARE @IDGRUPOLISTA INT
DECLARE @ANIO INT
DECLARE @IDMONEDA INT 

SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TIPOREPORTE= ISNULL(:PERIODO,0)
SET @ANIO = ISNULL(:ANIOREPORTE,0)
SET @TIPOAGRUPAMIENTO=ISNULL(:ELAGRUPAR,0)
SET @IDUSUARIOLISTA=ISNULL(:FILTUSUARIO,0)
SET @IDGRUPOLISTA=ISNULL(:FILTGRUPO,0)
SET @IDMONEDA = ISNULL(:IDMONEDA,0)

DECLARE @SQLTXT AS VARCHAR(8000)
DECLARE @CABECERASDEF VARCHAR(MAX)
DECLARE @CABECERAS VARCHAR(MAX)
DECLARE @CABECERASEXCEL VARCHAR(MAX)

DECLARE @SERVIDORIP VARCHAR(16)
SET @SERVIDORIP =  REPLACE(@@SERVERNAME,'-','.')

SET @CABECERASDEF = ''
SET @CABECERAS = ''
SET @CABECERASEXCEL = ''

DECLARE @TABLACABECERAS TABLE(ID INT IDENTITY, CABECERA VARCHAR(128), TOTAL INT)

INSERT INTO @TABLACABECERAS (CABECERA,TOTAL) EXEC <#SESSION.DB/>.DBO.SP_REPORTE_CLIENTES_CONTINUIDAD_CABECERA @IDEMPRESA, @IDUSUARIO, @TIPOREPORTE, @ANIO

SELECT @CABECERASDEF = @CABECERASDEF + ',PER' + CABECERA + ' MONEY', @CABECERAS = @CABECERAS + ',PER'+ CABECERA+'', @CABECERASEXCEL = @CABECERASEXCEL +',''PER'+ CABECERA+''' COLLATE DATABASE_DEFAULT' FROM @TABLACABECERAS

SELECT @SQLTXT = 'bcp " SELECT  '' NOMBRE'' COLLATE DATABASE_DEFAULT , ''EMPRESA'' COLLATE DATABASE_DEFAULT , ''MONTO'' COLLATE DATABASE_DEFAULT'+@CABECERASEXCEL+',''PCT'' COLLATE DATABASE_DEFAULT  '
SELECT @SQLTXT = @SQLTXT + ' " queryout C:\FileRepository\exporta\archivos\continuidad-<#SESSION.SESSIONID/>-1.csv   -c -C"Latin1" -t, -T -S'+ @@servername

exec master..xp_cmdshell @SQLTXT
SELECT @SQLTXT = ''
SELECT @SQLTXT = 'bcp "'
SELECT @SQLTXT = @SQLTXT + ' DECLARE @TABLATEMP TABLE (ID INT IDENTITY, IDPROSPECTO INT, NOMBRE VARCHAR(128), APELLIDOS VARCHAR(128), EMPRESA VARCHAR(128), MONTO MONEY, IDCOMPANIA INT, TKCOM VARCHAR(128)'+@CABECERASDEF+',PCT FLOAT,SALUD INT,PORCENTAJE VARCHAR(MAX)) '
SELECT @SQLTXT = @SQLTXT + ' INSERT INTO @TABLATEMP (IDPROSPECTO, NOMBRE,APELLIDOS,EMPRESA,MONTO,IDCOMPANIA,TKCOM'+@CABECERAS+', PCT,SALUD,PORCENTAJE) EXEC <#SESSION.DB/>.DBO.SP_REPORTE_CLIENTES_CONTINUIDAD_EXPORTAR '+CAST(@IDEMPRESA AS VARCHAR(128))+', '+CAST(@IDUSUARIO AS VARCHAR(128))+', '+CAST(@TIPOREPORTE AS VARCHAR(128))+', '+CAST(@ANIO AS VARCHAR(128))+', '+CAST(@TIPOAGRUPAMIENTO AS VARCHAR(128))+', '+CAST(@IDUSUARIOLISTA AS VARCHAR(128))+', '+CAST(@IDGRUPOLISTA AS VARCHAR(128))+', '+CAST(@IDMONEDA AS VARCHAR(128))+''
SELECT @SQLTXT = @SQLTXT + ' SELECT ISNULL(NOMBRE,'''') + '' '' + ISNULL(APELLIDOS,''''), ISNULL(EMPRESA,''''), MONTO '+@CABECERAS+', PCT FROM @TABLATEMP '
SELECT @SQLTXT = @SQLTXT + ' " queryout C:\FileRepository\exporta\archivos\continuidad-<#SESSION.SESSIONID/>-2.csv   -c -C"Latin1" -t, -T -S'+ @@servername

exec master..xp_cmdshell @SQLTXT
SELECT @SQLTXT =  'copy C:\FileRepository\exporta\archivos\continuidad-<#SESSION.SESSIONID/>-1.csv +  C:\FileRepository\exporta\archivos\continuidad-<#SESSION.SESSIONID/>-2.csv C:\FileRepository\exporta\archivos\continuidad-<#SESSION.SESSIONID/>.csv' 
exec master..xp_cmdshell @SQLTXT 
