//[tku|Text,tipo|Integer,session.db|Untyped,idusuario|Integer,]
DECLARE @TKU VARCHAR(128)
DECLARE @TIPO INT

SET @TKU = ISNULL(:TKU,'')
SET @TIPO = ISNULL(:TIPO, 0)

IF(@TIPO = 0)
BEGIN
	 SELECT 
	 left(nombre, 3) HOY, *, ISNULL(COMISION, 0) AS LACOMISION FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=:IDUSUARIO
END 
ELSE
BEGIN
 	 SELECT left(nombre, 3) HOY, *, ISNULL(COMISION, 0) AS LACOMISION FROM <#SESSION.DB/>.DBO.USUARIOS WHERE  TKU=@TKU
END

