//[session.idusuario|Untyped,session.db|Untyped,]

DECLARE @IDUSUARIO INT, @IDCSS INT

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SELECT @IDCSS = U.IDCSS FROM <#SESSION.DB/>.DBO.USUARIOS U WHERE IDUSUARIO = @IDUSUARIO

SELECT E.IdCss, E.Estilo, E.Imagen, 
CASE WHEN E.TIPO = 0 THEN '1' END AS Solido, 
CASE WHEN E.TIPO > 0 THEN '1' END AS ConImagen,
CASE WHEN E.IDCSS = @IDCSS THEN '1' END AS Actual
FROM <#SESSION.DB/>.DBO.ESTILOS E --where idcss != 34
ORDER BY 4 DESC, 2