//[session.idusuario|Untyped,datosconfiguracion|Text,tipo|Integer,session.db|Untyped,]
--SELECT

/*PROTEGIDO*/
DECLARE @IDUSUARIO AS INT 
DECLARE @DATOSCONFIG AS VARCHAR(MAX)
DECLARE @TIPO AS INT

SET @IDUSUARIO =CAST('<#SESSION.IDUSUARIO/>' AS INT) 
SET @DATOSCONFIG= ISNULL(:DATOSCONFIGURACION, '')
SET @TIPO = CAST(ISNULL(:TIPO, 0) AS INT)

IF(@TIPO=0)

 BEGIN
  UPDATE <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS
  SET CONFIGURACION_CALENDARIO=@DATOSCONFIG
  WHERE IDUSUARIO=@IDUSUARIO 
  SELECT 'OK' AS RESULT
 END 
ELSE 
 BEGIN
  SELECT ISNULL(CONFIGURACION_CALENDARIO, '') AS CONFIGURACION_CALENDARIO FROM <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS 
  WHERE IDUSUARIO=@IDUSUARIO
END