//[piezaid|Integer,asunto|Text,session.db|Untyped,session.idusuario|Untyped,correousuario|Text,cuerpo|Text,]
--INSERT
DECLARE @ASUNTO VARCHAR(8000), @ANEXOS VARCHAR(MAX)
DECLARE @PIEZAID INT
SET @PIEZAID = CAST(ISNULL(:piezaid,0) AS INT)
SET @ASUNTO = :ASUNTO
SET @ASUNTO = 'SalesUp! - Prueba de autoresponder - ' + @ASUNTO

IF @PIEZAID > 0
BEGIN
	 SELECT @ANEXOS = ANEXOS FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WITH(NOLOCK) WHERE IDPIEZA = @PIEZAID
END

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_EMAILS (IDUSUARIO, TIPO, DESTINATARIO, ASUNTO, CUERPO, ANEXOS) 
VALUES (<#SESSION.IDUSUARIO/>,0,ISNULL(:CORREOUSUARIO,''),<#SESSION.DB/>.DBO.PreparaCadena(@ASUNTO),<#SESSION.DB/>.DBO.PreparaCadena(:CUERPO), @ANEXOS)
