//[session.db|Untyped,session.idusuario|Untyped,nombrearchivo|Text,]
--INSERT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDUSUARIO INT
DECLARE @NOMBREARCHIVO VARCHAR(MAX)
SET @NOMBREARCHIVO = ISNULL(:NOMBREARCHIVO,'')
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
EXEC <#SESSION.DB/>.DBO.SP_INSERTA_USUARIO_ARCHIVO @IDUSUARIO,@NOMBREARCHIVO,0,1
