//[session.idusuario|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDUSUARIO INT
DECLARE @FONDO_SETTING INT
SET @FONDO_SETTING=0
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)

SELECT @FONDO_SETTING=FONDO_SETTING FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=@IDUSUARIO
SELECT @FONDO_SETTING AS FONDO_SETTING