//[ruta_doc|Text,pesokb|Text,session.db|Untyped,idpieza|Integer,titulo|Text,contenido|Text,dias|Integer,session.idempresa|Untyped,session.idusuario|Untyped,tkpi|Text,]
--INSERT
DECLARE @ANEXOS VARCHAR(8000)
DECLARE @RUTADOC VARCHAR(8000)
DECLARE @ANEXOSNUEVO VARCHAR(8000)
DECLARE @ARCHIVONUEVO VARCHAR(8000)
DECLARE @NOMBRE_REALNUEVO VARCHAR(8000)
DECLARE @ARCHIVO VARCHAR(8000)
DECLARE @NOMBRE_REAL VARCHAR(8000)
DECLARE @RUTA_DOC VARCHAR(8000)
DECLARE @ADJUNTOS VARCHAR(8000)
DECLARE @IDPIEZA INT
DECLARE @PESOS VARCHAR(8000)
DECLARE @TKPI VARCHAR(128)

SET @IDPIEZA = ISNULL(:IDPIEZA, 0)

SET @TKPI = ISNULL(:TKPI,'')
IF @TKPI != '' BEGIN SELECT @IDPIEZA=IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE CAST(TKPI AS VARCHAR(128))  = @TKPI END


SET @ADJUNTOS = :RUTA_DOC
SET @PESOS=:PESOKB
SET @RUTA_DOC=''
 
IF (@ADJUNTOS IS NOT NULL AND @ADJUNTOS!='')
 BEGIN
  SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/')
 END

SELECT @ANEXOS=ANEXOS, @ARCHIVO=NOMBRE_ARCHIVO , @NOMBRE_REAL = NOMBRE_ARCHIVO_REAL FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE IDPIEZA =@IDPIEZA

IF (RTRIM(LTRIM(REPLACE(REPLACE(@ANEXOS,CHAR(10),''),CHAR(13),'')))='')
   SET @ANEXOSNUEVO = @RUTA_DOC
ELSE
   SET @ANEXOSNUEVO = CASE WHEN @ANEXOS IS NULL THEN @RUTA_DOC ELSE @ANEXOS+CHAR(10)+CHAR(13)+ @RUTA_DOC END


SET @ARCHIVONUEVO = @ARCHIVO + <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_PLANTILLAS (@RUTA_DOC)
SET @NOMBRE_REALNUEVO = @NOMBRE_REAL + <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PLANTILLAS (@RUTA_DOC)
SET @ARCHIVO = @ARCHIVONUEVO
SET @NOMBRE_REAL = @NOMBRE_REALNUEVO


UPDATE <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS 
SET
ASUNTO = :TITULO,
CUERPO = :CONTENIDO,
ANEXOS = @ANEXOSNUEVO, 
NOMBRE_ARCHIVO =@ARCHIVO,
NOMBRE_ARCHIVO_REAL = @NOMBRE_REAL,
ENVIAR_TIEMPO = :DIAS
WHERE IDPIEZA = @IDPIEZA

EXEC <#SESSION.DB/>.DBO.SP_INGRESA_ARCHIVOS_CONTROL_EMPRESAS_ARCHIVOS_AMAZON <#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,@ADJUNTOS,@PESOS,'AU'
