//[session.convertcode|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,tkpseleccionado|Text,ido|Text,recordatorio|Text,hora|Text,vence|Text,idpeticion|Text,repetir|Text,terminar|Text,fecharepetir|Text,cada|Text,diasrecurrencia|Text,diasmes|Text,session.db|Untyped,]
--INSERT
DECLARE @IDUSUARIO INT, @CONVERTCODE INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT, @YAEXISTE INT, @IDRECORDATORIO INT, @IDEMPRESA INT
DECLARE @TKP VARCHAR(MAX), @RECORDATORIO VARCHAR(MAX), @Hora VARCHAR(MAX), @Vence VARCHAR(MAX), @IDPETICION VARCHAR(MAX)
DECLARE @FECHA DATETIME

DECLARE @RECURRENCIA INT
DECLARE @TIPOFIN INT
DECLARE @FECHAFINREPETIR DATETIME
DECLARE @FRECUENCIA INT
DECLARE @DIASFRECUENCIA VARCHAR(5000)
DECLARE @IDPADRE INT

SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TKP = dbo.ValidaToken(ISNULL(:TkpSeleccionado,''))
SET @IDOPORTUNIDAD = CAST(ISNULL(:IDO,'') AS INT)
SET @RECORDATORIO = :RECORDATORIO
SET @Hora =ISNULL(:Hora,'')
SET @Vence =ISNULL(:Vence,'')+' '+@Hora
SET @FECHA = CONVERT(DATETIME, @Vence, @CONVERTCODE)
SET @IDPETICION = ISNULL(:IDPETICION,'')
SET @IDPADRE=NULL
 
SET @RECURRENCIA=CAST(ISNULL(:REPETIR,'') AS INT)
SET @TIPOFIN=CAST(ISNULL(:TERMINAR,'') AS INT)
SET @FECHAFINREPETIR=CONVERT(DATETIME,ISNULL(:fecharepetir,''),@CONVERTCODE)
SET @FRECUENCIA=CAST(ISNULL(:CADA,'') AS INT)
SELECT @DIASFRECUENCIA=(CASE WHEN (@RECURRENCIA=0 OR @RECURRENCIA=1) THEN '' WHEN @RECURRENCIA=2 THEN ISNULL(:DIASRECURRENCIA,'') ELSE ISNULL(:DIASMES,'') END )


SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE TKP = @TKP AND IDEMPRESA = @IDEMPRESA 

IF @IDPROSPECTO IS NULL
BEGIN
	 SELECT TOP 1 @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD=@IDOPORTUNIDAD
END 


UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) 
SET ULTIMOAVISO = CONVERT(DATETIME,GetDate()-1,@CONVERTCODE) 
WHERE IDUSUARIO = @IDUSUARIO

IF @IDOPORTUNIDAD = 0 SET @IDOPORTUNIDAD = NULL

SELECT @YAEXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.RECORDATORIOS WITH(NOLOCK) WHERE FECHAHORA > GETDATE()-1 AND IDPETICION != '' AND IDPETICION = @IDPETICION
SELECT @IDPROSPECTO, @IDUSUARIO, @FECHA, @RECORDATORIO, @IDOPORTUNIDAD, @IDPETICION,
	 @RECURRENCIA,@TIPOFIN,@FECHAFINREPETIR,@FRECUENCIA,@DIASFRECUENCIA,@IDPADRE
	 
	 
IF @YAEXISTE = 0 
BEGIN
     EXEC <#SESSION.DB/>.DBO.SP_NUEVO_RECORDATORIO @IDPROSPECTO, @IDUSUARIO, @FECHA, @RECORDATORIO, @IDOPORTUNIDAD, @IDPETICION,
	 @RECURRENCIA,@TIPOFIN,@FECHAFINREPETIR,@FRECUENCIA,@DIASFRECUENCIA,@IDPADRE
END
