//[session.idempresa|Untyped,tku|Text,session.db|Untyped,email_usuario|Text,nombre_usuario|Text,apellidos_usuario|Text,cambiarprecios|Text,iniciales_usuario|Text,usuario_avatar|Text,usuariomovil|Text,usuariotelefono|Text,usuariopuesto|Text,grupo_usuario|Text,crearempresas|Integer,crearplantillas|Integer,creardocumentos|Integer,hacerdescuentos|Integer,crearcomunicaciones|Integer,gmt|Integer,pais_usuario|Text,estado_usuario|Text,versistema|Integer,comisionusuario|Integer,contrasenia_usuario|Text,crearetiquetas|Integer,nivel_usuario|Integer,session.idusuario|Untyped,puedeexportar_guarda|Integer,]
--UPDATE
/*protegido*/

DECLARE @EMAIL VARCHAR(256)
DECLARE @AVATAR VARCHAR(1024)
DECLARE @CONTRASENIA VARCHAR(256)
DECLARE @IDUSUARIO INT 
DECLARE @NOMBRE VARCHAR(MAX)
DECLARE @APELLIDOS VARCHAR(MAX)
DECLARE @INICIALES VARCHAR(256)
DECLARE @PUEDEEXPORTAR_GUARDA INT 
DECLARE @NIVEL INT 
DECLARE @EMAIL_EXISTENTE INT
DECLARE @USUARIOMOVIL VARCHAR(64)
DECLARE @USUARIOTELEFONO VARCHAR(64)
DECLARE @USUARIOPUESTO VARCHAR(128) 
DECLARE @IDGRUPO INT
DECLARE @GMT INT
DECLARE @DEFAULT_PAIS VARCHAR(2)
DECLARE @DEFAULT_ESTADO  VARCHAR(4)
DECLARE @VERSISTEMA INT
DECLARE @CREARETIQUETAS INT 
DECLARE @CONTRASENA VARBINARY(256)
DECLARE @FUERZA_CONTRASENA INT
DECLARE @COMISION INT 
DECLARE @TKGRUPO VARCHAR(MAX)
DECLARE @TKU VARCHAR(MAX) 
DECLARE @IDEMPRESA INT 
/**/
DECLARE @CREAREMPRESAS INT
DECLARE @CREARPLANTILLAS INT
DECLARE @CREARDOCUMENTOS INT
DECLARE @HACERDESCUENTOS INT
DECLARE @CREARCOMUNICACIONES INT
DECLARE @CAMBIARPRECIOS INT

DECLARE @IDEMPRESAORIGEN INT
DECLARE @NNIVEL INT
SET @IDEMPRESAORIGEN = ''
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SET @TKU=ISNULL(:TKU,'')  
SELECT @IDUSUARIO=IDUSUARIO, @IDEMPRESAORIGEN=IDEMPRESA, @NNIVEL = NIVEL,  @FUERZA_CONTRASENA = FUERZA_CONTRASENA FROM <#SESSION.DB/>.DBO.USUARIOS WHERE TKU=@TKU

SET @EMAIL               = ISNULL(:EMAIL_USUARIO,'')

SET @NOMBRE              = ISNULL(:NOMBRE_USUARIO,'')
SET @APELLIDOS           = ISNULL(:APELLIDOS_USUARIO,'')
SET @INICIALES           = ISNULL(:INICIALES_USUARIO,'')
SET @AVATAR              = ISNULL(:USUARIO_AVATAR,'')
SET @USUARIOMOVIL        = ISNULL(:USUARIOMOVIL,'')
SET @USUARIOTELEFONO     = ISNULL(:USUARIOTELEFONO,'')
SET @USUARIOPUESTO       = ISNULL(:USUARIOPUESTO,'')
SET @TKGRUPO             = ISNULL(:GRUPO_USUARIO, '') 

SET @CREAREMPRESAS       = ISNULL(:CREAREMPRESAS,'')
SET @CREARPLANTILLAS     = ISNULL(:CREARPLANTILLAS,'')
SET @CREARDOCUMENTOS     = ISNULL(:CREARDOCUMENTOS,'')
SET @HACERDESCUENTOS     = ISNULL(:HACERDESCUENTOS,'')
SET @CREARCOMUNICACIONES = ISNULL(:CREARCOMUNICACIONES,'')
SET @CAMBIARPRECIOS      = ISNULL(:CAMBIARPRECIOS,'')

SELECT @IDGRUPO=IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE TK=@TKGRUPO

SET @GMT= ISNULL(:GMT,0)
SET @DEFAULT_PAIS = ISNULL(:PAIS_USUARIO,'')
SET @DEFAULT_ESTADO = ISNULL(:ESTADO_USUARIO,'')
SET @VERSISTEMA= ISNULL(:VERSISTEMA,0)
SET @COMISION = ISNULL(:COMISIONUSUARIO, 0)
SET @CONTRASENIA= ISNULL(:CONTRASENIA_USUARIO,'')
IF(@CONTRASENIA='') 
BEGIN
   SELECT @CONTRASENA=CONTRASENA FROM SALESUP_CT.DBO.USUARIOS WHERE IDUSUARIO=@IDUSUARIO 
END
ELSE  
BEGIN
  SELECT @FUERZA_CONTRASENA=<#SESSION.DB/>.DBO.ValidaFuerzaContrasenia(@CONTRASENIA)
  SET @CONTRASENA = HASHBYTES ('SHA1', @CONTRASENIA )
END

SET @CREARETIQUETAS= ISNULL(:CREARETIQUETAS,'')

SET @NIVEL = ISNULL(:NIVEL_USUARIO,0) 

IF  @NIVEL = 0 
BEGIN 
  SET @NIVEL = 1 
END

IF @IDUSUARIO = <#SESSION.IDUSUARIO/>
BEGIN
  SELECT @NIVEL = NIVEL FROM  <#SESSION.DB/>.dbo.USUARIOS WHERE IDUSUARIO=@IDUSUARIO 
END

SET @PUEDEEXPORTAR_GUARDA = ISNULL(:PUEDEEXPORTAR_GUARDA,0)


IF @IDEMPRESAORIGEN = @IDEMPRESA
BEGIN
   IF @TKU = '<#SESSION.TKU/>'
  BEGIN
  EXEC CONTROL.CONTROL.DBO.SP_ACTUALIZA_USUARIOS_CONTROL @NOMBRE, @APELLIDOS ,@INICIALES,@CONTRASENA,@EMAIL,@NNIVEL,@IDUSUARIO,@IDEMPRESA

    UPDATE SALESUP_CT.DBO.USUARIOS 
      SET NOMBRE=@NOMBRE,
      APELLIDOS=@APELLIDOS,
      INICIALES=@INICIALES,
      CONTRASENA=@CONTRASENA,
      EMAIL=@EMAIL
    WHERE IDEMPRESA=@IDEMPRESA AND IDUSUARIO=@IDUSUARIO
   
    UPDATE <#SESSION.DB/>.dbo.USUARIOS 
    SET 
      NOMBRE=@NOMBRE,
      APELLIDOS=@APELLIDOS,
      INICIALES=@INICIALES,
      CONTRASENA=@CONTRASENA,
      USUARIOMOVIL =@USUARIOMOVIL , 
      USUARIOTELEFONO = @USUARIOTELEFONO, 
      USUARIOPUESTO = @USUARIOPUESTO,
      EMAIL=@EMAIL,
      IDGRUPO=@IDGRUPO, 
      GMT=@GMT, 
      DEFAULT_PAIS = @DEFAULT_PAIS, 
      DEFAULT_ESTADO =@DEFAULT_ESTADO, 
      PUEDEEXPORTAR = @PUEDEEXPORTAR_GUARDA, 
      VERSISTEMA = @VERSISTEMA, 
      FUERZA_CONTRASENA=@FUERZA_CONTRASENA 
    WHERE IDEMPRESA=@IDEMPRESA AND IDUSUARIO=@IDUSUARIO
  END
  ELSE
  BEGIN
  EXEC CONTROL.CONTROL.DBO.SP_ACTUALIZA_USUARIOS_CONTROL @NOMBRE, @APELLIDOS ,@INICIALES,@CONTRASENA,@EMAIL,@NIVEL,@IDUSUARIO,@IDEMPRESA

   UPDATE SALESUP_CT.DBO.USUARIOS 
    SET NOMBRE=@NOMBRE,
    APELLIDOS=@APELLIDOS,
    INICIALES=@INICIALES,
    CONTRASENA=@CONTRASENA,
    EMAIL=@EMAIL,
    NIVEL=@NIVEL   
    WHERE IDEMPRESA=@IDEMPRESA AND IDUSUARIO=@IDUSUARIO
    UPDATE <#SESSION.DB/>.dbo.USUARIOS 
    SET 
      NOMBRE              = @NOMBRE,
      APELLIDOS           = @APELLIDOS,
      INICIALES           = @INICIALES,
      CONTRASENA          = @CONTRASENA,
      USUARIOMOVIL        = @USUARIOMOVIL , 
      USUARIOTELEFONO     = @USUARIOTELEFONO, 
      USUARIOPUESTO       = @USUARIOPUESTO,
      EMAIL               = @EMAIL,
      NIVEL               = @NIVEL ,
      IDGRUPO             = @IDGRUPO, 
      GMT                 = @GMT, 
      DEFAULT_PAIS        = @DEFAULT_PAIS, 
      DEFAULT_ESTADO      = @DEFAULT_ESTADO, 
      PUEDEEXPORTAR       = @PUEDEEXPORTAR_GUARDA, 
      VERSISTEMA          = @VERSISTEMA, 
      CREARETIQUETAS      = @CREARETIQUETAS,
      FUERZA_CONTRASENA   = @FUERZA_CONTRASENA, 
      COMISION            = @COMISION,
      CREAREMPRESAS       = @CREAREMPRESAS, 
      CREARPLANTILLAS     = @CREARPLANTILLAS, 
      CREARDOCUMENTOS     = @CREARDOCUMENTOS, 
      HACERDESCUENTOS     = @HACERDESCUENTOS, 
      CREARCOMUNICACIONES = @CREARCOMUNICACIONES, 
      CAMBIARPRECIOS      = @CAMBIARPRECIOS

    WHERE IDEMPRESA=@IDEMPRESA AND IDUSUARIO=@IDUSUARIO
  END
END




