//[correo|Integer,session.convertcode|Untyped,session.idempresa|Untyped,ejecutivo|Integer,buscar|Text,estado|Integer,session.idgrupo|Untyped,desde|Text,hasta|Text,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @CONVERTECODE INT, @ESTADO INT, @IDGRUPO INT
DECLARE @CORREO INT = ISNULL(:CORREO,0)
DECLARE @BUSCAR VARCHAR(256)
DECLARE @DESDE VARCHAR(128), @HASTA VARCHAR(128)
DECLARE @FILTRO VARCHAR(MAX) = ''
DECLARE @SQLTXT VARCHAR(MAX) = ''

SET @CONVERTECODE = <#SESSION.CONVERTCODE/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = ISNULL(:ejecutivo,0)
SET @BUSCAR = ISNULL(:BUSCAR,'')
SET @ESTADO = ISNULL(:ESTADO,0)
SET @IDGRUPO = <#SESSION.IDGRUPO/>

SET @DESDE = ISNULL(:DESDE,'')
SET @HASTA = ISNULL(:HASTA,'')

IF(@ESTADO <> 2)
	SET @FILTRO =  @FILTRO + ' AND ESTADO = ' + CAST(@ESTADO AS VARCHAR(5))

IF(@CORREO <> 2)
	SET @FILTRO =  @FILTRO + ' AND TIPO = ' + CAST(@CORREO AS VARCHAR(5))
	
IF(@IDUSUARIO <> 0)
	SET @FILTRO =  @FILTRO + ' AND UE.IDUSUARIO = ' + CAST(@IDUSUARIO AS VARCHAR(5))

IF(@BUSCAR <> '')
	SET @FILTRO =  @FILTRO + ' AND (UE.DESTINATARIO LIKE ''%'+@BUSCAR+'%'' OR UE.ASUNTO LIKE ''%'+@BUSCAR+'%'' OR P.NOMBRE LIKE ''%'+@BUSCAR+'%'' OR P.APELLIDOS LIKE ''%'+@BUSCAR+'%'' OR P.EMPRESA LIKE ''%'+@BUSCAR+'%'') '

IF(@DESDE <> '')
BEGIN
	IF(@DESDE <> @HASTA)
	 	SET @FILTRO =  @FILTRO + ' AND <#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@DESDE+''','+CAST(@CONVERTECODE AS VARCHAR(5))+') AND CONVERT(DATETIME,'''+@HASTA+''','+CAST(@CONVERTECODE AS VARCHAR(5))+') ' 
	ELSE
		SET @FILTRO =  @FILTRO + ' AND <#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHAHORA) = <#SESSION.DB/>.DBO.GETONLYDATE(CONVERT(DATETIME,'''+@HASTA+''','+CAST(@CONVERTECODE AS VARCHAR(5))+')) ' 
END

SET @SQLTXT = '
DECLARE @GMT INT
SET @GMT = CAST(''<#SESSION.GMT/>'' AS INT )
SELECT P.TKP,
CASE WHEN ISNULL(UE.IDPROSPECTO,0) > 0 THEN 1 ELSE 0 END AS esProspecto,
CASE WHEN ISNULL(UI.IDINBOX,0) > 0 and ISNULL(UI.IDCOLABORADOR,0) > 0 THEN 1 ELSE 0 END AS esColaborador, 
CASE WHEN ISNULL(UI.IDINBOX,0) > 0 and ISNULL(UI.IDCOLABORADOR,0) = 0 and ISNULL(UE.IDPROSPECTO,0) = 0 THEN 1 ELSE 0 END AS esResponderExterno, 
CASE WHEN ISNULL(UI.IDINBOX,0) = 0 and ISNULL(UI.IDCOLABORADOR,0) = 0 and ISNULL(UE.IDPROSPECTO,0) = 0 THEN 1 ELSE 0 END AS esNuevoExterno, 
ui.FROMNAME, US1.NOMBRE+'' ''+RTRIM(LTRIM(ISNULL(US1.APELLIDOS,'''')))+'' (''+RTRIM(LTRIM(ISNULL(US1.INICIALES,'''')))+'')'' AS COLABORADOR,
P.NOMBRE, P.APELLIDOS, P.EMPRESA, UE.*, U.INICIALES ,ISNULL(U.NOMBRE,'''')+'' ''+ISNULL(U.APELLIDOS,'''') AS NOMBRE_USUARIO, 
<#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHALEIDO) AS FECHA_LEIDO , <#SESSION.DB/>.DBO.GETONLYDATE(FECHA_ABIERTO) AS FECHAABIERTO,ABIERTO,
SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,UE.FECHAHORA) AS FECHA , <#SESSION.DB/>.DBO.ValidaEmail(UE.DESTINATARIO) as ESCORREO, P.ESCLIENTE
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0) UL,
<#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK) 
LEFT JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL AC WITH(NOLOCK)  ON AC.IDPROSPECTO = UE.IDPROSPECTO AND AC.IDPIEZA = UE.IDPIEZA
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK) ON P.IDPROSPECTO = UE.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_INBOX UI WITH(NOLOCK)  ON UI.IDINBOX = UE.IDINBOX
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS US1  WITH(NOLOCK) ON US1.IDUSUARIO = UI.IDCOLABORADOR  
JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK)  ON UE.IDUSUARIO = U.IDUSUARIO
WHERE UL.ID=U.IDUSUARIO 
AND U.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(5))+' 
AND U.IDUSUARIO = UE.IDUSUARIO 
AND UE.ESTADO <> 3 ' + @FILTRO + ' ORDER BY FECHAHORA DESC '

EXEC(@SQLTXT)


