//[session.idempresa|Untyped,idu|Text,fechaactual|Text,r|Integer,condiciontareasasignadas|Text,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @MESACTUAL VARCHAR(MAX), @IDREALIZADOR VARCHAR(MAX)
DECLARE @IDUSUARIO VARCHAR(MAX)
DECLARE @RANGO INT, @IDEMPRESA INT, @SESSIONIDUSUARIO INT, @ESTA INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONDICIONTAREASASIGNADAS VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDREALIZADOR = ISNULL(:IDU,'')
SET @MESACTUAL = ISNULL(:FechaActual,'')
SET @RANGO = ISNULL(:R,0)
SET @CONDICIONTAREASASIGNADAS=ISNULL(:CONDICIONTAREASASIGNADAS,'')

SET @SQL ='
DECLARE @FECHA DATETIME, @FINICIO DATETIME, @FFIN DATETIME
DECLARE @IDEMPRESA INT
DECLARE @IDREALIZADOR VARCHAR(MAX)

SET @IDEMPRESA = '+cast(@IDEMPRESA as varchar(1000))+'
SET @IDREALIZADOR = '''+@IDREALIZADOR+'''

IF '''+@MESACTUAL+''' != ''''
BEGIN
	SET @FECHA = CONVERT(DATETIME, '''+@MESACTUAL+''', 103 )
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, 5, @FECHA)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, 5, @FECHA)
	SET @FINICIO = DATEADD(dd, -6, @FINICIO)
	SET @FFIN = DATEADD(dd, 6, @FFIN)
END
ELSE
BEGIN
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, '+CAST(@RANGO AS VARCHAR(1000))+', NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, '+CAST(@RANGO AS VARCHAR(1000))+', NULL)
END


SELECT ''1'' AS Tarea, ''1'' AS TareaAsiganda, 3 AS Tipo, ''#27A0C9'' AS color, 
''T''+CAST(T.IDTAREA AS VARCHAR(MAX)) AS id, 
(CASE WHEN T.IDPADRE IS NOT NULL AND T.RECURRENCIA>0 THEN ''<i class="fa fa-share-square"></i><i class="fa fa-clock-o"></i> <span class="Iniciales">(''+ U.INICIALES+'')</span> '' + T.TITULO ELSE ''<i class="fa fa-share-square"></i> <span class="Iniciales">(''+ U.INICIALES+'')</span> '' + T.TITULO END) AS title,
''Pointer EventoTareasAsignadas T''+CONVERT(VARCHAR(MAX),U.IDUSUARIO) AS className, SALESUP_CT.DBO.Fecha(T.FECHA_VENCIMIENTO) AS start,
SALESUP_CT.dbo.ObtieneHora(T.FECHA_VENCIMIENTO) as Hora, CONVERT(VARCHAR(10), T.FECHA_VENCIMIENTO ,103) as Fecha ,
TS.COMENTARIO AS Descripcion, VT.Estado, FECHA_CREACION AS CreadoEl, P.NOMBRE + '' ''+ ISNULL(P.APELLIDOS,'''') AS Prospecto, 
U.NOMBRE + '' ''+ U.APELLIDOS AS Responsable, U.INICIALES AS Para, U.NOMBRE + '' ''+ U.APELLIDOS AS NomPara,
U1.INICIALES AS De, U1.NOMBRE + '' ''+ U1.APELLIDOS AS NomDe,
(CASE WHEN T.IDPADRE IS NOT NULL AND T.RECURRENCIA>0 THEN ''1'' ELSE '''' END) AS tPadre,
CASE WHEN T.FECHA_VENCIMIENTO <= GETDATE() THEN ''1'' ELSE '''' END AS Vencido,
P.IdCompania, CASE WHEN ISNULL(P.IDCOMPANIA,0)=0 THEN P.EMPRESA ELSE COM.EMPRESA END AS Empresa, U.IDUSUARIO AS Idu, T.TKTR AS Tk,
COM.TkCom, P.Tkp, P.IdProspecto, O.IdOportunidad, O.Tko, '''' AS EsCliente,''1'' AS Acciones, CONVERT(FLOAT, T.FECHA_VENCIMIENTO) AS DTF
FROM <#SESSION.DB/>.dbo.TAREAS T 
JOIN <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO TS ON TS.IDTAREASEGUIMIENTO = T.IDTAREASEGUIMIENTO
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = T.IDREALIZADOR
JOIN <#SESSION.DB/>.dbo.USUARIOS U1 ON U1.IDUSUARIO = T.IDINICIADOR
JOIN SALESUP_CT.dbo.V_TAREAS_ESTADOS VT ON VT.IDESTADO = T.IDESTADO 
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = T.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDOPORTUNIDAD = T.IDOPORTUNIDAD
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA 
WHERE 
U.IDEMPRESA = '+CAST(@IDEMPRESA  AS VARCHAR(1000))+'
'+@CONDICIONTAREASASIGNADAS+'
'
EXEC (@SQL)