//[idautoresponder|Integer,tkauto|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @IDAUTORESPONDER INT
DECLARE @IDEMPRESA INT
DECLARE @TKAUTO VARCHAR(128)

SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER,0)

SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SELECT AP.IDPIEZA ,CAST(AP.TKPI AS VARCHAR(128)) AS TKPI, AP.ASUNTO, @IDAUTORESPONDER  AS IDAUTORESPONDER 
FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS AP
JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS AU ON AP.IDAUTORESPONDER = AU.IDAUTORESPONDER
WHERE AP.IDAUTORESPONDER = @IDAUTORESPONDER AND AU.IDEMPRESA = @IDEMPRESA
ORDER BY ORDEN