//[amazon|Integer,archivo|Text,session.db|Untyped,idplantilla|Integer,session.idempresa|Untyped,tkpl|Text,]
--delete
DECLARE @AMAZON INT
DECLARE @HAYARCHIVO INT
DECLARE @ARCHIVOBUSCAR VARCHAR(8000)
DECLARE @IDPLANTILLA  INT
DECLARE @TKPL VARCHAR(128)

SET @AMAZON=CAST(ISNULL(:AMAZON,0) AS INT)
SET @ARCHIVOBUSCAR = ISNULL(:ARCHIVO,'')

SET @IDPLANTILLA =ISNULL(:IDPLANTILLA, 0)

SET @TKPL = ISNULL(:TKPL,'')
IF @TKPL != '' BEGIN SELECT @IDPLANTILLA=IDPLANTILLA FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE CAST(TK AS VARCHAR(128))  = @TKPL END


delete <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS where idplantilla = @IDPLANTILLA

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (28,@IDPLANTILLA,1,<#SESSION.IDEMPRESA/>,GETDATE())

IF @AMAZON!=0 
 BEGIN
  SELECT @HAYARCHIVO=COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND ARCHIVO LIKE @ARCHIVOBUSCAR
  IF (@HAYARCHIVO>0)
   BEGIN
     DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE ARCHIVO LIKE @ARCHIVOBUSCAR AND IDEMPRESA=<#SESSION.IDEMPRESA/> AND TIPO='PA'
   END  
 END 