//[idautoresponder|Integer,session.db|Untyped,session.idempresa|Untyped,tkauto|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/

DECLARE @IDAUTORESPONDER INT
DECLARE @TKAUTO VARCHAR(128)

SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER, 0)

SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END


SELECT IDUSUARIO AS RESPONSABLE FROM <#SESSION.DB/>.dbo.AUTORESPONDERS WHERE IDAUTORESPONDER = @IDAUTORESPONDER AND IDEMPRESA = <#SESSION.IDEMPRESA/>