//[session.idempresa|Untyped,idg|Integer,session.idusuario|Untyped,session.db|Untyped,session.idgrupo|Untyped,]
--SELECT
DECLARE @TABLA AS TABLE (ID INT)
DECLARE @IDEMPRESA INT, @IDGRUPO INT, @SIDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDGRUPO = ISNULL(:IDG,0)
SET @SIDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SELECT @IDGRUPO=(CASE WHEN @IDGRUPO=0 THEN CAST('<#SESSION.IDGRUPO/>' AS INT) ELSE @IDGRUPO END)

INSERT INTO @TABLA (ID)
SELECT A.ID FROM (
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,5,0)
  UNION
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,6,0)
  UNION
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,7,0)
) A 
GROUP BY A.ID



SELECT U.IDUSUARIO AS IdUsuario, (U.NOMBRE + ISNULL(' '+U.APELLIDOS,'')+  ' (' + LTRIM(RTRIM(U.INICIALES)) +')') AS Usuario
FROM <#SESSION.DB/>.DBO.USUARIOS U
JOIN @TABLA UA ON UA.ID = U.IDUSUARIO
WHERE U.ACTIVO = 1 AND U.IDEMPRESA = @IDEMPRESA AND U.IDGRUPO = @IDGRUPO
ORDER BY U.NOMBRE