//[session.idempresa|Untyped,session.idusuario|Untyped,contrasenia_usuario|Text,crearetiquetas|Integer,puedeexportar_guarda|Integer,email_usuario|Text,nombre_usuario|Text,apellidos_usuario|Text,iniciales_usuario|Text,nivel_usuario|Integer,grupo_usuario|Text,crearempresas|Integer,crearplantillas|Integer,creardocumentos|Integer,hacerdescuentos|Integer,crearcomunicaciones|Integer,session.db|Untyped,pais_usuario|Text,estado_usuario|Text,gmt|Integer,versistema|Integer,usuariotelefono|Text,usuariomovil|Text,usuariopuesto|Text,comisionusuario|Integer,CAMBIARPRECIOS|Integer,]
-- insert
/*protegido*/
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT, @IDCSS INT
DECLARE @AVATAR VARCHAR(1024)
DECLARE @PUEDEEXPORTAR_GUARDA INT
DECLARE @CONTRASENIA VARCHAR(128)
DECLARE @CREARETIQUETAS INT
DECLARE @EMAIL_USUARIO VARCHAR(128)
DECLARE @NOMBRE_USUARIO VARCHAR(128)
DECLARE @APELLIDOS_USUARIO VARCHAR(128)
DECLARE @INICIALES_USUARIO VARCHAR(10)
DECLARE @NIVEL_USUARIO INT
DECLARE @GRUPO_USUARIO INT
DECLARE @PAIS_USUARIO VARCHAR(10)
DECLARE @ESTADO_USUARIO VARCHAR(10)
DECLARE @GMT INT
DECLARE @VERSISTEMA INT
DECLARE @USUARIOTELEFONO VARCHAR(64)
DECLARE @USUARIOMOVIL VARCHAR(64)
DECLARE @USUARIOPUESTO VARCHAR(128)
DECLARE @CONTRASENA VARBINARY(256) 
DECLARE @FUERZA_CONTRASENA INT
DECLARE @COMISION INT
DECLARE @TKGRUPO VARCHAR(MAX)

/*Variables agregadas*/
DECLARE @CREAREMPRESAS INT
DECLARE @CREARPLANTILLAS INT
DECLARE @CREARDOCUMENTOS INT
DECLARE @HACERDESCUENTOS INT
DECLARE @CREARCOMUNICACIONES INT
DECLARE @CAMBIARPRECIOS INT
/*Variables agregadas*/

SET @IDCSS = 34
SET @AVATAR=''
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'
SET @IDUSUARIO='<#SESSION.IDUSUARIO/>'
SET @CONTRASENIA = :CONTRASENIA_USUARIO
SET @CONTRASENA = HASHBYTES ('SHA1', @CONTRASENIA )
SET @CREARETIQUETAS=ISNULL(:crearetiquetas,0)
SET @PUEDEEXPORTAR_GUARDA=ISNULL(:PUEDEEXPORTAR_GUARDA,1)
SET @EMAIL_USUARIO  = :EMAIL_USUARIO
SET @NOMBRE_USUARIO = :NOMBRE_USUARIO
SET @APELLIDOS_USUARIO = :APELLIDOS_USUARIO
SET @INICIALES_USUARIO = :INICIALES_USUARIO
SET @NIVEL_USUARIO = :NIVEL_USUARIO
SET @TKGRUPO=:GRUPO_USUARIO
/*VARIABLES SET*/
SET @CREAREMPRESAS = ISNULL(:CREAREMPRESAS,0) 
SET @CREARPLANTILLAS =ISNULL(:CREARPLANTILLAS,0)
SET @CREARDOCUMENTOS = ISNULL(:CREARDOCUMENTOS,0)
SET @HACERDESCUENTOS = ISNULL(:HACERDESCUENTOS,0)
SET @CREARCOMUNICACIONES = ISNULL(:CREARCOMUNICACIONES,0)
SET @CAMBIARPRECIOS      = ISNULL(:CAMBIARPRECIOS,0)
/*VARIABLES SET*/
SELECT @GRUPO_USUARIO = IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE TK=@TKGRUPO

SET @PAIS_USUARIO = :PAIS_USUARIO
SET @ESTADO_USUARIO = :ESTADO_USUARIO
SET @GMT = :GMT
SET @VERSISTEMA = ISNULL(:VERSISTEMA,0)
SET @USUARIOTELEFONO = :USUARIOTELEFONO
SET @USUARIOMOVIL = :USUARIOMOVIL
SET @USUARIOPUESTO = :USUARIOPUESTO

SELECT @FUERZA_CONTRASENA=<#SESSION.DB/>.DBO.ValidaFuerzaContrasenia(@CONTRASENIA)

SET @COMISION = ISNULL(:COMISIONUSUARIO, 0) 

IF  @PUEDEEXPORTAR_GUARDA = -1 SET  @PUEDEEXPORTAR_GUARDA = 0
  
DECLARE @EMAIL_EXISTENTE INT

SELECT @EMAIL_EXISTENTE = COUNT(*) FROM CONTROL.CONTROL.DBO.USUARIOS WHERE EMAIL = @EMAIL_USUARIO

IF @EMAIL_EXISTENTE = 0 
BEGIN
 DECLARE @AGREGADO INT
 DECLARE @TKU VARCHAR(64)
 SET @TKU = 'U-'+CONVERT([varchar](64),newid(),0)
 
 SELECT  TOP 1  @AGREGADO = IDUSUARIO FROM CONTROL.CONTROL.DBO.CONSECUTIVOS
 
 UPDATE CONTROL.CONTROL.DBO.CONSECUTIVOS SET  IDUSUARIO  = IDUSUARIO+1
  
 INSERT INTO CONTROL.CONTROL.DBO.USUARIOS(IDUSUARIO,IDEMPRESA,NOMBRE,APELLIDOS,CONTRASENA,INICIALES,EMAIL,NIVEL, ACTIVO, TIPO_ACCESO,TKU) 
 VALUES 
  (@AGREGADO,@IDEMPRESA,@NOMBRE_USUARIO,@APELLIDOS_USUARIO ,@CONTRASENA, LEFT(@INICIALES_USUARIO, 8),@EMAIL_USUARIO,@NIVEL_USUARIO,'1', 1,@TKU)

 INSERT INTO SALESUP_CT.DBO.USUARIOS(IDUSUARIO,IDEMPRESA,NOMBRE,APELLIDOS,CONTRASENA, INICIALES,EMAIL,NIVEL, ACTIVO, TKU) 
 VALUES 
  (@AGREGADO,@IDEMPRESA,@NOMBRE_USUARIO,@APELLIDOS_USUARIO ,@CONTRASENA, LEFT(@INICIALES_USUARIO, 8),@EMAIL_USUARIO,@NIVEL_USUARIO,'1', @TKU)

 SELECT TOP 1 @AGREGADO = IDUSUARIO FROM SALESUP_CT.DBO.USUARIOS WHERE NOMBRE = @NOMBRE_USUARIO AND EMAIL = @EMAIL_USUARIO AND INICIALES = LEFT(@INICIALES_USUARIO, 8) ORDER BY 1 DESC
 INSERT INTO <#SESSION.DB/>.DBO.USUARIOS(IDUSUARIO,IDEMPRESA,NOMBRE,APELLIDOS,CONTRASENA, INICIALES,
                                        EMAIL,NIVEL,IDGRUPO, DEFAULT_PAIS, DEFAULT_ESTADO, GMT,AVATAR, PUEDEEXPORTAR, VERSISTEMA, USUARIOTELEFONO, USUARIOMOVIL , USUARIOPUESTO, CREARETIQUETAS, TKU, IDCSS,FUERZA_CONTRASENA, COMISION, CREAREMPRESAS,CREARPLANTILLAS,CREARCOMUNICACIONES,CREARDOCUMENTOS,HACERDESCUENTOS,CAMBIARPRECIOS) 
VALUES 
  (@AGREGADO,@IDEMPRESA,@NOMBRE_USUARIO,@APELLIDOS_USUARIO ,@CONTRASENA, LEFT(@INICIALES_USUARIO, 8),
   @EMAIL_USUARIO,@NIVEL_USUARIO,@GRUPO_USUARIO, @PAIS_USUARIO, @ESTADO_USUARIO, @GMT,@AVATAR, @PUEDEEXPORTAR_GUARDA,@VERSISTEMA, @USUARIOTELEFONO, @USUARIOMOVIL, @USUARIOPUESTO, @CREARETIQUETAS, @TKU, @IDCSS,@FUERZA_CONTRASENA, @COMISION, @CREAREMPRESAS,@CREARPLANTILLAS,@CREARCOMUNICACIONES,@CREARDOCUMENTOS,@HACERDESCUENTOS,@CAMBIARPRECIOS);

--Se inserta como prospecto en la empresa de SalesUp! Referidos y Usuarios
DECLARE @IDETIQUETA INT
IF @NIVEL_USUARIO = 1 SET @IDETIQUETA = 1140
IF @NIVEL_USUARIO = 2 SET @IDETIQUETA = 1142 
IF @NIVEL_USUARIO = 3 SET @IDETIQUETA = 1143
DECLARE @EMPRESA VARCHAR(256)
SELECT @EMPRESA = COMPANIA FROM SALESUP_CT.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA
EXEC PLATON.SALESUP_DB4.dbo.SP_INSERTA_PROSPECTO_FCONTACTO @NOMBRE_USUARIO,@APELLIDOS_USUARIO ,@EMAIL_USUARIO,@EMPRESA,'','','','','',14051,0,3238,@PAIS_USUARIO,@ESTADO_USUARIO,'','','','','','','','','','','','','','','','','','','','','','','','','','','','',@IDETIQUETA,0,0,'2'
/*****   5/6/15   ********/ 

 
DECLARE @IDCREADOR INT
DECLARE @IDNUEVO INT
SET @IDCREADOR = @IDUSUARIO
SELECT TOP 1 @IDNUEVO = IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE NOMBRE = @NOMBRE_USUARIO AND EMAIL = @EMAIL_USUARIO AND INICIALES = LEFT(@INICIALES_USUARIO, 8) ORDER BY 1 DESC 
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_CONFIGURACION_FONDO_USUARIO @IDEMPRESA,@IDNUEVO
EXEC salesup_CT.dbo.SP_NOTIFICA_NUEVO_USUARIO @IDCREADOR, @IDNUEVO,@CONTRASENIA

  /*PROCEDIMIENTO AGREGAR CONFIGURACION COLUMNAS*/ 

  SET @IDEMPRESA = CAST(@IDEMPRESA AS INT)
  EXEC <#SESSION.DB/>.DBO.SP_AGREGA_COLUMAS_USUARIO @IDEMPRESA, @IDNUEVO
  
  EXEC <#SESSION.DB/>.DBO.SP_AGREGA_COLUMNAS_CATALOGOS @IDEMPRESA, @IDNUEVO
  EXEC <#SESSION.DB/>.DBO.SP_AGREGA_COLUMNAS_PRODUCTOS_USUARIO_NUEVO @IDEMPRESA, @IDNUEVO
  EXEC <#SESSION.DB/>.DBO.SP_AGREAR_INBOXTABS_USUARIOS @IDNUEVO
  
END


INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDUSUARIO) VALUES(1,@AGREGADO)