//[session.idusuario|Untyped,idc|Integer,comentario|Text,session.db|Untyped,]
--INSERT

DECLARE @IDCITA INT, @SESSIONIDUSUARIO INT
DECLARE @COMENTARIO VARCHAR(MAX), @LTINVITADOSPROSPECTOS VARCHAR(MAX)

SET @SESSIONIDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDCITA = CAST(ISNULL(:IDC,0) AS INT)
SET @COMENTARIO = :COMENTARIO
SET @LTINVITADOSPROSPECTOS = ''

SELECT @LTINVITADOSPROSPECTOS = @LTINVITADOSPROSPECTOS + CONVERT(VARCHAR(MAX),IDPERSONA) + ',' 
FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS WHERE IDCITA = @IDCITA AND TIPOPERSONA = 1

INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, TIPO_SEGUIMIENTO, FECHAHORA, COMENTARIO, SISTEMA, IDRELACIONADO )
SELECT SplitValue, @SESSIONIDUSUARIO, 6, GETDATE(), @COMENTARIO, 0, @IDCITA FROM SALESUP_CT.dbo.Split(@LTINVITADOSPROSPECTOS,',')
