//[sexo|Text,nombre|Text,sp_version|Text,apellidos|Text,correo|Text,empresa|Text,puesto|Text,web|Text,ppaginaweb|Text,telefono|Text,telefono1|Text,telefono2|Text,movil|Text,comentarios|Text,idproducto|Text,producto|Text,precio|Text,cantidad|Text,subtotal|Text,total|Text,idempresa|Integer,idusuario|Integer,idorigen|Integer,pais|Text,ppais|Text,estado|Text,pestado|Text,refiere|Text,ciudad|Text,pciudad|Text,direccion1|Text,calle|Text,idetiqueta|Integer,idetiqueta1|Integer,idetiqueta2|Integer,campo1|Text,campo2|Text,campo3|Text,campo4|Text,campo5|Text,campo6|Text,campo7|Text,campo8|Text,campo9|Text,campo10|Text,campo11|Text,campo12|Text,campo13|Text,campo14|Text,campo15|Text,campo16|Text,campo17|Text,campo18|Text,campo19|Text,campo20|Text,campo21|Text,campo22|Text,campo23|Text,campo24|Text,campo25|Text,campo26|Text,campo27|Text,campo28|Text,campo29|Text,campo30|Text,campo31|Text,campo32|Text,la_bd|Untyped,]
--INSERT
DECLARE @P_NOMBRE VARCHAR(128) 
DECLARE @P_APELLIDOS VARCHAR(128)
DECLARE @P_CORREO VARCHAR(256)
DECLARE @P_EMPRESA VARCHAR(512)
DECLARE @P_PUESTO VARCHAR(128)
DECLARE @P_WEB VARCHAR(1024)
DECLARE @P_TELEFONO VARCHAR(128)
DECLARE @P_MOVIL VARCHAR(128)
DECLARE @P_COMENTARIOS varchar(8000)
DECLARE @P_IDEMPRESA INT
DECLARE @P_IDUSUARIO INT
DECLARE @P_IDORIGEN INT
DECLARE @P_PAIS VARCHAR(2)
DECLARE @P_ESTADO VARCHAR(4)
DECLARE @P_REFIERE VARCHAR(1024)
DECLARE @P_CIUDAD VARCHAR(128)
DECLARE @P_DIRECCION1 VARCHAR(512)
DECLARE @SP_VERSION VARCHAR(8)
DECLARE @P_IDETIQUETA1 INT
DECLARE @P_IDETIQUETA2 INT
DECLARE @P_IDETIQUETA3 INT
DECLARE @P_CAMPO1 VARCHAR(1024)
DECLARE @P_CAMPO2 VARCHAR(1024)
DECLARE @P_CAMPO3 VARCHAR(1024)
DECLARE @P_CAMPO4 VARCHAR(1024)
DECLARE @P_CAMPO5 VARCHAR(1024)
DECLARE @P_CAMPO6 VARCHAR(1024)
DECLARE @P_CAMPO7 VARCHAR(1024)
DECLARE @P_CAMPO8 VARCHAR(1024)
DECLARE @P_CAMPO9 VARCHAR(1024)
DECLARE @P_CAMPO10 VARCHAR(1024)
DECLARE @P_CAMPO11 VARCHAR(1024)
DECLARE @P_CAMPO12 VARCHAR(1024)
DECLARE @P_CAMPO13 VARCHAR(1024)
DECLARE @P_CAMPO14 VARCHAR(1024)
DECLARE @P_CAMPO15 VARCHAR(1024)
DECLARE @P_CAMPO16 VARCHAR(1024)
DECLARE @P_CAMPO17 VARCHAR(1024)
DECLARE @P_CAMPO18 VARCHAR(1024)
DECLARE @P_CAMPO19 VARCHAR(1024)
DECLARE @P_CAMPO20 VARCHAR(1024)
DECLARE @P_CAMPO21 VARCHAR(1024)
DECLARE @P_CAMPO22 VARCHAR(1024)
DECLARE @P_CAMPO23 VARCHAR(1024)
DECLARE @P_CAMPO24 VARCHAR(1024)
DECLARE @P_CAMPO25 VARCHAR(1024)

DECLARE @P_CAMPO26 VARCHAR(1024)
DECLARE @P_CAMPO27 VARCHAR(1024)
DECLARE @P_CAMPO28 VARCHAR(1024)
DECLARE @P_CAMPO29 VARCHAR(1024)
DECLARE @P_CAMPO30 VARCHAR(1024)
DECLARE @P_CAMPO31 VARCHAR(1024)
DECLARE @P_CAMPO32 VARCHAR(1024)

DECLARE @JSON VARCHAR(MAX)
SET @JSON=ISNULL(:SEXO, '')
SELECT @JSON='{"SEXO":"'+@JSON+'"}'

SET @P_NOMBRE =  SALESUP_CT.DBO.PREPARACADENA(:NOMBRE)
SET @SP_VERSION = :SP_VERSION 
SET @P_APELLIDOS  =  SALESUP_CT.DBO.PREPARACADENA(:APELLIDOS )
SET @P_CORREO = :CORREO 
SET @P_EMPRESA =SALESUP_CT.DBO.PREPARACADENA(:EMPRESA )
SET @P_PUESTO =SALESUP_CT.DBO.PREPARACADENA(:PUESTO )
SET @P_WEB =SALESUP_CT.DBO.PREPARACADENA(ISNULL(:WEB,''))+SALESUP_CT.DBO.PREPARACADENA(ISNULL(:PPAGINAWEB,'')) 
SET @P_TELEFONO = ISNULL(LTRIM(RTRIM(:TELEFONO)), '')
SET @P_TELEFONO = @P_TELEFONO  + ISNULL(LTRIM(RTRIM(:TELEFONO1)), '')
SET @P_TELEFONO = @P_TELEFONO  + ISNULL(LTRIM(RTRIM(:TELEFONO2)), '')
SET @P_MOVIL = :MOVIL 
SET @P_COMENTARIOS = SALESUP_CT.DBO.PREPARACADENA(:COMENTARIOS)

DECLARE @IDPRODUCTO VARCHAR(MAX) = ISNULL(:IDPRODUCTO, '')
DECLARE @PRODUCTO   VARCHAR(MAX) = ISNULL(:PRODUCTO, '')
DECLARE @PRECIO     VARCHAR(MAX) = ISNULL(:PRECIO, '')
DECLARE @CANTIDAD   VARCHAR(MAX) = ISNULL(:CANTIDAD, '')
DECLARE @SUBTOTAL   VARCHAR(MAX) = ISNULL(:SUBTOTAL, '')
DECLARE @TOTAL      VARCHAR(MAX) = ISNULL(:TOTAL, '')

IF (@IDPRODUCTO !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> IdProducto: '+ @IDPRODUCTO
IF (@PRODUCTO !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> Producto: '+ @PRODUCTO
IF (@PRECIO !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> Precio: $'+ @PRECIO
IF (@CANTIDAD !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> Cantidad: '+ @CANTIDAD
IF (@SUBTOTAL !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> Subtotal: $'+ @SUBTOTAL
IF (@TOTAL !='')
  SET @P_COMENTARIOS =  @P_COMENTARIOS + '<br /> Total: $ '+ @TOTAL






SET @P_idempresa= CAST(:IDEMPRESA  AS INT)
SET @P_IDUSUARIO=CAST(:IDUSUARIO  AS INT)
SET @P_IDORIGEN= CAST(:IDORIGEN  AS INT)
SET @P_PAIS =ISNULL(:PAIS,'')+ ISNULL(:PPAIS,'')

SET @P_ESTADO =ISNULL(:ESTADO, '') +ISNULL(:PESTADO, '')
SET @P_REFIERE = LEFT(:REFIERE, 1024)
SET @P_CIUDAD =ISNULL(:CIUDAD,'')+ ISNULL(:PCIUDAD,'')


SET @P_DIRECCION1 =SALESUP_CT.DBO.PREPARACADENA(:DIRECCION1)+ SALESUP_CT.DBO.PREPARACADENA(ISNULL(:CALLE, ''))
SET @P_idetiqueta1=CAST(:IDETIQUETA  AS INT)
SET @P_idetiqueta2=CAST(:IDETIQUETA1  AS INT)
SET @P_idetiqueta3=CAST(:IDETIQUETA2  AS INT)

IF (:CAMPO1 <>'') SET @P_CAMPO1 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO1,0) 
IF (:CAMPO2 <>'') SET @P_CAMPO2 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO2,0)
IF (:CAMPO3 <>'') SET @P_CAMPO3 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO3,0)
IF (:CAMPO4 <>'') SET @P_CAMPO4 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO4,0)
IF (:CAMPO5 <>'') SET @P_CAMPO5 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO5,1)
IF (:CAMPO6 <>'') SET @P_CAMPO6 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO6,1)
IF (:CAMPO7 <>'') SET @P_CAMPO7 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO7,1)
IF (:CAMPO8 <>'') SET @P_CAMPO8 = SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(:CAMPO8,1)


IF (:CAMPO9 <>'') SET @P_CAMPO9 = SALESUP_CT.dbo.NormalizaFecha(:CAMPO9 )
IF (:CAMPO10 <>'') SET @P_CAMPO10 = SALESUP_CT.dbo.NormalizaFecha(:CAMPO10 )
IF (:CAMPO11 <>'') SET @P_CAMPO11 = SALESUP_CT.dbo.NormalizaFecha(:CAMPO11 )
IF (:CAMPO12 <>'') SET @P_CAMPO12 = SALESUP_CT.dbo.NormalizaFecha(:CAMPO12 )

SET @P_CAMPO13 =:CAMPO13 
SET @P_CAMPO14 =:CAMPO14 
SET @P_CAMPO15 = :CAMPO15 
SET @P_CAMPO16 = :CAMPO16 
SET @P_CAMPO17 = :CAMPO17 
SET @P_CAMPO18 = :CAMPO18 
SET @P_CAMPO19 = :CAMPO19 
SET @P_CAMPO20 = :CAMPO20 
IF (:CAMPO21 <>'') SET @P_CAMPO21 = :CAMPO21 
IF (:CAMPO22 <>'') SET @P_CAMPO22 = :CAMPO22 
IF (:CAMPO23 <>'') SET @P_CAMPO23 = :CAMPO23 
IF (:CAMPO24 <>'') SET @P_CAMPO24 = :CAMPO24 
IF (:CAMPO25 <>'') SET @P_CAMPO25 = :CAMPO25 

SET @P_CAMPO26 = :CAMPO26 
SET @P_CAMPO27 = :CAMPO27 
SET @P_CAMPO28 = :CAMPO28 
SET @P_CAMPO29 = :CAMPO29 
SET @P_CAMPO30 = :CAMPO30 
SET @P_CAMPO31 = :CAMPO31 
SET @P_CAMPO32 = :CAMPO32 


IF @P_NOMBRE  IS NULL SET @P_NOMBRE  = ''
IF @P_APELLIDOS  IS NULL SET @P_APELLIDOS  = ''
IF @P_CORREO  IS NULL SET @P_CORREO  = ''
IF @P_EMPRESA  IS NULL SET @P_EMPRESA  = ''
IF @P_PUESTO  IS NULL SET @P_PUESTO  = ''
IF @P_WEB  IS NULL SET @P_WEB  = ''
IF @P_TELEFONO  IS NULL SET @P_TELEFONO  = ''
IF @P_MOVIL  IS NULL SET @P_MOVIL  = ''
IF @P_COMENTARIOS  IS NULL SET @P_COMENTARIOS  = ''
IF @P_IDEMPRESA  IS NULL SET @P_IDEMPRESA  = 0
IF @P_IDUSUARIO  IS NULL SET @P_IDUSUARIO  = 0
IF @P_IDORIGEN  IS NULL SET @P_IDORIGEN  = 0
IF @P_PAIS  IS NULL SET @P_PAIS  = ''
IF @P_ESTADO  IS NULL SET @P_ESTADO  = ''
IF @P_CAMPO13  IS NULL SET @P_CAMPO13  = ''
IF @P_CAMPO14  IS NULL SET @P_CAMPO14  = ''
IF @P_CAMPO15  IS NULL SET @P_CAMPO15  = ''
IF @P_CAMPO16  IS NULL SET @P_CAMPO16  = ''
IF @P_CAMPO17  IS NULL SET @P_CAMPO17  = ''
IF @P_CAMPO18  IS NULL SET @P_CAMPO18  = ''
IF @P_CAMPO19  IS NULL SET @P_CAMPO19  = ''
IF @P_CAMPO20  IS NULL SET @P_CAMPO20  = ''
IF @P_CAMPO26  IS NULL SET @P_CAMPO26  = ''
IF @P_CAMPO27  IS NULL SET @P_CAMPO27  = ''
IF @P_CAMPO28  IS NULL SET @P_CAMPO28  = ''
IF @P_CAMPO29  IS NULL SET @P_CAMPO29  = ''
IF @P_CAMPO31  IS NULL SET @P_CAMPO30  = ''
IF @P_CAMPO31  IS NULL SET @P_CAMPO31  = ''
IF @P_CAMPO32  IS NULL SET @P_CAMPO32  = ''
IF @P_REFIERE  IS NULL SET @P_REFIERE  = ''
IF @P_CIUDAD  IS NULL SET @P_CIUDAD  = ''
IF @P_DIRECCION1  IS NULL SET @P_DIRECCION1  = ''
IF @P_IDETIQUETA1  IS NULL SET @P_IDETIQUETA1 = 0
IF @P_IDETIQUETA2  IS NULL SET @P_IDETIQUETA2 = 0
IF @P_IDETIQUETA3  IS NULL SET @P_IDETIQUETA3 = 0
IF @SP_VERSION  IS NULL SET @SP_VERSION = ''



IF (@P_idempresa !=0)
BEGIN
EXEC <#LA_BD/>.dbo.SP_INSERTA_PROSPECTO_FCONTACTO_JSON @P_NOMBRE ,
@P_APELLIDOS ,
@P_CORREO ,
@P_EMPRESA ,
@P_PUESTO ,
@P_WEB ,
@P_TELEFONO ,
@P_MOVIL ,
@P_COMENTARIOS ,
@P_IDEMPRESA ,
@P_IDUSUARIO ,
@P_IDORIGEN ,
@P_PAIS ,
@P_ESTADO ,
@P_CAMPO1,
@P_CAMPO2 ,
@P_CAMPO3 ,
@P_CAMPO4 ,
@P_CAMPO5 ,
@P_CAMPO6 ,
@P_CAMPO7 ,
@P_CAMPO8 ,
@P_CAMPO9 ,
@P_CAMPO10 ,
@P_CAMPO11 ,
@P_CAMPO12 ,
@P_CAMPO13 ,
@P_CAMPO14 ,
@P_CAMPO15 ,
@P_CAMPO16 ,
@P_CAMPO17 ,
@P_CAMPO18 ,
@P_CAMPO19 ,
@P_CAMPO20 ,
@P_CAMPO21 ,
@P_CAMPO22 ,
@P_CAMPO23 ,
@P_CAMPO24 ,
@P_CAMPO25 ,
@P_CAMPO26 ,
@P_CAMPO27 ,
@P_CAMPO28 ,
@P_CAMPO29 ,
@P_CAMPO30 ,
@P_CAMPO31 ,
@P_CAMPO32 ,
@P_REFIERE ,
@P_CIUDAD ,
@P_DIRECCION1 ,
@P_IDETIQUETA1,
@P_IDETIQUETA2,
@P_IDETIQUETA3,
@SP_VERSION, 
@JSON

END



