//[session.idusuario|Untyped,idu|Text,fechaactual|Text,r|Integer,session.idempresa|Untyped,condicioncobrosauditar|Text,session.db|Untyped,]
--SELECT 
/*protegido*/
DECLARE @MESACTUAL VARCHAR(MAX), @IDUSUARIO VARCHAR(MAX)
DECLARE @RANGO INT, @IDEMPRESA INT, @SESSIONIDUSUARIO INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CERO VARCHAR(1000)
DECLARE @CONDICIONCOBROSAUDITAR VARCHAR(MAX) 
SET @SESSIONIDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDUSUARIO = ISNULL(:IDU,'')
SET @MESACTUAL = ISNULL(:FechaActual,'')
SET @RANGO = ISNULL(:R,0)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @CERO='00:00'
SET @CONDICIONCOBROSAUDITAR = ISNULL(:CONDICIONCOBROSAUDITAR,'')

SET @SQL ='
DECLARE @FECHA DATETIME, @FINICIO DATETIME, @FFIN DATETIME
DECLARE @IDUSUARIO VARCHAR(MAX)
DECLARE @IDEMPRESA INT

SET @IDUSUARIO = '''+@IDUSUARIO+'''
SET @IDEMPRESA = '+cast(@IDEMPRESA as varchar(1000))+'

IF '''+@MESACTUAL+''' != ''''
BEGIN
	SET @FECHA = CONVERT(DATETIME, '''+@MESACTUAL+''', 103 )
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, 5, @FECHA)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, 5, @FECHA)
	SET @FINICIO = DATEADD(dd, -6, @FINICIO)
	SET @FFIN = DATEADD(dd, 6, @FFIN)
END
ELSE
BEGIN
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, '+CAST(@RANGO AS VARCHAR(1000))+', NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, '+CAST(@RANGO AS VARCHAR(1000))+', NULL)
END



SELECT 
''1'' as CobrosAuditar, 5 AS Tipo, ''#dc0f24'' as color, ''#ffffff'' as textColor, ''CA''+CAST(VC.IDVENTA AS VARCHAR(MAX)) AS id,
SALESUP_CT.DBO.Fecha(V.FECHAHORA) as start, ''true'' as allDay, ''Venta por auditar'' as title, ''Pointer CobrosAuditar'' AS className,
CASE WHEN SALESUP_CT.dbo.ObtieneHora(V.FECHAHORA) = '''+@CERO+''' THEN ''-'' ELSE SALESUP_CT.dbo.ObtieneHora(V.FECHAHORA) END AS Hora, 
CONVERT(VARCHAR(10), V.FECHAHORA,103) as Fecha,
P.NOMBRE + '' ''+ ISNULL(P.APELLIDOS,'''') AS Prospecto, 
U.NOMBRE + '' ''+ U.APELLIDOS AS Responsable, U.INICIALES AS Para, U.NOMBRE + '' ''+ U.APELLIDOS AS NomPara,
CASE WHEN ISNULL(P.IDCOMPANIA,0)=0 THEN P.EMPRESA ELSE COM.EMPRESA END AS Empresa, 
O.Concepto, ''Auditar'' as Estado, O.IDOPORTUNIDAD as ido, V.IDVENTA AS Idv, V.IDVENTA AS IdVenta, V.Tkv,
COM.TkCom, P.Tkp, P.IdProspecto, O.IdOportunidad, O.Tko, 
CASE P.EsCliente WHEN 1 THEN ''1'' ELSE '''' END AS EsCliente,'''' AS Acciones, CONVERT(FLOAT, V.FECHAHORA) AS DTF
FROM 
<#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG,
<#SESSION.DB/>.DBO.USUARIOS U, 
<#SESSION.DB/>.DBO.VENTAS V, 
<#SESSION.DB/>.DBO.VENTAS_COBROS VC, 
<#SESSION.DB/>.DBO.PROSPECTOS P LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA, 
<#SESSION.DB/>.DBO.OPORTUNIDADES O,
<#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos ('+CAST(@SESSIONIDUSUARIO AS VARCHAR(1000))+',3,0) UP
WHERE 
	UG.IDEMPRESA = '+cast(@IDEMPRESA as varchar(1000))+' 
AND UG.AUDITADO = 1 
AND UG.IDUSUARIOGRUPO = U.IDGRUPO 
AND V.IDUSUARIO = U.IDUSUARIO 
AND VC.IDVENTA=V.IDVENTA 
AND VC.AUDITADO = 0 
AND VC.PAGADO = 1 
AND U.IDEMPRESA = P.IDEMPRESA 
AND O.IDPROSPECTO = P.IDPROSPECTO 
AND V.IDOPORTUNIDAD = O.IDOPORTUNIDAD
AND UP.ID = U.IDUSUARIO 
'+@CONDICIONCOBROSAUDITAR+'

GROUP BY VC.IDVENTA,V.FECHAHORA,P.TELEFONO,O.IDOPORTUNIDAD,P.NOMBRE,P.APELLIDOS,P.EMPRESA,U.INICIALES,O.CONCEPTO, 
U.NOMBRE,U.APELLIDOS , v.idventa, COM.EMPRESA, COM.IDCOMPANIA, P.IDCOMPANIA, V.Tkv, COM.TkCom, P.Tkp, P.IdProspecto, O.IdOportunidad, O.Tko, P.EsCliente

ORDER BY V.FECHAHORA DESC
'

EXEC (@SQL)