//[tipocorreo|Text,ruta_doc|Text,pesokb|Text,session.db|Untyped,descripcion|Text,contenido|Text,asunto|Text,session.idusuario|Untyped,compartircon|Integer,session.idempresa|Untyped,]
declare @IDULTIMO INT
DECLARE @DESCRIPCION VARCHAR(255), @CONTENIDO VARCHAR(MAX), @ASUNTO VARCHAR(255)
DECLARE @RUTA_DOC VARCHAR(8000)
DECLARE @ADJUNTOS VARCHAR(8000)
DECLARE @PESOS VARCHAR(8000)


DECLARE @TIPOCORREO INT
SET @TIPOCORREO = ISNULL(:TIPOCORREO,0)

IF @TIPOCORREO = 0 
   SET @TIPOCORREO = 1

SET @ADJUNTOS = :RUTA_DOC
SET @PESOS=:PESOKB

SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/')
SET @DESCRIPCION = <#SESSION.DB/>.dbo.PreparaCadena(:DESCRIPCION)
SET @CONTENIDO = <#SESSION.DB/>.dbo.PreparaCadena(:CONTENIDO)
SET @ASUNTO = <#SESSION.DB/>.dbo.PreparaCadena(:ASUNTO)

SET @ASUNTO = REPLACE(@ASUNTO, '"', '&quot;')
SET @DESCRIPCION = REPLACE(@DESCRIPCION, '"', '&quot;')
IF @CONTENIDO IS NULL SET @CONTENIDO = ''
INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS (IDUSUARIO, DESCRIPCION, CUERPO, ANEXOS, NOMBRE_ARCHIVO, NOMBRE_ARCHIVO_REAL, ASUNTO,compartircon, TIPOCORREO, IDEMPRESA) 
VALUES (<#SESSION.IDUSUARIO/>,@DESCRIPCION,@CONTENIDO,@RUTA_DOC,'','', @ASUNTO ,:compartircon, @TIPOCORREO, <#SESSION.IDEMPRESA/>)


SELECT @IDULTIMO = @@IDENTITY

UPDATE <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
SET 
NOMBRE_ARCHIVO = <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_PLANTILLAS (ANEXOS),
NOMBRE_ARCHIVO_REAL = <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PLANTILLAS (ANEXOS) 
WHERE IDPLANTILLA = @IDULTIMO


EXEC <#SESSION.DB/>.DBO.SP_INGRESA_ARCHIVOS_CONTROL_EMPRESAS_ARCHIVOS_AMAZON <#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,@ADJUNTOS,@PESOS,'PA'
