//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
	  SELECT U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
	  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO 
	   WHERE  (UP.COMPARTIRCON=U.IDGRUPO OR UP.COMPARTIRCON=-1) and U.IDEMPRESA=<#SESSION.IDEMPRESA/> 
	  GROUP BY U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION
	 -- ORDER BY ORDEN ASC 
 

