//[imagen|Text,aquien|Integer,session.nivel|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,session.db|Untyped,]
--update

DECLARE @FONDO VARCHAR(MAX)
DECLARE @aQuien INT, @NIVEL INT, @IDUSUARIO INT, @IDCSS INT, @IDGRUPO INT, @IDEMPRESA INT
SET @FONDO = isnull(:IMAGEN,'')
SET @aQuien = CAST(isnull(:aQuien,0) AS INT)
SET @NIVEL = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)

SELECT @IDCSS = U.IDCSS FROM <#SESSION.DB/>.DBO.USUARIOS U WHERE U.IDUSUARIO = @IDUSUARIO

IF LEN(@FONDO) > 0 BEGIN UPDATE <#SESSION.DB/>.dbo.USUARIOS SET FONDO = @FONDO WHERE IDUSUARIO = @IDUSUARIO END

IF LEN(@FONDO) = 0
BEGIN
	 SELECT @FONDO = FONDO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
	 UPDATE <#SESSION.DB/>.DBO.USUARIOS SET FONDO = NULL, CAMBIARFONDO = 1 
	 WHERE IDEMPRESA = @IDEMPRESA AND FONDO = @FONDO
	 UPDATE <#SESSION.DB/>.dbo.USUARIOS SET FONDO = @FONDO, FONDO_SETTING=@aQuien WHERE IDUSUARIO = @IDUSUARIO
END

IF @NIVEL = 1
BEGIN

	 IF @aQuien = 2
	 BEGIN
	 	  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET IDCSS = @IDCSS , FONDO = @FONDO
		  WHERE IDEMPRESA = @IDEMPRESA AND IDGRUPO = @IDGRUPO
		  
		  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET CAMBIARFONDO = 0 
		  WHERE IDEMPRESA = @IDEMPRESA AND IDGRUPO = @IDGRUPO AND IDUSUARIO != @IDUSUARIO AND NIVEL > 1
		  
	 END
	 IF @aQuien = 3
	 BEGIN
	 	  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET IDCSS = @IDCSS , FONDO = @FONDO
		  WHERE IDEMPRESA = @IDEMPRESA
		  
		  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET CAMBIARFONDO = 0  
		  WHERE IDEMPRESA = @IDEMPRESA AND NIVEL > 1
	 END
END

IF @NIVEL = 2
BEGIN
	 IF @aQuien = 2
	 BEGIN
	 	  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET IDCSS = @IDCSS , FONDO = @FONDO
		  WHERE IDEMPRESA = @IDEMPRESA AND IDGRUPO = @IDGRUPO
		  
		  UPDATE <#SESSION.DB/>.DBO.USUARIOS SET CAMBIARFONDO = 0 
		  WHERE IDEMPRESA = @IDEMPRESA AND IDGRUPO = @IDGRUPO AND IDUSUARIO != @IDUSUARIO AND NIVEL = 3
	 END
END
