//[idusuario|Integer,session.idempresa|Untyped,idplantilla|Integer,session.db|Untyped,tkpl|Text,tku|Text,]
--SELECT
DECLARE @IDUSUARIO INT 
DECLARE @IDEMPRESA INT 
DECLARE @IDGRUPO INT 
DECLARE @IDPLANTILLA  INT
DECLARE @TKPL VARCHAR(128)
DECLARE @TKU VARCHAR(128)

SET @IDUSUARIO = ISNULL(:IDUSUARIO, 0)
SET @IDEMPRESA =ISNULL('<#SESSION.IDEMPRESA/>', 0)
SET @IDPLANTILLA =ISNULL(:IDPLANTILLA, 0)

SET @TKPL = ISNULL(:TKPL,'')
IF @TKPL != '' BEGIN SELECT @IDPLANTILLA=IDPLANTILLA FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE CAST(TK AS VARCHAR(128))  = @TKPL END

SET @TKU = ISNULL(:TKU,'')
IF @TKU != '' BEGIN SELECT @IDUSUARIO=IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE CAST(TKU AS VARCHAR(128)) = @TKU  END



SELECT @IDGRUPO=IDGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS   WHERE IDUSUARIO=@IDUSUARIO AND IDEMPRESA=@IDEMPRESA

DECLARE @TEMP AS TABLE(IDUSUARIO INT, NOMBRE VARCHAR(MAX), IDGRUPO INT,    GRUPO VARCHAR(100))
INSERT INTO @TEMP(IDUSUARIO,NOMBRE, IDGRUPO,  GRUPO)
SELECT U.IDUSUARIO, U.INICIALES,  U.IDGRUPO,   UG.GRUPO  
FROM <#SESSION.DB/>.DBO.USUARIOS U, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG
WHERE U.IDEMPRESA=@IDEMPRESA AND U.IDGRUPO=@IDGRUPO AND UG.IDUSUARIOGRUPO=U.IDGRUPO

SELECT LTRIM(RTRIM(UP.DESCRIPCION)) AS DESCRIPCION,ISNULL(T.IDGRUPO, U.IDGRUPO) AS IDGRUPO, UPPER(ISNULL (T.NOMBRE,U.INICIALES)) AS NOMBRE, U.INICIALES, T.NOMBRE,
	   LEN(CONVERT(VARCHAR(MAX), ISNULL(REPLACE(CONVERT(VARCHAR(MAX), ANEXOS), CHAR(10)+CHAR(13) , ''),''))) as TieneAnexos,
       CASE WHEN TIPOCORREO = 1 THEN 'Correo' ELSE 'SMS' END AS ELTIPO,UP.TIPOCORREO,
	   CASE WHEN UP.COMPARTIRCON=-1 THEN 'Empresa' WHEN UP.COMPARTIRCON=0  THEN 'Nadie'	ELSE T.GRUPO END AS COMPARTIR, UP.COMPARTIRCON,
	   replace(up.asunto,'"','&quot;') as asunto, UP.IDPLANTILLA, UP.TK, UP.TKM,
	   UP.IDUSUARIO , UP.CUERPO, U.NIVEL
			 
FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
LEFT JOIN @TEMP T ON T.IDUSUARIO=UP.IDUSUARIO 
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO =UP.IDUSUARIO
WHERE UP.IDEMPRESA=@IDEMPRESA  
AND ( UP.IDUSUARIO=@IDUSUARIO OR UP.COMPARTIRCON=-1 OR (UP.COMPARTIRCON=<#session.idgrupo/>  aND UP.IDUSUARIO IN (SELECT IDUSUARIO FROM @TEMP)))
AND UP.IDPLANTILLA = @IDPLANTILLA

ORDER BY DESCRIPCION ASC
