//[session.idempresa|Untyped,sin_eliminado|Text,session.db|Untyped,ordenamiento|Text,]
--SELECT 
/*protegido*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @IDEMPRESA INT
DECLARE @ORDENAMIENTO VARCHAR(1000)
DECLARE @SIN_ELIMINADO VARCHAR(1000)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @ORDENAMIENTO=ISNULL(:ORDENAMIENTO, '1')
SET @SIN_ELIMINADO=ISNULL(:SIN_ELIMINADO, '') 
SELECT @ORDENAMIENTO = (CASE WHEN @ORDENAMIENTO IS NULL THEN '1' ELSE @ORDENAMIENTO END)
SELECT @SIN_ELIMINADO = (CASE WHEN @SIN_ELIMINADO IS NULL THEN '' ELSE @SIN_ELIMINADO END)

SET @SQL='
select U.IDUSUARIO, U.*,
FUERZA_CONTRASENA AS FUERZACONTRASENIA,SMS_ENVIADOS, U.TKU, U.TKM,
  (CASE WHEN NIVEL=3 THEN ''Ejecutivo de ventas''  WHEN NIVEL=2 THEN ''Gerente de Ventas''  WHEN (NIVEL=1 AND VERSISTEMA=0) THEN ''Auditor''  WHEN NIVEL=1 THEN ''Administrador del sistema''  END) AS TITULONIVEL,   
  (CASE WHEN U.ACTIVO=1 THEN 1 ELSE '''' END) AS ACTIVO,
  (CASE WHEN U.MAILCONFIG=1 THEN 1 ELSE '''' END) AS MAILCONFIG,
  (CASE WHEN U.PUEDEEXPORTAR=1 THEN 1 ELSE '''' END) AS PUEDEEXPORTAR,
  U.VERSISTEMA, U.EMAIL,SMS_ASIGNADOS, (u.apellidos + '', '' + u.nombre) as INTEGRANTE, g.grupo, UPPER(U.INICIALES) AS INICIALES 
from 
<#SESSION.DB/>.DBO.usuarios u, 
<#SESSION.DB/>.DBO.usuarios_grupos g
where u.IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(1000))+' '+@SIN_ELIMINADO+' and
u.idgrupo = g.idusuariogrupo ORDER BY '+CAST(@ORDENAMIENTO AS VARCHAR(MAX))

EXEC (@SQL)