//[idpieza|Integer,idetiqueta|Integer,idautoresponder|Integer,tk|Text,session.db|Untyped,session.idempresa|Untyped,tkpi|Text,tkauto|Text,]
--select
DECLARE @IDPIEZA INT
DECLARE @IDETIQUETA INT
DECLARE @IDAUTORESPONDER INT

DECLARE @TK VARCHAR(128)
DECLARE @TKPI VARCHAR(128)
DECLARE @TKAUTO VARCHAR(128)

SET @IDPIEZA=ISNULL(:IDPIEZA,0)
SET @IDETIQUETA=ISNULL(:IDETIQUETA,0)
SET @IDAUTORESPONDER=ISNULL(:IDAUTORESPONDER,0)


SET @TK = ISNULL(:TK,'')
IF @TK != '' BEGIN SELECT @IDETIQUETA=IDETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE TK = @TK AND IDEMPRESA = <#SESSION.IDEMPRESA/> END

SET @TKPI = ISNULL(:TKPI,'')
IF @TKPI != '' BEGIN SELECT @IDPIEZA=IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE CAST(TKPI AS VARCHAR(128))  = @TKPI END

SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END

IF @IDPIEZA = 0
SELECT 0 AS IDPIEZA, 0 AS ORDEN, @IDETIQUETA AS IDETIQUETA,@IDAUTORESPONDER AS IDAUTORESPONDER
ELSE
SELECT 
--AP.* , 
<#SESSION.DB/>.DBO.fnCountChar(AP.NOMBRE_ARCHIVO_REAL,',') AS TOTALFILES,
AP.IDAUTORESPONDER, AP.IDPIEZA,
(CASE WHEN RTRIM(LTRIM(REPLACE(REPLACE(CAST(AP.anexos AS VARCHAR(max)),CHAR(10),''),CHAR(13),'')))='' THEN '' ELSE REPLACE(REPLACE(REPLACE(CAST(AP.anexos AS VARCHAR(max)),CHAR(10)+CHAR(10),CHAR(10)),CHAR(10),','),CHAR(13),'')END) as anexos,

 AP.NOMBRE_ARCHIVO, AP.ENVIAR_TIEMPO, AP.ESTADO, AP.ASUNTO , AP.CUERPO, ISNULL(AP.ORDEN,999999999) AS ORDEN,AP.NOMBRE_ARCHIVO_REAL,
AU.IDAUTORESPONDER, AU.IDETIQUETA  ,
    (
       SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS WHERE IDAUTORESPONDER = AP.IDAUTORESPONDER AND ESTADO = 1
			AND IDPIEZA IN 
			(
				SELECT IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL WHERE IDPIEZA = AP.IDPIEZA AND IDETIQUETA=@IDETIQUETA
			)  
    ) AS ENVIADOS,
	(
	   SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS WHERE IDAUTORESPONDER = AP.IDAUTORESPONDER AND ESTADO = 0 AND ERRORES > 0
			AND IDPIEZA IN 
			(
				SELECT IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL WHERE IDPIEZA = AP.IDPIEZA AND IDETIQUETA=@IDETIQUETA
			)
    )AS NOENVIADOS,
    (
	 SELECT COUNT(*) 
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS PE
	 LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = PE.IDPROSPECTO AND DESCARTADO = 0
	 LEFT JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS AU ON AU.IDAUTORESPONDER = @IDAUTORESPONDER
	 WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND PE.IDETIQUETA = @IDETIQUETA
	 AND ( ( AU.ESPROSPECTO = 1 AND P.ESOPORTUNIDAD = 0 AND P.ESCLIENTE = 0) OR (AU.ESOPORTUNIDAD = 1 AND P.ESOPORTUNIDAD = 1) OR (AU.ESCLIENTE= 1 AND P.ESCLIENTE = 1))
	 )AS TOTAL,
	 (
	  SELECT COUNT(*)
      FROM <#SESSION.DB/>.DBO.PROSPECTOS_ETIQUETAS PE
      LEFT JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS AU ON AU.IDAUTORESPONDER = @IDAUTORESPONDER
	  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = PE.IDPROSPECTO AND DESCARTADO = 0 
    	AND P.IDPROSPECTO NOT IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL WHERE IDPIEZA = AP.IDPIEZA AND IDETIQUETA=@IDETIQUETA)
	  WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND PE.IDETIQUETA = @IDETIQUETA
	  AND ( ( AU.ESPROSPECTO = 1 AND P.ESOPORTUNIDAD = 0 AND P.ESCLIENTE = 0) OR (AU.ESOPORTUNIDAD = 1 AND P.ESOPORTUNIDAD = 1) OR (AU.ESCLIENTE= 1 AND P.ESCLIENTE = 1))

	 ) AS RESTAN2
FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS AP
JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS AU ON AP.IDAUTORESPONDER = AU.IDAUTORESPONDER
JOIN <#SESSION.DB/>.DBO.ETIQUETAS ETI ON ETI.IDETIQUETA = AU.IDETIQUETA
WHERE AP.IDAUTORESPONDER = @IDAUTORESPONDER AND AU.IDEMPRESA = <#SESSION.IDEMPRESA/>  AND IDPIEZA = @IDPIEZA
ORDER BY ORDEN