//[session.db|Untyped,idpeticion|Text,copiaoculta|Text,plantillas|Integer,ruta_doc|Text,session.idusuario|Untyped,idoportunidad|Integer,destinatario|Text,concopia|Text,asunto|Text,contenido|Text,estado|Integer,idprospecto|Integer,session.convertcode|Untyped,]
--INSERT
/*protegido*/

DECLARE @IDPETICION VARCHAR(100)
SET @IDPETICION = :IDPETICION

DECLARE @IDUSUARIO INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD,0)
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>

IF @IDOPORTUNIDAD = 0 BEGIN SET @IDOPORTUNIDAD = NULL END

IF( (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.USUARIOS_EMAILS WHERE FECHAHORA > GETDATE()-1 AND IDPETICION !='' AND IDPETICION = @IDPETICION) = 0)
BEGIN

DECLARE @IDULTIMO INT, @IDPLANTILLA INT, @CORREOSENVIADOS INT
DECLARE @COMENTARIO VARCHAR(8000), @RUTA_DOC VARCHAR(8000), @ADJUNTOS VARCHAR(8000)
DECLARE @CCO VARCHAR(8000), @ADJANEXOS VARCHAR(8000)



SET @CCO = :COPIAOCULTA

SET @IDPLANTILLA = ISNULL(:PLANTILLAS,0)
SET @ADJUNTOS = ISNULL(:RUTA_DOC,'') 
SET @RUTA_DOC=''

SELECT @CCO=@CCO + ','+ ISNULL(CCO,'') FROM <#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG WHERE IDUSUARIO=@IDUSUARIO
SELECT @ADJANEXOS = CAST(ANEXOS AS VARCHAR(8000)) FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA

IF (@ADJUNTOS='')
BEGIN
	 SET @RUTA_DOC=''
END
ELSE
BEGIN
	 SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/')
END
 
IF (RTRIM(LTRIM(@ADJANEXOS))!='') BEGIN SET @RUTA_DOC = @RUTA_DOC + CHAR(10)+CHAR(13)+@ADJANEXOS END

DECLARE @DESTINATARIO VARCHAR(MAX)
DECLARE @CONCOPIA VARCHAR(MAX), @ASUNTO VARCHAR(MAX), @CONTENIDO VARCHAR(MAX)
DECLARE @ESTADO INT

SET @DESTINATARIO = ISNULL(:DESTINATARIO,'') 
SET @CONCOPIA = ISNULL(:CONCOPIA,'') 
SET @ASUNTO = ISNULL(:ASUNTO,'') 
SET @CONTENIDO = ISNULL(:CONTENIDO,'') 
SET @ESTADO = ISNULL(:ESTADO,0) 


INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_EMAILS WITH(ROWLOCK) (IDUSUARIO , TIPO , DESTINATARIO, CC , BCC, ASUNTO, CUERPO, ANEXOS, ESTADO,IDPROSPECTO,IDPETICION)
VALUES (@IDUSUARIO,0,@DESTINATARIO, @CONCOPIA, @CCO, @ASUNTO, @CONTENIDO, @RUTA_DOC, @ESTADO, @IDPROSPECTO, @IDPETICION)

SELECT @IDULTIMO = @@IDENTITY

EXEC <#SESSION.DB/>.DBO.SP_INSERTA_LECTURA_CORREO @IDULTIMO, @ESTADO, '<#SESSION.DB/>'

 

SET @COMENTARIO = 'Correo enviado: ' + @ASUNTO

INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, IDEMAIL, TIPO_SEGUIMIENTO, COMENTARIO, SISTEMA)
VALUES(@IDPROSPECTO, @IDOPORTUNIDAD,@IDUSUARIO, @IDULTIMO, 1, @COMENTARIO , 1)

SELECT @CORREOSENVIADOS = CORREOSENVIADOS FROM <#SESSION.DB/>.DBO.USUARIOS WITH(NOLOCK) WHERE IDUSUARIO = @IDUSUARIO
SET @CORREOSENVIADOS = @CORREOSENVIADOS + 1
UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET CORREOSENVIADOS = @CORREOSENVIADOS WHERE IDUSUARIO = @IDUSUARIO


EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO,15,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, '',''


END -- del validador de IDPETICION
ELSE 
  INSERT INTO SALESUP_CT.dbo.LOG(IDU, IDP, IDO, TEXTO) VALUES (@IDUSUARIO, @IDPROSPECTO, @IDOPORTUNIDAD, 'Duplicidad de correo')


