//[tku|Text,session.idempresa|Untyped,idusuario|Integer,session.db|Untyped,]
--SELECT 


DECLARE @TKU VARCHAR(MAX)
DECLARE @IDEMPRESA INT 
DECLARE @TKGRUPO VARCHAR(MAX) 
DECLARE @IDGRUPO INT 
DECLARE @IDUSUARIO INT 

SET @TKU=ISNULL(:TKU, '') 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @IDUSUARIO=ISNULL(:IDUSUARIO, 0) 


SELECT U.EMAIL, U.NOMBRE, U.APELLIDOS, U.INICIALES, U.NIVEL, U.ACTIVO,  U.DEFAULT_PAIS, U.DEFAULT_ESTADO, U.GMT, U.USUARIOTELEFONO, U.USUARIOMOVIL, U.USUARIOPUESTO,
U.PUEDEEXPORTAR, U.VERSISTEMA, U.TKU, U.CREARETIQUETAS, ISNULL(U.COMISION, 0) LACOMISION, CAST(UG.TK AS VARCHAR(MAX)) AS IDGRUPO, U.CREAREMPRESAS,U.CREARPLANTILLAS,U.CREARCOMUNICACIONES,U.CREARDOCUMENTOS,U.HACERDESCUENTOS, U.CAMBIARPRECIOS
FROM <#SESSION.DB/>.DBO.USUARIOS  U
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG  ON UG.IDUSUARIOGRUPO=U.IDGRUPO
WHERE TKU=@TKU  OR IDUSUARIO=@IDUSUARIO
