//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 

/*PROTEGIDO*/

DECLARE @IDEMPRESA INT 
SET @IDEMPRESA='<#SESSION.IDEMPRESA/>'


SELECT IDUSUARIOGRUPO, GRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE IDEMPRESA=@IDEMPRESA

ORDER BY GRUPO ASC
