//[session.db|Untyped,idpieza|Integer,idautoresponder|Integer,]
--insert

DECLARE @IDPIEZA INT = ISNULL(:IDPIEZA,0)
DECLARE @IDAUTORESPONDER INT = ISNULL(:IDAUTORESPONDER,0)
DECLARE @ARRIBA INT = 1

EXEC <#SESSION.DB/>.DBO.SP_AUTORESPONDER_PIEZA_LUGAR @IDPIEZA,@IDAUTORESPONDER,@ARRIBA
