//[session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--select
DECLARE @TABLA AS TABLE (ID INT)
DECLARE @IDEMPRESA INT, @SIDUSUARIO INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @SIDUSUARIO = <#SESSION.IDUSUARIO/>
INSERT INTO @TABLA (ID)
SELECT A.ID FROM (
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,5,0)
  UNION
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,6,0)
  UNION
  SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (@SIDUSUARIO,7,0)
) A 
GROUP BY A.ID

SELECT UG.IDUSUARIOGRUPO AS IdGrupo, UG.Grupo , CAST(UG.TK AS VARCHAR(64)) AS tkg
FROM <#SESSION.DB/>.dbo.USUARIOS_GRUPOS UG 
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDGRUPO = UG.IDUSUARIOGRUPO AND U.IDEMPRESA = UG.IDEMPRESA
JOIN @TABLA UA ON UA.ID = U.IDUSUARIO
WHERE UG.IDEMPRESA = @IDEMPRESA
GROUP BY UG.IDUSUARIOGRUPO, UG.GRUPO , UG.TK
ORDER BY UG.GRUPO