//[session.idusuario|Untyped,session.db|Untyped,]
--select
DECLARE @IDUSUARIO INT, @VENTANA_TAREAS INT, @VENTANA_RECORDATORIOS INT, @VENTANA_CITAS INT
DECLARE @VENTANA_COBROS_AUDITAR INT, @VENTANA_COBROS_PENDIENTES INT 

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @VENTANA_RECORDATORIOS = 410
SET @VENTANA_TAREAS = 411
SET @VENTANA_CITAS = 412
SET @VENTANA_COBROS_PENDIENTES = 414
SET @VENTANA_COBROS_AUDITAR = 415

SELECT <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, @VENTANA_RECORDATORIOS) AS SQLRECORDATORIOS,
<#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, @VENTANA_TAREAS) AS SQLTAREAS,
<#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, @VENTANA_CITAS) AS SQLCITAS, 
<#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, @VENTANA_COBROS_PENDIENTES) AS SQLCOBROSPENDIENTES,
<#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO (@IDUSUARIO, @VENTANA_COBROS_AUDITAR) AS SQLCOBROSAUDITAR
