//[archivo|Text,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @ARCHIVO VARCHAR(MAX)
SET @ARCHIVO = ISNULL(:ARCHIVO,'')
SELECT IDUSUARIOARCHIVO FROM <#SESSION.DB/>.DBO.USUARIOS_ARCHIVOS WHERE ARCHIVO =@ARCHIVO