//[ltAdjuntosReenviar|Text,idinbox|Integer,idinboxmaster|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,correode|Text,destinatario|Text,asunto|Text,contenido|Text,totalprospectos|Integer,copiaoculta|Text,concopia|Text,idplantilla|Integer,idprospecto|Text,plantillas|Integer,ruta_doc|Text,idoportunidad|Text,programarcorreo|Integer,pcfecha|Text,pchora|Text,tkp|Text,tko|Text,session.db|Untyped,ltarchivosagregados|Text,ltarchivosagregadosprospecto|Text,enviarestearchivo|Text,estado|Integer,]
--INSERT
/*PROTEGIDO*/
DECLARE @IDULTIMO INT , @CORREOSENVIADOS INT, @IDPLANTILLA INT , @LIMITE INT , @TOTALPROSPECTOS INT
DECLARE @COMENTARIO VARCHAR(MAX), @RUTA_DOC VARCHAR(MAX),@ADJUNTOS VARCHAR(MAX), @ADJANEXOS VARCHAR(MAX), @FechaProgramada varchar(32), @Destinatario varchar(MAX)
DECLARE @IDOPORTUNIDAD VARCHAR(MAX), @CC VARCHAR(MAX), @CCO VARCHAR(MAX), @ASUNTO  VARCHAR(MAX), @CONTENIDO VARCHAR(MAX) , @PROSPECTOS VARCHAR(MAX) , @correoDe VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @ProgramarCorreo INT, @CONVERTCODE INT
DECLARE @dt_FechaProgramada datetime
DECLARE @IDINBOX INT, @IDINBOXMASTER INT

DECLARE @TKP VARCHAR(MAX), @TKO VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME


SET @IDINBOX = ISNULL(:idInbox,0)
SET @IDINBOXMASTER = ISNULL(:idInboxMaster,0)

SET @IDEMPRESA 	 = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO 	 = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

set @correoDe = :correoDe
SET @Destinatario = ISNULL(:Destinatario,'')
SET @ASUNTO = SALESUP_CT.DBO.PreparaCadena(ISNULL(:ASUNTO,''))
SET @CONTENIDO = SALESUP_CT.DBO.PreparaCadena(ISNULL(:CONTENIDO,''))
SET @TOTALPROSPECTOS = ISNULL(:TOTALPROSPECTOS,0)
SET @LIMITE = 80 
SET @CCO = ISNULL(:COPIAOCULTA,'')
SET @CC = ISNULL(:CONCOPIA,'')
SET @IDPLANTILLA = ISNULL(:idplantilla,'')
SET @PROSPECTOS = ISNULL(:IDPROSPECTO,'')
SET @IDPLANTILLA = ISNULL(:PLANTILLAS,0)
SET @ADJUNTOS = ISNULL(:RUTA_DOC,'') 
SET @RUTA_DOC = ''
SET @IDOPORTUNIDAD = LTRIM(RTRIM(ISNULL(:IDOPORTUNIDAD,'')))
SET @ProgramarCorreo = ISNULL(:ProgramarCorreo,0)
SET @FechaProgramada = ISNULL(:pcfecha,'') +' '+ ISNULL(:pchora,'') 

SET @FECHAHOY = GETDATE()

SET @TKP = ISNULL(:TKP,'')
SET @TKO = ISNULL(:TKO,'')

IF @TKP != '' BEGIN SET @PROSPECTOS = CAST(<#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) AS VARCHAR(MAX)) END

IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = CAST(<#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) AS VARCHAR(MAX)) END


SELECT @ADJANEXOS = CAST(ANEXOS AS VARCHAR(8000)) FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA

IF @ProgramarCorreo = 1 BEGIN SET @dt_FechaProgramada = CONVERT(DATETIME, @FechaProgramada, @CONVERTCODE) END

IF (@ADJUNTOS='') BEGIN SET @RUTA_DOC='' END ELSE BEGIN SET @RUTA_DOC = REPLACE('/'+@ADJUNTOS,',',  CHAR(10)+CHAR(13)+'/') END

/*agregando anexos del reenviar*/
declare @ltAdjuntosReenviar varchar(max)
SET @ltAdjuntosReenviar = ISNULL(:ltAdjuntosReenviar,'')
IF (@ltAdjuntosReenviar!='') BEGIN SET @RUTA_DOC = @RUTA_DOC + REPLACE(@ltAdjuntosReenviar, '|', CHAR(10)+CHAR(13) ) END

IF (RTRIM(LTRIM(@ADJANEXOS))!='') BEGIN SET @RUTA_DOC = @RUTA_DOC + CHAR(10)+CHAR(13)+@ADJANEXOS END

IF(@IDOPORTUNIDAD = '0' OR @IDOPORTUNIDAD='') BEGIN SET @IDOPORTUNIDAD = NULL END

/*ARCHIVOS AGREGADOS DESDE MI NUBE*/
DECLARE @LtArchivosAgregados VARCHAR(MAX), @LtArchivosAgregadosDelProspecto VARCHAR(MAX)
DECLARE @ArchivosAgregados VARCHAR(MAX), @EnviarEsteArchivo VARCHAR(MAX), @ArchivosAgregadosDelProspecto VARCHAR(MAX)

SET @LtArchivosAgregados = ISNULL(:LtArchivosAgregados,'')
SET @LtArchivosAgregadosDelProspecto = ISNULL(:LtArchivosAgregadosProspecto,'')
SET @EnviarEsteArchivo = ISNULL(:EnviarEsteArchivo,'')
SET @ArchivosAgregados = ''
SET @ArchivosAgregadosDelProspecto = ''

/*ARCHIVOS DE LA NUBE*/
SELECT @ArchivosAgregados = @ArchivosAgregados + '/'+SPLITVALUE + CHAR(10) + CHAR(13) FROM <#SESSION.DB/>.dbo.Split(@LtArchivosAgregados,'|')
IF @ArchivosAgregados != '' BEGIN SET @RUTA_DOC = @ArchivosAgregados + @RUTA_DOC + CHAR(10)+CHAR(13) END

/*ARCHIVOS DEL PROSPECTO */
SELECT @ArchivosAgregadosDelProspecto = @ArchivosAgregadosDelProspecto + '/'+SPLITVALUE + CHAR(10) + CHAR(13) FROM <#SESSION.DB/>.dbo.Split(@LtArchivosAgregadosDelProspecto,'|')
IF @ArchivosAgregadosDelProspecto != '' BEGIN SET @RUTA_DOC = @ArchivosAgregadosDelProspecto + @RUTA_DOC + CHAR(10)+CHAR(13) END

/*UN SOLO ARCHIVO DEL PROSPECTO*/
IF @EnviarEsteArchivo != '' BEGIN SET @RUTA_DOC = '/'+@EnviarEsteArchivo + CHAR(10)+CHAR(13) + @RUTA_DOC  END
   
DECLARE @TABLA AS TABLE (ID INT IDENTITY, IDPROSPECTO INT, CORREO VARCHAR(1000), IDOPORTUNIDAD INT)
DECLARE @TOTAL INT, @CONT INT, @IDP INT, @IDOPOR INT, @ESTADO INT 
DECLARE @CORREOP VARCHAR(1000)
 
SET @TOTAL = 0
SET @CONT = 1
SET @IDP = 0
SET @IDOPOR = 0
SET @CORREOP = ''
SET @ESTADO = ISNULL(:ESTADO,0)

IF (@IDOPORTUNIDAD IS NULL)
BEGIN
  INSERT INTO @TABLA (IDPROSPECTO, CORREO) SELECT IDPROSPECTO,CORREO 
  from <#SESSION.DB/>.DBO.PROSPECTOS 
  where IDPROSPECTO in (select splitvalue from <#SESSION.DB/>.DBO.Split(@PROSPECTOS,',')) and  correo is not null
END
ELSE
BEGIN
  INSERT INTO @TABLA (IDPROSPECTO, CORREO, IDOPORTUNIDAD)
  SELECT P.IDPROSPECTO, P.CORREO, O.IDOPORTUNIDAD from <#SESSION.DB/>.DBO.PROSPECTOS P ,<#SESSION.DB/>.DBO.OPORTUNIDADES O 
  WHERE P.IDPROSPECTO in (select splitvalue from <#SESSION.DB/>.DBO.Split(@PROSPECTOS,',')) AND O.IDPROSPECTO=P.IDPROSPECTO
  AND O.IDOPORTUNIDAD IN  (select splitvalue from <#SESSION.DB/>.DBO.Split(@IDOPORTUNIDAD,',')) 
END

SELECT @TOTAL=COUNT(*) FROM @TABLA

WHILE @CONT<=@TOTAL
BEGIN
	SELECT @CORREOSENVIADOS = CORREOSENVIADOS 
	FROM <#SESSION.DB/>.DBO.USUARIOS WITH(NOLOCK) 
	WHERE IDUSUARIO = @IDUSUARIO
	
	SELECT @IDP = IDPROSPECTO, @CORREOP = CORREO, @IDOPOR = CAST(IDOPORTUNIDAD AS INT) 
	FROM @TABLA 
	WHERE ID = @CONT
	
	IF @Destinatario != '' BEGIN SET @CORREOP = @Destinatario  END
	
	IF @IDPLANTILLA != 0 AND @TOTALPROSPECTOS > 1
    BEGIN
   	  SELECT 
      @CONTENIDO = <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(CUERPO, @IDP, @IDUSUARIO, @IDEMPRESA, @IDOPOR),
      @ASUNTO = <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(ASUNTO, @IDP, @IDUSUARIO, @IDEMPRESA, @IDOPOR)
	  FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
	  WHERE IDPLANTILLA = @IDPLANTILLA
    END 
    
	SET @RUTA_DOC = REPLACE (@RUTA_DOC,'\r \n',CHAR(13)+CHAR(10))
	
    INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_EMAILS WITH(ROWLOCK) 
	       (IDUSUARIO , TIPO , DESTINATARIO, CC , BCC, ASUNTO, CUERPO, ANEXOS, ESTADO, IDPROSPECTO, IDOPORTUNIDAD, FECHAPROGRAMADA, IDINBOX, idUsuarioCorreo)
    VALUES (@IDUSUARIO, 0, @CORREOP, @CC, @CCO, @ASUNTO, @CONTENIDO, @RUTA_DOC, 1, @IDP, @IDOPOR, @dt_FechaProgramada, @IDINBOX, @correoDe)

	SELECT TOP 1 @IDULTIMO = IDEMAIL FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS WHERE IDUSUARIO = @IDUSUARIO AND ASUNTO = @ASUNTO ORDER BY IDEMAIL DESC

	SET @COMENTARIO = 'Correo enviado - ' + @ASUNTO
	SET @ESTADO = 0
	/*IF (@CORREOSENVIADOS<= @LIMITE) BEGIN SET @ESTADO = 0 END ELSE BEGIN SET @ESTADO = 2 END*/
	
	IF @ProgramarCorreo = 1 
	BEGIN 
	  SET @ESTADO = 3 
	  SET @COMENTARIO = 'Correo programado ('+@FechaProgramada+') - '+ @ASUNTO
	END
	
	EXEC <#SESSION.DB/>.DBO.SP_INSERTA_LECTURA_CORREO @IDULTIMO, @ESTADO, '<#SESSION.DB/>'

    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, IDEMAIL, TIPO_SEGUIMIENTO, COMENTARIO, SISTEMA)
	VALUES(@IDP, @IDOPOR, @IDUSUARIO, @IDULTIMO, 1, @COMENTARIO , 1)
	EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @PROSPECTOS,@FECHAHOY,1
	IF @ProgramarCorreo = 0 
	BEGIN
	  SET @CORREOSENVIADOS = @CORREOSENVIADOS + 1
	  UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET CORREOSENVIADOS = @CORREOSENVIADOS WHERE IDUSUARIO = @IDUSUARIO
	  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, 15, @IDP, @CONVERTCODE, '', ''
	  EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS 1, @IDUSUARIO
	END
	
	IF @IDINBOX > 0
	BEGIN
		 UPDATE <#SESSION.DB/>.DBO.USUARIOS_INBOX 
		 SET IDINBOXMASTER = @IDINBOXMASTER, IDEMAIL = @IDULTIMO
		 WHERE IDINBOX = @IDINBOX AND IDUSUARIO = @IDUSUARIO
		 
		 DECLARE @CONVERSACIONES INT
		 SELECT @CONVERSACIONES = COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_INBOX WITH (NOLOCK) WHERE IDINBOXMASTER = @IDINBOXMASTER
		 SELECT @CONVERSACIONES = @CONVERSACIONES+COUNT(*) FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS WITH (NOLOCK) WHERE IDINBOX = @IDINBOXMASTER
		 UPDATE <#SESSION.DB/>.DBO.USUARIOS_INBOX WITH(ROWLOCK) SET CONVERSACIONES = @CONVERSACIONES WHERE IDINBOXMASTER = @IDINBOXMASTER 
	END
	
	SET @CONT = @CONT + 1
END

 
