//[session.idusuario|Untyped,session.db|Untyped,]
--delete
DECLARE @IDUSUARIO INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA IN (410,411,412,414,415)