//[idprospecto|Integer,idoportunidad|Integer,tipo|Integer,session.db|Untyped,tkp|Text,tko|Text,session.idempresa|Untyped,]
--select
DECLARE @TIPO INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT, @IDEMPRESA INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0) 
SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD,0) 
SET @TIPO = ISNULL(:TIPO,0)

DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END

DECLARE @TKO VARCHAR(MAX)
SET @TKO = ISNULL(:TKO,'')
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END

IF(@TIPO=0)
BEGIN
SELECT IDUSUARIO 
FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK)
WHERE IDPROSPECTO = @IDPROSPECTO 
END 
ELSE 
BEGIN 
SELECT IDUSUARIO 
FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK)
WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD
END