//[abierto|Text,ejecutivo|Integer,buscar|Text,desde|Text,hasta|Text,session.db|Untyped,session.convertcode|Untyped,idautoresponder|Integer,idpieza|Integer,idetiqueta|Integer,session.idempresa|Untyped,tk|Text,tkpi|Text,tkauto|Text,]
DECLARE @IDAUTORESPONDER INT
DECLARE @IDPIEZA INT
DECLARE @IDETIQUETA INT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @ABIERTO INT
DECLARE @FILTROABIERTO VARCHAR(MAX)
DECLARE @EJECUTIVO INT
DECLARE @FILTROUSUARIO VARCHAR(MAX)
DECLARE @BUSCAR VARCHAR(MAX)
DECLARE @FILTROTEXTO VARCHAR(MAX)
DECLARE @DESDE VARCHAR(1000)
DECLARE @HASTA VARCHAR(1000)
DECLARE @FILTROFECHAS VARCHAR(1000)
DECLARE @PIESACOND VARCHAR(MAX)
DECLARE @TK VARCHAR(128)
DECLARE @TKPI VARCHAR(128)
DECLARE @TKAUTO VARCHAR(128)


DECLARE @SQL VARCHAR(MAX)
SET @SQL=''

SET @ABIERTO=ISNULL(:ABIERTO,0)
SET @FILTROABIERTO=ISNULL((CASE WHEN @ABIERTO!= 2 THEN ' AND ABIERTO = '+CAST(@ABIERTO AS VARCHAR(100)) ELSE '' END),'')
SET @EJECUTIVO=ISNULL(:EJECUTIVO,0)
SET @FILTROUSUARIO=ISNULL((CASE WHEN @EJECUTIVO!= 0 THEN ' AND UE.IDUSUARIO = '+CAST(@EJECUTIVO AS VARCHAR(100)) ELSE '' END),'')
SET @BUSCAR=:BUSCAR
SET @BUSCAR=(CASE WHEN @BUSCAR='UNDEF' THEN '' ELSE @BUSCAR END)
SET @FILTROTEXTO=ISNULL((CASE WHEN @BUSCAR!='' THEN 'AND (UE.DESTINATARIO LIKE ''%''+'''+@BUSCAR+'''+''%'' OR UE.ASUNTO LIKE ''%''+'''+@BUSCAR+'''+''%'' OR P.NOMBRE LIKE ''%''+'''+@BUSCAR+'''+''%'' OR P.APELLIDOS LIKE ''%''+'''+@BUSCAR+'''+''%'' OR P.EMPRESA LIKE ''%''+'''+@BUSCAR+'''+''%'')' ELSE '' END),'')
SET @DESDE=:DESDE
SET @HASTA=:HASTA
SET @DESDE=(CASE WHEN @DESDE='UNDEF' THEN '' ELSE @DESDE END)
SET @HASTA=(CASE WHEN @HASTA='UNDEF' THEN '' ELSE @HASTA END)
SET @FILTROFECHAS=ISNULL((CASE WHEN ISNULL(@DESDE,'')!='' AND ISNULL(@HASTA,'')!='' THEN 'AND <#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHAHORA)  BETWEEN CONVERT(DATETIME,'''+@DESDE+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+@HASTA+''',<#SESSION.CONVERTCODE/>)' ELSE '' END ),'')


SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER,0)
SET @IDPIEZA = ISNULL(:IDPIEZA,0)
SET @IDETIQUETA = ISNULL(:IDETIQUETA,0)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET  @PIESACOND=ISNULL((CASE WHEN @IDPIEZA >0  THEN ' AND AC.IDPIEZA = '+CAST(@IDPIEZA AS VARCHAR(1000)) ELSE ''END),'')


SET @TK = ISNULL(:TK,'')
IF @TK != '' BEGIN SELECT @IDETIQUETA=IDETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE TK = @TK AND IDEMPRESA = <#SESSION.IDEMPRESA/> END

SET @TKPI = ISNULL(:TKPI,'')
IF @TKPI != '' BEGIN SELECT @IDPIEZA=IDPIEZA FROM <#SESSION.DB/>.DBO.AUTORESPONDERS_PIEZAS WHERE CAST(TKPI AS VARCHAR(128))  = @TKPI END

SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> END

SET @SQL='
SELECT UE.*, P.NOMBRE, P.APELLIDOS , P.EMPRESA  , AC.ULTIMO_ENVIO, AC.ABIERTO, AC.FECHA_ABIERTO, U.INICIALES
FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UE.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL AC ON AC.IDPROSPECTO = P.IDPROSPECTO AND AC.IDPIEZA = '+CAST(@IDPIEZA AS VARCHAR(1000))+'
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = UE.IDUSUARIO
WHERE UE.IDAUTORESPONDER ='+CAST(@IDAUTORESPONDER AS VARCHAR(1000))+' AND UE.IDPIEZA = AC.IDPIEZA AND ESTADO = 1 
'+@FILTROABIERTO+'
'+@FILTROTEXTO+'
'+@FILTROFECHAS+'
'+@FILTROUSUARIO+'
ORDER BY FECHAHORA DESC
'
EXEC (@SQL)
