//[idplantilla|Text,session.db|Untyped,archivos|Text,archivoreal|Text,ruta_doc|Text,]
--INSERT
DECLARE @ANEXOS VARCHAR(8000)
DECLARE @RUTADOC VARCHAR(8000)
DECLARE @ANEXOSNUEVO VARCHAR(8000)
DECLARE @ARCHIVONUEVO VARCHAR(8000)
DECLARE @NOMBRE_REALNUEVO VARCHAR(8000)
DECLARE @ARCHIVO VARCHAR(8000)
DECLARE @NOMBRE_REAL VARCHAR(8000)
DECLARE @IDPLANTILLA INT

SET @IDPLANTILLA = CAST(:IDPLANTILLA AS INT)
SET @RUTADOC = :RUTA_DOC
SET @RUTADOC = 'Z:\archivos_externos\'+@RUTADOC+CHAR(13)+CHAR(10)

SELECT @ANEXOS=ANEXOS, @ARCHIVO=NOMBRE_ARCHIVO , @NOMBRE_REAL = NOMBRE_ARCHIVO_REAL 
FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS WHERE IDPLANTILLA = @IDPLANTILLA

SET @ARCHIVONUEVO = @ARCHIVO + :ARCHIVOS + ','
SET @NOMBRE_REALNUEVO = @NOMBRE_REAL+ :ARCHIVOREAL + ','
SET @ANEXOSNUEVO = ISNULL(@ANEXOS,'') + @RUTADOC
SET @ARCHIVO = @ARCHIVONUEVO
SET @NOMBRE_REAL = @NOMBRE_REALNUEVO

UPDATE <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS 
SET
  ANEXOS = @ANEXOSNUEVO, NOMBRE_ARCHIVO =@ARCHIVO,
  NOMBRE_ARCHIVO_REAL = @NOMBRE_REAL
WHERE 
  IDPLANTILLA = @IDPLANTILLA