//[session.db|Untyped,correo|Text,correoanterior|Text,idprospecto|Integer,]
--UPDATE
DECLARE @CORREO VARCHAR(1000)
DECLARE @CORREOANTERIOR VARCHAR(1000)
DECLARE @IDPROSPECTO INT
SET @CORREOANTERIOR=ISNULL(:correoanterior,'')
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)
SET @CORREO=ISNULL(:CORREO,'')
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET CORREO = @CORREO WHERE CORREO = @CORREOANTERIOR AND IDPROSPECTO = @IDPROSPECTO
UPDATE <#SESSION.DB/>.DBO.USUARIOS_EMAILS SET DESTINATARIO = @CORREO WHERE DESTINATARIO = @CORREOANTERIOR AND IDPROSPECTO = @IDPROSPECTO