//[session.idusuario|Untyped,session.db|Untyped,]
--select
/*protegido*/
DECLARE @IDUSUARIO INT
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT) 
SELECT TOP 1 FIRMA FROM <#SESSION.DB/>.DBO.USUARIOS_CUENTAS_CORREOS WHERE IDUSUARIO = @IDUSUARIO AND TIPO_CUENTA IN (1,3) AND PREDETERMINADO = 1 ORDER BY TIPO_CUENTA DESC