//[session.idempresa|Untyped,nombreinvitado|Text,correoinvitado|Text,contenido|Text,]
--UPDATE
DECLARE @IDEMPRESA INT
DECLARE @NOMBRE VARCHAR(1000)
DECLARE @CORREO VARCHAR(1000)
DECLARE @CONTENIDO VARCHAR(8000)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @NOMBRE = ISNULL(:NOMBREINVITADO,'')
SET @CORREO = ISNULL(:CORREOINVITADO,'')
SET @CONTENIDO = :CONTENIDO

UPDATE SALESUP_CT.dbo.EMPRESA_INVITACIONES SET FECHA = GETDATE() WHERE CORREO = @CORREO AND IDEMPRESA = @IDEMPRESA
EXEC SALESUP_CT.dbo.SP_ENVIA_CORREO_INVITADO @NOMBRE, @CORREO, @CONTENIDO, @IDEMPRESA