//[session.idempresa|Untyped,session.idusuario|Untyped,idu|Text,fechaactual|Text,r|Integer,condicionrecordatorios|Text,session.db|Untyped,]
--select
/*PROTEGIDO*/
DECLARE @MESACTUAL VARCHAR(MAX), @IDUSUARIO VARCHAR(MAX)
DECLARE @RANGO INT, @IDEMPRESA INT, @SESSIONIDUSUARIO INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONDICIONRECORDATORIOS VARCHAR(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @SESSIONIDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDUSUARIO = ISNULL(:IDU,'')
SET @MESACTUAL = ISNULL(:FechaActual,'')
SET @RANGO = ISNULL(:R,0)
SET @CONDICIONRECORDATORIOS=ISNULL(:CONDICIONRECORDATORIOS,'')

SET @SQL ='
DECLARE @FECHA DATETIME, @FINICIO DATETIME, @FFIN DATETIME
DECLARE @IDUSUARIO VARCHAR(MAX)
DECLARE @IDEMPRESA INT

SET @IDUSUARIO = '''+@IDUSUARIO+'''
SET @IDEMPRESA = '+cast(@IDEMPRESA as varchar(1000))+'

IF '''+@MESACTUAL+''' != ''''
BEGIN
	SET @FECHA = CONVERT(DATETIME, '''+@MESACTUAL+''', 103 )
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, 5, @FECHA)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, 5, @FECHA)
	SET @FINICIO = DATEADD(dd, -6, @FINICIO)
	SET @FFIN = DATEADD(dd, 6, @FFIN)
END
ELSE
BEGIN
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0,'+CAST(@RANGO AS VARCHAR(1000))+', NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1,'+CAST(@RANGO AS VARCHAR(1000))+', NULL)
END


SELECT ''1'' as Recordatorio, 1 AS Tipo, ''#FFC908'' as color, ''#222222'' as textColor, ''R''+CAST(R.IDRECORDATORIO AS VARCHAR(MAX)) AS id, 
''<i class="fa fa-bell"></i> <span class="Iniciales">(''+ U.INICIALES+'')</span> '' + + R.RECORDATORIO AS title, 
SALESUP_CT.DBO.Fecha(R.FECHAHORA) AS start, ''Pointer EventoRecordatorio R''+CONVERT(VARCHAR(MAX),U.IDUSUARIO)+'' IDR''+CAST(R.IDRECORDATORIO AS VARCHAR(MAX)) AS className, 
SALESUP_CT.dbo.ObtieneHora(R.FECHAHORA) as Hora, CONVERT(VARCHAR(10), R.FECHAHORA ,103) as Fecha ,
U.Iniciales, U.INICIALES AS Para, U.NOMBRE + '' ''+ U.APELLIDOS AS NomPara, 
P.NOMBRE + '' '' + ISNULL(P.APELLIDOS,'''') AS Prospecto,
--(SELECT CASE  WHEN COUNT(*)>0 or  r.recurrencia>0 THEN ''1'' ELSE '''' END  FROM <#SESSION.DB/>.dbo.RECORDATORIOS R2 WHERE R2.IDPADRE = R.IDRECORDATORIO OR R2.IDRECORDATORIO=R.IDPADRE) AS tPadre,
(CASE WHEN R.IDPADRE IS NOT NULL OR R.RECURRENCIA>0 THEN ''1'' ELSE '''' END) AS tPadre,
COM.TkCom, P.Tkp, R.IdProspecto, R.IdOportunidad, O.Tko, CASE P.EsCliente WHEN 1 THEN ''1'' ELSE '''' END AS EsCliente,
P.IdCompania, CASE WHEN ISNULL(P.IDCOMPANIA,0)=0 THEN P.EMPRESA ELSE COM.EMPRESA END AS Empresa, 
P.Movil, P.Telefono, P.Telefono2,
U.IDUSUARIO AS Idu,
CASE WHEN R.FECHAHORA <= GETDATE() THEN ''1'' ELSE '''' END AS Vencido,
CASE WHEN R.IDUSUARIO = '+CAST(@SESSIONIDUSUARIO AS VARCHAR(1000))+' THEN ''1'' ELSE '''' END AS Duenio,
CASE WHEN R.FECHAHORA <= GETDATE() THEN ''Vencido'' ELSE '''' END AS Estado,''1'' AS Acciones, CONVERT(FLOAT, R.FECHAHORA) AS DTF
FROM <#SESSION.DB/>.dbo.RECORDATORIOS R 
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = R.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDOPORTUNIDAD = R.IDOPORTUNIDAD
JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = R.IDUSUARIO
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA
JOIN <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos ('+CAST(@SESSIONIDUSUARIO AS VARCHAR(1000))+',7,0) UP ON U.IDUSUARIO = UP.ID
WHERE R.COMPLETADO=0 AND U.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+'
'+@CONDICIONRECORDATORIOS+'
ORDER BY DTF
'
EXEC(@SQL)