//[session.idusuario|Untyped,session.idempresa|Untyped,idu|Text,fechaactual|Text,r|Text,session.db|Untyped,condiciontareas|Text,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL(:CONDICIONTAREAS, '')
SET @SQL = '

 DECLARE @MESACTUAL VARCHAR(MAX), @IDREALIZADOR VARCHAR(MAX)
 DECLARE @FECHA DATETIME, @FINICIO DATETIME, @FFIN DATETIME
 DECLARE @RANGO INT, @IDEMPRESA INT, @SESSIONIDUSUARIO INT

 SET @SESSIONIDUSUARIO = ISNULL(CAST(''<#SESSION.IDUSUARIO/>'' AS INT), 0)
  SET @IDEMPRESA = ISNULL(CAST(''<#SESSION.IDEMPRESA/>'' AS INT), 0)
 SET @IDREALIZADOR =ISNULL(''' + ISNULL( :IDU , '') +''', '''')
 SET @MESACTUAL    = ISNULL(''' + ISNULL( :FechaActual , '') +''', '''')
 SET @RANGO        = ISNULL(CAST(''' + ISNULL( :R , 0) + ''' AS INT), 0)

 IF @MESACTUAL != ''''
 BEGIN
	SET @FECHA = CONVERT(DATETIME, @MESACTUAL, 103 )
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, 5, @FECHA)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, 5, @FECHA)
 END
 ELSE
 BEGIN
	SET @FINICIO = SALESUP_CT.dbo.RangoFecha(0, @RANGO, NULL)
	SET @FFIN = SALESUP_CT.dbo.RangoFecha(1, @RANGO, NULL)
 END

 SELECT COUNT(*) AS Registros
 FROM <#SESSION.DB/>.dbo.TAREAS T 
 JOIN <#SESSION.DB/>.dbo.TAREAS_SEGUIMIENTO TS ON TS.IDTAREASEGUIMIENTO = T.IDTAREASEGUIMIENTO
 JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = T.IDREALIZADOR
 JOIN <#SESSION.DB/>.dbo.USUARIOS U1 ON U1.IDUSUARIO = T.IDINICIADOR
 JOIN SALESUP_CT.dbo.V_TAREAS_ESTADOS VT ON VT.IDESTADO = T.IDESTADO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = T.IDPROSPECTO
 LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDOPORTUNIDAD = T.IDOPORTUNIDAD
 LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA
 JOIN <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,6,0) UP ON U.IDUSUARIO = UP.ID
 WHERE (U.IDEMPRESA = @IDEMPRESA) AND 1 = 1 
 ' + @CRIT
 
EXEC (@SQL)