//[session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,TKG|Text,]
--select

DECLARE @SQL VARCHAR(MAX), @GRUPOS VARCHAR(MAX), @TKG VARCHAR(MAX), @BD VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @IDGRUPO INT, @IDEMPRESA INT

SET @BD = '<#SESSION.DB/>.'
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TKG = '<#TKG/>'
SET @GRUPOS = ''

IF @TKG != ''
BEGIN
	SELECT @IDGRUPO = IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE TK = @TKG
	SET @GRUPOS = ' AND U.IDGRUPO = '+CAST(@IDGRUPO AS VARCHAR(MAX))	
END

SET @SQL = ''
SET @SQL += ' DECLARE @IDUSUARIO INT, @IDGRUPO INT '
SET @SQL += ' SET @IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' '
SET @SQL += ' SELECT CAST(u.tku AS VARCHAR(MAX)) AS tku, u.nombre + '' ''+ isnull(u.apellidos,'''') as usuario, u.iniciales '
SET @SQL += ' FROM '+@BD+'DBO.USUARIOS U, '+@BD+'DBO.obtieneUsuariosAutorizadosModulos(@IDUSUARIO, 8, 0) M '
SET @SQL += ' WHERE U.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND U.IDUSUARIO = M.ID '+@GRUPOS+' ORDER BY U.NOMBRE'
SET @SQL += ' '

EXEC (@SQL)