//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @TB TABLE (  IdC VARCHAR(MAX), Campo VARCHAR(MAX), Nombre VARCHAR(MAX), Tip VARCHAR(MAX))

INSERT INTO @TB ( IdC, Campo, Nombre, Tip)

SELECT  '-'+CAST(ECC.CAMPO AS VARCHAR(MAX)) AS IdC,  C.CAMPO, UPPER(NOMBREBASE) AS Nombre, C.TIP AS Tip
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION ECC, SALESUP_CT.DBO.CAMPOS C
WHERE ECC.IDEMPRESA = @IDEMPRESA AND ECC.CAMPO = C.IDCAMPO 
ORDER BY ECC.CAMPO

INSERT INTO @TB (IdC, Campo, Nombre, Tip)

SELECT  
EC.INDICE AS IdC,
EC.Nombre_Campo AS Campo,
'CAMPO'+ cast(EC.INDICE as varchar(max)) AS Nombre, '['+EC.Nombre_Campo+ '] - ' +EC.DESCRIPCION as Tip
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC 
WHERE EC.IDEMPRESA = @IDEMPRESA AND ( EC.TIPO = 1 OR EC.COMPARTIR = 1 )
ORDER BY EC.INDICE

SELECT Campo, Nombre, Tip FROM @TB



