//[session.idempresa|Untyped,session.idusuario|Untyped,t|Integer,tk|Text,session.db|Untyped,]
--select

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA =  CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO =  CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @TIPO INT
DECLARE @TK VARCHAR(MAX)
SET @TIPO = CAST(ISNULL(:T,0) AS INT)
SET @TK = :TK

IF @TIPO = 1 OR @TIPO = 3 
BEGIN
	 SELECT IdProspecto as idp FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDEMPRESA = @IDEMPRESA AND TKP = @TK
END

IF @TIPO = 2 
BEGIN
	 SELECT IdOportunidad as ido FROM <#SESSION.DB/>.dbo.Oportunidades O 
	 JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON O.IDPROSPECTO = P.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
	 WHERE O.TKO = @TK
END

IF @TIPO = 4 
BEGIN
	 SELECT V.IdOportunidad as ido, V.IdVenta as idv, O.tko FROM <#SESSION.DB/>.dbo.VENTAS V 
	 JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
	 JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = V.IDUSUARIO AND U.IDEMPRESA = @IDEMPRESA
	 WHERE V.TKV = @TK
END

