//[session.idempresa|Untyped,session.idusuario|Untyped,b|Text,session.db|Untyped,]
--select
/* @IDTABLA ES EL ID DE LA TABLA QUE SE TOMA DE LA VISTA SALESUP_CT.DBO.V_TABLAS
   4 - PROSPECTOS, 15 OPORTUNIDADES, 16 VENTAS
   
   @PERMISOMODULO ES EL ID DEL PERMISOS QUE SE TOMA DE LA VISTA SALESUP_DB.DBO.V_MODULOS_PERMISOS
   1 - PROSPECTO, 2 - OPORTUNIDADES, 3- VENTAS Y 4-CLIENTES
   
   @TIPO, 0 ES DATOS, 1 ES PAGINACION
  
   @HOWMANY ES CUANTOS REGISTROS SE REGRESAN DEL TOTAL DE LA CONSULTA
   @PAGE ES LA PAGINA QUE INTERESA 
   PARA LA PAGINACION ESTOS VALORES DEBEN SER 1 AMBOS.
   
   @DESCARTADOS   
     0- PROSPECTOS, CLIENTES U OPORTUNIDADES DESCARTADAS
   	 1- PROSPECTOS, CLIENTES U OPORTUNIDADES DESCARTADAS
   
*/ 
DECLARE @TEXTO VARCHAR(256)
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TEXTO=:B

EXEC <#SESSION.DB/>.DBO.SP_BUSQUEDA_EN_BASE_TOTALES @IDUSUARIO,@IDEMPRESA,@TEXTO
