//[session.idusuario|Untyped,tipo|Integer,t|Integer,c|Integer,tk|Text,session.db|Untyped,]
--select
/*PROTEGIDO*/
DECLARE @IDTABLA INT, @TIPO INT, @ESCLIENTE INT
DECLARE @TOKEN VARCHAR(MAX)
DECLARE @IDUSUARIO INT
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @TIPO=ISNULL(:TIPO, 0)
SET @IDTABLA=ISNULL(:T, 0)
SET @ESCLIENTE=ISNULL(:C, 0) 
SET @TOKEN = ISNULL(:TK, 0)

IF (@IDTABLA>0)
   EXEC <#SESSION.DB/>.dbo.SP_BUSQUEDA_EN_BASE_DETALLE @TOKEN,@IDTABLA,@TIPO,@ESCLIENTE,@IDUSUARIO
ELSE
   SELECT '' AS CAMPO1   
