//[session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,pet|Text,tk|Text,c|Text,t|Integer,session.db|Untyped,]
-- INSERT 
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @TK VARCHAR(MAX), @COMENTARIO VARCHAR(MAX), @PETICION VARCHAR(MAX)
DECLARE @TIPO INT, @EXISTE INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT, @IDSEGUIMIENTOCATEGORIA INT
DECLARE @IDSEGUIMIENTO INT, @TIPOSUCESO INT, @PROSPECTOSCLIENTES INT, @OPORTUNIDADESVENTAS INT
DECLARE @CONVERTCODE INT, @ASIGNADOS INT

SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)

SET @PETICION = ISNULL(:PET,'')
SET @TK = :TK
SET @COMENTARIO = :C
SET @TIPO = ISNULL(:T,0) 

SET @PROSPECTOSCLIENTES = 0
SET @OPORTUNIDADESVENTAS = 0
SET @TIPOSUCESO = 0

IF @TIPO = 1 OR @TIPO = 3 
BEGIN
	 IF @TIPO = 1 BEGIN SET @TIPOSUCESO = 7 END ELSE BEGIN SET @TIPOSUCESO = 13 END
	 SET @PROSPECTOSCLIENTES = 1  
	 SELECT @IDPROSPECTO = IdProspecto 
	 FROM <#SESSION.DB/>.dbo.PROSPECTOS 
	 WHERE IDEMPRESA = @IDEMPRESA AND TKP = @TK 
END

IF @TIPO = 2 
BEGIN
	 SET @OPORTUNIDADESVENTAS = 1
	 SET @TIPOSUCESO = 10
	 SELECT @IDOPORTUNIDAD = O.IdOportunidad, @IDPROSPECTO = O.IdProspecto 
	 FROM <#SESSION.DB/>.dbo.Oportunidades O 
	 JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON O.IDPROSPECTO = P.IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
	 WHERE O.TKO = @TK
END

IF @TIPO = 4
BEGIN
	 SET @OPORTUNIDADESVENTAS = 1
	 SET @TIPOSUCESO = 10
	 SELECT @IDOPORTUNIDAD = V.IdOportunidad, @IDPROSPECTO = O.IdProspecto FROM <#SESSION.DB/>.dbo.VENTAS V 
	 JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
	 JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = V.IDUSUARIO AND U.IDEMPRESA = @IDEMPRESA
	 WHERE V.TKV = @TK
END

SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE FECHAHORA > GETDATE()-1  AND IDPETICION !='' AND IDPETICION = @PETICION

IF @EXISTE = 0
BEGIN
	INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK)
	(IDPROSPECTO, IDUSUARIO, COMENTARIO, IDOPORTUNIDAD, IDPETICION, IDSEGUIMIENTOCATEGORIA )
	VALUES 
	(@IDPROSPECTO, @IDUSUARIO, @COMENTARIO, @IDOPORTUNIDAD, @PETICION, @IDSEGUIMIENTOCATEGORIA)
	
	SELECT @ASIGNADOS = COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO != @IDUSUARIO
		
	IF @ASIGNADOS > 0 BEGIN EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_SEGUIMIENTO @IDPROSPECTO, @IDUSUARIO, @IDEMPRESA, @COMENTARIO END
	
	SELECT TOP 1 @IDSEGUIMIENTO = IDSEGUIMIENTO 
	FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(NOLOCK) 
	WHERE IDPROSPECTO = @IDPROSPECTO ORDER BY IDSEGUIMIENTO DESC
	
	IF @PROSPECTOSCLIENTES = 1  BEGIN EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @CONVERTCODE, '', @IDSEGUIMIENTO END
	
	IF @OPORTUNIDADESVENTAS = 1 BEGIN EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES @IDUSUARIO, @TIPOSUCESO, @IDPROSPECTO, @IDOPORTUNIDAD, @CONVERTCODE, '', @IDSEGUIMIENTO END
	
	
	DECLARE @HOY DATETIME
	SET @HOY = GETDATE()
	EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO, @HOY
END

