//[tkco|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT 

DECLARE @TKCO VARCHAR(MAX)

SET @TKCO = :tkco

IF(LEFT(@TKCO,2) = 'IN')
BEGIN
	SELECT 
	CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, 1, CHARINDEX('/',CA.CATALOGO) -1  ) ELSE CA.CATALOGO END AS Singular,
	CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, CHARINDEX('/',CA.CATALOGO) + 1 ,LEN(CA.CATALOGO)  ) ELSE CA.CATALOGO END AS Plural, 
	INDUSTRIA AS Opcion, 
	'' AS Descripcion 
	FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI
	LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CA ON CA.IDEMPRESA = EI.IDEMPRESA
	WHERE TKIND = @TKCO AND CA.TIPO = 1
END
ELSE IF(LEFT(@TKCO,2) = 'CG')
BEGIN
	 SELECT
	 CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, 1, CHARINDEX('/',CA.CATALOGO) -1  ) ELSE CA.CATALOGO END AS Singular,
	 CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, CHARINDEX('/',CA.CATALOGO) + 1 ,LEN(CA.CATALOGO)  ) ELSE CA.CATALOGO END AS Plural, 
	 COMPANIAGRUPO AS Opcion, 
	 '' AS Descripcion 
	 FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG
	 LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CA ON CA.IDEMPRESA = CG.IDEMPRESA 
	 WHERE TKCG = @TKCO AND CA.TIPO = 2
END
ELSE
BEGIN
	SELECT 
	CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, 1, CHARINDEX('/',CA.CATALOGO) -1  ) ELSE CA.CATALOGO END AS Singular,
	 CASE WHEN CHARINDEX('/',CA.CATALOGO) > 3 THEN SUBSTRING(CA.CATALOGO, CHARINDEX('/',CA.CATALOGO) + 1 ,LEN(CA.CATALOGO)  ) ELSE CA.CATALOGO END AS Plural, 
	OPCION AS Opcion, 
	(select NOMBRE_CAMPO from  <#SESSION.DB/>.dbo.empresas_campos where IDEMPRESA = <#SESSION.IDEMPRESA/> and Tipo = 5) as Campo13Nombre,
	CO.Campo13 as Campo13,
	replace(cast(CO.DESCRIPCION as varchar(max)),char(10),'') AS Descripcion 
	FROM <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES CO
	LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CA ON CA.IDCATALOGO = CO.IDCATALOGO
	WHERE TKCO = @TKCO AND CA.TIPO = 0
END