//[session.idempresa|Untyped,tkca|Text,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
DECLARE @TKCA VARCHAR(64)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TKCA = dbo.ValidaToken(:TKCA) 

SELECT  
CAO.IdCatalogoOpcion, 
CAO.Opcion, 
CAO.Tkco
FROM <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES CAO
JOIN <#SESSION.DB/>.dbo.CATALOGOS CA ON CA.IDEMPRESA = @IDEMPRESA AND CAO.IDCATALOGO = CA.IDCATALOGO AND CA.TKCA = @TKCA
WHERE ACTIVO=1
ORDER BY OPCION
