//[tkco|Text,session.idempresa|Untyped,session.gmt|Untyped,session.db|Untyped,]
-- select

DECLARE @GMT INT
DECLARE @TkCo VARCHAR(1000) 
DECLARE @IDEMPRESA INT 

SET @TkCo = dbo.ValidaToken(ISNULL(:TKCO,''))
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT  WITH(NOLOCK)  WHERE GMT= @GMT

EXEC <#SESSION.DB/>.DBO.SP_SELECT_SEGUIMIENTOS_OPCIONES @IDEMPRESA,1,@TkCo,''
