//[nombremarca|Text,session.idempresa|Untyped,idmarca|Integer,idmarcanueva|Integer,session.db|Untyped,actualiza|Integer,tk|Text,]
--INSERT
DECLARE @NOMBREMARCA VARCHAR(200) 
DECLARE @IDEMPRESA INT 

DECLARE @ACTUALIZAR INT 
DECLARE @IDMARCA INT 
DECLARE @EXISTEMARCA VARCHAR(200)
DECLARE @IDMARCANUEVA INT 
DECLARE @TK VARCHAR(256) 


SET @NOMBREMARCA=dbo.PreparaCadena(ISNULL(:NOMBREMARCA,''))
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @ACTUALIZAR= ISNULL(:ACTUALIZA,0)

SET @IDMARCANUEVA=ISNULL(:IDMARCANUEVA,0)
SET @TK =ISNULL(:TK, '') 
--SELECT @IDMARCA=IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE TK=@TK

IF(@ACTUALIZAR=0)
  BEGIN
	INSERT INTO <#SESSION.DB/>.DBO.MARCAS (IDEMPRESA, MARCA) 
	VALUES (@IDEMPRESA, @NOMBREMARCA)
  END
ELSE IF(@ACTUALIZAR=1) 
 BEGIN
  UPDATE  <#SESSION.DB/>.DBO.MARCAS
  SET    MARCA=@NOMBREMARCA
  WHERE TK=@TK

END
ELSE IF(@ACTUALIZAR=2) 
BEGIN 
	  
   UPDATE <#SESSION.DB/>.DBO.PRODUCTOS
   SET IDMARCA=@IDMARCANUEVA
   WHERE IDMARCA=@IDMARCA 
   DELETE FROM <#SESSION.DB/>.DBO.MARCAS
   WHERE IDMARCA=@IDMARCA
   SELECT 'ELIMINADO' AS RESULTADO, @NOMBREMARCA AS NOMBREMARCA, @actualizar AS BANDERA,@IDMARCA AS IDMARCA, @IDMARCANUEVA AS IDMARCANUEVA
  END
ELSE IF(@ACTUALIZAR=3) 
BEGIN 
	  
   IF((SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDMARCA = @IDMARCA) > 0)
   BEGIN
   		SELECT 1 AS RESULTADO, @NOMBREMARCA AS NOMBREMARCA, @actualizar AS BANDERA,@IDMARCA AS IDMARCA, @IDMARCANUEVA AS IDMARCANUEVA
   END 
   ELSE
   BEGIN
   		DELETE FROM <#SESSION.DB/>.DBO.MARCAS WHERE IDMARCA=@IDMARCA
		SELECT 'ELIMINADO' AS RESULTADO, @NOMBREMARCA AS NOMBREMARCA, @actualizar AS BANDERA,@IDMARCA AS IDMARCA, @IDMARCANUEVA AS IDMARCANUEVA
   END
  END