//[tkco|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Integer,f_usuario|Text,crit|Text,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT
DECLARE @TkCo VARCHAR(MAX)
DECLARE @FUSUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)

SET @TkCo = dbo.ValidaToken(ISNULL(:TKCO,''))
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @DESCARTADO=CAST (ISNULL(:DESCARTADO,0) AS INT)
SET @FUSUARIO = ISNULL(:F_USUARIO,'')
SET @CRIT = ISNULL(:CRIT,'')


EXEC <#SESSION.DB/>.DBO.SP_SELECT_OPORTUNIDADES_OPCIONES @FUSUARIO,@CRIT,2,@TkCo,@DESCARTADO,@IDEMPRESA,@IDUSUARIO,@NIVELUSUARIO, @MAILCONFIG

