//[prospectosclientes|Integer,oportunidadesventas|Integer,empresa|Integer,agrupa|Integer,enmenu|Integer,session.db|Untyped,nombre|Text,descripcion|Text,tkca|Text,]
-- UPDATE

DECLARE @VERPROSPECTOS INT
DECLARE @VERVENTAS INT
DECLARE @VEREMPRESA INT
DECLARE @AGRUPAR INT
DECLARE @ENMENU INT

SET @VERPROSPECTOS = CAST(ISNULL(:prospectosClientes,0) AS INT)
SET @VERVENTAS = CAST(ISNULL(:oportunidadesVentas,0) AS INT)
SET @VEREMPRESA = CAST(ISNULL(:empresa,0) AS INT)
SET @AGRUPAR = CAST(ISNULL(:agrupa,0) AS INT)
SET @ENMENU = CAST(ISNULL(:enmenu,0) AS INT)

UPDATE <#SESSION.DB/>.dbo.CATALOGOS SET CATALOGO = :NOMBRE, DESCRIPCION = :DESCRIPCION, VERPROSPECTOS = @VERPROSPECTOS, VERVENTAS = @VERVENTAS,VEREMPRESA = @VEREMPRESA, AGRUPAR = @AGRUPAR, ENMENU = @ENMENU
WHERE TKCA = :TKCA