//[tkco|Text,session.db|Untyped,accion|Integer,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/

DECLARE @TK VARCHAR(64)
DECLARE @ACCION INT
SET @TK = dbo.ValidaToken(ISNULL(:TKCO,''))
SET @ACCION = ISNULL(:ACCION,0)

UPDATE <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES 
SET ACTIVO = @ACCION
WHERE TKCO = @TK