//[tkco|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,f_usuario|Text,crit|Text,session.db|Untyped,]
--select

DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT,@IDCATALOGOOPCION INT
DECLARE @TKCO VARCHAR(MAX)
DECLARE @FUSUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)

SET @TKCO = dbo.ValidaToken(ISNULL(:TKCO,''))
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)
SET @FUSUARIO = ISNULL(:F_USUARIO,'')
SET @CRIT = ISNULL(:CRIT,'')

EXEC <#SESSION.DB/>.DBO.SP_SELECT_VENTAS_OPCIONES @FUSUARIO,@CRIT,2,@TKCO, @IDEMPRESA,@IDUSUARIO, @NIVELUSUARIO, @IDGRUPO




