//[tkca|Text,tkco|Text,tkcon|Text,session.db|Untyped,session.idempresa|Untyped,]
--UPDATE
DECLARE @INDICE INT
DECLARE @IDNUEVO INT
DECLARE @IDANTERIOR INT

DECLARE @TKCA  VARCHAR(64) SET @TKCA  = dbo.ValidaToken(ISNULL(:TKCA,''))
DECLARE @TKCO  VARCHAR(64) SET @TKCO  = dbo.ValidaToken(ISNULL(:TKCO,''))
DECLARE @TKCON VARCHAR(64) SET @TKCON = dbo.ValidaToken(ISNULL(:TKCON,''))


DECLARE @SQL VARCHAR(MAX)
SELECT @INDICE     = INDICE FROM <#SESSION.DB/>.dbo.CATALOGOS WHERE TKCA =  @TKCA AND IDEMPRESA = <#SESSION.IDEMPRESA/>
SELECT @IDANTERIOR = IDCATALOGOOPCION FROM <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES WHERE TKCO = @TKCO
SELECT @IDNUEVO    = IDCATALOGOOPCION FROM <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES WHERE TKCO = @TKCON 

--select @indice as indice, @IDANTERIOR id_ant,@IDnuevo as ind_nuev
IF @INDICE != 0 
BEGIN
  SET @SQL = ' UPDATE  <#SESSION.DB/>.dbo.PROSPECTOS WITH(ROWLOCK) SET IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(16)) + '= '+CAST(@IDNUEVO AS VARCHAR(16))+' WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(15)) + ' = '+CAST(@IDANTERIOR AS VARCHAR(16))
  EXEC (  @SQL)
  SET @SQL = ' UPDATE  <#SESSION.DB/>.dbo.OPORTUNIDADES  WITH(ROWLOCK)SET IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(16)) + '= '+CAST(@IDNUEVO AS VARCHAR(16))+' WHERE IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>) AND IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(15)) + ' = '+CAST(@IDANTERIOR AS VARCHAR(16))
  EXEC (  @SQL)
  SET @SQL = ' UPDATE  <#SESSION.DB/>.dbo.COMPANIAS  WITH(ROWLOCK) SET IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(16)) + '= '+CAST(@IDNUEVO AS VARCHAR(16))+' WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDCATALOGOOPCION'+ CAST(@INDICE AS VARCHAR(15)) + ' = '+CAST(@IDANTERIOR AS VARCHAR(16))
  EXEC (  @SQL)
  DELETE FROM <#SESSION.DB/>.dbo.CATALOGOS_OPCIONES WHERE IDCATALOGOOPCION = @IDANTERIOR
  UPDATE <#SESSION.DB/>.dbo.CATALOGOS SET OPCIONES = OPCIONES-1 WHERE TKCA = @TKCA AND IDEMPRESA = <#SESSION.IDEMPRESA/>
  INSERT INTO <#SESSION.DB/>.dbo.ELIMINACIONES (TIPO, IDTABLA, IDNUEVO, IDELIMINADO, IDEMPRESA) 
  VALUES (1,35,@IDNUEVO,@IDANTERIOR,<#SESSION.IDEMPRESA/>)
END