//[session.db|Untyped,session.idempresa|Untyped,]
SELECT
 CASE WHEN CHARINDEX('/',CATALOGO) > 3 THEN SUBSTRING(CATALOGO, 1, CHARINDEX('/',CATALOGO) -1  ) ELSE CATALOGO END AS SINGULAR, 
 CASE WHEN CHARINDEX('/',CATALOGO) > 3 THEN SUBSTRING(CATALOGO, CHARINDEX('/',CATALOGO) + 1 ,LEN(CATALOGO)  ) ELSE CATALOGO END AS PLURAL,
 descripcion,tipo ,tkca
 FROM <#SESSION.DB/>.dbo.CATALOGOS 
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>  AND STATUS = 1
ORDER BY INDICE,TIPO 