//[session.db|Untyped,tk|Text,]
--DELETE 


DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(256) 

SET @IDEMPRESA= <#SESSION.IDEMPRESA/>
SET @TK =ISNULL(:TK, '') 

DELETE FROM <#SESSION.DB/>.DBO.MARCAS 
WHERE IDEMPRESA=@IDEMPRESA AND TK = @TK 