//[session.db|Untyped,session.idempresa|Untyped,]
SELECT
 CASE WHEN CHARINDEX('/',CATALOGO) > 3 THEN SUBSTRING(CATALOGO, 1, CHARINDEX('/',CATALOGO) -1  ) ELSE CATALOGO END AS SINGULAR, 
 CASE WHEN CHARINDEX('/',CATALOGO) > 3 THEN SUBSTRING(CATALOGO, CHARINDEX('/',CATALOGO) + 1 ,LEN(CATALOGO)  ) ELSE CATALOGO END AS PLURAL, 
 CASE WHEN STATUS = 1 THEN 'Activo' ELSE 'Inactivo' END AS STATUS,
 CASE WHEN VERPROSPECTOS = 1 THEN 'Prospectos' ELSE '' END AS VerProspectos,
 CASE WHEN VERVENTAS = 1 THEN 'Ventas' ELSE '' END AS VerVentas,
 CASE WHEN VEREMPRESA = 1 THEN 'Empresas' ELSE '' END AS VerEmpresas,
 CASE WHEN AGRUPAR = 1 THEN 'Si' ELSE 'No' END AS AGRUPAR,
 CASE WHEN EnMENU = 1 THEN 'Si' ELSE 'No' END AS EnMENU,
 CATALOGO, OPCIONES, STATUS AS STATUS_INT, TIPO, INDICE, TKCA
 FROM <#SESSION.DB/>.dbo.CATALOGOS 
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> 
ORDER BY INDICE,TIPO 