//[tk|Text,session.db|Untyped,]
--SELECT 

DECLARE @TK VARCHAR(256) 
DECLARE @IDMARCA INT 

SET @TK=ISNULL(:TK, '') 

SELECT @IDMARCA=IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE TK=@TK

SELECT COUNT(*) AS total FROM <#SESSION.DB/>.DBO.PRODUCTOS WHERE IDMARCA=@IDMARCA 
