//[session.idempresa|Untyped,session.db|Untyped,tkeliminar|Text,tknuevo|Text,]
--update
 
DECLARE @IDEMPRESA INT 
DECLARE @TKELIMINAR VARCHAR(256)
DECLARE @TKNUEVO  VARCHAR(256) 
DECLARE @IDMARCAELIMINAR INT
DECLARE @IDMARCANUEVO INT  
 
SET @IDEMPRESA =<#SESSION.IDEMPRESA/>
SET @TKELIMINAR = ISNULL(:TKELIMINAR, '')
SET @TKNUEVO = ISNULL(:TKNUEVO, '') 

SELECT @IDMARCAELIMINAR=IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE TK =@TKELIMINAR 
SELECT @IDMARCANUEVO= IDMARCA FROM <#SESSION.DB/>.DBO.MARCAS WHERE TK =@TKNUEVO

UPDATE  <#SESSION.DB/>.DBO.PRODUCTOS 
SET IDMARCA=@IDMARCANUEVO 
WHERE IDEMPRESA= @IDEMPRESA AND IDMARCA=@IDMARCAELIMINAR

DELETE FROM <#SESSION.DB/>.DBO.MARCAS 
WHERE TK=@TKELIMINAR