//[session.idempresa|Untyped,session.idusuario|Untyped,f|Integer,c|Integer,paises|Text,session.db|Untyped,]
--SELECT

DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @FILTRO INT, @CATEGORIA INT
DECLARE @PAISES VARCHAR(MAX)
SET @FILTRO = ISNULL(:F,0)
SET @CATEGORIA = ISNULL(:C,0)
SET @PAISES = ISNULL(:PAISES,'') 


/*PROSPECTOS*/
IF(@CATEGORIA = 0 AND @FILTRO = 1)
BEGIN
	 DECLARE @QRYCONSULTA VARCHAR(MAX)
	SET @QRYCONSULTA = ''
	SET @QRYCONSULTA = @QRYCONSULTA + ' SELECT P.Tkp, P.IDPROSPECTO AS Valor, '
	SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(P.TITULO+'' '','''') AS Titulo , LTRIM(RTRIM(P.NOMBRE)) +'' ''+ '
	SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS FiltroTexto '
	SET @QRYCONSULTA = @QRYCONSULTA + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P '
	SET @QRYCONSULTA = @QRYCONSULTA + ' JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON PA.IDPROSPECTO = P.IDPROSPECTO '
	SET @QRYCONSULTA = @QRYCONSULTA + ' WHERE Pa.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' AND P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.DESCARTADO = 0 '
	SET @QRYCONSULTA = @QRYCONSULTA + ' ORDER BY P.NOMBRE, P.APELLIDOS '

	EXEC (@QRYCONSULTA)

END

/*USUARIOS*/
IF @CATEGORIA = 1 AND @FILTRO = 1 
BEGIN
	 SELECT U.IDUSUARIO AS Valor, U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.USUARIOS U, 
	 <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO, 8, 0) UA
	 WHERE U.IDUSUARIO = UA.ID ORDER BY FiltroTexto
END

/*ETIQUETAS*/
IF @CATEGORIA = 1 AND @FILTRO = 2
BEGIN
	 SELECT ETI.IDETIQUETA AS Valor, ETI.ETIQUETA AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.ETIQUETAS ETI
	 WHERE ETI.IDEMPRESA = @IDEMPRESA ORDER BY FiltroTexto
END

/*STATUS prospectos*/
IF @CATEGORIA = 1 AND @FILTRO = 3
BEGIN
	 SELECT 0 AS Valor, 'Activos' AS FiltroTexto 
	 UNION
	 SELECT 1, 'Descartados'
	 UNION
	 SELECT 2, 'Prospectos'
	 UNION
	 SELECT 3, 'Clientes'
	 UNION
	 SELECT 4, 'Canalizados'
	 UNION
	 SELECT 5, 'No canalizados'
END

/*FASES*/
IF @CATEGORIA = 1 AND @FILTRO = 4
BEGIN
	 SELECT IDFASE AS Valor, FASE AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY FASECLIENTE, ORDEN
END

/*ORIGENES*/
IF @CATEGORIA = 1 AND @FILTRO = 5
BEGIN
	 SELECT IDORIGEN AS Valor, ORIGEN AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES 
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY ORIGEN
END

/*País*/
IF @CATEGORIA = 1 AND @FILTRO = 6
BEGIN
	 SELECT IDPAIS AS Valor, PAIS AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.PAISES 
	 ORDER BY PAIS
END

/*ESTADO*/
IF @CATEGORIA = 1 AND @FILTRO = 7
BEGIN
	 DECLARE @NPAIS INT
	 SELECT @NPAIS = COUNT(*) FROM SALESUP_CT.dbo.SPLIT(@PAISES, '|')
	 
	 SELECT E.IDESTADO AS Valor, E.ESTADO + CASE WHEN @NPAIS > 1 THEN ' - ('+P.PAIS+')' ELSE '' END AS FiltroTexto
	 FROM dbo.ESTADOS E JOIN <#SESSION.DB/>.DBO.PAISES P ON P.IDPAIS = E.IDPAIS
	 WHERE E.IDPAIS IN (SELECT SPLITVALUE FROM SALESUP_CT.dbo.SPLIT(@PAISES, '|')) 
	 ORDER BY E.IDPAIS, E.ESTADO
	 
END

/*GRUPOS*/
IF @CATEGORIA = 1 AND @FILTRO = 8
BEGIN
	 SELECT IDUSUARIOGRUPO AS Valor, GRUPO AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G, 
	 <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos ( @IDUSUARIO , 8, 1) GA
	 WHERE G.IDUSUARIOGRUPO = GA.ID
END

/*INDUSTRIA*/
IF @CATEGORIA = 1 AND @FILTRO = 9
BEGIN
	 SELECT IDINDUSTRIA AS Valor, INDUSTRIA AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY INDUSTRIA ASC
END

/*Grupo empresarial*/
IF @CATEGORIA = 1 AND @FILTRO = 10
BEGIN
	 SELECT IDCOMPANIAGRUPO AS Valor, COMPANIAGRUPO AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS
	 WHERE IDEMPRESA = @IDEMPRESA ORDER BY COMPANIAGRUPO ASC
END

/*LINEAS*/
IF @CATEGORIA = 2 AND @FILTRO = 1
BEGIN
	 SELECT IDLINEA_PRODUCTO AS Valor, LINEA_PRODUCTO AS FiltroTexto
	 FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO L
	 WHERE L.IDEMPRESA = @IDEMPRESA ORDER BY LINEA_PRODUCTO
END

/*CERTEZA*/
IF @CATEGORIA = 2 AND @FILTRO = 2
BEGIN
	 DECLARE @MUESTRA_CERTEZA INT
	 SELECT @MUESTRA_CERTEZA = OCULTAR_CERTEZAS_SINDESC FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA
	 
	 SELECT '-1' AS Valor, 'Menor al 33%' AS FiltroTexto
	 UNION ALL
	 SELECT '-2', 'Entre 33% y 66%'
	 UNION ALL
	 SELECT '-3', 'Mayor al 66%'
	 UNION ALL
	 SELECT (CAST(CERTEZA AS FLOAT)/100),
	 CASE WHEN ISNULL(DESCRIPCION,'') <> '' THEN CAST(CERTEZA AS VARCHAR(10))+ '% - '+ LTRIM(RTRIM(ISNULL(DESCRIPCION,''))) ELSE CAST(CERTEZA AS VARCHAR(10))+ '%' END
	 FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA = @IDEMPRESA AND (@MUESTRA_CERTEZA != 10 OR (@MUESTRA_CERTEZA = 1 AND DESCRIPCION <> 'x'))
END

/*COMISION*/
IF @CATEGORIA = 2 AND @FILTRO = 3
BEGIN
	 SELECT '' AS Valor, '' AS FiltroTexto
END

/*STATUS OPORTUNIDADES*/
IF @CATEGORIA = 2 AND @FILTRO = 4
BEGIN
	 SELECT 1 AS Valor, 'Activas' AS FiltroTexto 
	 UNION
	 SELECT 2, 'Descartadas'
	 UNION
	 SELECT 3, 'Ganadas'
END


/*STATUS CORPORATIVO*/
IF @CATEGORIA = 1 AND @FILTRO = 12
BEGIN
	    select idcluster AS Valor, cluster AS FiltroTexto from control.control.dbo.empresas_relacionadas er, control.control.dbo.canalizaciones c  
left join control.control.dbo.canalizacion_clusters ccts on ccts.IDCANALIZACION=c.IDCANALIZACION
where er.IDEMPRESADESTINO=@IDEMPRESA and c.IDEMPRESA=er.IDEMPRESAORIGEN 
END


IF @CATEGORIA = 1 AND @FILTRO = 13
BEGIN
	 SELECT U.Idusuario AS Valor,  U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') AS FiltroTexto
	  FROM CONTROL.CONTROL.dbo.CANALIZACION_SUPERVISORES S,
	  CONTROL.CONTROL.dbo.CANALIZACION_CUENTAS CC,
	  CONTROL.CONTROL.dbo.CANALIZACIONES C,
	   CONTROL.CONTROL.DBO.USUARIOS U
	  WHERE C.IDCANALIZACION = CC.IDCANALIZACION AND C.IDEMPRESA = @IDEMPRESA
	  AND   U.IDUSUARIO = S.IDUSUARIO AND S.IDCANALIZACION = C.IDCANALIZACION
	  AND CC.IDSUPERVISOR = S.IDSUPERVISOR AND U.IDEMPRESA = C.IDEMPRESA
	  GROUP BY  U.Idusuario ,  U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') 
	  ORDER BY FiltroTexto
END


IF @CATEGORIA = 1 AND @FILTRO = 14
BEGIN
	 SELECT U.Idusuario AS Valor,  U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') AS FiltroTexto 
	 FROM <#SESSION.DB/>.DBO.USUARIOS U, 
	 <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO, 8, 0) UA,
	  <#SESSION.DB/>.DBO.CANALIZACIONES C 
	 WHERE U.IDUSUARIO = UA.ID AND U.IDUSUARIO = C.IDUSUARIO 
	  group by U.Idusuario,  U.NOMBRE+' '+ISNULL(U.APELLIDOS,'')
	  ORDER BY FiltroTexto
	 
END

IF @CATEGORIA = 1 AND @FILTRO = 15
BEGIN
	 SELECT E.Idempresa AS Valor,  E.compania AS FiltroTexto
	  FROM CONTROL.CONTROL.dbo.CANALIZACION_DISTRIBUIDORES S,
	  CONTROL.CONTROL.dbo.CANALIZACION_CUENTAS CC,
	  CONTROL.CONTROL.dbo.CANALIZACIONES C,
	   CONTROL.CONTROL.DBO.EMPRESAS E
	  WHERE C.IDCANALIZACION = CC.IDCANALIZACION AND C.IDEMPRESA = @IDEMPRESA
	  AND   S.IDCANALIZACION = C.IDCANALIZACION
	  AND CC.IDDISTRIBUIDOR = S.IDDISTRIBUIDOR AND E.IDEMPRESA = S.IDEMPRESA
	  GROUP BY  E.Idempresa ,  E.Compania 
	  ORDER BY FiltroTexto
	 
END

IF @CATEGORIA = 1 AND @FILTRO = 16
BEGIN
	 SELECT ISNULL(ZL.IDZONA, 0) AS Valor, ISNULL(ZONA, 'Sin asignar') AS FiltroTexto
	  FROM CONTROL.CONTROL.dbo.CANALIZACION_CLUSTERS CL
	  LEFT JOIN CONTROL.CONTROL.dbo.CANALIZACION_ZONAS ZL ON ZL.IDZONA = CL.IDZONA ,
	  CONTROL.CONTROL.dbo.CANALIZACIONES C 
	  WHERE C.IDCANALIZACION = CL.IDCANALIZACION AND C.IDEMPRESA = @IDEMPRESA
	  GROUP BY ZL.IDZONA, ZONA
	 
END

IF @CATEGORIA = 2 AND @FILTRO = 5
BEGIN
	 SELECT IDFASE AS Valor,FASE AS FiltroTexto
	 FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES
	  WHERE IDEMPRESA = @IDEMPRESA
	  ORDER BY FASE ASC
	 
END
