//[session.idempresa|Untyped,idca|Integer,session.db|Untyped,]
--select
/*PROTEGIDO*/
DECLARE @IDEMPRESA INT, @IDPADRE INT, @IDCARPETA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDCARPETA = CAST(ISNULL(:IDCA,0) AS INT)

SELECT IdPadre, @IDCARPETA AS IDCA FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS WHERE IDCARPETA = @IDCARPETA AND IDEMPRESA = @IDEMPRESA 