//[session.idempresa|Untyped,iddistribucion|Integer,session.db|Untyped,]
--SELECT

DECLARE @IDEMPRESA INT
DECLARE @IDDISTRIBUCION INT


SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDDISTRIBUCION = ISNULL(:IDDISTRIBUCION, 0) 

SELECT * FROM <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION WHERE IDEMPRESA = @IDEMPRESA AND IDDISTRIBUCION = @IDDISTRIBUCION