//[session.idempresa|Untyped,tkcom|Text,idusuarioup|Integer,session.db|Untyped,]
--UPDATE

DECLARE @IDEMPRESA INT
DECLARE @TKCOM VARCHAR(128) 
DECLARE @IDUSUARIOUP INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/> 
SET @TKCOM  = ISNULL(:TKCOM, '')
SET @IDUSUARIOUP = ISNULL(:IDUSUARIOUP, '')
  
UPDATE <#SESSION.DB/>.DBO.COMPANIAS 
SET IDUSUARIO=@IDUSUARIOUP 
WHERE IDEMPRESA=@IDEMPRESA AND TKCOM = @TKCOM

