//[session.idempresa|Untyped,session.db|Untyped,]
--select
DECLARE @IDEMPRESA INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT 'Folio-'+CAST(<#SESSION.DB/>.dbo.PreparaNumero((NUMFOLIO+1), 5) AS VARCHAR(128)) AS NUMFOLIO  FROM <#SESSION.DB/>.dbo.empresas WHERE IDEMPRESA =@IDEMPRESA
UPDATE <#SESSION.DB/>.dbo.EMPRESAS SET NUMFOLIO=(NUMFOLIO+1) WHERE IDEMPRESA=@IDEMPRESA