//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

IF (SELECT COUNT(*) FROM  <#SESSION.DB/>.DBO.EMPRESAS_CONTACTO EC WHERE  EC.IDEMPRESA=@IDEMPRESA) = 0
BEGIN
  INSERT INTO  <#SESSION.DB/>.DBO.EMPRESAS_CONTACTO (IDEMPRESA , EMPRESA, TELEFONOS, IDPAIS, IDESTADO, IDMUNICIPIO)
  SELECT IDEMPRESA, COMPANIA, TELEFONO, PAIS_DEFAULT, ESTADO_DEF, 0 FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA =@IDEMPRESA 
END 

SELECT    dbo.preparacadena(EC.EMPRESA) AS EMPRESA, dbo.preparacadena(EC.CONTACTO_NOMBRE) AS NOMBRE, dbo.preparacadena(EC.CONTACTO_APELLIDOS) AS APELLIDOS, dbo.preparacadena(EC.CORREO) AS CORREO,
        EC.TELEFONOS, dbo.preparacadena(EC.CALLE) AS CALLE,dbo.preparacadena( EC.COLONIA) AS COLONIA, dbo.preparacadena(EC.CIUDAD) AS CIUDAD,EC.IDPAIS, EC.IDMUNICIPIO, EC.IDESTADO, P.PAIS, EDO.ESTADO, MUN.MUNICIPIO, LATITUD, LONGITUD, CP, EC.IDESTADO, EC.IDMUNICIPIO, EC.URL
FROM  <#SESSION.DB/>.DBO.EMPRESAS_CONTACTO EC  JOIN PAISES P ON EC.IDPAIS=P.IDPAIS
LEFT JOIN ESTADOS EDO ON EC.IDESTADO=EDO.IDESTADO and EDO.IDPAIS=P.IDPAIS
LEFT JOIN MUNICIPIOS MUN ON EC.IDMUNICIPIO=MUN.IDMUNICIPIO AND  EC.IDESTADO=MUN.IDESTADO
WHERE EC.IDEMPRESA=@IDEMPRESA 