//[b64|Text,iddocumento|Integer,session.db|Untyped,]
--insert
DECLARE @B64 VARCHAR(MAX)
DECLARE @IDDOCUMENTO INT
SET @B64=ISNULL(:B64,NULL)
SET @IDDOCUMENTO=ISNULL(:IDDOCUMENTO,0)

--IF (@B64!='' AND @B64 IS NOT NULL)
  -- BEGIN
   		UPDATE <#SESSION.DB/>.DBO.EMPRESAS_DOCUMENTOS SET MINIATURA=@B64 WHERE IDDOCUMENTO=@IDDOCUMENTO
   
   --END