//[iarch|Integer,session.db|Untyped,]
--DELETE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDARCHIVO INT
SET @IDARCHIVO = ISNULL(:iArch,0)

DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS 
WHERE IDPROSPECTOARCHIVO = @IDARCHIVO     