//[session.idempresa|Untyped,session.idusuario|Untyped,idd|Integer,ido|Integer,idp|Integer,session.db|Untyped,]
--select 
DECLARE @ETIQUETAS VARCHAR(MAX)
DECLARE @TBCAMPOPERSONALIZADOS TABLE( DESCRIPCION VARCHAR(MAX), CAMPO VARCHAR(MAX), OcultarCaptura VARCHAR(MAX))
DECLARE @IDEMPRESA INT, @IDDOCUMENTO INT, @IDUSUARIO INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDDOCUMENTO = ISNULL(:IDD,0)
SET @IDOPORTUNIDAD = ISNULL(:IDO,0)
SET @IDPROSPECTO = ISNULL(:IDP,0)

IF @IDPROSPECTO = 0 BEGIN SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD END

SELECT @ETIQUETAS = ETIQUETAS FROM <#SESSION.DB/>.dbo.EMPRESAS_DOCUMENTOS WHERE IDEMPRESA = @IDEMPRESA AND IDDOCUMENTO = @IDDOCUMENTO
/*SET @ETIQUETAS =  @ETIQUETAS + ',[CP13],[CPO21]'*/

INSERT INTO @TBCAMPOPERSONALIZADOS (DESCRIPCION, CAMPO)
SELECT DESCRIPCION, ETIQUETA FROM SALESUP_CT.dbo.LISTADO_ETIQUETAS

INSERT INTO @TBCAMPOPERSONALIZADOS (DESCRIPCION, CAMPO, OcultarCaptura)
SELECT EC.NOMBRE_CAMPO,
CASE WHEN EC.TIPO IN (1,3) THEN '[CP'+CAST(EC.INDICE AS VARCHAR(12))+']' WHEN EC.TIPO IN (2,4) THEN '[CPO'+CAST(EC.INDICE AS VARCHAR(12))+']' END,
CASE WHEN EC.INDICE IN (33,34) THEN '1' ELSE '' END AS OcultarCaptura
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC 
WHERE EC.IDEMPRESA = @IDEMPRESA

SELECT SPLITVALUE AS Etiqueta, Descripcion, @IDDOCUMENTO AS IDD,@IDOPORTUNIDAD AS IDO, @IDPROSPECTO AS IDP,
CASE 
  WHEN SPLITVALUE  = '[FOLIO]' THEN ''
  WHEN CP.CAMPO IS NULL  AND SPLITVALUE  = '[WEBSITE]' THEN <#SESSION.DB/>.dbo.ObtieneEtiquetasPlantillas( @IDPROSPECTO, @IDUSUARIO, @IDEMPRESA, REPLACE(REPLACE(SP.SPLITVALUE,'[',''),']','') , @IDOPORTUNIDAD )
  WHEN CP.CAMPO IS NULL  AND SPLITVALUE  = '[EJECUTIVOEMPRESADIRECCION]' THEN <#SESSION.DB/>.dbo.ObtieneEtiquetasPlantillas( @IDPROSPECTO, @IDUSUARIO, @IDEMPRESA, REPLACE(REPLACE(SP.SPLITVALUE,'[',''),']','') , @IDOPORTUNIDAD )
  WHEN CP.CAMPO IS NULL  AND SPLITVALUE  = '[MUNICIPIO]' THEN <#SESSION.DB/>.dbo.ObtieneEtiquetasPlantillas( @IDPROSPECTO, @IDUSUARIO, @IDEMPRESA, REPLACE(REPLACE(SP.SPLITVALUE,'[',''),']','') , @IDOPORTUNIDAD )
  WHEN CP.CAMPO IS NULL  AND SPLITVALUE  LIKE '[TBL_%' THEN ''
  WHEN CP.CAMPO IS NOT NULL THEN <#SESSION.DB/>.dbo.ObtieneEtiquetasPlantillas( @IDPROSPECTO, @IDUSUARIO, @IDEMPRESA, REPLACE(REPLACE(SP.SPLITVALUE,'[',''),']','') , @IDOPORTUNIDAD )
  ELSE ''    
END AS Valor,
CASE SPLITVALUE WHEN '[TBL_PRODUCTOS]' THEN 1
WHEN '[TBL_PRODUCTOS_SIN_IMG]' THEN 1
WHEN '[TBL_PRODUCTOS_SOLO_IMG1]' THEN 1
WHEN '[B64_LOGO_EMPRESA]' THEN 1
ELSE OcultarCaptura END AS OcultarCaptura,
CASE SPLITVALUE 
WHEN '[FOLIO]' THEN '1'
ELSE '' END AS SugerirDato
FROM SALESUP_CT.dbo.SPLIT(@ETIQUETAS, ',') SP 
LEFT JOIN @TBCAMPOPERSONALIZADOS CP ON CP.CAMPO = SP.SPLITVALUE
ORDER BY 1 