//[session.idusuario|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,idcarpeta|Text,descripcion|Text,idpeticion|Text,archivo|Text,session.db|Untyped,]
--select
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @IDGRUPO INT
DECLARE @IDCARPETA INT
DECLARE @PATHFILE VARCHAR(MAX)
DECLARE @XMLFILENAME VARCHAR(MAX)
DECLARE @DESCRIPCION VARCHAR(MAX)
DECLARE @IDPETICION VARCHAR(MAX)
DECLARE @NombreFile VARCHAR(MAX)

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDGRUPO   = CAST('<#SESSION.IDGRUPO/>' AS INT)
SET @IDCARPETA = CAST(:IDCARPETA AS INT)
SET @PATHFILE  = 'C:\FileRepository\'
SET @DESCRIPCION = :DESCRIPCION
SET @IDPETICION  = :IDPETICION
SET @NombreFile  = :ARCHIVO

SELECT @XMLFILENAME= dbo.PreparaCadena(@NombreFile)


EXEC <#SESSION.DB/>.DBO.SP_SUBIR_ARCHIVO_XML @IDUSUARIO,@IDEMPRESA,@IDGRUPO,@IDCARPETA,@PATHFILE,@XMLFILENAME,@DESCRIPCION	   