//[session.idempresa|Untyped,orden|Text,idregla|Text,session.db|Untyped,]
--UPDATE
DECLARE @IDEMPRESA AS INT
DECLARE @ORDEN VARCHAR(MAX)
DECLARE @IDREGLA VARCHAR(MAX)


SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @ORDEN = ISNULL(:ORDEN,'')  
SET @IDREGLA = ISNULL(:IDREGLA,'')

UPDATE ED SET ED.ORDEN = O.SPLITVALUE
FROM SALESUP_CT.DBO.SPLIT(@ORDEN,',') O
JOIN SALESUP_CT.DBO.SPLIT(@IDREGLA,',') ID ON ID.OCCURENCEID = O.OCCURENCEID
JOIN <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION ED ON ED.IDDISTRIBUCION = ID.SPLITVALUE AND ED.IDEMPRESA = @IDEMPRESA AND O.SPLITVALUE != ED.ORDEN