//[agregarotro|Integer,agregaryver|Integer,editar|Integer,session.idusuario|Untyped,session.idempresa|Untyped,industria|Integer,pais|Text,estado|Text,empmunicipio|Integer,grupoempresarial|Integer,tkcom|Text,paginaweb|Text,telefonocorporativo|Text,calle|Text,colonia|Text,numinterior|Text,numexterior|Text,ciudad|Text,codigopostal|Text,nempleados|Integer,campo1c|Text,campo2c|Text,campo3c|Text,campo4c|Text,campo5c|Text,campo6c|Text,campo7c|Text,campo8c|Text,campo9c|Text,campo10c|Text,session.db|Untyped,nombre|Text,]
--SELECT
	DECLARE @EDITAR INT, @IDUSUARIO INT, @IDEMPRESA INT, @IDINDUSTRIA INT, @IDMUNICIPIO INT, @IDGRUPOEMPRESARIAL INT, @IDPAIS VARCHAR(2), @IDESTADO VARCHAR(4)
	DECLARE @TKCOM VARCHAR(64), @EMPRESA VARCHAR(512), @URL VARCHAR(1024), @TELEFONO VARCHAR(128), @DIRECCION1 VARCHAR(512), @DIRECCION2 VARCHAR(512), @NUM_INT VARCHAR(512), @NUM_EXT VARCHAR(512)
	DECLARE	@CIUDAD VARCHAR(128), @CODPOSTAL VARCHAR(16), @NEMPLEADOS INT, @CCAMP1 VARCHAR(1024), @CCAMP2 VARCHAR(1024), @CCAMP3 VARCHAR(1024), @CCAMP4 VARCHAR(1024), @CCAMP5 VARCHAR(1024)
	DECLARE @CCAMP6 VARCHAR(1024), @CCAMP7 VARCHAR(1024), @CCAMP8 VARCHAR(1024), @CCAMP9 VARCHAR(1024), @CCAMP10 VARCHAR(1024)
	DECLARE @AGREGARVER INT, @CREAROTRO INT
	
	SET @CREAROTRO = ISNULL(:AgregarOtro,0)
	SET @AGREGARVER = ISNULL(:AgregaryVer,0)
	SET @EDITAR = ISNULL(:Editar,0)
	SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
	SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
	SET @IDINDUSTRIA = ISNULL(:Industria,0)
	SET @IDPAIS = ISNULL(:Pais,'')
	SET @IDESTADO = ISNULL(:Estado,'')
	SET @IDMUNICIPIO = ISNULL(:EmpMunicipio,0)
	SET @IDGRUPOEMPRESARIAL = ISNULL(:GrupoEmpresarial,0)
	SET @TKCOM = ISNULL(:tkCom,'')
	SET @EMPRESA =  SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Nombre,''))
	SET @URL = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:PaginaWeb,''))
	SET @TELEFONO = ISNULL (:TelefonoCorporativo,'')
	SET @DIRECCION1 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Calle,''))
	SET @DIRECCION2 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Colonia,''))
	SET @NUM_INT = 	SALESUP_CT.DBO.PREPARACADENA(ISNULL(:NumInterior,''))
	SET @NUM_EXT = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:NumExterior,''))
	SET @CIUDAD = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Ciudad,''))
	SET @CODPOSTAL = ISNULL(:CodigoPostal,'')
	SET @NEMPLEADOS = ISNULL(:nEmpleados,0)
	SET @CCAMP1 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo1C,''))
	SET @CCAMP2 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo2C,''))
	SET @CCAMP3 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo3C,''))
	SET @CCAMP4 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo4C,''))
	SET @CCAMP5 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo5C,''))
	SET @CCAMP6 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo6C,''))
	SET @CCAMP7 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo7C,''))
	SET @CCAMP8 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo8C,''))
	SET @CCAMP9 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo9C,''))
	SET @CCAMP10 = SALESUP_CT.DBO.PREPARACADENA(ISNULL(:Campo10C,''))
	
	EXEC <#SESSION.DB/>.DBO.SP_COMPANIA_AGREGAR_EDITAR @EDITAR,@TKCOM,@IDUSUARIO,@IDEMPRESA,@IDINDUSTRIA,@IDPAIS,@IDESTADO,@IDMUNICIPIO,
	@IDGRUPOEMPRESARIAL,@EMPRESA,@URL,@TELEFONO,@DIRECCION1,@DIRECCION2,@NUM_INT,@NUM_EXT,@CIUDAD,@CODPOSTAL,@NEMPLEADOS,
	@CCAMP1,@CCAMP2,@CCAMP3,@CCAMP4,@CCAMP5,@CCAMP6,@CCAMP7,@CCAMP8,@CCAMP9,@CCAMP10
	
	SELECT TOP 1 @TKCOM = TKCOM FROM <#SESSION.DB/>.DBO.COMPANIAS WHERE @EMPRESA = EMPRESA AND @IDEMPRESA = IDEMPRESA
	
	SELECT @TKCOM AS tkcom, @AGREGARVER AS Ver, @CREAROTRO AS Otro 