//[session.idempresa|Untyped,idregla|Integer,status|Integer,session.db|Untyped,]
--UPDATE

DECLARE @IDEMPRESA INT
DECLARE @IDDISTRIBUCION INT
DECLARE @STATUS INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDDISTRIBUCION = ISNULL(:IDREGLA, 0)
SET @STATUS = ISNULL(:STATUS, 0)

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION SET ACTIVO = @STATUS WHERE IDEMPRESA = @IDEMPRESA AND IDDISTRIBUCION = @IDDISTRIBUCION