//[session.idempresa|Untyped,idca|Integer,tc|Integer,carpetaid|Integer,session.db|Untyped,foldercarpeta|Text,]
--INSERT

DECLARE @IDEMPRESA INT, @NIVEL INT, @IDPADRE INT, @TIPOCARPETA INT, @IDCARPETA INT
DECLARE @CARPETA VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDPADRE = CAST(IsnULL(:IDCA,0) AS INT)
SET @TIPOCARPETA = CAST(ISNULL(:TC,0) AS INT)
SET @CARPETA = :FolderCarpeta
SET @IDCARPETA = CAST(ISNULL(:carpetaId,0) AS INT)


IF @IDCARPETA = 0
BEGIN
	 INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS (CARPETA, IDEMPRESA, TIPOCARPETA, IDPADRE)
	 VALUES (@CARPETA, @IDEMPRESA, @TIPOCARPETA, @IDPADRE)
END

IF @IDCARPETA > 0
BEGIN
	 UPDATE <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS SET CARPETA = @CARPETA 
	 WHERE IDEMPRESA = @IDEMPRESA AND IDCARPETA = @IDCARPETA
END