//[session.idempresa|Untyped,empresa|Text,nombre|Text,apellido|Text,correo|Text,telefono|Text,calle|Text,colonia|Text,ciudad|Text,cp|Text,selectpais|Text,selectestado|Text,selectmunicipio|Integer,latitud|Text,longitud|Text,url|Text,session.db|Untyped,]
--UPDATE

DECLARE @IDEMPRESA INT 
DECLARE @EMPRESA VARCHAR(128) 
DECLARE @NOMBRE VARCHAR(128)
DECLARE @APELLIDO VARCHAR (128)  
DECLARE @CORREO VARCHAR(128) 
DECLARE @TELEFONO VARCHAR(128) 
DECLARE @CALLE VARCHAR(128) 
DECLARE @COLONIA VARCHAR(128) 
DECLARE @CIUDAD VARCHAR(128) 
DECLARE @CP VARCHAR(128) 
DECLARE @IDPAIS VARCHAR(20) 
DECLARE @IDESTADO VARCHAR(20) 
DECLARE @IDMUNICIPIO INT 
DECLARE @LATITUD VARCHAR(64)
DECLARE @LONGITUD  VARCHAR(64)
DECLARE @URL  VARCHAR(1024)


SET @IDEMPRESA=<#SESSION.IDEMPRESA/> 
SET @EMPRESA  =DBO.PREPARACADENA(ISNULL(:EMPRESA, '')) 
SET @NOMBRE=DBO.PREPARACADENA(ISNULL(:NOMBRE, ''))  
SET @APELLIDO=DBO.PREPARACADENA(ISNULL(:APELLIDO, '')) 
SET @CORREO=DBO.PREPARACADENA(ISNULL(:CORREO, ''))
SET @TELEFONO= DBO.PREPARACADENA(ISNULL(:TELEFONO, ''))
SET @CALLE=DBO.PREPARACADENA(ISNULL(:CALLE, ''))
SET @COLONIA= DBO.PREPARACADENA(ISNULL(:COLONIA, '')) 
SET @CIUDAD=DBO.PREPARACADENA(ISNULL(:CIUDAD, '') ) 
SET @CP=ISNULL(:CP, '')  
SET @IDPAIS=ISNULL(:SELECTPAIS, '')  
SET @IDESTADO=ISNULL(:SELECTESTADO, '')  
SET @IDMUNICIPIO= ISNULL(:SELECTMUNICIPIO, '')
SET @LATITUD=ISNULL(:LATITUD, '')
SET @LONGITUD=ISNULL(:LONGITUD, '')
SET @URL=ISNULL(:URL, '')
  

IF (@IDMUNICIPIO=0) SET @IDMUNICIPIO=''

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_CONTACTO

SET 

EMPRESA=@EMPRESA,
URL =@URL,
CONTACTO_NOMBRE=@NOMBRE,
CONTACTO_APELLIDOS=@APELLIDO,
CORREO=@CORREO, 
TELEFONOS=@TELEFONO,
CALLE=@CALLE,
COLONIA=@COLONIA,
CIUDAD=@CIUDAD,
CP=@CP,
IDPAIS=@IDPAIS ,
IDESTADO=@IDESTADO,
IDMUNICIPIO=@IDMUNICIPIO,
LATITUD=@LATITUD,
LONGITUD=@LONGITUD

WHERE IDEMPRESA=@IDEMPRESA


UPDATE CONTROL.CONTROL.DBO.EMPRESAS_CONTACTO
SET 
EMPRESA=@EMPRESA,
CONTACTO_NOMBRE=@NOMBRE,
CONTACTO_APELLIDOS=@APELLIDO,
CORREO=@CORREO,
TELEFONOS=@TELEFONO,
CALLE=@CALLE,
COLONIA=@COLONIA,
CIUDAD=@CIUDAD,
CP=@CP,
IDPAIS=@IDPAIS ,
IDESTADO=@IDESTADO,
IDMUNICIPIO=@IDMUNICIPIO,
LATITUD=@LATITUD,
LONGITUD=@LONGITUD

WHERE IDEMPRESA=@IDEMPRESA