//[session.idempresa|Untyped,]
--select


DECLARE @TOKEN uniqueidentifier
DECLARE @IDEMPRESA INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TOKEN = NEWID()

UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET TOKEN=@TOKEN WHERE IDEMPRESA = @IDEMPRESA

SELECT CAST(@TOKEN AS VARCHAR(MAX)) as TOKEN

