//[session.idempresa|Untyped,idregla|Integer,session.db|Untyped,]
--DELETE

DECLARE @IDEMPRESA INT
DECLARE @IDDISTRIBUCION INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDDISTRIBUCION = ISNULL(:IDREGLA, 0)

DELETE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION_USUARIOS WHERE   IDDISTRIBUCION = @IDDISTRIBUCION
DELETE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION_FILTROS WHERE IDDISTRIBUCION = @IDDISTRIBUCION
DELETE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION WHERE IDEMPRESA = @IDEMPRESA AND IDDISTRIBUCION = @IDDISTRIBUCION





