//[session.idempresa|Untyped,session.db|Untyped,]
--select

DECLARE @IDEMPRESA INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SELECT ED.Orden, ED.Descripcion, 
	   CASE WHEN ED.IDPLANTILLA=0   THEN 'Default' 
	   WHEN ED.IDPLANTILLA=-1  THEN 'Ninguna' 
	   ELSE UP.DESCRIPCION END AS Plantilla,
	   CASE WHEN ED.TIPO= 1 THEN 'Prospectos' ELSE 'Clientes' END AS Tipo,
	   CASE WHEN ED.ACTIVO=1 THEN 'Activo' ELSE 'Inactivo' END AS ACTIVO,
	   ED.IDUSUARIOS as Asignado,
	   ED.ACTIVO AS STATUS,
	   CASE WHEN REGLA_DEFAULT IS NULL THEN 0 ELSE 1 END AS REGLA_DEFAULT, 
	   <#SESSION.DB/>.DBO.Obtiene_ListaNombre_Usuarios(@IDEMPRESA, IDUSUARIOS) AS LISTA_USUARIOS,
	   ED.IDDISTRIBUCION as Id
	   FROM <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION ED
	   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP ON ED.IDPLANTILLA = UP.IDPLANTILLA
	   		WHERE ED.IDEMPRESA=@IDEMPRESA 
	   		ORDER BY ED.ORDEN ASC, IDDISTRIBUCION DESC
