//[session.idempresa|Untyped,session.idusuario|Untyped,idgrupodoc|Integer,visdoc|Integer,amazon|Integer,tipoarchivo|Integer,descdoc|Text,pesokb|Numeric,nombrearchivo|Text,idcarpeta|Integer,session.db|Untyped,]
--insert
DECLARE @HD_USADO FLOAT
DECLARE @PESOKB FLOAT
DECLARE @ARCHIVO VARCHAR(2000), @DESCRIPCION VARCHAR(MAX), @TIPO VARCHAR(6)
DECLARE @TIPOARCHIVO INT, @IDEMPRESA INT, @IDUSUARIO INT, @IDGRUPO INT, @VISIBILIDAD INT, @AMAZON INT, @IDCARPETA INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDGRUPO = CAST(ISNULL(:IDGRUPODOC,0) AS INT)
SET @VISIBILIDAD = CAST(ISNULL(:VISDOC,0) AS INT)
SET @AMAZON = CAST(ISNULL(:AMAZON,0) AS INT)
SET @TIPOARCHIVO = CAST(ISNULL(:TIPOARCHIVO,0) AS INT)
SET @DESCRIPCION = CAST(ISNULL(:DESCDOC,'') as varchar(8000))
SET @PESOKB = CAST(ISNULL(:pesokb,0) AS FLOAT)
SET @HD_USADO = 0
SET @ARCHIVO = LTRIM(RTRIM(:NOMBREARCHIVO))
SET @TIPO = 'DO'
SET @IDCARPETA = CAST(ISNULL(:IDCARPETA,0) AS INT)
IF @TIPOARCHIVO = 1 BEGIN SET @TIPO = 'IMG' END


INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_DOCUMENTOS (IDEMPRESA, IDUSUARIO, IDGRUPO, DESCRIPCION, VISIBILIDAD, NOMBRE_DOCUMENTO, AMAZON, TIPOARCHIVO, IDCARPETA) 
VALUES (@IDEMPRESA, @IDUSUARIO, @IDGRUPO, @DESCRIPCION, @VISIBILIDAD, @ARCHIVO, @AMAZON, @TIPOARCHIVO, @IDCARPETA)

IF @IDCARPETA > 0
BEGIN
	 UPDATE EC SET ARCHIVOS = ISNULL(ARCHIVOS,0) + 1
	 FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS EC WHERE IDCARPETA = @IDCARPETA AND IDEMPRESA = @IDEMPRESA
END
	 
IF(@ARCHIVO!='')
BEGIN
	 INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_ARCHIVOS_AMAZON (IDEMPRESA, IDUSUARIO, ARCHIVO, PESO, TIPO) VALUES (@IDEMPRESA, @IDUSUARIO, @ARCHIVO, @PESOKB, @TIPO)
END	 
