//[session.idempresa|Untyped,descripcion|Text,orden|Integer,plantillas|Integer,entidad|Integer,origen|Integer,criterio|Integer,jsonlistarusuarios|Text,jsoncriterio|Text,etiquetas|Text,cantidad|Integer,periodo|Integer,eseditar|Integer,iddistribucion|Integer,session.db|Untyped,]
--insert

DECLARE @IDEMPRESA INT
DECLARE @DESCRIPCION VARCHAR(MAX)
DECLARE @ORDEN INT
DECLARE @IDPLANTILLA INT
DECLARE @TIPO INT
DECLARE @ORIGEN INT
DECLARE @TIPO_PROCEDIMIENTO INT
DECLARE @IDUSUARIOS VARCHAR(MAX)
DECLARE @IDGRUPOS VARCHAR(MAX)
DECLARE @IDETIQUETAS VARCHAR(MAX)
DECLARE @FILTROS VARCHAR(MAX)
DECLARE @CANTIDAD INT 
DECLARE @PERIODO INT



SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @DESCRIPCION = ISNULL(:DESCRIPCION, '')
SET @ORDEN = ISNULL(:ORDEN, 1)
SET @IDPLANTILLA= ISNULL(:PLANTILLAS,0)
SET @TIPO = ISNULL(:ENTIDAD, 0)
SET @ORIGEN =ISNULL(:ORIGEN, 0)
SET @TIPO_PROCEDIMIENTO =ISNULL(:CRITERIO, 0)
SET @IDUSUARIOS =ISNULL(:jsonListarUsuarios,'')
SET @FILTROS = ISNULL(:jsonCriterio, '')
SET @IDGRUPOS = ''
SET @IDETIQUETAS = ISNULL(:Etiquetas, '')
SET @CANTIDAD = ISNULL(:CANTIDAD, 0)
SET @PERIODO = ISNULL(:PERIODO, 0)

/*Variables Editar*/
DECLARE @ES_EDITAR INT
DECLARE @IDDISTRIBUCION INT

SET @ES_EDITAR= ISNULL(:ESEDITAR, 0)
SET @IDDISTRIBUCION= ISNULL(:IDDISTRIBUCION, 0)


IF(@ES_EDITAR = 0)
BEGIN
	INSERT <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION (IDEMPRESA, DESCRIPCION, ORDEN, IDPLANTILLA, TIPO, ORIGEN, TIPO_PROCEDIMIENTO, IDUSUARIOS, IDGRUPOS, ACTIVO, IDETIQUETAS, CANTIDAD, PERIODO)
	VALUES(@IDEMPRESA, @DESCRIPCION, @ORDEN, @IDPLANTILLA, @TIPO, @ORIGEN, @TIPO_PROCEDIMIENTO, @IDUSUARIOS, @IDGRUPOS, 1, @IDETIQUETAS, @CANTIDAD, @PERIODO)

	SELECT TOP 1 @IDDISTRIBUCION = IDDISTRIBUCION FROM <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION WHERE IDEMPRESA = @IDEMPRESA ORDER BY IDDISTRIBUCION DESC
END
ELSE
BEGIN

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION 
	SET DESCRIPCION = @DESCRIPCION,
		IDPLANTILLA = @IDPLANTILLA, 
		TIPO = @TIPO, 
		ORIGEN = @ORIGEN,
		TIPO_PROCEDIMIENTO = @TIPO_PROCEDIMIENTO, 
		IDUSUARIOS = @IDUSUARIOS, 
		IDETIQUETAS = @IDETIQUETAS, 
		CANTIDAD = @CANTIDAD, 
		PERIODO = @PERIODO,
		IDULTIMOUSUARIO=NULL
	WHERE IDEMPRESA = @IDEMPRESA AND IDDISTRIBUCION= @IDDISTRIBUCION
	
	DELETE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION_USUARIOS WHERE IDDISTRIBUCION = @IDDISTRIBUCION
	DELETE <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION_FILTROS WHERE IDDISTRIBUCION = @IDDISTRIBUCION

END


DECLARE @TEMPORAL AS TABLE (ID INT IDENTITY, TIPOCRITERIO VARCHAR(MAX),CRITERIO VARCHAR(MAX), OPERADOR VARCHAR(MAX), OPERADORUSUARIO VARCHAR(MAX), VALORUSUARIO VARCHAR(MAX))

SELECT @FILTROS = SALESUP_CT.DBO.BASE64TOVARCHAR(@FILTROS)

 IF OBJECT_ID('tempdb..#TempTABLA_J1') IS NOT NULL
      DROP TABLE #TempTABLA_J1

    SELECT * INTO  #TempTABLA_J1 FROM dbo.parseJSON(@FILTROS) 

	INSERT INTO @TEMPORAL (TIPOCRITERIO,CRITERIO, OPERADOR, OPERADORUSUARIO, VALORUSUARIO)
	SELECT p1.stringvalue,p2.stringvalue,p3.stringvalue,p4.stringvalue,p5.stringvalue
	FROM   #TempTABLA_J1 P1, #TempTABLA_J1 P2 , #TempTABLA_J1 P3 ,
      #TempTABLA_J1 P4 , #TempTABLA_J1 P5 
	  WHERE  P1.PARENT_ID IS NOT NULL 
      AND P1.parent_id=P2.parent_id
      AND P1.name='tipoCriterio' and p2.name='criterio'
      and P1.parent_id=P3.parent_id AND P3.name='operador' 
      and P1.parent_id=P4.parent_id AND P4.name='OperadorUsuario'
      and P1.parent_id=P5.parent_id AND P5.name='ValorUsuario'

INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_DISTRIBUCION_FILTROS (IDDISTRIBUCION, IDTIPOFILTRO, FILTROVALOR, IDOPERADOR_SQL, IDOPERADOR_USUARIO, IDTIPOCRITERIO)
SELECT 
@IDDISTRIBUCION,
CASE WHEN TIPOCRITERIO=0 THEN CRITERIO ELSE TIPOCRITERIO END AS IDTIPOFILTRO,
CASE WHEN TIPOCRITERIO=0 THEN VALORUSUARIO ELSE CRITERIO END AS FILTROVALOR,
OPERADOR,
CASE WHEN TIPOCRITERIO=0 THEN OPERADORUSUARIO ELSE 0 END AS OPERADORUSUARIO,
CASE WHEN TIPOCRITERIO=0 THEN 0 ELSE 1 END AS IDTIPOCRITERIO
 FROM @TEMPORAL
 
 
 EXEC  <#SESSION.DB/>.DBO.SP_CREA_SQL_COMPILADO_DISTRIBUCION @IDDISTRIBUCION, @IDEMPRESA
 EXEC <#SESSION.DB/>.DBO.SP_CALCULA_PORCENTAJE_ASIGNACION @IDDISTRIBUCION