//[idrelacion|Text,contacto|Text,direccion1|Text,direccion2|Text,telefono|Text,pais|Text,estado|Text,codigopostal|Text,latitud|Text,longitud|Text,empresa|Text,session.idempresa|Untyped,]
-- update

DECLARE @IDRELACION INT
DECLARE @CONTACTO VARCHAR(128)
DECLARE @DIRECCION1 VARCHAR(128)
DECLARE @DIRECCION2 VARCHAR(128)
DECLARE @TELEFONO VARCHAR(20)
DECLARE @IDPAIS VARCHAR(4)
DECLARE @IDESTADO VARCHAR(4)
DECLARE @CODIGOPOSTAL VARCHAR(50)
DECLARE @LATITUD VARCHAR(32)
DECLARE @LONGITUD VARCHAR(32)
DECLARE @EMPRESA VARCHAR(128)

SET @IDRELACION = CAST(:IDRELACION AS INT)
SET @CONTACTO   = :CONTACTO
SET @DIRECCION1 = :DIRECCION1 
SET @DIRECCION2 = :DIRECCION2 
SET @TELEFONO   = :TELEFONO 
SET @IDPAIS     = :PAIS 
SET @IDESTADO   = :ESTADO 
SET @CODIGOPOSTAL = :CODIGOPOSTAL 
SET @LATITUD  = :LATITUD 
SET @LONGITUD = :LONGITUD 
SET @EMPRESA  = :EMPRESA 

UPDATE control.control.dbo.empresas_relacionadas WITH(ROWLOCK) SET CONTACTO = @CONTACTO, DIRECCION1 = @DIRECCION1, DIRECCION2 = @DIRECCION2, TELEFONO = @TELEFONO, IDPAIS = @IDPAIS, IDESTADO = @IDESTADO, CODIGOPOSTAL = @CODIGOPOSTAL, LATITUD = @LATITUD, LONGITUD = @LONGITUD, EMPRESA = @EMPRESA 
WHERE idempresaorigen = <#SESSION.IDEMPRESA/> and canalizar = 1 AND IDRELACION = @IDRELACION