//[iddocumento|Integer,session.idempresa|Untyped,session.idusuario|Untyped,amazon|Integer,visdoc|Integer,idgrupodoc|Integer,pesokb|Numeric,nombrearchivo|Text,descdoc|Text,idcarpeta|Integer,tipoarchivo|Integer,carpetaactual|Integer,canalizado|Integer,comentarionotificacion|Text,session.db|Untyped,]
--SELECT
DECLARE @IDDOCUMENTO INT
DECLARE @ESAMAZON INT, @HAYARCHIVO INT, @IDEMPRESA INT, @IDUSUARIO INT, @IDGRUPO INT, @AMAZON INT, @VISIBILIDAD INT, @IDCARPETA INT, @IDCARPETA_ANTERIOR INT, @TIPOARCHIVO INT
DECLARE @ARCHIVO_ANTERIOR VARCHAR(5000), @NOMBRE_ARCHIVO VARCHAR(MAX), @TIPO VARCHAR(6), @TIPO_ANTERIOR VARCHAR(6)
DECLARE @DESCRIPCION VARCHAR(MAX)
DECLARE @SIZEOLG FLOAT, @PESOKB FLOAT
DECLARE @CANALIZADO INT
DECLARE @NOTIFICACION VARCHAR(MAX)

SET @IDDOCUMENTO = CAST(ISNULL(:iddocumento,0) AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @AMAZON = CAST(ISNULL(:AMAZON,0) AS INT)
SET @VISIBILIDAD = CAST(ISNULL(:VISDOC,0) AS INT)
SET @IDGRUPO = CAST(ISNULL(:IDGRUPODOC,0) AS INT)
SET @PESOKB = CAST(ISNULL(:pesokb,0) AS FLOAT)
SET @NOMBRE_ARCHIVO = LTRIM(RTRIM(ISNULL(:NOMBREARCHIVO,'')))
SET @DESCRIPCION = CAST(ISNULL(:DESCDOC,'') as varchar(MAX))
SET @IDCARPETA = CAST(ISNULL(:IDCARPETA,0) AS INT)
SET @TIPOARCHIVO = CAST(ISNULL(:TIPOARCHIVO,0) AS INT)
SET @TIPO = 'DO'
SET @IDCARPETA_ANTERIOR = CAST(ISNULL(:CarpetaActual,0) AS INT)
SET @ARCHIVO_ANTERIOR = ''
SET @CANALIZADO=CAST(ISNULL(:CANALIZADO,0) AS INT) 
SET @NOTIFICACION=(CASE WHEN @CANALIZADO=1 THEN ISNULL(:ComentarioNotificacion,'') ELSE NULL END)


IF @TIPOARCHIVO = 1 BEGIN SET @TIPO = 'IMG' END

IF @NOMBRE_ARCHIVO != ''
BEGIN
	SELECT @ARCHIVO_ANTERIOR = NOMBRE_DOCUMENTO, @TIPO_ANTERIOR = TIPOARCHIVO 
	FROM <#SESSION.DB/>.DBO.EMPRESAS_DOCUMENTOS 
	WHERE IDDOCUMENTO = @IDDOCUMENTO AND IDEMPRESA = @IDEMPRESA
	 
	DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE ARCHIVO = @ARCHIVO_ANTERIOR AND IDEMPRESA = @IDEMPRESA AND TIPO = 'DO'
	
	INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_ARCHIVOS_AMAZON (IDEMPRESA, IDUSUARIO, ARCHIVO, PESO, TIPO) VALUES (@IDEMPRESA, @IDUSUARIO, @NOMBRE_ARCHIVO, @PESOKB, @TIPO)

	UPDATE <#SESSION.DB/>.DBO.EMPRESAS_DOCUMENTOS 
	SET FECHA_MODIFICADO = GETDATE(), NOMBRE_DOCUMENTO = @NOMBRE_ARCHIVO, AMAZON = @AMAZON
	WHERE IDDOCUMENTO = @IDDOCUMENTO
	
END

IF @IDCARPETA != @IDCARPETA_ANTERIOR
	BEGIN
	 UPDATE EC SET ARCHIVOS = ISNULL(ARCHIVOS,0) - 1
	 FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS EC WHERE IDCARPETA = @IDCARPETA_ANTERIOR AND IDEMPRESA = @IDEMPRESA
	 
	 IF @IDCARPETA > 0
	 BEGIN
	 	UPDATE EC SET ARCHIVOS = ISNULL(ARCHIVOS,0) + 1
		 FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS EC WHERE IDCARPETA = @IDCARPETA AND IDEMPRESA = @IDEMPRESA
	 END
END

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_DOCUMENTOS 
SET 
	DESCRIPCION = @DESCRIPCION, 
	IDGRUPO = @IDGRUPO,
    VISIBILIDAD = @VISIBILIDAD,
    IDCARPETA = @IDCARPETA,
    FECHA_MODIFICADO = GETDATE(),
	NOTIFICACION=@NOTIFICACION
WHERE IDDOCUMENTO = @IDDOCUMENTO

DECLARE @IDPADRE INT, @TIPO_CARPETA_PADRE INT
DECLARE @PATH VARCHAR(MAX), @CARPETA_PADRE VARCHAR(MAX)
SET @PATH = ''

SELECT @PATH = '<li><i class=\"fa fa-folder-open fa-lg\"></i> '+CARPETA+'</li>', @IDPADRE = IDPADRE FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS WHERE IDCARPETA = @IDCARPETA
IF @IDPADRE > 0 
BEGIN
	SELECT @TIPO_CARPETA_PADRE = TIPOCARPETA, @CARPETA_PADRE = CARPETA FROM <#SESSION.DB/>.dbo.EMPRESAS_CARPETAS WHERE IDCARPETA = @IDPADRE
END


SELECT 
@ARCHIVO_ANTERIOR AS ArchivoAnterior, <#SESSION.DB/>.dbo.PreparaNumero(@IDEMPRESA,6) AS CarpetaEmpresa, 
@PATH AS Path, @TIPOARCHIVO AS TipoArchivo, @IDPADRE AS IdPadre, 
@TIPO_CARPETA_PADRE AS TIPO_CARPETA_PADRE, @CARPETA_PADRE AS CARPETA_PADRE
