//[session.idempresa|Untyped,movil|Text,session.db|Untyped,telefono_fijo|Text,telefono_movil|Text,]
-- Update
DECLARE @IDEMPRESA INT 
DECLARE @LINKDESKTOP_FIJO VARCHAR(256)
DECLARE @LINKDESKTOP_MOVIL VARCHAR(256)
DECLARE @LINKMOVIL VARCHAR(128)

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @LINKDESKTOP_FIJO=:telefono_fijo
SET @LINKDESKTOP_MOVIL=:TELEFONO_MOVIL
SET @LINKMOVIL=:MOVIL


UPDATE <#SESSION.DB/>.DBO.EMPRESAS
SET LINKDESKTOP_FIJO = @LINKDESKTOP_FIJO
	,LINKDESKTOP_MOVIL = @LINKDESKTOP_MOVIL
	,LINKMOVIL = @LINKMOVIL
WHERE IDEMPRESA = @IDEMPRESA