//[idpermiso|Integer,session.db|Untyped,]
--update
DECLARE @IDPERMISO INT
DECLARE @IDUSUARIO INT
DECLARE @IDMODULO INT
SET @IDPERMISO=CAST(ISNULL(:IDPERMISO,0) AS INT)

SELECT @IDUSUARIO=IDUSUARIO , @IDMODULO=IDMODULO FROM <#SESSION.DB/>.dbo.PERMISOS_MODULOS WHERE IDPERMISO=@IDPERMISO
IF ((@IDMODULO>=1 AND @IDMODULO<=4) OR @IDMODULO=8 )
 BEGIN
  IF @IDMODULO=8
    DELETE FROM <#SESSION.DB/>.dbo.USUARIOS_FILTROS WHERE IDUSUARIO=@IDUSUARIO AND IDPANTALLA IN (10,25,9,14,15,400,16,405)
  ELSE
    DELETE FROM <#SESSION.DB/>.dbo.USUARIOS_FILTROS WHERE IDUSUARIO=@IDUSUARIO AND IDPANTALLA=@IDMODULO
 END
DELETE FROM  <#SESSION.DB/>.dbo.PERMISOS_MODULOS WHERE IDPERMISO=@IDPERMISO