//[accion|Integer,idmodulo|Integer,tku|Text,session.db|Untyped,]
 --select
 DECLARE @IDUSUARIO INT
 DECLARE @ACCION INT
 DECLARE @IDMODULO INT
 DECLARE @TK VARCHAR(64)

 SET @ACCION=CAST(ISNULL(:ACCION,0) AS INT)
 SET @IDMODULO=CAST(ISNULL(:IDMODULO,0) AS INT)
 SET @TK = dbo.ValidaToken(ISNULL(:TKU,''))
 IF (@ACCION=0)
 BEGIN
  SELECT @IDUSUARIO=IDUSUARIO FROM <#SESSION.DB/>.dbo.USUARIOS WHERE TKU = @TK
  SELECT IdModulo, Modulo FROM <#SESSION.DB/>.dbo.V_MODULOS_PERMISOS 
	   WHERE IDMODULO NOT IN (SELECT IDMODULO FROM <#SESSION.DB/>.dbo.PERMISOS_MODULOS WHERE IDUSUARIO=@IDUSUARIO)
 END
 ELSE
	 SELECT IdModulo, Modulo FROM <#SESSION.DB/>.dbo.V_MODULOS_PERMISOS WHERE IDMODULO=@IDMODULO

 