//[accion|Integer,idmodulo|Integer,tku|Text,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT
DECLARE @ACCION INT
DECLARE @IDMODULO INT
DECLARE @TK VARCHAR(64)

SET @ACCION=CAST(ISNULL(:ACCION,0) AS INT)
SET @IDMODULO=CAST(ISNULL(:IDMODULO,0) AS INT)
SET @TK = dbo.ValidaToken(ISNULL(:TKU,''))

SELECT @IDUSUARIO=IDUSUARIO FROM <#SESSION.DB/>.dbo.USUARIOS WHERE TKU = @TK


select * from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(@IDUSUARIO,@IDMODULO,@ACCION)