//[tku|Text,session.db|Untyped,]
--select
/*PROTEGIDO*/
DECLARE @TKU VARCHAR(MAX)
DECLARE @IDUSUARIO INT
SET @TKU = dbo.ValidaToken(ISNULL(:TKU,''))
SET @IDUSUARIO=0

SELECT @IDUSUARIO=IDUSUARIO FROM <#SESSION.DB/>.DBO.usuarios WHERE TKU=@TKU
SELECT @TKU as tku,*,<#SESSION.DB/>.DBO.SplitChar(PM.IDPERSONAS,',',1) as Personas,<#SESSION.DB/>.DBO.SplitChar(PM.IDGRUPOS,',',2) as Grupos

FROM <#SESSION.DB/>.DBO.PERMISOS_MODULOS PM
	   LEFT JOIN <#SESSION.DB/>.DBO.V_MODULOS_PERMISOS M ON M.IDMODULO=PM.IDMODULO
 WHERE IDUSUARIO=@IDUSUARIO 
 ORDER BY M.IDMODULO ASC
