//[tk|Text,ltidusuarios|Text,ltidgrupos|Text,session.db|Untyped,]
--update
DECLARE @TK VARCHAR(64)
DECLARE @PERSONAS VARCHAR(MAX)
DECLARE @GRUPOS VARCHAR(MAX)
SET @TK= dbo.ValidaToken(:TK)
SET @PERSONAS=REPLACE(ISNULL(:LtIdUsuarios,''),'U','')
SET @GRUPOS=REPLACE(ISNULL(:LtIdGrupos,''),'G','')

UPDATE <#SESSION.DB/>.dbo.EMPRESAS_LINKEXTERNO SET IDPERSONAS=@PERSONAS,IDGRUPOS=@GRUPOS WHERE TK=@TK

