//[idpantalla|Text,session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @IDPANTALLA VARCHAR(1000)
SET @IDPANTALLA=ISNULL(:IDPANTALLA,'')

IF @IDPANTALLA='4'
   SELECT * FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND  FASECLIENTE=1  ORDER BY ORDEN
else
   SELECT * FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND  FASECLIENTE=0  ORDER BY ORDEN