//[session.db|Untyped,session.idempresa|Untyped,]
--SELECT 

SELECT TOP 10 v.tkv, o.tko, VC.IDVENTA,  U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
<#SESSION.DB/>.DBO.FECHA_STR(V.FECHAHORA) AS FECHAHORA,P.TELEFONO,O.IDOPORTUNIDAD,P.NOMBRE,P.APELLIDOS,P.EMPRESA,U.INICIALES,O.CONCEPTO
FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG,
	 <#SESSION.DB/>.DBO.USUARIOS U, 
	 <#SESSION.DB/>.DBO.VENTAS V, 
	 <#SESSION.DB/>.DBO.VENTAS_COBROS VC, 
	 <#SESSION.DB/>.DBO.PROSPECTOS P, 
	 <#SESSION.DB/>.DBO.OPORTUNIDADES O
	WHERE UG.IDEMPRESA=<#SESSION.IDEMPRESA/> AND
		  UG.AUDITADO=1 AND 
		  UG.IDUSUARIOGRUPO=U.IDGRUPO AND
		  V.IDUSUARIO=U.IDUSUARIO AND
		  VC.IDVENTA=V.IDVENTA  AND
		  VC.AUDITADO=0 AND
		  VC.PAGADO=1 AND
		  U.IDEMPRESA = P.IDEMPRESA AND 
		  O.IDPROSPECTO = P.IDPROSPECTO AND
		  V.IDOPORTUNIDAD=O.IDOPORTUNIDAD
	GROUP BY v.tkv, o.tko,VC.IDVENTA,V.FECHAHORA,P.TELEFONO,O.IDOPORTUNIDAD,P.NOMBRE,P.APELLIDOS,P.EMPRESA,U.INICIALES,O.CONCEPTO,  U.NOMBRE,U.APELLIDOS  
	ORDER BY V.FECHAHORA DESC