//[session.gmt|Untyped|6,session.db|Untyped|salesup_db1,session.idusuario|Untyped|56]
/* Este es el del inicio!*/
DECLARE @COND VARCHAR(100)
DECLARE @GMT INT
SET @COND='Mensaje -%-:%'
SET @GMT = CAST('<#SESSION.GMT/>' AS INT )


SELECT TOP 10 CAST(R.TKREC AS VARCHAR(64)) AS TKREC, <#SESSION.DB/>.DBO.FECHA_STR(R.FECHAHORA) AS FECHAHORA, @gmt,u.iniciales,P.TELEFONO,  U.NOMBRE+' '+U.APELLIDOS AS EJECUTIVO_NOMBRE, 
(CASE WHEN R.RECORDATORIO LIKE @COND THEN 1 ELSE 0 END) AS TIPORECORDATORIO,
  <#SESSION.DB/>.DBO.GETONLYTIME(R.FECHAHORA) as REC_HR,
  --R.FECHAHORA, SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,GEtdATE()),
  cast (R.FECHAHORA-SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT, getdate()) as float) as remanente,
  <#SESSION.DB/>.DBO.TIEMPO_TXT (R.FECHAHORA, SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT, GETDATE())) AS REMANENTE_TXT, 
  R.FECHAHORA AS FECHA_HORA, ISNULL(O.CONCEPTO, '') AS OPORTUNIDADTITULO, 
  ISNULL(R.IDOPORTUNIDAD, 0) AS TIENEOPORTUNIDAD, *  
FROM <#SESSION.DB/>.DBO.RECORDATORIOS R  WITH(NOLOCK) 
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK)  ON R.IDPROSPECTO = P.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O  WITH(NOLOCK)  ON R.IDOPORTUNIDAD = O.IDOPORTUNIDAD 
left JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK) ON  P.IDUSUARIO = U.IDUSUARIO  
WHERE
   R.COMPLETADO =0 and R.IDUSUARIO = <#SESSION.IDUSUARIO/>  
order by TIPORECORDATORIO DESC,
case when R.RECORDATORIO LIKE @COND then R.FECHAHORA end desc, case when R.RECORDATORIO not LIKE @COND then R.FECHAHORA end asc
