//[auto|Text,session.idusuario|Untyped,session.db|Untyped,session.sessionid|Untyped,sp_month|Untyped,sp_year|Untyped,sp_day|Untyped,]
--INSERT
DECLARE @IDUSUARIO INT
DECLARE @LASTDAY INT
SELECT @LASTDAY=datepart(dd,DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+1,0)))
IF ISNULL(:auto,'') = ''
begin
  UPDATE  SALESUP_CT.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMO_ACCESO=GETDATE() WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
  DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_ACCESOS WITH(ROWLOCK)  WHERE  SESSIONID like '<#SESSION.SESSIONID/>'
end
SELECT @IDUSUARIO=IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS WITH(NOLOCK) WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>

UPDATE <#SESSION.DB/>.DBO.USUARIOS_ALERTAS SET NOTIFICADO = 1 WHERE IDUSUARIO  = <#SESSION.IDUSUARIO/>

UPDATE <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS WITH(ROWLOCK)
SET DEFAULT_IDUSUARIO = <#SESSION.IDUSUARIO/>, 
       DEFAULT_PROSPECTOS_BUSQUEDA = '', DEFAULT_PROSPECTOS_FASE = -1, 
     DEFAULT_OPORTUNIDADES_BUSQUEDA = '', DEFAULT_OPORTUNIDADES_FASE = -1, DEFAULT_OPORTUNIDADES_LINEA = -1,
     DEFAULT_VENTAS_BUSQUEDA = '', DEFAULT_VENTAS_LINEA = -1, 
     DEFAULT_VENTAS_DESDE =CONVERT(DATETIME, '01/' + CAST(MONTH(GETDATE()) AS VARCHAR(2)) + '/' + CAST(YEAR(GETDATE()) AS VARCHAR(4)),103),
     DEFAULT_VENTAS_HASTA = CONVERT(DATETIME,CAST(DAY(GETDATE()) AS VARCHAR(2)) + '/' + CAST(MONTH(GETDATE()) AS VARCHAR(2)) + '/' + CAST(YEAR(GETDATE()) AS VARCHAR(4)),103),
     DEFAULT_RECORDATORIOS_BUSQUEDA = ''
WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> 

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WITH(ROWLOCK) WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA NOT IN (410,411,412,414,415) 
INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS WITH(ROWLOCK) (IDUSUARIO,IDPANTALLA, TIPO, TEXTO, SQLTXT) VALUES
  (<#SESSION.IDUSUARIO/>, 3, 11, '01/<#SP_MONTH/>/<#SP_YEAR/> y <#SP_DAY/>/<#SP_MONTH/>/<#SP_YEAR/>',
   '(V.FECHAHORA BETWEEN CONVERT(DATETIME,''01/<#SP_MONTH/>/<#SP_YEAR/>'',103) AND CONVERT(DATETIME,''<#SP_DAY/>/<#SP_MONTH/>/<#SP_YEAR/>'',103))')

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WITH(ROWLOCK)WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=4
INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS  WITH(ROWLOCK) (IDUSUARIO,IDPANTALLA, TIPO, TEXTO, SQLTXT) VALUES
  (<#SESSION.IDUSUARIO/>, 4, 40, '01/01/<#SP_YEAR/> y <#SP_DAY/>/<#SP_MONTH/>/<#SP_YEAR/>',
   '(V.FECHAHORA BETWEEN CONVERT(DATETIME,''01/01/<#SP_YEAR/>'',103) AND CONVERT(DATETIME,''<#SP_DAY/>/<#SP_MONTH/>/<#SP_YEAR/>'',103))') 

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WITH(ROWLOCK)WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=413
INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS  WITH(ROWLOCK) (IDUSUARIO,IDPANTALLA, TIPO, TEXTO, SQLTXT) VALUES
  (<#SESSION.IDUSUARIO/>, 413, 413, 'No leídos',   '(A.LEIDO = 0)') 

  
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WITH(ROWLOCK)WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA=27
INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS  WITH(ROWLOCK) (IDUSUARIO,IDPANTALLA, TIPO, TEXTO, SQLTXT,SQLTXT_EXP) VALUES
  (<#SESSION.IDUSUARIO/>, 27, 0, '3', '01/<#SP_MONTH/>/<#SP_YEAR/>*'+CAST(@LASTDAY AS VARCHAR(1000))+'/<#SP_MONTH/>/<#SP_YEAR/>','Rango: 01/<#SP_MONTH/>/<#SP_YEAR/> - '+CAST(@LASTDAY AS VARCHAR(1000))+'/<#SP_MONTH/>/<#SP_YEAR/>') 
   
IF @IDUSUARIO IS NULL
  INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS WITH(ROWLOCK)
  (IDUSUARIO,DEFAULT_IDUSUARIO,default_ventas_desde,default_ventas_hasta)
   VALUES (<#SESSION.IDUSUARIO/>,<#SESSION.IDUSUARIO/>,CONVERT(DATETIME,'01/<#SP_MONTH/>/<#SP_YEAR/>',103),CONVERT(DATETIME,'<#SP_DAY/>/<#SP_MONTH/>/<#SP_YEAR/>',103))  