//[session.db|Untyped,]
--SELECT
/*PROTEGIDO*/

SELECT 
	(SELECT MESTXT
         FROM <#SESSION.DB/>.DBO.V_MESES M
         WHERE M.IDMES=(MONTH(GETDATE())) ) AS T_MES,

	(SELECT MESTXT
         FROM <#SESSION.DB/>.DBO.V_MESES M
         WHERE M.IDMES=(MONTH(DATEADD(m,1,GETDATE()))) ) AS T_MES1,

	(SELECT MESTXT
         FROM <#SESSION.DB/>.DBO.V_MESES M
         WHERE M.IDMES=(MONTH(DATEADD(m,2,GETDATE()))) ) AS T_MES2,

	(SELECT MESTXT+' +...' AS INTRO
         FROM <#SESSION.DB/>.DBO.V_MESES M
         WHERE   M.IDMES=(MONTH(DATEADD(M,3,GETDATE()))) ) AS T_MES3

FROM <#SESSION.DB/>.DBO.V_MESES
WHERE IDMES=MONTH(GETDATE())