//[idpantalla|Integer,session.idusuario|Untyped,session.idempresa|Untyped,reportevista|Integer,grupo|Integer,salida|Integer,moneda|Integer,tkgrupo|Text,session.db|Untyped,]
-- SELECT
/*PROTEGIDO*/

DECLARE @IDPANTALLA INT = :IDPANTALLA
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @CONTADOR INT = 0
DECLARE @REPORTEVISTA INT = ISNULL(:REPORTEVISTA,1)
DECLARE @GRUPO INT = ISNULL(:GRUPO,0)
DECLARE @SALIDA INT = ISNULL(:SALIDA,0)
DECLARE @MONEDA INT = ISNULL(:MONEDA,0)
DECLARE @TKGRUPO VARCHAR(256)

SET @TKGRUPO=ISNULL(:TKGRUPO, '') 

IF(@TKGRUPO!='') BEGIN SELECT @GRUPO=IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE CAST(TK AS VARCHAR(256))=@TKGRUPO AND IDEMPRESA=@IDEMPRESA END 

IF(@REPORTEVISTA = 1)
BEGIN
	 SELECT @CONTADOR = (U.IDUSUARIO)
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,<#SESSION.DB/>.DBO.USUARIOS U
	 WHERE U.IDEMPRESA=@IDEMPRESA AND U.IDUSUARIO=UL.ID
END
ELSE IF(@REPORTEVISTA = 2)
BEGIN
	 SELECT @CONTADOR = (U.IDUSUARIOGRUPO)
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,1) UL, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS U 
	 WHERE U.IDEMPRESA=@IDEMPRESA AND U.IDUSUARIOGRUPO=UL.ID
END
ELSE IF(@REPORTEVISTA = 3)
BEGIN
	 select @CONTADOR = count(a.total2)
	 from (
	 SELECT count(L.IDLINEA_PRODUCTO) as total2
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,
	 <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO L,<#SESSION.DB/>.DBO.USUARIOS_GRUPOS G, <#SESSION.DB/>.DBO.USUARIOS U 
	 WHERE UL.ID=U.IDUSUARIO AND L.IDEMPRESA=@IDEMPRESA AND L.IDEMPRESA=G.IDEMPRESA AND U.IDGRUPO = G.IDUSUARIOGRUPO
	 GROUP BY L.IDLINEA_PRODUCTO, L.LINEA_PRODUCTO,L.IDEMPRESA) a
END
ELSE IF(@REPORTEVISTA = 4)
BEGIN
	 select @CONTADOR = count(a.total2)
	 from (
	 SELECT count(PO.IDORIGEN) as total2
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,
	 <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO,<#SESSION.DB/>.DBO.USUARIOS_GRUPOS G, <#SESSION.DB/>.DBO.USUARIOS U 
	 WHERE UL.ID=U.IDUSUARIO AND PO.IDEMPRESA=@IDEMPRESA AND PO.IDEMPRESA=G.IDEMPRESA AND U.IDGRUPO = G.IDUSUARIOGRUPO 
	 GROUP BY PO.IDORIGEN) a
END
ELSE IF(@REPORTEVISTA = 5)
BEGIN
	 SELECT @CONTADOR = count(CASE WHEN PT.IDPAIS = '' OR PT.IDPAIS IS NULL THEN 'Desconocido' ELSE PS.PAIS END)
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,<#SESSION.DB/>.DBO.PROSPECTOS PT
	 LEFT JOIN <#SESSION.DB/>.DBO.PAISES PS ON PS.IDPAIS = PT.IDPAIS 
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = PT.IDUSUARIO
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G ON U.IDGRUPO = G.IDUSUARIOGRUPO AND PT.IDEMPRESA = G.IDEMPRESA
	 WHERE UL.ID=U.IDUSUARIO AND PT.IDEMPRESA=<#SESSION.IDEMPRESA/>
END
ELSE IF(@REPORTEVISTA = 6)
BEGIN
	 SELECT @CONTADOR = count (CASE WHEN PT.IDPAIS = '' OR PT.IDPAIS IS NULL THEN 'DESCONOCIDO' ELSE PS.PAIS END)
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,<#SESSION.DB/>.DBO.PROSPECTOS PT
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = PT.IDUSUARIO
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G ON PT.IDEMPRESA = G.IDEMPRESA AND G.IDUSUARIOGRUPO = U.IDGRUPO
	 LEFT JOIN <#SESSION.DB/>.DBO.PAISES PS ON PS.IDPAIS = PT.IDPAIS 
	 LEFT JOIN <#SESSION.DB/>.DBO.ESTADOS ES ON ES.IDESTADO = PT.IDESTADO 
	 WHERe ul.id=pt.idusuario and PT.IDEMPRESA=@IDEMPRESA
END
ELSE IF(@REPORTEVISTA = 7)
BEGIN
	 select @CONTADOR = count (distinct (CASE WHEN PT.CIUDAD = '' OR PT.CIUDAD IS NULL THEN 'Desconocido' ELSE PT.CIUDAD END))
	 FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) UL,
	 <#SESSION.DB/>.DBO.PROSPECTOS PT, <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G, <#SESSION.DB/>.DBO.USUARIOS U
	 WHERE ul.id=u.idusuario and PT.IDEMPRESA=@IDEMPRESA AND PT.IDUSUARIO = U.IDUSUARIO AND PT.IDEMPRESA = G.IDEMPRESA
END

IF(@CONTADOR = 0)
BEGIN
	 EXEC <#SESSION.DB/>.DBO.SP_REPORTE_COBROS_PENDIENTES '','','','','','',0
END
ELSE
BEGIN
	 EXEC <#SESSION.DB/>.DBO.SP_REPORTE_COBROS_PENDIENTES @IDUSUARIO, @IDEMPRESA, @REPORTEVISTA, @GRUPO,@MONEDA,@IDPANTALLA,@SALIDA
END
