//[session.db|Untyped,TKVARIANTE|Text]
--SELECT
DECLARE @TKVARIANTE VARCHAR(MAX)  
SET @TKVARIANTE = ISNULL(:TKVARIANTE,'')

SELECT IDAGRUPACION FROM SALESUP_CT.DBO.REPORTES_SISTEMA_VARIANTES WHERE TKRSV = @TKVARIANTE
