//[session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,OBJETO|Text]
-- SELECT
/*REPORTEVISTA|Integer,GRUPO|Integer,SALIDA|Integer,MONEDA|Integer,TKGRUPO|Text,IDPANTALLA|Integer*/

DECLARE @IDUSUARIO INT  
DECLARE @IDEMPRESA INT  
DECLARE @OBJETO VARCHAR(MAX) 

SET @OBJETO = ISNULL(:OBJETO, '') 
SET @IDUSUARIO = ISNULL(<#SESSION.IDUSUARIO/>, '') 
SET @IDEMPRESA = ISNULL(<#SESSION.IDEMPRESA/>, '') 
	

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_CLIENTES_COBROS_PENDIENTES_CABECERA @IDEMPRESA, @IDUSUARIO, @OBJETO