//[session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,OBJETO|Text]
-- SELECT
DECLARE @IDUSUARIO INT  
DECLARE @IDEMPRESA INT  
DECLARE @OBJETO VARCHAR(MAX) 
DECLARE @CONTEO INT

SET @CONTEO = 1
SET @OBJETO = ISNULL(:OBJETO, '') 
SET @IDUSUARIO = ISNULL(<#SESSION.IDUSUARIO/>, '') 
SET @IDEMPRESA = ISNULL(<#SESSION.IDEMPRESA/>, '') 
	

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_CLIENTES_COBROS_PENDIENTES_CUERPO @IDEMPRESA, @IDUSUARIO, @OBJETO, @CONTEO