//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--SELECT

DECLARE @AUX VARCHAR(MAX)
DECLARE @USUARIOS_FILTROS VARCHAR(MAX)
DECLARE @FILTROPANTALLA VARCHAR(MAX)
SELECT @USUARIOS_FILTROS = SQLTXT FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = <#SESSION.IDUSUARIO/> AND IDPANTALLA = 4 AND TIPO = 34
SELECT @FILTROPANTALLA = VALUE FROM <#SESSION.DB/>.DBO.filtrospantallas(4,<#SESSION.IDEMPRESA/>, <#SESSION.IDUSUARIO/>) WHERE ID = 1

SET @AUX = (CASE
	WHEN (@USUARIOS_FILTROS != '' AND @FILTROPANTALLA ='') OR (@USUARIOS_FILTROS IS NOT NULL AND @FILTROPANTALLA IS NULL) THEN '1'
	WHEN (@USUARIOS_FILTROS = '' AND @FILTROPANTALLA != '') OR (@USUARIOS_FILTROS IS NULL AND @FILTROPANTALLA IS NOT NULL) THEN '1'
	ELSE '0'
END)

SELECT @AUX AS RESPUESTA
