//[session.db|Untyped,session.idempresa]
--select
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @IDMONEDA INT
DECLARE @TIPOCAMBIO FLOAT

SELECT TOP 1 @IDMONEDA = IDEMPRESAMONEDA, @TIPOCAMBIO = TIPODECAMBIO FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA  = @IDEMPRESA ORDER BY NEWID()

SELECT @IDMONEDA AS IDMONEDA, @TIPOCAMBIO AS TIPOCAMBIO
