//[session.idempresa|Untyped|,session.db|Untyped|]

--SELECT

SELECT COUNT(*) AS CANTIDADENCERO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES
WHERE 
	(IDEMPRESAMONEDA = '' OR IDEMPRESAMONEDA IS NULL) AND 
	IDUSUARIO IN (
		SELECT IDUSUARIO 
		FROM <#SESSION.DB/>.DBO.USUARIOS 
		WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
	)