//[idusuario|Integer,db|Text,]
--update
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDUSUSARIO INT
DECLARE @DB VARCHAR(1000)
DECLARE @SQL VARCHAR(MAX)
SET @DB = ISNULL(:DB,'')
SET @IDUSUSARIO = :IDUSUARIO
SET @SQL='DECLARE @FECHA DATETIME; SET @FECHA = GETDATE(); EXEC '+@DB+'.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO '+CAST(@IDUSUSARIO AS VARCHAR(1000))+',@FECHA; '
EXEC (@SQL) 