//[idempresa|Integer,idusuario|Integer,concepto|Text,tipo|Text,monto|Numeric,fecha|Text,tiposeguimiento|Integer,db|Untyped,]
-- insert

DECLARE @IDEMPRESA INT,@IDUSUARIO INT
DECLARE @IDPROSPECTO INT,@TIPOSEGUIMIENTO INT
DECLARE @CONCEPTO VARCHAR(128), @TIPO VARCHAR(128)
DECLARE @MONTO MONEY
DECLARE @FECHA DATETIME
DECLARE @FECHAFIN DATETIME
	 
SET @IDEMPRESA = :IDEMPRESA
SET @IDUSUARIO = :IDUSUARIO
SET @CONCEPTO = :CONCEPTO
SET @TIPO = :TIPO
SET @MONTO = :MONTO
SET @FECHA = :FECHA
SET @TIPOSEGUIMIENTO = :TIPOSEGUIMIENTO

SELECT TOP 1 @IDPROSPECTO = IDPROSPECTO FROM <#DB>.DBO.PROSPECTOS WHERE IDUSUARIO = @IDUSUARIO ORDER BY 1 DESC

IF(@TIPO = 'venta')
BEGIN
	 EXEC <#DB>.DBO.SP_TEST_INSERTA_VENTA @IDEMPRESA,@IDUSUARIO,@IDPROSPECTO,@CONCEPTO,@MONTO,@FECHA
END	
ELSE IF(@TIPO = 'seguimiento')
BEGIN
	 EXEC <#DB/>.DBO.SP_INSERTA_PROSPECTO_SEGUIMIENTO_MV @IDPROSPECTO,0,@IDUSUARIO,0,@TIPOSEGUIMIENTO,@FECHA,@CONCEPTO,0,'','','',0,''
END
ELSE IF(@TIPO = 'email')
BEGIN
	 INSERT INTO <#DB/>.DBO.USUARIOS_EMAILS(IDUSUARIO,TIPO,DESTINATARIO,ASUNTO,CUERPO,ESTADO,FECHAHORA,ERRORES,IDPROSPECTO) VALUES(@IDUSUARIO,1,'usae15@prueba.com','pruebatestcase','prueba test case',1,@FECHA,0,@IDPROSPECTO)
END
ELSE IF(@TIPO = 'citas')
BEGIN
	 DECLARE @IDCITA INT

	 SET @FECHAFIN = @FECHA+1
	 
	 INSERT INTO <#DB/>.DBO.CITAS (IDUSUARIO_CREACION, IDEMPRESA, ASUNTO,LUGAR, FECHA_INICIO, FECHA_FIN,FECHACREACION,RECORDATORIO_CORREO_ACTIVO, 
			   RECORDATORIO_IDPLANTILLA,RECORDATORIO_MOMENTO, RECORDATORIO_SMS_ACTIVO, RECORDATORIO_SMS_IDPLANTILLA,RECORDATORIO_SMS_MOMENTO,NOTIFICA_CORREO_ACTIVO, 
			   NOTIFICA_IDPLANTILLA, NOTIFICA_SMS_ACTIVO, NOTIFICA_SMS_IDPLANTILLA, DESCRIPCION,TKC,RECURRENCIA,TIPOFIN,FRECUENCIA,PROXFECHARECORDAR,NOTIFICADO,ACTIVO)
		VALUES(@IDUSUARIO, @IDEMPRESA, 'TESTE CASE','CANCUN', @FECHA, @FECHAFIN,@FECHA,0, 
			   0,0,0,0,0,0,0,0,0,'TESTCASE','',0,0,1,'',0,1)
	
	SELECT TOP 1 @IDCITA = IDCITA FROM <#DB/>.DBO.CITAS WHERE IDUSUARIO_CREACION = @IDUSUARIO ORDER BY 1 DESC
			   
	INSERT INTO <#DB/>.DBO.CITAS_INVITADOS (IDCITA,IDPERSONA,PERSONA,TIPOPERSONA) VALUES(@IDCITA,@IDUSUARIO,'',2)
END
ELSE IF(@TIPO = 'tareas')
BEGIN
	 SET @FECHAFIN = @FECHA+1
	EXEC <#DB/>.dbo.SP_NUEVA_TAREA @IDUSUARIO, @IDEMPRESA, 120, @IDUSUARIO, '', 'TESTCASE', '', @FECHAFIN, '', '', '', '', '', '', '', '', '', '',1, @FECHA,NULL
END