//[idempresa|Text,idusuario|Text,db|Text,]
-- DELETE

DECLARE @IDEMPRESA VARCHAR(215),@IDUSUARIO VARCHAR(215), @DB VARCHAR(215) , @SQL VARCHAR(MAX) 

SET @IDEMPRESA = :IDEMPRESA
SET @IDUSUARIO = :IDUSUARIO
SET @DB = :DB


SET @SQL =  'DELETE FROM '+@DB+'.DBO.USUARIOS_METAS_CRITERIOS WHERE IDMETA IN(SELECT IDMETA FROM '+@DB+'.DBO.USUARIOS_METAS WHERE IDUSUARIO_ASIGNO = '+@IDUSUARIO+')'
SET @SQL = @SQL + ' DELETE FROM '+@DB+'.DBO.USUARIOS_METAS WHERE IDUSUARIO_ASIGNO = '+@IDUSUARIO+''
SET @SQL = @SQL + ' exec '+@DB+'.DBO.SP_ELIMINA_PROSPECTOS_ESPECIFICOS '+@IDEMPRESA+','+@IDUSUARIO+',0,0'
SET @SQL = @SQL + ' DELETE FROM '+@DB+'.DBO.CITAS_INVITADOS WHERE TIPOPERSONA = 2 AND IDPERSONA IN(SELECT IDUSUARIO_CREACION FROM '+@DB+'.DBO.CITAS WHERE IDUSUARIO_CREACION = '+@IDUSUARIO+')'
SET @SQL = @SQL + ' DELETE FROM '+@DB+'.DBO.CITAS WHERE IDUSUARIO_CREACION = '+@IDUSUARIO+''
SET @SQL = @SQL + ' DELETE FROM '+@DB+'.DBO.TAREAS WHERE IDINICIADOR = '+@IDUSUARIO+' OR IDREALIZADOR = '+@IDUSUARIO+''

IF @SQL IS NOT NULL
  EXEC (@SQL)