//[componente|Integer]

DECLARE @IDCOMPONENTE INT = ISNULL(:componente,0)
SELECT 
	NOMBRE_COMPONENTE,FORMATO,CLASIFICACION,
	ORIGENFROM,ORIGENWHERE,OPERADOR,
	CALIFICADOR,CAMPOFECHA,CATEGORIASVISIBLES,
	DETALLE,MODULO
FROM SALESUP_CT.DBO.TIPOS_METAS
WHERE IDCOMPONENTE = @IDCOMPONENTE