//[session.db|Untyped,session.idempresa|Untype,monto|text,tipoCambio|text,idmoneda|integer]
--select
DECLARE @IDEMPRESA INT
DECLARE @MONTO FLOAT
DECLARE @TIPOCAMBIO FLOAT
DECLARE @IDMONEDA_DEFAULT INT
DECLARE @IDMONEDA INT
DECLARE @NUEVO_MONTO FLOAT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @MONTO = ISNULL(CAST(:MONTO AS FLOAT),0)
SET @TIPOCAMBIO = ISNULL(CAST(:TIPOCAMBIO AS FLOAT),1)

SELECT @IDMONEDA_DEFAULT = IDEMPRESAMONEDA FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA  = @IDEMPRESA AND PORDEFECTO = 1

SET @IDMONEDA = ISNULL(:IDMONEDA,@IDMONEDA_DEFAULT)
SET @NUEVO_MONTO = <#SESSION.DB/>.DBO.ConvierteMontoaMonedaDefault(@MONTO,@TIPOCAMBIO,@IDEMPRESA,@IDMONEDA_DEFAULT,@IDMONEDA)

SELECT @NUEVO_MONTO AS MONTO
