//[SESSION.IDEMPRESA|Untyped,SESSION.IDUSUARIO|Untyped,SESSION.DB|Untyped,]
--SELECT

DECLARE @IDEMPRESA INT = CAST('<#SESSION.IDEMPRESA/>' AS INT)
DECLARE @IDUSUARIO INT = CAST('<#SESSION.IDUSUARIO/>' AS INT)
DECLARE @CONT INT

SELECT @CONT = COUNT(*) 
FROM <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES 
WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIO = @IDUSUARIO AND IDREPORTE = 1 AND DESISTEMA = 0

IF @CONT > 0 BEGIN
	SELECT TOP 1 IDGRUPOS_COMPARTIDOS AS COMPARTIDOS
	FROM <#SESSION.DB/>.dbo.REPORTES_CONFIGURACIONES 
	WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIO = @IDUSUARIO AND IDREPORTE = 1 AND DESISTEMA = 0 ORDER BY IDREPORTECONFIG DESC
END
ELSE SELECT 0 AS COMPARTIDOS