//[session.idempresa|Untyped|,session.db|Untyped|]

--SELECT

SELECT COUNT(*) AS CANTIDADENCERO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES
WHERE 
(TIPOCAMBIO = 0 OR TIPOCAMBIO IS NULL) AND
IDUSUARIO IN (
	SELECT IDUSUARIO 
	FROM <#SESSION.DB/>.dbo.USUARIOS
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
)