//[session.db|Untyped,session.idempresa|Untyped,usuario|Integer,fecha_desde|Text,session.convertcode|Untyped,fecha_hasta|Text,]
--SELECT

DECLARE @USUARIO INT
DECLARE @FECHA_DESDE VARCHAR(1000)
DECLARE @FECHA_HASTA VARCHAR(1000)
SET @FECHA_DESDE = ISNULL(:FECHA_DESDE,'')
SET @USUARIO =  ISNULL(:USUARIO,0)
SET @FECHA_HASTA = ISNULL(:FECHA_HASTA,'')

SELECT COUNT ( P.IDPROSPECTO) AS SEGUIMIENTOS_CLIENTES,  @USUARIO AS USUARIO, @FECHA_DESDE AS FECHA_DESDE, @FECHA_HASTA AS FECHA_HASTA
FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO PS WITH(NOLOCK), 
    <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND PS.IDUSUARIO = @USUARIO AND P.DESCARTADO = 0 AND P.ESCLIENTE = 1
AND P.IDPROSPECTO=PS.IDPROSPECTO
AND IDSEGUIMIENTOCATEGORIA IS NOT NULL
AND (<#SESSION.DB/>.DBO.GETONLYDATE(PS.FECHAHORA) 
BETWEEN CONVERT(DATETIME,@FECHA_DESDE,<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,@FECHA_HASTA,<#SESSION.CONVERTCODE/>))