//[idpantalla|Integer,tipo_suceso|Integer,tipo_ejecutivo|Integer,fecha_desde|Text,fecha_hasta|Text,tipo_texto|Text,ordenamiento|Text,session.gmt|Untyped,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,]
--SELECT

DECLARE @GMT INT
DECLARE @IDPANTALLA INT = ISNULL(:IDPANTALLA,25)
DECLARE @SQL VARCHAR(MAX)
DECLARE @SQLTXT VARCHAR(MAX) = ''
DECLARE @TIPO_SUCESO INT = ISNULL(:TIPO_SUCESO,-1)
DECLARE @TIPO_EJECTIVO INT = ISNULL(:TIPO_EJECUTIVO,0)
DECLARE @FILTRO VARCHAR(MAX) = ''
DECLARE @FILTRO_TEXTO VARCHAR(MAX) = ''
DECLARE @FECHA_DESDE VARCHAR(128) = ISNULL(:FECHA_DESDE,'')
DECLARE @FECHA_HASTA VARCHAR(128) = ISNULL(:FECHA_HASTA,'')
DECLARE @TIPO_TEXTO VARCHAR(MAX) = ISNULL(:TIPO_TEXTO,'0')
DECLARE @ORDENAMIENTO VARCHAR(MAX) = ISNULL(:ORDENAMIENTO,' 1 DESC ')

IF(@TIPO_SUCESO > -1)
BEGIN
	 SET @FILTRO = ' AND US.TIPO = ' + CAST(@TIPO_SUCESO AS VARCHAR(10)) + ' '
END

IF(@TIPO_EJECTIVO > 0)
BEGIN
	 SET @FILTRO = @FILTRO + ' AND US.IDUSUARIO = ' + CAST(@TIPO_EJECTIVO AS VARCHAR(10)) + ' '
END

IF(@TIPO_TEXTO <> '0')
BEGIN
	 SET @FILTRO_TEXTO = ' AND (PR.NOMBRE LIKE ''%'+@TIPO_TEXTO+'%'' OR PR.APELLIDOS LIKE ''%'+@TIPO_TEXTO+'%'' OR US.TEXTO LIKE ''%'+@TIPO_TEXTO+'%'' OR PR.EMPRESA LIKE ''%'+@TIPO_TEXTO+'%'') '
END

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )

SET @SQLTXT = ' SELECT * FROM 
(    SELECT TOP 50000 US.IDVENTA,PR.TKP, VE.TKV, '+CAST(@IDPANTALLA AS VARCHAR(5))+' AS IDPANTALLA, US.FECHAHORA,SALESUP_CT.dbo.[obtieneFechaRealGMT](+'+CAST(@GMT AS VARCHAR(5))+', US.FECHAHORA)  AS FECHA_SUCESO,OP.TKO,
    US.TEXTO + CASE WHEN UD.IDUSUARIO IS NULL THEN '''' ELSE '' a ''+ (UD.NOMBRE+'' ''+UD.APELLIDOS) END AS TEXTO,
	 CASE WHEN P2.NOMBRE IS NULL THEN PR.NOMBRE ELSE  P2.NOMBRE END AS NOMBRE,
	 CASE WHEN P2.NOMBRE IS NULL THEN ISNULL(PR.APELLIDOS,'''') ELSE  ISNULL(P2.APELLIDOS,'''') END AS APELLIDOS,
	 CASE WHEN P2.NOMBRE IS NULL THEN LEFT(PR.EMPRESA, 32) ELSE  LEFT(P2.EMPRESA, 32) END AS EMPRESA,
	 CASE WHEN P2.NOMBRE IS NULL THEN PR.IDPROSPECTO ELSE  P2.IDPROSPECTO END AS IDPROSPECTO,
	 CASE WHEN P2.NOMBRE IS NULL THEN PR.CORREO ELSE  P2.CORREO END AS CORREO,
	 CASE WHEN P2.NOMBRE IS NULL THEN PR.DESCARTADO ELSE  P2.DESCARTADO END AS DESCARTADO,
	 US.TIPO,
    (UU.NOMBRE+'' ''+UU.APELLIDOS) AS EJECUTIVO, UU.INICIALES, US.IDOPORTUNIDAD, 
    CASE WHEN P2.NOMBRE IS NULL THEN (CASE WHEN PSS.COMENTARIO IS NULL THEN CAST(PS.COMENTARIO AS VARCHAR (max)) ELSE CAST(PSS.COMENTARIO AS VARCHAR (max)) END) ELSE (CASE WHEN PSS.COMENTARIO IS NULL THEN CAST(PS2.COMENTARIO AS VARCHAR (max)) ELSE CAST(PSS.COMENTARIO AS VARCHAR (max)) END) END AS COMENTARIO, 
    CASE WHEN P2.NOMBRE IS NULL THEN (CASE WHEN PSS.COMENTARIO IS NULL THEN CAST(PS.COMENTARIO AS VARCHAR (max)) ELSE CAST(PSS.COMENTARIO AS VARCHAR (max)) END) ELSE (CASE WHEN PSS.COMENTARIO IS NULL THEN CAST(PS2.COMENTARIO AS VARCHAR (max)) ELSE CAST(PSS.COMENTARIO AS VARCHAR (max)) END) END AS COMENTARIO_FULL 
   
         FROM  <#SESSION.DB/>.dbo.USUARIOS_SUCESOS US WITH(NOLOCK) 
         JOIN <#SESSION.DB/>.dbo.USUARIOS UU WITH(NOLOCK)      ON US.IDUSUARIO=UU.IDUSUARIO AND IDEMPRESA=<#SESSION.IDEMPRESA/>  
		 LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS PR WITH(NOLOCK)    ON PR.IDPROSPECTO IS NOT NULL AND US.IDPROSPECTO=PR.IDPROSPECTO AND PR.IDEMPRESA=<#SESSION.IDEMPRESA/> 

		 LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P2 ON P2.IDPROSPECTO IN (SELECT SPLITVALUE FROM DBO.SPLIT(US.PROSPECTOS_RELACIONADOS,'',''))

         LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES OP WITH(NOLOCK) ON OP.IDPROSPECTO IS NOT NULL AND US.IDPROSPECTO=OP.IDPROSPECTO AND PR.IDPROSPECTO = OP.IDPROSPECTO AND OP.IDOPORTUNIDAD = US.IDOPORTUNIDAD
		 
		 LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS WITH(NOLOCK)   
            ON (PR.IDULTIMOSEGUIMIENTO = PS.IDSEGUIMIENTO AND PR.IDPROSPECTO IS NOT NULL AND PS.IDPROSPECTO=PR.IDPROSPECTO AND US.IDOPORTUNIDAD IS NULL) OR
            (OP.IDULTIMOSEGUIMIENTO = PS.IDSEGUIMIENTO AND PR.IDPROSPECTO IS NOT NULL AND PS.IDPROSPECTO=PR.IDPROSPECTO AND PS.IDOPORTUNIDAD=OP.IDOPORTUNIDAD AND US.IDOPORTUNIDAD IS NOT NULL)
			
		LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS2 WITH(NOLOCK)    
             ON (P2.IDULTIMOSEGUIMIENTO = PS2.IDSEGUIMIENTO AND P2.IDPROSPECTO IS NOT NULL AND PS2.IDPROSPECTO=P2.IDPROSPECTO AND US.IDOPORTUNIDAD IS NULL) OR 
             (OP.IDULTIMOSEGUIMIENTO = PS2.IDSEGUIMIENTO AND P2.IDPROSPECTO IS NOT NULL AND PS2.IDPROSPECTO=P2.IDPROSPECTO AND PS2.IDOPORTUNIDAD=OP.IDOPORTUNIDAD AND US.IDOPORTUNIDAD IS NOT NULL)

		LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSS WITH(NOLOCK) ON PSS.IDSEGUIMIENTO = US.IDSEGUIMIENTO
				   
         LEFT JOIN <#SESSION.DB/>.dbo.VENTAS VE WITH(NOLOCK)        ON VE.IDOPORTUNIDAD IS NOT NULL AND OP.IDOPORTUNIDAD=VE.IDOPORTUNIDAD AND VE.IDVENTA = US.IDVENTA
         LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS UD WITH(NOLOCK)        ON UD.IDUSUARIO = US.IDUSUARIO_DESTINO 
        WHERE 
			UU.IDEMPRESA=<#SESSION.IDEMPRESA/> 
			AND US.IDUSUARIO  IN (SELECT ID FROM   <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0)) '+@FILTRO+'
            AND (<#SESSION.DB/>.DBO.GETONLYDATE(SALESUP_CT.dbo.[obtieneFechaRealGMT]('+CAST(@GMT AS VARCHAR(5))+', US.FECHAHORA)) 
			BETWEEN CONVERT(DATETIME,'''+@FECHA_DESDE+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+@FECHA_HASTA+''',<#SESSION.CONVERTCODE/>))
          '+@FILTRO_TEXTO+'
		     order by '+@ORDENAMIENTO+'
		  ) AS US    
    order by '+@ORDENAMIENTO+' '

	EXEC(@SQLTXT)