//[tipo_suceso|Integer,tipo_ejecutivo|Integer,fecha_desde|Text,fecha_hasta|Text,tipo_texto|Text,idpantalla|Integer,ordenamiento|Text,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,]
-- SELECT

DECLARE @SQLTXT VARCHAR(MAX) = ''
DECLARE @TIPO_SUCESO INT = ISNULL(:TIPO_SUCESO,-1)
DECLARE @TIPO_EJECUTIVO INT = ISNULL(:TIPO_EJECUTIVO,0)
DECLARE @FILTRO VARCHAR(MAX) = ''
DECLARE @FILTRO_TEXTO VARCHAR(MAX) = ''
DECLARE @FECHA_DESDE VARCHAR(128) = ISNULL(:FECHA_DESDE,'')
DECLARE @FECHA_HASTA VARCHAR(128) = ISNULL(:FECHA_HASTA,'')
DECLARE @TIPO_TEXTO VARCHAR(MAX) = ISNULL(:TIPO_TEXTO,'0')
DECLARE @IDPANTALLA INT = ISNULL(:IDPANTALLA,25)
DECLARE @ORDENAMIENTO VARCHAR(MAX) = ISNULL(:ORDENAMIENTO,' 1 DESC ')

IF(@TIPO_SUCESO > -1)
BEGIN
	 SET @FILTRO = ' AND US.TIPO = ' + CAST(@TIPO_SUCESO AS VARCHAR(10)) + ' '
END

IF(@TIPO_EJECUTIVO > 0)
BEGIN
	 SET @FILTRO = @FILTRO + ' AND US.IDUSUARIO = ' + CAST(@TIPO_EJECUTIVO AS VARCHAR(10)) + ' '
END

IF(@TIPO_TEXTO <> '0')
BEGIN
	 SET @FILTRO_TEXTO = ' AND (PR.NOMBRE LIKE ''%'+@TIPO_TEXTO+'%'' OR PR.APELLIDOS LIKE ''%'+@TIPO_TEXTO+'%'' OR US.TEXTO LIKE ''%'+@TIPO_TEXTO+'%'' OR PR.EMPRESA LIKE ''%'+@TIPO_TEXTO+'%'') '
END

SET @SQLTXT = ' SELECT COUNT (us.idsuceso) as totaln, '+CAST(@IDPANTALLA AS VARCHAR(3))+' AS IDPANTALLA,'+CAST(@TIPO_SUCESO AS VARCHAR(5))+' AS TIPO_SUCESO,'+CAST(@TIPO_EJECUTIVO AS VARCHAR(5))+' AS TIPO_EJECUTIVO,'''+@TIPO_TEXTO+''' AS TIPO_TEXTO,
'''+@FECHA_DESDE+''' AS FECHA_DESDE,'''+@FECHA_HASTA+''' AS FECHA_HASTA,'''+@ORDENAMIENTO+''' AS ORDENAMIENTO
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0) UL,<#SESSION.DB/>.dbo.USUARIOS_SUCESOS US  WITH(NOLOCK) 
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS PR  WITH(NOLOCK) ON US.IDPROSPECTO=PR.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES OP  WITH(NOLOCK) ON US.IDPROSPECTO=OP.IDPROSPECTO AND US.IDOPORTUNIDAD = OP.IDOPORTUNIDAD
LEFT JOIN <#SESSION.DB/>.dbo.VENTAS VE  WITH(NOLOCK) ON OP.IDOPORTUNIDAD=VE.IDOPORTUNIDAD AND VE.IDVENTA = US.IDVENTA AND VE.IDOPORTUNIDAD = US.IDOPORTUNIDAD
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS UU  WITH(NOLOCK) ON US.IDUSUARIO=UU.IDUSUARIO
WHERE UU.IDEMPRESA=<#SESSION.IDEMPRESA/> '+@FILTRO+'
AND  UL.ID=US.IDUSUARIO
AND (<#SESSION.DB/>.DBO.GETONLYDATE(US.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@FECHA_DESDE+''',<#SESSION.CONVERTCODE/>) AND CONVERT(DATETIME,'''+@FECHA_HASTA+''',<#SESSION.CONVERTCODE/>)) ' + @FILTRO_TEXTO + ' '
EXEC(@SQLTXT)

