//[session.idgrupo|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT 
DECLARE @NIVEL     INT 
DECLARE @IDEMPRESA INT 
DECLARE @IDGRUPO   INT 

SET @IDGRUPO    =  CAST(ISNULL('<#SESSION.IDGRUPO/>', 0) AS INT)
SET @IDUSUARIO  =  CAST(ISNULL('<#SESSION.IDUSUARIO/>', 0) AS INT)
SET @NIVEL      =  CAST(ISNULL('<#SESSION.NIVEL/>', 0) AS INT )
SET @IDEMPRESA  =  CAST(ISNULL('<#SESSION.IDEMPRESA/>',0) AS INT)


    SELECT U.IDUSUARIO, U.NOMBRE +' '+U.APELLIDOS+' ('+LTRIM(RTRIM(U.INICIALES))+')' AS NOMBRE, U.IDGRUPO , UG.GRUPO 
	FROM <#SESSION.DB/>.DBO.USUARIOS U
	LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS UG ON U.IDGRUPO=UG.IDUSUARIOGRUPO 
	WHERE U.IDEMPRESA=@IDEMPRESA AND ACTIVO = 1
	AND (
   	     (@NIVEL = 1) OR
	     (@NIVEL = 2 AND U.IDGRUPO  = @IDGRUPO) OR
	     (@NIVEL = 3 AND U.IDUSUARIO = @IDUSUARIO) 
	) 
	
	ORDER BY U.NOMBRE ASC