//[session.convertcode|Untyped,session.idusuario|Untyped,session.idgrupo|Untyped,session.nivel|Untyped,ordenamiento|Text,fecha_desde|Text,fecha_hasta|Text,session.idempresa|Untyped,session.db|Untyped,]
--SELECT

DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @IDGRUPO INT
DECLARE @NIVEL INT
DECLARE @FECHA_DESDE DATETIME
DECLARE @FECHA_HASTA DATETIME
DECLARE @CONVERTCODE INT
DECLARE @ORDENAMIENTO VARCHAR(1000)
SET @CONVERTCODE=<#SESSION.CONVERTCODE/>
SET @IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @IDGRUPO=<#SESSION.IDGRUPO/>
SET @NIVEL=<#SESSION.NIVEL/>
SET @ORDENAMIENTO=ISNULL(:ORDENAMIENTO,'')
SET @FECHA_DESDE=CONVERT(DATETIME,:FECHA_DESDE,@CONVERTCODE)
SET @FECHA_HASTA=CONVERT(DATETIME,:FECHA_HASTA,@CONVERTCODE)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ACTIVIDADES @IDUSUARIO, @IDEMPRESA, @IDGRUPO, @NIVEL, @FECHA_DESDE, @FECHA_HASTA, @CONVERTCODE, @ORDENAMIENTO



