//[]
--SELECT
DECLARE @COLORES VARCHAR(2000)
DECLARE @TABLACOLORES AS TABLE (CODIGO VARCHAR(6))
  INSERT @TABLACOLORES (CODIGO) SELECT CODIGO FROM SALESUP_CT.DBO.COLORES ORDER BY IDCOLOR

  SET @COLORES=''
  SELECT @COLORES = @COLORES + '''#'+CODIGO+''',' FROM @TABLACOLORES
  SELECT REVERSE(SUBSTRING(REVERSE(@COLORES),2,LEN(@COLORES))) AS CODIGO
  
  