//[lapantalla|Integer,session.db|Untyped,session.idusuario|Untyped,]
--select
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @LAPANTALLA INT
SET @LAPANTALLA =  ISNULL(:LAPANTALLA,0)
select ISNULL(TEXTO,'1') AS ESCOMPRATIVO fROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDPANTALLA = @LAPANTALLA AND IDUSUARIO=<#SESSION.IDUSUARIO/> and TIPO=20