//[OBJETO|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped]
--SELECT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @OBJETO VARCHAR(MAX) 
DECLARE @GMT INT
DECLARE @TOTAL INT 
DECLARE @ORDENAMIENTO VARCHAR(MAX)

SET @TOTAL = 0
SET @GMT = CAST('<#SESSION.GMT/>' AS INT)
SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @OBJETO =ISNULL(:OBJETO,'')
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ACTIVIDADES_SUCESOS_CUERPO @IDEMPRESA, @IDUSUARIO, @OBJETO, @GMT, @CONVERTCODE, @TOTAL, @ORDENAMIENTO