//[eltipo|Integer,periodo|Integer,campo|Text,tipo|Text,agrupar|Integer,grupo|Integer,id|Integer,fechadesde|Text,fechahasta|Text,tk|Text,session.db|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,session.idusuario|Untyped,]
-- SELECT

DECLARE @ELTIPO INT = ISNULL(:ELTIPO,0)
DECLARE @CAMPO VARCHAR(MAX) = ISNULL(:CAMPO,'')
DECLARE @AGRUPAR INT =ISNULL(:AGRUPAR, 0) 
DECLARE @GRUPO INT =ISNULL(:GRUPO, 0) 
DECLARE @ID INT = ISNULL(:ID,0)
DECLARE @FECHADESDE VARCHAR(128) = ''
DECLARE @FECHAHASTA VARCHAR(128) = ''
DECLARE @PERIODO INT = ISNULL(:periodo,0)
DECLARE @TIPO VARCHAR(MAX) = ISNULL(:TIPO,'')
DECLARE @TK VARCHAR(MAX) = ISNULL(:tk, '')

DECLARE @CRIT VARCHAR(MAX) = ''

IF @GRUPO = 0 SET @CRIT = ''
IF @GRUPO = 1 SELECT @CRIT = IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE TKU = @TK
IF @GRUPO = 2 SELECT @CRIT = IDUSUARIOGRUPO FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS WHERE TK = @TK
IF @GRUPO = 4 SET @CRIT = @TK
IF @GRUPO = 5 SET @CRIT = @TK
IF @GRUPO = 6 SET @CRIT = @TK

IF @PERIODO = 0 BEGIN
	SET @FECHADESDE = ISNULL(:fechadesde,'')
	SET @FECHAHASTA = ISNULL(:fechahasta,'')
END
ELSE BEGIN
	SET @FECHADESDE = SALESUP_CT.DBO.RANGOFECHA(0,@PERIODO,NULL)
	SET @FECHAHASTA = SALESUP_CT.DBO.RANGOFECHA(1,@PERIODO,NULL)
END

DECLARE @SQLTXT VARCHAR(MAX) = ''

--IF(@CRIT !='' AND @AGRUPAR = 2 ) BEGIN SET @CRIT='AND U.IDUSUARIO='+@CRIT END
--IF(@GRUPO !=2) BEGIN SET @CRIT='' END }


SELECT @CRIT = 
(CASE
	WHEN @GRUPO = 0 THEN ''
	WHEN @GRUPO = 1 THEN ' AND U.IDUSUARIO= '+CAST(@CRIT AS VARCHAR(MAX))
	WHEN @GRUPO = 2 THEN ' AND G.IDUSUARIOGRUPO  ='+CAST(@CRIT AS VARCHAR(MAX))
	--WHEN @GRUPO = 3 THEN ' AND F.LINEA_PRODUCTO =' +CAST(@CRIT AS VARCHAR(MAX))
	WHEN @GRUPO = 4 THEN ' AND PO.IDORIGEN=' +CAST(@CRIT AS VARCHAR(MAX))
    WHEN @GRUPO = 5 THEN ' AND PA.IDPAIS=''' +CAST(@CRIT AS VARCHAR(MAX))+''''
	WHEN @GRUPO = 6 THEN ' AND E.IDESTADO=''' +CAST(@CRIT AS VARCHAR(MAX)) +'''' 
END)


IF @ELTIPO = 2
BEGIN
	SET @SQLTXT = 'SELECT
	P.NOMBRE + '' ''+ P.APELLIDOS AS NOMBRE, EMPRESA, o.tko,P.IDPROSPECTO,P.TKP,
	''.''+LTRIM(ISNULL(TELEFONO, '''')) AS TELEFONO_E, ''.''+LTRIM(ISNULL(TELEFONO2, '''')) AS TELEFONO2_E, 
	''.''+LTRIM(ISNULL(MOVIL, '''')) AS MOVIL_E, ''.''+LTRIM(ISNULL(CORREO, '''')) AS CORREO_E,
	P.NOMBRE, P.APELLIDOS, CAST(P.COMENTARIOS AS VARCHAR(512)) AS COMENTARIOS,  DESCARTADORAZON,TELEFONO, 
	MOVIL,TELEFONO2, CORREO, DESCARTADO, EMPRESA,ESCLIENTE, U.INICIALES,U.NOMBRE+'' ''+U.APELLIDOS AS 
	EJECUTIVO_NOMBRE,
	   <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,
		<#SESSION.DB/>.DBO.ObtieneEjecutivosCompartidos(P.IDPROSPECTO) AS EJECUTIVOS,
		(SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WITH (NOLOCK) WHERE 
	PA.IDPROSPECTO = P.IDPROSPECTO ) AS COMPARTIDO,
	  <#SESSION.DB/>.dbo.FECHA_STR(P.FECHACONTACTO) AS FECHA_CONTACTO
	FROM 
	 <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0) UL,
	 <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
	 LEFT  JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O  WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO
	 LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO F  WITH(NOLOCK) ON  O.IDLINEA_PRODUCTO = F.IDLINEA_PRODUCTO
	 JOIN <#SESSION.DB/>.DBO.USUARIOS U   WITH(NOLOCK) ON U.IDUSUARIO = P.IDUSUARIO
	 JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G   WITH(NOLOCK) ON U.IDGRUPO = G.IDUSUARIOGRUPO
	 JOIN <#SESSION.DB/>.DBO.PAISES PA   WITH(NOLOCK) on PA.IDPAIS = p.IDPAIS 
	 JOIN <#SESSION.DB/>.DBO.ESTADOS E   WITH(NOLOCK) on E.IDESTADO = p.IDESTADO AND E.IDPAIS = P.IDPAIS 
	 JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO   WITH(NOLOCK) on PO.IDORIGEN = p.IDORIGEN 
	 LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA R   WITH(NOLOCK) ON P.IDRAZONPERDIDA = R.IDRAZONPERDIDA AND P.IDEMPRESA = R.IDEMPRESA
	 WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND DESCARTADO = 1  '+CAST(@CRIT AS VARCHAR(256))+'
	 AND UL.ID=P.IDUSUARIO
	 AND ISNULL(R.IDRAZONPERDIDA, 0) = '+CAST(@ID AS VARCHAR(20))+'
        			 AND <#SESSION.DB/>.dbo.GetOnlyDate(DESCARTADOFECHA) BETWEEN 
				  CONVERT(DATETIME,'''+@FECHADESDE+''',<#SESSION.CONVERTCODE/>) AND 
				  CONVERT(DATETIME,'''+@FECHAHASTA+''',<#SESSION.CONVERTCODE/>)
	 
	 ORDER BY
	   DESCARTADOFECHA'
	 EXEC(@SQLTXT)
END
ELSE
BEGIN
	SET @SQLTXT = 'SELECT 
	P.NOMBRE + '' ''+ P.APELLIDOS AS NOMBRE, EMPRESA, TELEFONO,  TELEFONo2, CORREO, MOVIL, 
	  SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, O.IDOPORTUNIDAD, O.NARCHIVOS) AS VerArchivos,
	 NULL as archivo,CASE WHEN RAZONPERDIDA IS NULL THEN PERDIDA_RAZON ELSE RAZONPERDIDA END AS PERDIDA_RAZON,
	FECHA_CIERRE, O.*,P.*, CAST (COMENTARIOS AS VARCHAR(128))+''...'' AS INTRO,
	  U.INICIALES, U.NOMBRE+'' ''+U.APELLIDOS AS EJECUTIVO_NOMBRE,
	 (SELECT ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES   WITH(NOLOCK) WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,
	 (SELECT TOP 1 FECHAHORA FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO   WITH(NOLOCK) WHERE 
	IDPROSPECTO = P.IDPROSPECTO AND IDOPORTUNIDAD=O.IDOPORTUNIDAD AND SISTEMA=0 ORDER BY IDSEGUIMIENTO 
	DESC) AS ULTIMO_CONTACTO_FECHA,
	 (SELECT TOP 1 CAST(COMENTARIO AS VARCHAR(128)) FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO   
	WITH(NOLOCK) WHERE IDPROSPECTO = P.IDPROSPECTO AND IDOPORTUNIDAD=O.IDOPORTUNIDAD AND SISTEMA=0 ORDER 
	BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO,
	 (SELECT TOP 1 <#SESSION.DB/>.DBO.TIEMPO_TXT (FECHAHORA,GETDATE()) FROM 
	<#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO   WITH(NOLOCK) WHERE IDPROSPECTO = P.IDPROSPECTO AND 
	IDOPORTUNIDAD=O.IDOPORTUNIDAD AND SISTEMA=0 ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_TIEMPO,
	 (SELECT TOP 1 U.INICIALES FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S, 
	<#SESSION.DB/>.DBO.USUARIOS U   WITH(NOLOCK) WHERE S.IDPROSPECTO = P.IDPROSPECTO AND IDOPORTUNIDAD = 
	O.IDOPORTUNIDAD AND S.IDUSUARIO = U.IDUSUARIO ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_USUARIO,
	 (SELECT TOP 1 U.IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S, 
	<#SESSION.DB/>.DBO.USUARIOS U   WITH(NOLOCK) WHERE S.IDPROSPECTO = P.IDPROSPECTO AND IDOPORTUNIDAD = 
	O.IDOPORTUNIDAD AND S.IDUSUARIO = U.IDUSUARIO ORDER BY IDSEGUIMIENTO DESC) AS ULTIMO_CONTACTO_IDUSUARIO,
	 F.*,   
	 CASE 
	   WHEN O.FECHA_CIERRE < <#SESSION.DB/>.DBO.GETONLYDATE(GETDATE()) THEN 1
	   ELSE 0
	 END AS VENCIDA,
	 (SELECT ISNULL(ICONO_ARCHIVO, ''icon_default.jpg'') FROM <#SESSION.DB/>.DBO.DOCUMENTO_ICONOS   
	WITH(NOLOCK) WHERE O.ARCHIVO != '''' AND EXTENSION =<#SESSION.DB/>.DBO.obtiene_extension(O.ARCHIVO) ) 
	AS ICONO_ARCHIVO 
	FROM 
	 <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0) UL,
	 <#SESSION.DB/>.DBO.PROSPECTOS P   WITH(NOLOCK) 
	 JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O    WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO
	 JOIN <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO F   WITH(NOLOCK) ON  O.IDLINEA_PRODUCTO = 
	F.IDLINEA_PRODUCTO
	 JOIN <#SESSION.DB/>.DBO.USUARIOS U   WITH(NOLOCK) ON U.IDUSUARIO = O.IDUSUARIO
	 JOIN <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G   WITH(NOLOCK) ON U.IDGRUPO = G.IDUSUARIOGRUPO
	 JOIN <#SESSION.DB/>.DBO.PAISES PA   WITH(NOLOCK) on PA.IDPAIS = p.IDPAIS 
	 JOIN <#SESSION.DB/>.DBO.ESTADOS E   WITH(NOLOCK) on E.IDESTADO = p.IDESTADO AND E.IDPAIS = P.IDPAIS 
	 JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO   WITH(NOLOCK) on PO.IDORIGEN = p.IDORIGEN 
	 LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA R   WITH(NOLOCK) ON O.IDRAZONPERDIDA = 
	R.IDRAZONPERDIDA AND F.IDEMPRESA = R.IDEMPRESA
	   WHERE F.IDEMPRESA = <#SESSION.IDEMPRESA/> AND PERDIDA = 1  '+CAST(@CRIT AS VARCHAR(256))+'
	  AND UL.ID=P.IDUSUARIO
		AND ISNULL(O.IDRAZONPERDIDA, 0) = '+CAST(@ID AS VARCHAR(20))+'
        			 AND <#SESSION.DB/>.dbo.GetOnlyDate(PERDIDA_FECHA) BETWEEN 
				  CONVERT(DATETIME,'''+@FECHADESDE+''',<#SESSION.CONVERTCODE/>) AND 
				  CONVERT(DATETIME,'''+@FECHAHASTA+''',<#SESSION.CONVERTCODE/>)

	 ORDER BY
	   PERDIDA_FECHA'
	   EXEC(@SQLTXT)
END  