//[session.idusuario|Untyped,session.idempresa|Untyped,periodo|Text,parametros|Text,filtro|Text,]
-- Select
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @PERIODO VARCHAR(256) = ISNULL(:PERIODO,'')
DECLARE @FILTRO VARCHAR(MAX) = ISNULL(:FILTRO, '')
DECLARE @PARAMETROS VARCHAR(MAX) = ISNULL(:PARAMETROS,'')
SET @PARAMETROS = <#SESSION.DB/>.DBO.PREPARACADENA(@PARAMETROS)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ESTIMACION_DE_VENTAS_DETALLE  @IDUSUARIO,@IDEMPRESA,@PERIODO, @PARAMETROS,@FILTRO
