//[]
--select
DECLARE @ANIO INT
SET @ANIO = DATEPART (YY, GETDATE())

SELECT @ANIO AS idOpcion, @ANIO AS opcion
UNION 
SELECT @ANIO-1,@ANIO-1
UNION 
SELECT @ANIO-2,@ANIO-2
UNION 
SELECT @ANIO-3,@ANIO-3
UNION 
SELECT @ANIO-4,@ANIO-4
order by 2 desc