//[session.db|Untyped,session.CONTROL|Untyped,session.IDUSUARIO|Untyped,session.IDEMPRESA|Untyped,SP_HOST|TEXT]
--SELECT
DECLARE @DB VARCHAR(MAX)
DECLARE @CONTROL VARCHAR(MAX)
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @HOST VARCHAR(MAX)    

SET @DB = '<#SESSION.DB/>'
SET @CONTROL  = '<#SESSION.CONTROL/>'
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @HOST = :SP_HOST
--SELECT @HOST

IF(@HOST = 'devbranch4.salesup.com.mx' AND @DB = 'SALESUP_DB15' AND @IDUSUARIO = 60968 AND @IDEMPRESA = 42634)
BEGIN
	EXEC <#SESSION.DB/>.DBO.SP_TEST_POBLACION_DATOS_DUMMY @IDEMPRESA,@IDUSUARIO,1
	SELECT 'SUCCESS' AS 'RESPUESTA'
END
ELSE IF(@HOST = 'sandbox.salesup.com.mx' AND @DB = 'SALESUP_DB1' AND @IDUSUARIO = 54189 AND @IDEMPRESA = 38923)
BEGIN
	EXEC <#SESSION.DB/>.DBO.SP_TEST_POBLACION_DATOS_DUMMY @IDEMPRESA,@IDUSUARIO,1
	SELECT 'SUCCESS' AS 'RESPUESTA'
END
ELSE
BEGIN
	SELECT 'DENY' AS 'RESPUESTA'
END
