//[session.idempresa|Untyped|,session.db|Untyped|,session.idusuario|Untyped|,tipo|Integer|,session.convertcode|Untyped|]
--Select

DECLARE @IDUSUARIO INT
DECLARE @TIPO INT  = ISNULL(:TIPO, 0)
DECLARE @P VARCHAR(MAX)
DECLARE @CONVERTCODE INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

IF @TIPO = 0 BEGIN
	SELECT @P = (
		SELECT TOP 5 ',' + CAST(IDPROSPECTO AS VARCHAR(MAX))
		FROM <#SESSION.DB/>.DBO.RECORDATORIOS
		WHERE FECHAHORA > GETDATE() AND IDUSUARIO = @IDUSUARIO AND IDPROSPECTO IS NOT NULL
		FOR XML PATH('')
	)
	SELECT CAST(IDPROSPECTO AS INT) AS IDPROSPECTO,CONVERT(DATETIME,FECHA,@CONVERTCODE) AS FECHA,CAST(TEXTO AS VARCHAR(MAX)) AS TEXTO,CAST(TK AS VARCHAR(MAX)) AS TK FROM <#SESSION.DB/>.DBO.ObtieneProximosFechasProspectos(@P,GETDATE(),1) 
END
ELSE BEGIN
	SELECT TOP 5 CAST(R.IDPROSPECTO AS INT) AS IDPROSPECTO,CONVERT(DATETIME,R.FECHAHORA,@CONVERTCODE) AS FECHA,CAST(R.RECORDATORIO AS VARCHAR(MAX)) AS TEXTO,CAST(R.TKREC AS VARCHAR(MAX)) AS TK FROM 
		<#SESSION.DB/>.DBO.RECORDATORIOS R, <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA 
	WHERE 
		R.FECHAHORA > GETDATE() AND 
		R.IDUSUARIO = @IDUSUARIO AND 
		R.IDPROSPECTO IS NOT NULL AND 
		PA.IDPROSPECTO=R.IDPROSPECTO AND
		PA.FECHAPROXEVENTO IS NOT NULL
	ORDER BY R.IDPROSPECTO
END