//[tipo_consulta|Text,session.db|Untyped,session.idempresa|Untyped,]
-- select 

DECLARE @TIPO_CONSULTA INT
DECLARE @TIPO_CAMPOS VARCHAR(2)
DECLARE @TIPOCAMPO INT, @COMPARTIR INT

SET @TIPO_CONSULTA = CAST(:TIPO_CONSULTA AS INT)

IF @TIPO_CONSULTA = -2
 BEGIN
 	/* Todos Activos */
	SET @TIPO_CAMPOS = 'P'
	SET @TIPOCAMPO = 1
	SET @COMPARTIR = 3
 END
 
IF @TIPO_CONSULTA = -1
 BEGIN
 	/* Todos Incluye descartados */
	SET @TIPO_CAMPOS = 'P'
	SET @TIPOCAMPO = 1
	SET @COMPARTIR = 3
 END
ELSE
IF @TIPO_CONSULTA = 1
 BEGIN
 	/* Sólo prospectos */
	SET @TIPO_CAMPOS = 'P'
	SET @TIPOCAMPO = 1
	SET @COMPARTIR = 3
 END
ELSE
IF @TIPO_CONSULTA = 2
 BEGIN
 	/* Sólo oportunidades */
	SET @TIPO_CAMPOS = 'O'
	SET @TIPOCAMPO = 2
	SET @COMPARTIR = 4
 END
  

IF @TIPO_CONSULTA = 3
 BEGIN
 	/* Sólo ventas */
	SET @TIPO_CAMPOS = 'O'
	SET @TIPOCAMPO = 4
	SET @COMPARTIR = 2
 END


IF @TIPO_CONSULTA = 4
 BEGIN
 	/* Sólo descartados */
	SET @TIPO_CAMPOS = 'P'
	SET @TIPOCAMPO = 1
	SET @COMPARTIR = 3
 END
 
  
IF @TIPO_CONSULTA = 5
 BEGIN
 	/* Sólo clientes */
	SET @TIPO_CAMPOS = 'P'
	SET @TIPOCAMPO = 3
	SET @COMPARTIR = 1
 END
 
SELECT INDICE AS INDI,CAST(INDICE AS VARCHAR(2))+@TIPO_CAMPOS AS INDICE FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS
 WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND (TIPO = @TIPOCAMPO OR COMPARTIR = @COMPARTIR)  ORDER BY INDI DESC