//[session.idusuario|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,tipo_consulta|Integer,session.db|Untyped,tablaetiqueta|Text,fildesc_usuarios|Text,condiciondeetiquetas|Text,fildesc_desde|Text,fildesc_hasta|Text,]
--SELECT 
/*PROTEGIDO*/
	
DECLARE @IDEMPRESA INT
DECLARE @TIPO_CONSULTA INT
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES_OPORTUNIDADES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES_CLIENTES VARCHAR(MAX)
DECLARE @CAMPOS_PERSONALIZADOS_VALORES_VENTAS VARCHAR(MAX)

DECLARE @EXECSQL VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @CONVERTCODE INT
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/> 
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TIPO_CONSULTA = ISNULL(:TIPO_CONSULTA,0)

SET @CAMPOS_PERSONALIZADOS_VALORES  = <#SESSION.DB/>.DBO.ObtieneCamposLlave(@IDEMPRESA, 2, '<#SESSION.DB/>',1)
SET @CAMPOS_PERSONALIZADOS_VALORES_OPORTUNIDADES  = <#SESSION.DB/>.DBO.ObtieneCamposLlave(@IDEMPRESA, 2, '<#SESSION.DB/>',2)
SET @CAMPOS_PERSONALIZADOS_VALORES_CLIENTES  = <#SESSION.DB/>.DBO.ObtieneCamposLlave(@IDEMPRESA, 2, '<#SESSION.DB/>',3)
SET @CAMPOS_PERSONALIZADOS_VALORES_VENTAS  = <#SESSION.DB/>.DBO.ObtieneCamposLlave(@IDEMPRESA, 2, '<#SESSION.DB/>',4)

DECLARE @TABLAETIQUETA VARCHAR(MAX), @fildesc_usuarios VARCHAR(MAX), @CONDICIONDEETIQUETAS VARCHAR(MAX)
DECLARE @FILDESC_DESDE VARCHAR(MAX), @FILDESC_HASTA VARCHAR(MAX)

SET @TABLAETIQUETA = ISNULL(:TABLAETIQUETA,'')
SET @fildesc_usuarios = ISNULL(:fildesc_usuarios,'')
SET @CONDICIONDEETIQUETAS = ISNULL(:CONDICIONDEETIQUETAS,'')
SET @FILDESC_DESDE = ISNULL(:FILDESC_DESDE,'')
SET @FILDESC_HASTA = ISNULL(:FILDESC_HASTA,'')
SET @FILDESC_DESDE = REPLACE(@FILDESC_DESDE,'''''' ,'''')
SET @FILDESC_HASTA = REPLACE(@FILDESC_HASTA,'''''' ,'''')

IF @TIPO_CONSULTA = -2
 BEGIN
 	/* Todos Activos */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + ' SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, REPLACE(REPLACE(CAST(P.comentarios AS VARCHAR(MAX)),CHAR(13), ''''), CHAR(10), '''') AS COMENTARIOS , '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, PF.FASE, '
  SET @EXECSQL = @EXECSQL + ' U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO '+ @CAMPOS_PERSONALIZADOS_VALORES + ', '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS, CASE P.DESCARTADO WHEN 1 THEN ''DESCARTADO'' WHEN 0 THEN ''ACTIVO'' END AS STATUS,  '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO  '
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.USUARIOS U '+@TABLAETIQUETA+' WHERE P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +'''  '
  SET @EXECSQL = @EXECSQL + ' AND PO.IDORIGEN = P.IDORIGEN AND P.DESCARTADO = 0 AND P.IDFASE = PF.IDFASE AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND P.IDUSUARIO = U.IDUSUARIO '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+''
  EXEC (@EXECSQL)
  
 END
 
IF @TIPO_CONSULTA = -1
 BEGIN
 	/* Todos Incluye descartados */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + ' SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, REPLACE(REPLACE(CAST(P.comentarios AS VARCHAR(MAX)),CHAR(13), ''''), CHAR(10), '''') AS COMENTARIOS , '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, PF.FASE, '
  SET @EXECSQL = @EXECSQL + ' U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO '+ @CAMPOS_PERSONALIZADOS_VALORES + ', '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS, CASE P.DESCARTADO WHEN 1 THEN ''DESCARTADO'' WHEN 0 THEN ''ACTIVO'' END AS STATUS, SALESUP_CT.DBO.FechaFormato(P.DESCARTADOFECHA,1) as DESCARTADOFECHA , P.DESCARTADORAZON, '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO  '
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.USUARIOS U  '+@TABLAETIQUETA+' WHERE P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +'''  '
  SET @EXECSQL = @EXECSQL + ' AND PO.IDORIGEN = P.IDORIGEN AND P.IDFASE = PF.IDFASE AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND P.IDUSUARIO = U.IDUSUARIO '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+''
  EXEC (@EXECSQL)
 END
ELSE
IF @TIPO_CONSULTA = 1
 BEGIN
 	/* Sólo prospectos */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + ' SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, REPLACE(REPLACE(CAST(P.comentarios AS VARCHAR(MAX)),CHAR(13), ''''), CHAR(10), '''') AS COMENTARIOS , '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, PF.FASE, '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO '+ @CAMPOS_PERSONALIZADOS_VALORES + ' , <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS,  '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO '
  
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.USUARIOS U   '
  SET @EXECSQL = @EXECSQL + ' '+@TABLAETIQUETA+'  WHERE P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +''' AND P.IDUSUARIO = U.IDUSUARIO AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND PO.IDORIGEN = P.IDORIGEN '
  SET @EXECSQL = @EXECSQL + ' AND P.IDFASE = PF.IDFASE AND P.DESCARTADO = 0 AND P.ESCLIENTE = 0 AND P.ESOPORTUNIDAD = 0  '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+' '
  EXEC (@EXECSQL)
 END
ELSE
IF @TIPO_CONSULTA = 2
 BEGIN
 	/* Sólo oportunidades */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + 'SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO,L.LINEA_PRODUCTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, OFA.FASE '+ @CAMPOS_PERSONALIZADOS_VALORES + @CAMPOS_PERSONALIZADOS_VALORES_OPORTUNIDADES + ' ,  '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN ,O.CONCEPTO, O.MONTO , O.CERTEZA, O.FECHA_CIERRE, U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO , <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS , '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO '
  
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES OFA, <#SESSION.DB/>.dbo.USUARIOS U '+@TABLAETIQUETA+', <#SESSION.DB/>.dbo.OPORTUNIDADES O '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO L ON L.IDLINEA_PRODUCTO = O.IDLINEA_PRODUCTO '
  SET @EXECSQL = @EXECSQL + ' WHERE PO.IDORIGEN = P.IDORIGEN AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND O.IDFASE = OFA.IDFASE AND P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +''' AND O.IDUSUARIO = U.IDUSUARIO '
  SET @EXECSQL = @EXECSQL + ' AND P.DESCARTADO=0 AND P.ESOPORTUNIDAD=1 AND O.GANADA = 0 AND O.PERDIDA = 0 AND P.IDPROSPECTO = O.IDPROSPECTO '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+' '
  EXEC (@EXECSQL)
 END
  

IF @TIPO_CONSULTA = 3
 BEGIN
 	/* Sólo ventas */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + ' SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL,  '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO, P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, PF.FASE '+ @CAMPOS_PERSONALIZADOS_VALORES + @CAMPOS_PERSONALIZADOS_VALORES_VENTAS + ',  '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, O.CONCEPTO, V.MONTO, V.COMISION, V.FECHAHORA AS FECHA, V.NOPARCIALIDADES, V.ANTICIPOS_MONTO, V.SALDO_MONTO, U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO ,  '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS,  '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO ' 
  
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.OPORTUNIDADES O,  '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.VENTAS V, <#SESSION.DB/>.dbo.USUARIOS U  '+@TABLAETIQUETA+'  WHERE P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +''' AND V.IDUSUARIO = U.IDUSUARIO AND PO.IDORIGEN = P.IDORIGEN  '
  SET @EXECSQL = @EXECSQL + ' AND P.IDFASE = PF.IDFASE AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND P.DESCARTADO=0 AND P.ESCLIENTE = 1 AND P.IDPROSPECTO = O.IDPROSPECTO '
  SET @EXECSQL = @EXECSQL + ' AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+' '
  EXEC (@EXECSQL)
 END


IF @TIPO_CONSULTA = 4
 BEGIN
 	/* Sólo descartados */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + 'SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, REPLACE(REPLACE(CAST(P.comentarios AS VARCHAR(MAX)),CHAR(13), ''''), CHAR(10), '''') AS COMENTARIOS , '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO, PF.FASE, SALESUP_CT.DBO.FechaFormato(P.DESCARTADOFECHA,1) as DESCARTADOFECHA, '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, P.DESCARTADORAZON '+ @CAMPOS_PERSONALIZADOS_VALORES + ' , U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO, <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS , '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO '
  
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.USUARIOS U '+@TABLAETIQUETA+' '
  SET @EXECSQL = @EXECSQL + ' WHERE P.IDEMPRESA =  '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +''' AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND PO.IDORIGEN = P.IDORIGEN AND P.IDFASE = PF.IDFASE '
  SET @EXECSQL = @EXECSQL + ' AND DESCARTADO>0 AND P.IDUSUARIO = U.IDUSUARIO '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+' '
  EXEC (@EXECSQL)
 END
 
  
IF @TIPO_CONSULTA = 5
 BEGIN
 	/* Sólo clientes */
  SET @EXECSQL = ''
  SET @EXECSQL = @EXECSQL + ' SELECT '+CAST(@TIPO_CONSULTA AS VARCHAR(3))+' AS TIPO_CONSULTA,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.TITULO , P.CORREO, P.EMPRESA, CAST(P.NOEMPLEADOS AS VARCHAR(10)) AS NOEMPLEADOS, P.PUESTO, P.URL, P.TELEFONO, P.TELEFONO2, P.MOVIL, REPLACE(REPLACE(CAST(P.comentarios AS VARCHAR(MAX)),CHAR(13), ''''), CHAR(10), '''') AS COMENTARIOS ,  '
  SET @EXECSQL = @EXECSQL + ' SALESUP_CT.DBO.FechaFormato(P.FECHACONTACTO,2) AS FECHACONTACTO, P.DIRECCION1, P.DIRECCION2 , P.CODIGOPOSTAL , P.CIUDAD, P.IDESTADO,P.IDPAIS,PAS.PAIS,EDOS.ESTADO, MUN.MUNICIPIO,  '
  SET @EXECSQL = @EXECSQL + ' PO.ORIGEN, PF.FASE '+ @CAMPOS_PERSONALIZADOS_VALORES + @CAMPOS_PERSONALIZADOS_VALORES_CLIENTES + ' , U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO , <#SESSION.DB/>.DBO.ObtiqueEtiquetasProspecto(P.IDPROSPECTO) AS ETIQUETAS , '
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.TIEMPO_TXT(PS.FECHAHORA, GETDATE()) + '' - '' + SALESUP_CT.dbo.PreparaCadenaExportacion(PS.COMENTARIO) AS ULTIMOSEGUIMIENTO, SALESUP_CT.DBO.FechaFormato(PS.FECHAHORA,2) AS F_ULTIMOSEGUIMIENTO '
  
  SET @EXECSQL = @EXECSQL + ' , ISNULL(P.IDCOMPANIA,0) AS IDCOMPANIA, COM.EMPRESA AS NOMBREEMPRESA, COM.URL AS PAGINAEMPRESA, COM.TELEFONOCORPORATIVO, COM.DIRECCION1 AS CALLE, COM.DIRECCION2 AS COLONIA, '
  SET @EXECSQL = @EXECSQL + ' COM.CIUDAD AS CIUDADEMPRESA, COM.CODIGOPOSTAL AS CPEMPRESA, COM.IDESTADO AS EDOEMPRESA, COM.IDPAIS AS PAISEMPRESA, COM.NEMPLEADOS, CG.COMPANIAGRUPO, EI.INDUSTRIA '
  SET @EXECSQL = @EXECSQL + ' FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O, <#SESSION.DB/>.dbo.VENTAS V, <#SESSION.DB/>.dbo.PROSPECTOS P  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO  '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN PAISES PAS ON PAS.IDPAIS = P.IDPAIS'
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN ESTADOS EDOS ON EDOS.IDPAIS = P.IDPAIS AND EDOS.IDESTADO = P.IDESTADO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN MUNICIPIOS MUN ON MUN.IDPAIS = P.IDPAIS AND MUN.IDESTADO = P.IDESTADO AND MUN.IDMUNICIPIO = P.IDMUNICIPIO '
  SET @EXECSQL = @EXECSQL + ' LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA ,'
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES PO, '
  
  SET @EXECSQL = @EXECSQL + ' <#SESSION.DB/>.dbo.PROSPECTOS_FASES PF, <#SESSION.DB/>.dbo.USUARIOS U  '+@TABLAETIQUETA+' WHERE p.escliente=1 and P.IDEMPRESA = '''+CAST(@IDEMPRESA  AS VARCHAR(8)) +''' '
  SET @EXECSQL = @EXECSQL + ' AND P.IDFASE = PF.IDFASE AND PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO AND PO.IDORIGEN = P.IDORIGEN AND P.IDUSUARIO = U.IDUSUARIO AND O.IDPROSPECTO = P.IDPROSPECTO AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND V.NUEVA = 1 '+@fildesc_usuarios+' '+@CONDICIONDEETIQUETAS+' '+@FILDESC_DESDE+' '+@FILDESC_HASTA+' '
  EXEC (@EXECSQL)
 END


EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, 16, '', @CONVERTCODE, '', ''
