//[tipo_consulta|Integer,session.db|Untyped,session.idempresa|Untyped,]
DECLARE @CAMPOS_PERSONALIZADOS_NOMBRES VARCHAR(1028)
DECLARE @CAMPOS_PERSONALIZADOS_TAGS VARCHAR(1028)
DECLARE @TIPO_CONSULTA INT,@TIPO_CAMPOS INT

SET @TIPO_CONSULTA = ISNULL(:TIPO_CONSULTA,0)

IF @TIPO_CONSULTA = -2
 BEGIN
 	/* Todos Activos */
	SET @TIPO_CAMPOS = 1
 END
 
IF @TIPO_CONSULTA = -1
 BEGIN
 	/* Todos Incluye descartados */
	SET @TIPO_CAMPOS = 1
 END
ELSE
IF @TIPO_CONSULTA = 1
 BEGIN
 	/* Sólo prospectos */
	SET @TIPO_CAMPOS = 1
 END
ELSE
IF @TIPO_CONSULTA = 2
 BEGIN
 	/* Sólo oportunidades */
	SET @TIPO_CAMPOS = 2
 END
  

IF @TIPO_CONSULTA = 3
 BEGIN
 	/* Sólo ventas */
	SET @TIPO_CAMPOS = 4
 END


IF @TIPO_CONSULTA = 4
 BEGIN
 	/* Sólo descartados */
	SET @TIPO_CAMPOS = 1
 END
 
  
IF @TIPO_CONSULTA = 5
 BEGIN
 	/* Sólo clientes */
	SET @TIPO_CAMPOS = 3
 END

SET @CAMPOS_PERSONALIZADOS_NOMBRES  = <#SESSION.DB/>.DBO.ObtieneCamposPersonalizables(<#SESSIOn.IDEMPRESA/>, 1, '<#SESSION.DB/>',@TIPO_CAMPOS)
SELECT @CAMPOS_PERSONALIZADOS_NOMBRES AS CAMPOS_PERSONALIZADOS, @TIPO_CONSULTA AS TIPO_CONSULTA