//[session.idusuario|Untyped,session.idempresa|Untyped,filtros|Text,session.db|Untyped,]
-- Select
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @FILTROS VARCHAR(MAX) = ISNULL(:FILTROS,'')

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ESTIMACION_DE_VENTAS @IDUSUARIO,@IDEMPRESA,@FILTROS,1,0