//[session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,OBJETO|Text]
-- SELECT
DECLARE @IDUSUARIO INT  
DECLARE @IDEMPRESA INT  
DECLARE @OBJETO VARCHAR(MAX) 
DECLARE @TOTAL INT = 0

SET @OBJETO = ISNULL(:OBJETO, '') 
SET @IDUSUARIO = ISNULL(<#SESSION.IDUSUARIO/>, '') 
SET @IDEMPRESA = ISNULL(<#SESSION.IDEMPRESA/>, '') 
	

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_DETALLE_COBROS_PENDIENTES @IDEMPRESA, @IDUSUARIO, @OBJETO, @TOTAL

