//[session.idusuario|Untyped,idreporte|Integer,idpantalla|Integer,filtro|Integer,session.db|Untyped,]
-- DELETE
--DELETE
DECLARE @IDUSUARIO INT, @IDREPORTE INT, @IDPANTALLA INT, @IDFILTRO INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDREPORTE = CAST(ISNULL(:IDREPORTE,0) AS INT)
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS INT)
SET @IDFILTRO = CAST(ISNULL(:FILTRO,0) AS INT)

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA AND IDUSUARIOFILTRO = @IDFILTRO