//[session.idusuario|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,idreporte|Integer,session.db|Untyped,]
-- SELECT 

DECLARE @IDUSUARIO INT, @IDREPORTE INT, @IDGRUPO INT, @IDEMPRESA INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @IDREPORTE = :IDREPORTE

SELECT IDUSUARIOREPORTE,NOMBRE,FILTRO,PORDEFECTO 
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES 
WHERE IDREPORTE = @IDREPORTE AND (IDUSUARIO = @IDUSUARIO OR (IDUSUARIO IN(SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDEMPRESA = @IDEMPRESA) AND (COMPARTIRCON = 1 OR COMPARTIRCON = 2 OR (COMPARTIRCON = 3 AND @IDGRUPO IN (COMPARTIDOS)))))
