//[session.idusuario|Untyped,idreporte|Integer,idpantalla|Integer,filtro|Text,ocultaglobo|Integer,session.db|Untyped,]
-- INSERT

DECLARE @SQLTXT VARCHAR(MAX),@FILTRO VARCHAR(MAX), @TEXTO VARCHAR(256), @CONFIG VARCHAR(512)
DECLARE @IDUSUARIO INT,@IDREPORTE INT, @IDPANTALLA INT, @EXISTEFILTRO INT, @TIPO INT, @AGRUPACION INT, @OCULTAGLOBO INT
DECLARE @VALOR VARCHAR(MAX)

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,CONSULTA VARCHAR(256), TEXTO VARCHAR(256), VALOR VARCHAR(256),AGRUPACION INT,TIPO INT)

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDREPORTE = ISNULL(:IDREPORTE,0)
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SET @FILTRO = CAST(ISNULL(:FILTRO,'') AS VARCHAR(MAX))
SET @OCULTAGLOBO = CAST(ISNULL(:OCULTAGLOBO,0) AS INT)

INSERT INTO @TABLATEMP (CONSULTA,TEXTO,VALOR,AGRUPACION,TIPO)
Select 
max(case when NAME='consulta' then STRINGVALUE else '' end),
max(case when NAME='texto' then STRINGVALUE else '' end),
max(case when NAME='valor' then STRINGVALUE else '' end),
max(case when NAME='agrupacion' then STRINGVALUE else '' end),
max(case when NAME='tipoFiltro' then STRINGVALUE else '' end)
from SALESUP_CT.dbo.parseJSON(@FILTRO)
WHERE parent_id IS NOT NULL AND object_id IS NULL
group by PARENT_ID

SELECT @TIPO = TIPO, @AGRUPACION = AGRUPACION, @TEXTO = TEXTO, @VALOR = VALOR, @CONFIG = '{"VALOR":"'+VALOR+'","CONSULTA":"'+CONSULTA+'"}' FROM @TABLATEMP

IF(@VALOR = '-1')
BEGIN
	 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDPANTALLA AND TIPO = @TIPO AND IDREPORTE = @IDREPORTE
END
ELSE
BEGIN
SELECT @EXISTEFILTRO = COUNT(IDUSUARIOFILTRO) FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA AND TIPO = @TIPO

IF(@EXISTEFILTRO = 0)
BEGIN
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO,IDPANTALLA,TIPO,TEXTO,SQLTXT,SQLTXT_EXP,IDREPORTE) VALUES (@IDUSUARIO,@IDPANTALLA,@TIPO,@TEXTO,@CONFIG,@OCULTAGLOBO,@IDREPORTE)
END
ELSE
BEGIN
	DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDPANTALLA = @IDPANTALLA AND TIPO = @TIPO AND IDREPORTE = @IDREPORTE
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO,IDPANTALLA,TIPO,TEXTO,SQLTXT,SQLTXT_EXP,IDREPORTE) VALUES (@IDUSUARIO,@IDPANTALLA,@TIPO,@TEXTO,@CONFIG,@OCULTAGLOBO,@IDREPORTE)
END
END