//[session.idusuario|Untyped,idreporte|Integer,idusuarioreporte|Integer,idpantalla|Integer,session.db|Untyped,]
--DELETE

DECLARE @IDUSUARIO INT, @IDREPORTE INT, @IDUSUARIOREPORTE INT, @IDPANTALLA INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDREPORTE = CAST(ISNULL(:IDREPORTE,0) AS INT)
SET @IDUSUARIOREPORTE = CAST(ISNULL(:IDUSUARIOREPORTE,0) AS INT)
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS INT)

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA
DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDUSUARIOREPORTE = @IDUSUARIOREPORTE