//[idusuarioreporte|Integer,idreporte|Integer,session.db|Untyped,]
-- SELECT

DECLARE @IDUSUARIOREPORTE INT, @IDREPORTE INT

SET @IDUSUARIOREPORTE = CAST(ISNULL(:IDUSUARIOREPORTE,0) AS INT)
SET @IDREPORTE = CAST(ISNULL(:IDREPORTE,0) AS INT) 

SELECT FILTRO,NOMBRE,COMPARTIRCON,COMPARTIDOS FROM <#SESSION.DB>.DBO.USUARIOS_REPORTES WHERE IDUSUARIOREPORTE = @IDUSUARIOREPORTE AND IDREPORTE = @IDREPORTE