//[session.idempresa|Untyped,session.idusuario|Untyped,idfiltro|Integer,session.db|Untyped,]
-- SELECT
DECLARE @IDFILTRO INT, @IDEMPRESA INT
DECLARE @CONSULTA VARCHAR(MAX), @CONDICION VARCHAR(MAX),@CONSUL VARCHAR(MAX),@LINK VARCHAR(512)
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,VALOR VARCHAR(MAX), TEXTO VARCHAR(MAX),CAMPO VARCHAR(512),CONDICION VARCHAR(MAX))
DECLARE @TO INT, @TOTAL INT
DECLARE @IDUSUARIO INT

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>

SELECT @LINK = SERVIDOR FROM CONTROL.CONTROL.DBO.BASES_CONTEO B, CONTROL.CONTROL.DBO.EMPRESAS E WHERE E.BD_ACTUAL = B.DATA_BASE AND E.IDEMPRESA = @IDEMPRESA

SET @IDFILTRO = ISNULL(:IDFILTRO,0)

SELECT @CONSULTA = REPLACE(REPLACE(REPLACE(CONSULTA,'@DB','<#SESSION.DB/>'),'@IDEMPRESA',@IDEMPRESA), '@IDUSUARIO', @IDUSUARIO),@CONDICION = CRITERIO FROM SALESUP_CT.DBO.FILTROS_DETALLE WHERE IDFILTRO = @IDFILTRO
INSERT INTO @TABLATEMP (VALOR,TEXTO,CAMPO) EXEC(@CONSULTA)

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
SET @TO = 1

WHILE @TO <= @TOTAL
BEGIN
	SELECT @CONSUL = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@CONDICION,'@CAMPO',CAMPO),'@VALOR',VALOR),'@LINK',@LINK),'@DB','<#SESSION.DB/>'),'@IDEMPRESA',@IDEMPRESA), '@IDUSUARIO',@IDUSUARIO ) FROM @TABLATEMP WHERE ID = @TO
	UPDATE @TABLATEMP SET CONDICION = @CONSUL WHERE ID = @TO
	SET @TO = @TO+1
END

SELECT * FROM @TABLATEMP