//[idreporte|Integer,]
-- SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDREPORTE INT
SET @IDREPORTE = ISNULL(:IDREPORTE,0)

SELECT IDREPORTEVISTAS,VISTA,NOMBRECOLUMNA FROM SALESUP_CT.dbo.REPORTES_VISTAS WHERE IDREPORTE = @IDREPORTE