//[session.idusuario|Untyped,idreporte|Integer,idpantalla|Integer,tiporeporte|Integer,cambiafiltro|Integer,idfiltro|Integer,valor|Text,session.db|Untyped,]
--UPDATE

DECLARE @IDUSUARIO INT, @IDREPORTE INT, @IDPANTALLA INT, @CAMBIAFILTRO INT,@IDFILTRO INT
DECLARE @TIPOREPORTE VARCHAR(3)
DECLARE @VALOR VARCHAR(MAX), @SQLTXT VARCHAR(MAX)
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,idfiltro INT, valor VARCHAR(MAX), texto VARCHAR(MAX))

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDREPORTE = ISNULL(:IDREPORTE,0)
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SET @TIPOREPORTE = ISNULL(:TIPOREPORTE,0)
SET @CAMBIAFILTRO = ISNULL(:CAMBIAFILTRO,0) 
SET @IDFILTRO = ISNULL(:IDFILTRO,0)
SET @VALOR = ISNULL(:VALOR,'')

IF(@CAMBIAFILTRO = 1)
BEGIN
	SELECT @SQLTXT = SQLTXT FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA
	
	INSERT INTO @TABLATEMP (idfiltro,valor,texto)
	Select 
		   max(case when NAME='idfiltro' then STRINGVALUE else '' end),
		   max(case when NAME='valor' then STRINGVALUE else '' end),
		   max(case when NAME='texto' then STRINGVALUE else '' end)
	from SALESUP_CT.dbo.parseJSON(@SQLTXT)
	WHERE parent_id IS NOT NULL AND object_id IS NULL
	group by PARENT_ID
	
	UPDATE @TABLATEMP SET valor = @VALOR, texto = @VALOR where idfiltro = @IDFILTRO
	
	select @SQLTXT = STUFF((
        select 
            ',{"idfiltro":' + cast(idfiltro as varchar(max))
            + ',"valor":"' + valor + '"'
            + ',"texto":' + cast(texto as varchar(max))
			+ ',"tipo":"1"'
            +'}'

        from @TABLATEMP
        for xml path(''), type
    ).value('.', 'varchar(max)'), 1, 1, '')
    
    UPDATE <#SESSION.DB/>.DBO.USUARIOS_FILTROS SET SQLTXT = @SQLTXT WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA
END
ELSE IF(@CAMBIAFILTRO = 3 AND @IDREPORTE != 3)
BEGIN
	 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA
	 SET @SQLTXT = '{"idfiltro":"2","valor":"'+CAST(YEAR(GETDATE())AS VARCHAR(4))+'","texto":"'+CAST(YEAR(GETDATE())AS VARCHAR(4))+'","tipo":"1"}'
	 
	INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP, IDREPORTE) VALUES(@IDUSUARIO,@IDPANTALLA,0,'',@SQLTXT,@TIPOREPORTE,@IDREPORTE)
END
ELSE
BEGIN
	 DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA
	 INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO, IDPANTALLA, TIPO, TEXTO, SQLTXT, SQLTXT_EXP, IDREPORTE) VALUES(@IDUSUARIO,@IDPANTALLA,0,'','',@TIPOREPORTE,@IDREPORTE)
END