//[session.idusuario|Untyped,idpantalla|Integer,idreporte|Integer,idusuariofiltro|Integer,session.db|Untyped,]
-- INSERT 

DECLARE @IDUSUARIOFILTRO INT, @IDUSUARIO INT, @IDPANTALLA INT, @IDREPORTE INT
DECLARE @FILTRO VARCHAR(MAX), @NOMBREREPORTE VARCHAR(512),@SQLTXT VARCHAR(256),@SQLTXT_EXP VARCHAR(256)

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SET @IDREPORTE = ISNULL(:IDREPORTE,0)
SET @IDUSUARIOFILTRO = ISNULL(:IDUSUARIOFILTRO,0)

SELECT @FILTRO = FILTRO, @NOMBREREPORTE = NOMBRE FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES WHERE IDUSUARIOREPORTE = @IDUSUARIOFILTRO

DECLARE @TABLATEMP TABLE (ID INT IDENTITY, IDFILTRO INT, VALOR VARCHAR(128),TEXTO VARCHAR(256),TIPOREPORTE INT, NOMBRE VARCHAR(512))

INSERT INTO @TABLATEMP (IDFILTRO,VALOR,TEXTO,TIPOREPORTE,NOMBRE)
SELECT 
max(case when NAME='IDFILTRO' then STRINGVALUE else '' end) as IDFILTRO,
max(case when NAME='VALOR' then STRINGVALUE else '' end) as VALOR,
max(case when NAME='TEXTO' then STRINGVALUE else '' end) as TEXTO,
max(case when NAME='TIPOREPORTE' then STRINGVALUE else '' end) as TIPOREPORTE,
@NOMBREREPORTE AS NOMBRE
FROM SALESUP_CT.dbo.parseJSON(@FILTRO) WHERE parent_id IS NOT NULL AND object_id IS NULL 

IF(@FILTRO <> '')
BEGIN
	 SELECT @SQLTXT = '{"idfiltro":"'+CAST(IDFILTRO AS VARCHAR(128))+'","valor":"'+VALOR+'","texto":"'+NOMBRE+'","tipo":"2","idusuarioreporte":"'+CAST(@IDUSUARIOFILTRO AS VARCHAR(128))+'"}', @SQLTXT_EXP = TIPOREPORTE FROM @TABLATEMP
END
ELSE
BEGIN
	 SELECT @SQLTXT = '', @SQLTXT_EXP = TIPOREPORTE FROM @TABLATEMP
END

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_FILTROS (IDUSUARIO,IDPANTALLA,TIPO,TEXTO,SQLTXT,SQLTXT_EXP,IDREPORTE) VALUES(@IDUSUARIO,@IDPANTALLA,0,'',@SQLTXT,@SQLTXT_EXP,@IDREPORTE)