//[session.idusuario|Untyped,idreporte|Integer,idpantalla|Integer,agrupacion|Integer,session.db|Untyped,]
-- SELECT
DECLARE @IDUSUARIO INT, @IDREPORTE INT, @IDPANTALLA INT, @AGRUPACION INT
DECLARE @TIPOREPORTE VARCHAR(256)

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDREPORTE = CAST(ISNULL(:IDREPORTE,0) AS INT)
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS INT)
SET @AGRUPACION = CAST(ISNULL(:AGRUPACION,0) AS INT)

SELECT TEXTO, SQLTXT, SQLTXT_EXP,IDUSUARIOFILTRO AS FILTRO,TIPO, @IDREPORTE AS IDREPORTE, @IDPANTALLA AS IDPANTALLA, @AGRUPACION AS AGRUPACION FROM <#SESSION.DB/>.DBO.USUARIOS_FILTROS WHERE IDUSUARIO = @IDUSUARIO AND IDREPORTE = @IDREPORTE AND IDPANTALLA = @IDPANTALLA 