//[idreporte|Integer,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDREPORTE INT
SET @IDREPORTE = ISNULL(:IDREPORTE,0)
SELECT NOMBRE, TIPODEGRAFICA, DATOS AS TOKEN, CONFIGURACIONGENERAL,CONFIGURACIONTABLA FROM SALESUP_CT.DBO.REPORTES WHERE IDREPORTE = @IDREPORTE