//[session.db|Untyped,producto|Text,comision|Numeric,iproducto|Integer,tk|Text,]
--UPDATE 
DECLARE @TK VARCHAR(256) 
DECLARE @COMISION FLOAT 
DECLARE @PRODUCTO VARCHAR(MAX)
DECLARE @IDLINEA_PRODUCTO INT 

SET @TK=ISNULL(:TK, '') 
SET @COMISION=ISNULL(:COMISION, 0) 
SET @PRODUCTO=ISNULL(:PRODUCTO, '') 

SELECT @IDLINEA_PRODUCTO=IDLINEA_PRODUCTO FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE TK = @TK

update <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO set linea_producto = @PRODUCTO , 
COMISION =  @COMISION /100 where IDLINEA_PRODUCTO = @IDLINEA_PRODUCTO



delete from <#SESSION.DB/>.DBO.USUARIOS_LINEAS_COMISION where IDLINEA = @IDLINEA_PRODUCTO