//[session.idempresa|Untyped,session.db|Untyped,tk|Text,]
--SELECT 
/*PROTEGIDO*/
DECLARE @IDEMPRESA  INT 
DECLARE @IDLINEA_PRODUCTO INT 
DECLARE @TOTALLINEASOPORTUNIDADES INT 
DECLARE @TOTLINEASPRODUCTOS INT 
DECLARE @TK VARCHAR(256)

SET @IDEMPRESA= '<#SESSION.IDEMPRESA/>'
SET @TK = ISNULL(:TK, 0) 
SET @TOTALLINEASOPORTUNIDADES = 0 
SET @TOTLINEASPRODUCTOS = 0
SELECT @IDLINEA_PRODUCTO=IDLINEA_PRODUCTO FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO WHERE TK=@TK

SELECT @TOTALLINEASOPORTUNIDADES=COUNT(*)  
FROM  <#SESSION.DB/>.DBO.OPORTUNIDADES 
WHERE IDLINEA_PRODUCTO= @IDLINEA_PRODUCTO 
SELECT @TOTLINEASPRODUCTOS=COUNT(*) 
FROM <#SESSION.DB/>.DBO.PRODUCTOS 
WHERE IDLINEA_PRODUCTO=@IDLINEA_PRODUCTO AND IDEMPRESA=@IDEMPRESA

SELECT @TOTALLINEASOPORTUNIDADES AS TOTALOPORTUNIDADES, @TOTLINEASPRODUCTOS AS TOTALPRODUCTOS