//[session.idempresa|Untyped,session.db|Untyped,tkopt|Text,]
--SELECT
/*PROTEGIDO*/


DECLARE @IDEMPRESA INT 
DECLARE @TKO VARCHAR(MAX)


SET  @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET  @TKO=ISNULL(:TKOPT, '')



SELECT  U.NIVEL AS NIVEL, U.IDGRUPO AS IDGRUPO, O.IDUSUARIO 
	    FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O
		LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS  U ON U.IDUSUARIO=O.IDUSUARIO
WHERE O.TKO=@TKO  AND U.IDEMPRESA=@IDEMPRESA