//[idoportunidad|Integer,tko|Text,session.db|Untyped,]
--SELECT
DECLARE @IDOPORTUNIDAD INT
DECLARE @TKO VARCHAR(148)

SET @IDOPORTUNIDAD=ISNULL(:IDOPORTUNIDAD, 0)
SET @TKO=ISNULL(:TKO , '')
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.DBO.ObtieneIdOportunidad(@tko) END


SELECT P.IDPROSPECTO, P.TKP 
FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P
WHERE O.IDOPORTUNIDAD = @IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO