//[tkcom|Text,descartado|Text,session.db|Untyped,f_usuario|Text,crit|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :CRIT , '')
DECLARE @F_USUARIO VARCHAR(MAX) SET @F_USUARIO = ISNULL( :F_USUARIO , '')

SET @SQL = '
 DECLARE @IDCOMPANIA INT
 DECLARE @DESCARTADO TINYINT

 DECLARE @TkCom VARCHAR(64)
 SET @TkCom = ISNULL( ''' + ISNULL( :TKCOM , '') + ''', '''')
 SET @DESCARTADO= ISNULL( CAST (' + ISNULL( :DESCARTADO , 0) +' AS INT), 0)
 SELECT @IDCOMPANIA = 0

 IF @TkCom != ''''
 BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
 END


SELECT 
 count(*) AS TotalResgistros
 
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK)
  LEFT JOIN <#SESSION.DB/>.dbo.DOCUMENTO_ICONOS WITH(NOLOCK) ON O.ARCHIVO != '''' AND 
  EXTENSION = <#SESSION.DB/>.dbo.obtiene_extension(ARCHIVO)
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON O.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO, 
  <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK), 
  <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F WITH(NOLOCK), <#SESSION.DB/>.dbo.USUARIOS U 
  WITH(NOLOCK), <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK)

WHERE 
  O.PERDIDA=0 
  AND O.GANADA = 0 
  AND O.IDPROSPECTO = P.IDPROSPECTO
  '  +  @F_USUARIO +' 
  AND P.DESCARTADO=0 
  AND O.IDUSUARIO = U.IDUSUARIO 
  AND O.IDFASE = F.IDFASE 
  AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
  AND P.IDCOMPANIA=@IDCOMPANIA

' + @CRIT 


EXEC (@SQL) 