//[idprospecto|Integer,idoportunidad|Integer,pesokb|Numeric,cotizacion|Text,tipoarchivo|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,tkp|Text,tko|Text,]
--insert
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @PESOKB FLOAT
DECLARE @CONCEPTO VARCHAR(8000)
DECLARE @COTIZACION VARCHAR(8000)
DECLARE @TIPOARCHIVO VARCHAR(1000)
DECLARE @ARCHIVO VARCHAR(256)

SET @IDPROSPECTO=CAST(ISNULL(:IDPROSPECTO,0) AS INT)
SET @IDOPORTUNIDAD=CAST(ISNULL(:idoportunidad,0) AS INT)
SET @PESOKB=CAST(ISNULL(:pesokb,0) AS FLOAT)
SET @CONCEPTO=''
SET @COTIZACION=ISNULL(:cotizacion,'')
SET @TIPOARCHIVO=ISNULL(:tipoarchivo,'')
SET @ARCHIVO  = <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PROSPECTOS(@COTIZACION)


DECLARE @TKP VARCHAR(MAX), @TKO VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
SET @TKO = ISNULL(:TKO,'')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, <#SESSION.IDEMPRESA/>) END
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END

  INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_ARCHIVOS_AMAZON (IDEMPRESA,IDUSUARIO,ARCHIVO,PESO,TIPO) VALUES (<#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,@COTIZACION,@PESOKB,@TIPOARCHIVO)
  
  IF @IDOPORTUNIDAD=0
   BEGIN
    SELECT @CONCEPTO=CONCEPTO FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD=@IDOPORTUNIDAD
	INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS (IDPROSPECTO,IDUSUARIO,ARCHIVO,DESCRIPCION,AMAZON,PESO) VALUES (@IDPROSPECTO,<#SESSION.IDUSUARIO/>,@COTIZACION,@CONCEPTO,1,@PESOKB)
	  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)
      VALUES (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, 'Se agregó un archivo: '+@ARCHIVO+'', 1 )
   END
  ELSE
  BEGIN
    INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS (IDPROSPECTO,IDOPORTUNIDAD,IDUSUARIO,ARCHIVO,DESCRIPCION,AMAZON,PESO) VALUES (@IDPROSPECTO,@IDOPORTUNIDAD,<#SESSION.IDUSUARIO/>,@COTIZACION,@CONCEPTO,1,@PESOKB)
	INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, COMENTARIO, SISTEMA)
    VALUES (@IDPROSPECTO,@IDOPORTUNIDAD, <#SESSION.IDUSUARIO/>, 'Se agregó un archivo: '+@ARCHIVO+'', 1 )
  END    
  

