//[idoportunidad|Integer,session.db|Untyped,session.idusuario|Untyped,]
--select
DECLARE @IDOPORTUNIDAD INT 

SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD, 0)

select isnull(P.INDICE,0) AS COMISION, O.IDEMPRESAMONEDA, O.TIPOCAMBIO, O.IDDOCUMENTO from <#SESSION.DB/>.dbo.USUARIOS  U 
LEFT JOIN  <#SESSION.DB/>.dbo.OPORTUNIDADES O ON O.IDUSUARIO=U.IDUSUARIO
LEFT JOIN <#SESSION.DB/>.dbo.PRODUCTOS_COMISIONES P ON U.COMISION = P.IDPRODUCTO_COMISION   where O.IDOPORTUNIDAD=@IDOPORTUNIDAD AND U.IDUSUARIO=<#SESSION.IDUSUARIO/>


