//[id|Integer,session.db|Untyped,session.idusuario|Untyped,tk|Text,]
--insert
DECLARE @ID INT
SET @ID = ISNULL(:ID,0)


DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @NOMBRE VARCHAR(255), @TK VARCHAR(MAX)

SET @TK = ISNULL(:TK,'')

IF @TK != '' BEGIN SELECT @ID = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE TKARCH = @TK END


IF (@ID>0)
BEGIN

SELECT @NOMBRE =  <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PROSPECTOS(ARCHIVO), @IDPROSPECTO = IDPROSPECTO , @IDOPORTUNIDAD = IDOPORTUNIDAD  
FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE IDPROSPECTOARCHIVO = @ID
INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)
VALUES (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, 'Se eliminó un archivo: '+@NOMBRE+'', 1 )



DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE IDPROSPECTOARCHIVO=@ID

END