//[idprospecto|Text,idoportunidad|Text,session.idempresa|Untyped,session.idusuario|Untyped,razones|Text,comentario|Text,enviaactivado|Text,session.convertcode|Untyped,session.db|Untyped,tkp|Text,tko|Text,]
--INSERT
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @RAZONES INT
DECLARE @COMENTARIO VARCHAR(258)
DECLARE @ENVIAACTIVADO INT
DECLARE @CONVERTCODE INT
DECLARE @NOTIFICAR INT 

SET @IDPROSPECTO = CAST(:IDPROSPECTO AS INT)
SET @IDOPORTUNIDAD = CAST(:IDOPORTUNIDAD AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO   =CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @RAZONES = CAST(:RAZONES AS INT)
SET @COMENTARIO =  :COMENTARIO 
SET @ENVIAACTIVADO = CAST(:EnviaActivado AS INT)
SET @CONVERTCODE  = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @NOTIFICAR=  1

DECLARE @TKP VARCHAR(MAX), @TKO VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
SET @TKO = ISNULL(:TKO,'')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END

EXEC <#SESSION.DB/>.DBO.SP_DESCARTAR_OPORTUNIDAD @IDPROSPECTO,@IDOPORTUNIDAD, @IDEMPRESA, @IDUSUARIO, @RAZONES, @COMENTARIO, @ENVIAACTIVADO, @CONVERTCODE,@NOTIFICAR
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS 1,<#SESSION.IDUSUARIO/>

 
 