//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
SELECT IDLINEA_PRODUCTO as value, LINEA_PRODUCTO as Opcion, SALESUP_CT.dbo.esCanalizado(TK, TKM) AS esCanalizado, L.COMISION
FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO L
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_LINEAS_COMISION C ON  C.IDUSUARIO = <#SESSION.IDUSUARIO/> AND L.IDLINEA_PRODUCTO = C.IDLINEA 
WHERE L.IDEMPRESA = <#SESSION.IDEMPRESA/> ORDER BY LINEA_PRODUCTO