//[session.idempresa|Untyped,tkp|Text,session.db|Untyped,listap|Text,idprospecto|Integer,]
--SELECT 

DECLARE @IDPROSPECTO INT
DECLARE @esCanalizado int
DECLARE @LISTAP VARCHAR(MAX)
DECLARE @IDEMPRESA INT 
DECLARE @TKP VARCHAR(256) 


SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TKP=ISNULL(:TKP, '') 
IF (@TKP!='')
 BEGIN 
  SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDEMPRESA=@IDEMPRESA AND TKP=@TKP 
 END
ELSE
 BEGIN
 SET @IDPROSPECTO=ISNULL(:IDPROSPECTO, '') 
 END   

SET @LISTAP=ISNULL(:listap,'')
SET @ESCANALIZADO = 0
SELECT @esCanalizado = SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM)  
FROM <#SESSION.DB/>.DBO.PROSPECTOS P
WHERE P.IDPROSPECTO = @IDPROSPECTO


SELECT @esCanalizado = @esCanalizado+SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM)  
FROM <#SESSION.DB/>.DBO.PROSPECTOS P , dbo.split(@LISTAP, ',') L
WHERE P.IDPROSPECTO = L.SPLITVALUE and idempresa = @IDEMPRESA


DECLARE @PERMITE_OTRO INT
SELECT  @PERMITE_OTRO = ISNULL(PERMITIR_DESCARTAR_OTRO, 1) FROM  <#SESSION.DB/>.DBO.EMPRESAS E WHERE IDEMPRESA = @IDEMPRESA

SELECT COUNT(*) AS NUM_OP , @esCanalizado AS esCanalizado,  @PERMITE_OTRO AS  PERMITE_OTRO
FROM <#SESSION.DB/>.DBO.OPORTUNIDADES  O, <#SESSION.DB/>.DBO.PROSPECTOS P
WHERE O.IDPROSPECTO = P.IDPROSPECTO AND O.PERDIDA = 0 AND P.IDPROSPECTO = @IDPROSPECTO AND P.ESCLIENTE = 0
