//[session.convertcode|Untyped,ltfecha_ini|Text,ltfecha_fin|Text,ltnoches|Text,ltindices|Text,ltimpuesto|Text,ltcomision|Text,indicecomision|Integer,ltmontosubtotal|Text,ltmontodescuento|Text,ltmontototal|Text,session.db|Untyped,session.idempresa|Untyped,idoportunidad|Integer,ltidproducto|Text,ltdescripcion|Text,ltcantidad|Text,ltprecio|Text,ltnombreprecio|Text,descuento|Text,descuento_pct|Text,documentocotizacion|Integer,total|Text,monto|Text,subtotal|Text,decotizacion|Integer,json_subtotales|Text,tipocambio|Numeric,idempresamoneda|Integer,impuestosmonto|Numeric,tproductos|Integer,ltdescuentos|Text,ltdescuentos_porc|Text,ltcomentarios|Text,]
--insert
/*PROTEGIDO*/
DECLARE @IDOPORTUNIDAD AS INT
DECLARE @LTIDPRODUCTO VARCHAR(MAX)
DECLARE @LTDESCRIPCION VARCHAR(MAX)
DECLARE @LTCANTIDAD VARCHAR(MAX)
DECLARE @LTPRECIO VARCHAR(MAX)
DECLARE @LTNOMBREPRECIO VARCHAR(MAX)
DECLARE @DESCUENTO VARCHAR(MAX)
DECLARE @DESCUENTO_PCT VARCHAR(MAX)
DECLARE @SUBTOTAL VARCHAR(MAX)
DECLARE @IDIMPUESTO INT
DECLARE @TIPOCAMBIO FLOAT
DECLARE @IDEMPRESAMONEDA INT
DECLARE @PLANTILLA_SELECCIONADA INT
DECLARE @TOTAL VARCHAR(MAX)
DECLARE @MONTO VARCHAR(MAX)
DECLARE @DECOTIZACION INT
DECLARE @JSON_SUBTOTALES NVARCHAR(MAX)
DECLARE @IMPUESTOS FLOAT
DECLARE  @IndImp varchar(max)
DECLARE  @IndCantidad varchar(max)
DECLARE  @ltComision varchar(max)
DECLARE @indiceComision INT
DECLARE @ltMontoSubtotal VARCHAR(MAX) 
DECLARE @ltMontoDescuento VARCHAR(MAX)
DECLARE @ltMontoTotal VARCHAR(MAX) 
DECLARE @TIENEPRODUCTOS INT

DECLARE @LTFECHA_INI VARCHAR(MAX)
DECLARE @LTFECHA_FIN VARCHAR(MAX)
DECLARE @LTNOCHES VARCHAR(MAX)
DECLARE @CONVERTCODE INT

DECLARE @LTDESCUENTOS VARCHAR(MAX)
DECLARE @LTDESCUENTOS_PORC VARCHAR(MAX)
DECLARE @LTCOMENTARIOS VARCHAR(MAX)

SET @CONVERTCODE   = <#SESSION.CONVERTCODE/>

SET @LTFECHA_INI = ISNULL(:LTFECHA_INI,'')
SET @LTFECHA_FIN = ISNULL(:LTFECHA_FIN,'')
SET @LTNOCHES    = ISNULL(:LTNOCHES, '')

SET @IndImp = ISNULL(:LTINDICES,'')
SET @IndCantidad = ISNULL(:LTIMPUESTO,'')
SET @ltComision = ISNULL(:LTCOMISION,'')
SET @indiceComision = ISNULL(:indiceComision,0)

SET @ltMontoSubtotal = ISNULL(:LTMONTOSUBTOTAL,'')
SET @ltMontoDescuento = ISNULL(:LTMONTODESCUENTO,'')
SET @ltMontoTotal = ISNULL(:LTMONTOTOTAL,'')

SELECT TOP 1 @IDIMPUESTO= IDIMPUESTO FROM <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS WHERE IDEMPRESA= <#SESSION.IDEMPRESA/>
SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD, 0)
SET @LTIDPRODUCTO = ISNULL(:LTIDPRODUCTO, '')
SET @LTDESCRIPCION = salesup_ct.dbo.PreparaCadena(ISNULL(:LTDESCRIPCION, ''))
SET @LTCANTIDAD = ISNULL(:LTCANTIDAD,'') 
SET @LTPRECIO = ISNULL(:LTPRECIO, '')
SET @LTNOMBREPRECIO = ISNULL(:LTNOMBREPRECIO, '')
SET @DESCUENTO = ISNULL(:DESCUENTO, '0')
SET @DESCUENTO_PCT = ISNULL(:DESCUENTO_PCT, '')
SET @PLANTILLA_SELECCIONADA = ISNULL(:DOCUMENTOCOTIZACION, 0)
SET @TOTAL =ISNULL(:TOTAL,'')
SET @MONTO =ISNULL(:MONTO,'')
SET @SUBTOTAL = ISNULL(:SUBTOTAL, 0)
SET @DECOTIZACION=ISNULL(:DECOTIZACION,0)
SET @JSON_SUBTOTALES=salesup_ct.dbo.PreparaCadena(ISNULL(:JSON_SUBTOTALES, ''))
SET @TIPOCAMBIO=ISNULL(:TIPOCAMBIO,0)
SET @IDEMPRESAMONEDA=ISNULL(:IDEMPRESAMONEDA, 0)
SET @IMPUESTOS = ISNULL(:IMPUESTOSMONTO, 0)
SET @TIENEPRODUCTOS = ISNULL(:TPRODUCTOS, 0) 
SET @LTDESCUENTOS =ISNULL(:LTDESCUENTOS, '')
SET @LTDESCUENTOS_PORC = ISNULL(:LTDESCUENTOS_PORC, '')
SET @LTCOMENTARIOS = salesup_ct.dbo.PreparaCadena(ISNULL(:LTCOMENTARIOS, ''))

IF(@TIPOCAMBIO = 0) SET @TIPOCAMBIO = 1
IF(@IDEMPRESAMONEDA = 0)BEGIN
	SELECT @IDEMPRESAMONEDA = IDEMPRESAMONEDA FROM <#SESSION.DB/>.dbo.MONEDAS 
	WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND PORDEFECTO = 1
END

DELETE  <#SESSION.DB/>.dbo.OPORTUNIDADES_PRODUCTOS WHERE IDOPORTUNIDAD= @IDOPORTUNIDAD


INSERT INTO <#SESSION.DB/>.dbo.OPORTUNIDADES_PRODUCTOS
        ( IDOPORTUNIDAD ,
          IDPRODUCTO ,
          DESCRIPCION ,
          CANTIDAD ,
          PRECIO,
		  INDICEPRECIOLISTA,
		  COMISION1,
		  COMISION2,
		  COMISION3,
		  COMISION4,
		  COMISION5,
		  COMISION6,
		  COMISION7,
		  COMISION8,
		  COMISION9,
		  COMISION10,
  		  IDEMPRESAMONEDA,
		  TIPOCAMBIO,
		  SUBTOTAL,
		  DESCUENTO, 
		  TOTAL,
		  FECHAINICIO,
		  FECHAFIN,
		  FECHADIF,
		  CANTIDAD_DESC,
		  PORCENTAJE_DESC,
		  COMENTARIO
          ) 
SELECT  @IDOPORTUNIDAD , 
          RTRIM(LTRIM(LTP.SPLITVALUE)),
          RTRIM(LTRIM(LTD.SPLITVALUE)), 
		  RTRIM(LTRIM(LTC.SPLITVALUE)), 
          RTRIM(LTRIM(LTPRE.SPLITVALUE)),
		  RTRIM(LTRIM(LTNOM.SPLITVALUE)),
		  CASE WHEN @indiceComision = 1 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT)  ELSE 0 END,
		  CASE WHEN @indiceComision = 2 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 3 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 4 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 5 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 6 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 7 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 8 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 9 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  CASE WHEN @indiceComision = 10 THEN CAST(RTRIM(LTRIM(LTCOM.SPLITVALUE)) AS FLOAT) ELSE 0 END,
		  @IDEMPRESAMONEDA,
		  @TIPOCAMBIO, 
		  RTRIM(LTRIM(LTSUB.SPLITVALUE)), 
          RTRIM(LTRIM(LTDESC.SPLITVALUE)),
		  RTRIM(LTRIM(LTTOTAL.SPLITVALUE)),
		  CONVERT(DATETIME,RTRIM(LTRIM(LTFI.SPLITVALUE)),@CONVERTCODE), 
          CONVERT(DATETIME,RTRIM(LTRIM(LTFN.SPLITVALUE)),@CONVERTCODE),
		  RTRIM(LTRIM(LTNO.SPLITVALUE)),
		  RTRIM(LTRIM(LTDESC_PRODUCTOS.SPLITVALUE)),
		  RTRIM(LTRIM(LTDESC_PORC.SPLITVALUE)),
		  RTRIM(LTRIM(LTCOMEN.SPLITVALUE))
          FROM SALESUP_CT.DBO.SPLIT(@LTIDPRODUCTO,',') LTP
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTDESCRIPCION,',') LTD ON LTP.OCCURENCEID = LTD.OCCURENCEID
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTCANTIDAD,',') LTC ON LTP.OCCURENCEID = LTC.OCCURENCEID
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTPRECIO,',') LTPRE ON LTP.OCCURENCEID = LTPRE.OCCURENCEID
  		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTNOMBREPRECIO,',') LTNOM ON LTP.OCCURENCEID = LTNOM.OCCURENCEID
   		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@ltComision,',') LTCOM ON LTP.OCCURENCEID = LTCOM.OCCURENCEID
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@ltMontoSubtotal,',') LTSUB ON LTP.OCCURENCEID = LTSUB.OCCURENCEID
  		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@ltMontoDescuento,',') LTDESC ON LTP.OCCURENCEID = LTDESC.OCCURENCEID
   		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@ltMontoTotal,',') LTTOTAL ON LTP.OCCURENCEID = LTTOTAL.OCCURENCEID
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTFECHA_INI,',') LTFI ON LTP.OCCURENCEID = LTFI.OCCURENCEID
  		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTFECHA_FIN,',') LTFN ON LTP.OCCURENCEID = LTFN.OCCURENCEID
   		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTNOCHES,',') LTNO ON LTP.OCCURENCEID = LTNO.OCCURENCEID
		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTDESCUENTOS,',') LTDESC_PRODUCTOS ON LTP.OCCURENCEID = LTDESC_PRODUCTOS.OCCURENCEID
  		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTDESCUENTOS_PORC,',') LTDESC_PORC ON LTP.OCCURENCEID = LTDESC_PORC.OCCURENCEID
   		  LEFT JOIN SALESUP_CT.DBO.SPLIT(@LTCOMENTARIOS,'|') LTCOMEN ON LTP.OCCURENCEID = LTCOMEN.OCCURENCEID
		  		  		  
SET @LTIDPRODUCTO = ''
SELECT @LTIDPRODUCTO =@LTIDPRODUCTO+CAST(idoportunidades_productos AS varchar(100))+',' FROM  <#SESSION.DB/>.DBO.oportunidades_productos WHERE idoportunidad =@idoportunidad


 UPDATE OP SET OP.IMPUESTO1= IM.impuesto1, OP.IMPUESTO2=IM.impuesto2, OP.IMPUESTO3=IM.impuesto3, OP.IMPUESTO4=IM.impuesto4,
 OP.IMPUESTO5=IM.impuesto5, OP.IMPUESTO6=IM.impuesto6, OP.IMPUESTO7=IM.impuesto7, OP.IMPUESTO8=IM.impuesto8, OP.IMPUESTO9=IM.impuesto9, OP.IMPUESTO10=IM.impuesto10
FROM  <#SESSION.DB/>.DBO.oportunidades_productos OP,  <#SESSION.DB/>.DBO.ObtieneTablaOportunidadesProductosImp(@IDOPORTUNIDAD,@LTIDPRODUCTO,@IndImp,@IndCantidad) IM 
WHERE IM.idp = OP.idoportunidades_productos

		  
		  

IF(@DECOTIZACION = 1)
BEGIN
UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES 
	   	  SET SUBTOTAL= CAST(@SUBTOTAL AS MONEY),
	   	   DESCUENTO_PCT= CAST(@DESCUENTO_PCT AS FLOAT),
		   DESCUENTO= CAST(@DESCUENTO AS MONEY),
		   IDDOCUMENTO = CAST(@PLANTILLA_SELECCIONADA AS INT),
		   TIENEPRODUCTOS = CAST(@TIENEPRODUCTOS AS INT),
   		   MONTO = CAST(@MONTO AS MONEY),
		   JSON_SUBTOTALES = CAST(@JSON_SUBTOTALES AS NVARCHAR(MAX)), 
		   TIPOCAMBIO=@TIPOCAMBIO,
		   IDEMPRESAMONEDA=@IDEMPRESAMONEDA, 
		   IMPUESTOS = @IMPUESTOS
		      WHERE IDOPORTUNIDAD= @IDOPORTUNIDAD
END
ELSE IF(@DECOTIZACION = 2)
BEGIN
UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES 
	   	  SET SUBTOTAL= CAST(@SUBTOTAL AS MONEY),
	   	   DESCUENTO_PCT= CAST(@DESCUENTO_PCT AS FLOAT),
		   DESCUENTO= CAST(@DESCUENTO AS MONEY),
   		   MONTO = CAST(@TOTAL AS MONEY),
		   JSON_SUBTOTALES = CAST(@JSON_SUBTOTALES AS NVARCHAR(MAX)),
		   TIPOCAMBIO=@TIPOCAMBIO,
		   IDEMPRESAMONEDA=@IDEMPRESAMONEDA,
		   IMPUESTOS = @IMPUESTOS,
		   TIENEPRODUCTOS = CAST(@TIENEPRODUCTOS AS INT)
		   WHERE IDOPORTUNIDAD= @IDOPORTUNIDAD
END
