//[idc|Integer,v|Text,idp|Integer,session.convertcode|Untyped,session.idempresa|Untyped,session.db|Untyped,]
-- SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @IDPROSPECTO INT, @INDICE INT, @CONVERTCODE INT
DECLARE @VALOR VARCHAR(MAX) 

SET @INDICE = ISNULL(:IDC,0)
SET @VALOR = ISNULL(:V,'')
SET @IDPROSPECTO = ISNULL(:IDP,0)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT )
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @IDSOPORTUNIDADES VARCHAR(MAX)

      SET  @IDSOPORTUNIDADES = <#SESSION.DB/>.dbo.ValidaCamposSugeridosOportunidades(@INDICE, @VALOR, @IDPROSPECTO, @IDEMPRESA, @CONVERTCODE )

SELECT O.IDOPORTUNIDAD AS IdO , O.Perdida, CAST(ISNULL(P.NOMBRE, '') AS VARCHAR(256))+ ' ' + CAST(ISNULL(P.APELLIDOS, '') AS VARCHAR(256)) AS Nombre,
U.IdUsuario , U.NOMBRE + ' ' + U.APELLIDOS +' ('+ U.INICIALES+ ')' as Usuario
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O, <#SESSION.DB/>.dbo.USUARIOS U, <#SESSION.DB/>.dbo.PROSPECTOS P
WHERE O.IDOPORTUNIDAD in( select Splitvalue from  <#SESSION.DB/>.dbo.split(@IDSOPORTUNIDADES, ',')) AND U.IDUSUARIO = P.IDUSUARIO AND O.IDPROSPECTO=P.IDPROSPECTO

