//[monto|Text,session.db|Untyped,idoportunidad|Untyped,idempresamoneda|Text,tipocambio|Text,o|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,pesokb|Untyped,idfase|Untyped,comision|Untyped,concepto|Text,horarecordatorio|Text,00|Text,fecharecordatorio|Untyped,certeza|Untyped,seguimiento|Text,recordatorio|Text,cotizacion|Untyped,session.idusuario|Untyped,session.nombre|Untyped,session.apellidos|Untyped,session.iniciales|Untyped,cierreestimado|Untyped,comision_monto|Untyped,idlinea|Untyped,amazon|Untyped,campo1o|Untyped,campo2o|Untyped,campo3o|Untyped,campo4o|Untyped,campo5o|Untyped,campo6o|Untyped,campo7o|Untyped,campo8o|Untyped,campo9o|Untyped,campo10o|Untyped,campo11o|Untyped,campo12o|Untyped,campo13o|Untyped,campo14o|Untyped,campo15o|Untyped,campo16o|Untyped,campo17o|Untyped,campo18o|Untyped,campo19o|Untyped,campo20o|Untyped,campo21o|Untyped,campo22o|Untyped,campo23o|Untyped,campo24o|Untyped,campo25o|Untyped,campo26o|Untyped,campo27o|Untyped,campo28o|Untyped,campo29o|Untyped,campo30o|Untyped,campo31o|Untyped,campo32o|Untyped,campo35o|Untyped,campo36o|Untyped,campo37o|Untyped,campo38o|Untyped,campo39o|Untyped,campo40o|Untyped,campo41o|Untyped,campo42o|Untyped,campo43o|Untyped,campo44o|Untyped,campo45o|Untyped,campo46o|Untyped,campo47o|Untyped,campo48o|Untyped,campo49o|Untyped,campo50o|Untyped,campo51o|Untyped,campo52o|Untyped,campo53o|Untyped,campo54o|Untyped,campo55o|Untyped,campo56o|Untyped,campo57o|Untyped,campo58o|Untyped,campo59o|Untyped,campo60o|Untyped,campo61o|Untyped,campo62o|Untyped,campo63o|Untyped,campo64o|Untyped,idprospecto|Untyped,]
	--insert

DECLARE @CERTEZA FLOAT
DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @IDSEGUIMIENTO INT
DECLARE @IDOPORTUNIDAD INT, @CONVERTCODE INT
DECLARE @FECHA_CIERRE DATETIME
DECLARE @FECHA_RECORDATORIO DATETIME
DECLARE @ARCHIVO VARCHAR(2048)
DECLARE @SEGUIMIENTO VARCHAR(MAX)
DECLARE @RECORDATORIO VARCHAR(1024)
DECLARE @FASEANT INT
DECLARE @FASENEW INT
DECLARE @COMISION float
DECLARE @CONCEPTO VARCHAR(MAX)
DECLARE @HORAREC VARCHAR(8000), @DESCRIPCIONCERTEZA VARCHAR(MAX)
DECLARE @FECHA_REC varchar(8000)
DECLARE @PESOKB FLOAT
DECLARE @IDEMPRESAMONEDA INT
DECLARE @TIPOCAMBIO FLOAT
DECLARE @MONTO FLOAT
DECLARE @CERTEZA_IN FLOAT

DECLARE @IDMONEDA VARCHAR(MAX) = ISNULL(:IDEMPRESAMONEDA,'')
DECLARE @IDEMPRESAMONEDA_ACTUAL INT
DECLARE @TIPOCAMBIO_ACTUAL FLOAT

DECLARE @P VARCHAR(MAX)

SET @IDMONEDA = ISNULL(:IDEMPRESAMONEDA,'0')
SET @MONTO = ISNULL(:MONTO, 0)
SET @CERTEZA_IN = (cast (ISNULL(<#CERTEZA/>,0) as FLOAT)*100)

SELECT @IDEMPRESAMONEDA_ACTUAL= ISNULL(IDEMPRESAMONEDA,IDEMPRESAMONEDADEFAULT), @TIPOCAMBIO_ACTUAL= TIPOCAMBIO FROM  <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD=<#IDOPORTUNIDAD/>

SELECT @TIPOCAMBIO_ACTUAL=TIPODECAMBIO FROM  <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESAMONEDA=@IDEMPRESAMONEDA_ACTUAL

IF ISNUMERIC(@IDMONEDA) = 0 BEGIN SET @IDEMPRESAMONEDA = @IDEMPRESAMONEDA_ACTUAL END
ELSE BEGIN SET @IDEMPRESAMONEDA = @IDMONEDA END

SET @TIPOCAMBIO = ISNULL(:TIPOCAMBIO,@TIPOCAMBIO_ACTUAL);

DECLARE @O_CatalogoOpcion1 INT, @O_CatalogoOpcion2 INT, @O_CatalogoOpcion3 INT

SET @O_CatalogoOpcion1 = CAST('<#O-CatalogoOpcion1/>' AS INT)  
SET @O_CatalogoOpcion2 = CAST('<#O-CatalogoOpcion2/>' AS INT) 
SET @O_CatalogoOpcion3 = CAST('<#O-CatalogoOpcion3/>' AS INT)

IF @O_CatalogoOpcion1 = 0 BEGIN SET @O_CatalogoOpcion1 = NULL END
IF @O_CatalogoOpcion2 = 0 BEGIN SET @O_CatalogoOpcion2 = NULL END
IF @O_CatalogoOpcion3 = 0 BEGIN SET @O_CatalogoOpcion3 = NULL END

SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDOPORTUNIDAD = CAST('<#IDOPORTUNIDAD/>' AS INT)


SET @PESOKB=CAST('<#pesokb/>' AS FLOAT)

SET @FASENEW=CAST('<#IDFASE/>' AS INT)
SET @COMISION=0
IF '<#COMISION/>' != 'Infinity' 
  SET @COMISION=CAST('<#COMISION/>' AS float)
  
SET @CONCEPTO=ISNULL(:CONCEPTO, '') 
SET @HORAREC=:HORARECORDATORIO
IF LEN(@HORAREC)<2 SET @HORAREC = @HORAREC + ':00'
SET @FECHA_REC='<#FECHARECORDATORIO/> '+@HORAREC
SET @FECHA_RECORDATORIO=CONVERT(DATETIME, @FECHA_REC,<#SESSION.CONVERTCODE/>)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SET @DESCRIPCIONCERTEZA = ''
SELECT @DESCRIPCIONCERTEZA = CASE WHEN ISNULL(DESCRIPCION,'') <> '' THEN ' - '+ 

LTRIM(RTRIM(ISNULL(DESCRIPCION,''))) ELSE '' END
FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA = @IDEMPRESA AND CERTEZA = @CERTEZA_IN

SET @SEGUIMIENTO  =:SEGUIMIENTO
SET @RECORDATORIO = :RECORDATORIO

set @archivo=''
  SELECT @IDPROSPECTO=IDPROSPECTO, @FECHA_CIERRE=CONVERT(DATETIME,FECHA_CIERRE,<#SESSION.CONVERTCODE/>), @CERTEZA=CERTEZA, @ARCHIVO=ARCHIVO 
  FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK)
  WHERE IDOPORTUNIDAD = <#IDOPORTUNIDAD/>

  IF LTRIM('<#COTIZACION/>')>''
    SET @ARCHIVO = LTRIM('<#COTIZACION/>')
	
-- se activan las acciones de las fases
  	SELECT @FASEANT=IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK) WHERE IDOPORTUNIDAD = <#IDOPORTUNIDAD/>
    IF @FASEANT!=@FASENEW
	 begin
	   DECLARE @FASETXT VARCHAR(1000)
       SELECT @FASETXT=' - '+ISNULL(FASE,'') FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE 

IDFASE=@FASENEW AND IDEMPRESA=<#SESSION.IDEMPRESA/>
	   EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @FASENEW,@IDPROSPECTO,<#IDOPORTUNIDAD/>
	   EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES <#SESSION.IDUSUARIO/>,21,@IDPROSPECTO,<#IDOPORTUNIDAD/>,<#SESSION.CONVERTCODE/>, @FASETXT,''
	 end  	


/*ACTUALIZA TAMAÑO DEL ARCHIVO*/
DECLARE @ESAMAZON INT
DECLARE @ARCHIVOOLD VARCHAR(5000)

IF (LTRIM(RTRIM('<#cotizacion/>'))!='')
 BEGIN
  SELECT @ESAMAZON=AMAZON, @ARCHIVOOLD=LTRIM(RTRIM(ARCHIVO)) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE 

IDOPORTUNIDAD=<#IDOPORTUNIDAD/>
  INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_ARCHIVOS_AMAZON (IDEMPRESA,IDUSUARIO,ARCHIVO,PESO,TIPO) VALUES (<#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,'<#cotizacion/>',<#pesokb/>,'PO')
  INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS (IDPROSPECTO,IDOPORTUNIDAD,IDUSUARIO,ARCHIVO,DESCRIPCION,AMAZON,PESO) VALUES (@IDPROSPECTO,<#IDOPORTUNIDAD/>,<#SESSION.IDUSUARIO/>,'<#cotizacion/>',@CONCEPTO,1,@PESOKB)
 END

/*FIN ACTUALIZA TAMAÑO DEL ARCHIVO*/  


DECLARE @CAMBIOLOCAL INT, @OportunidadCanalizada INT, @ProspectoCanalizado INT
DECLARE @NOMBRE_QUIEN_CANALIZA VARCHAR(MAX), @ESCANALIZADO VARCHAR(2)
DECLARE @FECHACANALIZADO DATETIME

SET @OportunidadCanalizada = 0
SET @ProspectoCanalizado = 0

SELECT @ESCANALIZADO = SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) FROM <#SESSION.DB/>.dbo.PROSPECTOS P 

WHERE P.IDPROSPECTO = @IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
IF @ESCANALIZADO = '1' OR @ESCANALIZADO = '2' BEGIN SET @ProspectoCanalizado = 1 END

SELECT @ESCANALIZADO = SALESUP_CT.dbo.esCanalizado(O.TKO, O.TKOM) FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O 

WHERE O.IDPROSPECTO = @IDPROSPECTO AND O.IDOPORTUNIDAD = @IDOPORTUNIDAD
IF @ESCANALIZADO = '1' OR @ESCANALIZADO = '2' BEGIN SET @OportunidadCanalizada = 1 END

IF @ProspectoCanalizado = 1 AND @OportunidadCanalizada = 1 
   BEGIN SET @NOMBRE_QUIEN_CANALIZA = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.INICIALES/>)' SET @FECHACANALIZADO = GETDATE() SET @CAMBIOLOCAL = 2   END

DECLARE @SUBTOTAL FLOAT
DECLARE @TIENE_PRODUCTOS INT

SELECT @TIENE_PRODUCTOS = TIENEPRODUCTOS FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD = 

<#IDOPORTUNIDAD/>
IF(@TIENE_PRODUCTOS = 0)
 BEGIN 
  SET @SUBTOTAL  = @MONTO
 END 
 ELSE
 BEGIN
    SELECT @SUBTOTAL = SUBTOTAL FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD = 

<#IDOPORTUNIDAD/>
	SELECT @MONTO = MONTO FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD = <#IDOPORTUNIDAD/>
 END


UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET
 CONCEPTO = @CONCEPTO,
 MONTO = @MONTO, 
 SUBTOTAL = @SUBTOTAL, 
 CERTEZA = <#CERTEZA/>, 
 FECHA_CIERRE = CONVERT(DATETIME,'<#CIERREESTIMADO/>',<#SESSION.CONVERTCODE/>), 
 IDFASE   = <#IDFASE/>,  
 COMISION = @COMISION/100.00,  
 COMISION_MONTO = <#COMISION_MONTO/>,
 ARCHIVO = NULL,
 IDLINEA_PRODUCTO = <#IDLINEA/>,
 AMAZON= <#AMAZON/>,
 IDCATALOGOOPCION1 = @O_CatalogoOpcion1,
 IDCATALOGOOPCION2 = @O_CatalogoOpcion2,
 IDCATALOGOOPCION3 = @O_CatalogoOpcion3,
 CAMBIOLOCAL = @CAMBIOLOCAL, 
 IDEMPRESAMONEDA = @IDEMPRESAMONEDA, 
 TIPOCAMBIO=@TIPOCAMBIO
WHERE
  IDOPORTUNIDAD = <#IDOPORTUNIDAD/>

 

-- Actualiza el prospecto y la oportunidad
/*
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET 
  FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,GetDate(),<#SESSION.CONVERTCODE/>)
WHERE
  IDPROSPECTO = @IDPROSPECTO
*/

UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET 
  FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,GetDate(),<#SESSION.CONVERTCODE/>)
WHERE
  IDOPORTUNIDAD = <#IDOPORTUNIDAD/>


  /*SE ACTUALIZAR LOS PERSONALIZABLES*/
  	 EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_CAMPOS_PERSONALIZABLES 2, @IDOPORTUNIDAD, @IDEMPRESA, 

@CONVERTCODE,
  	 '<#CAMPO1O/>' , '<#CAMPO2O/>' , '<#CAMPO3O/>' , '<#CAMPO4O/>', 
  	 '<#CAMPO5O/>' , '<#CAMPO6O/>' , '<#CAMPO7O/>' , '<#CAMPO8O/>', 
  	 '<#CAMPO9O/>' , '<#CAMPO10O/>', '<#CAMPO11O/>', '<#CAMPO12O/>', 
  	 '<#CAMPO13O/>', '<#CAMPO14O/>', '<#CAMPO15O/>', '<#CAMPO16O/>', 
  	 '<#CAMPO17O/>', '<#CAMPO18O/>', '<#CAMPO19O/>', '<#CAMPO20O/>', 
  	 '<#CAMPO21O/>', '<#CAMPO22O/>', '<#CAMPO23O/>', '<#CAMPO24O/>', '<#CAMPO25O/>', 
  	 '<#CAMPO26O/>', '<#CAMPO27O/>', '<#CAMPO28O/>', '<#CAMPO29O/>', 
  	 '<#CAMPO30O/>', '<#CAMPO31O/>', '<#CAMPO32O/>',
	 '<#CAMPO35O/>', '<#CAMPO36O/>',
	 '<#CAMPO37O/>', '<#CAMPO38O/>', '<#CAMPO39O/>', '<#CAMPO40O/>',
	 '<#CAMPO41O/>', '<#CAMPO42O/>', '<#CAMPO43O/>', '<#CAMPO44O/>',
	 '<#CAMPO45O/>', '<#CAMPO46O/>', '<#CAMPO47O/>', '<#CAMPO48O/>',
	 '<#CAMPO49O/>', '<#CAMPO50O/>', '<#CAMPO51O/>', '<#CAMPO52O/>',
	 '<#CAMPO53O/>', '<#CAMPO54O/>', '<#CAMPO55O/>', '<#CAMPO56O/>',
	 '<#CAMPO57O/>', '<#CAMPO58O/>', '<#CAMPO59O/>', '<#CAMPO60O/>',
	 '<#CAMPO61O/>', '<#CAMPO62O/>', '<#CAMPO63O/>', '<#CAMPO64O/>'
  
IF @CERTEZA <> <#CERTEZA/>
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO, SISTEMA)
  VALUES  (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, <#IDOPORTUNIDAD/>, 'La certeza ha cambiado al '+CAST (@CERTEZA_IN as varchar(MAX)) + '%' + @DESCRIPCIONCERTEZA ,1) 

  
IF @FECHA_CIERRE<> CONVERT(DATETIME,'<#CIERREESTIMADO/>',<#SESSION.CONVERTCODE/>)  
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, 

IDOPORTUNIDAD, COMENTARIO, SISTEMA)
  VALUES 
    (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, <#IDOPORTUNIDAD/>, 'La fecha de cierre se estima ahora para el <#CIERREESTIMADO/>',1)

IF (@SEGUIMIENTO<>'')
begin
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK)  (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
  VALUES   (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, <#IDOPORTUNIDAD/>, @SEGUIMIENTO)
  
  SELECT TOP 1 @IDSEGUIMIENTO= IDSEGUIMIENTO from <#SESSION.DB/>.DBO.prospectos_seguimiento WITH(NOLOCK) 

where IDOPORTUNIDAD = <#IDOPORTUNIDAD/>  ORDER BY IDSEGUIMIENTO DESC
  
  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES 

<#SESSION.IDUSUARIO/>,10,<#IDPROSPECTO/>,<#IDOPORTUNIDAD/>,<#SESSION.CONVERTCODE/>, '',@IDSEGUIMIENTO
end  

  IF (@RECORDATORIO<>'') AND (@RECORDATORIO<>'-') AND (NOT LTRIM('<#FECHARECORDATORIO/>') IS NULL) 
  BEGIN
     INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK)
     (IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO, IDOPORTUNIDAD)
     VALUES 
     (@IDPROSPECTO, <#SESSION.IDUSUARIO/>,@FECHA_RECORDATORIO, @RECORDATORIO, <#IDOPORTUNIDAD/> )
	 
     EXEC <#SESSION.DB/>.DBO.SP_PROXIMORECORDATORIO_OPORTUNIDAD <#IDOPORTUNIDAD/>    
  END
 SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
 DECLARE @HOY DATETIME
 SET @HOY = GETDATE()
 EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO <#SESSION.IDUSUARIO/>, @HOY
 EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@HOY,1
 
 
