//[session.gmt|Untyped|1,session.db|Untyped|SALESUP_DB1,idoportunidad|Integer|,tko|Text|,session.idempresa|Untyped|11811]
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT

DECLARE @GMT INT
SET @GMT = CAST('<#SESSION.GMT/>' AS INT )


SET @IDOPORTUNIDAD = :IDOPORTUNIDAD

DECLARE @TKO VARCHAR(64)
SET @TKO = ISNULL(:TKO,'')
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.DBO.ObtieneIdOportunidad(@tko)  END

SELECT @IDPROSPECTO = IDPROSPECTO
FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK)
WHERE 
  O.IDOPORTUNIDAD = @IDOPORTUNIDAD

 
SELECT
 SALESUP_CT.dbo.esCanalizado(S.TK, S.TKM) AS esCanalizado, 
 (CASE WHEN UE.ESTADO=0 AND UE.ERRORES>=3 THEN 1 ELSE 0 END) AS ESTADOEMAIL,
 (CASE WHEN UE.FECHALEIDO IS NOT NULL THEN 1 ELSE 0 END ) AS EMAILEIDO, UE.FECHALEIDO,
 (CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,

 (CASE WHEN USMS.ESTADO=0 AND USMS.ERRORES>0 THEN 1 ELSE 0 END) AS ESTADOSMS,
 (CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,
 O.IDPROSPECTO, 
 SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,S.FECHAHORA) AS FECHAHORA, 
 CAST (S.COMENTARIO AS VARCHAR(8000)) AS COMENTARIO, S.IDEMAIL, S.TIPO_SEGUIMIENTO, S.SISTEMA, S.IDRELACIONADO,
 CASE WHEN S.SEGUIMIENTODE IS NULL THEN ISNULL(U.INICIALES, '--') ELSE S.SEGUIMIENTODE END AS INICIALES, 
 CASE WHEN S.SEGUIMIENTODE IS NULL THEN U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') ELSE '' END AS EJECUTIVO_NOMBRE, 
 S.LATITUD,S.LONGITUD,S.IDSEGUIMIENTO ,
  CASE S.TIPO_SEGUIMIENTO 
 WHEN 7 THEN T.TKTR 
 ELSE ''
 END AS TK, P.TKP, O.TKO,
 S.DURACION
FROM 
  <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK), 
  <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON  UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON  USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON S.IDUSUARIO = U.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7, 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
  
WHERE 
  O.IDOPORTUNIDAD = @IDOPORTUNIDAD AND O.IDPROSPECTO = P.IDPROSPECTO AND S.IDOPORTUNIDAD=@IDOPORTUNIDAD AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND
  O.IDPROSPECTO = S.IDPROSPECTO 

UNION ALL

SELECT
SALESUP_CT.dbo.esCanalizado(S.TK, S.TKM) AS esCanalizado, 
(CASE WHEN UE.ESTADO=0 AND UE.ERRORES>=3 THEN 1 ELSE 0 END) AS ESTADOEMAIL,
(CASE WHEN UE.FECHALEIDO IS NOT NULL THEN 1 ELSE 0 END ) AS EMAILEIDO, UE.FECHALEIDO,
 (CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,

(CASE WHEN USMS.ESTADO=0 AND USMS.ERRORES>0 THEN 1 ELSE 0 END) AS ESTADOSMS,
 (CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,
 S.IDPROSPECTO, 
 DATEADD(hh, 6+ dbo.offset(getdate()), S.FECHAHORA) AS FECHAHORA, 
 CAST (S.COMENTARIO AS VARCHAR(8000)) AS COMENTARIO, S.IDEMAIL, S.TIPO_SEGUIMIENTO, S.SISTEMA, S.IDRELACIONADO,
 CASE WHEN S.SEGUIMIENTODE IS NULL THEN ISNULL(U.INICIALES, '--') ELSE S.SEGUIMIENTODE END AS INICIALES, 
CASE WHEN S.SEGUIMIENTODE IS NULL THEN U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') ELSE '' END AS EJECUTIVO_NOMBRE, 
 S.LATITUD,S.LONGITUD,S.IDSEGUIMIENTO,
  CASE S.TIPO_SEGUIMIENTO 
 WHEN 7 THEN T.TKTR 
 ELSE ''
 END AS TK, P.TKP, ''
,S.DURACION
FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON  UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON  USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON S.IDUSUARIO = U.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7, 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
  
WHERE 
  S.IDPROSPECTO=@IDPROSPECTO AND  S.IDPROSPECTO = P.IDPROSPECTO  AND (S.IDOPORTUNIDAD IS NULL) AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>

  ORDER BY FECHAHORA DESC 
