//[idprospecto|Integer,idoportunidad|Integer,idventa|Integer,tkp|Text,tko|Text,tkv|Text,session.db|Untyped,session.idempresa|Untyped,]
--select
DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDVENTA INT
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)
SET @IDOPORTUNIDAD=CAST(ISNULL(:idoportunidad,0) AS INT)
SET @IDVENTA=CAST(ISNULL(:IDVENTA,0) AS INT)

DECLARE @TKP VARCHAR(64), @TKO VARCHAR(64), @TKV VARCHAR(64)

SET @TKP = ISNULL(:TKP, '')
SET @TKO = ISNULL(:TKO, '')
SET @TKV = ISNULL(:TKV, '')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP,<#SESSION.IDEMPRESA/> ) END
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END
IF @TKV != '' BEGIN SELECT @IDVENTA = IDVENTA FROM <#SESSION.DB/>.dbo.VENTAS WHERE TKV = @TKV END
IF @IDOPORTUNIDAD > 0 BEGIN SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD END
   		

IF @IDOPORTUNIDAD!=0 
  BEGIN
   IF (@IDVENTA!=0)
      SELECT count(*) as totalfiles, @IDPROSPECTO AS IDPROSPECTOd, @IDOPORTUNIDAD AS idoportunidadd, @IDVENTA AS IDVENTA
      FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS PAR 
		   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = PAR.IDUSUARIO
      WHERE PAR.IDPROSPECTO=@IDPROSPECTO AND PAR.IDOPORTUNIDAD=@IDOPORTUNIDAD  
	  
   ELSE
     SELECT count(*) as totalfiles, @IDPROSPECTO AS IDPROSPECTOd, @IDOPORTUNIDAD AS idoportunidadd, @IDVENTA AS IDVENTA
      FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS PAR 
   		   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = PAR.IDUSUARIO
      WHERE PAR.IDPROSPECTO=@IDPROSPECTO AND ((PAR.IDOPORTUNIDAD=@IDOPORTUNIDAD)
      OR (PAR.IDOPORTUNIDAD IS NULL))	  
  END   
ELSE 
  SELECT count(*) as totalfiles, @IDPROSPECTO AS IDPROSPECTOd, @IDOPORTUNIDAD AS idoportunidadd, @IDVENTA AS IDVENTA
  FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS PAR 
	   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = PAR.IDUSUARIO
  WHERE PAR.IDPROSPECTO=@IDPROSPECTO AND PAR.IDOPORTUNIDAD IS NULL
