//[tkcom|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Integer,session.db|Untyped,f_usuario|Text,crit|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')
SET @CRIT=ISNULL(:CRIT,'')

SET @SQL ='
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT,@IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
SET @TkCom = dbo.ValidaToken('''+ISNULL(:TKCOM,'')+''')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @NIVELUSUARIO = <#SESSION.NIVEL/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @MAILCONFIG = <#SESSION.MAILCONFIG/>
SET @DESCARTADO = '+CAST(ISNULL(:DESCARTADO,'') AS VARCHAR(1000))+'
SET @IDCOMPANIA = 0
IF @TkCom != ''''
BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END

SELECT  
  1 AS R, O.TKO AS Tko,
   SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, O.IDOPORTUNIDAD, O.NARCHIVOS )  AS VerArchivos,
  CASE @DESCARTADO WHEN 0 THEN ''1'' ELSE '''' END AS Descartado,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO OR PA.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tEtiquetar_tSeguimiento,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tCompartir_tReasignar,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO OR PA.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tOportunidad,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tDescartar_tVentas,
  
  
  P.IdProspecto, O.IdOportunidad,
  LTRIM(RTRIM(P.NOMBRE))+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS NombreCliente, ISNULL(P.Empresa,'''') AS Empresa , P.ETIQUETAS_TXT AS Etiquetas,
  CASE WHEN <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) = ''NO'' THEN ''1'' ELSE '''' END as EsCorreo, ISNULL(P.Correo,'''') As Correo , ISNULL(P.Telefono,'''') as Telefono , ISNULL(P.Telefono2,'''') AS Telefono2 , ISNULL(P.Movil,'''') as Movil,  
   O.Concepto as Concepto, LP.LINEA_PRODUCTO as LineaProducto,
  ISNULL(F.Fase,'''') AS Fase, ISNULL(ORI.Origen,'''') AS Origen,
  ISNULL(Monto,'''') AS Monto, ISNULL(COMISION_MONTO,0) as Comision, O.Certeza, EC.DESCRIPCION AS TxtCerteza, 
  CASE WHEN O.FECHA_CIERRE < <#SESSION.DB/>.DBO.GETONLYDATE(GETDATE()) THEN ''1'' ELSE '''' END AS Vencida, CONVERT(VARCHAR(10),O.FECHA_CIERRE,103) as CierreEstimado,
   isnull(CAST(S.COMENTARIO AS VARCHAR(MAX)),'''')  AS UltimoContacto,
  (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS UltimoContactoTiempo,
  U.Iniciales , U.NOMBRE+'' ''+U.APELLIDOS AS EjecutivoNombre,
  CASE WHEN ( SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WITH(NOLOCK) WHERE PA.IDPROSPECTO = O.IDPROSPECTO ) > 1 THEN ''1'' ELSE '''' END AS Compartido,
  CASE @MAILCONFIG WHEN 0 THEN ''1'' ELSE '''' END AS NoConfigurado,
  CASE @MAILCONFIG WHEN 1 THEN ''1'' ELSE '''' END AS EmailConfigurado,
  CASE @MAILCONFIG WHEN 2 THEN ''1'' ELSE '''' END AS MailTo, S.FECHAHORA AS ULTIMO_CONTACTO_FECHA,
  
	 
  CASE WHEN P.CAMPO1 IS NOT NULL THEN P.CAMPO1 ELSE '''' END AS cp1,
  CASE WHEN P.CAMPO2 IS NOT NULL THEN P.CAMPO2 ELSE '''' END AS cp2,
  CASE WHEN P.CAMPO3 IS NOT NULL THEN P.CAMPO3 ELSE '''' END AS cp3,
  CASE WHEN P.CAMPO4 IS NOT NULL THEN P.CAMPO4 ELSE '''' END AS cp4,
  
  CASE WHEN P.CAMPO5 IS NOT NULL THEN P.CAMPO5 ELSE '''' END AS cp5,
  CASE WHEN P.CAMPO6 IS NOT NULL THEN P.CAMPO6 ELSE '''' END AS cp6,
  CASE WHEN P.CAMPO7 IS NOT NULL THEN P.CAMPO7 ELSE '''' END AS cp7,
  CASE WHEN P.CAMPO8 IS NOT NULL THEN P.CAMPO8 ELSE '''' END AS cp8,
  
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '''' END AS cp9,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '''' END AS cp10,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '''' END AS cp11,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '''' END AS cp12,
  
  ISNULL(P.CAMPO13,'''') AS cp13,
  ISNULL(P.CAMPO14,'''') AS cp14,
  ISNULL(P.CAMPO15,'''') AS cp15,
  ISNULL(P.CAMPO16,'''') AS cp16,
  ISNULL(P.CAMPO17,'''') AS cp17,
  ISNULL(P.CAMPO18,'''') AS cp18,
  ISNULL(P.CAMPO19,'''') AS cp19,
  ISNULL(P.CAMPO20,'''') AS cp20,

  CP21.OPCION AS cp21,
  CP22.OPCION AS cp22,
  CP23.OPCION AS cp23,
  CP24.OPCION AS cp24,
  CP25.OPCION AS cp25
  
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK) 
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) ON O.IDPROSPECTO = P.IDPROSPECTO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON @IDUSUARIO = PA.IDUSUARIO AND PA.IDPROSPECTO = O.IDPROSPECTO
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES ORI WITH(NOLOCK) ON ORI.IDORIGEN = P.IDORIGEN
  INNER JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F WITH(NOLOCK) ON O.IDFASE = F.IDFASE  
  INNER JOIN <#SESSION.DB/>.dbo.USUARIOS U WITH(NOLOCK) ON O.IDUSUARIO = U.IDUSUARIO 
  INNER JOIN <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK) ON O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON O.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO = U1.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CERTEZAS EC ON EC.IDEMPRESA = P.IDEMPRESA AND EC.CERTEZA = (O.CERTEZA*100)
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 ON CP25.IDOPCION = P.CAMPO25

WHERE 
  P.IDCOMPANIA=@IDCOMPANIA AND O.PERDIDA=0 
  AND O.GANADA = 0 
  AND P.DESCARTADO=0
  '+@F_USUARIO+' '+@CRIT+'
 ORDER BY O.FECHAHORA DESC 

'
EXEC (@SQL)