//[idoportunidad|Integer,session.idusuario|Untyped,session.db|Untyped,tko|Text,]
--UPDATE 
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SESSIONIDUSUARIO INT
DECLARE @IDOPORTUNIDAD INT
SET @IDOPORTUNIDAD=ISNULL(:IDOPORTUNIDAD,0)

DECLARE @TKO VARCHAR(64) 
SET @TKO = ISNULL(:TKO,'')
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END


SET @SESSIONIDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
EXEC <#SESSION.DB/>.dbo.SP_RESTABLECER_OPORTUNIDAD @IDOPORTUNIDAD, @SESSIONIDUSUARIO
