//[idpantalla|Integer,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--select
DECLARE @IDPANTALLA INT
SET @IDPANTALLA=CAST(ISNULL(:IDPANTALLA,0) AS INT)
SELECT *, @IDPANTALLA AS IDPANTALLA, CAST(G.TK AS VARCHAR(64)) AS TKGRUPO 
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,@IDPANTALLA,1) UL,<#SESSION.DB/>.DBO.USUARIOS_GRUPOS G
WHERE G.IDEMPRESA = <#SESSION.IDEMPRESA/> AND G.IDUSUARIOGRUPO=UL.ID
