//[session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,idoportunidad|Integer,tipocomision|Integer,session.convertcode|Untyped]
--SELECT
/*protegido*/
DECLARE @IDEMPRESA INT
DECLARE @IDOPORTUNIDAD AS INT
DECLARE @LINKAMAZON VARCHAR(MAX)
DECLARE @CARPETA VARCHAR(MAX)
DECLARE @DESCUENTO VARCHAR(MAX)
DECLARE @DESCUENTO_PCT VARCHAR(MAX)
DECLARE @json VARCHAR(max)
DECLARE @TipoComision INT
DECLARE @TIPOCAMBIO FLOAT
DECLARE @IDEMPRESAMONEDA INT
DECLARE @IDUSUARIO INT
DECLARE @CONVERTCODE INT = <#SESSION.CONVERTCODE/>

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @json =''
   
 
DECLARE @EXISTEN_IMPUESTO INT

SELECT @EXISTEN_IMPUESTO = COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS WHERE STATUS =1 AND IDEMPRESA =@IDEMPRESA and indice is not null 

IF(@EXISTEN_IMPUESTO = 0 )
 BEGIN
  SET @json ='{"nombre":"demo","indice":"0"},'
 END
ELSE
 BEGIN
 SELECT @json=@json +'{"nombre":"'+IMPUESTO+'","indice":'+CAST(INDICE AS VARCHAR(128))+'},' FROM <#SESSION.DB/>.dbo.EMPRESAS_IMPUESTOS WHERE STATUS =1 AND IDEMPRESA =@IDEMPRESA and indice is not null 
 END

SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD, 0)
SET @TipoComision = ISNULL(:TIPOCOMISION, 1) 
SET @CARPETA = <#SESSION.DB/>.DBO.PREPARANUMERO(@IDEMPRESA, 6)
SET @LINKAMAZON='https://s3-us-west-2.amazonaws.com/salesupfiles/'+@CARPETA+'/'
SELECT @DESCUENTO_PCT=DESCUENTO_PCT, @TIPOCAMBIO=TIPOCAMBIO, @IDEMPRESAMONEDA=IDEMPRESAMONEDA  FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD= @IDOPORTUNIDAD

SELECT @TipoComision = CASE WHEN COMISION IS NULL  OR COMISION=0 THEN 0 ELSE COMISION END  FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDUSUARIO=@IDUSUARIO

if(@TipoComision != 0)
begin
	 SELECT @TipoComision = indice from <#SESSION.DB/>.dbo.productos_comisiones where idproducto_comision = @TipoComision
end

SELECT OP.CANTIDAD,OP.PRECIO AS PRECIO_USUARIO,OP.INDICEPRECIOLISTA, @DESCUENTO_PCT AS DESCUENTO_PCT, P.idProducto, P.TK AS tkProducto, P.TKM AS tkmProducto, P.Codigo, P.Nombre as Producto, P.idlinea_producto as IdLinea,
P.PRECIO_MIN AS precioMin, P.Costo, P.Unidad, P.Existencia, P.Status,
P.Precio1, P.Precio2, P.Precio3, P.Precio4, P.Precio5, P.Precio6, P.Precio7, P.Precio8, P.Precio9, P.Precio10, P.IMAGENES, P.impuesto1, P.impuesto2, P.impuesto3, P.impuesto4,
P.impuesto5, P.impuesto6, P.impuesto7, P.impuesto8, P.impuesto9, P.impuesto10, @json as ImpEmpresa, 
Descripcion_Corta as desCorta, DESCRIPCION_EXTENDIDA1 AS Descripcion1, DESCRIPCION_EXTENDIDA2 AS Descripcion2, @LINKAMAZON as link,
@TIPOCAMBIO AS TIPOCAMBIO,@IDEMPRESAMONEDA AS IDEMPRESAMONEDA, 
CASE 
WHEN @TipoComision = 1 THEN P.COMISION1
WHEN @TipoComision = 2 THEN P.COMISION2
WHEN @TipoComision = 3 THEN P.COMISION3
WHEN @TipoComision = 4 THEN P.COMISION4
WHEN @TipoComision = 5 THEN P.COMISION5
WHEN @TipoComision = 6 THEN P.COMISION6
WHEN @TipoComision = 7 THEN P.COMISION7
WHEN @TipoComision = 8 THEN P.COMISION8
WHEN @TipoComision = 9 THEN P.COMISION9
WHEN @TipoComision = 10 THEN P.COMISION10
END AS Comision, 
CONVERT(VARCHAR(10),OP.FECHAINICIO,@CONVERTCODE) AS FECHA_INI,
CONVERT(VARCHAR(10),OP.FECHAFIN,@CONVERTCODE) AS FECHA_FIN, 
OP.FECHADIF AS NOCHES, ISNULL(COMENTARIO,'') AS COMENTARIO, ISNULL(CANTIDAD_DESC,0) AS CANTIDAD_DESC, ISNULL(PORCENTAJE_DESC,0) AS PORCENTAJE_DESC 
FROM  <#SESSION.DB/>.dbo.OPORTUNIDADES_PRODUCTOS OP 
LEFT JOIN  <#SESSION.DB/>.dbo.PRODUCTOS P ON OP.IDPRODUCTO=P.IDPRODUCTO
WHERE OP.IDOPORTUNIDAD=@IDOPORTUNIDAD