//[session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Text,tkcom|Text,session.db|Untyped,top_registros|Text,f_usuario|Text,crit|Text,]
--SELECT 
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT
DECLARE @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @SQL VARCHAR(MAX)
DECLARE @TOP VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @DESCARTADO = CAST(isnull(:DESCARTADO,'') AS INT)
SET @TkCom = dbo.ValidaToken(isnull(:TKCOM,'')) 
SET @IDCOMPANIA = 0
SET @TOP = ISNULL(:TOP_REGISTROS,'')
SET @F_USUARIO = ISNULL(:F_USUARIO,'')
SET @CRIT =  ISNULL(:CRIT,'')
DECLARE @COMENTARIO VARCHAR(MAX)
SET @COMENTARIO=''

IF @TkCom != ''
BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END

SET @SQL ='
SELECT
'+@TOP+'
  CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 THEN 1 ELSE 0 END AS A , 
  ISNULL(COM.IDCOMPANIA,-1) AS Id, COM.TkCom, ISNULL(COM.Empresa,''Sin empresa'') as Empresa, 
  CASE WHEN (ISNULL(EI.Industria,'''')='''') OR (EI.Industria = ''Ninguna'') THEN '''' ELSE EI.Industria END AS Industria ,
  CASE WHEN (ISNULL(CG.CompaniaGrupo,'''')='''') OR (CG.CompaniaGrupo = ''Ninguna'') THEN '''' ELSE CG.CompaniaGrupo END AS CompaniaGrupo,
  COM.Url, COM.TELEFONOCORPORATIVO AS Telefono, 
  COUNT( isnull(P.IDCOMPANIA,0)) AS nRegistros,
 CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 
  	   THEN 
	   		( 
			  SELECT PP.NOMBRE +'' ''+ISNULL(PP.APELLIDOS,'''') + '', <b>''+<#SESSION.DB/>.DBO.TIEMPO_TXT (PSS.FECHAHORA,GETDATE()) + ''</b> (''+UU.INICIALES+'') - <i>''+ CAST(PSS.COMENTARIO AS VARCHAR(MAX)) + ''</i>''
			  FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSS , <#SESSION.DB/>.dbo.USUARIOS UU , <#SESSION.DB/>.dbo.PROSPECTOS PP 
			  WHERE --PSS.IDUSUARIO = UU.IDUSUARIO AND PSS.IDSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO) AND PP.IDULTIMOSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO)
			        PSS.IDUSUARIO = UU.IDUSUARIO AND PSS.IDSEGUIMIENTO = MAX(S.IDSEGUIMIENTO) AND  PSS.IDPROSPECTO=PP.IDPROSPECTO 
			) 
	   ELSE
	   	   ''''
	   END AS Comentario



FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK) 
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) ON O.IDPROSPECTO = P.IDPROSPECTO 
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI WITH(NOLOCK) ON  COM.IDINDUSTRIA = EI.IDINDUSTRIA
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG WITH(NOLOCK) ON COM.IDCOMPANIAGRUPO = CG.IDCOMPANIAGRUPO
  
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON '+CAST(@IDUSUARIO AS VARCHAR(1000))+' = PA.IDUSUARIO AND PA.IDPROSPECTO = O.IDPROSPECTO
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES ORI WITH(NOLOCK) ON ORI.IDORIGEN = P.IDORIGEN
  INNER JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F WITH(NOLOCK) ON O.IDFASE = F.IDFASE  
  INNER JOIN <#SESSION.DB/>.dbo.USUARIOS U WITH(NOLOCK) ON O.IDUSUARIO = U.IDUSUARIO 
  INNER JOIN <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK) ON O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON O.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO = U1.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CERTEZAS EC ON EC.IDEMPRESA = P.IDEMPRESA AND EC.CERTEZA = (O.CERTEZA*100)
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 ON CP25.IDOPCION = P.CAMPO25

  
WHERE 
  P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+' AND O.PERDIDA=0 
  AND O.GANADA = 0 
  '+@F_USUARIO+'
  AND P.DESCARTADO=0
  '+@CRIT+'

  
 
  GROUP BY COM.IDCOMPANIA, COM.TkCom, CG.COMPANIAGRUPO, COM.EMPRESA, COM.URL, COM.TELEFONOCORPORATIVO, COM.IDCOMPANIAGRUPO, EI.INDUSTRIA
  ORDER BY 1 DESC, COM.Empresa 
  '
  EXEC (@SQL)
  
 
