//[session.db|Untyped,session.convertcode|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,idoportunidad|Integer,tko|Text,]
--select
DECLARE @IDOPORTUNIDAD INT
DECLARE @TKO VARCHAR(128)

SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD,0 )
SET @TKO = ISNULL(:TKO, '')

  IF(@TKO != '')BEGIN SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE TKO = @TKO END

SELECT
 TOP 1 
 SALESUP_CT.dbo.esCanalizado(O.TKO, O.TKOM) AS esCanalizado, SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS ProspectoCanalizado, COM.TKCOM, COM.CCAMPO1,COM.CCAMPO2,COM.CCAMPO3,COM.CCAMPO4,COM.CCAMPO5,COM.CCAMPO6,COM.CCAMPO7,COM.CCAMPO8,COM.CCAMPO9,COM.CCAMPO10,
 CONVERT(VARCHAR(10),O.CANALIZADOEL ,103) AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, O.USRCANALIZO as Canalizo, O.USRCANALIZADO AS Canalizado,
 (SELECT CASE WHEN COUNT(PA1.IDPROSPECTO) > 0 THEN '1' ELSE '' END FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA1 WHERE PA1.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != PA1.IDUSUARIO) AS COMPARTIDO,
   COM.URL AS URLEMPRESA,COM.DIRECCION1 AS DIRECCIONEMPRESA1, COM.DIRECCION2 AS DIRECCIONEMPRESA2, COM.CIUDAD AS CIUDADEMPRESA,COM.CODIGOPOSTAL AS CPEMPRESA,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = COM.IDESTADO AND IDPAIS=COM.IDPAIS) AS ESTADOEMPRESA, COM.NEMPLEADOS AS NEMPRESA,
   (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = COM.IDPAIS) AS PAISEMPRESA,
   INDUSTRIA, COMPANIAGRUPO,
  LEN(ISNULL(MOVIL,0)) AS TIENEMOVIL, COM.TELEFONOCORPORATIVO,
  O.COMISION AS COMI,
  O.CAMPO1 AS CAMPO1O, O.CAMPO2 AS CAMPO2O, O.CAMPO3 AS CAMPO3O, O.CAMPO4 AS CAMPO4O,
  O.CAMPO5 AS CAMPO5O, O.CAMPO6 AS CAMPO6O, O.CAMPO7 AS CAMPO7O, O.CAMPO8 AS CAMPO8O,
  CASE WHEN O.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO9, <#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO9O,
  CASE WHEN O.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO10,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO10O,
  CASE WHEN O.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO11,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO11O,
  CASE WHEN O.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO12,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO12O,
  O.CAMPO13 AS CAMPO13O, O.CAMPO14 AS CAMPO14O, O.CAMPO15 AS CAMPO15O, O.CAMPO16 AS CAMPO16O,
  O.CAMPO17 AS CAMPO17O, O.CAMPO18 AS CAMPO18O, O.CAMPO19 AS CAMPO19O, O.CAMPO20 AS CAMPO20O,
  O.CAMPO21 AS CAMPO21O, O.CAMPO22 AS CAMPO22O, O.CAMPO23 AS CAMPO23O, O.CAMPO24 AS CAMPO24O, O.CAMPO25 AS CAMPO25O, 
  O.CAMPO26 AS CAMPO26O, O.CAMPO27 AS CAMPO27O, O.CAMPO28 AS CAMPO28O,
  O.CAMPO29 AS CAMPO29O, O.CAMPO30 AS CAMPO30O, O.CAMPO31 AS CAMPO31O, O.CAMPO32 AS CAMPO32O,
  O.CAMPO33 AS CAMPO33O, O.CAMPO34 AS CAMPO34O,  O.CAMPO35 AS CAMPO35O,  O.CAMPO36 AS CAMPO36O,
  O.CAMPO37 AS CAMPO37O, O.CAMPO38 AS CAMPO38O,  O.CAMPO39 AS CAMPO39O,  O.CAMPO40 AS CAMPO40O,
  O.CAMPO41 AS CAMPO41O, O.CAMPO42 AS CAMPO42O,  O.CAMPO43 AS CAMPO43O,  O.CAMPO44 AS CAMPO44O,
  O.CAMPO45 AS CAMPO45O, O.CAMPO46 AS CAMPO46O,  O.CAMPO47 AS CAMPO47O,  O.CAMPO48 AS CAMPO48O,
  O.CAMPO49 AS CAMPO49O, O.CAMPO50 AS CAMPO5O0,  O.CAMPO51 AS CAMPO51O,  O.CAMPO52 AS CAMPO52O,
  O.CAMPO53 AS CAMPO53O, O.CAMPO54 AS CAMPO54O,  O.CAMPO55 AS CAMPO55O,  O.CAMPO56 AS CAMPO56O,
  O.CAMPO57 AS CAMPO57O, O.CAMPO58 AS CAMPO58O,  O.CAMPO59 AS CAMPO59O,  O.CAMPO60 AS CAMPO60O,
  O.CAMPO61 AS CAMPO61O, O.CAMPO62 AS CAMPO62O,  O.CAMPO63 AS CAMPO63O,  O.CAMPO64 AS CAMPO64O,     
  
  
  
  P.CAMPO1 AS CAMPO1P, P.CAMPO2 AS CAMPO2P, P.CAMPO3 AS CAMPO3P, P.CAMPO4 AS CAMPO4P,
  P.CAMPO5 AS CAMPO5P, P.CAMPO6 AS CAMPO6P, P.CAMPO7 AS CAMPO7P, P.CAMPO8 AS CAMPO8P,
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO9P,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO10P,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO11P,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,<#SESSION.CONVERTCODE/>) ELSE '' END AS CAMPO12P,
  P.CAMPO13 AS CAMPO13P, P.CAMPO14 AS CAMPO14P, P.CAMPO15 AS CAMPO15P, P.CAMPO16 AS CAMPO16P,
  P.CAMPO17 AS CAMPO17P, P.CAMPO18 AS CAMPO18P, P.CAMPO19 AS CAMPO19P, P.CAMPO20 AS CAMPO20P,
  P.CAMPO21 AS CAMPO21P, P.CAMPO22 AS CAMPO22P, P.CAMPO23 AS CAMPO23P, P.CAMPO24 AS CAMPO24P,
  P.CAMPO25 AS CAMPO25P, P.CAMPO26 AS CAMPO26P, P.CAMPO27 AS CAMPO27P, P.CAMPO28 AS CAMPO28P,
  P.CAMPO29 AS CAMPO29P, P.CAMPO30 AS CAMPO30P, P.CAMPO31 AS CAMPO31P, P.CAMPO32 AS CAMPO32P,
  P.CAMPO33 AS CAMPO33P, P.CAMPO34 AS CAMPO34P,  P.CAMPO35 AS CAMPO35P,  P.CAMPO36 AS CAMPO36P,
  P.CAMPO37 AS CAMPO37P, P.CAMPO38 AS CAMPO38P,  P.CAMPO39 AS CAMPO39P,  P.CAMPO40 AS CAMPO40P,
  P.CAMPO41 AS CAMPO41P, P.CAMPO42 AS CAMPO42P,  P.CAMPO43 AS CAMPO43P,  P.CAMPO44 AS CAMPO44P,
  P.CAMPO45 AS CAMPO45P, P.CAMPO46 AS CAMPO46P,  P.CAMPO47 AS CAMPO47P,  P.CAMPO48 AS CAMPO48P,
  P.CAMPO49 AS CAMPO49P, P.CAMPO50 AS CAMPO5OP,  P.CAMPO51 AS CAMPO51P,  P.CAMPO52 AS CAMPO52P,
  P.CAMPO53 AS CAMPO53P, P.CAMPO54 AS CAMPO54P,  P.CAMPO55 AS CAMPO55P,  P.CAMPO56 AS CAMPO56P,
  P.CAMPO57 AS CAMPO57P, P.CAMPO58 AS CAMPO58P,  P.CAMPO59 AS CAMPO59P,  P.CAMPO60 AS CAMPO60P,
  P.CAMPO61 AS CAMPO61P, P.CAMPO62 AS CAMPO62P,  P.CAMPO63 AS CAMPO63P,  P.CAMPO64 AS CAMPO64P,
  
  cast(certeza as varchar(5)) as certeza, 
  convert(varchar(12), FECHA_CIERRE, <#SESSION.CONVERTCODE/>) as FECHA_CIERRE2,
   convert(varchar(12), GETDATE(), <#SESSION.CONVERTCODE/>) as FECHA_CIERRE3,
  ISNULL(ARCHIVO, '') AS ARCHIVO,
   convert(varchar(12),O.FECHA_CIERRE, <#SESSION.CONVERTCODE/>) AS FECHA_CIERRE,
   convert(varchar(12),O.GANADA_FECHA, <#SESSION.CONVERTCODE/>) AS GANADA_FECHA,
  convert(varchar(12),O.PERDIDA_FECHA, <#SESSION.CONVERTCODE/>) AS PERDIDA_FECHA,
     convert(varchar(12),O.FECHAHORA, <#SESSION.CONVERTCODE/>) AS FECHAHORA,
      convert(varchar(12),O.FECHA_ULTIMOSEGUIMIENTO, <#SESSION.CONVERTCODE/>) AS FECHA_ULTIMOSEGUIMIENTO,
    ISNULL(P.IDCOMPANIA, 0) as idcompania, '<a href="EmpresasVisualizar.dbsp?tkcom='+com.tkcom+'"><i class="fa fa-building-o"></i> '+P.EMPRESA+'</a>' as LINKEMPRESA,
    CASE WHEN ISNULL(P.IDCOMPANIA, 0) > 0 THEN '<i class="fa fa-building-o"></i>&nbsp;'+COM.EMPRESA ELSE p.EMPRESA END AS EMPRESATXT,
  O.IdCatalogoOpcion1, O.IdCatalogoOpcion2, O.IdCatalogoOpcion3,
   O.*, P.*, F.FASE, LP.LINEA_PRODUCTO,
    <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO , 
  CONVERT(VARCHAR(12),O.FECHA_CIERRE,<#SESSION.CONVERTCODE/>) AS FECHA_CIERRE_EST,
   (SELECT TOP 1 ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = P.IDESTADO) AS ESTADO,
  (SELECT TOP 1 PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = P.IDPAIS) AS PAIS,  
  (SELECT TOP 1 ORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDORIGEN = P.IDORIGEN) AS ORIGEN,  
  (U.NOMBRE + ' ' + U.APELLIDOS) AS AGENTE, U.EMAIL,U.CALENDARIOPAGOS,
  P.ETIQUETAS_TXT AS ETIQUETAS,  
  ISNULL(ICONO_ARCHIVO, 'icon_default.jpg') AS ICONO_ARCHIVO,
  CASE 
    WHEN O.FECHA_CIERRE < <#SESSION.DB/>.dbo.getonlydate (GETDATE()) THEN 1
  ELSE 0
  END AS VENCIDA, O.IDUSUARIO AS D_OPOR, P.IDUSUARIO AS D_PROS,
  (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WHERE PA.IDPROSPECTO = o.IDPROSPECTO ) AS COMPARTIDO,
  isnull((SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WHERE PA.IDUSUARIO = <#SESSION.IDUSUARIO/> AND PA.IDPROSPECTO = o.IDPROSPECTO),0) AS asignado

  FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA,<#SESSION.DB/>.DBO.OPORTUNIDADES O LEFT JOIN  <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES F ON O.IDFASE = F.IDFASE
  LEFT JOIN <#SESSION.DB/>.DBO.DOCUMENTO_ICONOS ON O.ARCHIVO != '' AND EXTENSION = <#SESSION.DB/>.dbo.obtiene_extension(ARCHIVO), 
  <#SESSION.DB/>.DBO.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA AND COM.IDEMPRESA = <#SESSION.IDEMPRESA/>
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO 
    LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA,
 <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>, 2, 0) UL,
  <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP
WHERE
  UL.ID=PA.IDUSUARIO AND
  O.IDOPORTUNIDAD = @IDOPORTUNIDAD AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND
  O.IDPROSPECTO = P.IDPROSPECTO  AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO AND O.IDUSUARIO = U.IDUSUARIO AND PA.IDPROSPECTO=P.IDPROSPECTO 
