//[session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,razones|Integer,comentario|Text,listao|Text,session.db|Untyped,]
--INSERT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT, @CONVERTCODE INT

DECLARE @REGISTRO INT, @IDOPORTUNIDAD INT, @IDPROSPECTO INT, @IDUSUARIO INT, @RAZONES INT, @FECHA DATETIME
DECLARE @TO INT, @TOTAL INT
DECLARE @COMENTARIO VARCHAR(258), @LISTA VARCHAR(MAX)
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDOPORTUNIDAD INT, IDPROSPECTO INT)

SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

SET @FECHA = GETDATE()
SET @RAZONES = ISNULL(:RAZONES, 0)
SET @COMENTARIO = :COMENTARIO
SET @LISTA = isnull(:LISTAO,'')

SET @TO = 1

IF @COMENTARIO IS NULL BEGIN SELECT @COMENTARIO = RAZONPERDIDA FROM <#SESSION.DB/>.DBO.EMPRESAS_RAZONES_PERDIDA WHERE IDRAZONPERDIDA = @RAZONES END

IF @RAZONES = 0 BEGIN SET @RAZONES = NULL END
	
  
INSERT INTO @TABLATEMP (IDOPORTUNIDAD,IDPROSPECTO)
SELECT  IDOPORTUNIDAD, IDPROSPECTO  FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WITH(NOLOCK) WHERE IDOPORTUNIDAD IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,','))

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDOPORTUNIDAD = IDOPORTUNIDAD, @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
	
	 UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET 
 	 PERDIDA=1,
 	 PERDIDA_FECHA=GETDATE(),
	 IDRAZONPERDIDA = @RAZONES,
 	 PERDIDA_RAZON = @COMENTARIO,
	 CAMBIOLOCAL = 1, ULTIMAMODIFICACION = GETDATE()
	 WHERE
 	 IDOPORTUNIDAD = @IDOPORTUNIDAD
	  
	 SELECT @REGISTRO=COUNT(*) FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO  AND PERDIDA=0 AND GANADA=0
	  
	 IF(@REGISTRO >= 1)
  	 BEGIN
	 	   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS 
		   SET ESOPORTUNIDAD = 1, DESCARTADO = 0, ULTIMAMODIFICACION = GETDATE(), CAMBIOLOCAL = 1 
    	   WHERE IDPROSPECTO =  @IDPROSPECTO
      	   		   
		   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
		   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE())
	 END 
	 ELSE
	 BEGIN
	  	   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK)
  		   SET ESOPORTUNIDAD = 0, DESCARTADO = 0, ULTIMAMODIFICACION = GETDATE(), CAMBIOLOCAL = 1
		   WHERE IDPROSPECTO = @IDPROSPECTO
		   
		   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
		   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE())
	 END
   
     EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES @IDUSUARIO,11,@IDPROSPECTO,@IDOPORTUNIDAD, @CONVERTCODE, '',''
	 EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO,@FECHA
	
	SET @TO = @TO + 1
END


