//[filtroagrupardetalle|Integer,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--SELECT
/*PROTEGIDO*/

DECLARE @FILTROAGRUPARDETALLE INT 
SET @FILTROAGRUPARDETALLE= ISNULL(:FILTROAGRUPARDETALLE, 0)

SELECT TK AS TKLINEA_PROD,L.*,  coalesce(C.COMISION, L.COMISION,0) AS COMISIONFINAL, SALESUP_CT.dbo.esCanalizado(TK, TKM) AS esCanalizado, @FILTROAGRUPARDETALLE AS FILTROAGRUPARDETALLE
FROM <#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO L
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_LINEAS_COMISION C ON  C.IDUSUARIO = <#SESSION.IDUSUARIO/> AND L.IDLINEA_PRODUCTO = C.IDLINEA 
WHERE L.IDEMPRESA = <#SESSION.IDEMPRESA/> ORDER BY LINEA_PRODUCTO

