//[id|Integer,archivo|Text,tk|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,]
--insert
DECLARE @ID INT
DECLARE @ARCHIVO VARCHAR(MAX), @TK VARCHAR(MAX)
DECLARE @HAYARCHIVO INT
SET @ID=ISNULL(:ID,0)
SET @ARCHIVO = ISNULL(:ARCHIVO,'')
SET @HAYARCHIVO=0
SET @TK = ISNULL(:TK,'')

IF @TK != '' BEGIN SELECT @ID = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE CAST(TKARCH AS VARCHAR(128))= @TK END

IF (@ID>0)
BEGIN
SELECT @HAYARCHIVO=COUNT(*) FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND ARCHIVO LIKE @ARCHIVO
  IF (@HAYARCHIVO>0)
   BEGIN
     DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_ARCHIVOS_AMAZON WHERE ARCHIVO LIKE @ARCHIVO AND IDEMPRESA=<#SESSION.IDEMPRESA/>
   END


DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
DECLARE @NOMBRE VARCHAR(255)

SELECT @NOMBRE =  <#SESSION.DB/>.DBO.NOMBRE_ARCHIVO_REAL_PROSPECTOS(ARCHIVO), @IDPROSPECTO = IDPROSPECTO , @IDOPORTUNIDAD = IDOPORTUNIDAD  
FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE IDPROSPECTOARCHIVO = @ID
INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)
VALUES (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, 'Se eliminó un archivo: '+@NOMBRE+'', 1 )


DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE IDPROSPECTOARCHIVO=@ID
END     