//[session.db|Untyped,f_usuario|Text,session.idempresa|Untyped,crit|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :CRIT , '')
DECLARE @F_USUARIO VARCHAR(MAX) SET @F_USUARIO = ISNULL( :F_USUARIO , '')

SET @SQL = '

SELECT COUNT (dISTINCT( ISNULL(P.idcompania,0) ) )  AS TotalResgistros
 
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK)
  LEFT JOIN <#SESSION.DB/>.dbo.DOCUMENTO_ICONOS WITH(NOLOCK) ON O.ARCHIVO != '''' 
  AND EXTENSION = <#SESSION.DB/>.dbo.obtiene_extension(ARCHIVO)
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON O.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO, 
  <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK)
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI WITH(NOLOCK) ON  COM.IDINDUSTRIA = EI.IDINDUSTRIA
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG WITH(NOLOCK) ON COM.IDCOMPANIAGRUPO = CG.IDCOMPANIAGRUPO,
  <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F WITH(NOLOCK), <#SESSION.DB/>.dbo.USUARIOS U WITH(NOLOCK), 
  <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK)


WHERE 
  O.PERDIDA=0 
  AND O.GANADA = 0 
  AND O.IDPROSPECTO = P.IDPROSPECTO
  '  +  @F_USUARIO +' 
  AND P.DESCARTADO=0 
  AND O.IDUSUARIO = U.IDUSUARIO 
  AND O.IDFASE = F.IDFASE 
  AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
  AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>

' + @CRIT 


EXEC (@SQL) 