//[session.convertcode|Untyped,session.idempresa|Untyped,ejecutivo|Integer,buscar|Text,estado|Integer,session.idgrupo|Untyped,desde|Text,hasta|Text,session.db|Untyped,correo|Integer,]
--SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @CONVERTECODE INT, @ESTADO INT, @IDGRUPO INT
DECLARE @CORREO INT = ISNULL(:CORREO,0)
DECLARE @BUSCAR VARCHAR(256)
DECLARE @DESDE VARCHAR(128), @HASTA VARCHAR(128)
DECLARE @FILTRO VARCHAR(MAX) = ''
DECLARE @SQLTXT VARCHAR(MAX) = ''

SET @CONVERTECODE = <#SESSION.CONVERTCODE/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = ISNULL(:ejecutivo,0)
SET @BUSCAR = ISNULL(:BUSCAR,'')
SET @ESTADO = ISNULL(:ESTADO,0)
SET @IDGRUPO = <#SESSION.IDGRUPO/>

SET @DESDE = ISNULL(:DESDE,'')
SET @HASTA = ISNULL(:HASTA,'')

IF(@ESTADO <> 2)
	SET @FILTRO =  @FILTRO + ' AND ESTADO = ' + CAST(@ESTADO AS VARCHAR(5))

IF(@CORREO <> 2)
	SET @FILTRO =  @FILTRO + ' AND TIPO = ' + CAST(@CORREO AS VARCHAR(5))
	
IF(@IDUSUARIO <> 0)
	SET @FILTRO =  @FILTRO + ' AND UE.IDUSUARIO = ' + CAST(@IDUSUARIO AS VARCHAR(5))

IF(@BUSCAR <> '')
	SET @FILTRO =  @FILTRO + ' AND (UE.DESTINATARIO LIKE ''%'+@BUSCAR+'%'' OR UE.ASUNTO LIKE ''%'+@BUSCAR+'%'' OR P.NOMBRE LIKE ''%'+@BUSCAR+'%'' OR P.APELLIDOS LIKE ''%'+@BUSCAR+'%'' OR P.EMPRESA LIKE ''%'+@BUSCAR+'%'') '

IF(@DESDE <> '')
BEGIN
	IF(@DESDE <> @HASTA)
	 	SET @FILTRO =  @FILTRO + ' AND <#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHAHORA) BETWEEN CONVERT(DATETIME,'''+@DESDE+''','+CAST(@CONVERTECODE AS VARCHAR(5))+') AND CONVERT(DATETIME,'''+@HASTA+''','+CAST(@CONVERTECODE AS VARCHAR(5))+') ' 
	ELSE
		SET @FILTRO =  @FILTRO + ' AND <#SESSION.DB/>.DBO.GETONLYDATE(UE.FECHAHORA) = <#SESSION.DB/>.DBO.GETONLYDATE(CONVERT(DATETIME,'''+@HASTA+''','+CAST(@CONVERTECODE AS VARCHAR(5))+')) ' 
END

SET @SQLTXT = ' SELECT U.IDUSUARIO,
 U.INICIALES , U.NOMBRE + '' '' + U.APELLIDOS AS EJECUTIVO, COUNT(*) AS SMS_ENVIADOS
FROM <#SESSION.DB/>.DBO.USUARIOS_SMS UE 
LEFT JOIN <#SESSION.DB/>.DBO.AUTORESPONDERS_CONTROL AC ON AC.IDPROSPECTO = UE.IDPROSPECTO AND AC.IDPIEZA = UE.IDPIEZA
JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO = UE.IDPROSPECTO
JOIN <#SESSION.DB/>.DBO.USUARIOS U ON UE.IDUSUARIO = U.IDUSUARIO
WHERE
U.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(5))+' 
AND U.IDUSUARIO = UE.IDUSUARIO '+@FILTRO+'
GROUP BY U.INICIALES , U.NOMBRE, U.APELLIDOS, U.IDUSUARIO
ORDER BY  U.NOMBRE, U.APELLIDOS DESC '

EXEC(@SQLTXT)