//[sms|Integer,session.db|Untyped,session.idempresa|Untyped,tku|Text,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SMS INT
DECLARE @USR INT
DECLARE @TKU VARCHAR(256) 

SET @SMS = ISNULL(:SMS,0)
SET @TKU = ISNULL(:TKU, '') 


UPDATE <#SESSION.DB/>.DBO.USUARIOS SET SMS_ASIGNADOS = CAST(@SMS AS INT) WHERE TKU = @TKU   AND IDEMPRESA = <#SESSION.IDEMPRESA/>