//[tkp|Text,msg|Text,session.idusuario|Untyped,session.idempresa|Untyped,idprospecto|Integer,idoportunidad|Integer,numtel|Text,session.db|Untyped,]
--UPDATE 
DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @IDPROSPECTO INT
DECLARE @TKP VARCHAR(128)
DECLARE @IDOPORTUNIDAD INT
DECLARE @NUMTEL VARCHAR(256)
DECLARE @MSG VARCHAR(256)
SET @MSG = :MSG 
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TKP=:TKP
SET @IDPROSPECTO=CAST(ISNULL(:IDPROSPECTO,0) AS INT)
SET @IDOPORTUNIDAD = CAST(ISNULL(:IDOPORTUNIDAD,0) AS INT)
SET @NUMTEL=REPLACE(ISNULL(:NUMTEL,''), ' ', '')

IF  ISNULL(@TKP,'') != ''
  SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDEMPRESA = @IDEMPRESA AND TKP = @TKP


EXEC <#SESSION.DB/>.dbo.SP_ENVIA_SMS @IDUSUARIO, @IDEMPRESA,@IDPROSPECTO, @IDOPORTUNIDAD, 0, @MSG,@NUMTEL,1

