//[session.idempresa|Untyped,idp|Integer,session.db|Untyped,]
--select
DECLARE @MUESTRA_CERTEZA INT, @IDEMPRESA INT, @ProspectoCanalizado INT, @idProspecto INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @idProspecto = ISNULL(:IDP,0)

SELECT @MUESTRA_CERTEZA = OCULTAR_CERTEZAS_SINDESC FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA
SET @ProspectoCanalizado = 0
IF @idProspecto > 0
BEGIN
	 SELECT @ProspectoCanalizado = SALESUP_CT.dbo.esCanalizado(TKP, TKPM) FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @idProspecto
END

IF(@ProspectoCanalizado < 2)
BEGIN
 
 SELECT SALESUP_CT.dbo.esCanalizado(TK, TKM) AS esCanalizado, IDCERTEZAEMPRESA,(CAST(CERTEZA AS FLOAT)/100) AS VALORCERTEZA,
 CASE WHEN ISNULL(DESCRIPCION,'') <> '' THEN CAST(CERTEZA AS VARCHAR(10))+ '% - '+ LTRIM(RTRIM(ISNULL(DESCRIPCION,''))) ELSE CAST(CERTEZA AS VARCHAR(10))+ '%' END AS NOMBRECERTEZA
 FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA =@IDEMPRESA AND (@MUESTRA_CERTEZA = 0 OR (@MUESTRA_CERTEZA = 1 AND DESCRIPCION <> ''))
 ORDER BY CERTEZA ASC

END
ELSE IF (@ProspectoCanalizado >= 2)
BEGIN
 
 SELECT SALESUP_CT.dbo.esCanalizado(TK, TKM) AS esCanalizado, IDCERTEZAEMPRESA,(CAST(CERTEZA AS FLOAT)/100) AS VALORCERTEZA,
 CASE WHEN ISNULL(DESCRIPCION_CORPORATIVA,'') <> '' THEN CAST(CERTEZA AS VARCHAR(10))+ '% - '+ LTRIM(RTRIM(ISNULL(DESCRIPCION_CORPORATIVA,''))) ELSE CAST(CERTEZA AS VARCHAR(10))+ '%' END AS NOMBRECERTEZA
 FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA =@IDEMPRESA AND DESCRIPCION_CORPORATIVA <> ''
 ORDER BY CERTEZA ASC

END


