//[session.idempresa|Untyped,prospectocanalizado|Text,session.db|Untyped,]
--select
DECLARE @MUESTRA_CERTEZA INT, @IDEMPRESA INT, @ProspectoCanalizado INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET  @ProspectoCanalizado = 0
IF (:PROSPECTOCANALIZADO !='undefined')
SET @ProspectoCanalizado = ISNULL(:PROSPECTOCANALIZADO,0)

SELECT @MUESTRA_CERTEZA = OCULTAR_CERTEZAS_SINDESC FROM <#SESSION.DB/>.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA

IF(@ProspectoCanalizado < 2)
BEGIN
 
SELECT IDCERTEZAEMPRESA,(CAST(CERTEZA AS FLOAT)/100) AS value,
CASE WHEN ISNULL(DESCRIPCION,'') <> '' THEN CAST(CERTEZA AS VARCHAR(10))+ '% - '+ LTRIM(RTRIM(ISNULL(DESCRIPCION,''))) ELSE CAST(CERTEZA AS VARCHAR(10))+ '%' END AS Opcion
FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA =@IDEMPRESA AND (@MUESTRA_CERTEZA = 0 OR (@MUESTRA_CERTEZA = 1 AND DESCRIPCION <> ''))
ORDER BY CERTEZA ASC

END
ELSE IF (@ProspectoCanalizado >= 2)
BEGIN
 
SELECT IDCERTEZAEMPRESA,(CAST(CERTEZA AS FLOAT)/100) AS value,
CASE WHEN ISNULL(DESCRIPCION_CORPORATIVA,'') <> '' THEN CAST(CERTEZA AS VARCHAR(10))+ '% - '+ LTRIM(RTRIM(ISNULL(DESCRIPCION_CORPORATIVA,''))) ELSE CAST(CERTEZA AS VARCHAR(10))+ '%' END AS Opcion
FROM <#SESSION.DB/>.DBO.EMPRESAS_CERTEZAS WHERE IDEMPRESA =@IDEMPRESA AND ( ( DESCRIPCION_CORPORATIVA <> ''))
ORDER BY CERTEZA ASC

END