//[ocultar_certezas|Text,session.db|Untyped,session.idempresa|Untyped,]
--UPDATE
DECLARE @OCULTA INT
DECLARE @OCULTAR_CERTEZAS VARCHAR(1000)

SET @OCULTAR_CERTEZAS=ISNULL(:OCULTAR_CERTEZAS,'')
IF @OCULTAR_CERTEZAS = ''
BEGIN
  SET @OCULTA = 1
END
ELSE
BEGIN
	 SET @OCULTA = CAST(@OCULTAR_CERTEZAS AS INT)
END


UPDATE <#SESSION.DB/>.DBO.EMPRESAS SET OCULTAR_CERTEZAS_SINDESC = @OCULTA WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>