//[fechainicial|Text,fechafin|Text,session.idempresa|Untyped,session.convertcode|Untyped,idcita|Text,session.db|Untyped,]
--SELECT

/*PROTEGIDO*/
DECLARE @IDUSUARIO  INT
DECLARE @IDEMPRESA INT
DECLARE @FECHAINICIO DATETIME 
DECLARE @USUARIOEXISTE varchar(256)
DECLARE @FECHAEXISTE DATETIME
DECLARE @CONVERTCODE  INT 
DECLARE @IDCITA VARCHAR(MAX)
DECLARE @IDCITAEDIT INT
DECLARE @SQLTEXT VARCHAR(MAX) 
DECLARE @FECHAFIN DATETIME 


DECLARE @PASA INT
SELECT @PASA = (CASE WHEN ISNULL(:FECHAINICIAL,'') LIKE '%UNDEF%' OR ISNULL(:FECHAFIN,'') LIKE '%UNDEF%' THEN 0 ELSE 1 END)

IF (@PASA=1)
   BEGIN

SET @IDEMPRESA =CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @CONVERTCODE=CAST('<#SESSION.CONVERTCODE/>' AS INT)
	SET @FECHAINICIO=CONVERT(DATETIME, ISNULL(:FECHAINICIAL,''), @CONVERTCODE)--fechainicial

    SET @IDCITAEDIT=ISNULL(:IDCITA,'')
	SET @IDCITA='0'
	SET @SQLTEXT=''

    SET @FECHAFIN =CONVERT(DATETIME, ISNULL(:FECHAFIN,''), @CONVERTCODE)

 
 
	SELECT @IDCITA=@IDCITA+','+CAST(IDCITA AS VARCHAR(1000)) FROM <#SESSION.DB/>.DBO.CITAS 
	WHERE IDEMPRESA=@IDEMPRESA 
	AND FECHA_INICIO BETWEEN @FECHAINICIO AND @FECHAFIN 
	AND FECHA_FIN BETWEEN @FECHAINICIO AND @FECHAFIN 
	AND IDCITA != @IDCITAEDIT
	
	 IF(LEN(@IDCITA)>0)
 	 	  BEGIN 
		   SET @SQLTEXT='SELECT C.IDCITA,CONVERT(VARCHAR(MAX), FECHA_INICIO, 103) AS FECHA_INICIO, 
		   SALESUP_CT.DBO.OBTIENEHORA(FECHA_INICIO)AS HORA, IDPERSONA,TIPOPERSONA,(CASE WHEN CI.TIPOPERSONA=2 THEN ISNULL(U.NOMBRE,'''')+'' ''+ISNULL(U.APELLIDOS,'''') ELSE  ISNULL(P.NOMBRE,'''')+'' ''+ISNULL(P.APELLIDOS,'''') END) AS USUARIO
		    FROM <#SESSION.DB/>.DBO.CITAS_INVITADOS CI   LEFT JOIN USUARIOS U ON U.IDUSUARIO=(CASE WHEN CI.TIPOPERSONA=2 THEN CI.IDPERSONA ELSE 0 END) AND U.IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(1000))+'
     	    LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDPROSPECTO=(CASE WHEN CI.TIPOPERSONA=1 THEN CI.IDPERSONA ELSE 0 END) AND P.IDEMPRESA='+CAST(@IDEMPRESA AS VARCHAR(1000))+'	
			LEFT JOIN <#SESSION.DB/>.DBO.CITAS  C ON C.IDCITA=CI.IDCITA
		    WHERE CI.IDCITA IN ('+@IDCITA+')'

			EXEC (@SQLTEXT)  
         END -- FIN ELSE ....
	ELSE 
	  BEGIN
		  SELECT 'EXISTE' AS IDPERSONA, '0' AS TIPOPERSONA, '0' AS USUARIO 
	  END
  end
ELSE   
          SELECT 'EXISTE' AS IDPERSONA, '0' AS TIPOPERSONA, '0' AS USUARIO	  

