//[session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,tipoidseleccionado|Text,idseleccionado|Text,donde|Text,asunto|Text,fechacitainicio|Text,horacitainicio|Text,fechacitafin|Text,horacitafin|Text,idplantillacorreo|Integer,idplantillasms|Integer,tiempoplantilla|Integer,descripcion|Text,repetir|Integer,terminar|Integer,fecharepetir|Text,cada|Integer,diasrecurrencia|Text,diasmes|Text,idplantillacorreonoti|Integer,idplantillasmsnoti|Integer,notifica|Integer,session.db|Untyped,]
--INSERT

DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @CONVERTCODE INT
DECLARE @TIPOPERSONA VARCHAR(5000)
DECLARE @IDPERSONA VARCHAR(5000)
DECLARE @LUGAR VARCHAR(5000)
DECLARE @ASUNTO VARCHAR(MAX)
DECLARE @FECHA_INICIO DATETIME
DECLARE @FECHA_FIN DATETIME
DECLARE @RECORDATORIO_IDPLANTILLA INT
DECLARE @RECORDATORIO_SMS_IDPLANTILLA INT
DECLARE @RECORDATORIO_CORREO_ACTIVO INT
DECLARE @RECORDATORIO_SMS_ACTIVO INT
DECLARE @RECORDATORIO_MOMENTO INT
DECLARE @RECORDATORIO_SMS_MOMENTO INT
DECLARE @DESCRIPCION VARCHAR(MAX)
DECLARE @RECURRENCIA INT
DECLARE @TIPOFIN INT
DECLARE @FECHAFINREPETIR DATETIME
DECLARE @FRECUENCIA INT
DECLARE @DIASFRECUENCIA VARCHAR(5000)
DECLARE @NOTIFICA_IDPLANTILLA INT
DECLARE @NOTIFICA_SMS_IDPLANTILLA INT
DECLARE @IDPADRE INT
DECLARE @NOTIFICACITA INT

SET @IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @CONVERTCODE=<#SESSION.CONVERTCODE/>
SET @TIPOPERSONA=ISNULL(:TipoIdSeleccionado,'')
SET @IDPERSONA=ISNULL(:IDSELECCIONADO,'')
SET @LUGAR=ISNULL(:DONDE,'')
SET @ASUNTO=ISNULL(:ASUNTO,'')
SET @FECHA_INICIO=CONVERT(DATETIME,ISNULL(:FECHACITAINICIO,''),<#SESSION.CONVERTCODE/>)+CONVERT(DATETIME,ISNULL(:horacitainicio,''),@CONVERTCODE)
SET @FECHA_FIN=CONVERT(DATETIME,ISNULL(:FECHACITAFIN,''),<#SESSION.CONVERTCODE/>)+CONVERT(DATETIME,ISNULL(:horacitafin,''),@CONVERTCODE)
SET @RECORDATORIO_IDPLANTILLA=CAST(ISNULL(:IdPlantillaCORREO,0) AS INT)
SET @RECORDATORIO_SMS_IDPLANTILLA=CAST(ISNULL(:IdPlantillaSMS,0) AS INT)
SELECT @RECORDATORIO_CORREO_ACTIVO=(CASE WHEN @RECORDATORIO_IDPLANTILLA=0 THEN 0 ELSE 1 END)
SELECT @RECORDATORIO_SMS_ACTIVO=(CASE WHEN @RECORDATORIO_SMS_IDPLANTILLA=0 THEN 0 ELSE 1 END)
SET @RECORDATORIO_MOMENTO=CAST(ISNULL(:TIEMPOPLANTILLA,0) AS INT)
SET @RECORDATORIO_SMS_MOMENTO=CAST(ISNULL(:TIEMPOPLANTILLA,0) AS INT)
SET @DESCRIPCION=:DESCRIPCION
SET @RECURRENCIA=CAST(ISNULL(:REPETIR,0) AS INT)
SET @TIPOFIN=CAST(ISNULL(:TERMINAR,0) AS INT)
SET @FECHAFINREPETIR=CONVERT(DATETIME,ISNULL(:fecharepetir,''),@CONVERTCODE)
SET @FRECUENCIA=CAST(ISNULL(:CADA,0) AS INT)
SELECT @DIASFRECUENCIA=(CASE WHEN (@RECURRENCIA=0 OR @RECURRENCIA=1) THEN '' WHEN @RECURRENCIA=2 THEN ISNULL(:DIASRECURRENCIA,'') ELSE ISNULL(:DIASMES,'') END )
SET @NOTIFICA_IDPLANTILLA=CAST(ISNULL(:IdPlantillaCORREONoti,0) AS INT)
SET @NOTIFICA_SMS_IDPLANTILLA=CAST(ISNULL(:IdPlantillaSMSNoti,0) AS INT)
SET @IDPADRE=NULL
SET @NOTIFICACITA=CAST(ISNULL(:NOTIFICA,0) AS INT)

EXEC <#SESSION.DB/>.dbo.SP_AGREGAR_CITA
	 @IDUSUARIO,
	 @IDEMPRESA,
	 @CONVERTCODE,
	 @IDPERSONA,
	 @TIPOPERSONA,
	 @LUGAR,
	 @ASUNTO,
	 @FECHA_INICIO,
	 @FECHA_FIN,
	 @RECORDATORIO_IDPLANTILLA,
	 @RECORDATORIO_SMS_IDPLANTILLA,
	 @RECORDATORIO_CORREO_ACTIVO,
	 @RECORDATORIO_SMS_ACTIVO,
	 @RECORDATORIO_MOMENTO,
	 @RECORDATORIO_SMS_MOMENTO,
	 @DESCRIPCION,@RECURRENCIA,
	 @TIPOFIN,@FECHAFINREPETIR,
	 @FRECUENCIA,
	 @DIASFRECUENCIA,
	 @NOTIFICA_IDPLANTILLA,
	 @NOTIFICA_SMS_IDPLANTILLA,
	 @IDPADRE,
	 @NOTIFICACITA
