//[session.db|Untyped,idcita|Integer,session.convertcode|Untyped,]
--select
DECLARE @IDSELECCIONADO VARCHAR(1000)
DECLARE @IDCITA INT
SET @IDSELECCIONADO=''
SET @IDCITA=ISNULL(:IDCITA,0)
SELECT @IDSELECCIONADO=CAST(IDPERSONA AS VARCHAR(100))+','+@IDSELECCIONADO FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS WHERE IDCITA=@IDCITA
SELECT *,@IDSELECCIONADO  AS IDSELECCIONADO,CONVERT(VARCHAR(10),FECHA_INICIO,<#SESSION.CONVERTCODE/>) AS FECHAINICIO, CONVERT(nvarchar(5), FECHA_INICIO, 108) AS HoraINICIO,CONVERT(VARCHAR(10),FECHAFINREPETIR,<#SESSION.CONVERTCODE/>) AS FECHAFIN_REPETIR,
       CONVERT(VARCHAR(10),FECHA_FIN,<#SESSION.CONVERTCODE/>) AS FECHAFIN, CONVERT(nvarchar(5), FECHA_FIN, 108) AS HoraFIN ,
	   CONVERT(VARCHAR(10),(CASE WHEN FECHAFINREPETIR=CONVERT(DATETIME,'',<#SESSION.CONVERTCODE/>) THEN NULL ELSE FECHAFINREPETIR END),<#SESSION.CONVERTCODE/>) AS FECHAREPETIR 
	   FROM <#SESSION.DB/>.dbo.CITAS  WHERE IDCITA=@IDCITA