//[tkc|Text,session.db|Untyped,]
--SELECT
DECLARE @TKC VARCHAR(MAX)
DECLARE @CONTACTOS VARCHAR(MAX)
DECLARE @IDPROSPECTO VARCHAR(MAX)
DECLARE @TKPROSPECTO VARCHAR(MAX)
DECLARE @IDCITA INT
DECLARE @CONPROSPECTOS INT
DECLARE @INVITADOS VARCHAR(MAX)
DECLARE @IDU INT

SET @CONTACTOS = ''
SET @IDPROSPECTO = ''
SET @TKPROSPECTO = ''
SET @INVITADOS = ''
SET @TKC = ISNULL(:tkc,'')

SELECT @IDCITA = C.IDCITA FROM <#SESSION.DB/>.dbo.CITAS C WHERE TKC = @TKC

SELECT @INVITADOS = @INVITADOS + U.NOMBRE +' '+ISNULL(U.APELLIDOS,'')+',',@IDU = IDUSUARIO
FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS CI
LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = CI.IDPERSONA
WHERE CI.TIPOPERSONA = 2  AND CI.IDCITA = @IDCITA
SET @INVITADOS = LEFT(@INVITADOS,LEN(@INVITADOS)-1)

SELECT 
@CONTACTOS = @CONTACTOS + ISNULL(P.NOMBRE,' ') + ' ' + ISNULL(P.APELLIDOS, ' ')+', ',
@IDPROSPECTO = @IDPROSPECTO + CAST(P.IDPROSPECTO AS VARCHAR(MAX)) + ', ',
@TKPROSPECTO = @TKPROSPECTO + P.TKP + ', '
FROM <#SESSION.DB/>.dbo.PROSPECTOS P
LEFT JOIN <#SESSION.DB/>.dbo.CITAS_INVITADOS CI ON CI.IDPERSONA = P.IDPROSPECTO 
WHERE CI.IDCITA = @IDCITA AND CI.TIPOPERSONA = 1
SET @CONTACTOS = LEFT(@CONTACTOS,LEN(@CONTACTOS)-1)
SET @IDPROSPECTO = LEFT(@IDPROSPECTO,LEN(@IDPROSPECTO)-1)
SET @TKPROSPECTO = LEFT(@TKPROSPECTO,LEN(@TKPROSPECTO)-1)

SELECT @CONPROSPECTOS = COUNT (*) FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS CI WHERE CI.IDCITA = @IDCITA AND CI.TIPOPERSONA =1

SELECT '1' AS tCita,'<i class="fa fa-calendar"></i> '+C.ASUNTO AS Titulo,@CONTACTOS AS Contactos,C.IDCITA AS Idc,@IDU AS Idu, @IDPROSPECTO AS IdsProspectos, @TKPROSPECTO AS TksProspectos, @INVITADOS AS Invitados, COM.EMPRESA AS Empresa,
 C.LUGAR AS Lugar, CASE WHEN SALESUP_CT.dbo.GetOnlyDate(C.FECHA_FIN) = SALESUP_CT.dbo.GetOnlyDate(C.FECHA_INICIO) THEN '1' ELSE ' ' END AS MismoDia,
 CONVERT(VARCHAR(10), C.FECHA_INICIO,103) AS FechaInicio, SALESUP_CT.dbo.ObtieneHora(C.FECHA_INICIO) as HoraInicio,
 CONVERT(VARCHAR(10), C.FECHA_FIN,103) as FechaFin, SALESUP_CT.dbo.ObtieneHora(C.FECHA_FIN) as HoraFin, @CONPROSPECTOS AS ConProspecto
FROM <#SESSION.DB/>.dbo.CITAS C
LEFT JOIN <#SESSION.DB/>.dbo.CITAS_INVITADOS CI ON CI.IDCITA = C.IDCITA AND CI.TIPOPERSONA = 1
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P ON P.IDPROSPECTO = CI.IDPERSONA
LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA
WHERE C.TKC = @TKC AND C.ACTIVO = 1