//[session.idempresa|Untyped,session.idusuario|Untyped,q|Text,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @Q VARCHAR(MAX)
DECLARE @T INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @Q = ISNULL(:Q,'')
SET @T=1

EXEC <#SESSION.DB/>.dbo.SP_BusquedaCitas @IDEMPRESA,@IDUSUARIO,@Q,1