//[idseleccionado|Text,tipoidseleccionado|Text,session.db|Untyped,session.idempresa|Untyped,]
--select
DECLARE @TABLAPERSONAS AS TABLE (ID INT, IDPERSONA INT, PERSONA VARCHAR(1000), TIPOPERSONA INT)
DECLARE @IdSeleccionado VARCHAR(MAX)
DECLARE @TipoIdSeleccionado VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
DECLARE @TOTALPROSPECTOS INT
DECLARE @TOTNOCOMPARTIDOS INT
DECLARE @TOTCORREO INT
DECLARE @TOTEMAIL INT
SET @TOTNOCOMPARTIDOS=0
SET @TOTCORREO=0
SET @TOTEMAIL=0
SET @TOTALPROSPECTOS=0
SET @SQL=''
SET @IdSeleccionado=:IdSeleccionado
SET @TipoIdSeleccionado=ISNULL(:TipoIdSeleccionado,'')

INSERT INTO @TABLAPERSONAS (ID,IDPERSONA,PERSONA,TIPOPERSONA)
SELECT  P.OCCURENCEID AS ID, (CASE WHEN T.SPLITVALUE=0 THEN 0 ELSE P.SPLITVALUE END) IDPERSONA, (CASE WHEN T.SPLITVALUE=0 THEN P.SPLITVALUE ELSE '' END) PERSONA, T.SPLITVALUE AS TIPOPERSONA
  FROM <#SESSION.DB/>.dbo.Split(@IdSeleccionado,',') P, <#SESSION.DB/>.dbo.Split(@TipoIdSeleccionado,',') T  WHERE P.OCCURENCEID=T.OCCURENCEID 
DELETE FROM @TABLAPERSONAS WHERE TIPOPERSONA=0

SELECT @TOTALPROSPECTOS=COUNT(*) FROM @TABLAPERSONAS WHERE TIPOPERSONA=1

/*CASO DE USARIOS QUE NO TIENEN  PROSPECTO COMPARTIDO*/
DECLARE @USUARIOSNOCOMPARTIDOS VARCHAR(MAX)
SET @USUARIOSNOCOMPARTIDOS=''
IF (@TOTALPROSPECTOS > 0)
 BEGIN
  SELECT @TOTNOCOMPARTIDOS=COUNT(*) FROM (SELECT IDPERSONA FROM  @TABLAPERSONAS TU WHERE TIPOPERSONA=2 EXCEPT SELECT idusuario from <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS  PA, @TABLAPERSONAS TP  where TP.IDPERSONA=PA.IDPROSPECTO AND TP.TIPOPERSONA=1) A
 
  SELECT @USUARIOSNOCOMPARTIDOS=@USUARIOSNOCOMPARTIDOS+','+(ISNULL(U.NOMBRE,'')+' '+ISNULL(U.APELLIDOS,'')) FROM USUARIOS U, (  
    SELECT IDPERSONA FROM  @TABLAPERSONAS TU WHERE TIPOPERSONA=2
    EXCEPT
    SELECT idusuario from <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS  PA, @TABLAPERSONAS TP  where TP.IDPERSONA=PA.IDPROSPECTO AND TP.TIPOPERSONA=1) A
  WHERE A.IDPERSONA=U.IDUSUARIO AND U.IDEMPRESA=<#SESSION.IDEMPRESA/> 
  SELECT @USUARIOSNOCOMPARTIDOS=SUBSTRING(LTRIM(RTRIM(@USUARIOSNOCOMPARTIDOS)),2,LEN(LTRIM(RTRIM(@USUARIOSNOCOMPARTIDOS))))
 END
 
DECLARE @PROSPECTOSEMAIL VARCHAR(MAX)
SET @PROSPECTOSEMAIL=''
SELECT @TOTCORREO=COUNT(*)FROM  @TABLAPERSONAS TP,<#SESSION.DB/>.dbo.PROSPECTOS P WHERE TP.TIPOPERSONA=1 AND TP.IDPERSONA=P.IDPROSPECTO AND ISNULL(CORREO,'')=''
SELECT 	@PROSPECTOSEMAIL=@PROSPECTOSEMAIL+','+(ISNULL(P.NOMBRE,'')+' '+ISNULL(P.APELLIDOS,'')) FROM  @TABLAPERSONAS TP,<#SESSION.DB/>.dbo.PROSPECTOS P WHERE TP.TIPOPERSONA=1 AND TP.IDPERSONA=P.IDPROSPECTO AND ISNULL(CORREO,'')=''
SELECT @PROSPECTOSEMAIL=SUBSTRING(LTRIM(RTRIM(@PROSPECTOSEMAIL)),2,LEN(LTRIM(RTRIM(@PROSPECTOSEMAIL))))

DECLARE @PROSPECTOSMOVIL VARCHAR(MAX)
SET @PROSPECTOSMOVIL=''
SELECT @TOTEMAIL=COUNT(*) FROM  @TABLAPERSONAS TP,<#SESSION.DB/>.dbo.PROSPECTOS P WHERE TP.TIPOPERSONA=1 AND TP.IDPERSONA=P.IDPROSPECTO AND ISNULL(MOVIL,'')=''
SELECT 	@PROSPECTOSMOVIL=@PROSPECTOSMOVIL+','+(ISNULL(P.NOMBRE,'')+' '+ISNULL(P.APELLIDOS,'')) FROM  @TABLAPERSONAS TP,<#SESSION.DB/>.dbo.PROSPECTOS P WHERE TP.TIPOPERSONA=1 AND TP.IDPERSONA=P.IDPROSPECTO AND ISNULL(MOVIL,'')=''
SELECT @PROSPECTOSMOVIL=SUBSTRING(LTRIM(RTRIM(@PROSPECTOSMOVIL)),2,LEN(LTRIM(RTRIM(@PROSPECTOSMOVIL))))


SELECT @USUARIOSNOCOMPARTIDOS AS NombrePersona, 1 AS TipoValidacion, @TOTNOCOMPARTIDOS AS Total 
UNION 
SELECT @PROSPECTOSEMAIL AS NombrePersona, 2 AS TipoValidacion , @TOTCORREO AS Total 
UNION 
SELECT @PROSPECTOSMOVIL AS NombrePersona, 3 AS TipoValidacion , @TOTEMAIL AS Total 
ORDER  BY TIPOVALIDACION

