//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @CONT INT
SELECT @CONT=COUNT(UP.IDPLANTILLA) FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO 
 WHERE (UP.COMPARTIRCON=U.IDGRUPO OR UP.COMPARTIRCON=-1) AND UP.IDUSUARIO != <#SESSION.IDUSUARIO/> and U.IDEMPRESA=<#SESSION.IDEMPRESA/> 

IF @CONT>0 
 BEGIN
 	  SELECT ((CASE WHEN TIPOCORREO=1 THEN 'CORREO' ELSE 'SMS' END)+CAST(TIPOCORREO AS VARCHAR(10)))  AS CLASE,U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION,0 AS ORDEN , TIPOCORREO
	  FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
	  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO AND U.IDEMPRESA=<#SESSION.IDEMPRESA/>
	  WHERE UP.IDUSUARIO = <#SESSION.IDUSUARIO/>
	  UNION ALL
	  SELECT '',0,'-1',0,'',0,'[-------- COMPARTIDAS ---------]',1,0
	  UNION ALL
	  SELECT ((CASE WHEN TIPOCORREO=1 THEN 'CORREO' ELSE 'SMS' END)+CAST(TIPOCORREO AS VARCHAR(10))) AS CLASE,U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION,2, TIPOCORREO 
	  FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
	  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO 
	  WHERE (UP.COMPARTIRCON=U.IDGRUPO OR UP.COMPARTIRCON=-1) AND UP.IDUSUARIO != <#SESSION.IDUSUARIO/> and U.IDEMPRESA=<#SESSION.IDEMPRESA/> 
	  GROUP BY UP.TIPOCORREO,U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION
	  ORDER BY ORDEN ASC , TIPOCORREO,DESCRIPCION
 END
ELSE
  	  SELECT ((CASE WHEN TIPOCORREO=1 THEN 'CORREO' ELSE 'SMS' END)+CAST(TIPOCORREO AS VARCHAR(10))) AS CLASE, U.IDGRUPO,UP.IDPLANTILLA,UP.IDUSUARIO,UP.ASUNTO,UP.COMPARTIRCON,UP.DESCRIPCION,0 AS ORDEN , TIPOCORREO FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS UP
	  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO=UP.IDUSUARIO
	  WHERE UP.IDUSUARIO = <#SESSION.IDUSUARIO/> and U.IDEMPRESA=<#SESSION.IDEMPRESA/>

	  
	  ORDER BY TIPOCORREO,DESCRIPCION
