//[idcita|Text,tipo|Text,session.db|Untyped,]
--SELECT
DECLARE @IDCITA INT
DECLARE @IDPERSONAS VARCHAR(MAX)
DECLARE @TIPOSPERSONAS VARCHAR(MAX)
DECLARE @TIPO INT
SET @IDCITA=CAST(:IDCITA AS INT)
SET @IDPERSONAS=''
SET @TIPOSPERSONAS=''
SET @TIPO=CAST(:TIPO AS INT)

IF (@TIPO=0)
 SELECT @IDPERSONAS=(CASE WHEN TIPOPERSONA=0 THEN PERSONA ELSE CAST(idpersona AS VARCHAR(1000)) END)+','+@IDPERSONAS,@TIPOSPERSONAS=CAST(tipopersona AS VARCHAR(100))+','+@TIPOSPERSONAS FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS  WHERE idcita=@IDCITA AND TIPOPERSONA=0 ORDER BY IDCITAINVITADO DESC
ELSE 
 SELECT @IDPERSONAS=(CASE WHEN TIPOPERSONA=0 THEN PERSONA ELSE CAST(idpersona AS VARCHAR(1000)) END)+','+@IDPERSONAS,@TIPOSPERSONAS=CAST(tipopersona AS VARCHAR(100))+','+@TIPOSPERSONAS FROM <#SESSION.DB/>.dbo.CITAS_INVITADOS  WHERE idcita=@IDCITA ORDER BY IDCITAINVITADO DESC

 
SELECT @IDPERSONAS=LTRIM(RTRIM(REVERSE(SUBSTRING(REVERSE(@IDPERSONAS),2,LEN(@IDPERSONAS))))) 
SELECT @TIPOSPERSONAS=LTRIM(RTRIM(REVERSE(SUBSTRING(REVERSE(@TIPOSPERSONAS),2,LEN(@TIPOSPERSONAS))))) 
SELECT @IDPERSONAS AS IdSeleccionado,@TIPOSPERSONAS AS TipoIdSeleccionado