//[referidopor|Text,origendemo|Integer,eldist|Text,empresa|Text,nombre|Text,apellidos|Text,correo|Text,confirma|Text,pais|Text,estado|Text,telefono|Text,]
--SELECT

DECLARE @DIST INT
DECLARE @ORIGENDEMO INT
DECLARE @REFERIDOPOR VARCHAR(MAX)
DECLARE @ELDIST VARCHAR(MAX)
DECLARE @CONFIRMA VARCHAR(MAX)
DECLARE @PAIS VARCHAR(1000)
DECLARE @ESTADO VARCHAR(1000)
DECLARE @TELEFONO VARCHAR(1000)
SET @TELEFONO=isnull(:TELEFONO,'')
SET @ESTADO=ISNULL(:ESTADO,'')
SET @PAIS=ISNULL(:PAIS,'')
SET @CONFIRMA=ISNULL(:CONFIRMA,'')
SET @ELDIST=ISNULL(:ELDIST,'')
SET @REFERIDOPOR=ISNULL(:referidopor,'')
SET @ORIGENDEMO = ISNULL(:ORIGENDEMO,0)

IF @ELDIST =  'undefined'
 SET @DIST = 0
ELSE 
 SET @DIST = CAST(@ELDIST AS INT)

IF (@ORIGENDEMO =  1)
 SET @REFERIDOPOR=@REFERIDOPOR + '-BOTONSALESUP'
 
 
DECLARE @TIPO_ACCESO INT
SET @TIPO_ACCESO = 1 

DECLARE @EMPRESANAME VARCHAR (1000)
select @EMPRESANAME=SALESUP_CT.dbo.NomalizaCadenaEsp2 (:EMPRESA)

DECLARE @NOMBRENAME VARCHAR (1000)
select @NOMBRENAME=SALESUP_CT.dbo.NomalizaCadenaEsp2 (:NOMBRE)

DECLARE @APELLIDOSNAME VARCHAR (1000)
select @APELLIDOSNAME=SALESUP_CT.dbo.NomalizaCadenaEsp2 (:APELLIDOS)

DECLARE @CORREO VARCHAR(1000)
SET @CORREO=:CORREO
DECLARE @EXISTE INT
SELECT @EXISTE=COUNT(*) FROM CONTROL.CONTROL.DBO.USUARIOS WHERE EMAIL LIKE @CORREO

IF @EXISTE=0
BEGIN
  EXEC CONTROL.CONTROL.DBO.SP_EMPRESA_NUEVA_TOTAL @NOMBRENAME,@APELLIDOSNAME,@CORREO,@CONFIRMA,@EMPRESANAME,@PAIS,@ESTADO,@TELEFONO,@REFERIDOPOR,@DIST,@TIPO_ACCESO
  DECLARE @EMPRESACREADA INT
  DECLARE @IDUSUARIOCREADO INT
  DECLARE @BASEDATOS VARCHAR(30)
  DECLARE @SQL1 VARCHAR(5000)

  SELECT TOP 1 @EMPRESACREADA=IDEMPRESA, @IDUSUARIOCREADO=IDUSUARIO FROM CONTROL.CONTROL.DBO.USUARIOS WHERE EMAIL LIKE @CORREO ORDER BY IDEMPRESA DESC
  SELECT TOP 1 @BASEDATOS=BD_ACTUAL FROM CONTROL.CONTROL.DBO.EMPRESAS WHERE IDEMPRESA=@EMPRESACREADA

END
BEGIN
  SELECT 0
END
