//[c|Text,idproducto|Integer,]
--select
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @EMAIL VARCHAR(1000)
DECLARE @IDPRODUCTO INT 
SET @IDPRODUCTO=ISNULL(:IDPRODUCTO, 1) 
SET @EMAIL=ISNULL(:C,'')

SELECT  COUNT(*)AS EXISTE FROM CONTROL.VENTAS.DBO.V_USUARIOS  WHERE IDPRODUCTO=@IDPRODUCTO  AND EMAIL = @EMAIL

