//[c|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @C VARCHAR(MAX)
SET @C=ISNULL(:C,'') 
IF (SELECT COUNT(*) AS EXISTE FROm CARRITO_CUPONES WHERE CUPON = LTRIM(RTRIM(@C)) AND TIPO > 2)>0
  SELECT 1 AS EXISTE, TIPO, VALOR, MIN_USUARIOS FROM CARRITO_CUPONES WHERE CUPON = LTRIM(RTRIM(@C)) AND TIPO > 2
ELSE
  SELECT 0 AS EXISTE  