//[calificacion|Integer,TKTCOM|Text,IDESTADO|Integer,VISTO|Integer,SESSION.IDUSUARIO|Untyped,SESSION.CONVERTCODE|Untyped]
--update

DECLARE @IDTC INT, @C INT, @IDTICKET INT
DECLARE @TIPOUSUARIO INT

SET @TIPOUSUARIO= 1

SET @C = ISNULL(:calificacion,0)
SELECT @C

SELECT @IDTICKET = IDTICKET, @IDTC = IDTICKETCOMENTARIO FROM CONTROL.TICKETS.DBO.TICKET_COMENTARIOS WHERE TKTCOM LIKE :TKTCOM
SELECT @IDTICKET,@IDTC

UPDATE CONTROL.TICKETS.DBO.TICKETS 
SET IDESTADO = ISNULL(:IDESTADO,0), 
TIPOUSUARIO_ULTIMAMODIFICACION =@TIPOUSUARIO,
IDUSUARIO_ULTIMAMODIFICACION = CAST('<#SESSION.IDUSUARIO/>' AS INT),
FECHA_ULTIMAMODIFICACION = GETDATE(),
FECHA_CIERRE = GETDATE(),
VISTO = ISNULL(:VISTO,0) 
WHERE IDTICKET = @IDTICKET 


IF @C = 0 
   SET @C = 1

IF @IDTC <> 0
BEGIN
   UPDATE CONTROL.TICKETS.DBO.TICKET_COMENTARIOS SET IDCALIFICACION = @C WHERE IDTICKETCOMENTARIO = @IDTC
   DECLARE @NOMBRE_USUARIO VARCHAR(MAX);

   SELECT @NOMBRE_USUARIO = LTRIM(RTRIM(NOMBRE COLLATE DATABASE_DEFAULT+ ' ' + ISNULL(APELLIDOS,''))) FROM SALESUP_CT.DBO.USUARIOS U WHERE U.IDUSUARIO = <#SESSION.IDUSUARIO/>
   INSERT INTO CONTROL.TICKETS.DBO.TICKET_COMENTARIOS (IDTICKET, TIPOUSUARIO, IDUSUARIO, COMENTARIO, FECHA)
   VALUES (@IDTICKET ,@TIPOUSUARIO,<#SESSION.IDUSUARIO/>,'Cerrado por '+@NOMBRE_USUARIO+' el '+CONVERT(VARCHAR, GETDATE(),<#SESSION.CONVERTCODE/>)+' '+SALESUP_CT.dbo.ObtieneHora(GETDATE())+'', GETDATE() )
END
