//[link_adjunto|Text,session.idproducto|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,departamento|Integer,asunto|Text,descripcion|Text,ticketnormalizado|Text,sp_browser|Text,]
--INSERT

DECLARE @FECHA DATETIME
DECLARE @IDTICKET INT
DECLARE @IDUSUARIO INT
DECLARE @IDPRODUCTO INT
DECLARE @TICKET VARCHAR(255)

DECLARE @URL VARCHAR(512), @ARCHIVO VARCHAR(512)
SET @ARCHIVO = :link_adjunto

 
SET @FECHA = GETDATE()
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPRODUCTO = <#SESSION.IDPRODUCTO/>

INSERT INTO CONTROL.TICKETS.DBO.TICKETS (IDPRODUCTO, IDEMPRESA, IDUSUARIO, IDDEPARTAMENTO, ASUNTO, DESCRIPCION, ADJUNTO, ADJUNTO_LINK, IDESTADO, FECHA_ULTIMAMODIFICACION, TIPOUSUARIO_ULTIMAMODIFICACION, IDUSUARIO_ULTIMAMODIFICACION, TICKET,VISTO_CLIENTE,NAVEGADOR) 
VALUES (<#SESSION.IDPRODUCTO/>,<#SESSION.IDEMPRESA/>, <#SESSION.IDUSUARIO/>, :DEPARTAMENTO, salesup_ct.dbo.PreparaCadena(:ASUNTO), salesup_ct.dbo.PreparaCadena(:DESCRIPCION), :TICKETNORMALIZADO, @ARCHIVO, 1, @FECHA, 1, <#SESSION.IDUSUARIO/>,'',1,:SP_BROWSER)

SELECT @IDTICKET = MAX(IDTICKET) FROM CONTROL.TICKETS.DBO.TICKETS

EXEC SP_GeneraTicket @IDPRODUCTO, @TICKET OUT
UPDATE CONTROL.TICKETS.DBO.TICKETS SET TICKET = @TICKET WHERE IDTICKET = @IDTICKET

EXEC CONTROL.TICKETS.DBO.SP_NOTIFICA_TICKET @IDUSUARIO, @IDTICKET, @IDPRODUCTO