//[session.idusuario|Untyped,session.idproducto|Untyped,estatus|Text,session.db|Untyped,filtroproducto|Text,filtroestado|Text,filtrousuario|Text,]
--select
DECLARE @SQL VARCHAR(MAX)
DECLARE @FILTROPRODUCTO VARCHAR(MAX) SET @FILTROPRODUCTO = ISNULL( :FILTROPRODUCTO , '')
DECLARE @FILTROESTADO VARCHAR(MAX) SET @FILTROESTADO = ISNULL( :FILTROESTADO , '')
DECLARE @FILTROUSUARIO VARCHAR(MAX) SET @FILTROUSUARIO = ISNULL( :FILTROUSUARIO , '')

SET @SQL = '
DECLARE @IDUSUARIO INT
DECLARE @IDPRODUCTO INT
DECLARE @ESTATUS INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPRODUCTO = <#SESSION.IDPRODUCTO/>
SET @ESTATUS =  ' + :ESTATUS + '

SELECT 
REPLACE(REPLACE(CAST(DESCRIPCION AS VARCHAR(128)), ''<script'', ''&#60script''), ''<meta'', ''&#60meta'')
+ CASE WHEN LEN(CAST(DESCRIPCION AS VARCHAR(130))) > 129 THEN ''...'' ELSE '''' END
 AS DESCRIPCION, 
T.*, VD.*, VE.*, 
<#SESSION.DB/>.DBO.TIEMPO_TXT(T.FECHA_CREACION,T.FECHA_CIERRE) AS TIEMPOTERMINADO, 
<#SESSION.DB/>.DBO.TIEMPO_TXT(T.FECHA_CREACION,GETDATE()) AS TIEMPOTRANSCURRIDO 
FROM CONTROL.TICKETS.DBO.TICKETS T, CONTROL.TICKETS.DBO.V_DEPARTAMENTOS VD, CONTROL.TICKETS.DBO.V_ESTADOS VE
WHERE T.IDDEPARTAMENTO=VD.IDDEPARTAMENTO AND T.IDESTADO=VE.IDESTADO
 ' + @FILTROPRODUCTO + ' ' + @FILTROESTADO  + ' ' +@FILTROUSUARIO + '
ORDER BY T.FECHA_ULTIMAMODIFICACION DESC
'
  
EXEC (@SQL)