//[session.idusuario|Untyped,session.idempresa|Untyped,idticket|Text,TKT|Text]
SELECT 
REPLACE(REPLACE(CAST(DESCRIPCION AS VARCHAR(MAX)), '<script', '&#60script'),'<meta', '&#60meta') AS DESCRIPCION,

CASE 
 WHEN DATEDIFF ( hh , T.FECHA_CREACION, GETDATE() ) > 48 
 	THEN 'comentó el ' + SALESUP_ct.DBO.FormatoFecha(T.FECHA_CREACION,2) 
 	ELSE 'comentó '+ LOWER(SALESUP_CT.dbo.TIEMPO_TXT(T.FECHA_CREACION, GETDATE()))  
 END AS FECHA_CREACION,
SALESUP_ct.DBO.FormatoFecha(T.FECHA_ULTIMAMODIFICACION,2) AS FECHA_ULTIMAMODIFICACION,
SALESUP_ct.DBO.FormatoFecha(T.FECHA_CIERRE,2) AS FECHA_CIERRE,
T.*, VD.DEPARTAMENTO, VD.RESPONSABLE_CORREO, VE.ESTADO, VU.NOMBRE+' '+VU.APELLIDOS AS NombreUsuario , VU.NOMBRE as NOMUSER , VU.EMAIL,
CASE TIPOUSUARIO_ULTIMAMODIFICACION
WHEN 1 THEN (SELECT NOMBRE COLLATE DATABASE_DEFAULT+ ' ' + ISNULL(APELLIDOS,'') FROM SALESUP_CT.DBO.USUARIOS WHERE IDUSUARIO = IDUSUARIO_ULTIMAMODIFICACION)
WHEN 2 THEN (SELECT NOMBRE COLLATE DATABASE_DEFAULT+ ' ' + ISNULL(APELLIDOS,'') FROM CONTROL.DISTRIBUIDORES.DBO.DISTRIBUIDORES WHERE IDDISTRIBUIDOR = IDUSUARIO_ULTIMAMODIFICACION)
END AS NOMBRE_ULTIMAMODIFICACION,
CASE WHEN T.ADJUNTO_LINK IS NULL THEN 'C:\sitios\SalesUp\docs\tickets\'+T.ADJUNTO ELSE T.ADJUNTO_LINK END AS LINK
FROM CONTROL.TICKETS.DBO.TICKETS T, CONTROL.TICKETS.DBO.V_DEPARTAMENTOS VD, CONTROL.TICKETS.DBO.V_ESTADOS VE , SALESUP_CT.DBO.USUARIOS VU
WHERE T.IDESTADO = VE.IDESTADO AND T.IDDEPARTAMENTO = VD.IDDEPARTAMENTO AND T.IDUSUARIO = VU.IDUSUARIO  AND T.TKT = COALESCE(:IDTICKET,:TKT,'') AND T.IDUSUARIO = <#SESSION.IDUSUARIO/> AND T.IDEMPRESA = <#SESSION.IDEMPRESA/>
