//[session.idempresa|Untyped,session.idusuario|Untyped,]
SELECT COUNT(*) AS NO_VISTOS 
FROM 
  CONTROL.TICKETS.DBO.TICKETS WITH(NOLOCK)  
WHERE  VISTO_CLIENTE = 0 AND IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDUSUARIO = <#SESSION.IDUSUARIO/>

