//[idticket|Text,c|Text,idestado|Text,idtc|Text,tkt|Text,tipousuario|Text,session.idusuario|Untyped,visto|Text,session.idproducto|Untyped,]
--UPDATE
DECLARE @IDTICKET INT, @IDRESPONSABLE INT

SELECT @IDTICKET = IDTICKET FROM CONTROL.TICKETS.DBO.TICKETS WHERE TKT = COALESCE(:IDTICKET,:TKT,'')

SELECT @IDRESPONSABLE = IDRESPONSABLE FROM CONTROL.TICKETS.DBO.TICKETS WHERE IDTICKET = @IDTICKET
IF @IDRESPONSABLE = 0
BEGIN
   SELECT TOP 1 @IDRESPONSABLE = IDUSUARIO FROM CONTROL.TICKETS.DBO.TICKET_COMENTARIOS WHERE IDTICKET = @IDTICKET AND TIPOUSUARIO = 2 ORDER BY 1 ASC
   UPDATE CONTROL.TICKETS.DBO.TICKETS SET IDRESPONSABLE = @IDRESPONSABLE WHERE IDTICKET = @IDTICKET
END

DECLARE @C INT,@IDESTADO INT, @IDTC INT, @TIPOUSUARIO INT, @VISTO INT
SET @C = ISNULL(:C,'')
SET @IDESTADO = ISNULL(:IDESTADO,'')
SET @IDTC = ISNULL(:IDTC,'')
SET @TIPOUSUARIO = ISNULL(:TIPOUSUARIO,'')
SET @VISTO = ISNULL(:VISTO,'')

EXEC CONTROL.TICKETS.DBO.SP_SOLICITAR_GERENTE @C, @IDESTADO, @IDTICKET , @IDTC, @TIPOUSUARIO , <#SESSION.IDUSUARIO/>, @VISTO, <#SESSION.IDPRODUCTO/>