//[filtroproducto|Text,filtroestado|Text,filtrousuario|Text,session.idusuario|Untyped,session.idproducto|Untyped,estatus|Text,]
--select
DECLARE @SQL VARCHAR(MAX)
DECLARE @FILTROPRODUCTO VARCHAR(MAX)
SET @FILTROPRODUCTO = ISNULL( :FILTROPRODUCTO , '')
DECLARE @FILTROESTADO VARCHAR(MAX)
SET @FILTROESTADO = ISNULL( :FILTROESTADO , '')
DECLARE @FILTROUSUARIO VARCHAR(MAX)
SET @FILTROUSUARIO = ISNULL( :FILTROUSUARIO , '')

SET @SQL = '
  DECLARE @IDUSUARIO INT
  DECLARE @IDPRODUCTO INT
  DECLARE @ESTATUS INT

  SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
  SET @IDPRODUCTO = <#SESSION.IDPRODUCTO/>
  SET @ESTATUS =  ' +  :ESTATUS + '

  SELECT COUNT(*) AS TOTALN, '''+ @FILTROPRODUCTO +'''  AS FILTROPRODUCTO ,  '''+ @FILTROESTADO+'''  AS FILTROESTADO 
  ,'''+@FILTROUSUARIO+'''  AS FILTROUSUARIO,  '''+ :ESTATUS +'''  AS ESTATUS 
  FROM CONTROL.TICKETS.DBO.TICKETS T, CONTROL.TICKETS.DBO.V_DEPARTAMENTOS VD, CONTROL.TICKETS.DBO.V_ESTADOS VE
  WHERE T.IDDEPARTAMENTO=VD.IDDEPARTAMENTO AND T.IDESTADO=VE.IDESTADO
 ' + @FILTROPRODUCTO +' '+ @FILTROESTADO  +' '+@FILTROUSUARIO
 EXEC (@SQL)