 //[session.idusuario|Untyped,session.idproducto|Untyped,estatus|Text,session.db|Untyped,]
--select
DECLARE @SQL VARCHAR(MAX)
DECLARE @FILTROESTADO VARCHAR(MAX)  
DECLARE @IDUSUARIO INT
DECLARE @IDPRODUCTO INT
DECLARE @ESTATUS INT

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPRODUCTO = <#SESSION.IDPRODUCTO/>
SET @ESTATUS =  ISNULL(:ESTATUS,'')

SET @FILTROESTADO = ''

IF @ESTATUS != 0 
BEGIN
	SET @FILTROESTADO = 'AND (T.IDESTADO = '+CAST(@ESTATUS AS VARCHAR)+')'
END


SET @SQL = '
SELECT 
REPLACE(REPLACE(CAST(DESCRIPCION AS VARCHAR(128)), ''<script'', ''&#60script''), ''<meta'', ''&#60meta'')
+ CASE WHEN LEN(CAST(DESCRIPCION AS VARCHAR(130))) > 129 THEN ''...'' ELSE '''' END
 AS DESCRIPCION, 
T.*, VD.*, VE.*, 
<#SESSION.DB/>.DBO.TIEMPO_TXT(T.FECHA_CREACION,T.FECHA_CIERRE) AS TIEMPOTERMINADO, 
<#SESSION.DB/>.DBO.TIEMPO_TXT(T.FECHA_CREACION,GETDATE()) AS TIEMPOTRANSCURRIDO 
FROM CONTROL.TICKETS.DBO.TICKETS T, CONTROL.TICKETS.DBO.V_DEPARTAMENTOS VD, CONTROL.TICKETS.DBO.V_ESTADOS VE
WHERE T.IDDEPARTAMENTO=VD.IDDEPARTAMENTO AND T.IDESTADO=VE.IDESTADO AND IDUSUARIO='+CAST(@IDUSUARIO AS VARCHAR(MAX))+'
 AND IDPRODUCTO='+CAST(@IDPRODUCTO AS VARCHAR(MAX))+'  ' + CAST(@FILTROESTADO AS VARCHAR(MAX)) + '
ORDER BY T.FECHA_ULTIMAMODIFICACION DESC'
  
EXEC (@SQL)