//[session.idempresa|Untyped,sp_host|Untyped,session.db|Untyped,]
--SELECT

DECLARE @CONFIGURACION VARCHAR(1024)
DECLARE @CONFIGURACION_LOCAL VARCHAR(1024)
DECLARE @CAMPOS_CONFIGURACION VARCHAR(1024)
DECLARE @SINCRONIZACION_TABLAS VARCHAR(2048)
DECLARE @token uniqueidentifier
DECLARE @IDEMPRESA INT
DECLARE @SERVER VARCHAR(MAX)
DECLARE @HOST VARCHAR(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @HOST='<#SP_HOST/>'
SET @token = NEWID()
SET @CONFIGURACION = '[{"Indice":"1","Tabla":"INTEGRACIONES_CLIENTES","Campos":{"CCAMPO1":"RFC","CCAMPO2":"CODIGO_CLIENTE","CCAMPO3":"","CCAMPO4":"","CCAMPO5":"","CCAMPO6":"","CCAMPO7":"","CCAMPO8":"","CCAMPO9":"","CCAMPO10":""}}]'; 
SET @CONFIGURACION_LOCAL='{"LINEAS":"25","MARCAS":"26"}' 
SET @SINCRONIZACION_TABLAS = '{"Tabla":"Lineas","valueE":"10","valueD":"1"},{"Tabla":"Marcas","valueE":"10","valueD":"1"},{"Tabla":"Listas de precio","valueE":"10","valueD":"1"},{"Tabla":"Productos","valueE":"10","valueD":"1"},{"Tabla":"Clientes","valueE":"1","valueD":"1"},{"Tabla":"Pedidos","valueE":"1","valueD":"10"}'
SET @CAMPOS_CONFIGURACION = '{"value":"1", "Opcion":"RFC"},{"value":"2", "Opcion":"CODIGO_CLIENTE"}'


SELECT @SERVER=<#SESSION.DB/>.DBO.DevuelveUrlServer(@HOST,@IDEMPRESA)

SELECT @SERVER=<#SESSION.DB/>.DBO.DevuelveUrlServer(@HOST,@IDEMPRESA)
IF NOT EXISTS(SELECT * FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE IDEMPRESA=@IDEMPRESA)
   BEGIN 
   		 INSERT INTO CONTROL.CONTROL.DBO.INTEGRACIONES(IDEMPRESA,TOKEN, SERVIDOR, CONFIGURACION, CONFIGURACION_LOCAL, CAMPOS_CONFIGURACION,ACTIVA, SINCRONIZACION_TABLAS) 
		VALUES (@IDEMPRESA, @token,@SERVER,@CONFIGURACION, @CONFIGURACION_LOCAL,@CAMPOS_CONFIGURACION, 1, @SINCRONIZACION_TABLAS)
   END
 
 	SELECT CAST(TOKEN AS VARCHAR(MAX)) as TOKEN, CASE WHEN ULTIMA_SINCRONIZACION_EXT IS NULL THEN 'nunca' ELSE CAST(ULTIMA_SINCRONIZACION_SUP AS VARCHAR(MAX)) END AS ULTIMA_SINCRONIZACION, 
	CONFIGURACION_LOCAL AS CONFIG_LOC, SINCRONIZACION_TABLAS AS SINC_TAB, CONFIGURACION AS CONFIG
	FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE IDEMPRESA=@IDEMPRESA
	
	   
	   