//[data|Text,tabla|Integer,token|Text]
--SELECT 

DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @JSON VARCHAR(MAX)
DECLARE @TABLA INT
DECLARE @DATA VARCHAR(MAX)
DECLARE @BD NVARCHAR(128)

SET @DATA = ISNULL(:DATA,'')
SET @TABLA = ISNULL(:TABLA, 0)
SET @TOKEN = ISNULL(:TOKEN, '') 


SELECT @BD=E.BD_ACTUAL FROM CONTROL.CONTROL.DBO.INTEGRACIONES I,  CONTROL.CONTROL.DBO.EMPRESAS E WHERE I.TOKEN = @TOKEN AND I.IDEMPRESA = E.IDEMPRESA

SET @JSON = SALESUP_CT.DBO.BASE64TOVARCHAR(REPLACE(@DATA,'?','')) 


DECLARE @SQL NVARCHAR(MAX)
DECLARE @PARAMDEF NVARCHAR(MAX)

INSERT INTO INTEGRACIONES.DBO.DATA_TEMP (TABLA, DATA, TOKEN) VALUES (@TABLA,@DATA,@TOKEN)

IF(@TABLA < 6)
	BEGIN 
	   SET @SQL=N'exec '+@BD+'.DBO.SP_WEBSERVICE_EXTERNO_A_SALESUP  @TOKEN, @TABLA, @JSON'
	   SET @PARAMDEF = N'@TOKEN UNIQUEIDENTIFIER, @TABLA INT, @JSON VARCHAR(MAX)'
	   EXEC sp_executesql @SQL,@PARAMDEF,@TABLA=@TABLA, @TOKEN=@TOKEN, @JSON=@JSON
	END
ELSE
	BEGIN
		 IF(@TABLA = 6)
		 BEGIN
		    	   SET @SQL=N'exec '+@BD+'.DBO.SP_WEBSERVICE_EXTERNO_A_SALESUP_INTEGRACIONES_IMPUESTOS  @TOKEN, @JSON'
	   			   SET @PARAMDEF = N'@TOKEN UNIQUEIDENTIFIER, @JSON VARCHAR(MAX)'
	   			   EXEC sp_executesql @SQL,@PARAMDEF,@TOKEN=@TOKEN, @JSON=@JSON	  	  
	   	END
		IF(@TABLA = 9)
		BEGIN
		    	   SET @SQL=N'exec '+@BD+'.DBO.SP_WEBSERVICE_EXTERNO_ACTUALIZA_CLIENTES_IDE   @TOKEN, @JSON'
	   			   SET @PARAMDEF = N'@TOKEN UNIQUEIDENTIFIER, @JSON VARCHAR(MAX)'
	   			   EXEC sp_executesql @SQL,@PARAMDEF,@TOKEN=@TOKEN, @JSON=@JSON	  	  
	   	END
				 IF(@TABLA = 10)
		BEGIN
		    	   SET @SQL=N'exec '+@BD+'.DBO.SP_WEBSERVICE_EXTERNO_ACTUALIZA_EXISTENCIAS   @TOKEN, @JSON'
	   			   SET @PARAMDEF = N'@TOKEN UNIQUEIDENTIFIER, @JSON VARCHAR(MAX)'
	   			   EXEC sp_executesql @SQL,@PARAMDEF,@TOKEN=@TOKEN, @JSON=@JSON	  	  
	   	END
	   	IF(@TABLA = 11)
		BEGIN
		    	  SET @SQL=N'exec '+@BD+'.DBO.SP_WEBSERVICE_EXTERNO_ACTUALIZA_PEDIDOS   @TOKEN, @JSON'
	   			  SET @PARAMDEF = N'@TOKEN UNIQUEIDENTIFIER, @JSON VARCHAR(MAX)'
	   			  EXEC sp_executesql @SQL,@PARAMDEF,@TOKEN=@TOKEN, @JSON=@JSON	  	  
		END
	END
