//[session.idempresa|Untyped,linea|Integer,marca|Integer,json|Text,]
--select

DECLARE @IDEMPRESA INT
DECLARE @LINEA INT
DECLARE @MARCA INT
DECLARE @CONFIG_LOCAL VARCHAR(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SET @LINEA = ISNULL(:LINEA, 25)
SET @MARCA = ISNULL(:MARCA, 26)
SET @CONFIG_LOCAL=CAST(('{"LINEAS":"'+CAST(@LINEA AS VARCHAR(128))+'","MARCAS":"'+CAST(@MARCA AS VARCHAR(128))+'"}') AS VARCHAR (128)) 




UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET CONFIGURACION_LOCAL=@CONFIG_LOCAL WHERE IDEMPRESA =@IDEMPRESA

SELECT CONFIGURACION_LOCAL AS CONFIG_LOC FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE IDEMPRESA =@IDEMPRESA
