//[session.idempresa|Untyped,session.db|Untyped,]
--select 
DECLARE @IDEMPRESA INT
DECLARE @CAMPOS_CONFIG VARCHAR(MAX)
DECLARE @JSON_PERSONALIZADOS VARCHAR(MAX)

SET @JSON_PERSONALIZADOS = ''
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


SELECT @CAMPOS_CONFIG = CAMPOS_CONFIGURACION  FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE IDEMPRESA=@IDEMPRESA


SELECT @JSON_PERSONALIZADOS = @JSON_PERSONALIZADOS+'{"value":"'+cast(indice as varchar(128))+'","Opcion":"'+ cast(NOMBRE_CAMPO as varchar)+'"},' 
FROM  <#SESSION.DB/>.dbo.empresas_campos WHERE idempresa=@IDEMPRESA AND TIPO=5
 
 
SELECT SUBSTRING(@JSON_PERSONALIZADOS, 0, LEN(@JSON_PERSONALIZADOS)) as CAMPOS_P, @CAMPOS_CONFIG AS CONFIG

