//[token|Text,]
DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ISNULL(ULTIMA_SINCRONIZACION_EXT1,0), @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN

SELECT *, CAST(FECHA_VENTA AS FLOAT) AS FECHA_VENTA_S FROM INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS IP
   JOIN INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES IC ON IC.IDI_CLIENTE=IP.IDI_CLIENTE  AND IC.IDINTEGRACION=IP.IDINTEGRACION
WHERE IP.IDINTEGRACION=@IDINTEGRACION AND IC.IDINTEGRACION=@IDINTEGRACION AND IP.FECHAHORA >= @ULTIMA_ACT

 