//[token|Text,]
DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ISNULL(ULTIMA_SINCRONIZACION_EXT1,0), @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN

SELECT PD.* 
FROM INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS_DETALLE PD, INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS P
	  JOIN INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES IC ON IC.IDI_CLIENTE=P.IDI_CLIENTE AND P.IDINTEGRACION=IC.IDINTEGRACION
WHERE PD.IDINTEGRACION=@IDINTEGRACION AND PD.IDINTEGRACION_PEDIDO = P.IDINTEGRACION_PEDIDO AND
  P.IDINTEGRACION = @IDINTEGRACION AND P.FECHAHORA >= @ULTIMA_ACT
  