//[token|Text,]
DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT
DECLARE @FECHA DATETIME

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ULTIMA_DESCARGA_PEDIDOS_DETALLE, @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN


UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_SINCRONIZACION_EXT1 = GETDATE(), ULTIMA_SINCRONIZACION_EXT = GETDATE()  WHERE TOKEN = @TOKEN

SET @FECHA = CAST(ISNULL(@ULTIMA_ACT,'') AS DATETIME)

SELECT PD.* 
FROM INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS_DETALLE PD, INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS P
	  JOIN INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES IC ON IC.IDI_CLIENTE=P.IDI_CLIENTE AND P.IDINTEGRACION=IC.IDINTEGRACION
WHERE PD.IDINTEGRACION=@IDINTEGRACION AND IC.IDINTEGRACION=@IDINTEGRACION AND PD.IDINTEGRACION_PEDIDO = P.IDINTEGRACION_PEDIDO AND
  P.IDINTEGRACION = @IDINTEGRACION AND P.FECHAHORA >= @FECHA
  

 UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_DESCARGA_PEDIDOS_DETALLE = GETDATE() WHERE TOKEN = @TOKEN
 
