//[token|Text,ts|Text,]
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @FECHA DATETIME

SET @TOKEN = :TOKEN
SET @FECHA = cast (:TS as DATETIME)


UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES 
  SET ULTIMA_SINCRONIZACION_EXT = @FECHA,ULTIMA_SINCRONIZACION_EXT1 = GETDATE()  
WHERE TOKEN = @TOKEN