//[token|Text,]
--SELECT

DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ULTIMA_SINCRONIZACION_EXT1, @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN

SELECT * FROM INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES 
WHERE ORIGEN = 1 AND IDINTEGRACION=@IDINTEGRACION AND FECHA_HORA >= @ULTIMA_ACT AND ((CODIGO_CLIENTE IS NOT NULL or CODIGO_CLIENTE != '') AND (RFC IS NOT NULL or RFC != '') )


