//[token|Text,]
-- UPDATE
DECLARE @IDINTEGRACION INT
DECLARE @BD NVARCHAR(128)


SELECT  @BD=E.BD_ACTUAL,@IDINTEGRACION=IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES I,  CONTROL.CONTROL.DBO.EMPRESAS E WHERE I.TOKEN = :TOKEN AND I.IDEMPRESA = E.IDEMPRESA


DECLARE @SQL NVARCHAR(MAX)
DECLARE @PARAMDEF NVARCHAR(MAX)


SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_COMPANIAS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_COMPANIAS'
END CATCH


SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS_LINEAS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS_LINEAS'
END CATCH

SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS_MARCAS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS_MARCAS'
END CATCH

SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_IMPUESTOS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION 
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_IMPUESTOS'
END CATCH

SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRECIOS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRECIOS '
END CATCH

SET @SQL=N'exec '+@BD+'.DBO.SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS @IDINTEGRACION'
SET @PARAMDEF = N'@IDINTEGRACION INT'
BEGIN TRY
	EXEC sp_executesql @SQL, @PARAMDEF, @IDINTEGRACION
END TRY	
BEGIN CATCH
	SELECT ERROR_MESSAGE(),'SP_INTEGRACIONES_EXTERNOS_A_SALESUP_INTEGRACIONES_PRODUCTOS'
END CATCH