//[session.idempresa|Untyped,json|Text,]
--Update

DECLARE @IDEMPRESA INT
DECLARE @CONFIGURACION VARCHAR(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


SET @CONFIGURACION= ISNULL(:json,'[{"Indice":"1","Tabla":"INTEGRACIONES_CLIENTES","Campos":{"CCAMPO1":"RFC","CCAMPO2":"CODIGO_CLIENTE","CCAMPO3":"","CCAMPO4":"","CCAMPO5":"","CCAMPO6":"","CCAMPO7":"","CCAMPO8":"","CCAMPO9":"","CCAMPO10":""}}]')

set @CONFIGURACION = SALESUP_CT.DBO.BASE64TOVARCHAR(@CONFIGURACION)


UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET CONFIGURACION=@CONFIGURACION WHERE IDEMPRESA =@IDEMPRESA

--SELECT CONFIGURACION AS CONFIGURACION FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE IDEMPRESA =@IDEMPRESA
