//[token|Text,]
--SELECT

DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT
DECLARE @FECHA DATETIME

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ULTIMA_DESCARGA_CLIENTES, @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN

SET @FECHA = CAST(ISNULL(@ULTIMA_ACT,'') AS DATETIME)

SELECT  IDE_CLIENTE, CODIGO_CLIENTE, NOMBRE_COMERCIAL, RAZON_SOCIAL, RFC, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, COLONIA, CODIGO_POSTAL, PAIS, ESTADO, CIUDAD, MUNICIPIO, NOMBRE, EMAIL, TELEFONO1, TELEFONO2, DIRECCIONWEB
 FROM INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES 
WHERE ORIGEN = 1 AND IDINTEGRACION=@IDINTEGRACION AND FECHA_HORA >= @FECHA  AND ((CODIGO_CLIENTE IS NOT NULL or CODIGO_CLIENTE != '') AND (RFC IS NOT NULL or RFC != '') )

UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_DESCARGA_CLIENTES = GETDATE() WHERE TOKEN = @TOKEN

UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_SINCRONIZACION_EXT1 = GETDATE(), ULTIMA_SINCRONIZACION_EXT = GETDATE()  WHERE TOKEN = @TOKEN

