//[token|Text,]
DECLARE @ULTIMA_ACT DATETIME
DECLARE @TOKEN UNIQUEIDENTIFIER
DECLARE @IDINTEGRACION INT
DECLARE @FECHA DATETIME

SET @TOKEN = :TOKEN

SELECT @ULTIMA_ACT = ULTIMA_DESCARGA_CLIENTES, @IDINTEGRACION = IDINTEGRACION 
FROM CONTROL.CONTROL.DBO.INTEGRACIONES WHERE TOKEN = @TOKEN

UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_SINCRONIZACION_EXT1 = GETDATE(), ULTIMA_SINCRONIZACION_EXT = GETDATE()  WHERE TOKEN = @TOKEN

SET @FECHA = CAST(ISNULL(@ULTIMA_ACT,'') AS DATETIME)


SELECT *, CAST(FECHA_VENTA AS FLOAT) AS FECHA_VENTA_S FROM INTEGRACIONES.DBO.INTEGRACIONES_PEDIDOS IP
   JOIN INTEGRACIONES.DBO.INTEGRACIONES_CLIENTES IC ON IC.IDI_CLIENTE=IP.IDI_CLIENTE   AND IC.IDINTEGRACION=IP.IDINTEGRACION
WHERE IP.IDINTEGRACION=@IDINTEGRACION AND IC.IDINTEGRACION=@IDINTEGRACION AND IP.FECHAHORA >= @ULTIMA_ACT

UPDATE CONTROL.CONTROL.DBO.INTEGRACIONES SET ULTIMA_DESCARGA_CLIENTES = GETDATE() WHERE TOKEN = @TOKEN
 
