//[session.idusuario|Untyped,session.idempresa|Untyped,idpantalla|Integer,session.db|Untyped,]
--select

DECLARE @ORDERSQL VARCHAR(MAX)
DECLARE @IDPANTALLA INT, @IDUSUARIO INT, @IDEMPRESA INT

SET @ORDERSQL = ''
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
		
SELECT @ORDERSQL = UC.ORDERSQL 
FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC 
JOIN <#SESSION.DB/>.DBO.USUARIOS U ON U.IDUSUARIO = UC.IDUSUARIO AND U.IDEMPRESA = @IDEMPRESA
WHERE UC.ORDENAPOR IS NOT NULL AND UC.IDUSUARIO = @IDUSUARIO AND UC.IDPANTALLA = @IDPANTALLA

IF(@IDPANTALLA=27)
BEGIN
	 SET @ORDERSQL = REPLACE(@ORDERSQL, 'ORDER BY ','')
	 SET @ORDERSQL = REPLACE(@ORDERSQL, ' ',',')
	 SELECT SPLITVALUE AS ORDENAMIENTO FROM <#SESSION.DB/>.DBO.SPLIT(@ORDERSQL,',') WHERE SPLITVALUE <> ''
END
ELSE
BEGIN
	 SELECT @ORDERSQL AS OrderSql
END
