//[session.idusuario|Untyped,session.idempresa|Untyped,idventana|Integer,session.db|Untyped,]
--select 
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT, @IDPANTALLA INT, @IDEMPRESA INT, @VERPROSPECTOS INT, @VERVENTAS INT, @VEREMPRESA INT
DECLARE @VIZUALIZAREN VARCHAR(MAX)
DECLARE @TB TABLE (Id INT, Tipo INT, Columna VARCHAR(MAX), OrdenaPor VARCHAR(MAX), MODULO VARCHAR(12))

SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDPANTALLA = ISNULL(:IDVENTANA,0)

SET @VIZUALIZAREN = ''

SET @VEREMPRESA = 1
SET @VERPROSPECTOS = 0
SET @VERVENTAS = 0

IF @IDPANTALLA = 1 OR @IDPANTALLA = 4 BEGIN SET @VERPROSPECTOS = 1 END
IF @IDPANTALLA = 2 OR @IDPANTALLA = 3 BEGIN SET @VERVENTAS = 1 SET @VERPROSPECTOS = 1 END

IF @IDPANTALLA = 1 BEGIN SET @VIZUALIZAREN = '1' END
IF @IDPANTALLA = 4 BEGIN SET @VIZUALIZAREN = '1,3' END

IF @IDPANTALLA = 2 BEGIN SET @VIZUALIZAREN = '1,2' END
IF @IDPANTALLA = 3 BEGIN SET @VIZUALIZAREN = '1,4' END


INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT UC.IdUsuarioColumna, 1, C.Columna,
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,
ISNULL(CAST(C.MODULO AS VARCHAR(12)),'') AS MODULO 
FROM SALESUP_CT.DBO.COLUMNAS C 
JOIN <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC ON UC.IDCOLUMNA = C.IDCOLUMNA AND UC.IDUSUARIO = @IDUSUARIO AND C.IDPANTALLA = UC.IDPANTALLA
WHERE C.ORDENAR = 1 AND C.IDPANTALLA = @IDPANTALLA
ORDER BY C.COLUMNA


INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT UC.IDUSUARIOCOLUMNA , 2, NOMBRE_CAMPO,
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,''  
FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC 
LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC ON UC.IDCAMPO = EC.IDCAMPO AND EC.IDEMPRESA = @IDEMPRESA AND (EC.TIPO IN (SELECT SPLITVALUE FROM DBO.SPLIT(@VIZUALIZAREN,',')) OR EC.COMPARTIR IN (SELECT SPLITVALUE FROM DBO.SPLIT(@VIZUALIZAREN,',')))
WHERE UC.IDUSUARIO = @IDUSUARIO  AND UC.IDPANTALLA = @IDPANTALLA AND EC.IDCAMPO IS NOT NULL
ORDER BY NOMBRE_CAMPO

INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT 
UC.IDUSUARIOCOLUMNA, 3, (SELECT SPLITVALUE FROM SALESUP_CT.DBO.SPLIT(CAT.CATALOGO,'/') WHERE OCCURENCEID = 1) , 
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,''
FROM <#SESSION.DB/>.dbo.USUARIOS_COLUMNAS UC 
LEFT JOIN <#SESSION.DB/>.dbo.CATALOGOS CAT ON CAT.IDEMPRESA = @IDEMPRESA AND CAT.IDCATALOGO = UC.IDCATALOGO AND (CAT.VERPROSPECTOS = @VERPROSPECTOS OR CAT.VEREMPRESA = 1) AND (CAT.VERVENTAS = @VERVENTAS OR CAT.VEREMPRESA = 1 OR CAT.VERPROSPECTOS = @VERPROSPECTOS) AND CAT.STATUS = 1
WHERE UC.IDUSUARIO = @IDUSUARIO AND UC.VISIBLE = 1 AND UC.IDPANTALLA = @IDPANTALLA AND CAT.IDCATALOGO IS NOT NULL
ORDER BY cat.catalogo

INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT UC.IDUSUARIOCOLUMNA , 4, NOMBRE,
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,''  
FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC 
LEFT JOIN <#SESSION.DB/>.DBO.LISTAS_PRECIO LP ON UC.IDLISTA_PRECIO = LP.IDLISTA_PRECIO AND LP.IDEMPRESA = @IDEMPRESA AND LP.STATUS =1
WHERE UC.IDUSUARIO = @IDUSUARIO  AND UC.IDPANTALLA = @IDPANTALLA AND LP.IDLISTA_PRECIO IS NOT NULL
ORDER BY NOMBRE

INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT UC.IDUSUARIOCOLUMNA , 5, IMPUESTO,
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,''  
FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC 
LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_IMPUESTOS IM ON UC.IDIMPUESTO = IM.IDIMPUESTO AND IM.IDEMPRESA = @IDEMPRESA AND IM.STATUS =1
WHERE UC.IDUSUARIO = @IDUSUARIO  AND UC.IDPANTALLA = @IDPANTALLA AND IM.IDIMPUESTO IS NOT NULL
ORDER BY IMPUESTO

INSERT @TB (ID, TIPO, COLUMNA, ORDENAPOR,MODULO)
SELECT UC.IDUSUARIOCOLUMNA , 6, DESCRIPCION,
CASE WHEN UC.OrdenaPor IS NOT NULL THEN CAST( UC.OrdenaPor AS VARCHAR(MAX)) ELSE '' END AS OrdenaPor,''  
FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS UC 
LEFT JOIN <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES COM ON UC.IDCOMISION = COM.IDPRODUCTO_COMISION AND COM.IDEMPRESA = @IDEMPRESA AND COM.STATUS =1
WHERE UC.IDUSUARIO = @IDUSUARIO  AND UC.IDPANTALLA = @IDPANTALLA AND COM.IDPRODUCTO_COMISION IS NOT NULL
ORDER BY DESCRIPCION

SELECT * FROM @TB


