//[controlorder|Text,clave|Text,idpantalla|Integer,session.db|Untyped,session.idusuario|Untyped,]
-- SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @CONTROLORDER VARCHAR(1000)
DECLARE @CLAVE VARCHAR(1000)
DECLARE @IDPANTALLA VARCHAR(1000)
SET @CONTROLORDER=ISNULL(:CONTROLORDER,'')
SET @CLAVE =  ISNULL(:CLAVE,'')
SET @IDPANTALLA = CAST(ISNULL(:IDPANTALLA,0) AS VARCHAR(1000))

SET @SQL='
IF ('''+@CONTROLORDER+'''=''0'')
BEGIN;
	 SELECT ''ASC'' AS ORDEN,1 AS CAMPO,1 AS NUMERO_COLUMNA, 1 AS BANDERA 
END;
ELSE
BEGIN;
SELECT CASE WHEN DEFAULT_O_'+@CLAVE+'<0 THEN ''DESC'' ELSE ''ASC'' END AS ORDEN,
PC.CAMPO AS CAMPO, PC.NUMERO_COLUMNA, ABS(DEFAULT_O_'+@CLAVE+') AS BANDERA  
 FROM <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS AS UD 
 JOIN <#SESSION.DB/>.DBO.PANTALLAS_COLUMNAS PC
 ON ABS(DEFAULT_O_'+@CLAVE+')= PC.NUMERO_COLUMNA
 WHERE UD.IDUSUARIO=<#SESSION.IDUSUARIO/> AND PC.IDPANTALLA='+@IDPANTALLA+'
END;'
EXEC (@SQL)
