//[]
--SELECT
DECLARE @SQL VARCHAR(MAX)
SET @SQL='IF EXISTS (SELECT * FROM sysobjects WHERE name=''VERSION'') SELECT (''versión: ''+VERSION) as version FROM VERSION ELSE SELECT '''' AS VERSION '
EXEC (@SQL)
