//[session.idusuario|Untyped,idpantalla|Integer,filtroagrupardetalle|Integer,session.db|Untyped,]
--SELECT


DECLARE @IDPANTALLA INT, @IDUSUARIO INT 
DECLARE @FILTROAGRUPARDETALLE INT 

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDPANTALLA = ISNULL(:idpantalla,0)
SET @FILTROAGRUPARDETALLE= ISNULL(:FILTROAGRUPARDETALLE, 0) 



SELECT * FROM 
(SELECT U.IDUSUARIO,CAST( U.TKU AS VARCHAR(MAX)) AS TKU, U.IDGRUPO, U.IDEMPRESA,
case when isnull(U.APELLIDOS,'') = '' then '' else U.APELLIDOS+', ' end +
case when isnull(U.NOMBRE,'') = '' then '' else U.NOMBRE end +
case when isnull(U.INICIALES,'') = '' then '' else '('+U.INICIALES+')' end as   NOMBRE_COMPLETO,NOMBRE, APELLIDOS, @FILTROAGRUPARDETALLE AS FILTRODETALLE, @FILTROAGRUPARDETALLE AS FILTROAGRUPARDETALLE, 1 AS ES_USUARIO

FROM <#SESSION.DB/>.DBO.USUARIOS U,<#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0) M
WHERE U.IDUSUARIO=M.ID 
UNION ALL
SELECT IDUSUARIOGRUPO AS IDUSUARIO, CAST(UG.TK AS VARCHAR(MAX)) AS TKU, UG.IDUSUARIOGRUPO AS IDGRUPO, UG.IDEMPRESA, UG.GRUPO AS NOMBRE_COMPLETO, UG.GRUPO AS NOMBRE, '' AS APELLIDOS, 0 AS FILTRODETALLE, 0 AS FILTROAGRUPARDETALLE, 0 AS ES_USUARIO  
FROM <#SESSION.DB/>.dbo.USUARIOS_GRUPOS UG  WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>
)
 AS LISTA ORDER BY ES_USUARIO ASC, LISTA.NOMBRE_COMPLETO
