//[session.db|Untyped,session.idusuario|Untyped,]
SELECT ARCHIVO, RUTA, U.IDCSS , U.FONDO, U.CAMBIARFONDO
FROM <#SESSION.DB/>.DBO.ESTILOS E,<#SESSION.DB/>.DBO.USUARIOS U 
WHERE U.IDCSS=E.IDCSS AND U.IDUSUARIO=<#SESSION.IDUSUARIO/>
