//[session.idempresa|Untyped,idcampo|Integer,session.db|Untyped,]
--DELETE

DECLARE @VENTANA INT, @COMPARTIR INT, @IDEMPRESA INT, @IDCAMPO INT
DECLARE @INDICE VARCHAR(12), @SQLTXT VARCHAR(MAX)

SET @SQLTXT = ''

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDCAMPO = ISNULL(:IDCAMPO,0)

SELECT @VENTANA = TIPO, @COMPARTIR = COMPARTIR, @INDICE = CAST(INDICE AS VARCHAR(12)) FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WITH(NOLOCK) WHERE IDCAMPO = @IDCAMPO

IF @VENTANA IN (1,3)
BEGIN
	 SET @SQLTXT = 'UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET CAMPO'+@INDICE+' = NULL WHERE IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(20))
	 EXEC(@SQLTXT)
END


IF @VENTANA IN (2,4)
BEGIN
	SET @SQLTXT = 'UPDATE O WITH(ROWLOCK) SET O.CAMPO'+@INDICE+' = NULL '
	SET @SQLTXT = @SQLTXT + 'FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O '
	SET @SQLTXT = @SQLTXT + 'JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO '
	SET @SQLTXT = @SQLTXT + 'WHERE P.IDEMPRESA = ' + CAST(@IDEMPRESA AS VARCHAR(20))
	EXEC(@SQLTXT)
END

DELETE FROM <#SESSION.DB/>.DBO.USUARIOS_COLUMNAS WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO
DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO
DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS WITH(ROWLOCK) WHERE IDCAMPO = @IDCAMPO

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WITH(ROWLOCK) WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES WITH(ROWLOCK) (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE())

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK) (IDTABLA,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (22, @IDCAMPO, 1, @IDEMPRESA, GETDATE())