//[session.idempresa|Untyped,orden|Text,idcampo|Text,naturaleza|Text,taboriginal|Integer,session.db|Untyped,]
--UPDATE

DECLARE @IDEMPRESA AS INT
DECLARE @ORDEN VARCHAR(MAX)
DECLARE @IDCAMPOS VARCHAR(MAX)
DECLARE @NATURALEZA VARCHAR(MAX)
DECLARE @TABORIGINAL INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @ORDEN = ISNULL(:ORDEN,'')  
SET @IDCAMPOS = ISNULL(:IDCAMPO,'')
SET @NATURALEZA = ISNULL(:NATURALEZA, '')
SET @TABORIGINAL=ISNULL(:TABORIGINAL, 0)

UPDATE EC SET EC.ORDEN = O.SPLITVALUE
FROM SALESUP_CT.DBO.SPLIT(@ORDEN,',') O
JOIN SALESUP_CT.DBO.SPLIT(@IDCAMPOS,',') ID ON ID.OCCURENCEID = O.OCCURENCEID
JOIN SALESUP_CT.DBO.SPLIT(@NATURALEZA,',') N ON N.OCCURENCEID = ID.OCCURENCEID AND N.SPLITVALUE = 1
JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION EC ON EC.IDCAMPOCON = ID.SPLITVALUE AND EC.IDEMPRESA = @IDEMPRESA AND O.SPLITVALUE != EC.ORDEN


UPDATE EC SET EC.ORDEN = O.SPLITVALUE
FROM SALESUP_CT.DBO.SPLIT(@ORDEN,',') O
JOIN SALESUP_CT.DBO.SPLIT(@IDCAMPOS,',') ID ON ID.OCCURENCEID = O.OCCURENCEID
JOIN SALESUP_CT.DBO.SPLIT(@NATURALEZA,',') N ON N.OCCURENCEID = ID.OCCURENCEID AND N.SPLITVALUE = 2
JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC ON EC.IDCAMPO = ID.SPLITVALUE AND EC.IDEMPRESA = @IDEMPRESA AND O.SPLITVALUE != EC.ORDEN AND EC.IDTAB=@TABORIGINAL 


UPDATE EC SET EC.TAMBIENEN_ORDEN = O.SPLITVALUE
FROM SALESUP_CT.DBO.SPLIT(@ORDEN,',') O
JOIN SALESUP_CT.DBO.SPLIT(@IDCAMPOS,',') ID ON ID.OCCURENCEID = O.OCCURENCEID
JOIN SALESUP_CT.DBO.SPLIT(@NATURALEZA,',') N ON N.OCCURENCEID = ID.OCCURENCEID AND N.SPLITVALUE = 2
JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS EC ON EC.IDCAMPO = ID.SPLITVALUE AND EC.IDEMPRESA = @IDEMPRESA AND O.SPLITVALUE != EC.TAMBIENEN_ORDEN AND EC.IDTAB!=@TABORIGINAL
