//[session.idempresa|Untyped,idventana|Integer,ventanas|Text,session.db|Untyped,]
--SELECT 
DECLARE @VENTANAS VARCHAR(MAX)
DECLARE @IDEMPRESA AS INT, @IDVENTANA AS INT 

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDVENTANA = CAST (ISNULL(:IDVENTANA,0) AS INT)
SET @VENTANAS = ISNULL(:VENTANAS,'')

SELECT IDTAB, NOMBRE AS TAB, ICONO, TAB_DEFAULT AS tabF , IDVENTANA, CAST(TKTAB AS VARCHAR(256)) AS TKTAB
FROM <#SESSION.DB/>.DBO.EMPRESAS_TABS
WHERE IDEMPRESA = @IDEMPRESA AND IDVENTANA = @IDVENTANA
ORDER BY ORDEN ASC