//[session.idempresa|Untyped,idtab|Integer,nombre|Text,icono|Text,session.db|Untyped,tktab|Text,]
DECLARE @IDEMPRESA INT
DECLARE @IDTAB INT
DECLARE @NOMBRE VARCHAR(MAX)
DECLARE @ICONO VARCHAR(MAX)
DECLARE @TKTAB VARCHAR(256) 

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDTAB = CAST(ISNULL(:IDTAB,0) AS INT)
SET @NOMBRE = ISNULL(:NOMBRE,'')
SET @ICONO = ISNULL(:ICONO,'')

UPDATE <#SESSION.DB/>.DBO.EMPRESAS_TABS
SET NOMBRE = @NOMBRE, 
ICONO = @ICONO
WHERE IDEMPRESA = @IDEMPRESA
AND IDTAB = @IDTAB
