//[session.idempresa|Untyped,idtab|Integer,session.db|Untyped,]
--DELETE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDEMPRESA INT, @IDTAB INT

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDTAB = ISNULL(:IDTAB,0)

DELETE <#SESSION.DB/>.DBO.EMPRESAS_TABS
WHERE IDEMPRESA = @IDEMPRESA
AND IDTAB = @IDTAB