//[session.idempresa|Untyped,idventana|Integer,nombretab|Text,icono|Text,session.db|Untyped,]
-- INSERT

DECLARE @IDEMPRESA  INT
DECLARE @IDVENTANA  INT
DECLARE @NOMBRETAB VARCHAR(MAX)
DECLARE @ICONO VARCHAR(MAX)
DECLARE @ORDEN INT

SET @IDEMPRESA =CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDVENTANA =ISNULL(:IDVENTANA,0)
SET @NOMBRETAB =ISNULL(:NOMBRETAB,'')
SET @ICONO =ISNULL(:ICONO,'')

SELECT @ORDEN = MAX(ORDEN) FROM <#SESSION.DB/>.DBO.EMPRESAS_TABS WHERE IDEMPRESA = @IDEMPRESA AND IDVENTANA=@IDVENTANA 

IF @ORDEN IS NULL BEGIN SET @ORDEN = 0 END
SET @ORDEN = @ORDEN+1 

INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_TABS 
(IDEMPRESA, IDVENTANA, NOMBRE, ORDEN, ICONO)
VALUES
(@IDEMPRESA, @IDVENTANA, @NOMBRETAB, @ORDEN,@ICONO)