//[session.db|Untyped,session.idusuario|Untyped,tku|Text,tipo|Integer,]
DECLARE @TKU VARCHAR(128)
DECLARE @TIPO INT

SET @TKU = ISNULL(:TKU,'')
SET @TIPO = ISNULL(:TIPO, 0)


IF(@TIPO = 0)
BEGIN
SELECT U.* /*U.NOMBRE, U.EMAIL, U.APELLIDOS, U.INICIALES*/, V.ZONA, E.ESTADO, P.PAIS
FROM <#SESSION.DB/>.DBO.USUARIOS U 
LEFT JOIN  <#SESSION.DB/>.DBO.V_GMT V  ON V.GMT=U.GMT
LEFT JOIN  <#SESSION.DB/>.DBO.ESTADOS E ON U.DEFAULT_ESTADO=E.IDESTADO AND U.DEFAULT_PAIS=E.IDPAIS
LEFT JOIN  <#SESSION.DB/>.DBO.PAISES  P  ON U.DEFAULT_PAIS=P.IDPAIS
WHERE U.IDUSUARIO=<#SESSION.IDUSUARIO/> AND U.IDEMPRESA = <#SESSION.IDEMPRESA/>
END
ELSE
BEGIN
SELECT U.* /*U.NOMBRE, U.EMAIL, U.APELLIDOS, U.INICIALES*/, V.ZONA, E.ESTADO, P.PAIS
FROM <#SESSION.DB/>.DBO.USUARIOS U 
LEFT JOIN  <#SESSION.DB/>.DBO.V_GMT V  ON V.GMT=U.GMT
LEFT JOIN  <#SESSION.DB/>.DBO.ESTADOS E ON U.DEFAULT_ESTADO=E.IDESTADO AND U.DEFAULT_PAIS=E.IDPAIS
LEFT JOIN  <#SESSION.DB/>.DBO.PAISES  P  ON U.DEFAULT_PAIS=P.IDPAIS
WHERE U.TKU=@TKU AND U.IDEMPRESA = <#SESSION.IDEMPRESA/>
 
END
