//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SELECT 'CP-'+cast(INDICE as varchar(max))as Id, 
IDCAMPO AS IdCampoPer,
Nombre_Campo AS Campo ,
'CAMPO'+ cast(INDICE as varchar(max)) AS Nombre,

CASE WHEN INDICE BETWEEN 21 AND 25 THEN '1' END AS EsSelect,
CASE WHEN NOT(INDICE BETWEEN 21 AND 25) THEN '1' END AS EsInput,
CASE
    WHEN INDICE BETWEEN 1 AND 4 THEN '1'
    WHEN INDICE BETWEEN 5 AND 8 THEN '2'
    WHEN INDICE BETWEEN 9 AND 12 THEN '3'
    WHEN ( (INDICE BETWEEN 13 AND 20)  OR (INDICE BETWEEN 26 AND 32)  )  THEN '4'
    WHEN INDICE BETWEEN 21 AND 25 THEN '5'
    END AS TipoDato, *
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS WHERE IDEMPRESA = @IDEMPRESA
AND (TIPO = 1 OR COMPARTIR = 1) AND TIPO_CAMPO NOT IN (3,4,6,7,8,9)
ORDER BY LLAVE DESC, NOMBRE_CAMPO 
