//[session.idempresa|Untyped,session.idusuario|Untyped,tkmc|Text,session.db|Untyped,]
--UPDATE
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @TKMC VARCHAR(max)

SET @TKMC = :tkmc
UPDATE <#SESSION.DB/>.dbo.USUARIOS SET TKMC = @TKMC WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIO = @IDUSUARIO

