//[session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SELECT tkmc as Config FROM <#SESSION.DB/>.dbo.USUARIOS WHERE IDEMPRESA = @IDEMPRESA AND IDUSUARIO = @IDUSUARIO

