//[session.idempresa|Untyped,]
--select 
DECLARE @MODULOS VARCHAR(128)
DECLARE @MODULOS_V VARCHAR(128)
SET @MODULOS = ''
SET @MODULOS_V =''


SELECT 
  @MODULOS = @MODULOS + CAST(M.IDMODULO AS VARCHAR(32))+',',
  @MODULOS_V = @MODULOS_V + CAST(CASE WHEN  STATUS > 0 AND (M.STATUS = 2 OR ME.IDEMPRESA IS NOT NULL) THEN 1 ELSE 0 END  AS VARCHAR(32))+ ','
FROM 
  CONTROL.CONTROL.DBO.MODULOS M
  LEFT JOIN CONTROL.CONTROL.DBO.MODULOS_EMPRESAS ME ON M.IDMODULO = ME.IDMODULO AND ME.IDEMPRESA = <#SESSION.IDEMPRESA/>
  
  SELECT @MODULOS AS MODULOS, @MODULOS_V AS MODULOS_V

 