//[adicional_otros|Text,session.idempresa|Untyped,session.db|Untyped,ltidusuarios|Text,ltidgrupos|Text,idempresanotificacion|Integer,]
--update
DECLARE @IDEMPRESA INT

DECLARE @ADICIONAL_TIPO INT
DECLARE @ADICIONAL_IDUSUARIOS VARCHAR(128)
DECLARE @ADICIONAL_IDGRUPOS VARCHAR(128)
DECLARE @ADICIONAL_OTROS VARCHAR(256)
SET @ADICIONAL_IDUSUARIOS = ''
SET @ADICIONAL_IDGRUPOS = ''

  SET @ADICIONAL_OTROS  = ISNULL(:ADICIONAL_OTROS,'')
  SET  @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
 SELECT @ADICIONAL_IDUSUARIOS = @ADICIONAL_IDUSUARIOS + CAST(IDUSUARIO AS VARCHAR(5))+',' FROM  <#SESSION.DB/>.dbo.USUARIOS WHERE IDEMPRESA = @IDEMPRESA AND
   (
     IDUSUARIO IN (SELECT SplitValue FROM <#SESSION.DB/>.dbo.Split(ISNULL(:LtIdUsuarios,''),','))
   )
 SELECT @ADICIONAL_IDGRUPOS = @ADICIONAL_IDGRUPOS + CAST(IDUSUARIOGRUPO AS VARCHAR(5))+',' FROM  <#SESSION.DB/>.dbo.USUARIOS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA AND
   (
     IDUSUARIOGRUPO   IN (SELECT SplitValue FROM <#SESSION.DB/>.dbo.Split(ISNULL(:LtIdGrupos,''),',')) 
   )

 
UPDATE  <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG SET 
  ADICIONAL_IDUSUARIOS = @ADICIONAL_IDUSUARIOS,
  ADICIONAL_IDGRUPOS = @ADICIONAL_IDGRUPOS,
  ADICIONAL_OTROS = @ADICIONAL_OTROS
WHERE IDEMPRESANOTIFICACION = ISNULL(:IDEMPRESANOTIFICACION,0)

--SELECT @ADICIONAL_IDUSUARIOS,@ADICIONAL_IDGRUPOS

