//[aidsuceso|Integer,session.idempresa|Untyped,session.db|Untyped,]
--UPDATE
DECLARE @IDSUCESO INT
DECLARE @IDEMPRESA INT

SET @IDSUCESO   = CAST(ISNULL(:aIDSUCESO,0) AS INT)
SET @IDEMPRESA  = CAST('<#SESSION.IDEMPRESA/>' AS INT)

UPDATE E SET
 E.ASUNTO = N.ASUNTO, E.CUERPO = N.CUERPO, E.SMS = N.SMS
FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG E,
 SALESUP_CT.dbo.NOTIFICACIONES N 
 WHERE E.IDSUCESo = @IDSUCESO AND E.IDEMPRESa = @IDEMPRESA AND E.IDSUCESO = N.IDSUCESO

