//[suceso|Text,session.idempresa|Untyped,session.db|Untyped,campo|Text,valor|Text,]
--update
DECLARE @IDSUCESO INT
DECLARE @IDEMPRESA INT
DECLARE @CAMPO VARCHAR(MAX)
DECLARE @VALOR VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)

SET  @IDSUCESO = CAST(ISNULL(:SUCESO,'') AS INT)
SET  @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET  @CAMPO = ISNULL(:CAMPO,'')
SET  @VALOR = ISNULL(:VALOR,'')


SET @SQL='

IF (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG WHERE  IDEMPRESA =  '+CAST(@IDEMPRESA AS VARCHAR(1000))+' AND IDSUCESO = '+CAST(@IDSUCESO AS VARCHAR(1000))+') = 0
INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG (IDEMPRESA, IDNOTIFICACION,IDSUCESO, ASUNTO, CUERPO, SMS, NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, NOTIFICA_PUSH, IDTIPODESTINATARIO)
SELECT '+CAST(@IDSUCESO AS VARCHAR(1000))+', IDNOTIFICACION,IDSUCESO, ASUNTO, CUERPO, SMS, NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, NOTIFICA_PUSH,1 FROM SALESUP_CT.dbo.NOTIFICACIONES WHERE IDSUCESO = '+CAST(@IDSUCESO AS VARCHAR(1000))+'

UPDATE  <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG SET '+@CAMPO+' = '+@VALOR+'
WHERE IDSUCESO = '+CAST(@IDSUCESO AS VARCHAR(1000))+' AND IDEMPRESA =  '+CAST(@IDEMPRESA AS VARCHAR(1000))+'

 INSERT INTO   <#SESSION.DB/>.dbo.USUARIOS_NOTIFICACION_CONFIG (IDUSUARIO, IDEMPRESANOTIFICACION, NOTIFICA_ALERTA, NOTIFICA_EMAIL, NOTIFICA_PUSH, NOTIFICA_SMS )
 SELECT US.IDUSUARIO,E.IDEMPRESANOTIFICACION, E.NOTIFICA_ALERTA, E.NOTIFICA_EMAIL, E.NOTIFICA_PUSH, E.NOTIFICA_SMS 
 FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG E
 LEFT  JOIN  <#SESSION.DB/>.dbo.USUARIOS_NOTIFICACION_CONFIG U ON E.IDEMPRESANOTIFICACION = U.IDEMPRESANOTIFICACION
 CROSS JOIN <#SESSION.DB/>.dbo.USUARIOS US 
 WHERE E.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+'  AND US.IDEMPRESA = E.IDEMPRESA
 AND U.IDUSUARIONOTIFICACION IS NULL
 
  
 UPDATE U  SET  '+@CAMPO+' = E.'+@CAMPO+'
 FROM 
   <#SESSION.DB/>.dbo.USUARIOS_NOTIFICACION_CONFIG U JOIN 
   <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG E ON IDSUCESO = '+CAST(@IDSUCESO AS VARCHAR(1000))+' AND E.IDEMPRESANOTIFICACION = U.IDEMPRESANOTIFICACION
 AND E.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+'

 '
 
 EXEC (@SQL)
