//[idsuceso|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
/*PROTEGIDO*/

DECLARE @IDSUCESO INT
DECLARE @IDEMPRESA INT

SET  @IDSUCESO = ISNULL(:IDSUCESO, 0)
SET  @IDEMPRESA =CAST('<#SESSION.IDEMPRESA/>' AS INT)

IF (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG EC WHERE IDEMPRESA = @IDEMPRESA AND IDSUCESO = @IDSUCESO)=0
BEGIN
 INSERT INTO  <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG (IDEMPRESA, idsuceso, IDNOTIFICACION, idtipodestinatario, ASUNTO, CUERPO, SMS,   NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, notifica_push)
 SELECT  @IDEMPRESA, IDSUCESO,idnotificacion, idtipodestinatario, ASUNTO, CUERPO, SMS,   NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, notifica_push 
 FROM SALESUP_CT.DBO.NOTIFICACIONES WHERE IDSUCESO = @IDSUCESO
END

SELECT 1, LEN(E.ASUNTOAD) TIENEAD,
 REPLACE ( 'U'+ADICIONAL_IDUSUARIOS, ',', ',U') AS USUARIOS,
 REPLACE ( 'G'+ADICIONAL_IDGRUPOS, ',', ',G') AS GRUPOS,
 ADICIONAL_OTROS,
  E.* FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG E JOIN
  SALESUP_CT.DBO.NOTIFICACIONES N ON N.IDNOTIFICACION = E.IDNOTIFICACION 
  WHERE IDEMPRESA = @IDEMPRESA AND E.IDSUCESO = @IDSUCESO 

