//[titulo|Text,contenido|Text,tituload|Text,contenidoad|Text,sms|Text,suceso|Integer,session.idempresa|Untyped,session.db|Untyped,ltidusuarios|Text,ltidgrupos|Text,adicional_otros|Text,idempresanotificacion|Integer,paraquienad|Text,usrnuevo|Text,]
--update
DECLARE @IDSUCESO INT
DECLARE @IDEMPRESA INT

DECLARE @ASUNTO VARCHAR(MAX)
DECLARE @CUERPO  VARCHAR(MAX)
DECLARE @ASUNTOAD VARCHAR(MAX)
DECLARE @CUERPOAD  VARCHAR(MAX)
DECLARE @SMS  VARCHAR(MAX)
DECLARE @ADICIONAL_TIPO INT
DECLARE @ADICIONAL_IDUSUARIOS VARCHAR(128)
DECLARE @ADICIONAL_IDGRUPOS VARCHAR(128)
DECLARE @ADICIONAL_OTROS VARCHAR(256)
DECLARE @LTIDUSUARIOS VARCHAR(MAX)
DECLARE @LTIDGRUPOS VARCHAR(MAX) 
DECLARE @IDEMPRESANOTIFICACION INT 
DECLARE @DESTINOADD VARCHAR(256)
DECLARE @USRNUEVO VARCHAR(128)


SET  @ASUNTO = ISNULL(:TITULO, '') 
SET  @CUERPO = ISNULL(:CONTENIDO, '') 
SET  @ASUNTOAD = ISNULL(:TITULOAD, '') 
SET  @CUERPOAD = ISNULL(:CONTENIDOAD, '') 
SET  @SMS = ISNULL(:SMS, '')
SET  @IDSUCESO = ISNULL (:SUCESO, 0)  
SET  @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

IF (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG WHERE  IDEMPRESA =  @IDEMPRESA AND IDSUCESO = @IDSUCESO) = 0
 BEGIN 
    INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG (IDEMPRESA, IDNOTIFICACION,IDSUCESO, ASUNTO, CUERPO, SMS, NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, NOTIFICA_PUSH, IDTIPODESTINATARIO, ASUNTOAD, CUERPOAD)
    SELECT @IDEMPRESA, IDNOTIFICACION,IDSUCESO, ASUNTO, CUERPO, SMS, NOTIFICA_EMAIL, NOTIFICA_SMS, NOTIFICA_ALERTA, NOTIFICA_PUSH,1, ASUNTOAD, CUERPOAD 
    FROM SALESUP_CT.dbo.NOTIFICACIONES WHERE IDSUCESO = @IDSUCESO
 END 
ELSE 
 BEGIN 
  SET @ADICIONAL_IDUSUARIOS = ''
  SET @ADICIONAL_IDGRUPOS = ''
  SET @LTIDUSUARIOS= ISNULL(:LTIDUSUARIOS , '')
  SET @LTIDGRUPOS =ISNULL(:LTIDGRUPOS, '')
  SET @ADICIONAL_OTROS  = ISNULL(:ADICIONAL_OTROS, '')
   
  SET @IDEMPRESANOTIFICACION  =ISNULL(:IDEMPRESANOTIFICACION, 0) 
  SET @DESTINOADD=ISNULL(:PARAQUIENAD, '')
  SET @USRNUEVO =ISNULL(:USRNUEVO, '')
  UPDATE  <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG 
  SET ASUNTO = @ASUNTO, 
   CUERPO = @CUERPO , 
   SMS = @SMS,  
   ASUNTOAD =@ASUNTOAD, 
   CUERPOAD = @CUERPOAD, 
   DESTINOADD=@DESTINOADD
  WHERE IDEMPRESANOTIFICACION =  @IDEMPRESANOTIFICACION  AND IDEMPRESA =  @IDEMPRESA


  SELECT @ADICIONAL_IDUSUARIOS = @ADICIONAL_IDUSUARIOS + CAST(IDUSUARIO AS VARCHAR(5))+',' FROM  <#SESSION.DB/>.dbo.USUARIOS WHERE IDEMPRESA = @IDEMPRESA AND
   (
     IDUSUARIO IN (SELECT SplitValue FROM <#SESSION.DB/>.dbo.Split(@LTIDUSUARIOS,','))
   )
  SELECT @ADICIONAL_IDGRUPOS = @ADICIONAL_IDGRUPOS + CAST(IDUSUARIOGRUPO AS VARCHAR(5))+',' FROM  <#SESSION.DB/>.dbo.USUARIOS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA AND
   (
     IDUSUARIOGRUPO   IN (SELECT SplitValue FROM <#SESSION.DB/>.dbo.Split(@LTIDGRUPOS,',')) 
   ) 
  UPDATE  <#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG SET 
  ADICIONAL_IDUSUARIOS = @ADICIONAL_IDUSUARIOS,
  ADICIONAL_IDGRUPOS = @ADICIONAL_IDGRUPOS,
  ADICIONAL_OTROS = @USRNUEVO
  
  WHERE IDEMPRESANOTIFICACION = @IDEMPRESANOTIFICACION 
 END

