//[session.db|Untyped,session.idusuario|Untyped,crit|Text,]
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
SET @CRIT = ISNULL( :CRIT , '')

SET @SQL = '
  SELECT
  LEIDO,
  A.IDUSUARIOALERTA,S.TIPO, S.IDPROSPECTO, S.IDOPORTUNIDAD, S.IDMETA, S.IDTAREA, S.IDCITA, A.ALERTA, A.FECHA
  FROM
   <#SESSION.DB/>.DBO.USUARIOS_ALERTAS A
   JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS S ON S.IDSUCESO =  A.IDSUCESO
   JOIN SALESUP_CT.dbo.TIPOS_SUCESOS T ON T.IDSUCESO = S.TIPO
   LEFT JOIN <#SESSION.DB/>.DBO.TAREAS TR ON TR.IDTAREA = S.IDTAREA
   LEFT JOIN <#SESSION.DB/>.DBO.CITAS C ON C.IDCITA = S.IDCITA
  WHERE A.IDUSUARIO=<#SESSION.IDUSUARIO> ' +  @CRIT + ' ANd T.NOTIFICA = 1
  AND ISNULL(ALERTA, '''') !=''''
  ORDER BY S.FECHAHORA DESC , A.FECHA DESC
  
  '
  
EXEC (@SQL)
