//[session.db|Untyped,session.idempresa|Untyped,idseccion|Integer,]
SELECT
S.MODULO,N.IDNOTIFICACIOn, EC.IDEMPRESANOTIFICACION, EC.NOTIFICA_SUPERVISOR,
S.SECCION, S.IDSUCESO, SUCESO, NIVELMINIMO, EXPLICACION,
ISNULL(EC.NOTIFICA_EMAIL, 1) AS NOTIFICA_EMAIL, ISNULL(EC.NOTIFICA_SMS, 0) AS NOTIFICA_SMS,
ISNULL(EC.NOTIFICA_ALERTA, 1) AS NOTIFICA_ALERTA, ISNULL(EC.NOTIFICA_PUSH, 0) AS NOTIFICA_PUSH,
ISNULL(SUCESOMOVIL, 0) AS sUCESOMOVIL, ISNULL(NOTIFICAR, 0) AS NOTIFICAR
FROM 
SALESUP_CT.dbo.TIPOS_SUCESOS S LEFT JOIN
SALESUP_CT.dbo.NOTIFICACIONES N ON  N.IDSUCESO = S.IDSUCESO LEFT JOIN
<#SESSION.DB/>.dbo.EMPRESAS_NOTIFICACION_CONFIG EC  
ON N.IDNOTIFICACION = EC.IDNOTIFICACION AND EC.IDEMPRESA = <#SESSION.IDEMPRESA/>
WHERE S.SECCION = ISNULL(:IDSECCION,0)  AND NOTIFICA = 1
GROUP BY S.MODULO,N.IDNOTIFICACIOn, EC.IDEMPRESANOTIFICACION, EC.NOTIFICA_SUPERVISOR,
S.SECCION, S.IDSUCESO, SUCESO, NIVELMINIMO, EXPLICACION,EC.NOTIFICA_EMAIL, EC.NOTIFICA_SMS,
EC.NOTIFICA_ALERTA,EC.NOTIFICA_PUSH,SUCESOMOVIL,NOTIFICAR
ORDER BY SUCESO