//[session.idempresa|Untyped,session.idusuario|Untyped,reporteconfig|Text,anio|Text,fecha_inicio|Text,session.convertcode|Untyped,fecha_fin|Text,tipodatos|Text,session.db|Untyped,]
--select
/*PROTEGIDO*/
DECLARE @SESSION_IDEMPRESA INT
DECLARE @SESSION_IDUSUARIO INT
DECLARE @IDREPORTECONFIG INT
DECLARE @PERIODO INT
DECLARE @FECHA_INICIO DATETIME
DECLARE @FECHA_FIN DATETIME
DECLARE @TIPO_REPORTE INT
DECLARE @ANIO INT
DECLARE @FFECHA_INICIO VARCHAR(MAX)
DECLARE @FFECHA_FIN VARCHAR(MAX) 
DECLARE @TIPODATOS VARCHAR(1000)

SET @SESSION_IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @SESSION_IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @FFECHA_INICIO=ISNULL(:FECHA_INICIO,'')
SET @FFECHA_FIN=ISNULL(:FECHA_FIN,'')
SET @TIPODATOS =  ISNULL(:TIPODATOS,'')

IF(:REPORTECONFIG = 'null' OR :REPORTECONFIG = 'UNDEFINED')  
  SET @IDREPORTECONFIG = 0
ELSE
  SET @IDREPORTECONFIG = :REPORTECONFIG
  
IF(:ANIO = 'null' OR :ANIO = 'UNDEFINED')
 SET @ANIO = 0
ELSE
 SET @ANIO=ISNULL(:ANIO, 0)  
 
IF(@ANIO > 0)
BEGIN
	 SET @FECHA_INICIO= CONVERT(DATETIME,'01/01/'+CAST(@ANIO AS VARCHAR),103)
   	 SET @FECHA_FIN=DATEADD(SS,-1,CONVERT(DATETIME,CONVERT(VARCHAR(10),CONVERT(DATETIME,'31/12/'+CAST(@ANIO AS VARCHAR),103)+1,103),103))
END
ELSE
BEGIN
	 SET @FECHA_INICIO= CONVERT(DATETIME,@FFECHA_INICIO,<#SESSION.CONVERTCODE/>)
   	 SET @FECHA_FIN=DATEADD(SS,-1,CONVERT(DATETIME,CONVERT(VARCHAR(10),CONVERT(DATETIME,@FFECHA_FIN,<#SESSION.CONVERTCODE/>)+1,<#SESSION.CONVERTCODE/>),<#SESSION.CONVERTCODE/>))
END

SET @TIPO_REPORTE = CAST(@TIPODATOS AS INT) /* 0 CABECERA, 1 DATOS, 2 TOTALES */

IF(@IDREPORTECONFIG <> 0)
	EXEC  <#SESSION.DB/>.DBO.SP_REPORTE_EMBUDO_Y_CONVERSIONES_CANALIZACION @SESSION_IDEMPRESA,@SESSION_IDUSUARIO, @IDREPORTECONFIG, @FECHA_INICIO,@FECHA_FIN,@TIPO_REPORTE
ELSE
	SELECT '' AS RESPUESTA
