//[OBJETO|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped]
--SELECT
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @OBJETO VARCHAR(MAX) 


SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO=CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @OBJETO =ISNULL(:OBJETO,'')
 

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_AVANCE_FASES_CABECERA @IDUSUARIO,@IDEMPRESA,@OBJETO
