//[OBJETO|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped]
--SELECT
DECLARE @OBJETO VARCHAR(MAX) 
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @CONTEO INT

SET @CONTEO = 0
SET @OBJETO = ISNULL(:OBJETO,'')
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_AVANCE @IDUSUARIO,@IDEMPRESA,@OBJETO, @CONTEO