//[VALOR|Integer,RetornaIDvariante|Text,RETORNATIPO|Integer,RETORNAIDFASE|Text,session.db|Untyped,]
--SELECT
DECLARE @VALOR INT
DECLARE @RetornaIDvariante VARCHAR(MAX)
DECLARE @RETORNATIPO INT
DECLARE @RETORNAIDFASE VARCHAR(MAX)

SET @VALOR = ISNULL(:VALOR,'')
SET @RetornaIDvariante = ISNULL(:RetornaIDvariante,'')
SET @RETORNATIPO = ISNULL(:RETORNATIPO,'')
SET @RETORNAIDFASE = ISNULL(:RETORNAIDFASE,'')



IF @RETORNAIDFASE != ''
BEGIN
	IF @RETORNATIPO = 1
	BEGIN
 		SELECT IDFASE FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE TK = @RETORNAIDFASE
	END
	ELSE
	BEGIN
 		SELECT IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE TK = @RETORNAIDFASE
	END
END


IF @VALOR != ''
BEGIN
	IF @RETORNATIPO = 1
	BEGIN
 		SELECT TK FROM <#SESSION.DB/>.DBO.OPORTUNIDADES_FASES WHERE IDFASE = @VALOR
	END
	ELSE
	BEGIN
 		SELECT TK FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE = @VALOR
	END
END

IF @RetornaIDvariante != ''
BEGIN
	SELECT IDVARIANTE FROM SALESUP_CT.DBO.REPORTES_SISTEMA_VARIANTES WHERE TKRSV = @RetornaIDvariante 
END


