//[TKMONEDA|Text,session.db|Untyped,]
--SELECT
DECLARE @TKMONEDA VARCHAR(MAX)
SET @TKMONEDA = ISNULL(:TKMONEDA,'')
DECLARE @IDMONEDA VARCHAR(50)
SELECT @IDMONEDA = IDMONEDA FROM <#SESSION.DB/>.dbo.monedas WHERE TK = @TKMONEDA
SELECT  MONEDA_SIMBOLO FROM salesup_ct.dbo.monedas WHERE IDMONEDA = @IDMONEDA


