//[tkp|Text,idprospecto|Integer,session.convertcode|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,modulo|Integer,]
--select
  DECLARE @TKP VARCHAR(64)
  DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @CONVERTCODE INT, @IDUSUARIO INT
  DECLARE @ELMODULO INT 
  
  SET @TKP = ISNULL(:TKP,'')
  SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)   
  SET @CONVERTCODE = '<#SESSION.CONVERTCODE/>' IF @CONVERTCODE = '' BEGIN SET @CONVERTCODE = 103 END
  SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
  SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
  SET @ELMODULO = ISNULL(:MODULO, 1) 
  
  IF @TKP != '' BEGIN SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE TKP = @TKP END
  
  SELECT TOP 1
  SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS esCanalizado, P.esCliente, CONVERT(VARCHAR(10),P.CANALIZADOEL ,103) AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, P.USRCANALIZO as Canalizo, P.USRCANALIZADO AS Canalizado,
  (SELECT CASE WHEN COUNT(PA1.IDPROSPECTO) > 0 THEN '1' ELSE '' END FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA1 WHERE PA1.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != PA1.IDUSUARIO) AS Compartido,
  isnull((SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WHERE PA.IDUSUARIO = @IDUSUARIO AND PA.IDPROSPECTO = P.IDPROSPECTO),0) AS Asignado,
  
  (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = P.IDPAIS) AS pPais,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = P.IDESTADO AND IDPAIS=P.IDPAIS) AS pEstado,
  (SELECT M.MUNICIPIO FROM SALESUP_CT.DBO.MUNICIPIOS M WHERE M.IDMUNICIPIO = P.IDMUNICIPIO AND M.IDESTADO = P.IDESTADO AND M.IDPAIS = P.IDPAIS) AS pMunicipio,
  
   A.Archivado, U.CalendarioPagos, P.recibirCorreos,
   (U.NOMBRE+' '+U.APELLIDOS) AS Ejecutivo, U.Iniciales, U.Email as EmailEjecutivo,
   A.IDUSUARIO AS idusr,
  
  
    p.idprospecto AS idp, P.Tkp, P.IdUsuario, P.Nombre, P.Apellidos, P.Titulo, P.Sexo, P.Correo, P.Puesto, P.Telefono, P.Telefono2, P.Movil,
	P.Comentarios, O.Origen, F.Fase, P.ETIQUETAS_TXT AS Etiquetas, CONVERT(VARCHAR(10),P.FECHACONTACTO,103) AS CreadoEl, SALESUP_CT.dbo.ObtieneHora(P.FECHACONTACTO) as CreadoHora,
	ISNULL(P.Descartado,0) as Descartado, descartadoRazon,
	P.Facebook, P.Twitter, P.Skype, P.Linkedin, P.Googleplus,
	/* pPaginaWeb */
	P.Empresa, P.Url, P.IdMunicipio, P.direccion1 AS pCalle, P.direccion2 as pColonia, P.Ciudad as pCiudad , P.codigopostal as pCodigoPostal,
	P.IdCompania, P.IdIndustria, P.IdCompaniaGrupo,
	
	P.Campo1, P.Campo2, P.Campo3, P.Campo4,
	P.Campo5, P.Campo6, P.Campo7, P.Campo8,
	
	CONVERT(VARCHAR(10), P.Campo9, 103 ) AS Campo9,
	CONVERT(VARCHAR(10), P.Campo10, 103 ) AS Campo10,
	CONVERT(VARCHAR(10), P.Campo11, 103 ) AS Campo11,
	CONVERT(VARCHAR(10), P.Campo12, 103 ) AS Campo12, 
	
	P.Campo13, P.Campo14, P.Campo15, P.Campo16, P.Campo17, P.Campo18, P.Campo19, P.Campo20,
	ECO1.OPCION AS Campo21, ECO2.OPCION AS Campo22, ECO3.OPCION AS Campo23, ECO4.OPCION AS Campo24, ECO5.OPCION AS Campo25,
	P.Campo26, P.Campo27, P.Campo28, P.Campo29, P.Campo30, P.Campo31, P.Campo32, P.Campo33, P.Campo34,
	
	P.Campo35, P.Campo36, P.Campo37, P.Campo38, P.Campo39, 
	P.Campo40, P.Campo41, P.Campo42, P.Campo43, P.Campo44, 
	P.Campo45, P.Campo46, P.Campo47, P.Campo48, P.Campo49, 
	P.Campo50, P.Campo51, P.Campo52, P.Campo53, P.Campo54, 
	P.Campo55, P.Campo56, P.Campo57, P.Campo58, P.Campo59, 
	P.Campo60, P.Campo61, P.Campo62, P.Campo63, P.Campo64, 
    CatP1.OPCION AS pCat1, CatP2.OPCION AS pCat2,CatP3.OPCION AS pCat3,
	CatE1.OPCION AS eCat1,CatE2.OPCION AS eCat2,CatE3.OPCION AS eCat3,
	
	COM.TKCOM as tkcom, EI.Industria, CG.CompaniaGrupo as GrupoEmpresarial, COM.URL AS PaginaWeb, COM.DIRECCION1 AS Calle, COM.DIRECCION2 AS Colonia, 
	COM.CIUDAD AS Ciudad, COM.CODIGOPOSTAL AS CodigoPostal, COM.NEMPLEADOS AS nEmpleados, COM.TELEFONOCORPORATIVO AS TelefonoCorporativo,
	COM.NUMERO_INTERIOR as NumInterior, COM.NUMERO_EXTERIOR as NumExterior, 
	COM.CCAMPO1 as Campo1C, COM.CCAMPO2 as Campo2C, COM.CCAMPO3 as Campo3C, COM.CCAMPO4 as Campo4C, COM.CCAMPO5 as Campo5C,
	COM.CCAMPO6 as Campo6C, COM.CCAMPO7 as Campo7C, COM.CCAMPO8 as Campo8C, COM.CCAMPO9 as Campo9C, COM.CCAMPO10 as Campo10C,
	(SELECT TOP 1 ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = COM.IDESTADO AND IDPAIS = COM.IDPAIS) AS Estado, 
	(SELECT TOP 1 PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = COM.IDPAIS) AS Pais,
	(SELECT TOP 1 MUNICIPIO FROM SALESUP_CT.dbo.MUNICIPIOS WHERE IDPAIS = COM.IDPAIS AND IDESTADO = COM.IDESTADO AND IDMUNICIPIO = COM.IDMUNICIPIO) AS EmpMunicipio,
	EI.tkInd, CG.Tkcg
  
  FROM 
    <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO, @ELMODULO, 0) UL,
	<#SESSION.DB/>.DBO.PROSPECTOS P
	LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA AND COM.IDEMPRESA = @IDEMPRESA
    LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO 
    LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO1 ON ECO1.IDOPCION = P.CAMPO21
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO2 ON ECO2.IDOPCION = P.CAMPO22 
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO3 ON ECO3.IDOPCION = P.CAMPO23 
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO4 ON ECO4.IDOPCION = P.CAMPO24 
	LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_OPCIONES ECO5 ON ECO5.IDOPCION = P.CAMPO25
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP1 WITH(NOLOCK) ON CatP1.IDCATALOGOOPCION = P.IDCATALOGOOPCION1      
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP2 WITH(NOLOCK) ON CatP2.IDCATALOGOOPCION = P.IDCATALOGOOPCION2      
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP3 WITH(NOLOCK) ON CatP3.IDCATALOGOOPCION = P.IDCATALOGOOPCION3
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE1 WITH(NOLOCK) ON CatE1.IDCATALOGOOPCION = COM.IDCATALOGOOPCION1      
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE2 WITH(NOLOCK) ON CatE2.IDCATALOGOOPCION = COM.IDCATALOGOOPCION2      
	LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE3 WITH(NOLOCK) ON CatE3.IDCATALOGOOPCION = COM.IDCATALOGOOPCION3    
	, 
    <#SESSION.DB/>.DBO.PROSPECTOS_FASES F, 
    <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O,
    <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A, 
    <#SESSION.DB/>.DBO.USUARIOS U
  WHERE 
      UL.ID = A.IDUSUARIO 
	AND P.IDPROSPECTO = @IDPROSPECTO
    AND P.IDPROSPECTO = A.IDPROSPECTO
    AND P.IDEMPRESA = @IDEMPRESA 
    AND P.IDFASE = F.IDFASE 
    AND P.IDORIGEN = O.IDORIGEN 
    AND P.IDUSUARIO = U.IDUSUARIO
	
	
	
	
