//[clave|Text,default_pros|Text,session.db|Untyped,session.idusuario|Untyped,]
--UPDATE
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @CLAVE VARCHAR(1000)
DECLARE @DEFAULT_PROS VARCHAR(1000)
SET @CLAVE = :CLAVE
SET @DEFAULT_PROS = CAST(ISNULL(:DEFAULT_PROS,0) AS VARCHAR(1000))
IF (@CLAVE IS NOT NULL)
 BEGIN
   SET @SQL ='UPDATE <#SESSION.DB/>.DBO.USUARIOS_DEFAULTS SET DEFAULT_O_'+@CLAVE+'='+@DEFAULT_PROS+' WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>'
   EXEC (@SQL)
 END