//[session.db|Untyped,titulo|Text,idtitulo|Integer,session.idempresa|Untyped,tituloold|Text,]
--UPDATE
/*PROTEGIDO*/
DECLARE @TITULO VARCHAR(MAX)
DECLARE @TITULOOLD VARCHAR(MAX)
DECLARE @IDTITULO INT
SET @IDTITULO=ISNULL(:IDTITULO,0)
SET @TITULO=ISNULL(:TITULO,'')
SET @TITULOOLD=ISNULL(:TITULOOLD,'')
UPDATE <#SESSION.DB/>.DBO.EMPRESAS_TITULOS SET TITULO = @TITULO WHERE IDTITULO = @IDTITULO AND IDEMPRESA = <#SESSION.IDEMPRESA/>
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET TITULO = @TITULO WHERE TITULO = @TITULOOLD AND IDEMPRESA = <#SESSION.IDEMPRESA/>