//[session.db|Untyped,session.idusuario|Untyped,tipossucesos|Text,]
DELETE FROM <#SESSION.DB/>.DBO.TIPO_SUCESOS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>
DECLARE @TIPOS INT

DECLARE @TABLATEMP TABLE (ID INT IDENTITY,TIPOS INT)
DECLARE @TO INT, @TOTAL INT
SET @TO = 1

INSERT INTO @TABLATEMP (TIPOS)
select SplitValue from <#SESSION.DB/>.DBO.Split(ISNULL(:TIPOSSUCESOS,''), ',')

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @TIPOS = TIPOS FROM @TABLATEMP WHERE ID = @TO
	INSERT INTO <#SESSION.DB/>.DBO.TIPO_SUCESOS (IDUSUARIO, TIPO)
	values (<#SESSION.IDUSUARIO/>,@TIPOS)
	SET @TO = @TO + 1
END
