//[nombre|Text,correo|Text,apellidos|Text,tipo|Text,laidempresa|Integer,idempresa|Text,idusuario|Text,]
--select 
DECLARE @laidempresa INT
DECLARE @NOMBRE VARCHAR(128) 
DECLARE @APELLIDOS VARCHAR(128)
DECLARE @CORREO VARCHAR(256)
DECLARE @IDEMPRESA VARCHAR(1000)
DECLARE @IDUSUARIO VARCHAR(1000)
DECLARE @TIPO VARCHAR(1000)
SET @NOMBRE = ISNULL(:NOMBRE,'')
IF @NOMBRE = ''
  SET @NOMBRE = ISNULL(:CORREO,'')
SET @APELLIDOS  = ISNULL(:APELLIDOS,'')
SET @CORREO = ISNULL(:CORREO,'')
SET @TIPO = ISNULL(:TIPO,'')


SET @IDEMPRESA = CAST(ISNULL(:IDEMPRESA,0) AS VARCHAR(1000))
SET @IDUSUARIO = CAST(ISNULL(:IDUSUARIO,0) AS VARCHAR(1000))


SET @laidempresa=ISNULL(:laidempresa,0)
select *,BD_ACTUAL AS BASE,@NOMBRE  as nombre,@APELLIDOS as apellidos, @CORREO as correo , @TIPO  AS TIPO,
 @IDEMPRESA AS IDEMPRESA, @IDUSUARIO  AS IDUSUARIO 
 from salesup_ct.dbo.empresas where idempresa=@laidempresa