//[ven|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @VerEn VARCHAR(12)
DECLARE @IDEMPRESA INT, @VENTANA INT

SET @VENTANA = CAST(ISNULL(:VEN,0) AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

IF @VENTANA = 1 BEGIN SET @VEREN = '1,3' END
IF @VENTANA = 2 BEGIN SET @VEREN = '2,4' END
IF @VENTANA = 3 BEGIN SET @VEREN = '1,3' END
IF @VENTANA = 4 BEGIN SET @VEREN = '1,2,3,4' END

SELECT COUNT(*) AS TotalRegistros
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS 
WHERE LLAVE IN (1,2) AND IDEMPRESA = @IDEMPRESA AND INDICE NOT IN (33,34) 
AND (
	TIPO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@VEREN,','))  OR COMPARTIR IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@VEREN,','))
	)