//[session.idempresa|Untyped,idp|Text,tkp|Text,session.db|Untyped,]
--select
DECLARE @IDPROSPECTO INT, @IDEMPRESA INT
DECLARE @TKP VARCHAR(MAX)
DECLARE @IDP VARCHAR(1000)
SET @IDPROSPECTO = 0
SET @TKP = ''
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDP=ISNULL(:IDP,'')

SET @TKP = ISNULL(:TKP,'')

IF @TKP != ''
BEGIN
	 SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA )
END

SELECT U.Nombre+' '+ISNULL(U.Apellidos,'') as Ejecutivo, U.Iniciales
FROM <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WITH(NOLOCK) ON PA.IDPROSPECTO = P.IDPROSPECTO,
<#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK)
WHERE PA.IDUSUARIO = U.IDUSUARIO AND P.IDPROSPECTO = @IDPROSPECTO AND U.IDEMPRESA = P.IDEMPRESA AND P.IDEMPRESA = @IDEMPRESA
ORDER BY U.NOMBRE



