//[idrecordatorio|Integer,session.convertcode|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,recordatorio|Text,horarecordatorio|Text,fecharecordatorio|Text,idpeticion|Text,repetir|Integer,terminar|Integer,fecharepetir|Text,cada|Integer,diasrecurrencia|Text,diasmes|Text,tkrec|Text,session.db|Untyped,]
--INSERT
DECLARE @IDUSUARIO INT, @CONVERTCODE INT, @IDPROSPECTO INT, @IDOPORTUNIDAD INT, @YAEXISTE INT, @IDRECORDATORIO INT, @IDEMPRESA INT
DECLARE @TKP VARCHAR(MAX), @RECORDATORIO VARCHAR(MAX), @Hora VARCHAR(MAX), @Vence VARCHAR(MAX), @IDPETICION VARCHAR(MAX)
DECLARE @FECHA DATETIME

DECLARE @RECURRENCIA INT
DECLARE @TIPOFIN INT
DECLARE @FECHAFINREPETIR DATETIME
DECLARE @FRECUENCIA INT
DECLARE @DIASFRECUENCIA VARCHAR(5000)


SET @IDRECORDATORIO = CAST(ISNULL(:IDRECORDATORIO,'') AS INT)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @RECORDATORIO = :RECORDATORIO
SET @Hora =ISNULL( :horarecordatorio ,'')
SET @Vence =ISNULL( :fecharecordatorio ,'')+' '+@Hora
SET @FECHA = CONVERT(DATETIME, @Vence, @CONVERTCODE)
SET @IDPETICION = ISNULL(:IDPETICION,'')
 
SET @RECURRENCIA=CAST(ISNULL(:REPETIR,0) AS INT)
SET @TIPOFIN=CAST(ISNULL(:TERMINAR,0) AS INT)
SET @FECHAFINREPETIR=CONVERT(DATETIME,ISNULL(:fecharepetir,''),@CONVERTCODE)
SET @FRECUENCIA=CAST(ISNULL(:CADA,0) AS INT)
SELECT @DIASFRECUENCIA=(CASE WHEN (@RECURRENCIA=0 OR @RECURRENCIA=1) THEN '' WHEN @RECURRENCIA=2 THEN ISNULL(:DIASRECURRENCIA,'') ELSE ISNULL(:DIASMES,'') END )

DECLARE @TKREC VARCHAR(64)
SET @TKREC = ISNULL(:TKREC,'')
IF @TKREC != '' BEGIN SELECT @IDRECORDATORIO = IDRECORDATORIO FROM <#SESSION.DB/>.DBO.RECORDATORIOS WHERE TKREC = @TKREC END

EXEC <#SESSION.DB/>.DBO.SP_EDITAR_RECORDATORIO @IDRECORDATORIO,@FECHA, @RECORDATORIO,@RECURRENCIA,@TIPOFIN,@FECHAFINREPETIR,@FRECUENCIA,@DIASFRECUENCIA
