//[session.db|Untyped,idseguimiento|Integer,idprospecto|Integer,]
-- SELECT
DECLARE @IDPROSPECTO INT
DECLARE @IDSEGUIMIENTO INT
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)
SET @IDSEGUIMIENTO=ISNULL(:IDSEGUIMIENTO,0)
SELECT PS.LATITUD,PS.LONGITUD,PS.COMENTARIO, P.NOMBRE+ ' ' +P.APELLIDOS AS NOMBRE,(<#SESSION.DB/>.DBO.TIEMPO_TXT (PS.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO , @IDPROSPECTO AS IDPROSPECTO, @IDSEGUIMIENTO AS IDSEGUIMIENTO
FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO PS, <#SESSION.DB/>.DBO.PROSPECTOS P 
WHERE PS.IDPROSPECTO = P.IDPROSPECTO AND PS.IDSEGUIMIENTO = @IDSEGUIMIENTO AND PS.IDPROSPECTO = @IDPROSPECTO