//[session.idusuario|Untyped,idoportunidad|Integer,idprospecto|Integer,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDOPORTUNIDAD INT, @IDDOCUMENTO INT, @IDUSUARIO INT, @IDARCHIVO INT, @IDPROSPECTO INT
DECLARE @FECHA DATETIME
DECLARE @NOMBRE_PROSPECTO VARCHAR(256)
DECLARE @ARCHIVO VARCHAR(256)
DECLARE @DESCRIPCION VARCHAR(256)
DECLARE @ETIQUETAS VARCHAR(1024)

SET @FECHA = GETDATE()
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD,0)
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO, 0)


SELECT @IDDOCUMENTO = IDDOCUMENTO  FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD ORDER BY 1 DESC


SELECT TOP 1 @IDARCHIVO = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD AND IDDOCUMENTO = @IDDOCUMENTO 
ORDER BY IDPROSPECTOARCHIVO DESC

IF(@IDARCHIVO IS NOT NULL)
 BEGIN

	   INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS
	     (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, ARCHIVO, DESCRIPCION, AMAZON, PESO, FECHA, IDDOCUMENTO, ETIQUETAS )
		 SELECT TOP 1 IDPROSPECTO, IDOPORTUNIDAD, @IDUSUARIO, <#SESSION.DB/>.dbo.NombreArchivoCotizacion (DESCRIPCION,'pdf'), 
	  	  DESCRIPCION, AMAZON, PESO, @FECHA, IDDOCUMENTO, ETIQUETAS 
		 FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
		 WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD AND IDDOCUMENTO = @IDDOCUMENTO 
	 	 ORDER BY IDPROSPECTOARCHIVO DESC
 END
 ELSE
 BEGIN
 	  	SELECT @NOMBRE_PROSPECTO = CAST(NOMBRE+' '+APELLIDOS AS VARCHAR(256)) FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
		SELECT @DESCRIPCION = DESCRIPCION, @ETIQUETAS = ETIQUETAS FROM <#SESSION.DB/>.dbo.EMPRESAS_DOCUMENTOS WHERE IDDOCUMENTO = @IDDOCUMENTO 
		
		SET @DESCRIPCION = @DESCRIPCION+' '+@NOMBRE_PROSPECTO
		DECLARE @DESCRIPCION_COTIZACION VARCHAR(256) 
		SET @DESCRIPCION_COTIZACION   = <#SESSION.DB/>.dbo.NombreArchivoCotizacion (@DESCRIPCION,'pdf')	
			
		INSERT <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, ARCHIVO, DESCRIPCION, AMAZON, PESO, FECHA, IDDOCUMENTO, ETIQUETAS)
		                                        values(@IDPROSPECTO, @IDOPORTUNIDAD, @IDUSUARIO, @DESCRIPCION_COTIZACION , @DESCRIPCION,1, 0, @FECHA, @IDDOCUMENTO, @ETIQUETAS)
 END
	 

SELECT TOP 1 @IDARCHIVO = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD AND IDDOCUMENTO = @IDDOCUMENTO 
ORDER BY IDPROSPECTOARCHIVO DESC

EXEC <#SESSION.DB/>.dbo.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO, @FECHA

SELECT @IDARCHIVO AS idArchivo
