//[session.gmt|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,f_usuario|Text,]
DECLARE @GMT INT, @IDEMPRESA INT, @IDUSUARIO INT
SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)

SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT WHERE GMT = @GMT
SET @F_USUARIO = ISNULL(:F_USUARIO,'')

SET @SQL='
SELECT 
1 as R,
CASE WHEN (P.DESCARTADO = 1) AND (X.TIPO = 6) THEN ''1'' ELSE '''' END AS Reclamar,
CASE WHEN (X.TIPO = 0) OR (X.TIPO = 2) OR (X.TIPO = 3) OR (X.TIPO = 4) OR (X.TIPO = 5) OR (X.TIPO = 6) OR (X.TIPO = 7) OR (X.TIPO = 8) OR (X.TIPO = 23) OR (X.TIPO = 20) THEN ''1'' ELSE '''' END AS pVisualizar,
CASE WHEN (X.TIPO = 13) OR (X.TIPO = 22) THEN ''1'' ELSE '''' END AS cVisualizar,
CASE WHEN (X.TIPO = 1) OR (X.TIPO = 9) OR (X.TIPO = 10) OR (X.TIPO = 11) OR (X.TIPO = 12) OR (X.TIPO = 14) OR (X.TIPO = 21) THEN ''1'' ELSE '''' END AS oVisualizar,
CASE WHEN P.Sexo = ''M'' THEN ''1'' ELSE '''' END AS Sexo,
LTRIM(RTRIM(P.NOMBRE))+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS Prospecto, 
X.DT_FechaHora, X.Fecha, X.Hora, X.Texto, X.Ejecutivo, X.IdProspecto, X.IdOportunidad
FROM
(
  SELECT TOP 26 DATEADD(hh, (6+'+CAST(@GMT AS VARCHAR(1000))+'),US.FECHAHORA) AS DT_FECHAHORA, CONVERT(VARCHAR(64), DATEADD(hh, (6+'+CAST(@GMT AS VARCHAR(1000))+'),US.FECHAHORA) ,103) AS FECHA, 
  
  LTRIM(RTRIM(RIGHT(CONVERT(VARCHAR, DATEADD(hh, (6+'+CAST(@GMT AS VARCHAR(1000))+'),US.FECHAHORA) ,100),8))) AS HORA, 
  US.TEXTO, US.TIPO, US.IDPROSPECTO,  (UU.NOMBRE+'' ''+UU.APELLIDOS) AS EJECUTIVO, US.IDOPORTUNIDAD
  FROM  <#SESSION.DB/>.dbo.USUARIOS UU  WITH(NOLOCK) 
  JOIN <#SESSION.DB/>.dbo.USUARIOS_SUCESOS US  WITH(NOLOCK) ON US.IDUSUARIO=UU.IDUSUARIO  
  JOIN <#SESSION.DB/>.dbo.TIPO_SUCESOS TS  WITH(NOLOCK) ON US.TIPO = TS.TIPO AND TS.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(1000))+'
  WHERE IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+'
  AND ( 1=1 '+@F_USUARIO+' OR US.IDPROSPECTO IN (SELECT IDPROSPECTO FROM  <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS WHERE IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(1000))+' ) )
  GROUP BY US.FECHAHORA, US.TEXTO, US.TIPO, US.IDPROSPECTO, (UU.NOMBRE+'' ''+UU.APELLIDOS) , US.IDOPORTUNIDAD
  ORDER BY US.FECHAHORA DESC
) AS X
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) ON P.IDPROSPECTO = X.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK) ON X.IDPROSPECTO = O.IDPROSPECTO

GROUP BY X.DT_FECHAHORA, X.FECHA, X.Hora, X.TEXTO, X.TIPO, X.IDPROSPECTO, X.EJECUTIVO, X.IDOPORTUNIDAD, NOMBRE, P.APELLIDOS, P.DESCARTADO, P.Sexo
ORDER BY X.DT_FECHAHORA DESC
'
--SELECT @SQL
EXEC (@SQL)
