//[tko|Text,session.convertcode|Untyped,tkp|Text,idprospecto|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,]
--select 

  DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @IDUSUARIO INT
  DECLARE @TKP VARCHAR(64)

  DECLARE @CODIGO INT
  DECLARE @TKO VARCHAR(64)
  
  SET @TKO=:Tko
  SET @CODIGO='<#SESSION.CONVERTCODE/>'
  
  IF @CODIGO = ''
  	 SET @CODIGO=103
  
  SET @TKP = dbo.ValidaToken(:TKP)
  SET @IDPROSPECTO = :IDPROSPECTO
  SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
  SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
  IF @TKP != ''
  BEGIN
  	   SELECT @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE TKP = @TKP
  END
  
  SELECT TOP 1 @TKO as tko, @TKP as tkp, U.tku, COM.Tkcom,<#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa(CAST(@IDUSUARIO AS VARCHAR(MAX)),Com.IdCompania) as hPermiso,
  SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS esCanalizado, CONVERT(VARCHAR(10),P.CANALIZADOEL ,103)AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, P.USRCANALIZO as Canalizo, P.USRCANALIZADO AS Canalizado,
  (SELECT CASE WHEN COUNT(PA1.IDPROSPECTO) > 0 THEN '1' ELSE '' END FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA1 WHERE PA1.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != PA1.IDUSUARIO) AS COMPARTIDO,
  /* datos de la empresa */
  EI.INDUSTRIA, CG.COMPANIAGRUPO, COM.URL AS URLEMPRESA,COM.DIRECCION1 AS DIRECCIONEMPRESA1, COM.DIRECCION2 AS DIRECCIONEMPRESA2, 
  COM.CIUDAD AS CIUDADEMPRESA,COM.CODIGOPOSTAL AS CPEMPRESA,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = COM.IDESTADO AND IDPAIS=COM.IDPAIS) AS ESTADOEMPRESA, COM.NEMPLEADOS AS NEMPRESA,
  (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = COM.IDPAIS) AS PAISEMPRESA, tkInd, Tkcg, 
  COM.TELEFONOCORPORATIVO,
  
  CASE WHEN ISNULL(P.IDCOMPANIA, 0) > 0 THEN '<a href="EmpresasVisualizar.dbsp?tkcom='+com.tkcom+'"><i class="fa fa-building-o"></i> '+COM.EMPRESA+'</a>' ELSE p.EMPRESA END AS EMPRESA,
  CASE WHEN ISNULL(P.IDCOMPANIA, 0) > 0 THEN '<i class="fa fa-building-o"></i>&nbsp;'+COM.EMPRESA ELSE p.EMPRESA END AS EMPRESATXT,

  LEN(ISNULL(P.MOVIL,0)) AS TIENEMOVIL, 
  convert(varchar(12), GETDATE(),@CODIGO) as LA_FECHA_CIERRE,
  CONVERT(VARCHAR, p.CAMPO9,@CODIGO) AS CAMPO9,  CONVERT(VARCHAR, P.CAMPO10,@CODIGO) AS CAMPO10,  CONVERT(VARCHAR, P.CAMPO11,@CODIGO) AS CAMPO11,  CONVERT(VARCHAR, P.CAMPO12,@CODIGO) AS CAMPO12,
  
  P.CAMPO1 AS CAMPO1P, P.CAMPO2 AS CAMPO2P, P.CAMPO3 AS CAMPO3P, P.CAMPO4 AS CAMPO4P,
  P.CAMPO5 AS CAMPO5P, P.CAMPO6 AS CAMPO6P, P.CAMPO7 AS CAMPO7P, P.CAMPO8 AS CAMPO8P,
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '' END AS CAMPO9P,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '' END AS CAMPO10P,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '' END AS CAMPO11P,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '' END AS CAMPO12P,
  P.CAMPO13+' ' AS CAMPO13P, P.CAMPO14+' ' AS CAMPO14P, P.CAMPO15+' ' AS CAMPO15P, P.CAMPO16+' ' AS CAMPO16P,
  P.CAMPO17+' ' AS CAMPO17P, P.CAMPO18+' ' AS CAMPO18P, P.CAMPO19+' ' AS CAMPO19P, P.CAMPO20+' ' AS CAMPO20P,
  P.CAMPO21 AS CAMPO21P, P.CAMPO22 AS CAMPO22P, P.CAMPO23 AS CAMPO23P, P.CAMPO24 AS CAMPO24P,
  P.CAMPO25 AS CAMPO25P, P.CAMPO26+' ' AS CAMPO26P, P.CAMPO27+' ' AS CAMPO27P, P.CAMPO28+' ' AS CAMPO28P,
  P.CAMPO29+' ' AS CAMPO29P, P.CAMPO30+' ' AS CAMPO30P, P.CAMPO31+' ' AS CAMPO31P, P.CAMPO32+' ' AS CAMPO32P,
  P.CAMPO33+' ' AS CAMPO33P, P.CAMPO34+' ' AS CAMPO34P,
  
  A.ARCHIVADO, P.*, F.FASE,O.ORIGEN, A.IDUSUARIO AS IDUSER, U.IDGRUPO,U.CALENDARIOPAGOS,
  <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO ,
  (SELECT ESTADO FROM <#SESSION.DB/>.DBO.ESTADOS WHERE IDESTADO = P.IDESTADO AND IDPAIS=P.IDPAIS) AS ESTADO,
  (SELECT PAIS FROM <#SESSION.DB/>.DBO.PAISES WHERE IDPAIS = P.IDPAIS) AS PAIS,
  P.ETIQUETAS_TXT AS ETIQUETAS, 
  
  
  (U.NOMBRE + ' ' + U.APELLIDOS) AS AGENTE, U.EMAIL, A.IDUSUARIO AS USUARIO,
  isnull((SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WHERE PA.IDUSUARIO = @IDUSUARIO AND PA.IDPROSPECTO = P.IDPROSPECTO),0) AS asignado,
   <#SESSION.DB/>.dbo.OpcionesMostrar (@IDEMPRESA, @IDPROSPECTO, 0) AS OpcionMostrar,
   
     <#SESSION.DB/>.dbo.OpcionesMostrar (@IDEMPRESA, @IDPROSPECTO, 0) AS OpcionMostrar, P.APROBACIONESTADO AS APROBACION,
  CASE WHEN COM.IDUSUARIO = @IDUSUARIO THEN '1' ELSE '' END AS COMPROP
  FROM 
    <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO, 4, 0) UL,
	 <#SESSION.DB/>.DBO.PROSPECTOS P
	LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA AND COM.IDEMPRESA = @IDEMPRESA
    LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CG ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO 
    LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS EI ON EI.IDINDUSTRIA = COM.IDINDUSTRIA, 
    <#SESSION.DB/>.DBO.PROSPECTOS_FASES F, 
    <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O,
    <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A, 
    <#SESSION.DB/>.DBO.USUARIOS U
  WHERE 
    UL.ID=A.IDUSUARIO AND
    P.IDPROSPECTO = @IDPROSPECTO
    AND P.IDPROSPECTO = A.IDPROSPECTO
    AND P.IDEMPRESA = @IDEMPRESA 
    AND P.IDFASE = F.IDFASE 
    AND P.IDORIGEN = O.IDORIGEN 
    AND P.IDUSUARIO = U.IDUSUARIO
	