//[compartir|Integer,session.idusuario|Untyped,aprobacionestado|Integer,session.empresa|Untyped,session.convertcode|Untyped,tkucompartir|Text,tkcom|Text,tkp|Text,detalles|Text,session.db|Untyped,]
--UPDATE

DECLARE @IDUSUARIO INT,@APROBACIONESTADO INT,@COMPARTIR INT  
DECLARE @IDEMPRESA INT, @CONVERTCODE INT
DECLARE @TKP VARCHAR(MAX),@DETALLE VARCHAR(MAX)
DECLARE @TKUACOMPARTIR VARCHAR(MAX), @TKCOM VARCHAR(MAX)


SET @COMPARTIR = CAST(ISNULL(:compartir,'') AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @APROBACIONESTADO = CAST(ISNULL(:aprobacionEstado,'') AS INT)
SET @IDEMPRESA = CAST('<#SESSION.EMPRESA/>' AS INT)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE>' AS INT)
SET @TKUACOMPARTIR = ISNULL(:tkuCompartir,'')
SET @TKCOM = ISNULL(:tkcom,'')
SET @TKP = ISNULL(:tkp,'')
SET @DETALLE = ISNULL(:detalles,'')

EXEC <#SESSION.DB/>.DBO.SP_PROSPECTO_EMPRESA_APROBACION @COMPARTIR,@APROBACIONESTADO,@IDUSUARIO,@IDEMPRESA,	@CONVERTCODE,@TKCOM,@TKP,@TKUACOMPARTIR,@DETALLE