//[autorizacionpendiente|Integer,compartircon|Text,sonobligatorios|Untyped,idempresa|Text,idpeticion|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,idprospecto|Untyped,idindustria|Untyped,idgrupoempresarial|Untyped,idfase|Untyped,idorigen|Untyped,idtitulo|Untyped,agregarver|Untyped,escliente|Untyped,session.convertcode|Untyped,tkp|Text,session.db|Untyped,nombre|Text,apellidos|Text,empresa|Text,ltidetiquetas|Untyped,ltidetiquetasoriginal|Untyped,sexo|Untyped,correo|Untyped,telefono1|Untyped,telefono2|Untyped,movil|Untyped,puesto|Untyped,comentarios|Text,telefonocorporativo|Untyped,paginaweb|Untyped,nempleados|Untyped,pais|Untyped,estado|Untyped,session.default_pais|Untyped,session.default_estado|Untyped,ciudad|Untyped,pmunicipio|Untyped,codigopostal|Untyped,calle|Untyped,colonia|Untyped,ppais|Untyped,pestado|Untyped,pciudad|Untyped,pcodigopostal|Untyped,pcalle|Text,pcolonia|Untyped,ppaginaweb|Untyped,facebook|Untyped,twitter|Untyped,skype|Untyped,linkedin|Untyped,googleplus|Untyped,campo9|Untyped,campo10|Untyped,campo11|Untyped,campo12|Untyped,campo1|Untyped,campo2|Untyped,campo3|Untyped,campo4|Untyped,campo5|Untyped,campo6|Untyped,campo7|Untyped,campo8|Untyped,campo13|Text,campo14|Text,campo15|Text,campo16|Text,campo17|Text,campo18|Text,campo19|Text,campo20|Text,campo21|Text,campo22|Text,campo23|Text,campo24|Text,campo25|Text,campo26|Text,campo27|Text,campo28|Text,campo29|Text,campo30|Text,campo31|Text,campo32|Text,campo35|Text,campo36|Text,campo37|Text,campo38|Text,campo39|Text,campo40|Text,campo41|Text,campo42|Text,campo43|Text,campo44|Text,campo45|Text,campo46|Text,campo47|Text,campo48|Text,campo49|Text,campo50|Text,campo51|Text,campo52|Text,campo53|Text,campo54|Text,campo55|Text,campo56|Text,campo57|Text,campo58|Text,campo59|Text,campo60|Text,campo61|Text,campo62|Text,campo63|Text,campo64|Text,p|Untyped,com|Untyped,canalizarprospecto|Untyped,numinterior|Text,numexterior|Text,empmunicipio|Text,campo1c|Text,campo2c|Text,campo3c|Text,campo4c|Text,campo5c|Text,campo6c|Text,campo7c|Text,campo8c|Text,campo9c|Text,campo10c|Text,idoportunidad|Untyped,]
--UPDATE
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @IDPROSPECTO INT, @IDCOMPANIA INT, @IDGRUPOEMPRESARIAL INT, @IDINDUSTRIA INT, @IDFASE INT, @IDORIGEN INT, @IDTITULO INT, @AGREGARVER INT, @ESCLIENTE INT, @CONVERTCODE INT
DECLARE @NOMBRE VARCHAR(MAX), @APELLIDOS VARCHAR(MAX), @EMPRESA VARCHAR(MAX), @ETIQUETAS VARCHAR(MAX), @SEXO VARCHAR(MAX)
DECLARE @CORREO VARCHAR(MAX), @TELEFONO VARCHAR(MAX), @TELEFONO2 VARCHAR(MAX), @MOVIL VARCHAR(MAX), @PUESTO VARCHAR(MAX)
DECLARE @COMENTARIOS VARCHAR(MAX), @TELEFONOCORPORATIVO VARCHAR(MAX), @PAGINAWEB VARCHAR(MAX), @NEMPLEADOS VARCHAR(MAX)
DECLARE @PAIS VARCHAR(MAX), @ESTADO VARCHAR(MAX), @CIUDAD VARCHAR(MAX), @CP VARCHAR(MAX), @CALLE VARCHAR(MAX), @COLONIA VARCHAR(MAX)
DECLARE @PROSPECTOPAIS VARCHAR(MAX), @PROSPECTOESTADO VARCHAR(MAX), @PROSPECTOMUNICIPIO VARCHAR(MAX), @PROSPECTOCIUDAD VARCHAR(MAX), @PROSPECTOCP VARCHAR(MAX), @PROSPECTOCALLE VARCHAR(MAX), @PROSPECTOCOLONIA VARCHAR(MAX), @PROSPECTOPAGINAWEB VARCHAR(MAX)
DECLARE @FACEBOOK VARCHAR(MAX), @TWITTER VARCHAR(MAX), @SKYPE VARCHAR(MAX), @LINKEDIN VARCHAR(MAX), @GOOGLEPLUS VARCHAR(MAX), @TKP VARCHAR(MAX)
DECLARE @FECHA9 VARCHAR(MAX), @FECHA10 VARCHAR(MAX), @FECHA11 VARCHAR(MAX), @FECHA12 VARCHAR(MAX), @IDPETICION VARCHAR(MAX), @TITULO VARCHAR (MAX)

DECLARE @FECHA DATETIME
--NUEVAS LINEAS 1
DECLARE @AUTORIZACIONPENDIENTE INT, @COMPARTIRCON VARCHAR(200), @AUTORIZACIONFECHA DATETIME
SET @AUTORIZACIONPENDIENTE = ISNULL(:AUTORIZACIONPENDIENTE, 0)
SET @COMPARTIRCON = ISNULL(:COMPARTIRCON,'')
IF @AUTORIZACIONPENDIENTE  = 1
BEGIN
SET @AUTORIZACIONFECHA = GETDATE()
END
-- FIN NUEVAS LINEAS 1
DECLARE @P_CatalogoOpcion1 INT, @P_CatalogoOpcion2 INT, @P_CatalogoOpcion3 INT 
DECLARE @COM_CatalogoOpcion1 INT, @COM_CatalogoOpcion2 INT, @COM_CatalogoOpcion3 INT 

DECLARE @CAMPO1 INT, @CAMPO2 INT, @CAMPO3 INT, @CAMPO4 INT
DECLARE @CAMPO5 FLOAT, @CAMPO6 FLOAT, @CAMPO7 FLOAT, @CAMPO8 FLOAT
DECLARE @CAMPO9 DATETIME, @CAMPO10 DATETIME, @CAMPO11 DATETIME, @CAMPO12 DATETIME
DECLARE @CAMPO13 VARCHAR(MAX), @CAMPO14 VARCHAR(MAX), @CAMPO15 VARCHAR(MAX), @CAMPO16 VARCHAR(MAX)
DECLARE @CAMPO17 VARCHAR(MAX), @CAMPO18 VARCHAR(MAX), @CAMPO19 VARCHAR(MAX), @CAMPO20 VARCHAR(MAX)
DECLARE @CAMPO21 INT, @CAMPO22 INT, @CAMPO23 INT, @CAMPO24 INT, @CAMPO25 INT
DECLARE @CAMPO26 VARCHAR(MAX), @CAMPO27 VARCHAR(MAX), @CAMPO28 VARCHAR(MAX), @CAMPO29 VARCHAR(MAX)
DECLARE @CAMPO30 VARCHAR(MAX), @CAMPO31 VARCHAR(MAX), @CAMPO32 VARCHAR(MAX)

DECLARE @CAMPO35 VARCHAR(MAX), @CAMPO36 VARCHAR(MAX), @CAMPO37 VARCHAR(MAX), @CAMPO38 VARCHAR(MAX), @CAMPO39 VARCHAR(MAX)
DECLARE @CAMPO40 VARCHAR(MAX), @CAMPO41 VARCHAR(MAX), @CAMPO42 VARCHAR(MAX), @CAMPO43 VARCHAR(MAX), @CAMPO44 VARCHAR(MAX)
DECLARE @CAMPO45 VARCHAR(MAX), @CAMPO46 VARCHAR(MAX), @CAMPO47 VARCHAR(MAX), @CAMPO48 VARCHAR(MAX), @CAMPO49 VARCHAR(MAX)
DECLARE @CAMPO50 VARCHAR(MAX), @CAMPO51 VARCHAR(MAX), @CAMPO52 VARCHAR(MAX), @CAMPO53 VARCHAR(MAX), @CAMPO54 VARCHAR(MAX)
DECLARE @CAMPO55 VARCHAR(MAX), @CAMPO56 VARCHAR(MAX), @CAMPO57 VARCHAR(MAX), @CAMPO58 VARCHAR(MAX), @CAMPO59 VARCHAR(MAX)
DECLARE @CAMPO60 VARCHAR(MAX), @CAMPO61 VARCHAR(MAX), @CAMPO62 VARCHAR(MAX), @CAMPO63 VARCHAR(MAX), @CAMPO64 VARCHAR(MAX)

DECLARE @NumInterior VARCHAR(MAX), @NumExterior VARCHAR(MAX), @IDMUNICIPIOEMP VARCHAR(MAX)
DECLARE @CCAMPO1 VARCHAR(MAX), @CCAMPO2 VARCHAR(MAX), @CCAMPO3 VARCHAR(MAX), @CCAMPO4 VARCHAR(MAX), @CCAMPO5 VARCHAR(MAX)
DECLARE @CCAMPO6 VARCHAR(MAX), @CCAMPO7 VARCHAR(MAX), @CCAMPO8 VARCHAR(MAX), @CCAMPO9 VARCHAR(MAX), @CCAMPO10 VARCHAR(MAX)

DECLARE @YAEXISTE INT, @SONOBLIGATORIOS INT
DECLARE @LTETIQUETASORIGINAL VARCHAR(MAX), @LTETIQUETASNUEVA VARCHAR(MAX)
DECLARE @ELIMINARETIQUETAS TABLE(ID INT IDENTITY, IDETIQUETA INT)
DECLARE @NUEVASETIQUETAS TABLE(ID INT IDENTITY, IDETIQUETA INT)

DECLARE @NOMBRE_QUIEN_CANALIZA VARCHAR(MAX)
DECLARE @CANALIZAR INT 
DECLARE @FECHACANALIZADO DATETIME


SET @IDPROSPECTO = CAST('<#SonObligatorios/>' AS INT)

IF (ISNUMERIC(:IdEmpresa) = 1 ) AND (:IdEmpresa != '.') BEGIN SET @IDCOMPANIA = CAST(:IdEmpresa AS INT) END ELSE BEGIN SET @IDCOMPANIA = NULL END

SET @IDPETICION = '<#IDPETICION/>'
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @IDPROSPECTO = CAST('<#IdProspecto/>' AS INT)
SET @IDINDUSTRIA = CAST('<#IdIndustria/>' AS INT)
SET @IDGRUPOEMPRESARIAL = CAST('<#IDGRUPOEMPRESARIAL/>' AS INT)
SET @IDFASE = CAST('<#IdFase/>' AS INT)
SET @IDORIGEN = CAST('<#IdOrigen/>' AS INT)
SET @IDTITULO = CAST('<#idTitulo/>' AS INT)
SET @AGREGARVER = CAST('<#AgregarVer/>' AS INT)
SET @ESCLIENTE = CAST('<#EsCliente/>' AS INT)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT)

SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = CAST(<#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) AS VARCHAR(MAX)) END

SET @NOMBRE = ISNULL(:Nombre,'')
SET @APELLIDOS = ISNULL(:Apellidos,'')
SET @EMPRESA = ISNULL(:Empresa,'')
SET @ETIQUETAS = '<#LtIdEtiquetas/>'
SET @LTETIQUETASNUEVA = @ETIQUETAS
SET @LTETIQUETASORIGINAL = '<#LtIdEtiquetasOriginal/>'
SET @SEXO = '<#Sexo/>'
SET @CORREO = LOWER('<#Correo/>')
SET @TELEFONO = '<#Telefono1/>'
SET @TELEFONO2 = '<#Telefono2/>'
SET @MOVIL = '<#Movil/>'
SET @PUESTO = '<#Puesto/>'
SET @COMENTARIOS = ISNULL(:Comentarios,'')
SET @TELEFONOCORPORATIVO = '<#TelefonoCorporativo/>'
SET @PAGINAWEB = '<#PaginaWeb/>'
SET @NEMPLEADOS = '<#nEmpleados/>'

SET @PAIS = '<#Pais/>'
SET @ESTADO = '<#Estado/>'
IF @PAIS = '' BEGIN SET @PAIS = '<#SESSION.DEFAULT_PAIS/>' END
IF @ESTADO = '' BEGIN SET @ESTADO = '<#SESSION.DEFAULT_ESTADO/>' END
SET @CIUDAD = '<#Ciudad/>'
SET @PROSPECTOMUNICIPIO = '<#pMunicipio/>'
SET @CP = '<#CodigoPostal/>'
SET @CALLE = '<#Calle/>'
SET @COLONIA = '<#Colonia/>'

SET @PROSPECTOPAIS = '<#pPais/>'
SET @PROSPECTOESTADO = '<#pEstado/>'
IF @PROSPECTOPAIS = '' BEGIN SET @PROSPECTOPAIS = '<#SESSION.DEFAULT_PAIS/>' END
IF @PROSPECTOESTADO = '' BEGIN SET @PROSPECTOESTADO = '<#SESSION.DEFAULT_ESTADO/>' END
SET @PROSPECTOCIUDAD = '<#pCiudad/>'
SET @PROSPECTOCP = '<#pCodigoPostal/>'
SET @PROSPECTOCALLE = :pCalle
SET @PROSPECTOCOLONIA = '<#pColonia/>'
SET @PROSPECTOPAGINAWEB = '<#pPaginaWeb/>'

SET @FACEBOOK = '<#Facebook/>'
SET @TWITTER = '<#Twitter/>'
SET @SKYPE = '<#Skype/>'
SET @LINKEDIN = '<#Linkedin/>'
SET @GOOGLEPLUS = '<#GooglePlus/>'

SET @FECHA9 = '<#CAMPO9/>'
SET @FECHA10 = '<#CAMPO10/>'
SET @FECHA11 = '<#CAMPO11/>'
SET @FECHA12 = '<#CAMPO12/>'

SET @CAMPO1 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO1>', 0),0)  
SET @CAMPO2 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO2>', 0),0) 
SET @CAMPO3 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO3>', 0),0) 
SET @CAMPO4 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO4>', 0),0) 
SET @CAMPO5 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO5>', 0),1) 
SET @CAMPO6 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO6>', 0),1) 
SET @CAMPO7 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO7>', 0),1) 
SET @CAMPO8 =  SALESUP_CT.dbo.RemueveNoNumericos_Int_Float(ISNULL('<#CAMPO8>', 0),1)

IF @FECHA9 <> '' BEGIN SET @CAMPO9 = CONVERT(DATETIME,@FECHA9,@CONVERTCODE) END
IF @FECHA10 <> '' BEGIN SET @CAMPO10 = CONVERT(DATETIME,@FECHA10,@CONVERTCODE) END
IF @FECHA11 <> '' BEGIN SET @CAMPO11 = CONVERT(DATETIME,@FECHA11,@CONVERTCODE) END
IF @FECHA12 <> '' BEGIN SET @CAMPO12 = CONVERT(DATETIME,@FECHA12,@CONVERTCODE) END

SET @CAMPO13 = CAST(:CAMPO13 AS VARCHAR(1024))
SET @CAMPO14 = CAST(:CAMPO14 AS VARCHAR(1024))
SET @CAMPO15 = CAST(:CAMPO15 AS VARCHAR(1024))
SET @CAMPO16 = CAST(:CAMPO16 AS VARCHAR(1024))
SET @CAMPO17 = CAST(:CAMPO17 AS VARCHAR(1024))
SET @CAMPO18 = CAST(:CAMPO18 AS VARCHAR(1024))
SET @CAMPO19 = CAST(:CAMPO19 AS VARCHAR(1024))
SET @CAMPO20 = CAST(:CAMPO20 AS VARCHAR(1024))

SET @CAMPO21 = CAST(:CAMPO21 AS INT)
SET @CAMPO22 = CAST(:CAMPO22 AS INT)
SET @CAMPO23 = CAST(:CAMPO23 AS INT)
SET @CAMPO24 = CAST(:CAMPO24 AS INT)
SET @CAMPO25 = CAST(:CAMPO25 AS INT)

SET @CAMPO26 = CAST(:CAMPO26 AS VARCHAR(1024))
SET @CAMPO27 = CAST(:CAMPO27 AS VARCHAR(1024))
SET @CAMPO28 = CAST(:CAMPO28 AS VARCHAR(1024))
SET @CAMPO29 = CAST(:CAMPO29 AS VARCHAR(1024))
SET @CAMPO30 = CAST(:CAMPO30 AS VARCHAR(1024))
SET @CAMPO31 = CAST(:CAMPO31 AS VARCHAR(1024))
SET @CAMPO32 = CAST(:CAMPO32 AS VARCHAR(1024))

SET @CAMPO35 = CAST(:CAMPO35 AS VARCHAR(1024))
SET @CAMPO36 = CAST(:CAMPO36 AS VARCHAR(1024))
SET @CAMPO37 = CAST(:CAMPO37 AS VARCHAR(1024))
SET @CAMPO38 = CAST(:CAMPO38 AS VARCHAR(1024))
SET @CAMPO39 = CAST(:CAMPO39 AS VARCHAR(1024))
SET @CAMPO40 = CAST(:CAMPO40 AS VARCHAR(1024))
SET @CAMPO41 = CAST(:CAMPO41 AS VARCHAR(1024))
SET @CAMPO42 = CAST(:CAMPO42 AS VARCHAR(1024))
SET @CAMPO43 = CAST(:CAMPO43 AS VARCHAR(1024))
SET @CAMPO44 = CAST(:CAMPO44 AS VARCHAR(1024))
SET @CAMPO45 = CAST(:CAMPO45 AS VARCHAR(1024))
SET @CAMPO46 = CAST(:CAMPO46 AS VARCHAR(1024))
SET @CAMPO47 = CAST(:CAMPO47 AS VARCHAR(1024))
SET @CAMPO48 = CAST(:CAMPO48 AS VARCHAR(1024))
SET @CAMPO49 = CAST(:CAMPO49 AS VARCHAR(1024))
SET @CAMPO50 = CAST(:CAMPO50 AS VARCHAR(1024))
SET @CAMPO51 = CAST(:CAMPO51 AS VARCHAR(1024))
SET @CAMPO52 = CAST(:CAMPO52 AS VARCHAR(1024))
SET @CAMPO53 = CAST(:CAMPO53 AS VARCHAR(1024))
SET @CAMPO54 = CAST(:CAMPO54 AS VARCHAR(1024))
SET @CAMPO55 = CAST(:CAMPO55 AS VARCHAR(1024))
SET @CAMPO56 = CAST(:CAMPO56 AS VARCHAR(1024))
SET @CAMPO57 = CAST(:CAMPO57 AS VARCHAR(1024))
SET @CAMPO58 = CAST(:CAMPO58 AS VARCHAR(1024))
SET @CAMPO59 = CAST(:CAMPO59 AS VARCHAR(1024))
SET @CAMPO60 = CAST(:CAMPO60 AS VARCHAR(1024))
SET @CAMPO61 = CAST(:CAMPO61 AS VARCHAR(1024))
SET @CAMPO62 = CAST(:CAMPO62 AS VARCHAR(1024))
SET @CAMPO63 = CAST(:CAMPO63 AS VARCHAR(1024))
SET @CAMPO64 = CAST(:CAMPO64 AS VARCHAR(1024))

SET @P_CatalogoOpcion1 = CAST('<#P-CatalogoOpcion1/>' AS INT)
SET @P_CatalogoOpcion2 = CAST('<#P-CatalogoOpcion2/>' AS INT)
SET @P_CatalogoOpcion3 = CAST('<#P-CatalogoOpcion3/>' AS INT)

SET @COM_CatalogoOpcion1 = CAST('<#Com-CatalogoOpcion1/>' AS INT)  
SET @COM_CatalogoOpcion2 = CAST('<#Com-CatalogoOpcion2/>' AS INT) 
SET @COM_CatalogoOpcion3 = CAST('<#Com-CatalogoOpcion3/>' AS INT)  

SET @CANALIZAR = CAST('<#CanalizarProspecto/>' AS INT)
SET @FECHA = GETDATE()

SET @NumInterior = ISNULL(:NumInterior, '')
SET @NumExterior = ISNULL(:NumExterior, '')
SET @IDMUNICIPIOEMP = ISNULL(:EmpMunicipio, '')
SET @CCAMPO1 = ISNULL(:Campo1C, '')
SET @CCAMPO2 = ISNULL(:Campo2C, '')
SET @CCAMPO3 = ISNULL(:Campo3C, '')
SET @CCAMPO4 = ISNULL(:Campo4C, '')
SET @CCAMPO5 = ISNULL(:Campo5C, '')
SET @CCAMPO6 = ISNULL(:Campo6C, '')
SET @CCAMPO7 = ISNULL(:Campo7C, '')
SET @CCAMPO8 = ISNULL(:Campo8C, '')
SET @CCAMPO9 = ISNULL(:Campo9C, '')
SET @CCAMPO10 = ISNULL(:Campo10C, '')


IF @COM_CatalogoOpcion1 > 0 BEGIN SET @P_CatalogoOpcion1 = @COM_CatalogoOpcion1 END
IF @COM_CatalogoOpcion2 > 0 BEGIN SET @P_CatalogoOpcion2 = @COM_CatalogoOpcion2 END
IF @COM_CatalogoOpcion3 > 0 BEGIN SET @P_CatalogoOpcion3 = @COM_CatalogoOpcion3 END

IF @P_CatalogoOpcion1 = 0 BEGIN SET @P_CatalogoOpcion1 = NULL END
IF @P_CatalogoOpcion2 = 0 BEGIN SET @P_CatalogoOpcion2 = NULL END
IF @P_CatalogoOpcion3 = 0 BEGIN SET @P_CatalogoOpcion3 = NULL END

IF @COM_CatalogoOpcion1 = 0 BEGIN SET @COM_CatalogoOpcion1 = NULL END
IF @COM_CatalogoOpcion2 = 0 BEGIN SET @COM_CatalogoOpcion2 = NULL END
IF @COM_CatalogoOpcion3 = 0 BEGIN SET @COM_CatalogoOpcion3 = NULL END

IF ISNUMERIC(@EMPRESA) = 1 BEGIN SELECT @EMPRESA = EMPRESA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA END

IF @IDFASE = 0 AND @ESCLIENTE = 0 BEGIN SELECT TOP 1 @IDFASE = IDFASE FROM <#SESSION.DB/>.dbo.PROSPECTOS_FASES WHERE IDEMPRESA = @IDEMPRESA AND FASECLIENTE = 0 ORDER BY ORDEN  END 
IF @IDFASE = 0 AND @ESCLIENTE = 1 BEGIN SELECT TOP 1 @IDFASE = IDFASE FROM <#SESSION.DB/>.dbo.PROSPECTOS_FASES WHERE IDEMPRESA = @IDEMPRESA AND FASECLIENTE = 1 ORDER BY ORDEN  END 

IF @IDORIGEN = 0 BEGIN SELECT TOP 1 @IDORIGEN = IDORIGEN FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES WHERE IDEMPRESA = @IDEMPRESA ORDER BY 1  END

IF @IDINDUSTRIA = 0 BEGIN SELECT TOP 1 @IDINDUSTRIA = IDINDUSTRIA FROM <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS WHERE IDEMPRESA = @IDEMPRESA ORDER BY 1  END
IF @IDGRUPOEMPRESARIAL = 0 BEGIN SELECT TOP 1 @IDGRUPOEMPRESARIAL = IDCOMPANIAGRUPO FROM <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS WHERE IDEMPRESA = @IDEMPRESA ORDER BY 1  END

SET @TITULO = ''
IF @IDTITULO > 0 BEGIN SELECT TOP 1 @TITULO = TITULO FROM <#SESSION.DB/>.dbo.EMPRESAS_TITULOS WHERE IDTITULO = @IDTITULO AND IDEMPRESA = @IDEMPRESA END 



DECLARE @CORREO_ANTERIOR VARCHAR(MAX), @TELEFONO1_ANTERIOR VARCHAR(MAX), @TELEFONO2_ANTERIOR VARCHAR(MAX), @MOVIL_ANTERIOR VARCHAR(MAX)
DECLARE @NOMBRE_ANTERIOR VARCHAR(MAX), @APELLIDOS_ANTERIOR VARCHAR(MAX)
DECLARE @IDFASE_ANTERIOR INT, @IDOPORTUNIDAD INT
SET @IDOPORTUNIDAD = CAST('<#IDOPORTUNIDAD/>' AS INT)

DECLARE @NOMBRE_QUIEN_CANALIZA_ANT VARCHAR(MAX)
DECLARE @TKPM_ANT VARCHAR(256)
DECLARE @CANALIZADOEL_ANT DATETIME


SELECT 
	 @CORREO_ANTERIOR = CORREO, @TELEFONO1_ANTERIOR = TELEFONO, @TELEFONO2_ANTERIOR = TELEFONO2, 
	 @MOVIL_ANTERIOR = MOVIL, @NOMBRE_ANTERIOR = NOMBRE, @APELLIDOS_ANTERIOR = APELLIDOS, 
	 @IDFASE_ANTERIOR = IDFASE, @ESCLIENTE = ESCLIENTE,@NOMBRE_QUIEN_CANALIZA_ANT=USRCANALIZO,@CANALIZADOEL_ANT=CANALIZADOEL,@TKPM_ANT=TKPM
FROM 
	 <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK)
WHERE 
	  IDPROSPECTO = @IDPROSPECTO

/* se activan las acciones de las fases */
 IF @IDFASE_ANTERIOR <> @IDFASE
 BEGIN
 	  DECLARE @FASETXT VARCHAR(MAX)
      SELECT @FASETXT = ' - ' + ISNULL(FASE,'') FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE = @IDFASE AND IDEMPRESA = @IDEMPRESA
  	  EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @IDFASE, @IDPROSPECTO, @IDOPORTUNIDAD
	  IF @ESCLIENTE=1
   	      EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO , 22, @IDPROSPECTO, @CONVERTCODE, @FASETXT, ''
 	  ELSE
	   	  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO , 23, @IDPROSPECTO, @CONVERTCODE, @FASETXT, ''
 END   

/*EL PROSPECTO ES UN PROSPECTO CANALIZADO*/
IF (@TKPM_ANT IS NOT NULL)
   BEGIN
     SET @NOMBRE_QUIEN_CANALIZA=@NOMBRE_QUIEN_CANALIZA_ANT
	 SET @FECHACANALIZADO=@CANALIZADOEL_ANT
   END

 
 /* ACTUALIZA EL PROSPECTO */
UPDATE <#SESSION.DB/>.dbo.PROSPECTOS
SET
   NOMBRE = @NOMBRE, APELLIDOS = @APELLIDOS, TITULO = @TITULO, SEXO = @SEXO,
   CORREO = @CORREO, TELEFONO = @TELEFONO, TELEFONO2 = @TELEFONO2, MOVIL = @MOVIL,
   PUESTO = @PUESTO, IDFASE = @IDFASE, IDORIGEN = @IDORIGEN, COMENTARIOS =  @COMENTARIOS,
   FACEBOOK = @FACEBOOK, TWITTER = @TWITTER, SKYPE = @SKYPE, LINKEDIN = @LINKEDIN, GOOGLEPLUS = @GOOGLEPLUS,
   
   EMPRESA = @EMPRESA, IDCOMPANIA = @IDCOMPANIA, 
   URL = @PROSPECTOPAGINAWEB, NOEMPLEADOS = @NEMPLEADOS,
   IDPAIS = @PROSPECTOPAIS, IDESTADO = @PROSPECTOESTADO, CIUDAD = @PROSPECTOCIUDAD, CODIGOPOSTAL = @PROSPECTOCP,
   IDMUNICIPIO = @PROSPECTOMUNICIPIO,
   DIRECCION1 = @PROSPECTOCALLE, DIRECCION2 = @PROSPECTOCOLONIA,
   
   
   CAMPO1 = @CAMPO1, CAMPO2 = @CAMPO2, CAMPO3 = @CAMPO3, CAMPO4 = @CAMPO4, 
   CAMPO5 = @CAMPO5, CAMPO6 = @CAMPO6, CAMPO7 = @CAMPO7, CAMPO8 = @CAMPO8, 
   CAMPO9 = @CAMPO9, CAMPO10 = @CAMPO10, CAMPO11 = @CAMPO11, CAMPO12 = @CAMPO12, 
   CAMPO13 = @CAMPO13, CAMPO14 = @CAMPO14, CAMPO15 = @CAMPO15, CAMPO16 = @CAMPO16, 
   CAMPO17 = @CAMPO17, CAMPO18 = @CAMPO18, CAMPO19 = @CAMPO19, CAMPO20 = @CAMPO20, 
   CAMPO21 = @CAMPO21, CAMPO22 = @CAMPO22, CAMPO23 = @CAMPO23, CAMPO24 = @CAMPO24, 
   CAMPO25 = @CAMPO25, CAMPO26 = @CAMPO26, CAMPO27 = @CAMPO27, CAMPO28 = @CAMPO28, 
   CAMPO29 = @CAMPO29, CAMPO30 = @CAMPO30, CAMPO31 = @CAMPO31, CAMPO32 = @CAMPO32,
   
   CAMPO35 = @CAMPO35, CAMPO36 = @CAMPO36, CAMPO37 = @CAMPO37, CAMPO38 = @CAMPO38, CAMPO39 = @CAMPO39, 
   CAMPO40 = @CAMPO40, CAMPO41 = @CAMPO41, CAMPO42 = @CAMPO42, CAMPO43 = @CAMPO43, CAMPO44 = @CAMPO44, 
   CAMPO45 = @CAMPO45, CAMPO46 = @CAMPO46, CAMPO47 = @CAMPO47, CAMPO48 = @CAMPO48, CAMPO49 = @CAMPO49, 
   CAMPO50 = @CAMPO50, CAMPO51 = @CAMPO51, CAMPO52 = @CAMPO52, CAMPO53 = @CAMPO53, CAMPO54 = @CAMPO54, 
   CAMPO55 = @CAMPO55, CAMPO56 = @CAMPO56, CAMPO57 = @CAMPO57, CAMPO58 = @CAMPO58, CAMPO59 = @CAMPO59, 
   CAMPO60 = @CAMPO60, CAMPO61 = @CAMPO61, CAMPO62 = @CAMPO62, CAMPO63 = @CAMPO63, CAMPO64 = @CAMPO64, 
   
   IDCATALOGOOPCION1 = @P_CatalogoOpcion1, IDCATALOGOOPCION2 = @P_CatalogoOpcion2, IDCATALOGOOPCION3 = @P_CatalogoOpcion3,
   CAMBIOLOCAL = 2, USRCANALIZO = @NOMBRE_QUIEN_CANALIZA, CANALIZADOEL = @FECHACANALIZADO, APROBACIONESTADO = @AUTORIZACIONPENDIENTE, APROBACIONFECHA = @AUTORIZACIONFECHA,
   ULTIMAMODIFICACION = GETDATE()
WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = @IDEMPRESA

IF @COMPARTIRCON != ''
BEGIN
	 DECLARE @IDCOMPARTIRCON INT
	 SELECT  @IDCOMPARTIRCON = IDUSUARIO FROM <#SESSION.DB/>.DBO.USUARIOS WHERE TKU = @COMPARTIRCON;
	 EXEC <#SESSION.DB/>.DBO.SP_COMPARTIR_PROSPECTOS @IDUSUARIO, @IDEMPRESA,@IDPROSPECTO ,@IDCOMPARTIRCON, @CONVERTCODE
END

IF(@LTETIQUETASORIGINAL <> '')
BEGIN
	 /*SELECCIONA LAS ETIQUETAS A ELIMINAR*/
	 INSERT INTO @ELIMINARETIQUETAS (IDETIQUETA)
	 SELECT A.splitvalue 
	 FROM <#SESSION.DB/>.dbo.Split(@LTETIQUETASORIGINAL, ',') A 
	 LEFT JOIN <#SESSION.DB/>.dbo.Split(@LTETIQUETASNUEVA, ',') N ON A.splitvalue = N.splitvalue 
	 WHERE N.splitvalue IS NULL GROUP BY  A.splitvalue
	 
	 /* ELIMINAR ETIQUETAS  */
	 DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WITH(ROWLOCK) 
	 WHERE IDPROSPECTO = @IDPROSPECTO AND IDETIQUETA IN (SELECT IDETIQUETA FROM @ELIMINARETIQUETAS)

	 /* NOTIFICAR A ELIMINACIONES PARA LA APP */
	 INSERT INTO <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK) (IDTABLA, IDNUEVO, IDELIMINADO, TIPO, IDEMPRESA, FECHAHORA) 
	 SELECT 6, @IDPROSPECTO, IDETIQUETA, 1, @IDEMPRESA, GETDATE() FROM @ELIMINARETIQUETAS
END

/* AGREGA O ELIMINA ETIQUETAS AL PROSPECTO*/
IF @ETIQUETAS <> ''
BEGIN
	 /* SELECCIONA LAS NUEVAS ETIQUETAS */
	 INSERT INTO @NUEVASETIQUETAS (IDETIQUETA)
	 SELECT N.splitvalue 
	 FROM <#SESSION.DB/>.dbo.Split(@LTETIQUETASNUEVA, ',') N 
	 LEFT JOIN <#SESSION.DB/>.dbo.Split(@LTETIQUETASORIGINAL, ',') A ON A.splitvalue = N.splitvalue  
	 WHERE A.splitvalue IS NULL AND N.splitvalue NOT IN (SELECT IDETIQUETA FROM <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WHERE IDPROSPECTO = @IDPROSPECTO) 
	 GROUP BY  N.splitvalue

	 /* AGREGAR NUEVAS ETIQUETAS */
	 INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WITH(ROWLOCK) (IDPROSPECTO, IDETIQUETA)
	 SELECT @IDPROSPECTO, IDETIQUETA FROM @NUEVASETIQUETAS

	 /* NOTIFICAR A LA APP DE LA MODIFICACION DEL PROSPECTO */
	 UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = @IDEMPRESA
	 DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
	 INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES ( IDEMPRESA, IDTABLA, FECHAHORA ) VALUES( @IDEMPRESA, 4, GETDATE() )

	 /* EJECTUAR PROCEDIMIENTOS PARA LAS ETIQUETAS */
	 EXEC <#SESSION.DB/>.DBO.SP_ENVIA_AUTORESPONDER_ESPECIFICO @IDEMPRESA, @IDPROSPECTO, @LTETIQUETASNUEVA
	 EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, 4, @IDPROSPECTO, @CONVERTCODE, '', ''

END
/* @ETIQUETAS <> '' */





/* SI ESTA LIGADO A UNA COMPAÑIA SE ACTUALIZA LA INFORMACION */
IF @IDCOMPANIA > 0
BEGIN

	/* Actualiza Info de la Empresa*/
	
	UPDATE <#SESSION.DB/>.dbo.COMPANIAS WITH(ROWLOCK)
	SET
	IDINDUSTRIA = @IDINDUSTRIA,
	URL = @PAGINAWEB,
	TELEFONOCORPORATIVO = @TELEFONOCORPORATIVO,
	DIRECCION1 = @CALLE,
	DIRECCION2 = @COLONIA,
	CIUDAD = @CIUDAD,
	CODIGOPOSTAL = @CP,
	IDESTADO = @ESTADO,
	IDPAIS = @PAIS,
	NEMPLEADOS = @NEMPLEADOS,
	IDCOMPANIAGRUPO = @IDGRUPOEMPRESARIAL,
	IDCATALOGOOPCION1 = @COM_CatalogoOpcion1, 
	IDCATALOGOOPCION2 = @COM_CatalogoOpcion2, 
	IDCATALOGOOPCION3 = @COM_CatalogoOpcion3,
		 NUMERO_INTERIOR = @NumInterior,
		 NUMERO_EXTERIOR = @NumExterior,
		 IDMUNICIPIO = @IDMUNICIPIOEMP,
		 CCAMPO1 = @CCAMPO1,
		 CCAMPO2 = @CCAMPO2,
		 CCAMPO3 = @CCAMPO3,
		 CCAMPO4 = @CCAMPO4,
		 CCAMPO5 = @CCAMPO5,
		 CCAMPO6 = @CCAMPO6,
		 CCAMPO7 = @CCAMPO7,
		 CCAMPO8 = @CCAMPO8,
		 CCAMPO9 = @CCAMPO9,
		 CCAMPO10 = @CCAMPO10 
	WHERE IDEMPRESA = @IDEMPRESA AND IDCOMPANIA = @IDCOMPANIA

END /* @IDCOMPANIA > 0 */
 


/* DETERMINA SI SE MODIFICO INFORMACION ESENCIAL DEL PROSPECTO */

DECLARE @C_CORREO INT, @C_TEL1 INT, @C_TEL2 INT, @C_MOVIL INT, @C_NOMBRE INT, @C_APELLIDOS INT
DECLARE @COMENTARIODECAMBIOS VARCHAR(MAX)

SET @COMENTARIODECAMBIOS = ''

IF (@CORREO_ANTERIOR IS NOT NULL) AND (@CORREO_ANTERIOR <> LOWER(@CORREO)) SET @C_CORREO=1
IF (@TELEFONO1_ANTERIOR IS NOT NULL) AND (@TELEFONO1_ANTERIOR <> @TELEFONO) SET @C_TEL1=1
IF (@TELEFONO2_ANTERIOR IS NOT NULL) AND (@TELEFONO2_ANTERIOR <> @TELEFONO2) SET @C_TEL2=1
IF (@MOVIL_ANTERIOR IS NOT NULL) AND (@MOVIL_ANTERIOR <> @MOVIL) SET @C_MOVIL=1 
IF (@NOMBRE_ANTERIOR IS NOT NULL) AND (@NOMBRE_ANTERIOR <> @NOMBRE) SET @C_NOMBRE=1 
IF (@APELLIDOS_ANTERIOR IS NOT NULL) AND (@APELLIDOS_ANTERIOR <> @APELLIDOS) SET @C_APELLIDOS=1 

IF (@CORREO_ANTERIOR IS NOT NULL) AND (@CORREO IS NULL) SET @C_CORREO=2
IF (@TELEFONO1_ANTERIOR IS NOT NULL) AND (@TELEFONO IS NULL) SET @C_TEL1=2
IF (@TELEFONO2_ANTERIOR IS NOT NULL) AND (@TELEFONO2 IS NULL) SET @C_TEL2=2
IF (@MOVIL_ANTERIOR IS NOT NULL) AND (@MOVIL IS NULL) SET @C_MOVIL=2
IF (@NOMBRE_ANTERIOR IS NOT NULL) AND (@NOMBRE IS NULL) SET @C_NOMBRE=2
IF (@APELLIDOS_ANTERIOR IS NOT NULL) AND (@APELLIDOS IS NULL) SET @C_APELLIDOS=2

  
IF @C_CORREO=1 
 BEGIN
 SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Correo ha sido cambiado.'
 IF LEN(LTRIM(RTRIM(REPLACE(@CORREO_ANTERIOR,' ',''))))>0
   SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Correo anterior: '+@CORREO_ANTERIOR+'. '
 SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'  
 END   

IF @C_TEL1=1 
   BEGIN
   SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono 1 ha sido cambiado.'
   IF LEN(LTRIM(RTRIM(REPLACE(@TELEFONO1_ANTERIOR,' ',''))))>0
    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Teléfono anterior: '+@TELEFONO1_ANTERIOR+'. '
   SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END

IF @C_TEL2=1
   BEGIN
    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono 2 ha sido cambiado.'
	IF LEN(LTRIM(RTRIM(REPLACE(@TELEFONO2_ANTERIOR,' ',''))))>0
     SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Teléfono anterior: '+@TELEFONO2_ANTERIOR+'. '
    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>' 
   END	
IF @C_MOVIL=1
   BEGIN
    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono móvil ha sido cambiado.'
	IF LEN(LTRIM(RTRIM(REPLACE(@MOVIL_ANTERIOR,' ',''))))>0
     SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Móvil anterior:'+@MOVIL_ANTERIOR+'. '
    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END	
IF @C_NOMBRE=1 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Nombre ha sido cambiado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@NOMBRE_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Nombre anterior: '+@NOMBRE_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END		
IF @C_APELLIDOS=1 
   BEGIN
      SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Apellido ha sido cambiado.'
	  IF LEN(LTRIM(RTRIM(REPLACE(@APELLIDOS_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Apellido anterior: '+@APELLIDOS_ANTERIOR+'. '
      SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END	

IF @C_CORREO=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Correo ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@CORREO_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Correo anterior: '+@CORREO_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END
IF @C_TEL1=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono 1 ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@TELEFONO1_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Teléfono anterior: '+@TELEFONO1_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END		
IF @C_TEL2=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono 2 ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@TELEFONO2_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Teléfono anterior: '+@TELEFONO2_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END	
IF @C_MOVIL=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Teléfono Movil ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@MOVIL_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Móvil anterior: '+@MOVIL_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END		
IF @C_NOMBRE=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Nombre ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@NOMBRE_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Nombre anterior: '+@NOMBRE_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END	
IF @C_APELLIDOS=2 
   BEGIN
   		SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + 'El Apellido ha sido eliminado.'
		IF LEN(LTRIM(RTRIM(REPLACE(@APELLIDOS_ANTERIOR,' ',''))))>0
		    SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + ' Apellido anterior: '+@APELLIDOS_ANTERIOR+'. '
        SET @COMENTARIODECAMBIOS = @COMENTARIODECAMBIOS + '<br/>'
   END

IF (@COMENTARIODECAMBIOS > '')
BEGIN
    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDUSUARIO, COMENTARIO, SISTEMA)
    VALUES (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @COMENTARIODECAMBIOS, 1)
END
   
DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE()) 

EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO <#SESSION.IDUSUARIO/>,@FECHA
