//[idprospecto|Integer,idoportunidad|Integer,session.db|Untyped,]

DECLARE @IDPROSPECTO INT
DECLARE @IDOPORTUNIDAD INT
declare @tko varchar(64)
SET @IDPROSPECTO = isnull(:IDPROSPECTO,0)
SET @IDOPORTUNIDAD = ISNULL(:IDOPORTUNIDAD,0)
set @tko = ''
IF @IDPROSPECTO = 0
SELECT  @IDPROSPECTO = IDPROSPECTO, @tko = tko FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD

SELECT @IDPROSPECTO as IdProspecto, @IDOPORTUNIDAD as IdOportunidad, @tko as tko, TKP AS TOKENP,T.*, CONVERT(VARCHAR(12),T.FECHA,103) AS F 
FROM  (
	SELECT 1 AS TIPO, 'Recordatorio' AS EVENTO, RECORDATORIO AS CONCEPTO, FECHAHORA AS FECHA ,UPPER(INICIALES) AS USUARIO, U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') AS NOMBREUSUARIO, IDRECORDATORIO AS ID, CAST(TKREC AS VARCHAR(MAX)) AS TOKEN, U.IDUSUARIO AS DUENIO
	FROM <#SESSION.DB/>.DBO.RECORDATORIOS R JOIN <#SESSION.DB/>.DBO.USUARIOS U ON R.IDUSUARIO = U.IDUSUARIO WHERE IDPROSPECTO = @IDPROSPECTO AND COMPLETADO = 0
	UNION
	SELECT 2, 'Cita', ASUNTO, FECHA_INICIO,UPPER(INICIALES), U.NOMBRE+' '+ISNULL(U.APELLIDOS,'') AS NOMBREUSUARIO, C.IDCITA, TKC, U.IDUSUARIO
	FROM <#SESSION.DB/>.DBO.CITAS C JOIN <#SESSION.DB/>.DBO.CITAS_INVITADOS I ON C.IDCITA  = I.IDCITA
	 JOIN <#SESSION.DB/>.DBO.USUARIOS U ON C.IDUSUARIO_CREACION = U.IDUSUARIO
	WHERE TIPOPERSONA = 1 AND I.IDPERSONA=  @IDPROSPECTO AND C.ACTIVO = 1
	AND FECHA_INICIO > GETDATE()-7
	UNION
	SELECT 3,'Tarea', TITULO, FECHA_VENCIMIENTO,UPPER(INICIALES), I.NOMBRE+' '+ISNULL(I.APELLIDOS,'') AS NOMBREUSUARIO, IDTAREA, TKTR, I.IDUSUARIO 
	FROM <#SESSION.DB/>.DBO.TAREAS C JOIN <#SESSION.DB/>.DBO.USUARIOS I ON C.IDREALIZADOR  = I.IDUSUARIO WHERE IDPROSPECTO =  @IDPROSPECTO AND IDESTADO NOT IN (5,3)
	UNION
	SELECT 6, 'Correo programado', UE.ASUNTO, UE.FECHAPROGRAMADA, UPPER(U.INICIALES), U.NOMBRE+' '+ISNULL(U.APELLIDOS,''), IDEMAIL, '', UE.IDUSUARIO
	FROM <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE
	LEFT JOIN USUARIOS U ON U.IDUSUARIO = UE.IDUSUARIO
	WHERE IDPROSPECTO = @IDPROSPECTO AND ESTADO = 3 AND ISNULL(UE.IDOPORTUNIDAD,0) = @IDOPORTUNIDAD 
) AS T, <#SESSION.DB/>.DBO.PROSPECTOS P 
WHERE IDPROSPECTO = @IDPROSPECTO
ORDER BY T.FECHA

