//[session.idempresa|Untyped,tkeliminar|Text,tknuevo|Text,session.db|Untyped,session.idusuario|Untyped,]
-- DELETE
DECLARE @FECHA DATETIME
DECLARE @IDEMPRESA INT 
DECLARE @TKELIMINAR VARCHAR(256) 
DECLARE @TKNUEVO VARCHAR(256) 
DECLARE @IDORIGENELIMINAR INT 
DECLARE @IDORIGENNUEVO INT 


SET @FECHA = GETDATE()
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TKELIMINAR=ISNULL(:TKELIMINAR, '') 
SET @TKNUEVO=ISNULL(:TKNUEVO, '') 

SELECT @IDORIGENELIMINAR=IDORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/>  AND TK=@TKELIMINAR 
SELECT @IDORIGENNUEVO =IDORIGEN FROM <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND TK=@TKNUEVO 



UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET IDORIGEN = @IDORIGENNUEVO WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDORIGEN = @IDORIGENELIMINAR

INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) VALUES (10,@IDORIGENNUEVO,@IDORIGENELIMINAR,1,<#SESSION.IDEMPRESA/>,GETDATE())

DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> and IDORIGEN=@IDORIGENELIMINAR

EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO <#SESSION.IDUSUARIO/>,@FECHA