//[buscarnombre|Text,]
--select
DECLARE @BUSCARNOMBRE VARCHAR(1000)
DECLARE @SEXO VARCHAR(20)
SET @BUSCARNOMBRE=:BUSCARNOMBRE
SET @SEXO=''

SELECT @SEXO=dbo.RetornaSexoNombre(@BUSCARNOMBRE)

SELECT @SEXO AS SEXO