//[session.idempresa|Untyped,session.db|Untyped,titulo|Text,]

--SELECT
DECLARE @IDEMPRESA INT, @EXISTE INT
DECLARE @TITULO VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @TITULO = <#SESSION.DB/>.dbo.PreparaCadena(:TITULO)


SELECT @EXISTE = COUNT(*) FROM <#SESSION.DB/>.dbo.EMPRESAS_TITULOS WHERE IDEMPRESA = @IDEMPRESA AND TITULO = @TITULO

IF @EXISTE = 0
BEGIN
	 INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_TITULOS (IDEMPRESA, TITULO) VALUES (@IDEMPRESA, @TITULO)
END

SELECT TOP 1 idTITULO AS Id FROM <#SESSION.DB/>.dbo.EMPRESAS_TITULOS 
WHERE IDEMPRESA = @IDEMPRESA AND TITULO = @TITULO
ORDER BY 1 DESC