//[session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,idventana|Integer,]
--SELECT
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT
DECLARE @DBNAME VARCHAR(200)
DECLARE @CONTAR TINYINT
DECLARE @IDPANTALLA INT
SET @DBNAME = '<#SESSION.DB/>'
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @IDPANTALLA = ISNULL(:IDVENTANA, 0)
SET @CONTAR = 1
DECLARE @TOP VARCHAR(50)
SET @TOP= ''

EXEC <#SESSION.DB/>.dbo.SP_LISTA_PROSPECTOS_EMPRESA  @IDEMPRESA, @IDUSUARIO, @NIVELUSUARIO,@IDGRUPO,@MAILCONFIG,@IDPANTALLA,@CONTAR,@TOP