//[listap|Integer,session.idempresa|Untyped,session.idusuario|Untyped,razones|Integer,comentario|Text,session.convertcode|Untyped,tkp|Text,session.db|Untyped,]
--insert
DECLARE @LISTA VARCHAR(MAX)
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @RAZONES INT
DECLARE @COMENTARIO VARCHAR(258)
DECLARE @CONVERTCODE INT
SET @LISTA = ISNULL(:LISTAP,'') 
SET @IDEMPRESA= CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO   =CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @RAZONES = ISNULL(:RAZONES,0)
SET @COMENTARIO =  isnull(:COMENTARIO ,'')
SET @CONVERTCODE  = CAST('<#SESSION.CONVERTCODE/>' AS INT)


DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @LISTA = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END

EXEC <#SESSION.DB/>.DBO.SP_DESCARTAR_CLIENTE @IDUSUARIO, @IDEMPRESA, @LISTA, @CONVERTCODE, @COMENTARIO,@RAZONES