//[idprospecto|Integer|297958,tkp|Text|,session.db|Untyped|salesup_db1,session.idempresa|Untyped|11811,session.gmt|Untyped|1]
--select
declare @idprospecto int
declare @tkp varchar(max)

set @idprospecto = :IDPROSPECTO 
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, <#SESSION.IDEMPRESA/>) END 
DECLARE @GMT INT

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
/*
SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT  WITH(NOLOCK)  WHERE GMT= @GMT*/


SELECT 
SALESUP_CT.dbo.esCanalizado(S.TK, S.TKM) AS esCanalizado,
(CASE WHEN UE.ERRORES>=3 THEN 1 ELSE 0 END) AS ESTADOEMAIL,
(CASE WHEN UE.FECHALEIDO IS NOT NULL THEN 1 ELSE 0 END ) AS EMAILEIDO, UE.FECHALEIDO,
(CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,
(CASE WHEN USMS.ESTADO=0 AND USMS.ERRORES>0 THEN 1 ELSE 0 END) AS ESTADOSMS,
(CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,
SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,S.FECHAHORA) AS FECHAHORA, 
p.descartado,
S.IDSEGUIMIENTO,S.IDPROSPECTO, S.IDOPORTUNIDAD, S.IDUSUARIO,S.IDSEGUIMIENTOCATEGORIA, S.IDEMAIL,S.TIPO_SEGUIMIENTO,
LTRIM(RTRIM(CAST(S.COMENTARIO AS VARCHAR(MAX)))) AS COMENTARIO, S.SISTEMA,S.ID_ANT,S.ULTIMAMODIFICACION,S.LATITUD, S.LONGITUD,S.DIRECCION, S.IDPETICION, S.IDRELACIONADO,
CASE WHEN S.SEGUIMIENTODE IS NULL THEN ISNULL(U.INICIALES, '--') ELSE S.SEGUIMIENTODE END AS INICIALES, 
CASE WHEN S.SEGUIMIENTODE IS NULL THEN U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') ELSE '' END AS EJECUTIVO_NOMBRE, 

CASE S.TIPO_SEGUIMIENTO WHEN 7 THEN T.TKTR ELSE '' END AS TK, P.TKP,
S.DURACION

FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) 
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK)  ON S.IDPROSPECTO=P.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK)  ON  S.IDUSUARIO = U.IDUSUARIO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON S.IDPROSPECTO = UE.IDPROSPECTO AND UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON S.IDPROSPECTO = USMS.IDPROSPECTO AND USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7
WHERE S.IDPROSPECTO = @idprospecto AND  S.IDOPORTUNIDAD IS NULL AND
P.IDEMPRESA = <#SESSION.IDEMPRESA/> 
order by S.FECHAHORA desc