//[session.idempresa|Untyped,idp|Integer,session.db|Untyped,]
--SELECT

DECLARE @IDPROSPECTO INT, @IDEMPRESA INT
DECLARE @NOMBRE VARCHAR(MAX), @EMPRESA VARCHAR(MAX)

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDPROSPECTO = CAST(ISNULL(:IDP,0) AS INT)

SELECT NOMBRE +' '+ ISNULL(APELLIDOS,'') AS NombreProspecto,  EMPRESA as Empresa
FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = @IDEMPRESA