//[session.db|Untyped,aidusuario|Integer,aidprospecto|Integer,session.idempresa|Untyped,session.idusuario|Untyped,]
DECLARE @AIDUSUARIO INT
DECLARE @AIDPROSPECTO INT
SET @AIDUSUARIO=ISNULL(:AIDUSUARIO,0)
SET @AIDPROSPECTO=ISNULL(:AIDPROSPECTO,0)

DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS WHERE IDUSUARIO=@AIDUSUARIO AND IDPROSPECTO=@AIDPROSPECTO
INSERT INTO <#SESSION.DB/>.dbo.ELIMINACIONES WITH (ROWLOCK) (IDTABLA,IDELIMINADO,TIPO,IDUSUARIO,FECHAHORA) VALUES(4,@AIDPROSPECTO,2,@AIDUSUARIO,GETDATE())

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 

EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>, 17, @AIDPROSPECTO, 103, 'Ha sido descartado un prospecto compartido',''