//[idc|Integer,v|Text,idp|Integer,session.convertcode|Untyped,session.idempresa|Untyped,tkp|Text,session.db|Untyped,]
-- SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @IDPROSPECTO INT, @INDICE INT, @CONVERTCODE INT
DECLARE @VALOR VARCHAR(MAX) 

SET @INDICE = ISNULL(:IDC,0) 
SET @VALOR = REPLACE(:V, '.', '') 
SET @IDPROSPECTO = ISNULL(:IDP,0) 
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT )
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @TKP VARCHAR(64)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = CAST(<#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) AS VARCHAR(MAX)) END




DECLARE @PROSPS VARCHAR(256)
 
   IF ( @INDICE IN (9, 10, 11, 12) ) 
     BEGIN
      SET  @PROSPS = <#SESSION.DB/>.dbo.ValidaCamposSugeridos(@INDICE, CONVERT(DATETIME, @VALOR, @CONVERTCODE), @IDPROSPECTO, @IDEMPRESA )
     END
   ELSE 
     BEGIN
      SET  @PROSPS = <#SESSION.DB/>.dbo.ValidaCamposSugeridos(@INDICE, @VALOR, @IDPROSPECTO, @IDEMPRESA )
     END

SELECT P.IDPROSPECTO AS IdP , P.Descartado, CAST(ISNULL(P.NOMBRE, '') AS VARCHAR(256))+ ' ' + CAST(ISNULL(P.APELLIDOS, '') AS VARCHAR(256)) AS Prospecto,
U.IdUsuario , U.NOMBRE + ' ' + U.APELLIDOS +' ('+ U.INICIALES+ ')' as Usuario
FROM <#SESSION.DB/>.dbo.PROSPECTOS P , <#SESSION.DB/>.dbo.USUARIOS U
WHERE P.IDPROSPECTO in( select Splitvalue from  <#SESSION.DB/>.dbo.split(@PROSPS, ',')) AND U.IDUSUARIO = P.IDUSUARIO
