//[edo|Text,pais|Text,tconsulta|Integer,]
--select
DECLARE @IDESTADO VARCHAR(MAX), @IDPAIS VARCHAR(MAX)
DECLARE @NESTADOS INT

SET @IDESTADO = isnull(:EDO,'')
SET @IDPAIS = isnull(:PAIS,'')

DECLARE @TIPOCOSULTA INT
SET @TIPOCOSULTA = CAST(isnull(:tConsulta,0) AS INT)

SELECT @NESTADOS = COUNT(*) FROM SALESUP_CT.dbo.MUNICIPIOS WHERE IDESTADO = @IDESTADO AND IDPAIS = @IDPAIS

IF @TIPOCOSULTA = 1
BEGIN
	IF @NESTADOS > 0
	BEGIN
	  SELECT IDMUNICIPIO as value, MUNICIPIO as Opcion FROM SALESUP_CT.dbo.MUNICIPIOS WHERE IDESTADO = @IDESTADO AND IDPAIS = @IDPAIS ORDER BY MUNICIPIO
	 END
	 ELSE
	 BEGIN
	  SELECT '-1' AS value , '(... No disponible ...)' as Opcion
     END 
END
ELSE
BEGIN
	IF @NESTADOS > 0
	BEGIN
	 SELECT IDMUNICIPIO, MUNICIPIO FROM SALESUP_CT.dbo.MUNICIPIOS WHERE IDESTADO = @IDESTADO AND IDPAIS = @IDPAIS ORDER BY MUNICIPIO
	END
	ELSE
	BEGIN
	 SELECT '-1' AS IDMUNICIPIO , '(... No disponible ...)' as MUNICIPIO
	END 
END





