//[session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,tkcom|Text,idpantalla|Integer,start|Integer,howmany|Integer,session.multimoneda|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT
DECLARE @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @SQL VARCHAR(MAX)
DECLARE @DBNAME VARCHAR(MAX)
DECLARE @IDPANTALLA INT
DECLARE @CONTAR TINYINT
DECLARE @MULTIMONEDA INT
DECLARE @TIPODECAMBIODEFAULT MONEY = 1
SET @DBNAME = '<#SESSION.DB/>'
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @TkCom = dbo.ValidaToken(isnull(:TKCOM,'')) 
SET @IDCOMPANIA = 0
SET @IDPANTALLA = ISNULL(:IDPANTALLA, 0)
SET @CONTAR = 0
SET @MULTIMONEDA = <#SESSION.MULTIMONEDA/>
DECLARE @TOP VARCHAR(50)
DECLARE @START INT SET @START = ISNULL(:START,1)
DECLARE @HOWMANY INT SET @HOWMANY = ISNULL(:HOWMANY,50)
SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))


IF(@MULTIMONEDA > 0)
BEGIN
     SELECT @TIPODECAMBIODEFAULT = TIPODECAMBIO FROM <#SESSION.DB/>.DBO.MONEDAS WHERE IDEMPRESA = @IDEMPRESA AND PORDEFECTO = 1
END

EXEC <#SESSION.DB/>.dbo.SP_LISTA_OPORTUNIDADES_EMPRESAS @IDEMPRESA,@IDUSUARIO,@NIVELUSUARIO,@IDGRUPO,@MAILCONFIG,@TkCom,@IDCOMPANIA,@CONTAR,@IDPANTALLA, @TOP, @TIPODECAMBIODEFAULT