//[ida|Text,session.idempresa|Untyped,doc|Text,session.db|Untyped,tk|Text,]
--SELECT 
DECLARE @IDARCHIVO INT, @IDEMPRESA INT, @DOC INT
DECLARE @TK VARCHAR(MAX)
SET @IDARCHIVO = CAST(:IDA AS INT)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @DOC = CAST(:DOC AS INT)

SET @TK = ISNULL(:TK,'')



IF @DOC = 0
BEGIN
  IF @TK != '' BEGIN SELECT @IDARCHIVO = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ARCHIVOS WHERE TKARCH = @TK END

  SELECT SALESUP_CT.dbo.NombreRealArchivo(ARCHIVO) AS Archivo, SALESUP_CT.dbo.VerArchivo(ARCHIVO,0) AS Ver, SALESUP_CT.dbo.SoloIconoArchivo(ARCHIVO,0) AS Icono,
  SALESUP_CT.DBO.TamanioArchivo(PESO) AS Tamanio, SALESUP_CT.dbo.LinkArchivo(AMAZON, ARCHIVO, @IDEMPRESA)  AS Link, IDPROSPECTOARCHIVO AS IdArchivo  
  FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS WHERE IDPROSPECTOARCHIVO = @IDARCHIVO
  ORDER BY 1

END
ELSE
BEGIN

  SELECT SALESUP_CT.dbo.NombreRealArchivo(NOMBRE_DOCUMENTO) AS Archivo, SALESUP_CT.dbo.VerArchivo(NOMBRE_DOCUMENTO,0) AS Ver, SALESUP_CT.dbo.SoloIconoArchivo(NOMBRE_DOCUMENTO,0) AS Icono,
  SALESUP_CT.DBO.TamanioArchivo('') AS Tamanio, SALESUP_CT.dbo.LinkArchivo(AMAZON, NOMBRE_DOCUMENTO, @IDEMPRESA)  AS Link, IDDOCUMENTO AS IdArchivo
  FROM <#SESSION.DB/>.dbo.EMPRESAS_DOCUMENTOS WHERE IDDOCUMENTO = @IDARCHIVO
  ORDER BY 1

END