//[idempresa|Text,la_bd|Text,origen|Text,fase|Text,etiqueta1|Text,]
--select
DECLARE @SQL VARCHAR(MAX)

SET @SQL = '

 DECLARE @IDORIGEN INT
 DECLARE @IDFASE INT
 DECLARE @IDETIQUETA INT

 DECLARE @IDEMPRESA INT 
 SET @IDEMPRESA = CAST( '+ :IDEMPRESA + '  AS INT)

 SELECT  TOP 1  @IDORIGEN = IDORIGEN FROM  ' + :LA_BD + '.dbo.PROSPECTOS_ORIGENES WHERE IDEMPRESA  = @IDEMPRESA AND ORIGEN =  ''' +  :ORIGEN + '''
 IF @IDORIGEN IS NULL
  SELECT TOP 1 @IDORIGEN = IDORIGEN FROM   ' +  :LA_BD  + '.dbo.PROSPECTOS_ORIGENES WHERE IDEMPRESA  = @IDEMPRESA ORDER BY IDORIGEN

 SELECT  TOP 1  @IDFASE = IDFASE FROM   ' +  :LA_BD  +'.dbo.PROSPECTOS_FASES WHERE IDEMPRESA  = @IDEMPRESA AND FASE =   ''' +  :FASE + '''
 IF @IDFASE IS NULL
  SELECT TOP 1 @IDFASE = IDFASE FROM   ' +  :LA_BD  +'.dbo.PROSPECTOS_FASES WHERE IDEMPRESA  = @IDEMPRESA ORDER BY IDFASE

 SELECT  TOP 1  @IDETIQUETA = IDETIQUETA FROM    ' +   :LA_BD   + '.dbo.ETIQUETAS WHERE IDEMPRESA  = @IDEMPRESA AND ETIQUETA =    ''' +   :ETIQUETA1 + '''
 IF @IDETIQUETA IS NULL
  SET  @IDETIQUETA = 0

 SELECT @IDORIGEN AS aIDORIGEN, @IDFASE AS aIDFASE, @IDETIQUETA AS aIDETIQUETA
'
EXEC (@SQL)