//[idp|Integer,ido|Integer,session.idempresa|Untyped,tkp|Text,tko|Text,session.db|Untyped,]
--SELECT 
DECLARE @IDPROSPECTO INT, @IDOPORTUNIDAD INT, @IDEMPRESA INT
SET @IDPROSPECTO = ISNULL(:IDP,0)
SET @IDOPORTUNIDAD = ISNULL(:IDO,0)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @TKP VARCHAR(MAX), @TKO VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
SET @TKO = ISNULL(:TKO,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP,@IDEMPRESA) END
IF @TKO != '' BEGIN SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END

SELECT SALESUP_CT.dbo.NombreRealArchivo(ARCHIVO) AS Archivo, SALESUP_CT.dbo.VerArchivo(ARCHIVO,0) AS Ver, SALESUP_CT.dbo.SoloIconoArchivo(ARCHIVO,0) AS Icono,
SALESUP_CT.DBO.TamanioArchivo(PESO) AS Tamanio, SALESUP_CT.dbo.LinkArchivo(AMAZON, ARCHIVO, @IDEMPRESA)  AS Link, IDPROSPECTOARCHIVO AS IdArchivo, ARCHIVO as ArchivoFisico,
@IDPROSPECTO  AS IDP,@IDOPORTUNIDAD AS IDO
FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
WHERE IDPROSPECTO = @IDPROSPECTO AND IDOPORTUNIDAD IS NULL
UNION
SELECT SALESUP_CT.dbo.NombreRealArchivo(ARCHIVO) AS Archivo, SALESUP_CT.dbo.VerArchivo(ARCHIVO,0) AS Ver, SALESUP_CT.dbo.SoloIconoArchivo(ARCHIVO,0) AS Icono,
SALESUP_CT.DBO.TamanioArchivo(PESO) AS Tamanio, SALESUP_CT.dbo.LinkArchivo(AMAZON, ARCHIVO, @IDEMPRESA)  AS Link, IDPROSPECTOARCHIVO AS IdArchivo, ARCHIVO as ArchivoFisico,
@IDPROSPECTO  AS IDP,@IDOPORTUNIDAD AS IDO
FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
WHERE IDPROSPECTO = @IDPROSPECTO AND IDOPORTUNIDAD = @IDOPORTUNIDAD
ORDER BY 1