//[f_usuario|Text,tkcom|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Text,porempresa|Text,session.db|Untyped,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')
IF (@F_USUARIO !='')
  SET @F_USUARIO = ' AND ( (1= 1 '+ @F_USUARIO + ') OR A2.IDUSUARIO = @IDUSUARIO )' 
SET @SQL ='
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT, @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @POREMPRESA VARCHAR(MAX)
SET @TkCom = dbo.ValidaToken('''+ISNULL(:TKCOM,'')+''')
SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)
SET @IDUSUARIO = CAST(''<#SESSION.IDUSUARIO/>'' AS INT)
SET @NIVELUSUARIO = CAST(''<#SESSION.NIVEL/>'' AS INT)
SET @IDGRUPO = CAST(''<#SESSION.IDGRUPO/>'' AS INT) 
SET @MAILCONFIG = CAST(''<#SESSION.MAILCONFIG/>'' AS INT )
SET @DESCARTADO = '+CAST(ISNULL(:DESCARTADO,'') AS VARCHAR(1000))+'
SET @IDCOMPANIA = 0
SET @POREMPRESA='''+ISNULL(:PorEmpresa,'')+'''

IF @TkCom != ''''
BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END

  SELECT @IDCOMPANIA, P.TKP AS Tkp, 1 as EV,(CASE WHEN P.ESCLIENTE=1 THEN ''1'' ELSE '''' END) AS ESCLIENTE, (CASE WHEN P.ESCLIENTE=0 THEN ''1'' ELSE '''' END) AS ESPROSPECTO,
  ''ReloadData''  AS ReloadData,
  SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, NULL, NULL ) AS VerArchivos,
  CASE @DESCARTADO WHEN 0 THEN ''1'' ELSE '''' END AS Descartado,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR A2.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tEtiquetar_tSeguimiento,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tCompartir_tReasignar,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR A2.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tOportunidad_tArchivar,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tDescartar,
  
  CASE WHEN ( SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA WITH(NOLOCK) WHERE PA.IDPROSPECTO = P.IDPROSPECTO ) > 1 THEN ''1'' ELSE '''' END AS Compartido,
  CASE @MAILCONFIG WHEN 0 THEN ''1'' ELSE '''' END AS NoConfigurado,
  CASE @MAILCONFIG WHEN 1 THEN ''1'' ELSE '''' END AS EmailConfigurado,
  CASE @MAILCONFIG WHEN 2 THEN ''1'' ELSE '''' END AS MailTo,
  
  CASE A2.Archivado WHEN 0 THEN ''1'' ELSE '''' END AS Archivado,
  CASE P.DESCARTADO WHEN 1 THEN ''1'' ELSE '''' END AS EsDescartado,
   
  P.IdProspecto, LTRIM(RTRIM(P.NOMBRE))+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS NombreCliente, isnull(P.Empresa,'''') as Empresa, P.Puesto,  P.ETIQUETAS_TXT  AS Etiquetas,
  CASE WHEN <#SESSION.DB/>.DBO.ValidaEmail(ISNULL(P.CORREO,'''')) = ''NO'' THEN ''1'' ELSE '''' END as EsCorreo, ISNULL(P.Correo,'''') AS Correo, ISNULL(P.Telefono,'''') AS Telefono, ISNULL(P.Telefono2,'''') AS Telefono2, ISNULL(P.Movil,'''') AS Movil, P.IdUsuario,
  ISNULL(F.Fase,'''') AS Fase, ISNULL(O.Origen,'''') AS Origen, 
  U.Iniciales, U.NOMBRE+'' ''+U.APELLIDOS AS EjecutivoNombre,
  (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS UltimoContactoTiempo,
  CONVERT(VARCHAR(10),P.FECHACONTACTO,103) AS FechaContacto,
   ISNULL(CAST(S.COMENTARIO AS VARCHAR(MAX)),'''')  AS UltimoContacto,
  ISNULL(U1.INICIALES,'''') AS UltimoUsuario, ISNULL(S.FechaHora,'''') AS FechaHora ,
  
  ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
  
  CASE WHEN P.CAMPO1 IS NOT NULL THEN P.CAMPO1 ELSE '''' END AS cp1,
  CASE WHEN P.CAMPO2 IS NOT NULL THEN P.CAMPO2 ELSE '''' END AS cp2,
  CASE WHEN P.CAMPO3 IS NOT NULL THEN P.CAMPO3 ELSE '''' END AS cp3,
  CASE WHEN P.CAMPO4 IS NOT NULL THEN P.CAMPO4 ELSE '''' END AS cp4,
  
  
  CASE WHEN P.CAMPO5 IS NOT NULL THEN P.CAMPO5 ELSE '''' END AS cp5,
  CASE WHEN P.CAMPO6 IS NOT NULL THEN P.CAMPO6 ELSE '''' END AS cp6,
  CASE WHEN P.CAMPO7 IS NOT NULL THEN P.CAMPO7 ELSE '''' END AS cp7,
  CASE WHEN P.CAMPO8 IS NOT NULL THEN P.CAMPO8 ELSE '''' END AS cp8,
  
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '''' END AS cp9,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '''' END AS cp10,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '''' END AS cp11,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '''' END AS cp12,
  
  ISNULL(P.CAMPO13,'''') AS cp13,
  ISNULL(P.CAMPO14,'''') AS cp14,
  ISNULL(P.CAMPO15,'''') AS cp15,
  ISNULL(P.CAMPO16,'''') AS cp16,
  ISNULL(P.CAMPO17,'''') AS cp17,
  ISNULL(P.CAMPO18,'''') AS cp18,
  ISNULL(P.CAMPO19,'''') AS cp19,
  ISNULL(P.CAMPO20,'''') AS cp20,
  
  CP21.OPCION AS cp21,
  CP22.OPCION AS cp22,
  CP23.OPCION AS cp23,
  CP24.OPCION AS cp24,
  CP25.OPCION AS cp25
   
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 ON CP25.IDOPCION = P.CAMPO25
  JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO AND A2.IDUSUARIO = @IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK)  ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO     
  WHERE  
    (P.IDCOMPANIA=@IDCOMPANIA AND P.DESCARTADO=@DESCARTADO   '+@F_USUARIO+'   /*AND P.ESOPORTUNIDAD = 0*/)
GROUP BY P.TKP,P.ESCLIENTE, P.NOMBRE, P.CORREO, F.FASE, P.FECHACONTACTO ,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR,  P.Puesto,
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA, P.DESCARTADO,
    F.ORDEN, s.fechahora, U.IDGRUPO, P.FECHAHORA, CAST(P.COMENTARIOS AS VARCHAR(128)), U.INICIALES, U.APELLIDOS, U.NOMBRE,P.ETIQUETAS_TXT, 
	A2.IDUSUARIO, O.ORIGEN, CAST(S.COMENTARIO AS VARCHAR(MAX)), U1.INICIALES, P.NARCHIVOS, A2.ARCHIVADO,
	P.CAMPO1, P.CAMPO2, P.CAMPO3, P.CAMPO4, P.CAMPO5, 
	P.CAMPO6, P.CAMPO7, P.CAMPO8, P.CAMPO9, P.CAMPO10,
	P.CAMPO11, P.CAMPO12, P.CAMPO13, P.CAMPO14, P.CAMPO15,
	P.CAMPO16, P.CAMPO17, P.CAMPO18, P.CAMPO19, P.CAMPO20,
	CP21.OPCION, CP22.OPCION, CP23.OPCION, CP24.OPCION, CP25.OPCION
	
	
ORDER BY ULTIMO_CONTACTO_FECHAHORA DESC
'
EXEC(@SQL)