//[f_usuario|Text,crit|Text,critarchivar|Text,porempresa|Text,porcatalogo|Text,session.db|Untyped,session.idempresa|Untyped,idpantalla|Integer,session.idusuario|Untyped,tkcom|Text,descartado|Text,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @FILTROUSUARIO VARCHAR(MAX) SET @FILTROUSUARIO = ISNULL( :F_USUARIO , '')
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL( :CRIT , '')
DECLARE @CRITARCHIVAR VARCHAR(MAX) SET @CRITARCHIVAR = ISNULL( :CRITARCHIVAR , '')
DECLARE @PorEmpresa VARCHAR(MAX) SET @PorEmpresa = ISNULL( :PorEmpresa , '')
DECLARE @PORCATALOGO VARCHAR(MAX) SET @PORCATALOGO = ISNULL( :PORCATALOGO , '')

DECLARE @DBNAME VARCHAR(MAX) SET @DBNAME = '<#SESSION.DB/>'
DECLARE @IDEMPRESA INT SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
DECLARE @IDPANTALLA INT SET @IDPANTALLA = ISNULL(:IDPANTALLA,1)
DECLARE @IDUSUARIO INT SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
DECLARE @DESCARTADO VARCHAR(10)
DECLARE @APROBADO VARCHAR(10)
 DECLARE @TABLADEFILTROS TABLE(ID INT, VAL VARCHAR(MAX))
	
	DECLARE @TkCom VARCHAR(64)
	SET @TkCom = CAST(ISNULL(:TKCOM,' ')  AS VARCHAR(MAX))
	
	INSERT INTO @TABLADEFILTROS
	SELECT * FROM <#SESSION.DB/>.dbo.filtrospantallas(@IDPANTALLA, @IDEMPRESA, @IDUSUARIO)

	SELECT
		@CRIT = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, CAST(RTRIM(LTRIM(@IDPANTALLA)) AS int))
	SELECT
	    @CRIT = @CRIT + <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, 15)

	SELECT @FILTROUSUARIO = VAL
	FROM @TABLADEFILTROS
	WHERE ID = 1
	
	SELECT @CRITARCHIVAR = VAL
	FROM @TABLADEFILTROS
	WHERE ID = 2
	
	SELECT @DESCARTADO = VAL
	FROM @TABLADEFILTROS
	WHERE ID = 3

	SELECT @APROBADO = VAL
	FROM @TABLADEFILTROS
	WHERE ID = 5

	IF @FILTROUSUARIO IS NOT NULL AND @TKCOM != '' OR 1=1
	BEGIN
		DECLARE @IDSUSUARIOS VARCHAR(MAX)
		SET @IDSUSUARIOS = ''
		SELECT @IDSUSUARIOS=CAST(ID AS VARCHAR(1000))+','+@IDSUSUARIOS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0)
		SET @IDSUSUARIOS=@IDSUSUARIOS+'0'
		SET @FILTROUSUARIO = @FILTROUSUARIO + ' AND A.IDUSUARIO IN  ('+@IDSUSUARIOS+')'
	END

SET @SQL = '

 DECLARE @IDCOMPANIA INT

 DECLARE @TkCom VARCHAR(64)
 SET @TkCom = ISNULL( ''' + ISNULL(@TkCom, '') + ''', '''')
 SELECT @IDCOMPANIA = 0
  
 IF @TkCom != ''''
 BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
 END

  SELECT COUNT ( DISTINCT(P.IDPROSPECTO)) AS TotalResgistros  
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) , 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
   LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM ON COM.IDCOMPANIA = P.IDCOMPANIA,
  <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK), 
  <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK)
  WHERE  
    P.IDEMPRESA = <#SESSION.IDEMPRESA/>  '  + @FILTROUSUARIO  +' 
     AND A.IDPROSPECTO = P.IDPROSPECTO AND P.DESCARTADO = '+@DESCARTADO+' AND P.ESOPORTUNIDAD=0 AND P.IDUSUARIO = U.IDUSUARIO AND ESCLIENTE = 0 AND 
     P.IDFASE = F.IDFASE '  + @CRIT  +'  '  + @CRITARCHIVAR  +' '  + @PorEmpresa  +' '  + @PORCATALOGO  +' AND P.APROBACIONESTADO '+CAST(@APROBADO AS VARCHAR(10))+'
'
EXEC (@SQL)