//[f_usuario|Text,tkcom|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,descartado|Integer,session.db|Untyped,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')

IF (@F_USUARIO !='')
  SET @F_USUARIO = ' AND ( (1= 1 '+ @F_USUARIO + ') OR A2.IDUSUARIO = @IDUSUARIO )' 


SET @SQL ='
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT, @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64), @POREMPRESA VARCHAR(MAX)
DECLARE @tbProspectos table(tkp varchar(64))

SET @TkCom =  ('''+ISNULL(:TKCOM,'')+''')
SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)
SET @IDUSUARIO = CAST(''<#SESSION.IDUSUARIO/>'' AS INT)
SET @NIVELUSUARIO = CAST(''<#SESSION.NIVEL/>'' AS INT)
SET @IDGRUPO = CAST(''<#SESSION.IDGRUPO/>'' AS INT) 

SET @DESCARTADO = '+CAST(ISNULL(:DESCARTADO,'') AS VARCHAR(1000))+'
SET @IDCOMPANIA = 0
SET @POREMPRESA='''+ISNULL('AND ISNULL(P.IDCOMPANIA,0) = @IDCOMPANIA ','')+'''

IF @TkCom != '''' BEGIN SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom END
	
 insert into @tbProspectos (tkp)
  SELECT P.TKP
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
  JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO AND A2.IDUSUARIO = @IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK)  ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO     
  WHERE  
    (P.IDCOMPANIA=@IDCOMPANIA AND P.DESCARTADO=@DESCARTADO   '+@F_USUARIO+'   /*AND P.ESOPORTUNIDAD = 0*/)
  GROUP BY P.TKP
	
  DECLARE @TOTALpROSPECTOS INT, @MIOS INT
  SELECT @TOTALpROSPECTOS = COUNT(*) FROM  <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDCOMPANIA = @IDCOMPANIA AND IDEMPRESA = @IDEMPRESA AND DESCARTADO = 0
  select @MIOS = count(*) from @tbProspectos
  
  SELECT @MIOS as TotalResgistros, @TOTALpROSPECTOS - @MIOS AS noVeo
	
  
'
EXEC(@SQL)