//[listap|Text,session.db|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,]
-- insert

DECLARE @IDPROSPECTO INT
  
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDPROSPECTO INT)
DECLARE @TO INT, @TOTAL INT
SET @TO = 1

DECLARE @LISTA VARCHAR(MAX)
SET @LISTA = ISNULL(:LISTAP,'')

INSERT INTO @TABLATEMP (IDPROSPECTO)
  SELECT IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,','))
  
SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
	EXEC <#SESSION.DB/>.dbo.SP_REACTIVAR @IDPROSPECTO, <#SESSION.IDUSUARIO/>,<#SESSION.CONVERTCODE/>
	UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO
	SET @TO = @TO + 1
END

DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES WITH (ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = <#SESSION.IDEMPRESA/>
INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES (4 , <#SESSION.IDEMPRESA/>)
