//[session.db|Untyped,session.idempresa|Untyped,]
SELECT (APELLIDOS + ', ' + NOMBRE + ' (' + INICIALES +')') as usuarios,* 
FROM 
<#SESSION.DB/>.DBO.EMPRESA_DISTRIBUCION_PROSPECTOS P, 
<#SESSION.DB/>.DBO.USUARIOS U 
WHERE U.IDEMPRESA = <#SESSION.IDEMPRESA/>
AND U.IDUSUARIO = P.IDUSUARIO AND U.ACTIVO = 1
ORDER BY IDDISTRIB
