//[sp_version|Untyped,idempresa|Integer,]
--SELECT
DECLARE @DB VARCHAR(36)
DECLARE @CONVERTCODE VARCHAR(3)
DECLARE @EXSQL VARCHAR(MAX)
DECLARE @SP_VERSION VARCHAR(128)
DECLARE @IDEMPRESA INT
DECLARE @MIGRADA INT

SET @SP_VERSION = '<#SP_VERSION/>'
SET @IDEMPRESA = isnull(:idempresa,0)

IF @SP_VERSION = ''
SELECT @MIGRADA = MIGRADA FROM SOCRATES.SALESUP.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA 
ELSE
SET @MIGRADA = 1

IF @MIGRADA = 0 SET @IDEMPRESA = 0

SELECT @DB = CASE WHEN LINK != 'SOCRATES' THEN LINK+'.'+BD_ACTUAL ELSE BD_ACTUAL END 
FROM CONTROL.CONTROL.dbo.EMPRESAS E, CONTROL.CONTROL.dbo.BASES_CONTEO B, CONTROL.CONTROL.dbo.SERVIDORESDB S  
 WHERE S.IDSERVIDORDB = B.IDSERVIDORDB AND E.BD_ACTUAL = B.DATA_BASE AND IDEMPRESA = CAST(@IDEMPRESA AS INT) AND BD_ACTUAL <> 'SALESUP_DB0'
--SELECT @DB 
IF @DB IS NULL SET @DB = 'SALESUP_DB1'
SET @EXSQL = 'SELECT TOP 1 ISNULL(P.CONVERTCODE, 103) AS CONVERTCODE , '''+@DB+''' AS ADB, '+cast(@IDEMPRESA AS VARCHAR(1000))+' AS IDEMPRESA FROM '+@DB+'.DBO.USUARIOS U LEFT JOIN PAISES P ON P.IDPAIS = U.DEFAULT_PAIS COLLATE Database_DEFAULT WHERE IDEMPRESA = '+CAST (@IDEMPRESA AS VARCHAR)+' ORDER BY NIVEL'
EXEC (@EXSQL)
