//[session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Text,session.db|Untyped,f_usuario|Text,crit|Text,critarchivar|Text,]
--SELECT 
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @DESCARTADO = CAST(ISNULL(:DESCARTADO,'') AS INT)
SET @F_USUARIO =  ISNULL(:F_USUARIO,'')
SET @CRIT =  ISNULL(:CRIT,'')
SET @CRITARCHIVAR =  ISNULL(:CRITARCHIVAR,'')


SET @SQL ='
  SELECT  COUNT (dISTINCT(ISNULL(P.idcompania,0)) )  AS TotalResgistros  
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 WITH(NOLOCK) ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 WITH(NOLOCK) ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 WITH(NOLOCK) ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 WITH(NOLOCK) ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 WITH(NOLOCK) ON CP25.IDOPCION = P.CAMPO25
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO  
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON P.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO = U1.IDUSUARIO 
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS C WITH(NOLOCK) ON C.IDCOMPANIA = P.IDCOMPANIA
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI WITH(NOLOCK) ON EI.IDINDUSTRIA = C.IDINDUSTRIA
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG WITH(NOLOCK) ON CG.IDCOMPANIAGRUPO = C.IDCOMPANIAGRUPO
  WHERE  
    (P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+' '+@F_USUARIO+' AND P.DESCARTADO = '+CAST(@DESCARTADO AS VARCHAR(1000))+' AND P.ESOPORTUNIDAD = 0 AND ESCLIENTE = 0 '+@CRIT+' '+@CRITARCHIVAR+')
'
EXEC (@SQL)

  
 