//[session.idusuario|Untyped,top_registros|Text,tkca|Text,descartado|Integer,f_usuario|Text,critarchivar|Text,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDUSUARIO INT
DECLARE @TKCA VARCHAR(MAX) = ISNULL(:TKCA,'')
DECLARE @TOPR VARCHAR(1000) = ISNULL(:TOP_REGISTROS,'')
DECLARE @DESCARTADO INT = ISNULL(:DESCARTADO,0)
DECLARE @F_USUARIO VARCHAR(MAX) = ISNULL(:F_USUARIO,'')
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITERIO VARCHAR(MAX) = ISNULL(:CRITARCHIVAR,'')

SET @IDUSUARIO= <#SESSION.IDUSUARIO/>

EXEC <#SESSION.DB/>.dbo.SP_PROSPECTOS_POR_CATALOGO @IDUSUARIO,@TKCA,@TOPR,@DESCARTADO,@F_USUARIO,@CRITERIO
