//[session.db|Untyped,idprospecto|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,]
--SELECT
DECLARE @SQL VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(8000)
DECLARE @IDPROSPECTO INT
DECLARE @NIVEL INT
SET @NIVEL=<#SESSION.NIVEL/>
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)

SET @F_USUARIO=(CASE WHEN @NIVEL=3 THEN ' AND PA.IDUSUARIO=<#SESSION.IDUSUARIO/>' WHEN @NIVEL=2 THEN ' AND PA.IDUSUARIO=<#SESSION.IDGRUPO/>' ELSE '' END)

SET @SQL='
SELECT TOP 1 PA.ARCHIVADO, P.IDPROSPECTO, P.IDEMPRESA, P.NOMBRE, P.APELLIDOS, P.CORREO, P.EMPRESA, P.IDUSUARIO, F.FASE, O.ORIGEN,
  (U.NOMBRE + '' '' + U.APELLIDOS) AS AGENTE, MC.EMAIL, U.CORREOSENVIADOS
  
FROM 
<#SESSION.DB/>.DBO.PROSPECTOS P, 
<#SESSION.DB/>.DBO.PROSPECTOS_FASES F, 
<#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O,
<#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA, 
<#SESSION.DB/>.DBO.USUARIOS U,
<#SESSION.DB/>.DBO.USUARIOS_MAILCONFIG MC

WHERE 
P.IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(1000))+'
AND PA.IDPROSPECTO = P.IDPROSPECTO
AND P.IDEMPRESA = <#SESSION.IDEMPRESA/> 
AND P.IDFASE = F.IDFASE 
AND P.IDORIGEN = O.IDORIGEN 
AND MC.IDUSUARIO=<#SESSION.IDUSUARIO/>
AND U.IDUSUARIO=<#SESSION.IDUSUARIO/>
'+@F_USUARIO+'
'
EXEC (@SQL)
