//[titulo|Text,session.idempresa|Untyped,actualiza|Integer,tk|Text,session.db|Untyped,]
--INSERT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @TITULO VARCHAR(1000)
DECLARE @IDEMPRESA INT 
DECLARE @ACTUALIZAR INT 
DECLARE @TK VARCHAR(256) 

SET @TITULO =  <#SESSION.DB/>.DBO.PREPARACADENA(ISNULL(:TITULO,''))
SET @IDEMPRESA=<#SESSION.IDEMPRESA/> 
SET @ACTUALIZAR=ISNULL(:ACTUALIZA, 0) 
SET @TK=ISNULL(:TK , '') 


IF(@ACTUALIZAR=0)
 BEGIN 
 IF @TITULO !=''
   INSERT INTO <#SESSION.DB/>.DBO.EMPRESAS_TITULOS (IDEMPRESA, TITULO) VALUES (<#SESSION.IDEMPRESA/>,@TITULO )
END
ELSE 
 BEGIN 
   UPDATE <#SESSION.DB/>.DBO.EMPRESAS_TITULOS
   SET TITULO=@TITULO
   WHERE TKTI=@TK
 END 

