//[tkeliminar|Text,tknuevo|Text,titulo|Text,titulonuevo|Text,bandera|Integer,session.db|Untyped,session.idempresa|Untyped,]
-- delete
DECLARE @IDTITULO INT 
DECLARE @TITULO VARCHAR(MAX)
DECLARE @TITULONUEVO VARCHAR(MAX)
DECLARE @BANDERA INT
DECLARE @TKELIMINAR VARCHAR(256) 
DECLARE @TKNUEVO  VARCHAR(256) 
SET @TKELIMINAR = ISNULL(:TKELIMINAR ,'')
SET @TKNUEVO  = ISNULL(:TKNUEVO, '' ) 
SELECT @TITULO=TITULO FROM  <#SESSION.DB/>.DBO.EMPRESAS_TITULOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND TKTI=@TKELIMINAR
SELECT @TITULONUEVO=TITULO FROM <#SESSION.DB/>.DBO.EMPRESAS_TITULOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND TKTI=@TKNUEVO
UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET TITULO = @TITULONUEVO WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND TITULO = @TITULO
DELETE FROM <#SESSION.DB/>.DBO.EMPRESAS_TITULOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND TKtI = @TKELIMINAR
