//[listap|Text,session.db|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,]
--update
DECLARE @IDPROSPECTO INT
  
DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDPROSPECTO INT)
DECLARE @TO INT, @TOTAL INT
SET @TO = 1

DECLARE @LISTA VARCHAR(MAX)
SET @LISTA = ISNULL(:LISTAP,'')

INSERT INTO @TABLATEMP (IDPROSPECTO)
SELECT IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,',') ) AND (IDPROSPECTO >0)

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
	SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
	EXEC <#SESSION.DB/>.dbo.SP_ARCHIVAR @IDPROSPECTO, <#SESSION.IDUSUARIO/>,<#SESSION.CONVERTCODE/>
	UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO
	SET @TO = @TO + 1
END


DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 