//[comentario|Text,motivo|Text,base|Integer,idprospecto|Integer,]
--UPDATE

DECLARE @SERVIDOR VARCHAR(MAX)
DECLARE @BASE VARCHAR(1000)
DECLARE @MOTIVO VARCHAR(1000)
DECLARE @COMENTARIO VARCHAR(MAX)
SET @COMENTARIO=ISNULL(:COMENTARIO,'')
SET @MOTIVO=ISNULL(:MOTIVO,'')
SET @BASE=ISNULL(:BASE,0)
SET @SERVIDOR = ''
SELECT @SERVIDOR = SERVIDOR + '.' + DATA_BASE
FROM CONTROL.CONTROL.DBO.BASES_CONTEO B, CONTROL.CONTROL.DBO.SERVIDORESDB S 
WHERE SUBSTRING(DATA_BASE,11, LEN(DATA_BASE)) = @BASE AND B.IDSERVIDORDB = S.IDSERVIDORDB

DECLARE @IDPROSPECTO INT
DECLARE @TSQL VARCHAR(MAX)

SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,0)AS INT)

SET @TSQL = ''
SET @TSQL = @TSQL + ' DECLARE @RAZON VARCHAR(MAX), @NOMBREUSUARIO VARCHAR(MAX), @NOMBREPROSPECTO VARCHAR(MAX), @BODY VARCHAR(MAX), @EMAIL VARCHAR(MAX), @IDPROSPECTO VARCHAR(MAX)'
SET @TSQL = @TSQL + ' DECLARE @IDUSUARIO INT, @RECIBIRCORREOS INT '
SET @TSQL = @TSQL + ' SET @IDPROSPECTO = '+CAST(@IDPROSPECTO AS VARCHAR(MAX))+' '
SET @TSQL = @TSQL + ' IF '''+@MOTIVO+''' = ''OTRO'' '
SET @TSQL = @TSQL + ' 	SET @RAZON = '''+@COMENTARIO+''' '
SET @TSQL = @TSQL + ' ELSE'
SET @TSQL = @TSQL + ' 	SET @RAZON = '''+@MOTIVO+''' '
SET @TSQL = @TSQL + ' IF @IDPROSPECTO > 0'
SET @TSQL = @TSQL + ' BEGIN'
SET @TSQL = @TSQL + ' 	SELECT @IDUSUARIO = IDUSUARIO, @RECIBIRCORREOS = RECIBIRCORREOS FROM '+@SERVIDOR+'.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO'
SET @TSQL = @TSQL + ' 	IF @RECIBIRCORREOS = 1'
SET @TSQL = @TSQL + ' 	BEGIN'
SET @TSQL = @TSQL + ' 		INSERT INTO '+@SERVIDOR+'.DBO.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, TIPO_SEGUIMIENTO, FECHAHORA, COMENTARIO, SISTEMA) '
SET @TSQL = @TSQL + ' 		VALUES (@IDPROSPECTO, @IDUSUARIO, 0, GETDATE(), ''El prospecto ha decidido no recibir correos automáticos por la siguiente razón: '' + @RAZON, 1) '
SET @TSQL = @TSQL + ' 		UPDATE '+@SERVIDOR+'.DBO.PROSPECTOS SET RECIBIRCORREOS = 2 WHERE IDPROSPECTO = @IDPROSPECTO '
SET @TSQL = @TSQL + ' 		EXEC '+@SERVIDOR+'.DBO.SP_NOTIFICA_UNSUSCRIBE @IDPROSPECTO, @RAZON '
SET @TSQL = @TSQL + ' 	END'
SET @TSQL = @TSQL + ' 	IF @RECIBIRCORREOS = 3'
SET @TSQL = @TSQL + ' 	BEGIN'
SET @TSQL = @TSQL + ' 		INSERT INTO '+@SERVIDOR+'.DBO.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO,IDUSUARIO,TIPO_SEGUIMIENTO,FECHAHORA,COMENTARIO,SISTEMA) '
SET @TSQL = @TSQL + ' 		VALUES (@IDPROSPECTO, @IDUSUARIO, 0, GETDATE(), ''El prospecto ha decidido no recibir correos automáticos por la siguiente razón: '' + @RAZON, 1) '
SET @TSQL = @TSQL + ' 		UPDATE '+@SERVIDOR+'.DBO.PROSPECTOS SET RECIBIRCORREOS = 0 WHERE IDPROSPECTO = @IDPROSPECTO '
SET @TSQL = @TSQL + ' 		EXEC '+@SERVIDOR+'.DBO.SP_NOTIFICA_UNSUSCRIBE @IDPROSPECTO, @RAZON '
SET @TSQL = @TSQL + ' 	END '
SET @TSQL = @TSQL + 'END '
SET @TSQL = @TSQL + ' '

EXEC (@TSQL)
