//[session.db|Untyped,session.idempresa|Untyped,idseguimientocategoria|Integer,]
UPDATE <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS SET POR_DEFECTO=0 WHERE IDEMPRESA=<#SESSION.IDEMPRESA/>
UPDATE <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS SET POR_DEFECTO=1 WHERE IDSEGUIMIENTOCATEGORIA=:IDSEGUIMIENTOCATEGORIA