//[session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Integer,top_registros|Text,session.db|Untyped,f_usuario|Text,crit|Text,critarchivar|Text,]
--SELECT 
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT
DECLARE @SQL VARCHAR(MAX)
DECLARE @TOP VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT) 
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @DESCARTADO = ISNULL(:DESCARTADO,0)
SET @TOP = ISNULL(:TOP_REGISTROS,'')
SET @F_USUARIO=ISNULL(:F_USUARIO,'')
SET @CRIT = ISNULL(:CRIT,'')
SET @CRITARCHIVAR=ISNULL(:CRITARCHIVAR,'')

SET @SQL ='

  SELECT '+@TOP+'
  
  CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 THEN 1 ELSE 0 END AS A , 
  ISNULL(COM.IDCOMPANIA,-1) AS Id, COM.TkCom, ISNULL(COM.Empresa,''Sin empresa'') as Empresa, 
  CASE WHEN (ISNULL(EI.Industria,'''')='''') OR (EI.Industria = ''Ninguna'') THEN '''' ELSE EI.Industria END AS Industria ,
  CASE WHEN (ISNULL(CG.CompaniaGrupo,'''')='''') OR (CG.CompaniaGrupo = ''Ninguna'') THEN '''' ELSE CG.CompaniaGrupo END AS CompaniaGrupo,
  COM.Url, COM.TELEFONOCORPORATIVO AS Telefono, 
  
  COUNT( distinct( isnull(p.IDprospecto,0) )) AS nRegistros,
  
  CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 
  	   THEN 
	   		( 
			  SELECT PP.NOMBRE +'' ''+ISNULL(PP.APELLIDOS,'''') + '', <b>''+<#SESSION.DB/>.DBO.TIEMPO_TXT (PSS.FECHAHORA,GETDATE()) + ''</b> (''+UU.INICIALES+'') - <i>''+ CAST(PSS.COMENTARIO AS VARCHAR(MAX)) + ''</i>''
			  FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSS , <#SESSION.DB/>.dbo.USUARIOS UU , <#SESSION.DB/>.dbo.PROSPECTOS PP 
			  WHERE PSS.IDUSUARIO = UU.IDUSUARIO AND PSS.IDSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO) AND PP.IDULTIMOSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO)
			) 
	   ELSE
	   	   ''''
	   END AS Comentario
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
  JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO AND A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+'
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK)  ON P.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO 
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI WITH(NOLOCK) ON EI.IDINDUSTRIA = COM.IDINDUSTRIA
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG WITH(NOLOCK) ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO
 
  WHERE (P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+' '+@F_USUARIO+' AND P.DESCARTADO = '+CAST(@DESCARTADO AS VARCHAR(1000))+' AND P.ESOPORTUNIDAD = 0 AND ESCLIENTE = 0 '+@CRIT+' '+@CRITARCHIVAR+')
  
  GROUP BY COM.IDCOMPANIA, COM.TkCom, CG.COMPANIAGRUPO, COM.EMPRESA, COM.URL, COM.TELEFONOCORPORATIVO, COM.IDCOMPANIAGRUPO, EI.INDUSTRIA
  ORDER BY 1 DESC, COM.Empresa
  '
  EXEC (@SQL)