//[filtroagrupardetalle|Integer,session.db|Untyped,session.idempresa|Untyped,]
DECLARE @FILTROAGRUPARDETALLE INT 
SET @FILTROAGRUPARDETALLE= ISNULL(:FILTROAGRUPARDETALLE, 0)

SELECT TK, TKM, ORIGEN, IDORIGEN, @FILTROAGRUPARDETALLE AS FILTROAGRUPARDETALLE 
FROM <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES
WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> 
ORDER BY ORIGEN 