//[idprospecto|Integer,session.db|Untyped,session.idempresa|Untyped,tkp|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDPROSPECTO INT, @IDEMPRESA INT
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END


SELECT IDUSUARIO AS USUARIO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = <#SESSION.IDEMPRESA/> 