//[session.db|Untyped,session.idusuario|Untyped,]
SELECT
TOP 10
CASE SECCION WHEN 4 THEN 'fa-share-square' WHEN 5 THEN 'fa-calendar' WHEN 0 THEN 'fa-bell' ELSE 'fa-user' END as Icono,
SUCESO AS Titulo,IDUSUARIOALERTA AS Id, LEFT(ALERTA,128) AS Mensaje, 'True' as Normal, SALESUP_ct.DBO.FormatoFecha(A.FECHA, 2) AS Fecha,
CONVERT(VARCHAR(22),A.FECHA, 20) AS Tiempo, A.IDUSUARIOALERTA,
S.TIPO, S.IDPROSPECTO, S.IDOPORTUNIDAD, S.IDMETA, S.IDTAREA, S.IDCITA, A.ALERTA, A.FECHA
FROM
 <#SESSION.DB/>.DBO.USUARIOS_ALERTAS A WITH(NOLOCK)
 JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS S WITH(NOLOCK) ON S.IDSUCESO =  A.IDSUCESO
 JOIN SALESUP_CT.dbo.TIPOS_SUCESOS T WITH(NOLOCK) ON T.IDSUCESO = S.TIPO
 LEFT JOIN <#SESSION.DB/>.DBO.TAREAS TR WITH(NOLOCK) ON TR.IDTAREA = S.IDTAREA
 LEFT JOIN <#SESSION.DB/>.DBO.CITAS C WITH(NOLOCK) ON C.IDCITA = S.IDCITA
WHERE A.IDUSUARIO=<#SESSION.IDUSUARIO> AND A.LEIDO = 0 AND S.IDMETA IS NULL
ORDER BY S.FECHAHORA DESC, A.FECHA DESC
