//[listaanterior|Text,listanueva|Text,idprospecto|Integer,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,tkp|Text,]
---UPDATE

DECLARE @CNOMBRE VARCHAR(255)
DECLARE @CAPELLIDOS VARCHAR(255)
DECLARE @CCORREO VARCHAR(255)
DECLARE @TXT VARCHAR(255)
DECLARE @IDUSUARIO INT
DECLARE @CONT INT,@TOTAL INT
DECLARE @IDS INT

SET @CONT=1

DECLARE @LISTAANTERIOR VARCHAR(MAX)
DECLARE @LISTANUEVA VARCHAR(MAX)
DECLARE @IDPROSPECTO INT

SET @LISTAANTERIOR = isnull(:LISTAANTERIOR,'')
SET @LISTANUEVA = ISNULL(:LISTANUEVA,'')
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)

DECLARE @IDEMPRESA INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END


IF @IDPROSPECTO > 0
 BEGIN
   DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO IN ( SELECT A.splitvalue FROM  <#SESSION.DB/>.dbo.Split(@LISTAANTERIOR, ',') A LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTANUEVA, ',') N ON A.splitvalue = N.splitvalue WHERE N.splitvalue IS NULL GROUP BY  A.splitvalue) 
   INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES WITH(ROWLOCK)  (IDTABLA,IDELIMINADO,TIPO,IDUSUARIO,FECHAHORA) SELECT 4,@IDPROSPECTO,2,A.splitvalue,GETDATE() FROM <#SESSION.DB/>.dbo.Split(@LISTAANTERIOR, ',') A LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTANUEVA, ',') N ON A.splitvalue = N.splitvalue  WHERE N.splitvalue IS NULL GROUP BY  A.splitvalue

   DECLARE @DUENIO_P INT
   SELECT @DUENIO_P = IDUSUARIO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
 
   UPDATE <#SESSION.DB/>.dbo.VENTAS SET IDUSUARIO = @DUENIO_P ,ULTIMAMODIFICACION = GETDATE() WHERE IDUSUARIO IN (SELECT A.splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAANTERIOR, ',') A 
   LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTANUEVA, ',') N ON A.splitvalue = N.splitvalue  WHERE N.splitvalue IS NULL
   and a.splitvalue in (select idusuario from <#SESSION.DB/>.dbo.oportunidades where idprospecto = @IDPROSPECTO) 
   GROUP BY  A.splitvalue)
   AND IDOPORTUNIDAD IN ( SELECT IDOPORTUNIDAD FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO IN (SELECT A.splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAANTERIOR, ',') A 
   LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTANUEVA, ',') N ON A.splitvalue = N.splitvalue  WHERE N.splitvalue IS NULL
   and a.splitvalue in (select idusuario from <#SESSION.DB/>.dbo.oportunidades where idprospecto = @IDPROSPECTO) 
   GROUP BY  A.splitvalue)
   )
   UPDATE <#SESSION.DB/>.dbo.OPORTUNIDADES SET IDUSUARIO = @DUENIO_P,ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO IN (SELECT A.splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAANTERIOR, ',') A 
   LEFT JOIN <#SESSION.DB/>.dbo.Split(@LISTANUEVA, ',') N ON A.splitvalue = N.splitvalue  WHERE N.splitvalue IS NULL
   and a.splitvalue in (select idusuario from <#SESSION.DB/>.dbo.oportunidades where idprospecto = @IDPROSPECTO) 
   GROUP BY  A.splitvalue)
   
   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = @IDEMPRESA
   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE())
   
 END 
 
/** FIN NUEVO QUERY **/

DECLARE @TABLAANTERIOR TABLE (IDMASTER INT IDENTITY,IDUSUARIO INT)  
INSERT @TABLAANTERIOR select SplitValue from <#SESSION.DB/>.DBO.Split(@LISTAANTERIOR, ',')

DECLARE @TABLATMP TABLE (IDMASTER INT IDENTITY,IDUSUARIO INT)  
INSERT @TABLATMP select SplitValue from <#SESSION.DB/>.DBO.Split(@LISTANUEVA, ',') WHERE SplitValue NOT IN (SELECT IDUSUARIO FROM @TABLAANTERIOR)
SELECT @TOTAL=COUNT(*) FROM @TABLATMP

WHILE (@CONT<=@TOTAL)
BEGIN 
   SELECT @IDUSUARIO=IDUSUARIO FROM @TABLATMP WHERE IDMASTER=@CONT
   
   SELECT @CNOMBRE = NOMBRE, @CAPELLIDOS = APELLIDOS, @CCORREO = EMAIL FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
   SET @TXT=@CNOMBRE+' '+@CAPELLIDOS
   
   /*SE COMPARTE AGREGANDOLO A ASIGNADOS*/
   insert into <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS (IDUSUARIO, IDPROSPECTO, ARCHIVADO) values (@IDUSUARIO, @IDPROSPECTO,0)
   
   /*PARA LA APP*/
   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO
   UPDATE  <#SESSION.DB/>.DBO.prospectos_seguimiento SET ultimamodificacion=GETDATE() WHERE IDSEGUIMIENTO IN (SELECT TOP (10) IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.prospectos_seguimiento WHERE idprospecto=@IDPROSPECTO ORDER BY 1 DESC)
   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDTABLA = 5 AND IDUSUARIO = @IDUSUARIO
   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDTABLA,IDUSUARIO,FECHAHORA) VALUES (5,@IDUSUARIO,GETDATE())
   
   /*PARA NOTIFICAR*/
   EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,3,@IDPROSPECTO,<#SESSION.CONVERTCODE/>,@txt,''
   SELECT TOP 1 @IDS = IDSUCESO FROM <#SESSION.DB/>.dbo.USUARIOS_SUCESOS WHERE TIPO = 3 AND IDUSUARIO = <#SESSION.IDUSUARIO/> ORDER BY IDSUCESO DESC
   UPDATE <#SESSION.DB/>.dbo.USUARIOS_SUCESOS SET IDUSUARIO_DESTINO = @IDUSUARIO WHERE IDSUCESO = @IDS
  SET @CONT=@CONT+1  
END

DECLARE @TABLAANTERIOR_D TABLE (IDMASTER INT IDENTITY,IDUSUARIO INT)  
INSERT @TABLAANTERIOR_D select SplitValue from <#SESSION.DB/>.DBO.Split(@LISTANUEVA, ',')

DECLARE @TABLATMP_D TABLE (IDMASTER INT IDENTITY,IDUSUARIO INT)  
INSERT @TABLATMP_D select SplitValue from <#SESSION.DB/>.DBO.Split(@LISTAANTERIOR, ',') WHERE SplitValue NOT IN (SELECT IDUSUARIO FROM @TABLAANTERIOR_D)
SELECT @TOTAL=COUNT(*) FROM @TABLATMP_D

WHILE (@CONT<=@TOTAL)
BEGIN 
   SELECT @IDUSUARIO=IDUSUARIO FROM @TABLATMP_D WHERE IDMASTER=@CONT
   
   SELECT @CNOMBRE = NOMBRE, @CAPELLIDOS = APELLIDOS, @CCORREO = EMAIL FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
   SET @TXT=@CNOMBRE+' '+@CAPELLIDOS
   
   EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,17,@IDPROSPECTO,<#SESSION.CONVERTCODE/>,@txt,''
   SELECT TOP 1 @IDS = IDSUCESO FROM <#SESSION.DB/>.dbo.USUARIOS_SUCESOS WHERE TIPO = 17 AND IDUSUARIO = <#SESSION.IDUSUARIO/> ORDER BY IDSUCESO DESC
   UPDATE <#SESSION.DB/>.dbo.USUARIOS_SUCESOS SET IDUSUARIO_DESTINO = @IDUSUARIO WHERE IDSUCESO = @IDS
  SET @CONT=@CONT+1  
END

IF(@TOTAL > 0)
BEGIN
   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE()) 
   
END  