//[listap|Text,listanueva|Text,operacion|Integer,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,tkpe|Text,]
--insert
DECLARE @LISTAPROSPECTOS VARCHAR(8000)
DECLARE @LISTAUSUARIOS VARCHAR(8000)
DECLARE @IDPROSPECTO INT
DECLARE @IDUSUARIO INT
DECLARE @DUENIO INT, @operacion int
DECLARE @CNOMBRE VARCHAR(255)
DECLARE @CAPELLIDOS VARCHAR(255)
DECLARE @CCORREO VARCHAR(255)
DECLARE @TXT VARCHAR(255)
DECLARE @TO INT, @TOTAL INT
DECLARE @TKPEXISTE VARCHAR(MAX)

SET @LISTAPROSPECTOS = isnull(:LISTAP,'') 
SET @LISTAUSUARIOS = isnull(:LISTANUEVA,'')
SET @TKPEXISTE = ISNULL(:tkPe,'');
set @operacion = isnull(:operacion,0)

IF @TKPEXISTE != '' AND @TKPEXISTE IS NOT NULL
BEGIN
 select @LISTAPROSPECTOS = <#SESSION.DB/>.dbo.obtieneListaIdProspecto(@LISTAPROSPECTOS, <#SESSION.IDEMPRESA/>)
END

IF @operacion = 2
BEGIN
   INSERT INTO <#SESSION.DB/>.dbo.ELIMINACIONES (IDTABLA,IDELIMINADO,TIPO,IDUSUARIO,FECHAHORA)
   SELECT 4,A.splitvalue,2,B.splitvalue,GETDATE() 
   FROM <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') A, <#SESSION.DB/>.dbo.Split(@LISTAUSUARIOS, ',') B, <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA, <#SESSION.DB/>.dbo.PROSPECTOS P
   WHERE PA.IDPROSPECTO = A.SplitValue AND P.IDPROSPECTO = A.SplitValue AND P.IDUSUARIO != PA.IDUSUARIO AND PA.IDUSUARIO = B.SplitValue
   
   DECLARE @TABLABORRAR TABLE (ID INT IDENTITY,IDPROSPECTO int) 
   SET @TO = 1
   
   INSERT INTO @TABLABORRAR (IDPROSPECTO)
   SELECT CAST(SplitValue as int) from <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') GROUP BY splitvalue
  
   SELECT @TOTAL = COUNT(*)  FROM @TABLABORRAR
   
   WHILE @TO <= @TOTAL
    BEGIN
  	   SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLABORRAR WHERE ID = @TO
	   SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
	   
	   DELETE  FROM  <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS  WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO <> @DUENIO AND IDUSUARIO IN  (SELECT splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAUSUARIOS, ','))
  	   
	   SET @TO = @TO + 1
    END
   
   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDPROSPECTO IN  (SELECT splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ','))
   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE())
END
ELSE
BEGIN

  INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS (IDPROSPECTO, IDUSUARIO) SELECT N.splitvalue, A.splitvalue 
  FROM <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') N CROSS JOIN <#SESSION.DB/>.dbo.Split(@LISTAUSUARIOS, ',') A 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA ON N.splitvalue = PA.IDPROSPECTO AND A.splitvalue = PA.IDUSUARIO
  WHERE PA.IDUSUARIO IS NULL GROUP BY A.splitvalue, N.splitvalue

  DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDPROSPECTO int) 
  SET @TO = 1
  
  DECLARE @TABLAUSUARIOS TABLE (ID INT IDENTITY,IDUSUARIO int)
  DECLARE @TO2 INT, @TOTAL2 INT

  INSERT INTO @TABLATEMP (IDPROSPECTO)
  SELECT CAST(SplitValue as int) from <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') GROUP BY splitvalue
  
  INSERT INTO @TABLAUSUARIOS (IDUSUARIO)
  SELECT CAST(SplitValue as int) from <#SESSION.DB/>.dbo.Split(@LISTAUSUARIOS, ',') GROUP BY splitvalue

  SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP
  SELECT @TOTAL2 = COUNT(*)  FROM @TABLAUSUARIOS

  WHILE @TO <= @TOTAL
  BEGIN
  	   SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
  	   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = <#SESSION.IDEMPRESA/>
  	   
	   	SET @TO2 = 1
	    WHILE @TO2 <= @TOTAL2
  		BEGIN
  	  		 SELECT @IDUSUARIO = IDUSUARIO FROM @TABLAUSUARIOS WHERE ID = @TO2
  	   		 SELECT @CNOMBRE = NOMBRE, @CAPELLIDOS = APELLIDOS, @CCORREO = EMAIL FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @IDUSUARIO
   			 SET @TXT=@CNOMBRE+' '+@CAPELLIDOS
   	   		 EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,3,@IDPROSPECTO,<#SESSION.CONVERTCODE/>,@TXT,''
     
   	 		 DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDTABLA = 5 AND IDUSUARIO = @IDUSUARIO
   			 INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDTABLA,IDUSUARIO,FECHAHORA) VALUES (5,@IDUSUARIO,GETDATE())
			 
			 EXEC <#SESSION.DB/>.DBO.SP_ENVIAR_CORREO_COMPARTIDO @IDPROSPECTO,<#SESSION.IDUSUARIO/>,@CCORREO
  	   
	   		 SET @TO2 = @TO2 + 1
  		END
		
		UPDATE  <#SESSION.DB/>.DBO.prospectos_seguimiento SET ultimamodificacion=GETDATE() WHERE IDSEGUIMIENTO IN (SELECT TOP (10) IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.prospectos_seguimiento WHERE idprospecto=@IDPROSPECTO ORDER BY 1 DESC)
  	   
	   SET @TO = @TO + 1
  END
  
  DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
  INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 
  
END
