//[idc|Integer,v|Text,ido|Integer,session.convertcode|Untyped,session.idempresa|Untyped,session.db|Untyped,]
-- SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @IDOPORTUNIDAD INT, @INDICE INT, @CONVERTCODE INT
DECLARE @VALOR VARCHAR(MAX) 

SET @INDICE = isnull(:IDC,0)
SET @VALOR = :V
SET @IDOPORTUNIDAD = isnull(:IDO,0)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT )
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

SET @IDOPORTUNIDAD = <#SESSION.DB/>.dbo.ValidaCamposUnicosOportunidades(@INDICE, @VALOR, @IDOPORTUNIDAD, @IDEMPRESA, @CONVERTCODE )

SELECT O.Concepto, O.Monto, O.Certeza, P.IDPROSPECTO AS IdP , P.Descartado, 
CAST(ISNULL(P.NOMBRE, '') AS VARCHAR(256))+ ' ' + CAST(ISNULL(P.APELLIDOS, '') AS VARCHAR(256)) AS Prospecto,
U.IdUsuario , U.NOMBRE + ' ' + U.APELLIDOS +' ('+ U.INICIALES+ ')' as Usuario, @INDICE as IDC, @IDOPORTUNIDAD as IDO
FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O, <#SESSION.DB/>.dbo.PROSPECTOS P , <#SESSION.DB/>.dbo.USUARIOS U
WHERE P.IDPROSPECTO = O.IDPROSPECTO AND U.IDUSUARIO = P.IDUSUARIO AND O.IDOPORTUNIDAD = @IDOPORTUNIDAD

