//[origen|Text,session.idempresa|Untyped,tk|Text,session.db|Untyped,]
--UPDATE 

DECLARE @ORIGEN VARCHAR(128)
DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(256) 
SET  @ORIGEN=ISNULL(:ORIGEN, '')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TK= ISNULL(:TK, '') 
UPDATE  <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES SET ORIGEN =@ORIGEN WHERE IDEMPRESA =@IDEMPRESA  AND TK =@TK
  
