//[descartado|Integer,top_registros|Text,session.db|Untyped,session.idempresa|Untyped,f_usuario|Text,crit|Text,critarchivar|Text,ordenamiento|Text,]
-- SELECT
/*PROTEGIDO*/
  DECLARE @DESCARTADO TINYINT
  
  DECLARE @TOP_REGISTROS VARCHAR(512)
  DECLARE @CRIT VARCHAR(MAX)
  DECLARE @CRITARCHIVAR VARCHAR(MAX)
  DECLARE @F_USUARIO VARCHAR(MAX)
  DECLARE @ORDENAMIENTO VARCHAR(MAX)
  
  DECLARE @SQLTXT VARCHAR(MAX)
  
  SET @SQLTXT = ''
  
  SET @TOP_REGISTROS = ISNULL(:TOP_REGISTROS,'')
  SET @CRIT = ISNULL(:CRIT,'')
  SET @CRITARCHIVAR = ISNULL(:CRITARCHIVAR,'')
  SET @F_USUARIO = ISNULL(:F_USUARIO,'')
  SET @ORDENAMIENTO = ISNULL(:ORDENAMIENTO,' 1 DESC')
  
  SET @DESCARTADO = ISNULL(:DESCARTADO,0)
  
  SET @SQLTXT = ' SELECT '+@TOP_REGISTROS+' U.IDGRUPO, '
  SET @SQLTXT = @SQLTXT + ' SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, NULL,  NULL) AS VerArchivos, '
  SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.DBO.ObtieneEjecutivosCompartidos(P.IDPROSPECTO) AS EJECUTIVOS, '
  SET @SQLTXT = @SQLTXT + ' (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA  WITH(NOLOCK) WHERE PA.IDPROSPECTO = P.IDPROSPECTO ) AS COMPARTIDO, ' 
  SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) as ESCORREO , '
  SET @SQLTXT = @SQLTXT + ' P.NOMBRE,    P.CORREO, fase,fechacontacto, ' 
  SET @SQLTXT = @SQLTXT + ' ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA, '
  SET @SQLTXT = @SQLTXT + ' P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR, A.ARCHIVADO, '  
  SET @SQLTXT = @SQLTXT + ' P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO, '
  SET @SQLTXT = @SQLTXT + ' F.ORDEN,CAST (COMENTARIOS AS VARCHAR(128))+''...'' AS INTRO, U.INICIALES, U.NOMBRE+'' ''+U.APELLIDOS AS EJECUTIVO_NOMBRE, ' 
  SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.DBO.GETONLYDATE(P.FECHACONTACTO) AS FECHA_CONTACTO, '
  SET @SQLTXT = @SQLTXT + ' P.ETIQUETAS_TXT AS ETIQUETAS, A.IDUSUARIO AS USUARIO,ORIGEN, '    
  SET @SQLTXT = @SQLTXT + ' (CAST(S.COMENTARIO AS VARCHAR(128))) AS ULTIMO_CONTACTO, '
  SET @SQLTXT = @SQLTXT + ' (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS ULTIMO_CONTACTO_TIEMPO, '
  SET @SQLTXT = @SQLTXT + ' (U1.INICIALES) AS ULTIMO_CONTACTO_USUARIO, s.fechahora ' 
   
  SET @SQLTXT = @SQLTXT + ' FROM ' 
  SET @SQLTXT = @SQLTXT + ' <#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK) ' 
  SET @SQLTXT = @SQLTXT + ' JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO ' 
  SET @SQLTXT = @SQLTXT + ' JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A  WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO ' 
  SET @SQLTXT = @SQLTXT + ' JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F  WITH(NOLOCK) ON P.IDFASE = F.IDFASE ' 
  SET @SQLTXT = @SQLTXT + ' JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O  WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN ' 
  SET @SQLTXT = @SQLTXT + ' LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S  WITH(NOLOCK)  ON P.IDULTIMOSEGUIMIENTO=S.IDSEGUIMIENTO ' 
  SET @SQLTXT = @SQLTXT + ' LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1  WITH(NOLOCK) ON S.IDUSUARIO=U1.IDUSUARIO ' 
        
  SET @SQLTXT = @SQLTXT + ' WHERE '  
  SET @SQLTXT = @SQLTXT + ' (P.IDEMPRESA = <#SESSION.IDEMPRESA/> '+@F_USUARIO + ' ' 
  SET @SQLTXT = @SQLTXT + ' AND P.DESCARTADO='+CAST(@DESCARTADO AS VARCHAR(2))+' AND P.ESOPORTUNIDAD=0 AND   ESCLIENTE = 0 '  
  SET @SQLTXT = @SQLTXT + @CRIT+' '+@CRITARCHIVAR+') '
  SET @SQLTXT = @SQLTXT + ' GROUP BY P.NOMBRE, P.CORREO, F.FASE, P.FECHACONTACTO , '
  SET @SQLTXT = @SQLTXT + ' P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR, A.ARCHIVADO, '  
  SET @SQLTXT = @SQLTXT + ' P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA,    P.DESCARTADO, '
  SET @SQLTXT = @SQLTXT + ' F.ORDEN, s.fechahora, U.IDGRUPO, P.FECHAHORA, CAST(P.COMENTARIOS AS VARCHAR(128)), U.INICIALES, U.APELLIDOS, U.NOMBRE,P.ETIQUETAS_TXT, ' 
  SET @SQLTXT = @SQLTXT + ' A.IDUSUARIO, O.ORIGEN, CAST(S.COMENTARIO AS VARCHAR(128)), U1.INICIALES, P.NARCHIVOS '
  
  SET @SQLTXT = @SQLTXT + ' ORDER BY ' + @ORDENAMIENTO
  
  EXEC(@SQLTXT)
