//[idprospecto|Integer,idplantilla|Integer,para|Text,cc|Text,cco|Text,session.db|Untyped,]
-- INSERT
DECLARE @PARA VARCHAR(255)
DECLARE @CC VARCHAR(255)
DECLARE @CCO VARCHAR(255)
DECLARE @PROSPECTO INT
DECLARE @PLANTILLA INT

SET @PROSPECTO = CAST(ISNULL(:IDPROSPECTO,0) AS INT)
SET @PLANTILLA = CAST(ISNULL(:IDPLANTILLA,0) AS INT)
SET @PARA = :PARA
SET @CC = :CC
SET @CCO = :CCO

EXEC <#SESSION.DB/>.dbo.SP_ENVIA_MAIL_ACCIONES @PROSPECTO, @PLANTILLA, @PARA, @CC, @CCO,0