//[session.db|Untyped,session.idempresa|Untyped,tk_eliminar|Text,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/

DECLARE @FASE_ELIMINAR INT
DECLARE @TK VARCHAR(MAX)
DECLARE @IDEMPRESA INT 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET  @TK=ISNULL(:TK_ELIMINAR, '')
SELECT @FASE_ELIMINAR=IDFASE 
FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE TK=@TK  AND IDEMPRESA= @IDEMPRESA

SELECT *,SALESUP_CT.DBO.ESCANALIZADO(TK, TKM) AS esCanalizado from <#SESSION.DB/>.DBO.PROSPECTOS_FASES 
WHERE IDEMPRESA=@IDEMPRESA AND IDFASE != @FASE_ELIMINAR AND FASECLIENTE=0
ORDER BY ORDEN