//[session.db|Untyped,session.idempresa|Untyped,iddelgrupo|Integer,tk|Text,]
--SELECT 

DECLARE @TK VARCHAR(256) 
DECLARE @IDEMPRESA INT 

SET @TK=ISNULL(:TK, '') 
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SELECT * FROM  <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES WHERE IDEMPRESA = @IDEMPRESA AND TK=@TK