//[listap|Text,session.idempresa|Untyped,session.idusuario|Untyped,razones|Integer,comentario|Text,session.convertcode|Untyped,session.db|Untyped,tkp|Text,]
--insert
DECLARE @LISTA VARCHAR(MAX)
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @RAZONES INT
DECLARE @COMENTARIO VARCHAR(258)
DECLARE @CONVERTCODE INT
DECLARE @NOTIFICAR INT 
SET @LISTA = :LISTAP
SET @IDEMPRESA= CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO   =CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @RAZONES = CAST(:RAZONES AS INT)
SET @COMENTARIO =  :COMENTARIO 
SET @CONVERTCODE  = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @NOTIFICAR=  1


DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' 
BEGIN
   SET @LISTA = <#SESSION.DB/>.dbo.obtieneListaIdProspecto(@TKP, @IDEMPRESA)
END


EXEC <#SESSION.DB/>.DBO.SP_DESCARTAR_PROSPECTO @LISTA, @IDEMPRESA, @IDUSUARIO, @RAZONES, @COMENTARIO, @CONVERTCODE, @NOTIFICAR
