//[e|Text,session.db|Untyped,]
--SELECT
DECLARE @EMAIL VARCHAR(MAX), @VALIDO VARCHAR(3)
SET @EMAIL = :E

SELECT @VALIDO = <#SESSION.DB/>.dbo.ValidaEmail(@EMAIL)
SELECT CASE @VALIDO WHEN 'SI' THEN 1 ELSE 0 END Valido