//[session.idempresa|Untyped,session.db|Untyped,]

--SELECT

DECLARE @IDEMPRESA INT
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)

DECLARE @TB TABLE (N INT IDENTITY, Id VARCHAR(MAX), IdCampoPer VARCHAR(MAX), IdC VARCHAR(MAX), Campo VARCHAR(MAX), Nombre VARCHAR(MAX), Tip VARCHAR(MAX), EsSelect VARCHAR(MAX), EsTextArea VARCHAR(MAX), EsInput VARCHAR(MAX), TipoDato VARCHAR(MAX), ClasesAdicionales VARCHAR(MAX) )

INSERT INTO @TB (Id, IdCampoPer, IdC, Campo, Nombre, Tip, EsSelect, EsTextArea, EsInput, TipoDato, ClasesAdicionales)

SELECT /*C.IDCAMPO AS N,*/ 'CS-'+cast(C.IDCampo as varchar(max)) as Id, '' AS IdCampoPer, '-'+CAST(ECC.CAMPO AS VARCHAR(MAX)) AS IdC,  C.Campo, ID AS Nombre, C.TIP AS Tip,
CASE WHEN (C.IDCAMPO = 4) OR (C.IDCAMPO = 5) OR (C.IDCAMPO = 18) OR (C.IDCAMPO = 19) OR (C.IDCAMPO = 20) OR (C.IDCAMPO = 21) OR (C.IDCAMPO = 22) OR (C.IDCAMPO = 29) OR (C.IDCAMPO = 30) OR (C.IDCAMPO = 32) OR (C.IDCAMPO = 33) THEN '1' END EsSelect,
CASE WHEN (C.IDCAMPO = 17) THEN '1' END AS EsTextArea,
CASE WHEN NOT( (C.IDCAMPO = 4) OR (C.IDCAMPO = 5) OR (C.IDCAMPO = 18) OR (C.IDCAMPO = 19) OR (C.IDCAMPO = 20) OR (C.IDCAMPO = 21) OR (C.IDCAMPO = 22) OR (C.IDCAMPO=17) OR (C.IDCAMPO = 29) OR (C.IDCAMPO = 30) OR (C.IDCAMPO = 32) OR (C.IDCAMPO = 33)  ) THEN '1' END AS EsInput,
'' AS TipoDato,
CASE ECC.TIPO
	WHEN 2 THEN 'InfoObligatorio' 
	WHEN 3 THEN 'InfoObligatorio InfoUnico' 
	END AS ClasesAdicionales
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS_CONFIGURACION ECC, SALESUP_CT.DBO.CAMPOS C
WHERE ECC.IDEMPRESA = @IDEMPRESA AND ECC.CAMPO = C.IDCAMPO AND (ECC.TIPO IN (2,3) OR C.IDCAMPO = 2  ) 
ORDER BY IdC

INSERT INTO @TB (Id, IdCampoPer, IdC, Campo, Nombre, Tip, EsSelect, EsTextArea, EsInput, TipoDato, ClasesAdicionales)

SELECT  /*EC.IDCAMPO AS N,*/ 'CP-'+cast(EC.INDICE as varchar(max))as Id, 
EC.IDCAMPO AS IdCampoPer, EC.INDICE AS IdC,
EC.Nombre_Campo AS Campo,
'Campo'+ cast(EC.INDICE as varchar(max)) AS Nombre, '['+EC.Nombre_Campo+ '] - ' +EC.DESCRIPCION as Tip,

CASE WHEN EC.INDICE BETWEEN 21 AND 25 THEN '1' END AS EsSelect, '' AS EsTextArea,
CASE WHEN NOT(EC.INDICE BETWEEN 21 AND 25) THEN '1' END AS EsInput,
CASE
    WHEN EC.INDICE BETWEEN 1 AND 4 THEN '1'
    WHEN EC.INDICE BETWEEN 5 AND 8 THEN '2'
    WHEN EC.INDICE BETWEEN 9 AND 12 THEN '3'
    WHEN ( (EC.INDICE BETWEEN 13 AND 20) OR (EC.INDICE BETWEEN 26 AND 32) )  THEN '4'
    WHEN EC.INDICE BETWEEN 21 AND 25 THEN '5'
    END AS TipoDato,
CASE EC.LLAVE 
	WHEN 1 THEN 'InfoObligatorio InfoUnico' 
	WHEN 2 THEN 'InfoObligatorio' 
	END AS ClasesAdicionales
FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS EC 
WHERE EC.LLAVE IN (1,2) AND EC.IDEMPRESA = @IDEMPRESA AND ( EC.TIPO = 1 OR EC.COMPARTIR = 1 )
--ORDER BY 2 DESC, 4 desc

SELECT * FROM @TB ORDER BY 1