//[pd|Integer,tconsulta|Text,session.db|Untyped,]
--SELECT
DECLARE @PAISDEFAULT VARCHAR(MAX)
SET @PAISDEFAULT = ISNULL(:pd,'')

DECLARE @TIPOCOSULTA INT
SET @TIPOCOSULTA = CAST(ISNULL(:tConsulta,0) AS INT)


IF @TIPOCOSULTA = 1
BEGIN
	 SELECT IdPais as value, Pais as Opcion
	 FROM <#SESSION.DB/>.dbo.PAISES ORDER BY PAIS
END
ELSE
BEGIN
	 SELECT IdPais, Pais,
	 CASE WHEN @PAISDEFAULT = IDPAIS THEN '1' ELSE '' END as Seleccionado
	 FROM <#SESSION.DB/>.dbo.PAISES ORDER BY PAIS
END

