//[f_usuario|Text,session.gmt|Untyped,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL(:F_USUARIO, '')
SET @SQL = '
DECLARE @GMT INT

SET @GMT = CAST(''<#SESSION.GMT/>'' AS INT )

SELECT PR.TKP, PR.NOMBRE, PR.APELLIDOS  ,PR.DESCARTADO, X.* FROM

(SELECT TOP 10 SALESUP_CT.dbo.[obtieneFechaRealGMT](@GMT,US.FECHAHORA) AS FECHAHORA, US.TEXTO, US.TIPO, US.IDPROSPECTO,  (UU.NOMBRE+'' ''+UU.APELLIDOS) AS EJECUTIVO, US.IDOPORTUNIDAD,(CASE WHEN US.TIPO=24 THEN CONVERT(VARCHAR(10),CIT.FECHA_INICIO,103) ELSE NULL END) AS FECHA_CITA, OP.TKO
FROM 
<#SESSION.DB/>.dbo.USUARIOS UU  WITH(NOLOCK) 
JOIN <#SESSION.DB/>.dbo.USUARIOS_SUCESOS US  WITH(NOLOCK)  ON US.IDUSUARIO=UU.IDUSUARIO  
  LEFT JOIN <#SESSION.DB/>.dbo.CITAS CIT  WITH(NOLOCK) ON  CIT.IDCITA=US.IDCITA
  LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES OP WITH(NOLOCK) ON US.IDOPORTUNIDAD=OP.IDOPORTUNIDAD
JOIN <#SESSION.DB/>.dbo.TIPO_SUCESOS TS  WITH(NOLOCK)  ON  US.TIPO=TS.TIPO AND TS.IDUSUARIO= <#SESSION.IDUSUARIO/>
WHERE UU.IDEMPRESA=<#SESSION.IDEMPRESA/> 

		 AND (1=1  ' + @CRIT+ '
              OR US.IDPROSPECTO IN (SELECT IDPROSPECTO FROM  <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS  WITH(NOLOCK) WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>)
          )

GROUP BY US.FECHAHORA,US.TEXTO,  US.TIPO, US.IDPROSPECTO,  (UU.NOMBRE+'' ''+UU.APELLIDOS) , US.IDOPORTUNIDAD,CIT.FECHA_INICIO,OP.TKO
ORDER BY US.FECHAHORA DESC
) AS X
LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS PR WITH(NOLOCK) ON PR.IDPROSPECTO=X.IDPROSPECTO
GROUP BY PR.TKP, X.FECHAHORA, X.TEXTO, X.TIPO, X.IDPROSPECTO, X.EJECUTIVO,X.IDOPORTUNIDAD,NOMBRE, PR.APELLIDOS,PR.DESCARTADO,X.FECHA_CITA,X.TKO
ORDER BY FECHAHORA DESC
'
EXEC (@SQL)