//[tkcom|Text,session.db|Untyped,session.gmt|Untyped,session.idempresa|Untyped,]
DECLARE @GMT INT
DECLARE @TKCOMPANIA VARCHAR(64) 
DECLARE @IDCOMPANIA INT 

SET @TKCOMPANIA = dbo.ValidaToken(ISNULL(:TKCOM,''))
SET @IDCOMPANIA  = 0

SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.DBO.COMPANIAS WHERE TKCOM=@TKCOMPANIA

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT  WITH(NOLOCK)  WHERE GMT= @GMT

SELECT 
COUNT(*) AS TotalResgistros, @TKCOMPANIA AS TKCOM
FROM
<#SESSION.DB/>.DBO.PROSPECTOS P  WITH(NOLOCK)  
JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON S.IDPROSPECTO=P.IDPROSPECTO AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>
JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK)  ON  S.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/>
WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND P.IDCOMPANIA=@IDCOMPANIA AND S.IDPROSPECTO = P.IDPROSPECTO AND  S.IDOPORTUNIDAD IS NULL 
