//[tipo|Integer,session.db|Untyped,session.idempresa|Untyped,]
--SELECT
DECLARE @TIPO INT

SET @TIPO = ISNULL(:TIPO,0)

SELECT (APELLIDOS + ', ' + NOMBRE + ' (' + INICIALES +')') as usuarios,* ,@TIPO AS TIPO, U.TKU

FROM 
<#SESSION.DB/>.DBO.EMPRESA_DISTRIBUCION_PROSPECTOS P, 
<#SESSION.DB/>.DBO.USUARIOS U 
WHERE U.IDEMPRESA = <#SESSION.IDEMPRESA/>
AND U.IDUSUARIO = P.IDUSUARIO AND U.ACTIVO = 1 AND P.TIPO_DISTRIBUCION = @TIPO
ORDER BY IDDISTRIB