//[]
--select

SELECT 0 AS IDTIPOFILTRO, 1 AS CATE, 0 AS TIPO,

 CASE WHEN IDCAMPO=11 THEN 'No. Vendedores' ELSE CAMPO END AS FILTRO
 
 , IDCAMPO

FROM [SALESUP_CT].[dbo].[CAMPOS]
 WHERE (IDVENTANA=1 AND TIPO_FILTRO IS NULL) OR IDCAMPO=11
 union all
SELECT IDTIPOFILTRO, CATE, TIPO, FILTRO, TIPO  AS IDCAMPO
FROM SALESUP_CT.dbo.TIPOS_FILTROS 
WHERE IDTIPOFILTRO   NOT LIKE '%14%'
ORDER BY FILTRO