//[valor|Text,idcampo|Integer,session.db|Untyped,session.convertcode|Untyped,idprospecto|Integer,session.idempresa|Untyped,]
DECLARE @USR INT
DECLARE @IDPROSPECTO INT
DECLARE @INDICE INT
declare @VALOR VARCHAR(200) 
DECLARE @IDPROSPECTO INT
DECLARE @IDCAMPO INT

SET @VALOR= ISNULL(:VALOR,'')
SET @IDPROSPECTO =  ISNULL (:IDPROSPECTO,0)
SET @IDCAMPO= ISNULL(:IDCAMPO,0)

IF @IDCAMPO >= 0 
BEGIN
	 SELECT @INDICE = INDICE FROM <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS WHERE IDCAMPO = @IDCAMPO
	 IF (@INDICE in (9,10,11,12))
	 SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCampoLlave_V2(@IDCAMPO,CONVERT (DATETIME,@VALOR,<#SESSION.CONVERTCODE/>), @IDPROSPECTO, <#SESSION.IDEMPRESA/>)
	 ELSE
	 SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCampoLlave_V2(@IDCAMPO,@VALOR, @IDPROSPECTO, <#SESSION.IDEMPRESA/>)
END
ELSE
BEGIN
	 SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCampoLlave_V2(@IDCAMPO,@VALOR,@IDPROSPECTO, <#SESSION.IDEMPRESA/>)
END

SELECT @USR = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
SELECT  NOMBRE + ' '+APELLIDOS + '('+INICIALES+')' AS NOMBRE  FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO = @USR