//[escliente|Integer,session.idempresa|Untyped,session.db|Untyped,]
--SELECT
DECLARE @FASET INT
SET @FASET=:ESCLIENTE

IF @FASET=1
      SELECT * FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND  FASECLIENTE=1  ORDER BY ORDEN
ELSE
 SELECT * FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND  FASECLIENTE=0  ORDER BY ORDEN