//[session.db|Untyped,session.idempresa|Untyped,categoria|Text,]
--INSERT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @CATEGORIA VARCHAR(1000)
SET @CATEGORIA = ISNULL(:CATEGORIA, '')
IF (@CATEGORIA != '')
   INSERT INTO <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS (IDEMPRESA, CATEGORIA) VALUES (<#SESSION.IDEMPRESA/>,@CATEGORIA)