//[tk|Text,session.idempresa|Untyped,]
--SELECT 

DECLARE @TK VARCHAR(256) 
DECLARE @IDEMPRESA INT 
DECLARE @TOTAL INT 

SET @TK=ISNULL(:TK, '') 
SET @IDEMPRESA =<#SESSION.IDEMPRESA/>
SET @TOTAL = 1

SELECT @TOTAL AS total