//[jsondatosdocumento|Text,plantillaseleccionada|Text,session.idempresa|Untyped,session.idusuario|Untyped,idoportunidad|Text,idprospecto|Text,nombrearchivosugerido|Text,descripcionarchivo|Text,session.db|Untyped,]
--select 
DECLARE @IDDOCUMENTO INT, @IDEMPRESA INT, @IDARCHIVO INT, @IDOPORTUNIDAD INT, @IDUSUARIO INT, @IDPROSPECTO INT
DECLARE @ETIQUETASDOCUMENTO VARCHAR(MAX), @ARCHIVO VARCHAR(MAX), @DESCRIPCIONARCHIVO VARCHAR(MAX)
DECLARE @FECHA DATETIME

SET @FECHA = GETDATE()
  
  SET @ETIQUETASDOCUMENTO = :jsonDatosDocumento
  SET @IDDOCUMENTO = CAST(ISNULL(:PlantillaSeleccionada,'') AS INT)
  SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
  SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
  SET @IDOPORTUNIDAD = CAST(ISNULL(:IDOPORTUNIDAD,'') AS INT)
  SET @IDPROSPECTO = CAST(ISNULL(:IDPROSPECTO,'') AS INT)
  SET @IDARCHIVO = 0
  SET @ARCHIVO = :NombreArchivoSugerido
  SET @DESCRIPCIONARCHIVO = :DescripcionArchivo
  
  IF @IDDOCUMENTO > 0
  BEGIN
  	   IF @IDOPORTUNIDAD = 0 BEGIN SET @IDOPORTUNIDAD = NULL END
	   
	   DECLARE @CAMPO33 VARCHAR(MAX), @CAMPO34 VARCHAR(MAX)
	   
	   SET @CAMPO33 = '' 
	   SET @CAMPO34 = ''
	   
	   SELECT @CAMPO33 = ISNULL(CAMPO33,''), @CAMPO34 = ISNULL(CAMPO34,'') 
	   FROM <#SESSION.DB/>.dbo.OPORTUNIDADES 
	   WHERE IDPROSPECTO = @IDPROSPECTO AND IDOPORTUNIDAD = @IDOPORTUNIDAD
	   
	   SET @ETIQUETASDOCUMENTO = REPLACE(@ETIQUETASDOCUMENTO, '"Valor":"[CPO33]"', '"Valor":"'+@CAMPO33+'"')
	   SET @ETIQUETASDOCUMENTO = REPLACE(@ETIQUETASDOCUMENTO, '"Valor":"[CPO34]"', '"Valor":"'+@CAMPO34+'"')
	   
  	   INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS
	   ( IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, ARCHIVO, DESCRIPCION, AMAZON, PESO, FECHA, IDDOCUMENTO, ETIQUETAS)
  	   VALUES 
	   ( @IDPROSPECTO, @IDOPORTUNIDAD, @IDUSUARIO, @ARCHIVO, @DESCRIPCIONARCHIVO, 1, 0, GETDATE(), @IDDOCUMENTO, @ETIQUETASDOCUMENTO)
		
	   SELECT TOP 1 @IDARCHIVO = IDPROSPECTOARCHIVO FROM <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS 
       WHERE IDPROSPECTO = @IDPROSPECTO AND ARCHIVO = @ARCHIVO ORDER BY IDPROSPECTOARCHIVO DESC
	   
	    EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO,@FECHA
	   
  END
  
 
  SELECT @IDARCHIVO AS idArchivo, @IDPROSPECTO AS IDPROSPECTO, @IDOPORTUNIDAD AS IDOPORTUNIDAD, @IDDOCUMENTO AS IDDOCUMENTO