//[sp_version|Untyped,usuario|Text,]
--SELECT  
DECLARE @DB VARCHAR(16)  
DECLARE @CONVERTCODE VARCHAR(3)  
DECLARE @EXSQL VARCHAR(256)  
DECLARE @SP_VERSION VARCHAR(128)  
DECLARE @IDEMPRESA INT  
DECLARE @MIGRADA INT    

SET @SP_VERSION = '<#SP_VERSION/>'  
SELECT  @IDEMPRESA = IDEMPRESA FROM SALESUP_CT.dbo.USUARIOS WHERE EMAIL = ISNULL(:USUARIO,'')

    
IF @SP_VERSION = ''  
  SELECT @MIGRADA = MIGRADA FROM SALESUP.DBO.EMPRESAS WHERE IDEMPRESA = @IDEMPRESA   
ELSE  
  SET @MIGRADA = 1    
  
IF @MIGRADA = 0 
SET @IDEMPRESA = 0    
SELECT @DB = BD_ACTUAL FROM EMPRESAS WHERE IDEMPRESA = CAST(@IDEMPRESA AS INT) AND BD_ACTUAL <> 'SALESUP_DB0' 


IF @DB IS NULL 
  SET @DB = 'SALESUP_DB1'  
  SET @EXSQL = 'SELECT TOP 1 '+CAST (@IDEMPRESA AS VARCHAR)+' AS LAEMPRESA, ISNULL(P.CONVERTCODE, 103) AS CONVERTCODE , '''+@DB+
		     ''' AS ADB FROM '+@DB+'.DBO.USUARIOS U LEFT JOIN PAISES P ON P.IDPAIS = U.DEFAULT_PAIS WHERE IDEMPRESA = '
			 +CAST (@IDEMPRESA AS VARCHAR)+' ORDER BY NIVEL'  
EXEC (@EXSQL)  
			 