//[tkcom|Text,session.db|Untyped,session.gmt|Untyped,session.idempresa|Untyped,]
DECLARE @GMT INT
DECLARE @TKCOMPANIA VARCHAR(64) 
DECLARE @IDCOMPANIA INT 

SET @TKCOMPANIA = dbo.ValidaToken(ISNULL(:TKCOM,'')) 
SET @IDCOMPANIA  = 0


SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.DBO.COMPANIAS WHERE TKCOM=@TKCOMPANIA

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )
SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT  WITH(NOLOCK)  WHERE GMT= @GMT

SELECT IDSEGUIMIENTO,UE.ESTADO,UE.ESTADO,ISNULL(P.NOMBRE,'')+ ' '+ISNULL(P.APELLIDOS,'') AS NOMBREPROSPECTO,P.TKP AS Tkp,1 as EV,(CASE WHEN P.ESCLIENTE=1 THEN '1' ELSE '' END) AS ESCLIENTE, (CASE WHEN P.ESCLIENTE=0 THEN '1' ELSE '' END) AS ESPROSPECTO,
CONVERT(VARCHAR(10),s.FECHAHORA,103) AS FECHAHORA, p.descartado,
LTRIM(RTRIM(RIGHT(CONVERT(VARCHAR, DATEADD(hh, (6+@GMT),S.FECHAHORA) ,100),8))) AS HORA,S.TIPO_SEGUIMIENTO AS ELTIPO,
CASE WHEN SISTEMA = 1 THEN '1' ELSE '' END AS Sistema,
(CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,
CASE WHEN TIPO_SEGUIMIENTO = 1 AND  UE.ESTADO=0 AND UE.ERRORES>=3 THEN '1' ELSE '' END AS Tipo_Seguimiento1_Error,
CASE WHEN TIPO_SEGUIMIENTO = 1 AND  ((UE.ESTADO=1 AND UE.FECHALEIDO IS NULL) OR (UE.ESTADO=0 AND UE.ERRORES<3) OR UE.FECHALEIDO IS NULL) THEN '1' ELSE '' END AS Tipo_Seguimiento1_Bien,
CASE WHEN TIPO_SEGUIMIENTO = 1 AND  UE.FECHALEIDO IS NOT NULL AND UE.ESTADO=1 THEN '1' ELSE '' END AS Tipo_Seguimiento1_Leido,
CASE WHEN TIPO_SEGUIMIENTO = 2 AND  UE.ESTADO=0 AND UE.ERRORES>=3 THEN '1' ELSE '' END AS Tipo_Seguimiento2_Error,
CASE WHEN TIPO_SEGUIMIENTO = 2 AND   ((UE.ESTADO=1 AND UE.FECHALEIDO IS NULL) OR (UE.ESTADO=0 AND UE.ERRORES<3) OR UE.FECHALEIDO IS NULL) THEN '1' ELSE '' END AS Tipo_Seguimiento2_Bien,
CASE WHEN TIPO_SEGUIMIENTO = 2 AND  UE.FECHALEIDO IS NOT NULL AND UE.ESTADO=1 THEN '1' ELSE '' END AS Tipo_Seguimiento2_Leido,
CASE WHEN LATITUD IS NOT NULL AND LONGITUD IS NOT NULL THEN '1' ELSE '' END AS Latitud_Longitud,
(CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,
CASE WHEN TIPO_SEGUIMIENTO = 3 AND  USMS.ESTADO=1 THEN '1' ELSE '' END AS Tipo_Seguimiento3_Bien,
CASE WHEN TIPO_SEGUIMIENTO = 3 AND  USMS.ESTADO=0 AND USMS.ERRORES>=1 THEN '1' ELSE '' END AS Tipo_Seguimiento3_Error,
CASE WHEN TIPO_SEGUIMIENTO = 4 AND  USMS.ESTADO=1 THEN '1' ELSE '' END AS Tipo_Seguimiento4_Bien,
CASE WHEN TIPO_SEGUIMIENTO = 4 AND  USMS.ESTADO=0 AND USMS.ERRORES>=1  THEN '1' ELSE '' END AS Tipo_Seguimiento4_Error,
CASE WHEN TIPO_SEGUIMIENTO = 5 THEN '1' ELSE '' END AS Tipo_Seguimiento5,
CASE WHEN LATITUD IS NOT NULL AND LONGITUD IS NOT NULL THEN '1' ELSE '' END AS Latitud_Longitud,
CASE WHEN S.TIPO_SEGUIMIENTO = 7 THEN '1' ELSE '' END AS Tipo_Seguimiento7,
CASE WHEN S.TIPO_SEGUIMIENTO = 10 THEN '1' ELSE '' END AS Tipo_Seguimiento10,
CASE S.TIPO_SEGUIMIENTO 
 WHEN 7 THEN T.TKTR 
 ELSE ''
 END AS TK,
S.*, ISNULL(U.INICIALES, '--') AS INICIALES,@TKCOMPANIA AS TKCOM
FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) 
LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)  ON S.IDPROSPECTO=P.IDPROSPECTO  AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U  WITH(NOLOCK)  ON  S.IDUSUARIO = U.IDUSUARIO AND U.IDEMPRESA = <#SESSION.IDEMPRESA/>
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON  UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON  USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7

WHERE P.IDCOMPANIA=@IDCOMPANIA AND S.IDPROSPECTO = P.IDPROSPECTO /*AND  S.IDOPORTUNIDAD IS NULL*/ 
order by S.IDSEGUIMIENTO desc