//[session.idempresa|Untyped,session.idusuario|Untyped,idprospecto|Integer,tkp|Text,session.db|Untyped,]
--UPDATE
DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @TKP VARCHAR(64)
DECLARE @TKPM VARCHAR(64)
DECLARE @CAMBIOLOCAL INT 

SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @TKP = ISNULL(:TKP,'')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA)  end




DECLARE @ASIGNADO INT
DELETE FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WHERE IDPROSPECTO=@IDPROSPECTO

SELECT @ASIGNADO=IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WHERE IDUSUARIO=@IDUSUARIO AND IDPROSPECTO=@IDPROSPECTO
IF @ASIGNADO IS NULL
BEGIN
  INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS (IDUSUARIO,IDPROSPECTO,ARCHIVADO) VALUES (@IDUSUARIO,@IDPROSPECTO,0)
END

UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET DESCARTADO = 0, DESCARTADOPOR = NULL, DESCARTADOFECHA = NULL,DESCARTADORAZON = NULL, IDRAZONPERDIDA = NULL, IDUSUARIO=@IDUSUARIO, ULTIMAMODIFICACION = GETDATE(), 
CAMBIOLOCAL=(CASE WHEN TKPM IS NULL THEN 0 ELSE 1 END)
WHERE IDPROSPECTO=@IDPROSPECTO

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE()) 

INSERT INTO <#SESSION.DB/>.DBO.USUARIOS_SUCESOS (IDUSUARIO,FECHAHORA,TIPO,TEXTO,IDPROSPECTO) 
VALUES (@IDUSUARIO,CONVERT(DATETIME,GetDate(),103),7,'El prospecto ha sido reclamado',@IDPROSPECTO)
