//[idprospectos|Text,session.db|Untyped,]
--SELECT
DECLARE @PROSPECTOS VARCHAR(8000)
SET @PROSPECTOS = ISNULL(:IdProspectos,'')

SELECT IDPROSPECTO,ISNULL(NOMBRE,'') + ' ' +ISNULL(APELLIDOS,'') AS NOMBRE, CORREO FROM <#SESSION.DB/>.DBO.PROSPECTOS 
WHERE IDPROSPECTO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@PROSPECTOS,',')) AND ISNULL(ltrim(CORREO), '')!=''

