//[session.db|Untyped,accion|Integer,ocasion|Text,dia|Integer,mes|Integer,ano|Integer,recordatorio|Text,idfecharecordar|Integer,tkfi|Text,diaSemana|Integer,recurrencia|Integer,]
--insert
/*proegido*/
DECLARE @IDFECHARECORDAR INT
DECLARE @TKFI VARCHAR(64)
SET @TKFI = ISNULL(:TKFI,'')
IF @TKFI != '' BEGIN SELECT @IDFECHARECORDAR = IDFECHARECORDAR FROM <#SESSION.DB/>.dbo.FECHAS_IMPORTANTES WHERE TKFI = @TKFI END

DECLARE @DIASEMANA INT = ISNULL(:DIASEMANA, 0)
DECLARE @DIA INT = ISNULL(:DIA,0)
DECLARE @MES INT = ISNULL(:MES,0)
DECLARE @ANIO INT = ISNULL(:ANO,0)
DECLARE @RECURRENCIA INT = ISNULL(:RECURRENCIA,0)

IF @RECURRENCIA > 1 BEGIN
	UPDATE <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES SET IDACCION = :ACCION, OCASION = :OCASION, DIA = @DIA, MES = @MES, ANIO = @ANIO,DIA_SEMANA = NULL,RECORDATORIO = :RECORDATORIO WHERE IDFECHARECORDAR = @IDFECHARECORDAR
END
IF @RECURRENCIA = 1 BEGIN
	UPDATE <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES SET IDACCION = :ACCION, OCASION = :OCASION, DIA = 0, MES = 0, ANIO = 0, DIA_SEMANA = @DIASEMANA,RECORDATORIO = :RECORDATORIO WHERE IDFECHARECORDAR = @IDFECHARECORDAR
END
IF @RECURRENCIA = 0 BEGIN
	UPDATE <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES SET IDACCION = :ACCION, OCASION = :OCASION, DIA = @DIA, MES = 0, ANIO = 0,DIA_SEMANA = NULL,
 	RECORDATORIO = :RECORDATORIO WHERE IDFECHARECORDAR = @IDFECHARECORDAR
END

