//[nombre|Text,sp_version|Untyped,campo1|Text,correo|Text,campo4|Text,campo5|Text,campo6|Text,telefono|Text,movil|Text,comentarios|Text,idempresa|Integer,idusuario|Text,idorigen|Text,campo2|Text,campo3|Text,refiere|Text,ciudad|Text,direccion1|Text,idetiqueta|Text,idetiqueta1|Text,idetiqueta2|Text,la_bd|Text,]
DECLARE @SQL VARCHAR(MAX)
DECLARE @BASE VARCHAR(MAX)
DECLARE @P_NOMBRE VARCHAR(128) 
DECLARE @P_APELLIDOS VARCHAR(128)
DECLARE @P_CORREO VARCHAR(256)
DECLARE @P_EMPRESA VARCHAR(512)
DECLARE @P_PUESTO VARCHAR(128)
DECLARE @P_WEB VARCHAR(1024)
DECLARE @P_TELEFONO VARCHAR(128)
DECLARE @P_MOVIL VARCHAR(128)
DECLARE @P_COMENTARIOS varchar(8000)
DECLARE @P_IDEMPRESA INT
DECLARE @P_IDUSUARIO INT
DECLARE @P_IDORIGEN INT
DECLARE @P_PAIS VARCHAR(2)
DECLARE @P_ESTADO VARCHAR(4)
DECLARE @P_REFIERE VARCHAR(1024)
DECLARE @P_CIUDAD VARCHAR(128)
DECLARE @P_DIRECCION1 VARCHAR(512)
DECLARE @SP_VERSION VARCHAR(8)
DECLARE @P_IDETIQUETA1 INT
DECLARE @P_IDETIQUETA2 INT
DECLARE @P_IDETIQUETA3 INT
DECLARE @P_CAMPO1 VARCHAR(1024)
DECLARE @P_CAMPO2 VARCHAR(1024)
DECLARE @P_CAMPO3 VARCHAR(1024)
DECLARE @P_CAMPO4 VARCHAR(1024)
DECLARE @P_CAMPO5 VARCHAR(1024)
DECLARE @P_CAMPO6 VARCHAR(1024)
DECLARE @P_CAMPO7 VARCHAR(1024)
DECLARE @P_CAMPO8 VARCHAR(1024)
DECLARE @P_CAMPO9 VARCHAR(1024)
DECLARE @P_CAMPO10 VARCHAR(1024)
DECLARE @P_CAMPO11 VARCHAR(1024)
DECLARE @P_CAMPO12 VARCHAR(1024)
DECLARE @P_CAMPO13 VARCHAR(1024)
DECLARE @P_CAMPO14 VARCHAR(1024)
DECLARE @P_CAMPO15 VARCHAR(1024)
DECLARE @P_CAMPO16 VARCHAR(1024)
DECLARE @P_CAMPO17 VARCHAR(1024)
DECLARE @P_CAMPO18 VARCHAR(1024)
DECLARE @P_CAMPO19 VARCHAR(1024)
DECLARE @P_CAMPO20 VARCHAR(1024)
DECLARE @P_CAMPO21 VARCHAR(1024)
DECLARE @P_CAMPO22 VARCHAR(1024)
DECLARE @P_CAMPO23 VARCHAR(1024)
DECLARE @P_CAMPO24 VARCHAR(1024)
DECLARE @P_CAMPO25 VARCHAR(1024)

SET @BASE=ISNULL(:LA_BD,'')
SET @P_NOMBRE = :NOMBRE
SET @SP_VERSION = '<#SP_VERSION/>'
SET @P_APELLIDOS  = ISNULL(:CAMPO1,'')
SET @P_CORREO = ISNULL(:CORREO,'')
SET @P_EMPRESA =ISNULL(:CAMPO4,'')
SET @P_PUESTO =ISNULL(:CAMPO5,'')
SET @P_WEB =ISNULL(:CAMPO6,'')
SET @P_TELEFONO = ISNULL(:TELEFONO,'')
SET @P_MOVIL = ISNULL(:MOVIL,'')
SET @P_COMENTARIOS = ISNULL(:COMENTARIOS,'')
SET @P_idempresa= ISNULL(:IDEMPRESA,0)
SET @P_IDUSUARIO=CAST(ISNULL(:IDUSUARIO,'') AS INT)
SET @P_IDORIGEN= CAST(ISNULL(:IDORIGEN,'') AS INT)
SET @P_PAIS =ISNULL(:CAMPO2,'')
SET @P_ESTADO =ISNULL(:CAMPO3,'')
SET @P_REFIERE = LEFT(ISNULL(:REFIERE,''), 1024)
SET @P_CIUDAD =ISNULL(:CIUDAD,'')
SET @P_DIRECCION1 =ISNULL(:DIRECCION1,'')
SET @P_idetiqueta1=CAST(ISNULL(:IDETIQUETA,'') AS INT)
SET @P_idetiqueta2=CAST(ISNULL(:IDETIQUETA1,'') AS INT)
SET @P_idetiqueta3=CAST(ISNULL(:IDETIQUETA2,'') AS INT)


IF (@P_idempresa !=0)
BEGIN
	 SET @SQL='
	   EXEC  '+@BASE+'.dbo.SP_INSERTA_PROSPECTO_FCONTACTO '''+@P_NOMBRE+''' ,'''+@P_APELLIDOS +''','''+@P_CORREO+''' ,'''+@P_EMPRESA+''' ,'''+@P_PUESTO+''' ,'''+@P_WEB+''' ,'''+@P_TELEFONO +''','''+@P_MOVIL+''' ,
	   		 '''+@P_COMENTARIOS+''' ,'+CAST( @P_IDEMPRESA AS VARCHAR(1000))+' ,'+CAST(@P_IDUSUARIO AS VARCHAR(1000))+' ,'+CAST(@P_IDORIGEN AS VARCHAR(1000))+' ,'''+@P_PAIS+''' ,'''+@P_ESTADO+''' ,'''' ,
			 '''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,
			 '''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,
			 '''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,'''' ,
			 '''+@P_REFIERE+''' ,'''+@P_CIUDAD+''' ,'''+@P_DIRECCION1+''' ,'+CAST(@P_IDETIQUETA1 AS VARCHAR(1000))+','+CAST(@P_IDETIQUETA2 AS VARCHAR(1000))+','+CAST(@P_IDETIQUETA3 AS VARCHAR(1000))+','''+@SP_VERSION+'''
	 
	 '
	 EXEC (@SQL)
END