//[tk|Text,]
-- select 

DECLARE @TK VARCHAR(64)

SET @TK = dbo.ValidaToken(:TK)

SELECT top 1000 OPCION as dato, ROUND(REPLACE(REPLACE(REPLACE(SALESUP_DB8.dbo.RemueveLetras(CO.CAMPO13), ',', ''), '$', ''), 'USD', '') ,0) as estimado,
LINEA_PRODUCTO AS Linea_producto, 
COUNT(DISTINCT(O.IDOPORTUNIDAD)) AS oportunidades_num, SUM(ISNULL(O.MONTO, 0)) AS oportunidades,  
COUNT(DISTINCT(V.IDVENTA)) AS ventas_num, SUM(ISNULL(V.MONTO, 0)) AS ventas, 
(SALESUP_DB8.DBO.TIEMPO_TXT (P.FECHA_ULTIMOSEGUIMIENTO,GETDATE())) AS Ultimo_contacto_tiempo ,
U.INICIALEs + ' - '+CAST(PSP.COMENTARIO AS VARCHAR(32))  AS ultimo_seguimiento
FROM 
SALESUP_DB8.dbo.EMPRESAS_REPORTES ER, 
SALESUP_DB8.dbo.CATALOGOS C,
SALESUP_DB8.dbo.CATALOGOS_OPCIONES CO,
SALESUP_DB8.dbo.PROSPECTOS P LEFT JOIN SALESUP_DB8.dbo.OPORTUNIDADES O ON O.IDPROSPECTO = P.IDPROSPECTO AND PERDIDA = 0
LEFT JOIN SALESUP_DB8.dbo.EMPRESAS_LINEAS_PRODUCTO L ON L.IDLINEA_PRODUCTO = O.IDLINEA_PRODUCTO
LEFT JOIN SALESUP_DB8.dbo.VENTAS V ON V.IDOPORTUNIDAD = O.IDOPORTUNIDAD
LEFT JOIN SALESUP_DB8.dbo.PROSPECTOS_SEGUIMIENTO PSP ON P.IDULTIMOSEGUIMIENTO = PSP.IDSEGUIMIENTO 
LEFT JOIN SALESUP_DB8.dbo.USUARIOS U ON PSP.IDUSUARIO = U.IDUSUARIO 
WHERE 
  ER.TK = @TK AND P.IDEMPRESA = ER.IDEMPRESA AND
  C.IDCATALOGO = ER.IDCATALOGO AND P.IDCATALOGOOPCION1 = CO.IDCATALOGOOPCION
  /*AND CO.ACTIVO = 1 */ AND P.DESCARTADO = 0
  
  GROUP BY OPCION, CO.CAMPO13, U.INICIALEs ,CAST(PSP.COMENTARIO AS VARCHAR(32)),P.FECHA_ULTIMOSEGUIMIENTO, LINEA_PRODUCTO
  ORDER BY LTRIM(RTRIM(OPCION))