//[start|Integer,howmany|Integer,porempresa|Text,porcatalogo|Text,ordersql|Text,session.db|Untyped,idpantalla|Integer,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Integer,tkcom|Text,]
--SELECT 
/*PROTEGIDO*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
DECLARE @PorEmpresa VARCHAR(MAX)
DECLARE @PORCATALOGO VARCHAR(MAX)
DECLARE @OrderSql VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @TOP VARCHAR(MAX)

SET @TOP= ''
DECLARE @START INT SET @START = :START
DECLARE @HOWMANY INT SET @HOWMANY = :HOWMANY
IF @START IS NOT NULL AND @HOWMANY IS NOT NULL
BEGIN 
	  SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))
END

SET @CRIT=ISNULL('','')
SET @CRITARCHIVAR=ISNULL('','')
SET @PorEmpresa = ISNULL(:PorEmpresa,'')
SET @PORCATALOGO=ISNULL(:PORCATALOGO,'')
SET @OrderSql = ISNULL(:OrderSql,'')
SET @F_USUARIO=ISNULL('','')
DECLARE @DBNAME VARCHAR(MAX) SET @DBNAME = '<#SESSION.DB/>'
DECLARE @IDPANTALLA INT SET @IDPANTALLA = ISNULL(:IDPANTALLA,1)
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @DESCARTADO INT, @IDCOMPANIA INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @NIVELUSUARIO = <#SESSION.NIVEL/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @MAILCONFIG = <#SESSION.MAILCONFIG/>
--SET @DESCARTADO = '+CAST(ISNULL(:DESCARTADO,0) AS VARCHAR(1000)) AS VARCHAR(MAX))+'
SET @IDCOMPANIA = 0
----
DECLARE @TkCom VARCHAR(64)
SET @TkCom = CAST(ISNULL(:TKCOM,' ')  AS VARCHAR(MAX))

DECLARE @PORTKCOM VARCHAR(MAX)
SET @PORTKCOM = ''
--DECLARE @IDCOMPANIA INT;
--SET @IDCOMPANIA = 0
IF @TkCom != ''
BEGIN
   --SELECT @IDCOMPANIA  = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
   SET @PORTKCOM = 'AND COM.TKCOM = '''+CAST(@TkCom AS VARCHAR(MAX))+''' '
END

---
DECLARE @APROBADO VARCHAR(10)
 DECLARE @TABLADEFILTROS TABLE(ID INT, VAL VARCHAR(MAX))
  
  INSERT INTO @TABLADEFILTROS
  SELECT * FROM <#SESSION.DB/>.dbo.filtrospantallas(@IDPANTALLA, @IDEMPRESA, @IDUSUARIO)

  SELECT
    @CRIT = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, CAST(RTRIM(LTRIM(@IDPANTALLA)) AS int))
  SELECT
      @CRIT = @CRIT + <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, 15)

  SELECT @F_USUARIO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 1
  
  SELECT @CRITARCHIVAR = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 2
  
  SELECT @DESCARTADO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 3

  SELECT @APROBADO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 5
  DECLARE @RECHX VARCHAR(10)
  SELECT @RECHX = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 6

  	IF @F_USUARIO IS NOT NULL AND @TKCOM != '' OR 1=1
	BEGIN
		DECLARE @IDSUSUARIOS VARCHAR(MAX)
		SET @IDSUSUARIOS = ''
		SELECT @IDSUSUARIOS=CAST(ID AS VARCHAR(1000))+','+@IDSUSUARIOS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0)
		SET @IDSUSUARIOS=@IDSUSUARIOS+'0'
		SET @F_USUARIO = @F_USUARIO + ' AND A.IDUSUARIO IN  ('+@IDSUSUARIOS+')'
	END
	

SET @SQL ='

DECLARE @POREMPRESA VARCHAR(MAX)
SET @POREMPRESA='''+CAST(@PORCATALOGO AS VARCHAR(MAX))+'''

DECLARE @TkCom VARCHAR(64)
SET @TkCom = '''+CAST(ISNULL(:TKCOM,' ')  AS VARCHAR(MAX))+'''


DECLARE @IDCOMPANIA INT;
SET @IDCOMPANIA = 0
IF @TkCom != ''''
BEGIN
   SELECT @IDCOMPANIA  = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END






  SELECT '+CAST(@TOP AS VARCHAR(MAX))+' P.TKP AS Tkp,P.APROBACIONESTADO, SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS esCanalizado, P.CANALIZADOEL AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, P.USRCANALIZO as Canalizo, P.USRCANALIZADO AS Canalizado,
  P.IdCompania, COM.TkCom,(CASE WHEN CAST(@POREMPRESA AS VARCHAR(MAX))='''' THEN ''ReloadData'' ELSE ''SalesUp.Variables.ReloadDataEmpresaProsp'' END) AS ReloadData,
  P.NARCHIVOS AS tieneArchivos,
  CASE WHEN ('+CAST(@DESCARTADO AS VARCHAR(MAX))+') = 0 AND  ('+CAST(@RECHX AS VARCHAR(MAX))+' = 0) THEN ''1'' ELSE '''' END AS Descartado,
  CASE WHEN P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+'  <= 2 THEN ''1'' ELSE '''' END AS tEtiquetar_tSeguimiento,
  CASE WHEN P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+'  <= 2 THEN ''1'' ELSE '''' END AS tCompartir_tReasignar,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+') AND P.APROBACIONESTADO = 0 THEN ''1'' ELSE '''' END AS tOportunidad_tArchivar,
  CASE WHEN P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' THEN ''1'' ELSE '''' END AS tDescartar,
  CASE WHEN (COM.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+'  <= 2) AND  (P.APROBACIONESTADO != 0) AND <#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa('+CAST(@IDUSUARIO AS VARCHAR(MAX))+',Com.IdCompania) = 1 THEN ''1'' ELSE '''' END AS tAprobar,
  CASE WHEN (COM.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+'  <= 2) AND  (P.APROBACIONESTADO > 1) AND <#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa('+CAST(@IDUSUARIO AS VARCHAR(MAX))+',Com.IdCompania) = 1 THEN '''' ELSE ''1'' END AS tRechazar,
  CASE WHEN P.APROBACIONESTADO = 2 THEN 1 ELSE 0 END AS hRechazar, 
  CASE WHEN COUNT(A3.IDPROSPECTO) > 0 THEN ''1'' ELSE '''' END AS Compartido,
  CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+'  WHEN 0 THEN ''1'' ELSE '''' END AS NoConfigurado,
  CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+'  WHEN 1 THEN ''1'' ELSE '''' END AS EmailConfigurado,
  CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+'  WHEN 2 THEN ''1'' ELSE '''' END AS MailTo,
  
  CASE A2.Archivado WHEN 0 THEN ''1'' ELSE '''' END AS Archivado,
  CASE P.DESCARTADO WHEN 1 THEN ''1'' ELSE '''' END AS EsDescartado,
   
  P.IdProspecto, LTRIM(RTRIM(P.NOMBRE))+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS NombreCliente, LTRIM(RTRIM(P.NOMBRE)) AS Nombre, 
  ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS Apellidos,
  P.Puesto, isnull(P.Empresa,'''') as Empresa,  P.ETIQUETAS_TXT  AS Etiquetas,
  CASE WHEN <#SESSION.DB/>.DBO.ValidaEmail(ISNULL(P.CORREO,'''')) = ''NO'' THEN ''1'' ELSE '''' END as EsCorreo, ISNULL(P.Correo,'''') AS Correo, 
  ISNULL(P.Telefono,'''') AS Telefono, ISNULL(P.Telefono2,'''') AS Telefono2, ISNULL(P.Movil,'''') AS Movil, P.IdUsuario,
  ISNULL(F.Fase,'''') AS Fase, ISNULL(O.Origen,'''') AS Origen, 
  U.Iniciales, U.NOMBRE+'' ''+U.APELLIDOS AS EjecutivoNombre,
  CASE P.Sexo WHEN ''H'' THEN ''Hombre'' WHEN ''M'' THEN ''Mujer'' ELSE '''' END AS Sexo,
  (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS UltimoContactoTiempo,
  CONVERT(VARCHAR(10),P.FECHACONTACTO,103) AS FechaContacto,
  CONVERT(FLOAT,P.FECHACONTACTO) AS FechaContactoInt,
   ISNULL(CAST(S.COMENTARIO AS VARCHAR(MAX)),'''')  AS UltimoContacto,
  ISNULL(U1.INICIALES,'''') AS UltimoUsuario, ISNULL(S.FechaHora,'''') AS FechaHora ,
 A.JSONEVENTO AS proximoEvento,
 U.tku as Tku,
  ( CASE WHEN S.FECHAHORA IS NOT NULL THEN S.FECHAHORA ELSE P.FECHAHORA END) AS ULTIMO_CONTACTO_FECHAHORA,
  
  LTRIM(P.Facebook) as Facebook, LTRIM(P.Twitter) AS Twitter, LTRIM(P.Skype) AS Skype, LTRIM(P.Linkedin) AS Linkedin, LTRIM(P.Googleplus) AS Googleplus, 
  
  CASE WHEN P.CAMPO1 IS NOT NULL THEN P.CAMPO1 ELSE '''' END AS cp1,
  CASE WHEN P.CAMPO2 IS NOT NULL THEN P.CAMPO2 ELSE '''' END AS cp2,
  CASE WHEN P.CAMPO3 IS NOT NULL THEN P.CAMPO3 ELSE '''' END AS cp3,
  CASE WHEN P.CAMPO4 IS NOT NULL THEN P.CAMPO4 ELSE '''' END AS cp4,
  
  CASE WHEN P.CAMPO5 IS NOT NULL THEN P.CAMPO5 ELSE '''' END AS cp5,
  CASE WHEN P.CAMPO6 IS NOT NULL THEN P.CAMPO6 ELSE '''' END AS cp6,
  CASE WHEN P.CAMPO7 IS NOT NULL THEN P.CAMPO7 ELSE '''' END AS cp7,
  CASE WHEN P.CAMPO8 IS NOT NULL THEN P.CAMPO8 ELSE '''' END AS cp8,
  
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '''' END AS cp9,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '''' END AS cp10,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '''' END AS cp11,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '''' END AS cp12,
  
  ISNULL(P.CAMPO13,'''') AS cp13,
  ISNULL(P.CAMPO14,'''') AS cp14,
  ISNULL(P.CAMPO15,'''') AS cp15,
  ISNULL(P.CAMPO16,'''') AS cp16,
  ISNULL(P.CAMPO17,'''') AS cp17,
  ISNULL(P.CAMPO18,'''') AS cp18,
  ISNULL(P.CAMPO19,'''') AS cp19,
  ISNULL(P.CAMPO20,'''') AS cp20,
  
  CP21.OPCION AS cp21,
  CP22.OPCION AS cp22,
  CP23.OPCION AS cp23,
  CP24.OPCION AS cp24,
  CP25.OPCION AS cp25,
  P.CAMPO26 AS cp26, P.CAMPO27 AS cp27, P.CAMPO28 AS cp28P,
  P.CAMPO29 AS cp29, P.CAMPO30 AS cp30, P.CAMPO31 AS cp31P, P.CAMPO32 AS cp32P,
  P.CAMPO33 AS cp33, P.CAMPO34 AS cp34, 
  P.CAMPO35 AS cp35, P.CAMPO36 AS cp36, P.CAMPO37 AS cp37, P.CAMPO38 AS cp38, P.CAMPO39 AS cp39, 
  P.CAMPO40 AS cp40, P.CAMPO41 AS cp41, P.CAMPO42 AS cp42, P.CAMPO43 AS cp43, P.CAMPO44 AS cp44, 
  P.CAMPO45 AS cp45, P.CAMPO46 AS cp46, P.CAMPO47 AS cp47, P.CAMPO48 AS cp48, P.CAMPO49 AS cp49, 
  P.CAMPO50 AS cp50, P.CAMPO51 AS cp51, P.CAMPO52 AS cp52, P.CAMPO53 AS cp53, P.CAMPO54 AS cp54, 
  P.CAMPO55 AS cp55, P.CAMPO56 AS cp56, P.CAMPO57 AS cp57, P.CAMPO58 AS cp58, P.CAMPO59 AS cp59, 
  P.CAMPO60 AS cp60, P.CAMPO61 AS cp61, P.CAMPO62 AS cp62, P.CAMPO63 AS cp63, P.CAMPO64 AS cp64,
  
  CatP1.OPCION AS pCat1, CatP2.OPCION AS pCat2,CatP3.OPCION AS pCat3,
  CatE1.OPCION AS eCat1,CatE2.OPCION AS eCat2,CatE3.OPCION AS eCat3,
  CatI.INDUSTRIA AS CatIndustria, CatG.COMPANIAGRUPO AS CatCorporativo 
  FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 WITH(NOLOCK) ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 WITH(NOLOCK) ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 WITH(NOLOCK) ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 WITH(NOLOCK) ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 WITH(NOLOCK) ON CP25.IDOPCION = P.CAMPO25
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON A.IDPROSPECTO = P.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO AND A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+'
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A3 WITH(NOLOCK) ON A3.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != A3.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA2 WITH(NOLOCK) ON PA2.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO = PA2.IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES O WITH(NOLOCK) ON O.IDORIGEN = P.IDORIGEN 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON P.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO
  LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO = U1.IDUSUARIO      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP1 WITH(NOLOCK) ON CatP1.IDCATALOGOOPCION = P.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP2 WITH(NOLOCK) ON CatP2.IDCATALOGOOPCION = P.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP3 WITH(NOLOCK) ON CatP3.IDCATALOGOOPCION = P.IDCATALOGOOPCION3      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE1 WITH(NOLOCK) ON CatE1.IDCATALOGOOPCION = COM.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE2 WITH(NOLOCK) ON CatE2.IDCATALOGOOPCION = COM.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE3 WITH(NOLOCK) ON CatE3.IDCATALOGOOPCION = COM.IDCATALOGOOPCION3      
  LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS CatI WITH(NOLOCK) ON CatI.IDINDUSTRIA = COM.IDINDUSTRIA      
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CatG WITH(NOLOCK) ON CatG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO         
  WHERE  
    (P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+'  '+CAST(@F_USUARIO AS VARCHAR(MAX))+' AND P.DESCARTADO='+CAST(@DESCARTADO AS VARCHAR(MAX))+'  AND P.ESOPORTUNIDAD = 0 AND ESCLIENTE = 0  
    '+CAST(@CRIT AS VARCHAR(MAX))+' '+CAST(@CRITARCHIVAR AS VARCHAR(MAX))+' '+CAST(@PorEmpresa AS VARCHAR(MAX))+' '+CAST(@PORCATALOGO AS VARCHAR(MAX))+' '+CAST(@PORTKCOM AS VARCHAR(MAX))+'  AND P.APROBACIONESTADO '+CAST(@APROBADO AS VARCHAR(10))+') 
  GROUP BY P.TKP, P.TKPM, P.CANALIZADOEL, P.USRCANALIZO, P.USRCANALIZADO, P.NOMBRE, P.CORREO, F.FASE, P.FECHACONTACTO , p.puesto, P.IDCOMPANIA, COM.TkCom,
    P.FECHA_ULTIMOSEGUIMIENTO,P.TELEFONO, P.TELEFONO2, P.MOVIL, P.IDUSUARIO, P.REFERIDOPOR,   
    P.IDPROSPECTO,P.APELLIDOS,P.EMPRESA, P.DESCARTADO, P.Sexo, P.NARCHIVOS,
    F.ORDEN, s.fechahora, U.IDGRUPO, P.FECHAHORA, CAST(P.COMENTARIOS AS VARCHAR(128)), U.INICIALES, U.APELLIDOS, U.NOMBRE,P.ETIQUETAS_TXT, 
  A2.IDUSUARIO, A2.ARCHIVADO, O.ORIGEN, CAST(S.COMENTARIO AS VARCHAR(MAX)), U1.INICIALES, P.NARCHIVOS, A.JSONEVENTO,
  P.Facebook, P.Twitter, P.Skype, P.Linkedin, P.Googleplus, 
  P.CAMPO1, P.CAMPO2, P.CAMPO3, P.CAMPO4, P.CAMPO5, 
  P.CAMPO6, P.CAMPO7, P.CAMPO8, P.CAMPO9, P.CAMPO10,
  P.CAMPO11, P.CAMPO12, P.CAMPO13, P.CAMPO14, P.CAMPO15,
  P.CAMPO16, P.CAMPO17, P.CAMPO18, P.CAMPO19, P.CAMPO20,
  P.CAMPO21, P.CAMPO22, P.CAMPO23, P.CAMPO24, P.CAMPO25,
  CP21.OPCION, CP22.OPCION, CP23.OPCION, CP24.OPCION, CP25.OPCION,COM.IDINDUSTRIA,COM.IDCOMPANIAGRUPO,
  
  P.CAMPO26, P.CAMPO27, P.CAMPO28,
    P.CAMPO29, P.CAMPO30, P.CAMPO31, P.CAMPO32,
  P.CAMPO33, P.CAMPO34, 
  P.CAMPO35, P.CAMPO36, P.CAMPO37, P.CAMPO38, P.CAMPO39, 
  P.CAMPO40, P.CAMPO41, P.CAMPO42, P.CAMPO43, P.CAMPO44, 
  P.CAMPO45, P.CAMPO46, P.CAMPO47, P.CAMPO48, P.CAMPO49, 
  P.CAMPO50, P.CAMPO51, P.CAMPO52, P.CAMPO53, P.CAMPO54, 
  P.CAMPO55, P.CAMPO56, P.CAMPO57, P.CAMPO58, P.CAMPO59, 
  P.CAMPO60, P.CAMPO61, P.CAMPO62, P.CAMPO63, P.CAMPO64,  
  CatP1.OPCION , CatP2.OPCION ,CatP3.OPCION ,
    CatE1.OPCION ,CatE2.OPCION ,CatE3.OPCION ,   
  CatI.INDUSTRIA , CatG.COMPANIAGRUPO,P.APROBACIONESTADO,COM.IDUSUARIO,U.TKU, Com.IdCompania 
    '+CAST(@OrderSql AS VARCHAR(MAX))+'
  '
  --SELECT @SQL
  EXEC (@SQL)