//[idplantilla|Integer,idprospecto|Integer,idoportunidad|Integer,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,tkp|Text,tko|Text,]
--SELECT
DECLARE @CORREOPROSPECTO VARCHAR(255)
DECLARE @IDPROSPECTO INT
DECLARE @IDoportunidad INT
DECLARE @IDPLANTILLA INT
SET @IDPLANTILLA = ISNULL(:IDPLANTILLA, 0)
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @IDoportunidad = ISNULL(:IDoportunidad,0)

DECLARE @TKP VARCHAR(MAX), @TKO VARCHAR(64)
SET @TKP = ISNULL(:TKP,'')
SET @TKO = ISNULL(:TKO,'')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP,<#SESSION.IDEMPRESA/> ) END
IF @TKO != '' BEGIN SET @IDoportunidad = <#SESSION.DB/>.dbo.obtieneIdOportunidad(@TKO) END


SELECT @CORREOPROSPECTO = CORREO FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO

SELECT <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(CUERPO,@IDPROSPECTO,<#SESSION.IDUSUARIO/>,<#SESSION.IDEMPRESA/>,@IDOPORTUNIDAD) AS CUERPO,
 <#SESSION.DB/>.dbo.ObtieneCuerpoAutoresponder(ASUNTO,@IDPROSPECTO,<#SESSION.IDUSUARIO/>,<#SESSION.IDEMPRESA/>,@IDOPORTUNIDAD) AS ASUNTO, 
 @CORREOPROSPECTO AS CORREO
FROM <#SESSION.DB/>.DBO.USUARIOS_PLANTILLAS
WHERE IDPLANTILLA = @IDPLANTILLA