//[idprospecto|Integer,recordatorio|Text,idrecordatorio|Integer,idpeticion|Text,comentario|Text,horarecordatorio|Text,fecharecordatorio|Text,idfase|Integer,tkp|Text,duracionllamada|Integer,tkrec|Text,session.db|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,00|Text,session.idusuario|Untyped,session.nivel|Untyped,]
-- INSERT 13  
DECLARE @IDPROSPECTO INT
DECLARE @IDRECORDATORIO INT
DECLARE @RECORDATORIO varchar(max)
DECLARE @IDPETICION VARCHAR(100) 
DECLARE @COMENTARIO VARCHAR(MAX), @TKP VARCHAR(MAX)
DECLARE @HORA_RECORDATORIO VARCHAR(100)
DECLARE @FECHARECORDATORIO VARCHAR(100) 
DECLARE @IDFASE INT 
DECLARE @RECURRENCIA INT
DECLARE @TKREC VARCHAR(MAX)
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME
DECLARE @DURACIONLLAMADA INT
DECLARE @TIPO_SEGUIMIENTO INT
SET @FECHAHOY = GETDATE()

SET @IDPROSPECTO= ISNULL(:IDPROSPECTO,0) 
SET @RECORDATORIO = RTRIM(LTRIM(ISNULL(:RECORDATORIO, '') ))
SET @IDRECORDATORIO = ISNULL(:IDRECORDATORIO,0)
SET @IDPETICION=ISNULL(:IDPETICION, '')
SET @COMENTARIO=ISNULL(:COMENTARIO, '') 
SET @HORA_RECORDATORIO=ISNULL(:HORARECORDATORIO, '')
SET @FECHARECORDATORIO= ISNULL(:FECHARECORDATORIO, '')
SET @IDFASE= ISNULL(:IDFASE, 0)
SET @TKP = ISNULL(:TKP,'')
SET @DURACIONLLAMADA =ISNULL(:DURACIONLLAMADA, 0 )
SET @TIPO_SEGUIMIENTO=0

SET @TKREC = ISNULL(:TKREC,'')
IF @TKREC != '' BEGIN SELECT @IDRECORDATORIO = IDRECORDATORIO FROM <#SESSION.DB/>.DBO.RECORDATORIOS WHERE TKREC = @TKREC END


IF @TKP != ''
BEGIN
	 SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP,<#SESSION.IDEMPRESA/> )
END

IF( (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO WHERE FECHAHORA > GETDATE()-1  AND   
     IDPETICION !='' AND IDPETICION = @IDPETICION) = 0)
BEGIN

IF @DURACIONLLAMADA > 0
BEGIN
	 SET @TIPO_SEGUIMIENTO=8
END

DECLARE @TOTAL INT
DECLARE @DUENIO INT
DECLARE @FECHA_RECORDATORIO DATETIME
DECLARE @HORAREC VARCHAR(8000)
DECLARE @FECHA_REC varchar(8000)


if @HORA_RECORDATORIO=''
  begin
  SET @FECHA_REC=@FECHARECORDATORIO
  SET @FECHA_RECORDATORIO=dateadd(hh,12,CONVERT(DATETIME, @FECHA_REC,<#SESSION.CONVERTCODE/>))
  end  
else
  begin  
  SET @HORAREC=@HORA_RECORDATORIO
  IF LEN(@HORAREC)<= 2 SET @HORAREC = @HORAREC + ':00'

  SET @FECHA_REC=@FECHARECORDATORIO+' '+@HORAREC
  SET @FECHA_RECORDATORIO=CONVERT(DATETIME, @FECHA_REC,<#SESSION.CONVERTCODE/>)
  end


declare @idoportunidad int
set @idoportunidad=0
IF (@IDRECORDATORIO>0)
  select @idoportunidad=idoportunidad from <#SESSION.DB/>.DBO.recordatorios WITH(NOLOCK) where idrecordatorio = @IDRECORDATORIO

IF @COMENTARIO != ''
begin
  IF (@idoportunidad > 0)
  BEGIN
    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, COMENTARIO, IDOPORTUNIDAD, IDPETICION, DURACION, TIPO_SEGUIMIENTO )
    VALUES 
    (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @COMENTARIO,@idoportunidad, @IDPETICION, @DURACIONLLAMADA, @TIPO_SEGUIMIENTO )
	
	SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
	
	SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
	
	IF (<#SESSION.NIVEL/> = 1 AND @TOTAL <= 1 AND <#SESSION.IDUSUARIO/> <> @DUENIO)
	BEGIN
		 EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_SEGUIMIENTO @IDPROSPECTO, <#SESSION.IDUSUARIO/>, <#SESSION.IDEMPRESA/>, @COMENTARIO
	END
	
  END
  ELSE
  BEGIN 
    INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, COMENTARIO, IDPETICION, DURACION, TIPO_SEGUIMIENTO)
    VALUES 
    (@IDPROSPECTO, <#SESSION.IDUSUARIO/>, @COMENTARIO, @IDPETICION, @DURACIONLLAMADA, @TIPO_SEGUIMIENTO) 
					  
	SELECT @TOTAL = COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
	
	SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
	
	IF (<#SESSION.NIVEL/> = 1 AND @TOTAL <= 1 AND <#SESSION.IDUSUARIO/> <> @DUENIO)
	BEGIN
		 EXEC <#SESSION.DB/>.DBO.SP_NOTIFICA_SEGUIMIENTO @IDPROSPECTO, <#SESSION.IDUSUARIO/>, <#SESSION.IDEMPRESA/>, @COMENTARIO
	END
	
  END
end

IF LEN(@RECORDATORIO)>0
BEGIN 
  UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMOAVISO = CONVERT(DATETIME,GetDate()-1,<#SESSION.CONVERTCODE/>) WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
  IF (@idoportunidad > 0)
  BEGIN
    INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO, IDOPORTUNIDAD)
    VALUES 
    (@IDPROSPECTO, <#SESSION.IDUSUARIO/>,@FECHA_RECORDATORIO, @RECORDATORIO,@idoportunidad )
  
    EXEC <#SESSION.DB/>.DBO.SP_PROXIMORECORDATORIO_OPORTUNIDAD @idoportunidad 
  
  END
  ELSE
  BEGIN 
    INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK)
    (IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO)
      VALUES 
  (@IDPROSPECTO, <#SESSION.IDUSUARIO/>,@FECHA_RECORDATORIO, @RECORDATORIO)
  END
END


 DECLARE @IDUSUARIO INT
 DECLARE @LA_FASE INT
 SET  @LA_FASE = CAST(@IDFASE AS INT)

 
 DECLARE  @REASIGNADO INT
 DECLARE @OLD_FASE INT
 DECLARE @ESCLIENTE INT
 SELECT @REASIGNADO = REASIGNADO, @IDUSUARIO = IDUSUARIO, @OLD_FASE=IDFASE, @ESCLIENTE=ESCLIENTE FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO

 
  if  (<#SESSION.IDUSUARIO/> = @IDUSUARIO)   SET @REASIGNADO = 0
 
  IF   @LA_FASE!=0
    UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET
     REASIGNADO = @REASIGNADO,  
     IDFASE = @LA_FASE,   
   FECHA_ULTIMOSEGUIMIENTO=GetDate()
   WHERE
     IDPROSPECTO = @IDPROSPECTO

-- se activan las acciones de las fases
   	IF @OLD_FASE<>@LA_FASE AND @LA_FASE !=0 BEGIN
			DECLARE @FASETXT VARCHAR(1000)
			SELECT @FASETXT=' - '+ISNULL(FASE,'') FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WHERE IDFASE=@LA_FASE AND IDEMPRESA=<#SESSION.IDEMPRESA/>
  		EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @LA_FASE,@IDPROSPECTO,@idoportunidad
			IF (@ESCLIENTE=0) BEGIN
 			  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,23,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, @FASETXT,''
      END
			ELSE BEGIN	 
   		  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,22,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, @FASETXT,''
      END
		END    
	 

--inserta el ultimo seguimiento
IF @COMENTARIO != ''
begin
  declare @IDSEGUIMIENTO int
  SELECT TOP 1 @IDSEGUIMIENTO= IDSEGUIMIENTO from <#SESSION.DB/>.DBO.prospectos_seguimiento WITH(NOLOCK) where idprospecto = @IDPROSPECTO  ORDER BY IDSEGUIMIENTO DESC
  IF (@idoportunidad > 0)
  BEGIN
       UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET 
       FECHA_ULTIMOSEGUIMIENTO=GetDate(),
       IDULTIMOSEGUIMIENTO=@IDSEGUIMIENTO
       WHERE
       IDOPORTUNIDAD = @idoportunidad
	END
   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET 
   FECHA_ULTIMOSEGUIMIENTO=GetDate(),
   IDULTIMOSEGUIMIENTO=@IDSEGUIMIENTO
   WHERE
   IDPROSPECTO = @IDPROSPECTO
end
     
   
  
-- Marca un recordatorio previo como realizado
IF (@IDRECORDATORIO>0)
BEGIN
  UPDATE <#SESSION.DB/>.DBO.USUARIOS WITH(ROWLOCK) SET ULTIMOAVISO = CONVERT(DATETIME,GetDate()-1,<#SESSION.CONVERTCODE/>) WHERE IDUSUARIO = <#SESSION.IDUSUARIO/>
  UPDATE <#SESSION.DB/>.DBO.RECORDATORIOS WITH(ROWLOCK) SET COMPLETADO = 1 WHERE IDRECORDATORIO = @IDRECORDATORIO
END

IF (@IDSEGUIMIENTO IS NOT NULL)
BEGIN
	 EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,7,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, '', @IDSEGUIMIENTO
END

END -- del validador de IDPETICION
ELSE 
  INSERT INTO SALESUP_CT.dbo.LOG(IDU, IDP, IDO, TEXTO) VALUES ('<#SESSION.IDUSUARIO/>', @IDPROSPECTO, '', 'Duplicidad de seguimiento')
  
 EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS 1, <#SESSION.IDUSUARIO/>
 
 SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
 EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1
