//[recordatorio|Text,ocasion|Text,ano|Integer,diasemana|Integer,session.convertcode|Untyped,idprospecto|Integer,accion|Integer,plantilla|Integer,dia|Integer,mes|Integer,tkp|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,]
-- INSERT

DECLARE @CC VARCHAR(255)
DECLARE @CCO VARCHAR(255)
DECLARE @PARA VARCHAR(255)
DECLARE @TXTADICIONAL VARCHAR(MAX)
DECLARE @FECHA DATETIME
DECLARE @ANO INT
DECLARE @MESTXT VARCHAR(255)
DECLARE @DIA_SEMANA INT
DECLARE @DIA_SEMANATXT VARCHAR(MAX)
DECLARE @CONVERTCODE INT
DECLARE @IDPROSPECTO INT
DECLARE @ACCION INT
DECLARE @PLANTILLA INT
DECLARE @DIA INT
DECLARE @MES INT
DECLARE @OCASION VARCHAR(MAX)
DECLARE @RECORDATORIO VARCHAR(MAX)
DECLARE @P VARCHAR(MAX)
DECLARE @FECHAHOY DATETIME

SET @RECORDATORIO=ISNULL(:RECORDATORIO,'')
SET @OCASION=ISNULL(:OCASION, '')
SET @ANO=ISNULL(:ANO, 0)
SET @DIA_SEMANA=ISNULL(:DIASEMANA,1)
SET @CONVERTCODE=<#SESSION.CONVERTCODE/>
SET @IDPROSPECTO=ISNULL(:IDPROSPECTO, 0)
SET @ACCION=ISNULL(:ACCION,0)
SET @PLANTILLA=ISNULL(:PLANTILLA, 0)
SET @DIA=ISNULL(:DIA,0)
SET @MES=ISNULL(:MES,0)
SET @FECHAHOY = GETDATE()

declare @tkp varchar(64)

SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, <#SESSION.IDEMPRESA/>) END
SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
IF(@ANO = 1)
BEGIN
	 SELECT @DIA_SEMANATXT=DIATXT FROM <#SESSION.DB/>.DBO.V_DIAS_SEMANA WHERE IDDIA=@DIA_SEMANA
		 INSERT INTO <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES (IDPROSPECTO, IDACCION, OCASION, DIA, MES, ANIO, RECORDATORIO, DIA_SEMANA) VALUES (@IDPROSPECTO, @ACCION, @OCASION, 0, 0, 0, @RECORDATORIO, @DIA_SEMANA) 
	 SET @TXTADICIONAL = '.Todos los '+CAST(@DIA_SEMANATXT AS VARCHAR(MAX))+' de cada semana'
END


ELSE IF((@ANO = 0) OR (@ANO > 3)) 
BEGIN
	 INSERT INTO <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES (IDPROSPECTO, IDACCION, OCASION, DIA, MES, ANIO, RECORDATORIO) VALUES (@IDPROSPECTO, @ACCION, @OCASION, @DIA, @MES, @ANO, @RECORDATORIO)
	 IF(@ANO = 0)
	 BEGIN
	 	  SELECT @MESTXT = MesTxt FROM SALESUP_CT.DBO.V_MESES WHERE IDMES = @MES 
	 	  SET @TXTADICIONAL = '. Todos los años el dia '+CAST(@DIA AS VARCHAR(MAX))+' del mes de ' + @MESTXT
		  END
	ELSE
 	BEGIN
		  SET @FECHA = CONVERT(VARCHAR, CAST(@MES AS VARCHAR(2))+'/'+CAST(@DIA AS VARCHAR(2))+'/'+CAST(@ANO AS VARCHAR(4)), @CONVERTCODE)
		  SET @TXTADICIONAL = '. Fecha de notificación: ' + CONVERT(VARCHAR(10),@FECHA,@CONVERTCODE)
		  END
END
ELSE IF(@ANO = 2)
BEGIN
	 INSERT INTO <#SESSION.DB/>.DBO.FECHAS_IMPORTANTES (IDPROSPECTO, IDACCION, OCASION, DIA, MES, ANIO, RECORDATORIO) VALUES (@IDPROSPECTO, @ACCION, @OCASION, @DIA, 0, 0, @RECORDATORIO)
	 SET @TXTADICIONAL = '.El dia '+CAST(@DIA AS VARCHAR(MAX))+'de cada mes'
END
EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHAHOY,1 
EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>, '52', @IDPROSPECTO, @CONVERTCODE, @TXTADICIONAL,''