//[session.db|Untyped,session.idempresa|Untyped,tkeliminar|Text,tknuevo|Text,]
--update


DECLARE @IDEMPRESA INT
DECLARE @TKELIMINAR VARCHAR(256)
DECLARE @TKNUEVO VARCHAR(256) 
DECLARE @IDNUEVO INT 
DECLARE @IDELIMINAR INT 


SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TKELIMINAR = ISNULL(:TKELIMINAR, '')  
SET @TKNUEVO =ISNULL(:TKNUEVO, '')  

SELECT @IDELIMINAR =IDSEGUIMIENTOCATEGORIA FROM <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS WHERE TK = @TKELIMINAR 
SELECT @IDNUEVO = IDSEGUIMIENTOCATEGORIA FROM <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS WHERE TK=@TKNUEVO  


UPDATE <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO SET IDSEGUIMIENTOCATEGORIA = @IDNUEVO WHERE IDSEGUIMIENTOCATEGORIA=@IDELIMINAR
DELETE FROM <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDSEGUIMIENTOCATEGORIA =@IDELIMINAR