//[tk|Text,session.idempresa|Untyped,session.db|Untyped,]
--select 

DECLARE @IDEMPRESA INT 
DECLARE @TK VARCHAR(256) 

SET @TK=ISNULL(:TK, '') 
SET @IDEMPRESA= <#SESSION.IDEMPRESA/>

SELECT TITULO, CAST(TKTI AS VARCHAR(256)) AS TK FROM <#SESSION.DB/>.DBO.EMPRESAS_TITULOS WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>  AND TKTI !=@TK ORDER BY  1 DESC
