//[idc|Integer,v|Text,idp|Integer,session.convertcode|Untyped,session.idempresa|Untyped,session.db|Untyped,tkp|Text,]
-- SELECT
DECLARE @IDEMPRESA INT, @IDUSUARIO INT, @IDPROSPECTO INT, @INDICE INT, @CONVERTCODE INT
DECLARE @VALOR VARCHAR(MAX), @TKP VARCHAR(MAX) 

SET @INDICE = ISNULL(:IDC,0)
SET @VALOR = :V
SET @IDPROSPECTO = ISNULL(:IDP,0)
SET @CONVERTCODE = CAST('<#SESSION.CONVERTCODE/>' AS INT )
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)


SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = CAST(<#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) AS VARCHAR(MAX)) END

   IF ( @INDICE IN (9, 10, 11, 12) ) 
     BEGIN
      SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCamposUnicos(@INDICE, CONVERT(DATETIME, @VALOR, @CONVERTCODE), @IDPROSPECTO, @IDEMPRESA )
     END
   ELSE 
     BEGIN
      SET  @IDPROSPECTO = <#SESSION.DB/>.dbo.ValidaCamposUnicos(@INDICE, @VALOR, @IDPROSPECTO, @IDEMPRESA )
     END

SELECT P.IDPROSPECTO AS IdP , P.Descartado, CAST(ISNULL(P.NOMBRE, '') AS VARCHAR(256))+ ' ' + CAST(ISNULL(P.APELLIDOS, '') AS VARCHAR(256)) AS Prospecto,
U.IdUsuario , U.NOMBRE + ' ' + U.APELLIDOS +' ('+ U.INICIALES+ ')' as Usuario
FROM <#SESSION.DB/>.dbo.PROSPECTOS P , <#SESSION.DB/>.dbo.USUARIOS U
WHERE P.IDPROSPECTO = @IDPROSPECTO AND U.IDUSUARIO = P.IDUSUARIO
