//[session.idusuario|Untyped,session.idempresa|Untyped,idorigen|Integer,idprospectos|Text,session.db|Untyped,]
-- UPDATE
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @IDORIGEN INT
DECLARE @IDPROSPECTOS VARCHAR(MAX)
DECLARE @FECHA DATETIME

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDORIGEN = :IDORIGEN
SET @IDPROSPECTOS = :IDPROSPECTOS
SET @FECHA = GETDATE()

UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET IDORIGEN = @IDORIGEN WHERE IDEMPRESA = @IDEMPRESA AND IDPROSPECTO IN(SELECT SPLITVALUE FROM DBO.SPLIT(@IDPROSPECTOS,','))

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE()) 

EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO,@FECHA