//[session.nivel|Untyped,session.db|Untyped,session.idusuario|Untyped,]
--select

DECLARE @NIVEL INT

SET @NIVEL=CAST('<#SESSION.NIVEL/>' AS INT)

SELECT SS.SECCION,VTS.IDSUCESO AS TIPO, VTS.SUCESO AS SUCESO_NOMBRE, VTS.SUCESOMOVIL AS TIPOSUCESOMOVIL,
	 (CASE WHEN VTS.IDSUCESO!=16 THEN 1 WHEN VTS.IDSUCESO=16 AND @NIVEL=1 THEN 1 ELSE 0 END) AS MOSTRAR,
	 MODULO , TS.IDUSUARIO
 	 FROM SALESUP_CT.DBO.TIPOS_SUCESOS VTS
LEFT JOIN <#SESSION.DB/>.DBO.TIPO_SUCESOS TS
ON VTS.IDSUCESO=TS.TIPO AND TS.IDUSUARIO=<#SESSION.IDUSUARIO/>
LEFT JOIN SALESUP_CT.dbo.V_SUCESOS_SECCIONES SS ON VTS.SECCION = SS.IDSECCION
WHERE SITIOWEB = 1
GROUP BY SS.SECCION, VTS.IDSUCESO , VTS.SUCESO  , VTS.SUCESOMOVIL , 
(CASE WHEN VTS.IDSUCESO!=16 THEN 1 WHEN VTS.IDSUCESO=16 AND @NIVEL=1 THEN 1 ELSE 0 END),
MODULO, TS.IDUSUARIO
ORDER BY SS.SECCION, SUCESO_NOMBRE