//[monedas|Integer,tipodecambio|Numeric,concepto|Text,session.db|Untyped,idpeticion|Untyped,o|Untyped,session.convertcode|Untyped,session.idempresa|Untyped,idprospecto|Untyped,session.idusuario|Untyped,pesokb|Untyped,tproductos|Integer,session.nombre|Untyped,session.apellidos|Untyped,session.iniciales|Untyped,calendariopagos|Untyped,monto|Untyped,fecha_cierre|Untyped,comision_pct|Untyped,comision_monto|Untyped,idlinea|Untyped,amazon|Untyped,cotizacion|Untyped,seguimiento|Text,referencia|Text,periodicidad|Untyped,comision_modo|Untyped,campo1o|Untyped,campo2o|Untyped,campo3o|Untyped,campo4o|Untyped,campo5o|Untyped,campo6o|Untyped,campo7o|Untyped,campo8o|Untyped,campo9o|Untyped,campo10o|Untyped,campo11o|Untyped,campo12o|Untyped,campo13o|Untyped,campo14o|Untyped,campo15o|Untyped,campo16o|Untyped,campo17o|Untyped,campo18o|Untyped,campo19o|Untyped,campo20o|Untyped,campo21o|Untyped,campo22o|Untyped,campo23o|Untyped,campo24o|Untyped,campo25o|Untyped,campo26o|Untyped,campo27o|Untyped,campo28o|Untyped,campo29o|Untyped,campo30o|Untyped,campo31o|Untyped,campo32o|Untyped,campo35o|Untyped,campo36o|Untyped,campo37o|Untyped,campo38o|Untyped,campo39o|Untyped,campo40o|Untyped,campo41o|Untyped,campo42o|Untyped,campo43o|Untyped,campo44o|Untyped,campo45o|Untyped,campo46o|Untyped,campo47o|Untyped,campo48o|Untyped,campo49o|Untyped,campo50o|Untyped,campo51o|Untyped,campo52o|Untyped,campo53o|Untyped,campo54o|Untyped,campo55o|Untyped,campo56o|Untyped,campo57o|Untyped,campo58o|Untyped,campo59o|Untyped,campo60o|Untyped,campo61o|Untyped,campo62o|Untyped,campo63o|Untyped,campo64o|Untyped,campo1|Untyped,campo2|Untyped,campo3|Untyped,campo4|Untyped,campo5|Untyped,campo6|Untyped,campo7|Untyped,campo8|Untyped,campo9|Untyped,campo10|Untyped,campo11|Untyped,campo12|Untyped,campo13|Untyped,campo14|Untyped,campo15|Untyped,campo16|Untyped,campo17|Untyped,campo18|Untyped,campo19|Untyped,campo20|Untyped,campo21|Untyped,campo22|Untyped,campo23|Untyped,campo24|Untyped,campo25|Untyped,campo26|Untyped,campo27|Untyped,campo28|Untyped,campo29|Untyped,campo30|Untyped,campo31|Untyped,campo32|Untyped,campo35|Untyped,campo36|Untyped,campo37|Untyped,campo38|Untyped,campo39|Untyped,campo40|Untyped,campo41|Untyped,campo42|Untyped,campo43|Untyped,campo44|Untyped,campo45|Untyped,campo46|Untyped,campo47|Untyped,campo48|Untyped,campo49|Untyped,campo50|Untyped,campo51|Untyped,campo52|Untyped,campo53|Untyped,campo54|Untyped,campo55|Untyped,campo56|Untyped,campo57|Untyped,campo58|Untyped,campo59|Untyped,campo60|Untyped,campo61|Untyped,campo62|Untyped,campo63|Untyped,campo64|Untyped,Campo1C|Untyped,Campo2C|Untyped,Campo3C|Untyped,Campo4C|Untyped,Campo5C|Untyped,Campo6C|Untyped,Campo7C|Untyped,Campo8C|Untyped,Campo9C|Untyped,Campo10C|Untyped]
--select
DECLARE @IDUSUARIO INT
DECLARE @IDVENTA INT
DECLARE @IDMONEDA INT = ISNULL(:MONEDAS,0)
DECLARE @TIPODECAMBIO FLOAT = ISNULL(:TIPODECAMBIO,0)
DECLARE @IDOPORTUNIDAD INT
DECLARE @IDCOMPANIA INT
DECLARE @TIENEPRODUCTOS INT
DECLARE @CONCEPTO VARCHAR(MAX)

IF(@TIPODECAMBIO = 0) SET @TIPODECAMBIO = 1
IF(@IDMONEDA = 0)BEGIN
  SELECT @IDMONEDA = IDEMPRESAMONEDA FROM <#SESSION.DB/>.dbo.MONEDAS 
  WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND PORDEFECTO = 1
END

SET @CONCEPTO = ISNULL(:CONCEPTO, '') 

IF( (SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDPETICION !='' AND IDPETICION = '<#IDPETICION/>') = 0)
BEGIN

DECLARE @CONVERTCODE INT, @IDEMPRESA INT
DECLARE @IDPROSPECTO INT
DECLARE @TOTAL INT
DECLARE @HD_USADO FLOAT
DECLARE @PESOKB FLOAT

DECLARE @O_CatalogoOpcion1 INT, @O_CatalogoOpcion2 INT, @O_CatalogoOpcion3 INT


DECLARE @CAMBIOLOCAL INT
DECLARE @NOMBRE_QUIEN_CANALIZA VARCHAR(MAX), @ESCANALIZADO VARCHAR(2)
DECLARE @FECHACANALIZADO DATETIME

DECLARE @IDMONEDADEFAULT INT
  
SET @O_CatalogoOpcion1 = CAST('<#O-CatalogoOpcion1/>' AS INT)  
SET @O_CatalogoOpcion2 = CAST('<#O-CatalogoOpcion2/>' AS INT) 
SET @O_CatalogoOpcion3 = CAST('<#O-CatalogoOpcion3/>' AS INT)

IF @O_CatalogoOpcion1 = 0 BEGIN SET @O_CatalogoOpcion1 = NULL END
IF @O_CatalogoOpcion2 = 0 BEGIN SET @O_CatalogoOpcion2 = NULL END
IF @O_CatalogoOpcion3 = 0 BEGIN SET @O_CatalogoOpcion3 = NULL END


SET @CONVERTCODE = <#SESSION.CONVERTCODE/>
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDPROSPECTO = CAST('<#IDPROSPECTO/>' AS INT)
SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @HD_USADO=0
SET @PESOKB=CAST('<#pesokb/>' AS FLOAT)
SET @TIENEPRODUCTOS = ISNULL(:TPRODUCTOS, 0)

SELECT @IDMONEDADEFAULT = IDEMPRESAMONEDA FROM <#SESSION.DB/>.dbo.MONEDAS WHERE IDEMPRESA = @IDEMPRESA AND PORDEFECTO = 1

SELECT @ESCANALIZADO = SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) FROM <#SESSION.DB/>.dbo.PROSPECTOS P WHERE P.IDPROSPECTO = @IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
IF @ESCANALIZADO = '1' OR @ESCANALIZADO = '2' BEGIN SET @NOMBRE_QUIEN_CANALIZA = '<#SESSION.NOMBRE/> <#SESSION.APELLIDOS/> (<#SESSION.INICIALES/>)' SET @FECHACANALIZADO = GETDATE() SET @CAMBIOLOCAL = 1 END
  
IF @IDCOMPANIA IS NOT NULL 
BEGIN
  EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_PERSONALIZADOS_COMPANIA @IDCOMPANIA,'<#Campo1C/>','<#Campo2C/>','<#Campo3C/>','<#Campo4C/>','<#Campo5C/>','<#Campo6C/>','<#Campo7C/>','<#Campo8C/>','<#Campo9C/>','<#Campo10C/>'
END

UPDATE <#SESSION.DB/>.DBO.USUARIOS SET CALENDARIOPAGOS=CAST('<#CALENDARIOPAGOS/>' AS INT) WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>

declare @idfase INT
if (@ESCANALIZADO = '1' OR @ESCANALIZADO = '2')
   select top 1 @idfase = IDFASE from <#SESSION.DB/>.DBO.oportunidades_fases where idempresa = <#SESSION.IDEMPRESA/>  AND TKM IS NOT NULL order by orden desc
else
  select top 1 @idfase = IDFASE from <#SESSION.DB/>.DBO.oportunidades_fases where idempresa = <#SESSION.IDEMPRESA/>  order by orden desc

INSERT INTO <#SESSION.DB/>.dbo.OPORTUNIDADES WITH(ROWLOCK)
(
 IDPROSPECTO, IDUSUARIO, CONCEPTO, MONTO, CERTEZA, 
 FECHA_CIERRE, IDFASE, COMISION, COMISION_MONTO, 
 IDLINEA_PRODUCTO,AMAZON, IDPETICION,
 IDCATALOGOOPCION1, IDCATALOGOOPCION2, IDCATALOGOOPCION3, CAMBIOLOCAL, USRCANALIZO, CANALIZADOEL,IDEMPRESAMONEDA,IDEMPRESAMONEDADEFAULT
)
VALUES 
(
 <#IDPROSPECTO/>,<#SESSION.IDUSUARIO/>, @CONCEPTO, cast ('<#monto/>' as money), 1, 
 CONVERT(DATETIME,'<#FECHA_CIERRE/>',<#SESSION.CONVERTCODE/>), @idfase, cast ('<#comision_pct/>' as float)/100, cast ('<#comision_monto/>' as money),
 <#idlinea/>, CAST('<#AMAZON>' AS INT), '<#IDPETICION/>',
 @O_CatalogoOpcion1, @O_CatalogoOpcion2, @O_CatalogoOpcion3, @CAMBIOLOCAL, @NOMBRE_QUIEN_CANALIZA, @FECHACANALIZADO,@IDMONEDA,@IDMONEDADEFAULT
)


SELECT TOP 1 @IDOPORTUNIDAD=IDOPORTUNIDAD, @IDPROSPECTO = IDPROSPECTO FROM <#SESSION.DB/>.dbo.OPORTUNIDADES WHERE IDPROSPECTO = <#IDPROSPECTO/> ORDER BY IDOPORTUNIDAD DESC

UPDATE <#SESSION.DB/>.dbo.OPORTUNIDADES SET CONCEPTO  = @CONCEPTO WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD

IF (LTRIM(RTRIM('<#cotizacion/>'))!='')
 BEGIN
  INSERT INTO <#SESSION.DB/>.dbo.EMPRESAS_ARCHIVOS_AMAZON (IDEMPRESA,IDUSUARIO,ARCHIVO,PESO,TIPO) VALUES (<#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,'<#cotizacion/>',@PESOKB,'PO')
  INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ARCHIVOS (IDPROSPECTO,IDOPORTUNIDAD,IDUSUARIO,ARCHIVO,DESCRIPCION,AMAZON,PESO) VALUES (<#IDPROSPECTO/>,@IDOPORTUNIDAD,<#SESSION.IDUSUARIO/>,'<#cotizacion/>',@CONCEPTO,1,@PESOKB)
  /*UPDATE <#SESSION.DB/>.dbo.EMPRESAS SET HD_USADO=HD_USADO+@PESOKB WHERE IDEMPRESA=<#SESSION.IDEMPRESA/>*/
 END 


UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET ESOPORTUNIDAD = 1 WHERE IDPROSPECTO = <#IDPROSPECTO/>
UPDATE <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS SET ARCHIVADO = 0 WHERE IDPROSPECTO = <#IDPROSPECTO/> AND IDUSUARIO = <#SESSION.IDUSUARIO/>


/* Para la comision por linea de vendedor */
IF ((SELECT COUNT(*) FROM <#SESSION.DB/>.dbo.USUARIOS_LINEAS_COMISION WHERE IDLINEA = <#idlinea/> AND IDUSUARIO = <#SESSION.IDUSUARIO/>) = 1)
BEGIN
  UPDATE <#SESSION.DB/>.dbo.USUARIOS_LINEAS_COMISION SET COMISION = cast ('<#comision_PCT/>' as float)/100 WHERE IDLINEA = <#idlinea/> AND IDUSUARIO = <#SESSION.IDUSUARIO/>
END
ELSE
BEGIN
  INSERT INTO <#SESSION.DB/>.dbo.USUARIOS_LINEAS_COMISION (COMISION, IDLINEA, IDUSUARIO) VALUES (cast('<#comision_PCT/>' as float)/100, <#idlinea/>, <#SESSION.IDUSUARIO/>)
END

INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO, SISTEMA)
VALUES 
  (<#IDPROSPECTO/>, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, 'Convertido en oportunidad con el '+CAST (cast ((1) as int) as varchar) + '% de certeza.',1)



IF NOT  ( LTRIM (:seguimiento) IS NULL )
  INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO
  (IDPROSPECTO, IDUSUARIO, IDOPORTUNIDAD, COMENTARIO)
  VALUES 
  (<#IDPROSPECTO/>, <#SESSION.IDUSUARIO/>, @IDOPORTUNIDAD, :seguimiento)
  

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 

EXEC <#SESSION.DB/>.dbo.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,1,<#IDPROSPECTO/>,<#SESSION.CONVERTCODE/>,'', ''
 
--EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS 1,<#SESSION.IDUSUARIO/>  
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS 2,<#SESSION.IDUSUARIO/>


-----------------
--inserta oportunidad
-----------------
--insert



--SELECT
DECLARE @FECHAMETA DATETIME

SET @FECHAMETA = convert(DATETIME,'<#FECHA_CIERRE/>', <#SESSION.CONVERTCODE/>)
SELECT @IDPROSPECTO=IDPROSPECTO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(NOLOCK) WHERE IDOPORTUNIDAD = @IDOPORTUNIDAD

UPDATE <#SESSION.DB/>.DBO.OPORTUNIDADES WITH(ROWLOCK) SET
  GANADA=1,
  GANADA_FECHA = convert(DATETIME,'<#FECHA_CIERRE/>', <#SESSION.CONVERTCODE/>) 
WHERE
  IDOPORTUNIDAD = @IDOPORTUNIDAD
  
INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(ROWLOCK) (IDPROSPECTO, IDOPORTUNIDAD, IDUSUARIO, COMENTARIO, SISTEMA)  VALUES 
 (@IDPROSPECTO, @IDOPORTUNIDAD, <#SESSION.IDUSUARIO/> , '¡La oportunidad se ha ganado! Hay una venta más.',1)

INSERT INTO <#SESSION.DB/>.DBO.VENTAS WITH(ROWLOCK)
 (IDOPORTUNIDAD, MONTO, COMISION, FECHAHORA,REFERENCIA, IDUSUARIO, PERIODICIDAD,TIPOCOMISION, CAMBIOLOCAL,IDMONEDA,TIPODECAMBIO,IDEMPRESAMONEDADEFAULT)
VALUES
 (@IDOPORTUNIDAD,0,0,  convert(DATETIME,'<#FECHA_CIERRE/>', <#SESSION.CONVERTCODE/>), :REFERENCIA,<#SESSION.IDUSUARIO/>,<#PERIODICIDAD/>,<#comision_modo/>, @CAMBIOLOCAL,@IDMONEDA,@TIPODECAMBIO,@IDMONEDADEFAULT)

 
SELECT TOP 1 @IDVENTA=IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS WITH(NOLOCK) WHERE 
 IDOPORTUNIDAD = @IDOPORTUNIDAD AND FECHAHORA =  convert(DATETIME,'<#FECHA_CIERRE/>', <#SESSION.CONVERTCODE/>) 
ORDER BY IDVENTA DESC

-- se activan las acciones de las fases
          DECLARE @IDFASEC INT
          DECLARE @IDFASEP INT
            --SELECT TOP 1 @IDFASEC=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WITH(NOLOCK) WHERE IDEMPRESA=<#SESSION.IDEMPRESA/> AND FASECLIENTE=1 ORDER BY ORDEN ASC
          SELECT @IDFASEP=IDFASE FROM <#SESSION.DB/>.DBO.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO
          IF (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_FASES WITH(NOLOCK) WHERE IDFASE=@IDFASEC AND FASECLIENTE=1 ) > 0
           begin
            UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET ESCLIENTE=1, @IDFASEC=IDFASE, ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO
          EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @IDFASEC,@IDPROSPECTO,@IDOPORTUNIDAD  
           end
          else   
            UPDATE <#SESSION.DB/>.DBO.PROSPECTOS WITH(ROWLOCK) SET ESCLIENTE=1, ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO  



--EXEC SP_STS_ACTUALIZA_USUARIO <#SESSION.IDUSUARIO/>  
EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_OPORTUNIDADES <#SESSION.IDUSUARIO/>,9,@IDPROSPECTO,@IDOPORTUNIDAD,<#SESSION.CONVERTCODE/>, '' ,''

DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES WITH(ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = <#SESSION.IDEMPRESA/>
DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) WHERE IDTABLA = 15 AND IDUSUARIO =<#SESSION.IDUSUARIO/> 

INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES(4,<#SESSION.IDEMPRESA/>) 
INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDUSUARIO) VALUES(15,<#SESSION.IDUSUARIO/>) 

DECLARE @FECHAMETADA DATETIME
SET @FECHAMETA = CONVERT(DATETIME,'<#FECHA_CIERRE/>',<#SESSION.CONVERTCODE/>)           
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO 3, <#SESSION.IDUSUARIO/>, @FECHAMETA
SELECT @IDVENTA AS AIDVENTA, V.IDOPORTUNIDAD, O.TKO FROM <#SESSION.DB/>.DBO.VENTAS V,<#SESSION.DB/>.DBO.OPORTUNIDADES O WHERE V.IDVENTA=@IDVENTA AND O.IDOPORTUNIDAD= V.IDOPORTUNIDAD 

/*SE ACTUALIZAR LOS PERSONALIZABLES*/
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_CAMPOS_PERSONALIZABLES 4, @IDOPORTUNIDAD, @IDEMPRESA, @CONVERTCODE,
'<#CAMPO1O/>' , '<#CAMPO2O/>' , '<#CAMPO3O/>' , '<#CAMPO4O/>', 
'<#CAMPO5O/>' , '<#CAMPO6O/>' , '<#CAMPO7O/>' , '<#CAMPO8O/>', 
'<#CAMPO9O/>' , '<#CAMPO10O/>', '<#CAMPO11O/>', '<#CAMPO12O/>', 
'<#CAMPO13O/>', '<#CAMPO14O/>', '<#CAMPO15O/>', '<#CAMPO16O/>', 
'<#CAMPO17O/>', '<#CAMPO18O/>', '<#CAMPO19O/>', '<#CAMPO20O/>', 
'<#CAMPO21O/>', '<#CAMPO22O/>', '<#CAMPO23O/>', '<#CAMPO24O/>', '<#CAMPO25O/>', 
'<#CAMPO26O/>', '<#CAMPO27O/>', '<#CAMPO28O/>', '<#CAMPO29O/>', 
'<#CAMPO30O/>', '<#CAMPO31O/>', '<#CAMPO32O/>',
'<#CAMPO35O/>', '<#CAMPO36O/>',
'<#CAMPO37O/>', '<#CAMPO38O/>', '<#CAMPO39O/>', '<#CAMPO40O/>',
'<#CAMPO41O/>', '<#CAMPO42O/>', '<#CAMPO43O/>', '<#CAMPO44O/>',
'<#CAMPO45O/>', '<#CAMPO46O/>', '<#CAMPO47O/>', '<#CAMPO48O/>',
'<#CAMPO49O/>', '<#CAMPO50O/>', '<#CAMPO51O/>', '<#CAMPO52O/>',
'<#CAMPO53O/>', '<#CAMPO54O/>', '<#CAMPO55O/>', '<#CAMPO56O/>',
'<#CAMPO57O/>', '<#CAMPO58O/>', '<#CAMPO59O/>', '<#CAMPO60O/>',
'<#CAMPO61O/>', '<#CAMPO62O/>', '<#CAMPO63O/>', '<#CAMPO64O/>'

/*SE ACTUALIZAR LOS PERSONALIZABLES*/
EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_CAMPOS_PERSONALIZABLES 3, <#IDPROSPECTO/>, @IDEMPRESA, @CONVERTCODE,
'<#CAMPO1/>' , '<#CAMPO2/>' , '<#CAMPO3/>' , '<#CAMPO4/>', 
'<#CAMPO5/>' , '<#CAMPO6/>' , '<#CAMPO7/>' , '<#CAMPO8/>', 
'<#CAMPO9/>' , '<#CAMPO10/>', '<#CAMPO11/>', '<#CAMPO12/>', 
'<#CAMPO13/>', '<#CAMPO14/>', '<#CAMPO15/>', '<#CAMPO16/>', 
'<#CAMPO17/>', '<#CAMPO18/>', '<#CAMPO19/>', '<#CAMPO20/>', 
'<#CAMPO21/>', '<#CAMPO22/>', '<#CAMPO23/>', '<#CAMPO24/>', '<#CAMPO25/>', 
'<#CAMPO26/>', '<#CAMPO27/>', '<#CAMPO28/>', '<#CAMPO29/>', 
'<#CAMPO30/>', '<#CAMPO31/>', '<#CAMPO32/>',
'<#CAMPO35/>', '<#CAMPO36/>',
'<#CAMPO37/>', '<#CAMPO38/>', '<#CAMPO39/>', '<#CAMPO40/>',
'<#CAMPO41/>', '<#CAMPO42/>', '<#CAMPO43/>', '<#CAMPO44/>',
'<#CAMPO45/>', '<#CAMPO46/>', '<#CAMPO47/>', '<#CAMPO48/>',
'<#CAMPO49/>', '<#CAMPO50/>', '<#CAMPO51/>', '<#CAMPO52/>',
'<#CAMPO53/>', '<#CAMPO54/>', '<#CAMPO55/>', '<#CAMPO56/>',
'<#CAMPO57/>', '<#CAMPO58/>', '<#CAMPO59/>', '<#CAMPO60/>',
'<#CAMPO61/>', '<#CAMPO62/>', '<#CAMPO63/>', '<#CAMPO64/>'
	 
/* Agrega campos auto y uuid  P-(1), O-(2), C-(3), V-(4) */
EXEC <#SESSION.DB/>.dbo.SP_ACTUALIZA_AUTO_UUID @IDOPORTUNIDAD, 4, @IDEMPRESA 


  -- se activan las acciones de las fases
  /*EXEC <#SESSION.DB/>.DBO.SP_EJECUTA_ACCION @idfase,<#IDPROSPECTO/>,@IDOPORTUNIDAD*/  


END -- del validador de IDPETICION
ELSE 
BEGIN
  INSERT INTO SALESUP_CT.dbo.LOG(IDU, IDP, IDO, TEXTO) VALUES ('<#SESSION.IDUSUARIO/>', '<#IDPROSPECTO/>', '', 'Duplicidad de venta directa')
  SELECT TOP 1 @IDVENTA=IDVENTA FROM <#SESSION.DB/>.DBO.VENTAS V, <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK) WHERE 
   IDPROSPECTO = <#IDPROSPECTO/> AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD   ORDER BY IDVENTA DESC
END

SELECT ISNULL(@IDVENTA,0) AS AIDVENTA, V.IDOPORTUNIDAD, O.TKO FROM <#SESSION.DB/>.DBO.VENTAS V,<#SESSION.DB/>.DBO.OPORTUNIDADES O WHERE V.IDVENTA=@IDVENTA AND O.IDOPORTUNIDAD= V.IDOPORTUNIDAD 

