//[session.idusuario|Untyped,session.idempresa|Untyped,session.convertcode|Untyped,idpeticion|Integer,comentario|Text,recordatorio|Text,fecharecordatorio|Text,horarecordatorio|Text,idseguimiento|Integer,idprospecto|Integer,idrecordatorio|Integer,tkp|Text,session.db|Untyped,idfase|Integer,]
--INSERT

DECLARE @IDPETICION VARCHAR(MAX), @COMENTARIO VARCHAR(MAX), @RECORDATORIO VARCHAR(MAX)
DECLARE @FECHARECORDATORIO VARCHAR(MAX), @HORARECORDATORIO VARCHAR(MAX)
DECLARE @IDUSUARIO INT, @IDEMPRESA INT, @IDSEGUIMIENTO INT, @IDPROSPECTO INT
DECLARE @CONVERTCODE INT, @IDRECORDATORIO INT
DECLARE @FECHAHORA DATETIME, @FECHA DATETIME
DECLARE @P VARCHAR(MAX)
DECLARE @IDFASE INT 

SET @FECHA = GETDATE()
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

SET @IDPETICION = ISNULL(:IDPETICION,'')
SET @COMENTARIO = ISNULL(:COMENTARIO,'')
SET @RECORDATORIO = ISNULL(:RECORDATORIO,'')
SET @FECHARECORDATORIO = ISNULL(:FECHARECORDATORIO,'')
SET @HORARECORDATORIO = ISNULL(:HORARECORDATORIO,'')
SET @IDFASE=ISNULL(:IDFASE, 0) 
SET @FECHAHORA = CONVERT(DATETIME, @FECHARECORDATORIO + ' '+ @HORARECORDATORIO, @CONVERTCODE)

SET @IDSEGUIMIENTO = ISNULL(:IDSEGUIMIENTO,0)
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @IDRECORDATORIO = ISNULL(:IDRECORDATORIO,0)

DECLARE @TKP VARCHAR(MAX)
SET @TKP = ISNULL(:TKP,'')

IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA ) END



IF (SELECT COUNT(*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WHERE FECHAHORA > GETDATE()-1 AND IDPETICION != '' AND IDPETICION = @IDPETICION) = 0
BEGIN
	
	IF  @COMENTARIO != ''
	BEGIN
		INSERT INTO <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO (IDPROSPECTO, IDUSUARIO, COMENTARIO, IDSEGUIMIENTOCATEGORIA)
		VALUES (@IDPROSPECTO, @IDUSUARIO, @COMENTARIO, @IDSEGUIMIENTO)
	END
	
	IF  ( @RECORDATORIO != NULL   OR  @RECORDATORIO !=''  )
	BEGIN 
		UPDATE <#SESSION.DB/>.DBO.USUARIOS SET ULTIMOAVISO = CONVERT(DATETIME,@FECHA-1,@CONVERTCODE) WHERE IDUSUARIO = @IDUSUARIO
		INSERT INTO <#SESSION.DB/>.DBO.RECORDATORIOS
		(IDPROSPECTO, IDUSUARIO, FECHAHORA, RECORDATORIO)
		VALUES 
		(@IDPROSPECTO, @IDUSUARIO, @FECHAHORA, @RECORDATORIO)
	END
	
	DECLARE @IDUSUARIOPROSPECTO INT, @NOCOMENTARIOS INT
	
	SELECT @IDUSUARIOPROSPECTO = IDUSUARIO FROM <#SESSION.DB/>.DBO.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
	SELECT @NOCOMENTARIOS = COUNT (*) FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WHERE IDPROSPECTO = @IDPROSPECTO AND IDUSUARIO = @IDUSUARIOPROSPECTO AND SISTEMA = 0
	
	IF @NOCOMENTARIOS > 0
	BEGIN
		UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET
		FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,@FECHA,@CONVERTCODE),
		REASIGNADO = 0, IDFASE=@IDFASE   
		WHERE
		IDPROSPECTO = @IDPROSPECTO
	END
	ELSE
	BEGIN
		UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET   
		FECHA_ULTIMOSEGUIMIENTO=CONVERT(DATETIME,@FECHA,@CONVERTCODE)
		WHERE
		IDPROSPECTO = @IDPROSPECTO
	END
	
	-- MARCA UN RECORDATORIO PREVIO COMO REALIZADO
	IF @IDRECORDATORIO > 0
	BEGIN
		UPDATE <#SESSION.DB/>.DBO.USUARIOS SET ULTIMOAVISO = CONVERT(DATETIME,@FECHA-1,@CONVERTCODE) WHERE IDUSUARIO = @IDUSUARIO
		UPDATE <#SESSION.DB/>.DBO.RECORDATORIOS SET COMPLETADO = 1 WHERE IDRECORDATORIO = @IDRECORDATORIO
	END  
	
	IF @COMENTARIO != ''
	BEGIN
		SELECT TOP 1 @IDSEGUIMIENTO = IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO WITH(NOLOCK) WHERE IDPROSPECTO = @IDPROSPECTO  ORDER BY IDSEGUIMIENTO DESC
	END  
	SET @P = CAST(@IDPROSPECTO AS VARCHAR(MAX))
	EXEC <#SESSION.DB/>.DBO.SP_UPDATE_PROSPECTOS_ASIGNADOS @P,@FECHA,1
	EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS @IDUSUARIO, 13, @IDPROSPECTO, @CONVERTCODE, '', @IDSEGUIMIENTO
	EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO, @FECHA
END








