//[lista_prosp|Text,lista_etq|Text,operacion|Integer,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.convertcode|Untyped,tkpe|Text,]
--insert
DECLARE @LISTAPROSPECTOS VARCHAR(8000)
DECLARE @LISTAETIQUETAS VARCHAR(8000)
DECLARE @IDPROSPECTO INT   
DECLARE @operacion INT
DECLARE @TKPEXISTE VARCHAR(MAX)

SET @LISTAPROSPECTOS = ISNULL(:LISTA_PROSP,'')
SET @LISTAETIQUETAS = ISNULL(:Lista_etq,'')
SET @TKPEXISTE = ISNULL(:tkPe,'')
SET @operacion=ISNULL(:operacion,0)



IF @TKPEXISTE != '' 
BEGIN 
 select @LISTAPROSPECTOS = <#SESSION.DB/>.dbo.obtieneListaIdProspecto(@LISTAPROSPECTOS, <#SESSION.IDEMPRESA/>)
END

IF @operacion = 2
BEGIN
   INSERT INTO  <#SESSION.DB/>.dbo.ELIMINACIONES (IDTABLA,IDNUEVO,IDELIMINADO,TIPO,IDEMPRESA,FECHAHORA) 
   SELECT 6,A.splitvalue,B.splitvalue,1,<#SESSION.IDEMPRESA/>,GETDATE() 
   FROM <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') A, <#SESSION.DB/>.dbo.Split(@LISTAETIQUETAS, ',') B, <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS PE
   WHERE PE.IDPROSPECTO = A.SplitValue AND PE.IDETIQUETA = B.SplitValue
   
   DELETE  FROM  <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS WHERE 
   IDPROSPECTO IN  (SELECT splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ','))
   AND IDETIQUETA IN  (SELECT splitvalue FROM <#SESSION.DB/>.dbo.Split(@LISTAETIQUETAS, ','))
END
ELSE
BEGIN

  INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS (IDETIQUETA, IDPROSPECTO) SELECT N.splitvalue, A.splitvalue 
  FROM <#SESSION.DB/>.dbo.Split(@LISTAETIQUETAS, ',') N CROSS JOIN <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') A 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ETIQUETAS PE ON A.splitvalue = PE.IDPROSPECTO AND N.splitvalue = PE.IDETIQUETA
  WHERE PE.IDETIQUETA IS NULL GROUP BY N.splitvalue, A.splitvalue

  DECLARE @TABLATEMP TABLE (ID INT IDENTITY,IDPROSPECTO int)
  DECLARE @TO INT, @TOTAL INT
  SET @TO = 1

  INSERT INTO @TABLATEMP (IDPROSPECTO)
  SELECT CAST(SplitValue as int) from <#SESSION.DB/>.dbo.Split(@LISTAPROSPECTOS, ',') GROUP BY splitvalue

  SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

  WHILE @TO <= @TOTAL
  BEGIN
  SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
  UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO AND IDEMPRESA = <#SESSION.IDEMPRESA/>
  EXEC  <#SESSION.DB/>.DBO.SP_ENVIA_AUTORESPONDER_ESPECIFICO <#SESSION.IDEMPRESA/>, @IDPROSPECTO,   @LISTAETIQUETAS
  EXEC <#SESSION.DB/>.DBO.SP_INGRESA_SUCESOS_PROSPECTOS <#SESSION.IDUSUARIO/>,4,@IDPROSPECTO,<#SESSION.CONVERTCODE/>, '',''
  SET @TO = @TO + 1
  END
  
  DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = <#SESSION.IDEMPRESA/> AND IDTABLA = 4
  INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(<#SESSION.IDEMPRESA/>,4,GETDATE()) 
  
END
