//[criterio_opor_desc|Text,session.db|Untyped,idprospecto|Text,]
--select
DECLARE @CRIT VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)
SET @CRIT = ISNULL( :CRITERIO_OPOR_DESC , '')

SET @SQL = 'SELECT COUNT (*) AS OP_TOTAL FROM <#SESSION.DB/>.DBO.OPORTUNIDADES O WHERE O.IDPROSPECTO =  '+  ISNULL( :IDPROSPECTO,  '') + ' AND O.GANADA=0' + @CRIT
EXEC (@SQL)


