//[OBJETO|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,session.gmt|Untyped,session.convertcode|Untyped]
--SELECT
DECLARE @IDUSUARIO INT  
DECLARE @IDEMPRESA INT  
DECLARE @OBJETO VARCHAR(MAX) 
DECLARE @TOTAL INT
DECLARE @GMT INT
DECLARE @CONVERTCODE INT 
DECLARE @ORDENAMIENTO VARCHAR(MAX) = ' 1 DESC '	

SET @TOTAL = 1
SET @GMT = <#SESSION.GMT/> 
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/> 
SET @OBJETO = ISNULL(:OBJETO,'')
SET @CONVERTCODE = <#SESSION.CONVERTCODE/>

EXEC <#SESSION.DB/>.DBO.SP_REPORTE_ACTIVIDADES_SUCESOS_CUERPO @IDEMPRESA, @IDUSUARIO, @OBJETO, @GMT, @CONVERTCODE, @TOTAL,@ORDENAMIENTO