//[session.db|Untyped,tkrsv|Text,]
--select

DECLARE @TKURV VARCHAR(MAX)
DECLARE @IDREPORTEVARIANTE INT

SET @TKURV = ISNULL(:TKRSV, '')

SELECT @IDREPORTEVARIANTE = IDREPORTEVARIANTE 
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE TKURV = @TKURV

SELECT variante, agruparPor, periodicidad, criteriosVisibles, compartido, compartidoCon, totalizar
FROM <#SESSION.DB>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE IDREPORTEVARIANTE = @IDREPORTEVARIANTE 