//[session.idempresa|Untyped,q|Text,session.db|Untyped,session.idusuario|Untyped,]
--SELECT  
/*protegido*/
DECLARE @IDEMPRESA INT
DECLARE @Q VARCHAR(MAX), @QRYCONSULTA VARCHAR(MAX), @CONSULTASQL VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @Q =ISNULL(:Q,'')
SET @Q = '%'+@Q+'%'

SET @CONSULTASQL = ''
SET @CONSULTASQL = SALESUP_CT.DBO.ArmaQryConsulta(@Q )

SET @QRYCONSULTA = ''
SET @QRYCONSULTA = @QRYCONSULTA + ' SELECT 2 as tipo, P.idProspecto, p.tkp, '
SET @QRYCONSULTA = @QRYCONSULTA + ' LTRIM(RTRIM(P.NOMBRE)) + '' '' + ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS contacto , '
SET @QRYCONSULTA = @QRYCONSULTA + ' <#SESSION.DB/>.dbo.NomalizaCadena(LTRIM(RTRIM(P.NOMBRE))) + '' ''+ <#SESSION.DB/>.dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''')) AS contactoNormalizado, '
SET @QRYCONSULTA = @QRYCONSULTA + ' P.CORREO AS correo '
SET @QRYCONSULTA = @QRYCONSULTA + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P '
SET @QRYCONSULTA = @QRYCONSULTA + ' LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = P.IDUSUARIO '
SET @QRYCONSULTA = @QRYCONSULTA + ' WHERE P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.DESCARTADO = 0 '
SET @QRYCONSULTA = @QRYCONSULTA + ' AND P.IDUSUARIO  IN ( SELECT ID FROM  <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulosCorreos(<#SESSION.IDUSUARIO/>, <#SESSION.IDEMPRESA/>, 1))	 '
SET @QRYCONSULTA = @QRYCONSULTA + @CONSULTASQL
SET @QRYCONSULTA = @QRYCONSULTA + ' ORDER BY P.NOMBRE '

EXEC (@QRYCONSULTA)
