//[session.nivel|Untyped,session.db|Untyped,session.idempresa|Untyped,idprospecto|Integer,session.idgrupo|Untyped,session.idusuario|Untyped,]
--SELECT
DECLARE @IDPROSPECTO INT, @NIVEL INT, @IDUSUARIO INT, @IDEMPRESA INT, @IDGRUPO INT

SET @IDPROSPECTO=ISNULL(:IDPROSPECTO,0)
SET @NIVEL = <#SESSION.NIVEL/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDGRUPO   = <#SESSION.IDGRUPO/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>


IF @NIVEL=1
BEGIN
	SELECT 
		V.TKV, O.TKO, U.INICIALES, V.IDVENTA, P.IDPROSPECTO, O.IDOPORTUNIDAD, O.CONCEPTO, V.FECHAHORA, 
		V.MONTO AS MONTO, 
		V.ANTICIPOS_MONTO AS ANTICIPOS_MONTO, 
		V.SALDO_MONTO AS SALDO_MONTO, 
		V.REFERENCIA, V.IDUSUARIO, P.IDUSUARIO AS D_PROS,U.IDGRUPO,U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') AS EJECUTIVO_NOMBRE,
		MONCT.MONEDA_SIMBOLO, UNICODE(MONCT.MONEDA_SIMBOLO) AS UNICODEMONEDA, LP.LINEA_PRODUCTO as LineaProducto
  	FROM 
		<#SESSION.DB/>.DBO.VENTAS V 
			LEFT JOIN <#SESSION.DB/>.DBO.MONEDAS MON ON MON.IDEMPRESAMONEDA = V.IDMONEDA AND MON.IDEMPRESA = @IDEMPRESA
			LEFT JOIN SALESUP_CT.DBO.MONEDAS MONCT ON MONCT.IDMONEDA = MON.IDMONEDA,
		<#SESSION.DB/>.DBO.OPORTUNIDADES O,
		<#SESSION.DB/>.DBO.PROSPECTOS P,
		<#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP,
		<#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
    	P.IDEMPRESA = @IDEMPRESA AND P.IDPROSPECTO = @IDPROSPECTO AND P.IDPROSPECTO = O.IDPROSPECTO AND 
		O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND V.IDUSUARIO = U.IDUSUARIO AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
	ORDER BY
		V.FECHAHORA
END
IF @NIVEL=2
BEGIN
	SELECT 
    	V.TKV, O.TKO, U.INICIALES, V.IDVENTA, P.IDPROSPECTO, O.IDOPORTUNIDAD, O.CONCEPTO, V.FECHAHORA,
	    V.MONTO AS MONTO, 
		V.ANTICIPOS_MONTO AS ANTICIPOS_MONTO, 
		V.SALDO_MONTO AS SALDO_MONTO,
		V.REFERENCIA,V.IDUSUARIO, P.IDUSUARIO AS D_PROS,U.IDGRUPO, U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') AS EJECUTIVO_NOMBRE,
		MONCT.MONEDA_SIMBOLO, UNICODE(MONCT.MONEDA_SIMBOLO) AS UNICODEMONEDA, LP.LINEA_PRODUCTO as LineaProducto
  	FROM 
		<#SESSION.DB/>.DBO.VENTAS V
			LEFT JOIN <#SESSION.DB/>.DBO.MONEDAS MON ON MON.IDEMPRESAMONEDA = V.IDMONEDA AND MON.IDEMPRESA = @IDEMPRESA
			LEFT JOIN SALESUP_CT.DBO.MONEDAS MONCT ON MONCT.IDMONEDA = MON.IDMONEDA,
		<#SESSION.DB/>.DBO.OPORTUNIDADES O,
		<#SESSION.DB/>.DBO.PROSPECTOS P,
		<#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP, 
		<#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
    	P.IDEMPRESA = @IDEMPRESA AND P.IDPROSPECTO = @IDPROSPECTO AND P.IDPROSPECTO = O.IDPROSPECTO 
		AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD AND V.IDUSUARIO = U.IDUSUARIO  AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
		AND (U.IDGRUPO = @IDGRUPO OR P.IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PAM WHERE IDUSUARIO = @IDUSUARIO))
	ORDER BY 
		V.FECHAHORA
END
IF @NIVEL=3
BEGIN
	SELECT 
		V.TKV, O.TKO, U.INICIALES, V.IDVENTA, O.IDPROSPECTO, O.IDOPORTUNIDAD, O.CONCEPTO, V.FECHAHORA,
		V.MONTO AS MONTO, 
		V.ANTICIPOS_MONTO AS ANTICIPOS_MONTO, 
		V.SALDO_MONTO AS SALDO_MONTO, 
		V.REFERENCIA,V.IDUSUARIO, O.IDUSUARIO AS D_PROS,U.IDGRUPO, U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') AS EJECUTIVO_NOMBRE,
		MONCT.MONEDA_SIMBOLO, UNICODE(MONCT.MONEDA_SIMBOLO) AS UNICODEMONEDA, LP.LINEA_PRODUCTO as LineaProducto
 	FROM 
		<#SESSION.DB/>.DBO.VENTAS V
			LEFT JOIN <#SESSION.DB/>.DBO.MONEDAS MON ON MON.IDEMPRESAMONEDA = V.IDMONEDA AND MON.IDEMPRESA = @IDEMPRESA
			LEFT JOIN SALESUP_CT.DBO.MONEDAS MONCT ON MONCT.IDMONEDA = MON.IDMONEDA,
		<#SESSION.DB/>.DBO.OPORTUNIDADES O,
		<#SESSION.DB/>.DBO.EMPRESAS_LINEAS_PRODUCTO LP,
		<#SESSION.DB/>.DBO.USUARIOS U
  	WHERE 
	  	O.IDPROSPECTO = @IDPROSPECTO  AND O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
		AND V.IDUSUARIO = U.IDUSUARIO AND O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
		AND ( O.IDPROSPECTO IN (SELECT IDPROSPECTO FROM <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PAM WHERE IDUSUARIO = @IDUSUARIO))
	ORDER BY 
		V.FECHAHORA
END
