//[session.idusuario|Untyped,top_registros|Text,tkca|Text,descartado|Integer,f_usuario|Text,critarchivar|Text,session.db|Untyped,]
DECLARE @IDUSUARIO INT
DECLARE @TKCA VARCHAR(64) 
DECLARE @TOPR VARCHAR(1000)
DECLARE @DESCARTADO INT
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITERIO VARCHAR(MAX)
SET @IDUSUARIO= CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TOPR=ISNULL(:TOP_REGISTROS,'')
SET @TKCA= dbo.ValidaToken(:TKCA)
SET @DESCARTADO=CAST(ISNULL(:DESCARTADO,0) AS INT)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')
SET @CRITERIO=ISNULL(:CRITARCHIVAR,'')
EXEC <#SESSION.DB/>.dbo.SP_CLIENTES_POR_CATALOGO @IDUSUARIO,@TKCA,@TOPR,@DESCARTADO,@F_USUARIO,@CRITERIO