//[inicia|Integer,howmany|Integer,directorio|Text,mostrar|Integer,buscar|Text,orden1|Integer,orden2|Integer,ordenextra|Integer,pais|Text,estado|Text,bcp|Integer,session.idusuario|Untyped,session.idempresa|Untyped,session.db|Untyped,session.idgrupo|Untyped,session.nivel|Untyped,]
--SELECT
DECLARE @DIRECTORIO VARCHAR(MAX)
DECLARE @MOSTRAR INT
DECLARE @BUSCAR VARCHAR(MAX)
DECLARE @ORDEN1 INT
DECLARE @ORDEN2 INT
DECLARE @TOTALES INT
DECLARE @EMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @BASE VARCHAR(MAX)
DECLARE @IDGRUPO INT
DECLARE @NIVEL INT
DECLARE @PAIS VARCHAR(5)
DECLARE @ESTADO VARCHAR(5)
DECLARE @BCP INT
DECLARE @BCP_NOMBRE VARCHAR(MAX)
DECLARE @ORDENEXTRA INT

DECLARE @TOP VARCHAR(50)
DECLARE @START INT SET @START = ISNULL(:INICIA,1)
DECLARE @HOWMANY INT SET @HOWMANY = ISNULL(:HOWMANY,50)
SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))
--SELECT @TOP
SET @DIRECTORIO =  ISNULL(:DIRECTORIO,'')
SET @MOSTRAR = ISNULL(:MOSTRAR,0)
SET @BUSCAR = ISNULL(:BUSCAR,'')
SET @ORDEN1 = ISNULL(:ORDEN1,0)
SET @ORDEN2 = ISNULL(:ORDEN2,0)
SET @ORDENEXTRA = ISNULL(:ORDENEXTRA,0)
SET @PAIS = ISNULL(:PAIS,'')
SET @ESTADO = ISNULL(:ESTADO, '')
SET @TOTALES = 0
SET @BCP = ISNULL(:BCP,0)
SET @BCP_NOMBRE = 'directorio-'+CAST(<#SESSION.IDUSUARIO/> AS varchar(100))
SET @EMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @BASE = '<#SESSION.DB/>'
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @NIVEL = <#SESSION.NIVEL/>

--DECLARE @TOTALES2 INT

--SET @TOTALES2 = 
--EXEC <#SESSION.DB/>.dbo.SP_LISTA_DIRECTORIO @DIRECTORIO, @MOSTRAR, @BUSCAR, @ORDEN1, @ORDEN2, 1, @EMPRESA, @IDUSUARIO, @BASE, @IDGRUPO, @NIVEL, @PAIS, @ESTADO, 0, @BCP_NOMBRE

--SELECT @TOTALES2
EXEC <#SESSION.DB/>.dbo.SP_LISTA_DIRECTORIO @DIRECTORIO, @MOSTRAR, @BUSCAR, @ORDEN1, @ORDEN2, @TOTALES, @EMPRESA, @IDUSUARIO, @BASE, @IDGRUPO, @NIVEL, @PAIS, @ESTADO, @BCP, @BCP_NOMBRE, @ORDENEXTRA, @TOP