//[session.idempresa|Untyped,q|Text,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT
DECLARE @Q VARCHAR(MAX), @QRYCONSULTA VARCHAR(MAX), @CONSULTASQL VARCHAR(MAX)
DECLARE @Q1 VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @Q1=ISNULL(:Q,'')	
SET @Q = '%'+@Q1+'%'

SET @CONSULTASQL = ''
SET @CONSULTASQL = SALESUP_CT.DBO.ArmaQryConsulta(@Q )

SET @QRYCONSULTA = ''
SET @QRYCONSULTA = @QRYCONSULTA + ' SELECT 1 AS LE, P.Tkp, P.IDPROSPECTO AS IdProspecto, '''+@Q1+''' AS Q,'
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(P.TITULO+'' '','''') AS Titulo , LTRIM(RTRIM(P.NOMBRE)) AS Nombre , '
SET @QRYCONSULTA = @QRYCONSULTA + ' <#SESSION.DB/>.dbo.NomalizaCadena(LTRIM(RTRIM(P.NOMBRE))) AS NomNorma, '
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS Apellido , '
SET @QRYCONSULTA = @QRYCONSULTA + ' <#SESSION.DB/>.dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''')) AS ApeNorma, '
SET @QRYCONSULTA = @QRYCONSULTA + ' P.EMPRESA AS Empresa, P.CORREO AS Correo, P.SEXO AS Sexo, '
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(P.TELEFONO,'''') + ISNULL('', ''+P.TELEFONO2,'''') AS Telefono, ISNULL(P.MOVIL,'''') AS Movil, '
SET @QRYCONSULTA = @QRYCONSULTA + ' ISNULL(E.ESTADO+'', '','''')+ ISNULL(PAI.PAIS,'''') AS Region, '
SET @QRYCONSULTA = @QRYCONSULTA + ' P.ESCLIENTE AS EsCliente , LTRIM(RTRIM(U.INICIALES)) AS Iniciales '
SET @QRYCONSULTA = @QRYCONSULTA + ' FROM <#SESSION.DB/>.dbo.PROSPECTOS P '
SET @QRYCONSULTA = @QRYCONSULTA + ' LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS '
SET @QRYCONSULTA = @QRYCONSULTA + ' LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO '
SET @QRYCONSULTA = @QRYCONSULTA + ' LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = P.IDUSUARIO '
SET @QRYCONSULTA = @QRYCONSULTA + ' WHERE P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.DESCARTADO = 0 '
SET @QRYCONSULTA = @QRYCONSULTA + @CONSULTASQL
SET @QRYCONSULTA = @QRYCONSULTA + ' ORDER BY P.NOMBRE '

EXEC (@QRYCONSULTA)
