//[porempresa|Text,start|Integer,howmany|Integer,porcatalogo|Text,ordersql|Text,idpantalla|Integer,tkcom|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Integer,]
--select
/*PROTEGIDO*/
DECLARE @SQL VARCHAR(MAX)
DECLARE @TOP VARCHAR(1000)
DECLARE @POREMPRESA VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
DECLARE @PORCATALOGO VARCHAR(MAX)
DECLARE @OrderSql VARCHAR(MAX)
DECLARE @COLUMNAORDEN VARCHAR(MAX) = ''
SET @POREMPRESA= ISNULL(:PorEmpresa,'')

SET @TOP= ''
DECLARE @START INT SET @START = :START
DECLARE @HOWMANY INT SET @HOWMANY = :HOWMANY
IF @START IS NOT NULL AND @HOWMANY IS NOT NULL
BEGIN 
    SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))
END
SET @CRIT= ''
SET @F_USUARIO= ''
SET @CRITARCHIVAR= ''
SET @PORCATALOGO=ISNULL(:PORCATALOGO,'')
SET @OrderSql=ISNULL(:OrderSql,'')
DECLARE @IDPANTALLA INT SET @IDPANTALLA = ISNULL(:IDPANTALLA,4)
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT, @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @DBNAME VARCHAR(MAX)
SET @TkCom = ISNULL(:TKCOM,'')
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @DBNAME = '<#SESSION.DB/>'
SET @NIVELUSUARIO = <#SESSION.NIVEL/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @MAILCONFIG = <#SESSION.MAILCONFIG/>
SET @DESCARTADO = CAST(ISNULL(:DESCARTADO,0) AS VARCHAR(1000))
SET @IDCOMPANIA = 0
DECLARE @ORTEMP VARCHAR(MAX);

SET  @ORTEMP = REPLACE(@OrderSql,'ORDER BY','');
SET  @ORTEMP = REPLACE(@ORTEMP,'ASC','');
SET  @ORTEMP = REPLACE(@ORTEMP,'DESC','');
SET  @ORTEMP = REPLACE(@ORTEMP,' ,1,2 ','');
SET  @ORTEMP = REPLACE(@ORTEMP,' ','');
DECLARE @NWO VARCHAR(MAX) 
SET @NWO = ''

IF @ORTEMP = 'MontoComprado' OR @ORTEMP =  'Saldo' OR @ORTEMP = 'MontoPromedio' OR @ORTEMP = 'SaldoVencido' OR @ORTEMP = 'Anticipos'
BEGIN
  SET @NWO = @OrderSql
  SET @OrderSql = ''
END

IF @NWO = '' 
BEGIN
  SET @NWO = 'ORDER BY SQL1.COLUMNAEXTRA ASC ,2,3' 
END

SET @TkCom = CAST(ISNULL(:TKCOM,' ')  AS VARCHAR(MAX))

DECLARE @PORTKCOM VARCHAR(MAX)
SET @PORTKCOM = ''
--DECLARE @IDCOMPANIA INT;
--SET @IDCOMPANIA = 0
IF @TkCom != ''
BEGIN
   --SELECT @IDCOMPANIA  = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
   SET @PORTKCOM = ' AND COM.TKCOM = '''+CAST(@TkCom AS VARCHAR(MAX))+''' '
END

 DECLARE @APROBADO VARCHAR(10)
 DECLARE @TABLADEFILTROS TABLE(ID INT, VAL VARCHAR(MAX))
  
  INSERT INTO @TABLADEFILTROS
  SELECT * FROM <#SESSION.DB/>.dbo.filtrospantallas(@IDPANTALLA, @IDEMPRESA, @IDUSUARIO)

  SELECT
    @CRIT = <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, CAST(RTRIM(LTRIM(@IDPANTALLA)) AS int))
  SELECT
      @CRIT = @CRIT + <#SESSION.DB/>.DBO.UDF_CONSTRUYE_FILTRO(@IDUSUARIO, 15)

  SELECT @F_USUARIO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 1
  
  SELECT @CRITARCHIVAR = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 2
  
  SELECT @DESCARTADO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 3

  SELECT @APROBADO = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 5
  
  DECLARE @RECHX VARCHAR(10)
  SELECT @RECHX = VAL
  FROM @TABLADEFILTROS
  WHERE ID = 6

IF @F_USUARIO IS NOT NULL AND @TKCOM != ''
  BEGIN
    DECLARE @IDSUSUARIOS VARCHAR(MAX)
    SET @IDSUSUARIOS = ''
    SELECT @IDSUSUARIOS=CAST(ID AS VARCHAR(1000))+','+@IDSUSUARIOS FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,@IDPANTALLA,0)
    SET @IDSUSUARIOS=@IDSUSUARIOS+'0'
    SET @F_USUARIO = ' AND ( (P.IDUSUARIO IN('+@IDSUSUARIOS+')))'
  END

IF @TkCom != ''''
BEGIN
   SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END
SET @SQL ='
DECLARE @IDCOMPANIA VARCHAR(MAX)
SET @IDCOMPANIA = '+CAST(@IDCOMPANIA AS VARCHAR(MAX))+'

IF OBJECT_ID(''tempdb..#tblMior'') IS NOT NULL
DROP TABLE #tblMior
SELECT '+CAST(@TOP AS VARCHAR(MAX))+' IDENTITY(INT) AS COLUMNAEXTRA,P.TKP AS Tkp, P.IdCompania, COM.TkCom, U.Tku,
  SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS esCanalizado, P.CANALIZADOEL AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, P.USRCANALIZO as Canalizo, P.USRCANALIZADO AS Canalizado,
  SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, NULL, NULL) AS VerArchivos, P.NARCHIVOS AS tieneArchivos,
    CASE   WHEN ('+CAST(@DESCARTADO AS VARCHAR(MAX))+') = 0 AND  ('+CAST(@RECHX AS VARCHAR(MAX))+' = 0) THEN ''1'' ELSE '''' END AS Descartado,
  (CASE WHEN '''+CAST(@POREMPRESA AS VARCHAR(MAX))+'''='''' THEN ''ReloadData'' ELSE ''SalesUp.Variables.ReloadDataEmpresaClie'' END) AS ReloadData,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2) AND  (P.APROBACIONESTADO < 2) AND <#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa('+CAST(@IDUSUARIO AS VARCHAR(MAX))+',Com.IdCompania) = 1  THEN ''true'' ELSE '''' END AS tSeguimiento,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2) AND  (P.APROBACIONESTADO < 2) AND <#SESSION.DB/>.dbo.obtienePermisoUtilizarEmpresa('+CAST(@IDUSUARIO AS VARCHAR(MAX))+',Com.IdCompania) = 1  THEN ''true'' ELSE '''' END AS tEtiquetar,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2)   AND  (P.APROBACIONESTADO < 2) THEN ''true'' ELSE '''' END AS tCompartir,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2)  AND  (P.APROBACIONESTADO < 2) THEN ''true'' ELSE '''' END AS tReasignar,
  CASE WHEN P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+'  AND  P.APROBACIONESTADO < 2 THEN ''1'' ELSE '''' END AS tDescartar,
  CASE WHEN (P.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+') AND (P.APROBACIONESTADO = 0) THEN ''true'' ELSE '''' END AS tOportunidad,
CASE WHEN (COM.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+'  OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2) AND  (P.APROBACIONESTADO != 0) THEN ''1'' ELSE '''' END AS tAprobar,
  CASE WHEN (COM.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' OR '+CAST(@NIVELUSUARIO AS VARCHAR(MAX))+' <= 2) AND  (P.APROBACIONESTADO > 1) THEN '''' ELSE ''1'' END AS tRechazar,
  CASE WHEN (P.APROBACIONESTADO = 0) THEN ''true'' ELSE '''' END AS tVtaDirecta,
  CASE WHEN (SELECT COUNT(*) FROM  <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A3 WITH(NOLOCK) WHERE A3.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != A3.IDUSUARIO) > 0 THEN ''1'' ELSE '''' END AS Compartido,
  CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+' WHEN 0 THEN ''1'' ELSE '''' END AS NoConfigurado,
    CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+' WHEN 1 THEN ''1'' ELSE '''' END AS EmailConfigurado,
    CASE '+CAST(@MAILCONFIG AS VARCHAR(MAX))+' WHEN 2 THEN ''1'' ELSE '''' END AS MailTo,
  
  ISNULL(LTRIM(RTRIM(P.NOMBRE)),'''')+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS Prospecto, 
  CASE P.Sexo WHEN ''H'' THEN ''Hombre'' WHEN ''M'' THEN ''Mujer'' ELSE '''' END AS Sexo,
  ISNULL(P.Telefono,'''') AS Telefono, ISNULL(P.Movil,'''') AS Movil, P.Puesto,  ISNULL(P.Correo,'''') AS Correo, isnull(P.Telefono2,'''') as Telefono2, isnull(Fase,'''') as Fase,
  isnull(PO.Origen,'''') as Origen, COUNT (DISTINCT V.IDVENTA) AS Transacciones,
  
  isnull(U.Iniciales,'''') as Iniciales, 
  U.NOMBRE+'' ''+U.APELLIDOS AS EjecutivoNombre,
  P.IdProspecto, ISNULL(LTRIM(RTRIM(P.Empresa)),'''') AS Empresa, P.IdUsuario, P.EsCliente, 
  P.ETIQUETAS_TXT AS Etiquetas,
  SALESUP_CT.DBO.FechaFormato(MAX(V.FECHAHORA),5) AS FechaHora,
  MAX(V.FECHAHORA) AS DT_FechaHora,
  DATEDIFF("d", MAX(V.FECHAHORA) , SALESUP_CT.DBO.GETONLYDATE(GETDATE())) AS Dias ,
  CAST(PS.COMENTARIO AS VARCHAR(MAX)) AS Comentario,
  <#SESSION.DB/>.DBO.TIEMPO_TXT (MAX(PS.FECHAHORA),GETDATE())  AS TiempoTxt,
  isnull(U1.INICIALES,'''') AS InicialUltimoUsuario,
   
   
  CASE WHEN P.CAMPO1 IS NOT NULL THEN P.CAMPO1 ELSE '''' END AS cp1,
  CASE WHEN P.CAMPO2 IS NOT NULL THEN P.CAMPO2 ELSE '''' END AS cp2,
  CASE WHEN P.CAMPO3 IS NOT NULL THEN P.CAMPO3 ELSE '''' END AS cp3,
  CASE WHEN P.CAMPO4 IS NOT NULL THEN P.CAMPO4 ELSE '''' END AS cp4,
  
  CASE WHEN P.CAMPO5 IS NOT NULL THEN P.CAMPO5 ELSE '''' END AS cp5,
  CASE WHEN P.CAMPO6 IS NOT NULL THEN P.CAMPO6 ELSE '''' END AS cp6,
  CASE WHEN P.CAMPO7 IS NOT NULL THEN P.CAMPO7 ELSE '''' END AS cp7,
  CASE WHEN P.CAMPO8 IS NOT NULL THEN P.CAMPO8 ELSE '''' END AS cp8,
  
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '''' END AS cp9,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '''' END AS cp10,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '''' END AS cp11,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '''' END AS cp12,
  
  ISNULL(P.CAMPO13,'''') AS cp13,
  ISNULL(P.CAMPO14,'''') AS cp14,
  ISNULL(P.CAMPO15,'''') AS cp15,
  ISNULL(P.CAMPO16,'''') AS cp16,
  ISNULL(P.CAMPO17,'''') AS cp17,
  ISNULL(P.CAMPO18,'''') AS cp18,
  ISNULL(P.CAMPO19,'''') AS cp19,
  ISNULL(P.CAMPO20,'''') AS cp20,
 
  CP21.OPCION AS cp21,
  CP22.OPCION AS cp22,
  CP23.OPCION AS cp23,
  CP24.OPCION AS cp24,
  CP25.OPCION AS cp25,
  P.CAMPO26 AS cp26, P.CAMPO27 AS cp27, P.CAMPO28 AS cp28P,
  P.CAMPO29 AS cp29, P.CAMPO30 AS cp30, P.CAMPO31 AS cp31P, P.CAMPO32 AS cp32P,
  P.CAMPO33 AS cp33, P.CAMPO34 AS cp34,
  P.CAMPO35 AS cp35, P.CAMPO36 AS cp36, P.CAMPO37 AS cp37, P.CAMPO38 AS cp38, P.CAMPO39 AS cp39, 
  P.CAMPO40 AS cp40, P.CAMPO41 AS cp41, P.CAMPO42 AS cp42, P.CAMPO43 AS cp43, P.CAMPO44 AS cp44, 
  P.CAMPO45 AS cp45, P.CAMPO46 AS cp46, P.CAMPO47 AS cp47, P.CAMPO48 AS cp48, P.CAMPO49 AS cp49, 
  P.CAMPO50 AS cp50, P.CAMPO51 AS cp51, P.CAMPO52 AS cp52, P.CAMPO53 AS cp53, P.CAMPO54 AS cp54, 
  P.CAMPO55 AS cp55, P.CAMPO56 AS cp56, P.CAMPO57 AS cp57, P.CAMPO58 AS cp58, P.CAMPO59 AS cp59, 
  P.CAMPO60 AS cp60, P.CAMPO61 AS cp61, P.CAMPO62 AS cp62, P.CAMPO63 AS cp63, P.CAMPO64 AS cp64,
   CatP1.OPCION AS pCat1, CatP2.OPCION AS pCat2,CatP3.OPCION AS pCat3,
  CatE1.OPCION AS eCat1,CatE2.OPCION AS eCat2,CatE3.OPCION AS eCat3  , 
  CatI.INDUSTRIA AS CatIndustria, CatG.COMPANIAGRUPO AS CatCorporativo, A.JSONEVENTO AS proximoEvento '+CAST(@COLUMNAORDEN AS VARCHAR(MAX))+'
INTO #tblMior FROM  
  
    <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO WITH(NOLOCK)
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) ON P.IDORIGEN = PO.IDORIGEN 
  JOIN  <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
    LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO AND A2.IDUSUARIO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+'
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 WITH(NOLOCK) ON CP21.IDOPCION = P.CAMPO21
    LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 WITH(NOLOCK) ON CP22.IDOPCION = P.CAMPO22
    LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 WITH(NOLOCK) ON CP23.IDOPCION = P.CAMPO23
    LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 WITH(NOLOCK) ON CP24.IDOPCION = P.CAMPO24
    LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 WITH(NOLOCK) ON CP25.IDOPCION = P.CAMPO25
    LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO 
    LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK) ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD

    
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
    JOIN  <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO PS WITH(NOLOCK) ON PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO
  JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON U1.IDUSUARIO = PS.IDUSUARIO
    JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON P.IDPROSPECTO = A.IDPROSPECTO

  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP1 WITH(NOLOCK) ON CatP1.IDCATALOGOOPCION = P.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP2 WITH(NOLOCK) ON CatP2.IDCATALOGOOPCION = P.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP3 WITH(NOLOCK) ON CatP3.IDCATALOGOOPCION = P.IDCATALOGOOPCION3      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE1 WITH(NOLOCK) ON CatE1.IDCATALOGOOPCION = COM.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE2 WITH(NOLOCK) ON CatE2.IDCATALOGOOPCION = COM.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE3 WITH(NOLOCK) ON CatE3.IDCATALOGOOPCION = COM.IDCATALOGOOPCION3      
  LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS CatI WITH(NOLOCK) ON CatI.IDINDUSTRIA = COM.IDINDUSTRIA      
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CatG WITH(NOLOCK) ON CatG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO         
  
  WHERE  
    P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.ESCLIENTE =1  AND P.APROBACIONESTADO '+CAST(@APROBADO AS VARCHAR(MAX))+'
    '+CAST(@CRIT AS VARCHAR(MAX))+' '+CAST(@F_USUARIO AS VARCHAR(MAX))+' '+CAST(@CRITARCHIVAR AS VARCHAR(MAX))+' '+CAST(@POREMPRESA AS VARCHAR(MAX))+' '+CAST(@PORCATALOGO AS VARCHAR(MAX))+' '+CAST(@PORTKCOM AS VARCHAR(MAX))+'
  GROUP BY 
    p.tkp ,P.NARCHIVOS, A2.IDUSUARIO, fase,P.IDPROSPECTO, P.NOMBRE, P.APELLIDOS, P.Puesto, P.EMPRESA,  PO.ORIGEN, U.INICIALES, 
  U.NOMBRE, U.APELLIDOS,A.JSONEVENTO,
  P.ETIQUETAS_TXT, P.ESCLIENTE, P.IDUSUARIO, P.IDCOMPANIA, COM.TkCom,
  telefono, movil, telefono2, CAST(PS.COMENTARIO AS VARCHAR(MAX)), U1.INICIALES, PS.FECHAHORA, P.CORREO, 
  P.CAMPO1, P.CAMPO2, P.CAMPO3, P.CAMPO4, P.CAMPO5,
  P.CAMPO6, P.CAMPO7, P.CAMPO8, P.CAMPO9, P.CAMPO10,
  P.CAMPO11, P.CAMPO12, P.CAMPO13, P.CAMPO14, P.CAMPO15,
  P.CAMPO16, P.CAMPO17, P.CAMPO18, P.CAMPO19, P.CAMPO20,
  P.CAMPO21, P.CAMPO22, P.CAMPO23, P.CAMPO24, P.CAMPO25,
  CP21.OPCION, CP22.OPCION, CP23.OPCION, CP24.OPCION, CP25.OPCION,COM.IDINDUSTRIA,COM.IDCOMPANIAGRUPO,
  P.CAMPO26, P.CAMPO27, P.CAMPO28,
    P.CAMPO29, P.CAMPO30, P.CAMPO31, P.CAMPO32,
  P.CAMPO33, P.CAMPO34,
  P.CAMPO35, P.CAMPO36, P.CAMPO37, P.CAMPO38, P.CAMPO39, 
  P.CAMPO40, P.CAMPO41, P.CAMPO42, P.CAMPO43, P.CAMPO44, 
  P.CAMPO45, P.CAMPO46, P.CAMPO47, P.CAMPO48, P.CAMPO49, 
  P.CAMPO50, P.CAMPO51, P.CAMPO52, P.CAMPO53, P.CAMPO54, 
  P.CAMPO55, P.CAMPO56, P.CAMPO57, P.CAMPO58, P.CAMPO59, 
  P.CAMPO60, P.CAMPO61, P.CAMPO62, P.CAMPO63, P.CAMPO64, 
  CatP1.OPCION , CatP2.OPCION ,CatP3.OPCION ,
    CatE1.OPCION ,CatE2.OPCION ,CatE3.OPCION ,   
  CatI.INDUSTRIA , CatG.COMPANIAGRUPO, P.TKPM, P.CANALIZADOEL, P.USRCANALIZO, P.USRCANALIZADO , P.SEXO, P.APROBACIONESTADO, COM.IDUSUARIO, U.Tku, Com.IdCompania '+CAST(@OrderSql AS VARCHAR(MAX))+'


SELECT * FROM  #tblMior  SQL1
outer APPLY
(SELECT 
SUM(MONTO) AS MontoComprado,
SUM(ANTICIPOS_MONTO) AS Anticipos,
SUM(SALDO_MONTO) AS   Saldo,
SUM(MONTO_VENCIDO) AS SaldoVencido,
CASE WHEN SQL1.Transacciones = 0 THEN SUM(MONTO) ELSE SUM(MONTO)/SQL1.Transacciones END as MontoPromedio
FROM
(SELECT
  V.IDVENTA, P.IDPROSPECTO, 
  ISNULL(V.MONTO,0)*ISNULL(V.TIPODECAMBIO,1) AS MONTO,
  ISNULL(VC.MONTO,0)*ISNULL(V.TIPODECAMBIO,1) AS MONTO_VENCIDO,
  ISNULL(V.ANTICIPOS_MONTO,0)*ISNULL(V.TIPODECAMBIO,1) AS ANTICIPOS_MONTO,
  ISNULL(V.SALDO_MONTO,0)*ISNULL(V.TIPODECAMBIO,1) AS SALDO_MONTO
  from <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO WITH(NOLOCK)
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) ON P.IDORIGEN = PO.IDORIGEN 
  JOIN  <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A2 WITH(NOLOCK) ON A2.IDPROSPECTO = P.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O WITH(NOLOCK) ON P.IDPROSPECTO = O.IDPROSPECTO 
  LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V WITH(NOLOCK) ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD
  Cross APPLY(
  SELECT SUM(VC.MONTO) AS MONTO FROM <#SESSION.DB/>.DBO.VENTAS_COBROS VC WHERE VC.IDVENTA=V.IDVENTA AND VC.FECHAHORA<GETDATE() AND VC.PAGADO=0 
  ) VC
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
  JOIN  <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON P.IDUSUARIO = U.IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO PS WITH(NOLOCK) ON PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO
  JOIN <#SESSION.DB/>.DBO.USUARIOS U1 WITH(NOLOCK) ON U1.IDUSUARIO = PS.IDUSUARIO
  JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A WITH(NOLOCK) ON P.IDPROSPECTO = A.IDPROSPECTO
  WHERE
  P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND P.ESCLIENTE =1  AND P.APROBACIONESTADO '+CAST(@APROBADO AS VARCHAR(MAX))+'
    '+CAST(@CRIT AS VARCHAR(MAX))+' '+CAST(@F_USUARIO AS VARCHAR(MAX))+' '+CAST(@CRITARCHIVAR AS VARCHAR(MAX))+' '+CAST(@POREMPRESA AS VARCHAR(MAX))+' '+CAST(@PORCATALOGO AS VARCHAR(MAX))+' '+CAST(@PORTKCOM AS VARCHAR(MAX))+' AND P.IDPROSPECTO = SQL1.IDPROSPECTO
GROUP BY  V.IDVENTA,V.MONTO,V.TIPODECAMBIO,VC.MONTO,V.ANTICIPOS_MONTO,V.SALDO_MONTO,P.IDPROSPECTO) MNS)AN
'+CAST(@NWO AS VARCHAR(MAX))+'
'
--SELECT @ORTEMP;
EXEC (@SQL)