//[session.db|Untyped,tkrsv|Text,]
--select

DECLARE @TKURV VARCHAR(MAX)
DECLARE @IDREPORTEVARIANTE INT

SET @TKURV = ISNULL(:TKRSV, '')

SELECT @IDREPORTEVARIANTE = IDREPORTEVARIANTE 
FROM <#SESSION.DB/>.DBO.USUARIOS_REPORTES_VARIANTES 
WHERE TKURV = @TKURV

SELECT idFiltro, valor, operador_Logico as operador,filtro
FROM <#SESSION.DB>.DBO.usuarios_reportes_filtros_adicionales 
WHERE IDREPORTEVARIANTE = @IDREPORTEVARIANTE
