//[idpantalla|Integer,session.db|Untyped,session.idusuario|Untyped,]
--SELECT
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDPANTALLA INT
SET @IDPANTALLA = ISNULL(:IDPANTALLA,0)
SELECT * FROM <#SESSION.DB/>.dbo.USUARIOS_FILTROS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/> AND TIPO=401 AND IDPANTALLA=@IDPANTALLA