//[tkcom|Text,porempresa|Text,session.db|Untyped,]
--select
DECLARE @IDCOMPANIA INT
DECLARE @TkCom VARCHAR(64)
DECLARE @POREMPRESA VARCHAR(MAX)
DECLARE @ULTIMOCOMENTARIO VARCHAR(MAX)
SET @TkCom = dbo.ValidaToken( :TKCOM)
SET @IDCOMPANIA = 0
SET @POREMPRESA= :PorEmpresa

IF @TkCom != ''
BEGIN
	 SELECT @IDCOMPANIA = IDCOMPANIA FROM <#SESSION.DB/>.dbo.COMPANIAS WHERE TKCOM = @TkCom
END


SELECT (CASE WHEN ISNULL(@IDCOMPANIA,0) > 0 
  	   THEN 
	   		( 
			  SELECT TOP 1 PP.NOMBRE +' '+ISNULL(PP.APELLIDOS,'') + ', <b>'+<#SESSION.DB/>.DBO.TIEMPO_TXT (PSS.FECHAHORA,GETDATE()) + '</b> ('+UU.INICIALES+') - <i>'+ CAST(PSS.COMENTARIO AS VARCHAR(MAX)) + '</i>'
			  FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSS , <#SESSION.DB/>.dbo.USUARIOS UU , <#SESSION.DB/>.dbo.PROSPECTOS PP 
			  WHERE PSS.IDUSUARIO = UU.IDUSUARIO AND PP.IDCOMPANIA=@IDCOMPANIA AND PSS.IDPROSPECTO=PP.IDPROSPECTO AND PP.ESCLIENTE=1 AND ISNULL(PSS.IDOPORTUNIDAD,0)=0 
			  ORDER BY PSS.IDSEGUIMIENTO DESC
			) 
	   ELSE
	   	   ''
	   END ) AS ULTIMOCOMENTARIO

