//[buscar|Text,session.db|Untyped,session.idusuario|Untyped,directorio|Text,mostrar|Text,orden1|Text,orden2|Text,session.idempresa|Untyped,]
--SELECT
declare @SQL VARCHAR(MAX)
DECLARE @IDGRUPO INT
DECLARE @NIVEL INT
DECLARE @BUSCAR VARCHAR(MAX)
DECLARE @DIRECTORIO VARCHAR(MAX)
DECLARE @MOSTRAR VARCHAR(MAX)
DECLARE @MOST VARCHAR(MAX)
DECLARE @ORDEN1 VARCHAR(MAX)
DECLARE @ORDEN2 VARCHAR(MAX)
SET @BUSCAR = ISNULL(:BUSCAR,'')
SELECT @IDGRUPO=IDGRUPO, @NIVEL=NIVEL FROM <#SESSION.DB/>.DBO.USUARIOS WHERE IDUSUARIO=<#SESSION.IDUSUARIO/>
SET @DIRECTORIO= ISNULL(:DIRECTORIO,'')
SET @MOST = :MOSTRAR
SET @MOSTRAR =(CASE WHEN @MOST IS NOT NULL THEN '  AND '+ISNULL(@MOST,'') ELSE '' END)
SET @ORDEN1= ISNULL(:ORDEN1,'')
SET @ORDEN2= ISNULL(:ORDEN2,'')

SET @SQL='
DECLARE @BUSCAR VARCHAR(MAX)
DECLARE @NIVEL INT
DECLARE @DIRECTORIO VARCHAR(MAX)
SET @BUSCAR='''+@BUSCAR+'''
SET @DIRECTORIO= '''+@DIRECTORIO+'''
SET @NIVEL='+CAST(@NIVEL AS VARCHAR(1000))+'
IF (@NIVEL=1)
BEGIN
SELECT 
  count(*) AS TOTAL, @DIRECTORIO AS DIRECTORIO, @BUSCAR AS BUSCAR,'''+@MOSTRAR+''' AS MOSTRAR,'''+@ORDEN1+''' AS ORDEN1,'''+@ORDEN2+''' AS ORDEN2
  FROM <#SESSION.DB/>.dbo.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS
  LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/> --AND ESCLIENTE=1  
  AND P.NOMBRE LIKE @DIRECTORIO+''%''
  and (P.NOMBRE LIKE ''%''+@BUSCAR+''%'' OR P.APELLIDOS LIKE ''%''+@BUSCAR+''%'' OR P.CORREO LIKE ''%''+@BUSCAR+''%'' )
  '+@MOSTRAR+'
END

IF @NIVEL=2
BEGIN
SELECT 
  count(*) AS TOTAL, @DIRECTORIO AS DIRECTORIO, @BUSCAR AS BUSCAR,'''+@MOSTRAR+''' AS MOSTRAR,'''+@ORDEN1+''' AS ORDEN1,'''+@ORDEN2+''' AS ORDEN2
  FROM <#SESSION.DB/>.dbo.USUARIOS U,<#SESSION.DB/>.dbo.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS
  LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/>  
  AND U.IDUSUARIO=P.IDUSUARIO AND U.IDGRUPO='+CAST(@IDGRUPO AS VARCHAR(1000))+'
  AND P.NOMBRE LIKE @DIRECTORIO+''%''
  and (P.NOMBRE LIKE ''%''+@BUSCAR+''%'' OR P.APELLIDOS LIKE ''%''+@BUSCAR+''%'' OR P.CORREO LIKE ''%''+@BUSCAR+''%'' )
  '+@MOSTRAR+'

END
 
IF @NIVEL=3
BEGIN
SELECT 
  count(*) AS TOTAL, @DIRECTORIO AS DIRECTORIO, @BUSCAR AS BUSCAR,'''+@MOSTRAR+''' AS MOSTRAR,'''+@ORDEN1+''' AS ORDEN1,'''+@ORDEN2+''' AS ORDEN2
  FROM <#SESSION.DB/>.dbo.USUARIOS U,<#SESSION.DB/>.dbo.PROSPECTOS P
  LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS
  LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO
  WHERE P.IDEMPRESA=<#SESSION.IDEMPRESA/>
  AND U.IDUSUARIO=P.IDUSUARIO AND p.IDUSUARIO=<#SESSION.IDUSUARIO/>
  AND P.NOMBRE LIKE @DIRECTORIO+''%''
  and (P.NOMBRE LIKE ''%''+@BUSCAR+''%'' OR P.APELLIDOS LIKE ''%''+@BUSCAR+''%'' OR P.CORREO LIKE ''%''+@BUSCAR+''%'' )
  '+@MOSTRAR+'

END  
'
EXEC (@SQL)
