//[session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,descartado|Text,top_registros|Text,session.db|Untyped,criterio|Text,crit|Text,f_usuario|Text,critarchivar|Text,]
--select
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX)
DECLARE @CRITARCHIVAR VARCHAR(MAX)
DECLARE @CRITERIO VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX) 
DECLARE @TOP VARCHAR(MAX)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @NIVELUSUARIO = CAST('<#SESSION.NIVEL/>' AS INT)
SET @IDGRUPO = CAST('<#SESSION.IDGRUPO/>' AS INT)
SET @MAILCONFIG = CAST('<#SESSION.MAILCONFIG/>' AS INT )
SET @DESCARTADO = CAST(ISNULL(:DESCARTADO,'') AS INT)
SET @F_USUARIO=ISNULL(:F_USUARIO,'')
SET @CRITARCHIVAR=ISNULL(:CRITARCHIVAR,'')
SELECT @CRIT=ISNULL(:CRIT,'')
SET @CRITERIO=ISNULL(:CRITERIO,'')
SET @TOP= ISNULL(:TOP_REGISTROS,'')
--SELECT @CRIT
 
 
SET @SQL=' 
SELECT '+@TOP+'
CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 THEN 1 ELSE 0 END AS A , 
  ISNULL(COM.IDCOMPANIA,-1) AS Id, COM.TkCom, ISNULL(COM.Empresa,''Sin empresa'') as Empresa,
  CASE WHEN (ISNULL(EI.Industria,'''')='''') OR (EI.Industria = ''Ninguna'') THEN '''' ELSE EI.Industria END AS Industria ,
  CASE WHEN (ISNULL(CG.CompaniaGrupo,'''')='''') OR (CG.CompaniaGrupo = ''Ninguna'') THEN '''' ELSE CG.CompaniaGrupo END AS CompaniaGrupo,
  COM.Url, COM.TELEFONOCORPORATIVO AS Telefono, 
  /* COM.DIRECCION1 as Calle, COM.DIRECCION2 as Colonia, COM.Ciudad, COM.CODIGOPOSTAL as Cp,  CASE WHEN ISNULL(COM.NEMPLEADOS,0) = 0 THEN '' ELSE CAST(COM.NEMPLEADOS AS VARCHAR(MAX)) END as Empleados, */
  COUNT( DISTINCT isnull(P.IDPROSPECTO,0))  AS nRegistros,
  
  CASE WHEN ISNULL(COM.IDCOMPANIA,0) > 0 
  	   THEN 
	   		( 
			  SELECT PP.NOMBRE +'' ''+ISNULL(PP.APELLIDOS,'''') + '', <b>'' + <#SESSION.DB/>.DBO.TIEMPO_TXT(PSS.FECHAHORA,GETDATE()) + ''</b> (''+UU.INICIALES+'') - <i>''+ CAST(PSS.COMENTARIO AS VARCHAR(MAX)) + ''</i>''
			  FROM <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO PSS , <#SESSION.DB/>.dbo.USUARIOS UU , <#SESSION.DB/>.dbo.PROSPECTOS PP 
			  WHERE --PSS.IDUSUARIO = UU.IDUSUARIO AND PSS.IDSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO) AND PP.IDULTIMOSEGUIMIENTO = MAX(P.IDULTIMOSEGUIMIENTO)
			  PSS.IDUSUARIO = UU.IDUSUARIO AND PSS.IDSEGUIMIENTO = MAX(PS.IDSEGUIMIENTO) AND  PSS.IDPROSPECTO=PP.IDPROSPECTO 
			) 
	   ELSE
	   	   ''''
	   END AS Comentario
  FROM 
  
    <#SESSION.DB/>.DBO.PROSPECTOS_ORIGENES PO 
	JOIN <#SESSION.DB/>.DBO.PROSPECTOS P ON P.IDORIGEN = PO.IDORIGEN 
	JOIN  <#SESSION.DB/>.DBO.PROSPECTOS_FASES F WITH(NOLOCK) ON P.IDFASE = F.IDFASE 
	LEFT JOIN <#SESSION.DB/>.DBO.OPORTUNIDADES O ON P.IDPROSPECTO = O.IDPROSPECTO 
    LEFT JOIN <#SESSION.DB/>.DBO.VENTAS V ON O.IDOPORTUNIDAD = V.IDOPORTUNIDAD 
    JOIN <#SESSION.DB/>.DBO.USUARIOS U ON P.IDUSUARIO = U.IDUSUARIO
	JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO PS WITH(NOLOCK) ON PS.IDSEGUIMIENTO = P.IDULTIMOSEGUIMIENTO
	JOIN <#SESSION.DB/>.DBO.USUARIOS U1 ON U1.IDUSUARIO = PS.IDUSUARIO
	LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA
    LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_INDUSTRIAS EI WITH(NOLOCK) ON EI.IDINDUSTRIA = COM.IDINDUSTRIA
    LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS_GRUPOS CG WITH(NOLOCK) ON CG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO,
    <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A 
  WHERE  
    P.IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(1000))+' AND P.ESCLIENTE =1 AND 
    P.IDPROSPECTO = A.IDPROSPECTO '+@CRITERIO+' '+@CRIT+' '+@CRITARCHIVAR+' '+@F_USUARIO+'
  GROUP BY 
  COM.IDCOMPANIA, COM.TkCom, CG.COMPANIAGRUPO, COM.EMPRESA, COM.URL, COM.TELEFONOCORPORATIVO, COM.IDCOMPANIAGRUPO, EI.INDUSTRIA
  ORDER BY 1 DESC, COM.Empresa

  '
  EXEC (@SQL)
  