//[session.gmt|Untyped|1,session.db|Untyped|salesup_db1,session.idempresa|Untyped|11811,tipo|Text|0,idprospecto|Integer|296186]
--select
/*PROTEGIDO*/
DECLARE @hay int, @GMT INT, @TIPO INT, @IDPROSPECTO INT
DECLARE @IDEMPRESA INT 
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TIPO = ISNULL(:TIPO,0)
SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)

SET @GMT = CAST('<#SESSION.GMT/>' AS INT )

/*S

SELECT @GMT = DIFERENCIA FROM  <#SESSION.DB/>.dbo.V_GMT WHERE GMT= @GMT*/

SELECT @hay=COUNT (*)from <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS WHERE IDEMPRESA = @IDEMPRESA

IF @TIPO = 0    
BEGIN      
SELECT
SALESUP_CT.dbo.esCanalizado(S.TK, S.TKM) AS esCanalizado, 
(CASE WHEN UE.ESTADO=0 AND UE.ERRORES>=3 THEN 1 ELSE 0 END) AS ESTADOEMAIL,
(CASE WHEN UE.FECHALEIDO IS NOT NULL THEN 1 ELSE 0 END ) AS EMAILEIDO, UE.FECHALEIDO,
 (CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,

(CASE WHEN USMS.ESTADO=0 AND USMS.ERRORES>0 THEN 1 ELSE 0 END) AS ESTADOSMS,
 (CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,
 
 
SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,S.FECHAHORA) AS FECHAHORA, 
SC.CATEGORIA,@hay as totalrecla  ,
CASE WHEN S.SEGUIMIENTODE IS NULL THEN ISNULL(U.INICIALES, '--') ELSE S.SEGUIMIENTODE END AS INICIALES, 
CASE WHEN S.SEGUIMIENTODE IS NULL THEN U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') ELSE '' END AS EJECUTIVO_NOMBRE, 
CASE S.TIPO_SEGUIMIENTO 
WHEN 7 THEN T.TKTR 
ELSE ''
END AS TK, S.*,P.TKP
FROM <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK)
INNER JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S  WITH(NOLOCK) ON  S.IDPROSPECTO = P.IDPROSPECTO
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON  UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON  USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK )ON  S.IDUSUARIO = U.IDUSUARIO   
LEFT JOIN <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS SC WITH(NOLOCK) ON SC.IDSEGUIMIENTOCATEGORIA = S.IDSEGUIMIENTOCATEGORIA
LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7
WHERE S.IDPROSPECTO = @IDPROSPECTO AND P.IDEMPRESA= @IDEMPRESA AND  S.IDOPORTUNIDAD IS NULL AND P.ESCLIENTE = 1    
ORDER BY S.FECHAHORA DESC    
END  
ELSE    
 BEGIN
      SELECT 
	  SALESUP_CT.dbo.esCanalizado(S.TK, S.TKM) AS esCanalizado,
	  (CASE WHEN UE.ESTADO=0 AND UE.ERRORES>=3 THEN 1 ELSE 0 END) AS ESTADOEMAIL,
      (CASE WHEN UE.FECHALEIDO IS NOT NULL THEN 1 ELSE 0 END ) AS EMAILEIDO, UE.FECHALEIDO,
      (CASE WHEN UE.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+UE.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORMSG,

      (CASE WHEN USMS.ESTADO=0 AND USMS.ERRORES>0 THEN 1 ELSE 0 END) AS ESTADOSMS,
      (CASE WHEN USMS.ULTIMOERRORMSG IS NOT NULL THEN 'Error: '+USMS.ULTIMOERRORMSG ELSE '' END) AS ULTIMOERRORSMS,

SALESUP_CT.dbo.[obtieneFechaRealGMT]( @GMT,S.FECHAHORA) AS FECHAHORA, 
	  SC.CATEGORIA ,@hay as totalrecla,
	  CASE WHEN S.SEGUIMIENTODE IS NULL THEN ISNULL(U.INICIALES, '--') ELSE S.SEGUIMIENTODE END AS INICIALES, 
	  CASE WHEN S.SEGUIMIENTODE IS NULL THEN U.NOMBRE + ' ' + ISNULL(U.APELLIDOS, '') ELSE '' END AS EJECUTIVO_NOMBRE, 
	  CASE S.TIPO_SEGUIMIENTO WHEN 7 THEN T.TKTR ELSE '' END AS TK,S.*
 FROM 
  <#SESSION.DB/>.DBO.PROSPECTOS P WITH(NOLOCK) 
  INNER JOIN <#SESSION.DB/>.DBO.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON  S.IDPROSPECTO = P.IDPROSPECTO
   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_EMAILS UE  WITH(NOLOCK)  ON  UE.IDEMAIL = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (1,2)
   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS_SMS USMS  WITH(NOLOCK)  ON  USMS.IDSMS = S.IDEMAIL AND S.TIPO_SEGUIMIENTO IN (3,4,5)
   LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U WITH(NOLOCK) ON  S.IDUSUARIO = U.IDUSUARIO  
   LEFT JOIN <#SESSION.DB/>.DBO.SEGUIMIENTO_CATEGORIAS SC WITH(NOLOCK) ON SC.IDSEGUIMIENTOCATEGORIA = S.IDSEGUIMIENTOCATEGORIA 
   LEFT JOIN <#SESSION.DB/>.DBO.TAREAS T WITH(NOLOCK) ON T.IDTAREA = S.IDRELACIONADO AND S.TIPO_SEGUIMIENTO = 7   
 WHERE S.IDPROSPECTO = @IDPROSPECTO AND P.IDEMPRESA= @IDEMPRESA AND  
S.IDOPORTUNIDAD IS NULL  AND P.ESCLIENTE = 1 AND S.IDSEGUIMIENTOCATEGORIA = @TIPO     
 ORDER BY s.FECHAHORA DESC    END