//[session.idusuario|Untyped,top_registros|Text,tkca|Text,descartado|Integer,f_usuario|Text,critarchivar|Text,session.db|Untyped,]
--SELECT
DECLARE @IDUSUARIO INT
DECLARE @TKCA VARCHAR(64) 
DECLARE @TOPR VARCHAR(1000)
DECLARE @DESCARTADO INT
DECLARE @F_USUARIO VARCHAR(MAX)
DECLARE @CRITERIO VARCHAR(MAX)
SET @IDUSUARIO= CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @TOPR=ISNULL(:TOP_REGISTROS,'')
SET @TKCA= dbo.ValidaToken(:TKCA)
SET @DESCARTADO=CAST(ISNULL(:DESCARTADO,0) AS INT)
SET @F_USUARIO=CAST(ISNULL(:F_USUARIO,'') AS VARCHAR(Max))
SET @CRITERIO=CAST(ISNULL(:CRITARCHIVAR,'') AS varchar(max))

EXEC <#SESSION.DB/>.dbo.SP_CLIENTES_POR_CATALOGO_TOTAL @IDUSUARIO,@TKCA,@TOPR,@DESCARTADO,@F_USUARIO,@CRITERIO
