//[session.idempresa|Untyped,status|Integer,session.db|Untyped,tk|Text,]
--SELECT
/*PROTEGIDO*/
DECLARE @TK VARCHAR(256) 
DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
SET @TK=ISNULL(:TK, 0)
SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @STATUS=ISNULL(:STATUS, 0)




  UPDATE <#SESSION.DB/>.DBO.MARCAS
  SET STATUS=@STATUS
  WHERE  IDEMPRESA=@IDEMPRESA AND TK=@TK
  SELECT STATUS FROM <#SESSION.DB/>.DBO.MARCAS
  WHERE  IDEMPRESA=@IDEMPRESA AND TK=@TK

