//[session.idempresa|Untyped,tk|Text,session.db|Untyped,status|Integer,]
--SELECT
/*PROTEGIDO*/
DECLARE @IDCOMISION INT 
DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
DECLARE @TK VARCHAR(256) 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TK=ISNULL(:TK , '') 
SET @IDCOMISION = 0 
IF(@TK!='') BEGIN SELECT @IDCOMISION = IDPRODUCTO_COMISION FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES WHERE  IDEMPRESA=@IDEMPRESA AND TKCOMISION = @TK END

SET @STATUS=ISNULL(:STATUS, -1)

IF(@STATUS=-1)
   SELECT STATUS FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
   WHERE IDPRODUCTO_COMISION=@IDCOMISION AND IDEMPRESA=@IDEMPRESA
ELSE 
 BEGIN 
  UPDATE <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
  SET STATUS=@STATUS
  WHERE IDPRODUCTO_COMISION=@IDCOMISION AND IDEMPRESA=@IDEMPRESA
  SELECT STATUS FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
  WHERE IDPRODUCTO_COMISION=@IDCOMISION AND IDEMPRESA=@IDEMPRESA
 END 
