//[session.idempresa|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @IDEMPRESA INT 

SET @IDEMPRESA=<#SESSION.IDEMPRESA/>

SELECT IDPRODUCTO_COMISION,  STATUS, DESCRIPCION, INDICE, MONTO
 FROM <#SESSION.DB/>.DBO.PRODUCTOS_COMISIONES
 WHERE IDEMPRESA=@IDEMPRESA
 
 