//[session.idempresa|Untyped,bandera|Integer,idmarca|Integer,session.db|Untyped,]
--SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT 
DECLARE @BANDERA INT 
DECLARE @IDMARCA INT

SET @IDEMPRESA=CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @BANDERA=ISNULL(:BANDERA, 0) 
SET @IDMARCA=ISNULL (:IDMARCA, 0)
 
SELECT RTRIM(LTRIM(MARCA)) AS MARCA, TK, TKM, STATUS
FROM <#SESSION.DB/>.DBO.MARCAS 
WHERE IDEMPRESA=@IDEMPRESA 
ORDER BY MARCA ASC
