//[session.db|Untyped,c|Text,v|Text,session.idempresa|Untyped,]
--UPDATE
DECLARE @SQL VARCHAR(MAX)
DECLARE @C VARCHAR(MAX)
DECLARE @V VARCHAR(MAX)
SET @C=ISNULL(:C,'')
SET @V=ISNULL(:V,'')
SET @SQL=''

SET @SQL='UPDATE <#SESSION.DB/>.DBO.EMPRESAS_BUSQUEDA_CONFIG SET '+@C+' = '+@V+' WHERE IDEMPRESA = <#SESSION.IDEMPRESA/>'
EXEC (@SQL)
