//[session.idempresa|Untyped,tk|Text,session.db|Untyped,]
--SELECT 


DECLARE @IDEMPRESA INT 
DECLARE @TKELIMINAR VARCHAR(256)  


SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @TKELIMINAR=ISNULL(:TK , '') 


SELECT TK, RTRIM(LTRIM(MARCA)) AS MARCA
FROM <#SESSION.DB/>.DBO.MARCAS WHERE CAST(TK AS VARCHAR(256))  NOT IN (@TKELIMINAR) 
AND IDEMPRESA=@IDEMPRESA
ORDER BY MARCA ASC