//[sp_requestedfile|Untyped,]
--SELECT
DECLARE @ARCHIVO VARCHAR(1024)
SET @ARCHIVO = LOWER('<#SP_REQUESTEDFILE/>')
SELECT @ARCHIVO =  SUBSTRING(@ARCHIVO,10, LEN(@ARCHIVO))


SELECT TOP 1 CAST(A.TEXTO AS VARCHAR(MAX)) AS TEXTO , A.SNIPPET , PA.PANTALLA
FROM CONTROL.DISTRIBUIDORES.dbo.AYUDA A
JOIN CONTROL.DISTRIBUIDORES.dbo.PANTALLAS PA ON PA.ARCHIVO = @ARCHIVO AND A.IDPANTALLA = PA.IDPANTALLA