//[session.idempresa|Untyped,session.idusuario|Untyped,idprospecto|Integer,tkp|Text,session.db|Untyped,]
--insert
DECLARE @IDPROSPECTO INT, @IDEMPRESA INT, @IDUSUARIO INT
DECLARE @TKP VARCHAR(64)
SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO = CAST('<#SESSION.IDUSUARIO/>' AS INT)

SET @IDPROSPECTO = ISNULL(:IDPROSPECTO,0)
SET @TKP = ISNULL(:TKP,'')
IF @TKP != '' BEGIN SET @IDPROSPECTO = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END

EXEC <#SESSION.DB/>.dbo.SP_RESTABLECER @IDPROSPECTO, @IDUSUARIO

UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE() WHERE IDPROSPECTO = @IDPROSPECTO

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA,4,GETDATE()) 