//[idayuda|Integer,session.idproducto|Untyped,]
SELECT A.*, C.CATEGORIA , (SELECT MAX(ORDENAYUDA) FROM CONTROL.DISTRIBUIDORES.dbo.AYUDA WHERE IDPRODUCTO = <#SESSION.IDPRODUCTO/>) AS ULTIMO 
FROM CONTROL.DISTRIBUIDORES.dbo.AYUDA A
LEFT JOIN AYUDA_CATEGORIAS C ON A.IDAYUDACAT = C.IDAYUDACAT
WHERE A.IDAYUDA = :IDAYUDA