//[session.idempresa|Untyped,status|Integer,session.db|Untyped,tk|Text,]
--SELECT
/*PROTEGIDO*/

DECLARE @IDEMPRESA INT 
DECLARE @STATUS INT
DECLARE @TK VARCHAR(256) 


SET @IDEMPRESA=<#SESSION.IDEMPRESA/>
SET @STATUS=ISNULL(:STATUS, -1)
SET @TK=ISNULL(:TK, '')  

UPDATE <#SESSION.DB/>.DBO.lISTAS_PRECIO
SET STATUS=@STATUS
WHERE TK=@TK  AND IDEMPRESA=@IDEMPRESA
SELECT STATUS FROM <#SESSION.DB/>.DBO.lISTAS_PRECIO
WHERE TK=@TK AND IDEMPRESA=@IDEMPRESA
