//[ordersql|Text,ids|Text,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.db|Untyped,]
--SELECT 
DECLARE @SQL VARCHAR(MAX)
DECLARE @OrderSql VARCHAR(MAX)

SET @OrderSql=ISNULL(:OrderSql,'')

SET @SQL='
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT, @Descartado INT,@IDCOMPANIA INT
DECLARE @IDS VARCHAR(MAX)

SET @IDS = '''+ISNULL(:IDS,'')+'''
SET @IDEMPRESA = CAST(''<#SESSION.IDEMPRESA/>'' AS INT)
SET @IDUSUARIO = CAST(''<#SESSION.IDUSUARIO/>'' AS INT)
SET @NIVELUSUARIO = CAST(''<#SESSION.NIVEL/>'' AS INT)
SET @IDGRUPO = CAST(''<#SESSION.IDGRUPO/>'' AS INT) 

SELECT 
  O.TKO AS Tko, P.IdCompania, COM.TkCom,O.idusuario as IdUsuario,
  SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) AS esCanalizado, P.CANALIZADOEL AS FechaCanalizado, SALESUP_CT.dbo.ObtieneHora(P.CANALIZADOEL) AS HoraCanalizado, P.USRCANALIZO as Canalizo, P.USRCANALIZADO AS Canalizado,
  SALESUP_CT.dbo.VerLtArchivos(P.IDPROSPECTO, P.NARCHIVOS, O.IDOPORTUNIDAD, O.NARCHIVOS )  AS VerArchivos,
  CASE @DESCARTADO WHEN 0 THEN ''1'' ELSE '''' END AS Descartado,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO OR PA2.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tEtiquetar_tSeguimiento,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR @NIVELUSUARIO <= 2 THEN ''1'' ELSE '''' END AS tCompartir_tReasignar,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO OR PA2.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tOportunidad,
  CASE WHEN P.IDUSUARIO = @IDUSUARIO OR O.IDUSUARIO = @IDUSUARIO THEN ''1'' ELSE '''' END AS tDescartar_tVentas,
  P.IdProspecto, O.IdOportunidad,
  LTRIM(RTRIM(P.NOMBRE))+'' ''+ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'''') AS NombreCliente, P.Puesto, ISNULL(P.Empresa,'''') AS Empresa , P.ETIQUETAS_TXT AS Etiquetas,
  CASE P.Sexo WHEN ''H'' THEN ''Hombre'' WHEN ''M'' THEN ''Mujer'' ELSE '''' END AS Sexo,
  CASE WHEN <#SESSION.DB/>.DBO.ValidaEmail(P.CORREO) = ''NO'' THEN ''1'' ELSE '''' END as EsCorreo, ISNULL(P.Correo,'''') As Correo , ISNULL(P.Telefono,'''') as Telefono , ISNULL(P.Telefono2,'''') AS Telefono2 , ISNULL(P.Movil,'''') as Movil,  
   O.Concepto as Concepto, LP.LINEA_PRODUCTO as LineaProducto,
  ISNULL(F.Fase,'''') AS Fase, ISNULL(ORI.Origen,'''') AS Origen,
  ISNULL(Monto,'''') AS Monto, ISNULL(COMISION_MONTO,0) as Comision, O.Certeza, EC.DESCRIPCION AS TxtCerteza, 
  CASE WHEN O.FECHA_CIERRE < <#SESSION.DB/>.DBO.GETONLYDATE(GETDATE()) THEN ''1'' ELSE '''' END AS Vencida, CONVERT(VARCHAR(10),O.FECHA_CIERRE,103) as CierreEstimado,
   isnull(CAST(S.COMENTARIO AS VARCHAR(MAX)),'''')  AS UltimoContacto,
  (<#SESSION.DB/>.DBO.TIEMPO_TXT (S.FECHAHORA,GETDATE())) AS UltimoContactoTiempo,
  U.Iniciales , U.NOMBRE+'' ''+U.APELLIDOS AS EjecutivoNombre,
  
  CASE WHEN COUNT(A3.IDPROSPECTO) >0 THEN ''1'' ELSE '''' END AS Compartido,
  CASE @MAILCONFIG WHEN 0 THEN ''1'' ELSE '''' END AS NoConfigurado,
  CASE @MAILCONFIG WHEN 1 THEN ''1'' ELSE '''' END AS EmailConfigurado,
  CASE @MAILCONFIG WHEN 2 THEN ''1'' ELSE '''' END AS MailTo, S.FECHAHORA AS ULTIMO_CONTACTO_FECHA, CONVERT(VARCHAR(10),O.FECHAHORA,103) AS FechaCreacion,
  
	 
  CASE WHEN P.CAMPO1 IS NOT NULL THEN P.CAMPO1 ELSE '''' END AS cp1,
  CASE WHEN P.CAMPO2 IS NOT NULL THEN P.CAMPO2 ELSE '''' END AS cp2,
  CASE WHEN P.CAMPO3 IS NOT NULL THEN P.CAMPO3 ELSE '''' END AS cp3,
  CASE WHEN P.CAMPO4 IS NOT NULL THEN P.CAMPO4 ELSE '''' END AS cp4,
  
  CASE WHEN P.CAMPO5 IS NOT NULL THEN P.CAMPO5 ELSE '''' END AS cp5,
  CASE WHEN P.CAMPO6 IS NOT NULL THEN P.CAMPO6 ELSE '''' END AS cp6,
  CASE WHEN P.CAMPO7 IS NOT NULL THEN P.CAMPO7 ELSE '''' END AS cp7,
  CASE WHEN P.CAMPO8 IS NOT NULL THEN P.CAMPO8 ELSE '''' END AS cp8,
  
  CASE WHEN P.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO9,103) ELSE '''' END AS cp9,
  CASE WHEN P.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO10,103) ELSE '''' END AS cp10,
  CASE WHEN P.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO11,103) ELSE '''' END AS cp11,
  CASE WHEN P.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),P.CAMPO12,103) ELSE '''' END AS cp12,
  
  ISNULL(P.CAMPO13,'''') AS cp13,
  ISNULL(P.CAMPO14,'''') AS cp14,
  ISNULL(P.CAMPO15,'''') AS cp15,
  ISNULL(P.CAMPO16,'''') AS cp16,
  ISNULL(P.CAMPO17,'''') AS cp17,
  ISNULL(P.CAMPO18,'''') AS cp18,
  ISNULL(P.CAMPO19,'''') AS cp19,
  ISNULL(P.CAMPO20,'''') AS cp20,

  CP21.OPCION AS cp21,
  CP22.OPCION AS cp22,
  CP23.OPCION AS cp23,
  CP24.OPCION AS cp24,
  CP25.OPCION AS cp25,
  
  P.CAMPO26 AS cp26, P.CAMPO27 AS cp27, P.CAMPO28 AS cp28P,
  P.CAMPO29 AS cp29, P.CAMPO30 AS cp30, P.CAMPO31 AS cp31P, P.CAMPO32 AS cp32P,
  P.CAMPO33 AS cp33, P.CAMPO34 AS cp34,
  
  O.CAMPO1 AS cp1O, O.CAMPO2 AS cp2O, O.CAMPO3 AS cp3O, O.CAMPO4 AS cp4O,
  O.CAMPO5 AS cp5O, O.CAMPO6 AS cp6O, O.CAMPO7 AS cp7O, O.CAMPO8 AS cp8O,
  CASE WHEN O.CAMPO9 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO9,103) ELSE '''' END AS cp9O,
  CASE WHEN O.CAMPO10 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO10,103) ELSE '''' END AS cp10O,
  CASE WHEN O.CAMPO11 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO11,103) ELSE '''' END AS cp11O,
  CASE WHEN O.CAMPO12 IS NOT NULL THEN CONVERT(VARCHAR(10),O.CAMPO12,103) ELSE '''' END AS cp12O,
  O.CAMPO13 AS cp13O, O.CAMPO14 AS cp14O, O.CAMPO15 AS cp15O, O.CAMPO16 AS cp16O,
  O.CAMPO17 AS cp17O, O.CAMPO18 AS cp18O, O.CAMPO19 AS cp19O, O.CAMPO20 AS cp20O,
  CPO21.OPCION AS cp21O, CPO22.OPCION AS cp22O, CPO23.OPCION AS cp23O, CPO24.OPCION AS cp24O, CPO25.OPCION AS cp25O,
  O.CAMPO26 AS cp26O, O.CAMPO27 AS cp27O, O.CAMPO28 AS cp28O,
  O.CAMPO29 AS cp29O, O.CAMPO30 AS cp30O, O.CAMPO31 AS cp31O, O.CAMPO32 AS cp32O,
  O.CAMPO33 AS cp33O, O.CAMPO34 AS cp34O
  ,CatP1.OPCION AS pCat1, CatP2.OPCION AS pCat2,CatP3.OPCION AS pCat3,
  CatO1.OPCION AS oCat1, CatO2.OPCION AS oCat2,CatO3.OPCION AS oCat3,
  CatE1.OPCION AS eCat1,CatE2.OPCION AS eCat2,CatE3.OPCION AS eCat3  , 
  CatI.INDUSTRIA AS CatIndustria, CatG.COMPANIAGRUPO AS CatCorporativo 

FROM <#SESSION.DB/>.dbo.OPORTUNIDADES O WITH(NOLOCK) 
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) ON O.IDPROSPECTO = P.IDPROSPECTO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS PA WITH(NOLOCK) ON @IDUSUARIO = PA.IDUSUARIO AND PA.IDPROSPECTO = O.IDPROSPECTO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA2 WITH(NOLOCK) ON PA2.IDPROSPECTO = P.IDPROSPECTO AND PA2.IDUSUARIO = @IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS A3 WITH(NOLOCK) ON A3.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO != A3.IDUSUARIO
  INNER JOIN <#SESSION.DB/>.dbo.PROSPECTOS_ORIGENES ORI WITH(NOLOCK) ON ORI.IDORIGEN = P.IDORIGEN
  INNER JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES_FASES F WITH(NOLOCK) ON O.IDFASE = F.IDFASE  
  INNER JOIN <#SESSION.DB/>.dbo.USUARIOS U WITH(NOLOCK) ON O.IDUSUARIO = U.IDUSUARIO 
  INNER JOIN <#SESSION.DB/>.dbo.EMPRESAS_LINEAS_PRODUCTO LP WITH(NOLOCK) ON O.IDLINEA_PRODUCTO = LP.IDLINEA_PRODUCTO 
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS_SEGUIMIENTO S WITH(NOLOCK) ON O.IDULTIMOSEGUIMIENTO = S.IDSEGUIMIENTO 
  LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U1 WITH(NOLOCK) ON S.IDUSUARIO = U1.IDUSUARIO
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CERTEZAS EC WITH(NOLOCK) ON EC.IDEMPRESA = P.IDEMPRESA AND EC.CERTEZA = (O.CERTEZA*100)
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP21 WITH(NOLOCK) ON CP21.IDOPCION = P.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP22 WITH(NOLOCK) ON CP22.IDOPCION = P.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP23 WITH(NOLOCK) ON CP23.IDOPCION = P.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP24 WITH(NOLOCK) ON CP24.IDOPCION = P.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CP25 WITH(NOLOCK) ON CP25.IDOPCION = P.CAMPO25
  
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CPO21 WITH(NOLOCK) ON CPO21.IDOPCION = O.CAMPO21
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CPO22 WITH(NOLOCK) ON CPO22.IDOPCION = O.CAMPO22
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CPO23 WITH(NOLOCK) ON CPO23.IDOPCION = O.CAMPO23
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CPO24 WITH(NOLOCK) ON CPO24.IDOPCION = O.CAMPO24
  LEFT JOIN <#SESSION.DB/>.dbo.EMPRESAS_CAMPOS_OPCIONES CPO25 WITH(NOLOCK) ON CPO25.IDOPCION = O.CAMPO25
  
  LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS COM WITH(NOLOCK) ON COM.IDCOMPANIA = P.IDCOMPANIA

  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP1 WITH(NOLOCK) ON CatP1.IDCATALOGOOPCION = P.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP2 WITH(NOLOCK) ON CatP2.IDCATALOGOOPCION = P.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatP3 WITH(NOLOCK) ON CatP3.IDCATALOGOOPCION = P.IDCATALOGOOPCION3      

  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatO1 WITH(NOLOCK) ON CatO1.IDCATALOGOOPCION = O.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatO2 WITH(NOLOCK) ON CatO2.IDCATALOGOOPCION = O.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatO3 WITH(NOLOCK) ON CatO3.IDCATALOGOOPCION = O.IDCATALOGOOPCION3      

  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE1 WITH(NOLOCK) ON CatE1.IDCATALOGOOPCION = COM.IDCATALOGOOPCION1      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE2 WITH(NOLOCK) ON CatE2.IDCATALOGOOPCION = COM.IDCATALOGOOPCION2      
  LEFT JOIN <#SESSION.DB/>.DBO.CATALOGOS_OPCIONES CatE3 WITH(NOLOCK) ON CatE3.IDCATALOGOOPCION = COM.IDCATALOGOOPCION3      

  LEFT JOIN <#SESSION.DB/>.DBO.EMPRESAS_INDUSTRIAS CatI WITH(NOLOCK) ON CatI.IDINDUSTRIA = COM.IDINDUSTRIA      
  LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS_GRUPOS CatG WITH(NOLOCK) ON CatG.IDCOMPANIAGRUPO = COM.IDCOMPANIAGRUPO		      


WHERE 
  P.IDEMPRESA = @IDEMPRESA 
  --AND O.PERDIDA=0
  --AND O.GANADA = 0 
  AND P.DESCARTADO=0
  AND O.IDOPORTUNIDAD IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.DBO.SPLIT(@IDS,'',''))
  
 GROUP BY
O.TKO , P.IdCompania, COM.TkCom, P.IDUSUARIO,P.APELLIDOS, P.NOMBRE,P.PUESTO,P.EMPRESA,P.ETIQUETAS_TXT,P.CORREO,P.TELEFONO, P.TELEFONO2, P.MOVIL,
O.CONCEPTO,
   P.IDPROSPECTO, P.NARCHIVOS, O.IDOPORTUNIDAD, O.NARCHIVOS,  O.IDUSUARIO , PA2.IDUSUARIO,
      P.CAMPO1,P.CAMPO2,P.CAMPO3,P.CAMPO4,P.CAMPO5,P.CAMPO6,P.CAMPO7,P.CAMPO8,P.CAMPO9,P.CAMPO10,
      P.CAMPO11,P.CAMPO12,P.CAMPO13,P.CAMPO14,P.CAMPO15,P.CAMPO16,P.CAMPO17,P.CAMPO18,P.CAMPO19,P.CAMPO20,
  CP21.OPCION ,  CP22.OPCION ,  CP23.OPCION ,  CP24.OPCION ,  CP25.OPCION ,
  CPO21.OPCION, CPO22.OPCION, CPO23.OPCION, CPO24.OPCION, CPO25.OPCION,
  LP.LINEA_PRODUCTO ,  F.Fase, ORI.Origen,  Monto,COMISION_MONTO, O.Certeza, EC.DESCRIPCION , 
  O.FECHA_CIERRE , CAST(S.COMENTARIO  AS VARCHAR(MAX)),S.FECHAHORA, O.IDPROSPECTO,O.FECHAHORA,
  U.Iniciales , U.NOMBRE+'' ''+U.APELLIDOS,COM.IDINDUSTRIA,COM.IDCOMPANIAGRUPO,
  P.CAMPO21, P.CAMPO22, P.CAMPO23, P.CAMPO24, P.CAMPO25,
  P.CAMPO26, P.CAMPO27, P.CAMPO28,
  P.CAMPO29, P.CAMPO30, P.CAMPO31, P.CAMPO32,
  P.CAMPO33, P.CAMPO34,
  O.CAMPO1, O.CAMPO2, O.CAMPO3, O.CAMPO4 ,
  O.CAMPO5, O.CAMPO6, O.CAMPO7, O.CAMPO8,
  O.CAMPO9, O.CAMPO10, O.CAMPO11, O.CAMPO12,
  O.CAMPO13, O.CAMPO14, O.CAMPO15, O.CAMPO16,
  O.CAMPO17, O.CAMPO18, O.CAMPO19, O.CAMPO20,
  O.CAMPO21, O.CAMPO22, O.CAMPO23, O.CAMPO24,
  O.CAMPO25, O.CAMPO26, O.CAMPO27, O.CAMPO28,
  O.CAMPO29, O.CAMPO30, O.CAMPO31, O.CAMPO32,
  O.CAMPO33, O.CAMPO34,CatP1.OPCION , CatP2.OPCION ,CatP3.OPCION ,
  CatO1.OPCION , CatO2.OPCION ,CatO3.OPCION ,
  CatE1.OPCION ,CatE2.OPCION ,CatE3.OPCION , P.Sexo,
   CatI.INDUSTRIA , CatG.COMPANIAGRUPO, p.tkp, P.TKPM, P.CANALIZADOEL, P.USRCANALIZO, P.USRCANALIZADO
  '+@OrderSql+'
'
EXEC(@SQL)