//[u|Text,e|Text,]
--select
DECLARE @IDUSUARIO VARCHAR(16)
DECLARE @IDEJECUTIVO VARCHAR(16)
DECLARE @BD VARCHAR(128)
DECLARE @EMAILEJECUTIVO VARCHAR(128)
DECLARE @U VARCHAR(1000)
DECLARE @E VARCHAR(1000)
SET @U=ISNULL(:U,'')
SET @E=ISNULL(:E,'')
SELECT @IDUSUARIO=  IDUSUARIO, @BD = BD_ACTUAL FROM SALESUP_CT.dbo.USUARIOS  U,  SALESUP_CT.dbo.EMPRESAS E 
 WHERE TKU = @U AND E.IDEMPRESA = U.IDEMPRESA AND TKE = @E
 
IF (@IDUSUARIO IS NOT NULL) AND (@BD IS NOT NULL) 
BEGIN
DECLARE @SQL VARCHAR(8000)

SET @SQL = 'SELECT IDUSUARIO,'''+@U+''' AS U,'''+@E+''' AS E, U.IDEMPRESA,EMAIL,NOMBRE,APELLIDOS,INICIALES,MAILCONFIG,NIVEL,ACTIVO,IDGRUPO,IDCSS,DEFAULT_PAIS,DEFAULT_ESTADO,GMT, E.COMPANIA, E.MAX_USUARIOS, E.EXPIRACION, E.ACTIVA,E.SIN_CONFIGURAR,E.IDUSUARIO_DISTRIBUCION,E.TIPO_LICENCIA,P.LOCALEID,'''
  +@BD+''' AS DB, ISNULL(CONVERTCODE, 103) AS CONVERTCODE, ISNULL(IDDISTRIBUIDOR, 0) AS IDDISTRIBUIDOR, 1 AS IDPRODUCTO, U.PUEDEEXPORTAR FROM '+@BD+'.DBO.USUARIOS U, '+@BD+'.DBO.EMPRESAS E, SALESUP_CT.DBO.PAISES P WHERE U.IDEMPRESA = E.IDEMPRESA AND U.IDUSUARIO='+@IDUSUARIO+' AND ((E.ACTIVA = 1 AND U.ACTIVO = 1) OR (U.NIVEL = 1 AND ACTIVA = 0)) AND U.DEFAULT_PAIS = P.IDPAIS'
EXEC (@SQL)
END
ELSE
  SELECT * FROM SALESUP_CT.DBO.USUARIOS WHERE IDUSUARIO = 0