//[session.db|Untyped,session.idempresa|Untyped,session.nivel|Untyped,]
 SELECT DATEDIFF(d, GETDATE(), EXPIRACION) AS DIASDEMO
 FROM 
   <#SESSION.DB/>.dbo.EMPRESAS E WITH(NOLOCK)   LEFT JOIN 
    CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION EF WITH(NOLOCK)  ON E.IDEMPRESA = EF.IDEMPRESA  AND EF.IDPRODUCTO = 1
 WHERE E.IDEMPRESA = <#SESSION.IDEMPRESA/> AND <#SESSION.NIVEL/> = 1   
 AND DATEDIFF(d, GETDATE(), EXPIRACION)  < 15 --AND FORMA_PAGO = 3
 AND ISNULL ((SELECT TOP 1 FORMA_PAGO FROM CONTROL.VENTAS.DBO.EMPRESA_DATOS_FACTURACION WITH(NOLOCK) WHERE IDPRODUCTO = 1 AND IDEMPRESA = <#SESSION.IDEMPRESA/>),0)<>2     
  
 