//[session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,]
--select
DECLARE @FECHA_HOY DATETIME
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
SET @FECHA_HOY = <#SESSION.DB/>.DBO.GETONLYDATE(GETDATE())
SET @IDEMPRESA = <#SESSION.IDEMPRESA>
SET @IDUSUARIO  = <#SESSION.IDUSUARIO/>


SELECT 1 AS NO,'Baja' as Rango, ISNULL(SUM (O.MONTO),0) as TOTAL,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE < @FECHA_HOY THEN O.MONTO ELSE 0 END),0) AS VENCIDO,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY AND @FECHA_HOY+30 THEN O.MONTO ELSE 0 END),0) AS DIAS_30,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+31 AND @FECHA_HOY+60 THEN O.MONTO ELSE 0 END),0) AS DIAS_60,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+61 AND @FECHA_HOY+90 THEN O.MONTO ELSE 0 END),0) AS DIAS_90,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE > @FECHA_HOY+91 THEN O.MONTO ELSE 0 END),0) AS MAS_90
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,8,0) UL,<#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.USUARIOS U
WHERE O.GANADA=0 AND O.PERDIDA=0 AND O.IDPROSPECTO=P.IDPROSPECTO AND P.IDUSUARIO = U.IDUSUARIO  AND 
P.IDEMPRESA=@IDEMPRESA AND CERTEZA < 0.34 
AND UL.ID=U.IDUSUARIO 

UNION

SELECT 2,'Media' as Rango, ISNULL(SUM (O.MONTO),0) as TOTAL,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE < @FECHA_HOY THEN O.MONTO ELSE 0 END),0) AS VENCIDO,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY AND @FECHA_HOY+30 THEN O.MONTO ELSE 0 END),0) AS DIAS_30,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+31 AND @FECHA_HOY+60 THEN O.MONTO ELSE 0 END),0) AS DIAS_60,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+61 AND @FECHA_HOY+90 THEN O.MONTO ELSE 0 END),0) AS DIAS_90,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE > @FECHA_HOY+91 THEN O.MONTO ELSE 0 END),0) AS MAS_90
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,8,0) UL,<#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P , <#SESSION.DB/>.DBO.USUARIOS U
WHERE O.GANADA=0 AND O.PERDIDA=0 AND O.IDPROSPECTO=P.IDPROSPECTO  AND P.IDUSUARIO = U.IDUSUARIO AND P.IDEMPRESA=@IDEMPRESA
AND CERTEZA>=0.34 AND CERTEZA<0.66 
AND UL.ID=U.IDUSUARIO



UNION

SELECT 3,'Alta' as Rango, ISNULL(SUM (O.MONTO),0) as TOTAL,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE < @FECHA_HOY THEN O.MONTO ELSE 0 END),0) AS VENCIDO,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY AND @FECHA_HOY+30 THEN O.MONTO ELSE 0 END),0) AS DIAS_30,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+31 AND @FECHA_HOY+60 THEN O.MONTO ELSE 0 END),0) AS DIAS_60,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE BETWEEN @FECHA_HOY+61 AND @FECHA_HOY+90 THEN O.MONTO ELSE 0 END),0) AS DIAS_90,
   ISNULL (SUM(CASE WHEN  O.FECHA_CIERRE > @FECHA_HOY+91 THEN O.MONTO ELSE 0 END),0) AS MAS_90

FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (@IDUSUARIO,8,0) UL,<#SESSION.DB/>.DBO.OPORTUNIDADES O, <#SESSION.DB/>.DBO.PROSPECTOS P, <#SESSION.DB/>.DBO.USUARIOS U
WHERE O.GANADA=0 AND O.PERDIDA=0 AND O.IDPROSPECTO=P.IDPROSPECTO  AND P.IDUSUARIO = U.IDUSUARIO 
AND P.IDEMPRESA=@IDEMPRESA AND CERTEZA >= 0.66 
AND UL.ID=U.IDUSUARIO


ORDER BY 1 DESC