//[session.db|Untyped,session.idempresa|Untyped,session.idgrupo|Untyped,session.nivel|Untyped,]
--
DECLARE @IDGRUPO INT
DECLARE @NIVEL INT
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @NIVEL = <#SESSION.NIVEL/>

IF (@NIVEL=1)
  BEGIN
	 SELECT G.GRUPO, G.IDUSUARIOGRUPO
	 FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON G.IDUSUARIOGRUPO = U.IDGRUPO
	 WHERE G.IDEMPRESA = <#SESSION.IDEMPRESA/> AND U.IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDUSUARIO = U.IDUSUARIO)
	 GROUP BY G.IDUSUARIOGRUPO, G.GRUPO ORDER BY G.GRUPO
  END
ELSE
  BEGIN
	 SELECT G.GRUPO, G.IDUSUARIOGRUPO
	 FROM <#SESSION.DB/>.DBO.USUARIOS_GRUPOS G
	 LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON G.IDUSUARIOGRUPO = U.IDGRUPO
	 WHERE G.IDEMPRESA = <#SESSION.IDEMPRESA/> AND U.IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDUSUARIO = U.IDUSUARIO) AND G.IDUSUARIOGRUPO=@IDGRUPO
	 GROUP BY G.IDUSUARIOGRUPO, G.GRUPO ORDER BY G.GRUPO
  END
