//[session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
--select
SELECT G.GRUPO, G.IDUSUARIOGRUPO, CAST(TK AS VARCHAR(256)) AS TKGRUPO
FROM <#SESSION.DB/>.DBO.ObtieneUsuariosAutorizadosModulos (<#SESSION.IDUSUARIO/>,8,0) UL,<#SESSION.DB/>.DBO.USUARIOS_GRUPOS G
LEFT JOIN <#SESSION.DB/>.DBO.USUARIOS U ON G.IDUSUARIOGRUPO = U.IDGRUPO
WHERE U.IDUSUARIO=UL.ID AND G.IDEMPRESA = <#SESSION.IDEMPRESA/> 
AND U.IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.DBO.OPORTUNIDADES WHERE IDUSUARIO = U.IDUSUARIO)
GROUP BY G.IDUSUARIOGRUPO, G.GRUPO, TK ORDER BY G.GRUPO